{
 "title": "CI",
 "tags": [ "ci" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "runner_prometheus_job",
    "label": "Runner Prometheus Job",
    "query": "gitlab_runner_version_info{job=~\".*\"}"
   },
   {
    "name": "runner_managers",
    "label": "Runner Managers",
    "query": "query_result(label_replace(gitlab_runner_version_info{job=~\"$runner_prometheus_job\"}, \"fqdn\", \"$1.*\", \"instance\", \"(.*):[0-9]+$\"))"
   },
   { "name": "has_minutes", "label": "Has Shared Runners Minutes", "query": "yes,no" },
   {
    "name": "runner_job_failure_reason",
    "label": "Job failure reason",
    "query": "label_values(gitlab_runner_failed_jobs_total, failure_reason)"
   }
  ]
 },
 "panels": [
  {
   "title": "Started jobs",
   "type": "singlestat",
   "description": "Total of jobs that were started",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(gitlab_runner_jobs_total[$__range]))"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ci_pending_builds{shared_runners=\"yes\",has_minutes=~\"$has_minutes\"}) or vector(0)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "pending jobs for project with shared runners enabled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(ci_pending_builds{shared_runners=\"no\",has_minutes=~\"$has_minutes\"}) or vector(0)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "pending jobs for project without shared runners enabled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(ci_running_builds{has_minutes=~\"$has_minutes\"}) or vector(0)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "running jobs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(ci_stale_builds) or vector(0)",
     "legendFormat": "stale jobs"
    }
   ]
  },
  {
   "title": "Job minutes",
   "type": "singlestat",
   "description": "Total number of job minutes",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(gitlab_runner_job_duration_seconds_sum{instance=~\"${runner_managers:pipe}\"}[$__range])) / 60",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs by Runner's state, stage and executor_stage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs by Runner's state",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Jobs running by Runner's stage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (stage)",
       "legendFormat": "{{stage}}"
      }
     ]
    },
    {
     "title": "Jobs by Runner's executor_stage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (executor_stage)",
       "legendFormat": "{{executor_stage}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runner limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Concurrent by Prometheus job",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (job) / sum(gitlab_runner_concurrent{instance=~\"${runner_managers:pipe}\"}) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Concurrent by instance",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (instance) / sum(gitlab_runner_concurrent{instance=~\"${runner_managers:pipe}\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs failures on Runners",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs failures on Runners (by instance)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(gitlab_runner_failed_jobs_total{instance=~\"${runner_managers:pipe}\",failure_reason=~\"$runner_job_failure_reason\"}[1m])) by (instance, failure_reason)",
       "legendFormat": "{{instance}} - {{failure_reason}}"
      },
      {
       "expr": "AVG(irate(gitlab_runner_failed_jobs_total{instance=~\"${runner_managers:pipe}\",failure_reason=~\"$runner_job_failure_reason\"}[1m]))",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Jobs Origin",
     "type": "graph",
     "description": "What triggered the job, and how many of these are there?",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ci_running_builds{triggered=\"yes\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Triggered",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(ci_running_builds{scheduled=\"yes\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Scheduled",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(ci_running_builds{mirror=\"yes\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Mirroring",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(ci_running_builds{mirror=\"no\",triggered=\"no\",scheduled=\"no\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Push",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "jobs distribution by runner",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ci_running_builds{has_minutes=~\"$has_minutes\"}) by (runner)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "runner {{runner}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Runners errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runners error 5m rate (by instance&level)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gitlab_runner_errors_total{instance=~\"${runner_managers:pipe}\"}[5m])) by (instance,level)",
       "legendFormat": "{{instance}}: {{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runners uptime & version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runners uptime",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{instance=~\"${runner_managers:pipe}\",job=~\"${runner_prometheus_job}\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Runner versions",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "gitlab_runner_version_info{instance=~\"${runner_managers:pipe}\"}",
       "legendFormat": "{{instance}}: {{version}} ({{revision}})"
      }
     ]
    }
   ]
  }
 ]
}