{
 "title": "GitLab Omnibus - NFS mountstats",
 "description": "node_exporter NFS mountstats",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_mountstats_nfs_age_seconds_total, instance)"
   },
   {
    "name": "export",
    "query": "label_values(node_mountstats_nfs_age_seconds_total{instance=\"$instance\"}, export)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Receive/Send Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes recieved(-) / send(+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_mountstats_nfs_operations_received_bytes_total{instance=\"$instance\",export=\"$export\"}[$__interval])) by (export)",
     "legendFormat": "Received - {{export}}"
    },
    {
     "expr": "sum(rate(node_mountstats_nfs_operations_sent_bytes_total{instance=\"$instance\",export=\"$export\"}[$__interval])) by (export)",
     "legendFormat": "Sent - {{export}}"
    }
   ]
  },
  {
   "title": "Average Queue Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "Response time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_mountstats_nfs_operations_queue_time_seconds_total{instance=\"$instance\",export=\"$export\"}[$__interval])) by (export)\n/\nsum(rate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\",export=\"$export\"}[$__interval])) by (export)",
     "legendFormat": "{{export}} "
    }
   ]
  },
  {
   "title": "Requests Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "reqps", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\",export=\"$export\"}[$__interval])) by (export)",
     "legendFormat": "Requests - {{export}}"
    },
    {
     "expr": "sum(rate(node_mountstats_nfs_operations_transmissions_total{instance=\"$instance\",export=\"$export\"}[$__interval])) by (export)",
     "legendFormat": "Transmissions - {{export}}"
    },
    {
     "expr": "sum(rate(node_mountstats_nfs_major_timeouts_total{instance=\"$instance\",export=\"$export\"}[$__interval])) by (export)",
     "legendFormat": "Major timeouts - {{export}}"
    }
   ]
  },
  {
   "title": "Average Response/Request Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s", "label": "Response time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_mountstats_nfs_operations_response_time_seconds_total{instance=\"$instance\",export=\"$export\"}[$__interval])) by (export)\n/\nsum(rate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\",export=\"$export\"}[$__interval])) by (export)",
     "legendFormat": "Response time - {{export}}"
    },
    {
     "expr": "sum(rate(node_mountstats_nfs_operations_request_time_seconds_total{instance=\"$instance\",export=\"$export\"}[$__interval])) by (export)\n/\nsum(rate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\",export=\"$export\"}[$__interval])) by (export)",
     "legendFormat": "Request time - {{export}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive/Send",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes recieved(-) / send(+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_mountstats_nfs_operations_received_bytes_total{instance=\"$instance\",export=\"$export\"}[$__interval])",
       "legendFormat": "Received - {{operation}}"
      },
      {
       "expr": "rate(node_mountstats_nfs_operations_sent_bytes_total{instance=\"$instance\",export=\"$export\"}[$__interval])",
       "legendFormat": "Sent - {{operation}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "reqps", "label": "Requests" }
     ],
     "targets": [
      {
       "expr": "rate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s", "label": "Response time" }
     ],
     "targets": [
      {
       "expr": "rate(node_mountstats_nfs_operations_response_time_seconds_total{instance=\"$instance\",export=\"$export\"}[$__interval])\n/\nrate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\",export=\"$export\"}[$__interval]) > 0",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Requests time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "s", "label": "Request time" }
     ],
     "targets": [
      {
       "expr": "rate(node_mountstats_nfs_operations_request_time_seconds_total{instance=\"$instance\",export=\"$export\"}[$__interval])\n/\nrate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\",export=\"$export\"}[$__interval]) > 0",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Transmissions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "ops", "label": "Transmissions" }
     ],
     "targets": [
      {
       "expr": "rate(node_mountstats_nfs_operations_transmissions_total{instance=\"$instance\",export=\"$export\"}[$__interval])",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Queue time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "s", "label": "Queue time" }
     ],
     "targets": [
      {
       "expr": "rate(node_mountstats_nfs_operations_queue_time_seconds_total{instance=\"$instance\",export=\"$export\"}[$__interval])\n/\nrate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\",export=\"$export\"}[$__interval]) > 0",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Major timeouts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "ops", "label": "Major timeouts" }
     ],
     "targets": [
      {
       "expr": "rate(node_mountstats_nfs_operations_major_timeouts_total{instance=\"$instance\",export=\"$export\"}[$__interval])",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}