{
 "title": "GitLab Omnibus - NGINX VTS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_vts_upstream_response_seconds_total[$__interval])) > 0"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Server - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_vts_server_bytes_total[$__interval])",
     "legendFormat": "{{direction}}-{{host}} / {{instance}}"
    }
   ]
  },
  {
   "title": "Upstream - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_vts_upstream_bytes_total[$__interval])",
     "legendFormat": "{{direction}}-{{backend}}-{{upstream}} / {{instance}}"
    }
   ]
  },
  { "title": "Requests by HTTP code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Server - Requests by HTTP code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_vts_server_requests_total[5m])",
     "legendFormat": "{{code}} {{host}}"
    }
   ]
  },
  {
   "title": "Upstream - Requests by HTTP code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_vts_upstream_requests_total[5m])",
     "legendFormat": "{{code}} {{backend}} {{upstream }}"
    }
   ]
  }
 ]
}