{
 "title": "GitLab Omnibus - Praefect",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(gitaly_praefect_read_distribution,instance)"
   },
   {
    "name": "virtual_storage",
    "label": "Virtual storage",
    "query": "label_values(gitaly_praefect_read_distribution{instance=\"${instance}\"},virtual_storage)"
   }
  ]
 },
 "panels": [
  {
   "title": "Praefect RPC Success/Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_method)(rate(grpc_server_handled_total{job=\"praefect\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "Error[{{grpc_method}}]"
    },
    {
     "expr": "sum by (grpc_method)(rate(grpc_server_handled_total{job=\"praefect\",grpc_code=\"OK\"}[5m]))",
     "legendFormat": "Success[{{grpc_method}}]"
    },
    {}
   ]
  },
  {
   "title": "Total Replication Jobs In Flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitaly_praefect_replication_jobs) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Praefect Gitaly Node Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitaly_praefect_node_last_healthcheck_up",
     "legendFormat": "{{instance}}[{{gitaly_storage}}]"
    }
   ]
  },
  {
   "title": "Replication Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_praefect_replication_latency_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(gitaly_praefect_replication_latency_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gitaly_praefect_replication_latency_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Virtual Storage Primary Flapping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitaly_praefect_primaries",
     "legendFormat": "{{instance}}[{{gitaly_storage}}]"
    }
   ]
  },
  {
   "title": "Replication Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_praefect_replication_delay_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(gitaly_praefect_replication_delay_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gitaly_praefect_replication_delay_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Shard Primary Election",
   "type": "table",
   "description": "Shows the currently elected primary for the shard (virtual storage)\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "gitaly_praefect_primaries > 0" },
    {
     "expr": "max(gitaly_praefect_read_only_mode) by (virtual_storage)"
    }
   ]
  },
  {
   "title": "Distribution of reads",
   "type": "graph",
   "description": "It shows distribution of the read operations across the Gitaly nodes that are in up-to-date state. Distribution happens between nodes of a single virtual storage. Reads issues to one virtual storage won't be distributed to Gitaly nodes of another virtual storage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(storage) (rate(gitaly_praefect_read_distribution{job=\"praefect\",instance=\"${instance}\",virtual_storage=\"${virtual_storage}\"}[5m]))",
     "legendFormat": "Gitaly: {{storage}}"
    }
   ]
  }
 ]
}