{
 "title": "GitLab Omnibus - Redis",
 "description": "GitLab Omnibus dashboard for Redis servers",
 "tags": [ "redis" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{job=\"redis\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - redis_start_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_connected_clients{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Commands Executed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=\"$instance\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Hits, Misses per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_keyspace_hits_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "hits"
    },
    {
     "expr": "rate(redis_keyspace_misses_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=\"$instance\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_config_maxmemory{instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=\"$instance\"}[$__interval]))",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=\"$instance\"}[$__interval])",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_command_call_duration_seconds_count{instance=\"$instance\"}[$__interval]) > 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys{instance=\"$instance\"}) - sum(redis_db_keys_expiring{instance=\"$instance\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum(redis_db_keys_expiring{instance=\"$instance\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (db) (redis_db_keys{instance=\"$instance\"})",
     "legendFormat": "{{ db }} "
    }
   ]
  }
 ]
}