{
 "title": "GitLab Omnibus - Service Platform Metrics",
 "tags": [
  "managed",
  "general",
  "general"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Node",
    "query": "label_values(up{job=\"node\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "🏅 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of the most saturated component of the service. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "\n        max(\n          max_over_time(\n            gitlab_sli:gitlab_service_saturation:ratio[$__interval]\n          )\n        ) by (component)\n        ",
     "legendFormat": "{{component}} saturation"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "graph",
   "description": "Availability measures the ratio of component processes in the service that are currently healthy and able to handle requests. The closer to 100% the better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability %" }
   ],
   "targets": [
    {
     "expr": "\n        min(\n          min_over_time(\n            gitlab_sli:job:availability:ratio[$__interval]\n          )\n        ) by (job)\n        ",
     "legendFormat": "{{ job }} service"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "\n      max(\n        max_over_time(\n          gitlab_sli:gitlab_component_errors:ratio[$__interval]\n        )\n      ) by (job)\n      ",
     "legendFormat": "{{ job }} service"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "\n        max(\n          avg_over_time(\n            gitlab_sli:code_method_route:workhorse_http_request_count:rate1m[$__interval]\n          ) \n        ) \n          ",
     "legendFormat": "gitlab-workhorse"
    }
   ]
  },
  { "title": "🖥️ Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Node CPU",
   "type": "graph",
   "description": "The amount of non-idle time consumed by nodes for this service",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit", "label": "Average CPU Utilization" }
   ],
   "targets": [
    {
     "expr": "avg(1 - rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"($instance):9100\"}[$__interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node Maximum Single Core Utilization",
   "type": "graph",
   "description": "The maximum utilization of a single core on each node. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(\n          max(1 - rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"($instance):9100\"}[$__interval])) by (instance)\n        ,1),0)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node Network Utilization",
   "type": "graph",
   "description": "Network utilization for nodes for this service",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "\n          sum(rate(node_network_transmit_bytes_total{instance=~\"($instance):9100\"}[$__interval])) by (instance)\n          ",
     "legendFormat": "send {{ instance }}"
    },
    {
     "expr": "\n          sum(rate(node_network_receive_bytes_total{instance=~\"($instance):9100\"}[$__interval])) by (instance)\n          ",
     "legendFormat": "receive {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "Memory utilization. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(\n        1 -\n        (\n          (\n            node_memory_MemFree_bytes{instance=~\"($instance):9100\"} +\n            node_memory_Buffers_bytes{instance=~\"($instance):9100\"} +\n            node_memory_Cached_bytes{instance=~\"($instance):9100\"}\n          )\n        )\n        /\n        node_memory_MemTotal_bytes{instance=~\"($instance):9100\"}\n      ,1),0)",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  }
 ]
}