{
 "title": "GitLab Kubernetes Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "User Authentications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_auth_user_authenticated_total)",
     "legendFormat": "Total user authentications"
    },
    {
     "expr": "sum(gitlab_auth_user_password_invalid_total)",
     "legendFormat": "Invalid password attempts"
    }
   ]
  },
  {
   "title": "HTTP requests rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method)(rate(http_requests_total[5m])) ",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sidekiq_queue_size) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "PostgreSQL dead tuple rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table_name)(rate(gitlab_database_stat_table_n_dead_tup[5m]))",
     "legendFormat": "{{ table_name }}"
    }
   ]
  }
 ]
}