{
 "title": "2019-11-14",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "🗞️ Headline Metrics - 𝘦𝘹𝘱𝘢𝘯𝘥 𝘬𝘦𝘺 𝘴𝘦𝘳𝘷𝘪𝘤𝘦 𝘮𝘦𝘵𝘳𝘪𝘤𝘴 𝘳𝘰𝘸 𝘧𝘰𝘳 𝘥𝘦𝘵𝘢𝘪𝘭𝘴",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"web\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"web\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"web\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"$stage\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"$stage\"}\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"$stage\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"$stage\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"\"}\n",
     "legendFormat": "upper normal (legacy)"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal (legacy)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "👩‍⚕️ Service Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "7d Latency SLA",
     "type": "singlestat",
     "description": "Percentage time the latency SLI for this service is within SLO",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(avg_over_time(slo_observation_status{slo=\"apdex_ratio\", environment=\"$environment\", type=\"web\", stage=\"$stage\"}[7d]))\n"
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "sort(\n  max(\n  ALERTS{environment=\"$environment\", type=\"web\", stage=~\"|$stage\", severity=\"s1\", alertstate=\"firing\"} * 4\n  or\n  ALERTS{environment=\"$environment\", type=\"web\", stage=~\"|$stage\", severity=\"s2\", alertstate=\"firing\"} * 3\n  or\n  ALERTS{environment=\"$environment\", type=\"web\", stage=~\"|$stage\", severity=\"s3\", alertstate=\"firing\"} * 2\n  or\n  ALERTS{environment=\"$environment\", type=\"web\", alertstate=\"firing\"}\n  ) by (alertname, severity)\n)\n"
      }
     ]
    },
    {
     "title": "7d Error Rate SLA",
     "type": "singlestat",
     "description": "Percentage time the error ratio SLI for this service is within SLO",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg_over_time(slo_observation_status{slo=\"error_ratio\", environment=\"$environment\", type=\"web\", stage=\"$stage\"}[7d])\n"
      }
     ]
    }
   ]
  },
  { "title": "Workhorse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "p50 Overall Latency Estimate",
   "type": "graph",
   "description": "p50 Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\"}\n  ) by (le))\n",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  {
   "title": "p90 Latency Estimate per Route",
   "type": "graph",
   "description": "90th percentile Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  histogram_quantile(\n    0.9,\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n        environment=\"$environment\",\n        type=\"web\",\n        stage=\"$stage\"}\n    ) by (route, le)),\n\"route\", \"none\", \"route\", \"\")\n",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  {
   "title": "p50 Latency Estimate per Route",
   "type": "graph",
   "description": "Median Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  histogram_quantile(\n    0.5,\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n        environment=\"$environment\",\n        type=\"web\",\n        stage=\"$stage\"}\n    ) by (route, le)),\n\"route\", \"none\", \"route\", \"\")\n",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "description": "Total Requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\",\n      le=\"+Inf\"}\n)\n",
     "legendFormat": "{{ code_class }}"
    }
   ]
  },
  {
   "title": "Requests by Status Class",
   "type": "graph",
   "description": "Requests by Status Class",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n          environment=\"$environment\",\n          type=\"web\",\n          stage=\"$stage\",\n          le=\"+Inf\"}\n    ) by (code),\n  \"code_class\", \"${1}XX\", \"code\", \"(.).*\")\n) by (code_class)\n",
     "legendFormat": "{{ code_class }}"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "graph",
   "description": "Requests by Status Code",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\",\n      le=\"+Inf\"}\n) by (code)\n",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Requests by Route",
   "type": "graph",
   "description": "Requests by Route",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n          environment=\"$environment\",\n          type=\"web\",\n          stage=\"$stage\",\n          le=\"+Inf\"}\n    ) by (route),\n  \"route\", \"none\", \"route\", \"\")\n) by (route)\n",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  { "title": "Unicorn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Active Unicorn Workers for Service",
   "type": "graph",
   "description": "The number of unicorn workers actively processing a request. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  unicorn_active_connections{\n    environment=\"$environment\",\n    type=\"web\",\n    stage=\"$stage\"}\n) by (type)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Active Unicorn Workers by Node",
   "type": "graph",
   "description": "The number of unicorn workers actively processing a request. Lower is better. Outliers may indicate a problem with a single node in the fleet.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  unicorn_active_connections{\n    environment=\"$environment\",\n    type=\"web\",\n    stage=\"$stage\"}\n) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Queued Unicorn Requests for Service",
   "type": "graph",
   "description": "The number of http requests actively waiting for an available unicorn. Zero is good, anything higher means clients are waiting.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job:unicorn_queued_connections:sum{\n    environment=\"$environment\",\n    type=\"web\",\n    stage=\"$stage\"}\n) by (type)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Queued Unicorn Requests per Node",
   "type": "graph",
   "description": "The number of http requests actively waiting for an available unicorn. Zero is good, anything higher means clients are waiting. Outliers may indicate a problem with a single node in the fleet.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  unicorn_queued_connections{\n    environment=\"$environment\",\n    type=\"web\",\n    stage=\"$stage\"}\n) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Unicorn Kills for Service",
   "type": "graph",
   "description": "The number of unicorn processes terminated after 60s timeout. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  changes(\n    unicorn_killer_terminations_total{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\"\n    }[$__interval])\n) by (type)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Unicorn Kills per Node",
   "type": "graph",
   "description": "The number of unicorn processes terminated after 60s timeout. Lower is better. Outliers may indicate a faulty node.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  changes(\n    unicorn_killer_terminations_total{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\"\n    }[$__interval])\n) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  { "title": "Rails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "p95 Latency Estimate",
   "type": "graph",
   "description": "95th percentile Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,\n  sum(job_environment:gitlab_transaction_duration_seconds_bucket:rate5m{\n    environment=\"$environment\",\n    type=\"web\",\n    stage=\"$stage\"\n  }) by (le, job)\n)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Rails Total Time",
   "type": "graph",
   "description": "Seconds of Rails processing, per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job_environment:gitlab_transaction_duration_seconds_sum:rate1m{\n    environment=\"$environment\",\n    type=\"web\",\n    stage=\"$stage\"}\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Rails Queue Time",
   "type": "graph",
   "description": "Time spend waiting for a rails worker",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    gitlab_transaction_rails_queue_duration_total{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\"}\n      [$__interval]\n  )\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Total SQL Time",
   "type": "graph",
   "description": "Total seconds spent doing SQL processing, per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job_environment:gitlab_sql_duration_seconds_bucket:rate1m{\n    environment=\"$environment\",\n    type=\"web\",\n    stage=\"$stage\"}\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "graph",
   "description": "Cache Operations per Second",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    gitlab_cache_operations_total{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\"}[$__interval]\n  )\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "gitlab-rails Process restarts",
   "type": "graph",
   "description": "The number of times this process restarted in a given period, including children workers. Restarts are associated with poor client experience, so lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short", "label": "Process restarts" }
   ],
   "targets": [
    {
     "expr": "sum(\n  changes(\n    ruby_process_start_time_seconds{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\",\n      job=\"gitlab-rails\"\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "process restarts"
    }
   ]
  },
  {
   "title": "Database load balancer: average secondary connections per client",
   "type": "graph",
   "description": "This graph shows the average number of secondary database connections\n        per process. A value of zero indicates that the secondary replicas are unreachable.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short", "label": "Average connections" }
   ],
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(\n    db_load_balancing_hosts{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\"}[$__interval]\n  )\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  { "title": "🏅 Key Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"web\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"web\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Component Availability",
   "type": "graph",
   "description": "Availability measures the ratio of component processes in the service that are currently healthy and able to handle requests. The closer to 100% the better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability %" }
   ],
   "targets": [
    {
     "expr": "min(\n  min_over_time(\n    gitlab_component_availability:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"web\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"$stage\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"$stage\"}\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"$stage\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"$stage\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"\"}\n",
     "legendFormat": "upper normal (legacy)"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal (legacy)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "🔩 Service Component Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "collapsed": true,
   "panels": [
    {
     "title": "Component Latency: Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min(\n  min_over_time(\n    gitlab_component_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
       "legendFormat": "{{ component }} component"
      },
      {
       "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})\n",
       "legendFormat": "SLO"
      }
     ]
    },
    {
     "title": "Component Error Rates - modified scale: (1 + n) log10",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors per Minute" }
     ],
     "targets": [
      {
       "expr": "1 +\n(\n  60 *\n  max(\n    max_over_time(\n      gitlab_component_errors:rate{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n    )\n  ) by (component)\n)\n",
       "legendFormat": "{{ component }} component"
      }
     ]
    },
    {
     "title": "Component Availability",
     "type": "graph",
     "description": "Availability measures the ratio of component processes in the service that are currently healthy and able to handle requests. The closer to 100% the better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Availability %" }
     ],
     "targets": [
      {
       "expr": "min(\n  min_over_time(\n    gitlab_component_availability:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
       "legendFormat": "{{ component }} component"
      }
     ]
    },
    {
     "title": "Component RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "reqps", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "1 +\nmax(\n  avg_over_time(\n    gitlab_component_ops:rate{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
       "legendFormat": "{{ component }} component"
      }
     ]
    },
    {
     "title": "Saturation",
     "type": "graph",
     "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"web\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
       "legendFormat": "{{ component }} component"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "avg(instance:node_cpu_utilization:ratio{type=\"web\", environment=\"$environment\", stage=\"$stage\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{type=\"web\", environment=\"$environment\", stage=\"$stage\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{type=\"web\", environment=\"$environment\", stage=\"$stage\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "sum(rate(node_network_receive_bytes_total{type=\"web\", environment=\"$environment\", stage=\"$stage\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(1 -\n(\n  (\n    node_memory_MemFree_bytes{type=\"web\", environment=\"$environment\", stage=\"$stage\"} +\n    node_memory_Buffers_bytes{type=\"web\", environment=\"$environment\", stage=\"$stage\"} +\n    node_memory_Cached_bytes{type=\"web\", environment=\"$environment\", stage=\"$stage\"}\n  )\n)\n/\nnode_memory_MemTotal_bytes{type=\"web\", environment=\"$environment\", stage=\"$stage\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_reads_completed_total{type=\"web\", environment=\"$environment\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_writes_completed_total{type=\"web\", environment=\"$environment\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_read_bytes_total{type=\"web\", environment=\"$environment\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_written_bytes_total{type=\"web\", environment=\"$environment\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Total Time",
     "type": "graph",
     "description": "Total time spent in read operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_read_time_seconds_total{type=\"web\", environment=\"$environment\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Total Time",
     "type": "graph",
     "description": "Total time spent in write operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_write_time_seconds_total{type=\"web\", environment=\"$environment\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "📆 Capacity Planning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "collapsed": true,
   "panels": [
    {
     "title": "Currently Saturated Resources",
     "type": "table",
     "description": "Lists saturated resources that are breaching their soft SLO thresholds at this instant",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "max by (type, stage, component) (\n  clamp_max(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"web\", stage=~\"|$stage\"}\n    ,\n    1\n  ) >= on(component, monitor, env) group_left slo:max:soft:gitlab_component_saturation:ratio\n)\n"
      }
     ]
    },
    {
     "title": "Resources Currently at Risk of being Saturated",
     "type": "table",
     "description": "Lists saturated resources that, given their current value and weekly variance, have a high probability of breaching their soft thresholds limits within the next few hours",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sort_desc(\n  max by (type, stage, component) (\n    clamp_max(\n      gitlab_component_saturation:ratio:avg_over_time_1w{\n        environment=\"$environment\",\n        type=\"web\", stage=~\"|$stage\"\n      } +\n      2 *\n        gitlab_component_saturation:ratio:stddev_over_time_1w{\n          environment=\"$environment\",\n          type=\"web\", stage=~\"|$stage\"\n        }\n      , 1\n    )\n    >= on(component, monitor, env) group_left slo:max:soft:gitlab_component_saturation:ratio\n  )\n)\n"
      }
     ]
    },
    {
     "title": "Resources Forecasted to be at Risk of Saturation in 14d",
     "type": "table",
     "description": "Lists saturated resources that, given their growth rate over the the past week, and their weekly variance, are likely to breach their soft thresholds limits in the next 14d",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sort_desc(\n  max by (type, stage, component) (\n    clamp_max(\n      gitlab_component_saturation:ratio:predict_linear_2w{\n        environment=\"$environment\",\n        type=\"web\", stage=~\"|$stage\"\n      } +\n      2 *\n        gitlab_component_saturation:ratio:stddev_over_time_1w{\n          environment=\"$environment\",\n          type=\"web\", stage=~\"|$stage\"\n        }\n    , 1\n    )\n    >= on(component, monitor, env) group_left slo:max:soft:gitlab_component_saturation:ratio\n  )\n)\n"
      }
     ]
    },
    {
     "title": "Long-term Resource Saturation",
     "type": "graph",
     "description": "Resource saturation levels for saturation components for this service. Lower is better.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(\n  max(\n    gitlab_component_saturation:ratio{\n      type=\"web\",\n      environment=\"$environment\",\n      stage=~\"|$stage\"\n    }\n  ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "{{ component }}"
      }
     ]
    },
    {
     "title": "Long-term Resource Saturation - Rolling 1w average trend",
     "type": "graph",
     "description": "Percentage of time that resource is within capacity SLOs. Higher is better.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio:avg_over_time_1w{\n        type=\"web\",\n        environment=\"$environment\",\n        stage=~\"$stage|\"\n      }\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "{{ component }}"
      }
     ]
    }
   ]
  }
 ]
}