{
 "title": "2020-01-27 frontend haproxy saturation",
 "time": { "from": "2020-01-27T10:00:00.000Z", "to": "2020-01-27T21:00:00.000Z" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Percentage of all CPU cores/hyperthreads",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "% of all CPUs" }
   ],
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{fqdn=~\"fe-[0-9][0-9]-lb-gprd.*\", mode=\"idle\"}[$__interval])) by (fqdn)",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Established TCP connection count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{fqdn=~\"fe-[0-9][0-9]-lb-gprd.*\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP ActiveOpens/sec: Rate of opening new TCP connections/sec as a client",
   "type": "graph",
   "description": "An \"active open\" refers to the client side of establishing a new TCP connection (i.e. sending the initial TCP SYN).\n\nA \"passive open\" refers to the server side of establishing a new TCP connection (i.e. receiving the initial TCP SYN).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{fqdn=~\"fe-[0-9][0-9]-lb-gprd.*\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP PassiveOpens/sec: Rate of receiving new TCP connections/sec as a server",
   "type": "graph",
   "description": "An \"active open\" refers to the client side of establishing a new TCP connection (i.e. sending the initial TCP SYN).\n\nA \"passive open\" refers to the server side of establishing a new TCP connection (i.e. receiving the initial TCP SYN).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_PassiveOpens{fqdn=~\"fe-[0-9][0-9]-lb-gprd.*\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network throughput: Sent bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"fe-[0-9][0-9]-lb-gprd.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network throughput: Received bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"fe-[0-9][0-9]-lb-gprd.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}