{
 "title": "!21725",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total API requests",
   "type": "graph",
   "description": "Requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(code_method:gitlab_workhorse_http_requests_total:rate1m{type=\"api\", })"
    }
   ]
  },
  {
   "title": "Average API requests per second",
   "type": "graph",
   "description": "Requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(code_method:gitlab_workhorse_http_requests_total:rate1m{type=\"api\", }[30m]))"
    }
   ]
  },
  {
   "title": "pg_stat_database_blk_write_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_write_time[10m])"
    }
   ]
  }
 ]
}