{
 "title": "Product Analytics Service Health (GitLab.com project)",
 "tags": [
  "unmanaged",
  "protected"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "ClickHouse Database Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(ClickHouse_NumberOfDatabases{cluster=\"prd-278964\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Enriched Events Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_events_total{component_id=\"clickhouse_enriched_events\",host=~\"prd-278964-vector-0|prd-278964-vector-1|prd-278964-vector-2\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster_name=\"gitlab-com-278964\",container_name=\"vector\",environment=\"gprd\",severity=\"ERROR\"} |~ \"WARN\"[$__interval])) by (pod_name)"
    }
   ]
  },
  {
   "title": "Vector Bad Events Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_events_total{component_id=\"clickhouse_bad_events\",host=~\"prd-278964-vector-0|prd-278964-vector-1|prd-278964-vector-2\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cube API Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster_name=\"gitlab-com-278964\",container_name=\"cube-api\",environment=\"gprd\"}[$__interval])) by (pod_name)"
    }
   ]
  },
  {
   "title": "Configurator logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{container_name=\"snowplow-configurator\"} != `/healthz`"
    }
   ]
  },
  {
   "title": "Vector Error Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{cluster_name=\"gitlab-com-278964\",container_name=\"vector\",environment=\"gprd\",severity=\"ERROR\"} |~ \"WARN\""
    }
   ]
  },
  {
   "title": "Cube Error Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{cluster_name=\"gitlab-com-278964\",container_name=\"cube-api\",environment=\"gprd\"}"
    }
   ]
  }
 ]
}