{
 "title": "ci-runners: Docker Machine to Autoscaler migration",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6818900265 at Thu May  9 19:10:34 UTC 2024",
 "tags": [
  "managed",
  "ci-runners",
  "type:ci-runners",
  "managed"
 ],
 "time": { "from": "now-12h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "type",
    "query": "label_values(gitlab_runner_version_info{job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", environment=\"$environment\"}, type)\n"
   },
   {
    "name": "shard",
    "query": "label_values(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",type=~\"$type\",shard!=\"default\"}, shard)\n"
   },
   {
    "name": "runner_manager",
    "query": "query_result(label_replace(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",shard=~\"$shard\"}, \"fqdn\", \"$1.*\", \"instance\", \"([^:]*)(:[0-9]+)?$\"))\n"
   },
   {
    "name": "dm_instance",
    "query": "query_result(sum by(instance) (gitlab_runner_autoscaling_actions_total{environment=~\"$environment\", stage=~\"$stage\", shard=~\"$shard\"}) > 0)"
   },
   {
    "name": "autoscaler_instance",
    "query": "query_result(sum by(instance) (fleeting_taskscaler_scale_operations_total{environment=~\"$environment\", stage=~\"$stage\", shard=~\"$shard\"}) > 0)"
   }
  ]
 },
 "panels": [
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  },
  {
   "title": "Percent of Taskscaler/Fleeting powered jobs (compared to Docker Machine powered ones)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1000 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (\n  gitlab_runner_jobs{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${autoscaler_instance:pipe}\"}\n)\n/\n(\n  sum(\n    gitlab_runner_jobs{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${autoscaler_instance:pipe}\"}\n  )\n  +\n  sum(\n    gitlab_runner_jobs{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${dm_instance:pipe}\"}\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Jobs started on runners (docker+machine)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(\n    gitlab_runner_jobs_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${dm_instance:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Jobs running on runners (docker+machine)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  gitlab_runner_jobs{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${dm_instance:pipe}\"}\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Jobs failed on runners (docker+machine)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(\n    gitlab_runner_failed_jobs_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${dm_instance:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Pending job queue duration (docker+machine)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(gitlab_runner_job_queue_duration_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${dm_instance:pipe}\"}[$__rate_interval])\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs started on runners (docker-autoscaler)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(\n    gitlab_runner_jobs_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${autoscaler_instance:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Jobs running on runners (docker-autoscaler)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  gitlab_runner_jobs{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${autoscaler_instance:pipe}\"}\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Jobs failed on runners (docker-autoscaler)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(\n    gitlab_runner_failed_jobs_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${autoscaler_instance:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Pending job queue duration (docker-autoscaler)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(gitlab_runner_job_queue_duration_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${autoscaler_instance:pipe}\"}[$__rate_interval])\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}