{
 "title": "5xx Presentation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg,dr" },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "content": "![](https://media.giphy.com/media/l0HlKrB02QY0f1mbm/giphy.gif)\n\n"
  },
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "content": "# Deprecated ⚠️⚠️⚠️⚠️⚠️\n\nThis dashboard is not maintained or officially supported.\n\nPlease consider the following alternatives:\n\n* **[General Public Splashscreen](/d/general-public-splashscreen/general-gitlab-dashboards?orgId=1)**\n* [`frontend` Overview](/d/frontend-main/frontend-overview?orgId=1) - HAProxy\n* [`web` Overview](/d/web-main/frontend-overview?orgId=1) - Web Requests\n* [`api` Overview](/d/api-main/frontend-overview?orgId=1) - API Requests\n* [`git` Overview](/d/git-main/frontend-overview?orgId=1) - Git Requests\n\n\n"
  },
  { "title": "Max 5xx errors / minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "500 Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(stackdriver_gce_instance_logging_googleapis_com_user_haproxy_500)"
    }
   ]
  },
  {
   "title": "502 Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum(stackdriver_gce_instance_logging_googleapis_com_user_haproxy_502)"
    }
   ]
  },
  {
   "title": "503 Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(stackdriver_gce_instance_logging_googleapis_com_user_haproxy_503)"
    }
   ]
  },
  {
   "title": "404 Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(stackdriver_gce_instance_logging_googleapis_com_user_haproxy_404)",
     "legendFormat": "404"
    }
   ]
  },
  {
   "title": "All requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_requests_total[1h]))*60"
    }
   ]
  },
  {
   "title": "5xx Errors at HAProxy",
   "type": "graph",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gce_instance_logging_googleapis_com_user_haproxy_500)",
     "legendFormat": "500"
    },
    {
     "expr": "sum(stackdriver_gce_instance_logging_googleapis_com_user_haproxy_502)",
     "legendFormat": "502"
    },
    {
     "expr": "sum(stackdriver_gce_instance_logging_googleapis_com_user_haproxy_503)",
     "legendFormat": "503"
    }
   ]
  },
  {
   "title": "404 Errors at HAProxy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gce_instance_logging_googleapis_com_user_haproxy_404)",
     "legendFormat": "404"
    }
   ]
  }
 ]
}