{
 "title": "[Draft] Postgres aggregated query performance analysis",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(node_exporter_build_info,type)"
    }
   },
   {
    "name": "fqdn",
    "query": {
     "query": "label_values(node_exporter_build_info{tier=\"db\", type=\"$type\", environment=\"$environment\"},fqdn)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Query Statistics (pg_stat_statements)  from ${__from:date:YYYY-MM-DD HH:mm:ss}   to ${__to:date:YYYY-MM-DD HH:mm:ss}",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (datname, queryid) (delta(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(\n  delta(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__range])\n) by (datname,queryid))  / $__range_s",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (datname, queryid) (delta(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (datname, queryid) (delta(pg_stat_statements_rows{fqdn=\"$fqdn\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (datname, queryid) (delta(pg_stat_statements_wal_records{fqdn=\"$fqdn\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_wal_records{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n  increase(pg_stat_statements_wal_records{fqdn=\"$fqdn\"}[$__range])\n) by (queryid,datname)\n/ ignoring(queryid,datname) group_left\nsum(\n  increase(pg_stat_statements_wal_records{fqdn=\"$fqdn\"}[$__range])\n) by ()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pg_stat_statements",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "pg_stat_statements_calls{fqdn=\"$fqdn\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Statistics (pg_stat_statements)  from ${__from:date:YYYY-MM-DD HH:mm:ss}   to ${__to:date:YYYY-MM-DD HH:mm:ss}",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (datname, queryid) (delta(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(\n  delta(pg_stat_statements_calls{fqdn=\"$fqdn\"}[$__range])\n) by (datname,queryid))  / $__range_s",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (datname, queryid) (delta(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_seconds_total{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (datname, queryid) (delta(pg_stat_statements_rows{fqdn=\"$fqdn\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (datname, queryid) (delta(pg_stat_statements_wal_records{fqdn=\"$fqdn\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (datname, queryid) (delta(pg_stat_statements_wal_records{fqdn=\"$fqdn\"}[$__range]))) / $__range_s",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n  increase(pg_stat_statements_wal_records{fqdn=\"$fqdn\"}[$__range])\n) by (queryid,datname)\n/ ignoring(queryid,datname) group_left\nsum(\n  increase(pg_stat_statements_wal_records{fqdn=\"$fqdn\"}[$__range])\n) by ()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top N by blocks write",
   "type": "table",
   "description": "show pg_stat_statements with sorting by columns option",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top N by calls",
   "type": "table",
   "description": "show pg_stat_statements with sorting by columns option",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top N by total time",
   "type": "table",
   "description": "show pg_stat_statements with sorting by columns option",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top N by mean time",
   "type": "table",
   "description": "show pg_stat_statements with sorting by columns option",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top N by blocks read",
   "type": "table",
   "description": "show pg_stat_statements with sorting by columns option",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top N by physical IO time",
   "type": "table",
   "description": "show pg_stat_statements with sorting by columns option",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top N by WAL generated ",
   "type": "table",
   "description": "show pg_stat_statements with sorting by columns option",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top N by temp files ",
   "type": "table",
   "description": "show pg_stat_statements with sorting by columns option",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top N by CPU time",
   "type": "table",
   "description": "show pg_stat_statements with sorting by columns option",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "irate(pg_stat_statements_calls{fqdn=\"$fqdn\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}