{
 "title": "Product Analytics Service Health (prod-1, primary shared beta cluster)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Configurator error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"snowplow-configurator\", cluster_name=\"prod-1\"} != `/healthz` != `200` !=`404` [$__interval]))"
    }
   ]
  },
  {
   "title": "Configurator logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"snowplow-configurator\", cluster_name=\"prod-1\"} != `/healthz`"
    }
   ]
  },
  {
   "title": "Vector Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster_name=\"prod-1\",container_name=\"vector\",environment=\"gprd\",severity=\"ERROR\"} |~ \"WARN\"[$__interval])) by (pod_name)"
    }
   ]
  },
  {
   "title": "Vector Bad Events Sent",
   "type": "timeseries",
   "description": "Events that failed enrichment/validation still get sent to ClickHouse for debugging. This could be due to a new SDK having issues, or some other failure in the Snowplow pipeline process.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_events_total{component_id=\"clickhouse_bad_events\",host=~\"prod-1-vector-0|prod-1-vector-1|prod-1-vector-2\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Enriched Events Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_events_total{component_id=\"clickhouse_enriched_events\",host=~\"prd-278964-vector-0|prd-278964-vector-1|prd-27896-vector-2\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Error Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{cluster_name=\"prod-1\",container_name=\"vector\",environment=\"gprd\",severity=\"ERROR\"} |~ \"WARN\""
    }
   ]
  },
  {
   "title": "Cube API Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster_name=\"prod-1\",container_name=\"cube-api\",environment=\"gprd\"}[$__interval])) by (pod_name)"
    }
   ]
  },
  {
   "title": "ClickHouse Inserted Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(ClickHouse_InsertedRows{cluster=\"prod-1\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cube Error Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{cluster_name=\"prod-1\",container_name=\"cube-api\",environment=\"gprd\"}"
    }
   ]
  }
 ]
}