{
 "title": "AI Framework",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Llm chat answers by tool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(tool) (rate(gitlab_sli_llm_chat_answers_apdex_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Llm chat answers success ratio",
   "type": "timeseries",
   "description": "Ratio of not-error chat answers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(tool) (rate(gitlab_sli_llm_chat_answers_apdex_success_total[$__rate_interval]))/sum by(tool) (rate(gitlab_sli_llm_chat_answers_apdex_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI requests by provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(client) (rate(gitlab_sli_llm_client_request_apdex_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI requests by provider",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(client) (rate(gitlab_sli_llm_client_request_apdex_success_total[$__rate_interval]))/sum by(client) (rate(gitlab_sli_llm_client_request_apdex_total[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Details about Llm::CompletionWorker",
   "type": "text",
   "description": "Estimated queue time, between when the job is enqueued and executed. Lower is better.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "options": {
    "content": "* [📈 Grafana dashboard for Llm::CompletionWorker](https://dashboards.gitlab.net/d/sidekiq-worker-detail/sidekiq-worker-detail?orgId=1&var-PROMETHEUS_DS=Global&var-environment=gprd&var-stage=main&var-worker=Llm::CompletionWorker)\n"
   },
   "targets": [
    {}
   ]
  }
 ]
}