{
 "title": "Postgres User Table Alerts Primary",
 "tags": [
  "alert-target",
  "gcp"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "fqdn",
    "query": "label_values(pg_stat_user_tables_idx_tup_fetch{type=\"patroni\", env=\"$environment\"}, fqdn)"
   },
   {
    "name": "relname",
    "query": "label_values(pg_stat_user_tables_idx_tup_fetch{type=\"patroni\", env=\"$environment\", fqdn=\"$fqdn\"}, relname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tuple Fetches per Second",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, tier, type, fqdn, relname) (\n  rate(pg_stat_user_tables_idx_tup_fetch{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{relname}}"
    },
    {
     "expr": "increase(pg_stat_user_tables_analyze_count{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}[$__rate_interval])\n",
     "legendFormat": "Analyze {{ relname }}"
    },
    {
     "expr": "increase(pg_stat_user_tables_vacuum_count{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}[$__rate_interval])\n",
     "legendFormat": "Vacuum {{ relname }}"
    }
   ]
  },
  {
   "title": "Tuple Modifies per Second",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, tier, type, fqdn, relname) (\n  rate(pg_stat_user_tables_n_tup_ins{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}[$__rate_interval])\n)\n",
     "legendFormat": "insert {{relname}}"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}[$__rate_interval])\n",
     "legendFormat": "update {{ relname }}"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}[$__rate_interval])\n",
     "legendFormat": "delete {{ relname }}"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_hot_upd{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}[$__rate_interval])\n",
     "legendFormat": "hot update {{ relname }}"
    }
   ]
  },
  {
   "title": "Index Scans per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, tier, type, fqdn, relname) (\n  rate(pg_stat_user_tables_idx_scan{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Index Tuple Fetches per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, tier, type, fqdn, relname) (\n  rate(pg_stat_user_tables_idx_tup_fetch{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Live Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}\n",
     "legendFormat": "Live tuples: {{relname}}"
    }
   ]
  },
  {
   "title": "Dead Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}\n",
     "legendFormat": "Dead tuples: {{relname}}"
    }
   ]
  },
  {
   "title": "Seq Scans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_scan{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}[$__rate_interval])\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Rows returned by seq scans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_tup_read{type=\"patroni\", env=\"$environment\", relname=\"$relname\", fqdn=\"$fqdn\"}[$__rate_interval])\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/alerts/pg_user_tables.jsonnet)\n"
  }
 ]
}
{
 "title": "Postgres User Table Alerts Replicas",
 "tags": [
  "alert-target",
  "gcp"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "relname",
    "query": "label_values(pg_stat_user_tables_idx_tup_fetch{type=\"patroni\", env=\"$environment\"}, relname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tuple Fetches per Second",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, tier, type, fqdn, relname) (\n  rate(pg_stat_user_tables_idx_tup_fetch{type=\"patroni\", env=\"$environment\", relname=\"$relname\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Tuple Modifies per Second",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, tier, type, fqdn, relname) (\n  rate(pg_stat_user_tables_n_tup_ins{type=\"patroni\", env=\"$environment\", relname=\"$relname\"}[$__rate_interval])\n)\n",
     "legendFormat": "insert {{fqdn}}"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd{type=\"patroni\", env=\"$environment\", relname=\"$relname\"}[$__rate_interval])\n",
     "legendFormat": "update {{ fqdn }}"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del{type=\"patroni\", env=\"$environment\", relname=\"$relname\"}[$__rate_interval])\n",
     "legendFormat": "delete {{ fqdn }}"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_hot_upd{type=\"patroni\", env=\"$environment\", relname=\"$relname\"}[$__rate_interval])\n",
     "legendFormat": "hot update {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Index Scans per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, tier, type, fqdn, relname) (\n  rate(pg_stat_user_tables_idx_scan{type=\"patroni\", env=\"$environment\", relname=\"$relname\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Index Tuple Fetches per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, tier, type, fqdn, relname) (\n  rate(pg_stat_user_tables_idx_tup_fetch{type=\"patroni\", env=\"$environment\", relname=\"$relname\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Live Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{type=\"patroni\", env=\"$environment\", relname=\"$relname\"}\n",
     "legendFormat": "Live tuples: {{fqdn}}"
    }
   ]
  },
  {
   "title": "Dead Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{type=\"patroni\", env=\"$environment\", relname=\"$relname\"}\n",
     "legendFormat": "Dead tuples: {{fqdn}}"
    }
   ]
  },
  {
   "title": "Seq Scans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_scan{type=\"patroni\", env=\"$environment\", relname=\"$relname\"}[$__rate_interval])\n",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Rows returned by seq scans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_tup_read{type=\"patroni\", env=\"$environment\", relname=\"$relname\"}[$__rate_interval])\n",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/alerts/pg_user_tables.jsonnet)\n"
  }
 ]
}