{
 "title": "alerts: MWMBR Apdex SLA Monitoring",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/627495291 at Tue Jul  7 14:48:56 UTC 2020",
 "tags": [
  "managed",
  "alerts",
  "alert-target",
  "general"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "type",
    "query": "label_values(gitlab_service_ops:rate{environment=\"$environment\"}, type)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "component",
    "query": "label_values(gitlab_component_ops:rate{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}, component)"
   },
   {
    "name": "proposed_slo",
    "query": "NaN,0.9,0.95,0.99,0.995,0.999,0.9995,0.9999"
   }
  ]
 },
 "panels": [
  {
   "title": "SLO",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(slo:min:events:gitlab_service_apdex:ratio{type=\"$type\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "content": "The Apdex Rate SLO for this service will determine the thresholds (indicated by the dotted lines)\nin the following graphs. Over time, we expect these SLOs to become stricted (more nines) by\nimproving the reliability of our service.\n\n**For more details of this technique, be sure to the Alerting on SLOs chapter of the\n[Google SRE Workbook](https://landing.google.com/sre/workbook/chapters/alerting-on-slos/)**\n"
  },
  {
   "title": "Multi-window, multi-burn-rates",
   "type": "graph",
   "description": "apdex burn rates: higher is better",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(gitlab_component_apdex:ratio_1h{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"},1),0)\n",
     "legendFormat": "1h apdex burn rate"
    },
    {
     "expr": "gitlab_component_apdex:ratio_5m{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"}",
     "legendFormat": "5m apdex burn rate"
    },
    {
     "expr": "1 - (14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{type=\"$type\"})))",
     "legendFormat": "1h apdex burn threshold"
    },
    {
     "expr": "1 - (14.4 * (1 - $proposed_slo))",
     "legendFormat": "Proposed SLO @ 1h burn"
    },
    {
     "expr": "gitlab_component_apdex:ratio_6h{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"}",
     "legendFormat": "6h apdex burn rate"
    },
    {
     "expr": "gitlab_component_apdex:ratio_30m{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"}",
     "legendFormat": "30m apdex burn rate"
    },
    {
     "expr": "1 - (6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{type=\"$type\"})))",
     "legendFormat": "6h apdex burn threshold"
    },
    { "expr": "1 - (6 * (1 - $proposed_slo))", "legendFormat": "Proposed SLO @ 6h burn" }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 100 },
   "content": "# Multi-window, multi-burn-rates\n\nThe alert will fire when both of the green solid series cross the green dotted threshold, or\nboth of the blue solid series cross the blue dotted threshold.\n"
  },
  {
   "title": "Single window, 1h/5m burn-rates",
   "type": "graph",
   "description": "apdex burn rates: higher is better",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(gitlab_component_apdex:ratio_1h{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"},1),0)\n",
     "legendFormat": "1h apdex burn rate"
    },
    {
     "expr": "gitlab_component_apdex:ratio_5m{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"}",
     "legendFormat": "5m apdex burn rate"
    },
    {
     "expr": "1 - (14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{type=\"$type\"})))",
     "legendFormat": "1h apdex burn threshold"
    },
    {
     "expr": "1 - (14.4 * (1 - $proposed_slo))",
     "legendFormat": "Proposed SLO @ 1h burn"
    }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 110 },
   "content": "# Single window, 1h/5m burn-rates\n\nRemoving the 6h/30m burn-rates, this shows the same data over the 1h/5m burn-rates.\n\nThe alert will fire when the solid lines cross the dotted threshold.\n"
  },
  {
   "title": "Single window, 6h/30m burn-rates",
   "type": "graph",
   "description": "apdex burn rates: higher is better",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(gitlab_component_apdex:ratio_6h{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"},1),0)\n",
     "legendFormat": "6h apdex burn rate"
    },
    {
     "expr": "gitlab_component_apdex:ratio_30m{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"}",
     "legendFormat": "30m apdex burn rate"
    },
    {
     "expr": "1 - (6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{type=\"$type\"})))",
     "legendFormat": "6h apdex burn threshold"
    },
    { "expr": "1 - (6 * (1 - $proposed_slo))", "legendFormat": "Proposed SLO @ 6h burn" }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 120 },
   "content": "# Single window, 6h/30m burn-rates\n\nRemoving the 1h/5m burn-rates, this shows the same data over the 6h/30m burn-rates.\n\nThe alert will fire when the solid lines cross the dotted threshold.\n"
  },
  {
   "title": "Single window, 1h/5m burn-rates, no thresholds",
   "type": "graph",
   "description": "apdex burn rates: higher is better",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(gitlab_component_apdex:ratio_1h{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"},1),0)\n",
     "legendFormat": "1h apdex burn rate"
    },
    {
     "expr": "gitlab_component_apdex:ratio_5m{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"}",
     "legendFormat": "5m apdex burn rate"
    }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 130 },
   "content": "# Single window, 1h/5m burn-rates, no thresholds\n\nSince the threshold can be relatively high, removing it can help visualise the current values better.\n"
  },
  {
   "title": "Single window, 6h/30m burn-rates, no thresholds",
   "type": "graph",
   "description": "apdex burn rates: higher is better",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(gitlab_component_apdex:ratio_6h{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"},1),0)\n",
     "legendFormat": "6h apdex burn rate"
    },
    {
     "expr": "gitlab_component_apdex:ratio_30m{environment=\"$environment\", env=\"$environment\", type=\"$type\", stage=\"$stage\", component=\"$component\"}",
     "legendFormat": "30m apdex burn rate"
    }
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 140 },
   "content": "# Single window, 6h/30m burn-rates, no thresholds\n\nSince the threshold can be relatively high, removing it can help visualise the current values better.\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./alerts/component_multiburn_apdex.dashboard.jsonnet)\n"
  }
 ]
}