{
 "title": "Alerts",
 "description": "Alerts from prometheus.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s,1m,5m,1h,6h,1d" },
   { "name": "environment", "label": "environment", "query": "gprd,gstg" },
   {
    "name": "alertname",
    "label": "alertname",
    "query": "label_values(ALERTS, alertname)"
   },
   { "name": "alertstate", "label": "alertstate", "query": "firing, pending" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "prometheus_app", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Prometheus",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max_over_time(ALERTS{alertstate=\"firing\"}[$__interval])) OR vector(0)"
    }
   ]
  },
  {
   "title": "Current alerts table",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=~\"$alertstate\"}) by (fqdn,alertname,alertstate,severity)",
     "legendFormat": "service: {{service}} environment: {{environment}} instance: {{instance}}  alertname: {{alertname}}   service: {{service}}"
    }
   ]
  },
  {
   "title": "Alerts Graph: instance alertname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "count(ALERTS{} == 1) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Prometheus App",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max_over_time(ALERTS{environment=~\"$environment\",monitor=~\".*-app\",alertstate=\"firing\"}[$__interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Current alerts table",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "count(ALERTS{}) by (fqdn,alertname,alertstate,severity)",
     "legendFormat": "service: {{service}} environment: {{environment}} instance: {{instance}}  alertname: {{alertname}}   service: {{service}}"
    },
    {}
   ]
  },
  {
   "title": "Alerts Graph: instance alertname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "count(ALERTS{} == 1)  by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  }
 ]
}