{
 "title": "Alert Reporting",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(ALERTS, environment)"
   },
   { "name": "reporting_period", "query": "1d,7d,30d,90d,180d" }
  ]
 },
 "panels": [
  {
   "title": "90 Day Alert Trend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(alertmanager_alerts{state=\"active\", environment=\"$environment\"}[$__interval])) by (environment) ",
     "legendFormat": "{{ environment }}"
    }
   ]
  },
  {
   "title": "Noisiest Alerts in Reporting Period ($reporting_period)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, \n  sum(\n    sum_over_time(\n      ALERTS{alertstate=\"firing\", environment=\"$environment\", severity!=\"warn\"}[$reporting_period]\n    )\n  ) by (alertname, severity)\n)",
     "legendFormat": "{{ alertname }} ({{ severity }})"
    }
   ]
  },
  {
   "title": "Alerts over Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(ALERTS{environment=\"$environment\"}[$__interval])) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  }
 ]
}