{
 "title": "alipniagov: LB worker",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/1348829016 at Tue Jun 15 15:10:31 UTC 2021",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "queue",
    "query": "label_values(sidekiq_jobs_completion_seconds_count{environment=\"$environment\", type=\"sidekiq\"}, queue)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queue Attribute: Urgency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (queue) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__range])) by (queue, urgency)),\n  \"urgency\", \"unknown\", \"urgency\", \"\"\n)\n",
     "legendFormat": "{{ urgency }} ({{ queue }})"
    }
   ]
  },
  {
   "title": "Queue Attribute: Feature Category",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (queue) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__range])) by (queue, feature_category)),\n  \"feature_category\", \"unknown\", \"feature_category\", \"\"\n)\n",
     "legendFormat": "{{ feature_category }} ({{ queue }})"
    }
   ]
  },
  {
   "title": "Queue Attribute: Shard",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (queue) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__range])) by (queue, shard)),\n  \"shard\", \"unknown\", \"shard\", \"\"\n)\n",
     "legendFormat": "{{ shard }} ({{ queue }})"
    }
   ]
  },
  {
   "title": "Queue Attribute: External Dependencies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (queue) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__range])) by (queue, external_dependencies)),\n  \"external_dependencies\", \"none\", \"external_dependencies\", \"\"\n)\n",
     "legendFormat": "{{ external_dependencies }} ({{ queue }})"
    }
   ]
  },
  {
   "title": "Queue Attribute: Resource Boundary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (queue) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__range])) by (queue, boundary)),\n  \"boundary\", \"none\", \"boundary\", \"\"\n)\n",
     "legendFormat": "{{ boundary }} ({{ queue }})"
    }
   ]
  },
  {
   "title": "Max Queuing Duration SLO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(NaN) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\", urgency=\"throttled\"}\nor\nvector(60.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\", urgency=\"low\"}\nor\nvector(10.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\", urgency=\"high\"}\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Max Execution Duration SLO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(300.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\", urgency=\"throttled\"}\nor\nvector(300.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\", urgency=\"low\"}\nor\nvector(10.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\", urgency=\"high\"}\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Backlog",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sidekiq_queue_size{environment=\"$environment\", name=~\"$queue\"} and on(fqdn) (redis_connected_slaves != 0)) > 10)\n/\n(-deriv(sidekiq_queue_size{environment=\"$environment\", name=~\"$queue\"}[5m]) and on(fqdn) (redis_connected_slaves != 0) > 0)\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "🌡 Queue Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Queue Apdex",
   "type": "graph",
   "description": "Queue apdex monitors the percentage of jobs that are dequeued within their queue threshold. Higher is better. Different jobs have different thresholds.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    {
     "format": "percentunit",
     "label": "% Jobs within Max Queuing Duration SLO"
    }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (queue) (\n  (gitlab_background_jobs:queue:apdex:ratio_5m{environment=\"$environment\", queue=~\"$queue\"} >= 0)\n  *\n  (gitlab_background_jobs:queue:apdex:weight:score_5m{environment=\"$environment\", queue=~\"$queue\"} >= 0)\n)\n/\nsum by (queue) (\n  (gitlab_background_jobs:queue:apdex:weight:score_5m{environment=\"$environment\", queue=~\"$queue\"})\n)\n,1),0)\n",
     "legendFormat": "{{ queue }} queue apdex"
    }
   ]
  },
  {
   "title": "Execution Apdex",
   "type": "graph",
   "description": "Execution apdex monitors the percentage of jobs that run within their execution (run-time) threshold. Higher is better. Different jobs have different thresholds.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    {
     "format": "percentunit",
     "label": "% Jobs within Max Execution Duration SLO"
    }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (queue) (\n  (gitlab_background_jobs:execution:apdex:ratio_5m{environment=\"$environment\", queue=~\"$queue\"} >= 0)\n  *\n  (gitlab_background_jobs:execution:apdex:weight:score_5m{environment=\"$environment\", queue=~\"$queue\"} >= 0)\n)\n/\nsum by (queue) (\n  (gitlab_background_jobs:execution:apdex:weight:score_5m{environment=\"$environment\", queue=~\"$queue\"})\n)\n,1),0)\n",
     "legendFormat": "{{ queue }} execution apdex"
    }
   ]
  },
  {
   "title": "Execution Rate (RPS)",
   "type": "graph",
   "description": "Jobs executed per second",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ops", "label": "Jobs per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (gitlab_background_jobs:execution:ops:rate_5m{environment=\"$environment\", queue=~\"$queue\"})\n",
     "legendFormat": "{{ queue }} rps"
    }
   ]
  },
  {
   "title": "Error Ratio",
   "type": "graph",
   "description": "Percentage of jobs that fail with an error. Lower is better.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "percentunit", "label": "Error Percentage" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (queue) (\n  (gitlab_background_jobs:execution:error:rate_5m{environment=\"$environment\", queue=~\"$queue\"} >= 0)\n)\n/\nsum by (queue) (\n  (gitlab_background_jobs:execution:ops:rate_5m{environment=\"$environment\", queue=~\"$queue\"} >= 0)\n)\n,1),0)\n",
     "legendFormat": "{{ queue }} error ratio"
    }
   ]
  },
  {
   "title": "Enqueuing (rate of jobs enqueuing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Jobs Enqueued",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (\n  gitlab_background_jobs:queue:ops:rate_5m{environment=\"$environment\", queue=~\"$queue\"}\n)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Jobs Enqueued per Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type, queue) (\n  gitlab_background_jobs:queue:ops:rate_5m{environment=\"$environment\", queue=~\"$queue\"}\n)\n",
     "legendFormat": "{{ queue }} - {{ type }}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "graph",
   "description": "The number of unstarted jobs in a queue",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (name) (max_over_time(sidekiq_queue_size{environment=\"$environment\", name=~\"$queue\"}[$__interval]) and on(fqdn) (redis_connected_slaves != 0))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Queue Latency (the amount of time spent queueing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Queue Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (queue, le) (\n  sli_aggregations:sidekiq_jobs_queue_duration_seconds_bucket_rate5m{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}\n))\n",
     "legendFormat": "p95 {{ queue }}"
    }
   ]
  },
  {
   "title": "Execution Latency (the amount of time the job takes to execute after dequeue)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Execution Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (queue, le) (\n  sli_aggregations:sidekiq_jobs_completion_seconds_bucket_rate5m{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}\n))\n",
     "legendFormat": "p95 {{ queue }}"
    }
   ]
  },
  {
   "title": "Execution RPS (the rate at which jobs are completed after dequeue)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (\n  gitlab_background_jobs:execution:ops:rate_5m{environment=\"$environment\", queue=~\"$queue\"}\n)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Error Rate (the rate at which jobs fail)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 }
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (\n  gitlab_background_jobs:execution:error:rate_5m{environment=\"$environment\", queue=~\"$queue\"}\n)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Dead Jobs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (\n  increase(sidekiq_jobs_dead_total{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (queue, le) (\n  rate(sidekiq_jobs_cpu_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (queue, le) (\n  rate(sidekiq_jobs_cpu_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (queue, le) (\n  rate(sidekiq_jobs_cpu_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (queue, le) (\n  rate(sidekiq_jobs_cpu_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p99"
    }
   ]
  },
  {
   "title": "Gitaly Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (queue, le) (\n  rate(sidekiq_jobs_gitaly_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (queue, le) (\n  rate(sidekiq_jobs_gitaly_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (queue, le) (\n  rate(sidekiq_jobs_gitaly_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (queue, le) (\n  rate(sidekiq_jobs_gitaly_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p99"
    }
   ]
  },
  {
   "title": "Database Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (queue, le) (\n  rate(sidekiq_jobs_db_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (queue, le) (\n  rate(sidekiq_jobs_db_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (queue, le) (\n  rate(sidekiq_jobs_db_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (queue, le) (\n  rate(sidekiq_jobs_db_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p99"
    }
   ]
  },
  {
   "title": "Redis Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (queue, le) (\n  rate(sidekiq_redis_requests_duration_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (queue, le) (\n  rate(sidekiq_redis_requests_duration_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (queue, le) (\n  rate(sidekiq_redis_requests_duration_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (queue, le) (\n  rate(sidekiq_redis_requests_duration_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p99"
    }
   ]
  },
  {
   "title": "Elasticsearch Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (queue, le) (\n  rate(sidekiq_elasticsearch_requests_duration_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (queue, le) (\n  rate(sidekiq_elasticsearch_requests_duration_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (queue, le) (\n  rate(sidekiq_elasticsearch_requests_duration_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (queue, le) (\n  rate(sidekiq_elasticsearch_requests_duration_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p99"
    }
   ]
  },
  { "title": "SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Total SQL Queries Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint_id) (\n  rate(\n    gitlab_transaction_db_count_total{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{ endpoint_id }} - total"
    },
    {
     "expr": "sum by (endpoint_id) (\n  rate(\n    gitlab_transaction_db_primary_count_total{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{ endpoint_id }} - primary"
    },
    {
     "expr": "sum by (endpoint_id) (\n  rate(\n    gitlab_transaction_db_replica_count_total{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{ endpoint_id }} - replica"
    }
   ]
  },
  {
   "title": "SQL Transactions Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint_id) (\n  rate(gitlab_database_transaction_seconds_count{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n)\n",
     "legendFormat": "{{ endpoint_id }}"
    }
   ]
  },
  {
   "title": "SQL Transaction Holding Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_database_transaction_seconds_sum{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])) by (endpoint_id)\n/\nsum(rate(gitlab_database_transaction_seconds_count{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])) by (endpoint_id)\n",
     "legendFormat": "{{ endpoint_id }} - p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_database_transaction_seconds_bucket{environment=\"$environment\",queue=~\"$queue\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])) by (endpoint_id, le))\n",
     "legendFormat": "{{ endpoint_id }} - p95"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 100 },
   "options": {
    "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./sidekiq/queue-detail.dashboard.jsonnet)\n"
   },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./sidekiq/queue-detail.dashboard.jsonnet)\n"
  }
 ]
}