{
 "title": "Andrew - Anomaly Talk - Non Seasonal 1",
 "tags": [ "general" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "type",
    "query": "label_values(gitlab_service_ops:rate{environment=\"$environment\"}, type)"
   },
   { "name": "stage", "query": "main,cny," },
   { "name": "sigma", "query": "0.5,1,1.5,2,2.5,3" }
  ]
 },
 "panels": [
  {
   "title": "7d Latency SLO Error Budget",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "\n        avg(avg_over_time(slo_observation_status{slo=\"error_ratio\", environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[7d]))\n      "
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "\n      sort(\n        max(\n        ALERTS{environment=\"$environment\", type=\"$type\", stage=\"$stage\", severity=\"critical\", alertstate=\"firing\"} * 3\n        or\n        ALERTS{environment=\"$environment\", type=\"$type\", stage=\"$stage\", severity=\"error\", alertstate=\"firing\"} * 2\n        or\n        ALERTS{environment=\"$environment\", type=\"$type\", stage=\"$stage\", severity=\"warn\", alertstate=\"firing\"}\n        ) by (alertname, severity)\n      )\n      "
    }
   ]
  },
  {
   "title": "7d Apdex Rate SLO Error Budget",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "\n        avg_over_time(slo_observation_status{slo=\"apdex_ratio\",  environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[7d])\n      "
    }
   ]
  },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "\n      min(\n        min_over_time(\n          gitlab_service_apdex:ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval]\n        )\n      ) by (type)\n      ",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "\n      min(\n        min_over_time(\n          gitlab_service_apdex:ratio{environment=\"$environment\", type=\"$type\", stage=\"\"}[$__interval]\n        )\n      ) by (type)\n      ",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "\n        avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"$type\"})\n      ",
     "legendFormat": "SLO"
    },
    {
     "expr": "\n      min(\n        min_over_time(\n          gitlab_service_apdex:ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval] offset 1w\n        )\n      ) by (type)\n      ",
     "legendFormat": "last week"
    },
    {
     "expr": "\n      avg(\n        clamp_max(\n          gitlab_service_apdex:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"} +\n          $sigma * gitlab_service_apdex:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"},\n          1\n        )\n      )\n      ",
     "legendFormat": "upper normal"
    },
    {
     "expr": "\n      avg(\n        clamp_min(\n          gitlab_service_apdex:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"} -\n          $sigma * gitlab_service_apdex:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"},\n          0\n        )\n      )\n      ",
     "legendFormat": "lower normal"
    },
    {
     "expr": "\n      avg(\n        clamp_max(\n          gitlab_service_apdex:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"} +\n          $sigma * gitlab_service_apdex:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"},\n          1\n        )\n      )\n      ",
     "legendFormat": "upper normal (legacy)"
    },
    {
     "expr": "\n      avg(\n        clamp_min(\n          gitlab_service_apdex:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"} -\n          $sigma * gitlab_service_apdex:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"},\n          0\n        )\n      )\n      ",
     "legendFormat": "lower normal (legacy)"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "\n      max(\n        max_over_time(\n          gitlab_service_errors:ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval]\n        )\n      ) by (type)\n      ",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "\n      max(\n        max_over_time(\n          gitlab_service_errors:ratio{environment=\"$environment\", type=\"$type\", stage=\"\"}[$__interval]\n        )\n      ) by (type)\n      ",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "\n        avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"$type\"})\n      ",
     "legendFormat": "SLO"
    },
    {
     "expr": "\n      max(\n        max_over_time(\n          gitlab_service_errors:ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval] offset 1w\n        )\n      ) by (type)\n      ",
     "legendFormat": "last week"
    },
    {
     "expr": "\n      avg(\n        (\n          gitlab_service_errors:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"} +\n          $sigma * gitlab_service_errors:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}\n        )\n      )\n      ",
     "legendFormat": "upper normal"
    },
    {
     "expr": "\n      avg(\n        clamp_min(\n          gitlab_service_errors:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"} -\n          $sigma * gitlab_service_errors:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"},\n          0\n        )\n      )\n      ",
     "legendFormat": "lower normal"
    },
    {
     "expr": "\n      avg(\n        (\n          gitlab_service_errors:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"} +\n          $sigma * gitlab_service_errors:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"}\n        )\n      )\n      ",
     "legendFormat": "upper normal (legacy)"
    },
    {
     "expr": "\n      avg(\n        clamp_min(\n          gitlab_service_errors:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"} -\n          $sigma * gitlab_service_errors:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"},\n          0\n        )\n      )\n      ",
     "legendFormat": "lower normal (legacy)"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "graph",
   "description": "Availability measures the ratio of component processes in the service that are currently healthy and able to handle requests. The closer to 100% the better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability %" }
   ],
   "targets": [
    {
     "expr": "\n      min(\n        min_over_time(\n          gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval]\n        )\n      ) by (tier, type)\n      ",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "\n      min(\n        min_over_time(\n          gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\", stage=\"\"}[$__interval]\n        )\n      ) by (tier, type)\n      ",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "\n      min(\n        min_over_time(\n          gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval] offset 1w\n        )\n      ) by (tier, type)\n      ",
     "legendFormat": "last week"
    },
    {
     "expr": "\n      avg(\n        clamp_max(\n          gitlab_service_availability:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"} +\n          $sigma * gitlab_service_availability:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"},\n        1)\n      )\n      ",
     "legendFormat": "upper normal"
    },
    {
     "expr": "\n      avg(\n        clamp_min(\n          gitlab_service_availability:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"} -\n          $sigma * gitlab_service_availability:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"},\n          0\n        )\n      )\n      ",
     "legendFormat": "lower normal"
    },
    {
     "expr": "\n      avg(\n        clamp_max(\n          gitlab_service_availability:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"} +\n          $sigma * gitlab_service_availability:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"},\n        1)\n      )\n      ",
     "legendFormat": "upper normal (legacy)"
    },
    {
     "expr": "\n      avg(\n        clamp_min(\n          gitlab_service_availability:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"} -\n          $sigma * gitlab_service_availability:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"\"},\n          0\n        )\n      )\n      ",
     "legendFormat": "lower normal (legacy)"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "\n      max(\n        avg_over_time(\n          gitlab_service_ops:rate{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval]\n        )\n      ) by (type)\n      ",
     "legendFormat": "{{ type }} RPS"
    },
    {
     "expr": "\n      max(\n        avg_over_time(\n          gitlab_service_ops:rate{environment=\"$environment\", type=\"$type\", stage=\"\"}[$__interval]\n        )\n      ) by (type)\n      ",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "\n      gitlab_service_ops:rate:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"} +\n      ($sigma) * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}\n      ",
     "legendFormat": "upper normal"
    },
    {
     "expr": "\n      avg(\n        clamp_min(\n          gitlab_service_ops:rate:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"} -\n          ($sigma) * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"},\n          0\n        )\n      )\n      ",
     "legendFormat": "lower normal"
    },
    {
     "expr": "      gitlab_service_ops:rate:avg_over_time_1w{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}",
     "legendFormat": "Gitaly Average RPS"
    }
   ]
  }
 ]
}