{
 "title": "Andrew - General Triage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "label_values(gitlab:service:availability, environment)"
   },
   {
    "name": "tier_prom",
    "query": "label_values(gitlab:service:availability{environment=\"$environment\"}, tier)"
   },
   {
    "name": "tier_prom_app",
    "query": "label_values(gitlab:service:availability{environment=\"$environment\"}, tier)"
   }
  ]
 },
 "panels": [
  {
   "title": "Availability by Tier (prometheus-1)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab:service:availability{environment=\"$environment\"}) by (tier)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ tier }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Availability by Tier (prometheus-app)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab:service:availability{environment=\"$environment\"}) by (tier)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ tier }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$tier_prom services (prom)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "repeat": "tier_prom",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab:service:availability{environment=\"$environment\", tier=\"$tier_prom\"}) by (type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$tier_prom services (prom)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab:service:availability{environment=\"$environment\", tier=\"$tier_prom\"}) by (type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$tier_prom services (prom)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab:service:availability{environment=\"$environment\", tier=\"$tier_prom\"}) by (type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$tier_prom services (prom)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab:service:availability{environment=\"$environment\", tier=\"$tier_prom\"}) by (type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$tier_prom_app services (prom-app)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "repeat": "tier_prom_app",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab:service:availability{environment=\"$environment\", tier=\"$tier_prom_app\"}) by (type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$tier_prom_app services (prom-app)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab:service:availability{environment=\"$environment\", tier=\"$tier_prom_app\"}) by (type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$tier_prom_app services (prom-app)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab:service:availability{environment=\"$environment\", tier=\"$tier_prom_app\"}) by (type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$tier_prom_app services (prom-app)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab:service:availability{environment=\"$environment\", tier=\"$tier_prom_app\"}) by (type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}