{
 "title": "API Actions by Count [deprecated]",
 "tags": [ "influxdb" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "content": "![](https://media.giphy.com/media/l0HlKrB02QY0f1mbm/giphy.gif)"
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "content": "# InfluxDB is Deprecated\nInfluxDB is deprecated in 13.0. This dashboad will be removed after 2020-05-22.\n"
  },
  {
   "title": "API v3 Actions by Count",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"duration\") AS \"count\" FROM rails_transactions WHERE $timeFilter AND request_uri =~ /^\\/api\\/v3/ GROUP BY action",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API v4 Actions by Count",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"duration\") AS \"count\" FROM rails_transactions WHERE $timeFilter AND request_uri =~ /^\\/api\\/v4/ GROUP BY action",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CI API v1 Actions by Count",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"duration\") AS \"count\" FROM rails_transactions WHERE $timeFilter AND request_uri =~ /^\\/ci\\/api\\/v1/ GROUP BY action",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}