{
 "title": "API-C2-Conversion",
 "time": { "from": "2020-04-02T14:00:00.000Z", "to": "2020-04-02T18:00:00.000Z" },
 "panels": [
  {
   "title": "P95 request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, fqdn) (rate(http_request_duration_seconds_bucket{env=\"gprd\",instance=~\"api.*\",job=\"gitlab-rails\", status=\"200\"}[2m])))",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "P99 request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, fqdn) (rate(http_request_duration_seconds_bucket{env=\"gprd\",instance=~\"api.*\",job=\"gitlab-rails\",status=\"200\"}[2m])))",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "P95 request queue time (rails)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, fqdn) (rate(gitlab_rails_queue_duration_seconds_bucket{environment=\"gprd\",fqdn=~\"api.*\",job=\"gitlab-rails\"}[2m])))",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "P99 request queue time (rails)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, fqdn) (rate(gitlab_rails_queue_duration_seconds_bucket{environment=\"gprd\",fqdn=~\"api.*\",job=\"gitlab-rails\"}[2m])))",
     "legendFormat": "{{fqdn}}"
    }
   ]
  }
 ]
}