{
 "title": "Application Info",
 "tags": [
  "docker",
  "registry",
  "internals"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "StackDriver Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log messages with severity ERROR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"ERROR\", cluster_name=\"$cluster\", namespace_id=\"$namespace\"}) / 60",
     "legendFormat": "ERROR msgs per second"
    }
   ]
  },
  {
   "title": "Log messages with severity INFO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"INFO\", cluster_name=\"$cluster\", namespace_id=\"$namespace\"}) / 60",
     "legendFormat": "INFO msgs per second"
    }
   ]
  },
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Registry Process CPU Time",
   "type": "graph",
   "description": "CPU time.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\".*registry.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Registry Resident Memory Usage",
   "type": "graph",
   "description": "Resident memory size",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\".*registry.*\", cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }} Resident Memory"
    }
   ]
  },
  {
   "title": "Registry Open File Descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\".*registry.*\", cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Registry Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "The HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_http_requests_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (handler, code)",
     "legendFormat": "{{ handler }}: {{ code }}"
    }
   ]
  },
  {
   "title": "In-Flight HTTP Requests",
   "type": "graph",
   "description": "The in-flight HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_http_in_flight_requests{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (handler, code)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Registry Action Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(registry_storage_action_seconds_sum{job=~\".*registry.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval])) by (action)",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Registry Cache Requests Rate",
   "type": "graph",
   "description": "The rate of registry cache requests",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_storage_cache_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Cache Hit %",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 26 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{cluster=\"$cluster\", namespace=\"$namespace\",type=\"Hit\"}[$__interval])) / sum(rate(registry_storage_cache_total{env=\"$env\",type=\"Request\"}[$__interval]))"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Manifest HTTP Request Latencies in seconds (manifest)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"manifest\",cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (blob_upload_chunk)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob_upload_chunk\", cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "HTTP Request Latencies in seconds (blob)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob\",cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (base)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"base\",cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "Tags HTTP Request Latencies in seconds (tags)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"tags\", cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "Upload HTTP Request Latencies in seconds (blob_upload)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob_upload\", cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  }
 ]
}