{
 "title": "Arkose metrics",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Session logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(user_session_logins_total[60m])) by (env)"
    },
    {
     "expr": "avg(sum(rate(user_session_logins_total[30m])) by (env))"
    }
   ]
  },
  {
   "title": "CAPTCHA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "successful_login_captcha_total" },
    { "expr": "failed_login_captcha_total" }
   ]
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "gitlab_auth_user_authenticated_total"
    },
    {
     "expr": "gitlab_auth_user_unauthenticated_total"
    }
   ]
  },
  {
   "title": "Invalid passwords and blocked users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "gitlab_auth_user_password_invalid_total"
    },
    { "expr": "gitlab_auth_user_blocked_total" }
   ]
  }
 ]
}