{
 "title": "Background Migrations",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(gitlab_service_ops:rate, environment)"
    }
   },
   {
    "name": "migration_identifier",
    "label": "Migration Identifier",
    "query": {
     "query": "label_values(batched_migration_total_tuple_count{env=\"$environment\"}, migration_identifier)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$migration_identifier",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "migration_identifier",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n    max_over_time(batched_migration_migrated_tuples_total{env=\"$environment\",monitor=\"default\",migration_identifier=${migration_identifier:doublequote}}[$__interval])\n    /  \n    max_over_time(batched_migration_total_tuple_count{env=\"$environment\",monitor=\"default\",migration_identifier=${migration_identifier:doublequote}}[$__interval])\n)",
     "legendFormat": "{{ migration_identifier }}"
    }
   ]
  },
  { "title": "Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Progress per Migration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    max_over_time(batched_migration_migrated_tuples_total{env=\"$environment\",monitor=\"default\"}[$__interval])\n    /\n    max_over_time(batched_migration_total_tuple_count{env=\"$environment\",monitor=\"default\"}[$__interval])\n) by (migration_identifier)",
     "legendFormat": "{{ migration_identifier }}"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(batched_migration_job_duration_seconds{env=\"$environment\",monitor=\"default\"}) by (migration_identifier)",
     "legendFormat": "{{ migration_identifier }}"
    }
   ]
  },
  {
   "title": "Updated Tuples",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(batched_migration_job_updated_tuples_total{env=\"$environment\",monitor=\"default\"}) by (migration_identifier)",
     "legendFormat": "{{ migration_identifier }}"
    }
   ]
  }
 ]
}