{
 "title": "Bitbucket Importer",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Imported Projects Per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bitbucket_importer_imported_projects{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Total Imported Projects",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 0 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(bitbucket_importer_imported_projects[10y]))"
    }
   ]
  },
  {
   "title": "Imported Pull Requests Per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bitbucket_importer_imported_pull_requests{env=\"gprd\",monitor=\"app\"}[$__interval])) * 3600",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Total Imported Pull Requests",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 8 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(bitbucket_importer_imported_pull_requests[10y]))"
    }
   ]
  },
  {
   "title": "Imported Issues per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bitbucket_importer_imported_issues{env=\"gprd\",monitor=\"app\"}[$__interval])) * 3600",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Total Imported Issues",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 16 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(bitbucket_importer_imported_issues[10y]))"
    }
   ]
  }
 ]
}