{
 "title": "bjk - Gitlab Shell",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Git Commands",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (command, gl_key_type, git_protocol) (\n  rate(gitlab_shell_git_commands_total[$__rate_interval])\n)",
     "legendFormat": "{{command}} - {{git_protocol}} - {{gl_key_type}}"
    }
   ]
  },
  {
   "title": "GET Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (le) (rate(gitlab_shell_request_seconds_bucket{method=\"GET\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "POST Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (le) (rate(gitlab_shell_request_seconds_bucket{method=\"POST\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}