{
 "title": "bjk - Gitaly Reporting June 2020",
 "tags": [ "bjk" ],
 "time": { "from": "2020-06-01T00:00:00.000Z", "to": "2020-07-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "IOPs - Write",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile(0.999, quantile_over_time(0.999, instance:node_disk_writes_completed:irate1m{env=\"gprd\",type=\"gitaly\",tier=\"stor\",shard=\"default\"}[$__interval]))",
     "legendFormat": "99.9th %"
    },
    {
     "expr": "max(max_over_time(instance:node_disk_writes_completed:irate1m{env=\"gprd\",type=\"gitaly\",tier=\"stor\",shard=\"default\"}[$__interval]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "IOPs - Read",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile(0.999, quantile_over_time(0.999, instance:node_disk_reads_completed:irate1m{env=\"gprd\",type=\"gitaly\",tier=\"stor\",shard=\"default\"}[$__interval]))",
     "legendFormat": "99.9th %"
    },
    {
     "expr": "max(max_over_time(instance:node_disk_reads_completed:irate1m{env=\"gprd\",type=\"gitaly\",tier=\"stor\",shard=\"default\"}[$__interval]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Hourly Storage Activity - 95th Percentile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.95, increase(node_disk_read_bytes_total{env=\"gprd\",type=\"gitaly\",tier=\"stor\",shard=\"default\",device=\"sdb\",fqdn!~\"file-hdd.*\"}[$__interval]))",
     "legendFormat": "reads"
    },
    {
     "expr": "quantile(0.95, increase(node_disk_written_bytes_total{env=\"gprd\",type=\"gitaly\",tier=\"stor\",shard=\"default\",device=\"sdb\",fqdn!~\"file-hdd.*\"}[$__interval]))",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "IO Bandwidth - 95th Percentile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "quantile(0.99, sum by (fqdn) (\n  quantile_over_time(0.999, rate(node_disk_written_bytes_total{env=\"gprd\",type=\"gitaly\",tier=\"stor\",shard=\"default\",device=\"sdb\"}[5m])[1h:5m])\n))",
     "legendFormat": "reads"
    }
   ]
  },
  {
   "title": "CPU Utilization ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.95, quantile_over_time(0.95, instance:node_cpu_utilization:ratio{env=\"gprd\",type=\"gitaly\",tier=\"stor\",shard=\"default\",fqdn!~\"file-hdd.*\"}[$__interval]))",
     "legendFormat": "95th %"
    },
    {
     "expr": "quantile(0.99, quantile_over_time(0.99, instance:node_cpu_utilization:ratio{env=\"gprd\",type=\"gitaly\",tier=\"stor\",shard=\"default\",fqdn!~\"file-hdd.*\"}[$__interval]))",
     "legendFormat": "99th %"
    }
   ]
  }
 ]
}