{
 "title": "Broken: Gitaly: Rails Analysis",
 "tags": [ "controller" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "action",
    "label": "Action",
    "query": "SHOW TAG VALUES FROM gitlab.downsampled.rails_transaction_counts_per_action WITH KEY = \"action\""
   },
   { "name": "database", "label": "Database", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Transaction Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "transactions",
     "query": "SELECT \"duration\" AS \"Duration\", \"allocated_memory\" AS \"Memory\", \"sql_count\" AS \"Queries\", \"request_method\" AS \"Method\", \"action\" AS \"Action\", \"request_uri\" AS \"URI\" FROM \"rails_transactions\" WHERE $timeFilter AND \"action\" ='[[action]]' ORDER BY time DESC LIMIT 500",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "method" ], "type": "field" }
      ],
      [
       { "params": [ "path" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Method Times",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "rails_method_call_timings_per_action_and_method",
     "query": "    SELECT mean(call_count_99th) as mean_99th \n      FROM downsampled.rails_method_call_timings_per_action_and_method \n     WHERE $timeFilter \n       AND \"action\" =~ /^[[action]]$/\n  GROUP BY method, time(30d)",
     "select": [
      [
       { "params": [ "cpu_duration_95th" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "action",
       "operator": "=",
       "value": "Admin::DashboardController#index"
      }
     ]
    }
   ]
  },
  {
   "title": "Git Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"duration_95th\" AS \"95th Percentile\", \"duration_99th\" AS \"99th Percentile\", \"duration_mean\" AS \"Mean\" FROM downsampled.rails_git_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"sql_duration_95th\" AS \"95th Percentile\", \"sql_duration_99th\" AS \"99th Percentile\", \"sql_duration_mean\" AS \"Mean\", \"sql_duration_max\" AS \"Maximum\" FROM downsampled.rails_transaction_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Query Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"sql_count_95th\" AS \"95th Percentile\", \"sql_count_99th\" AS \"99th Percentile\", \"sql_count_mean\" AS \"Mean\", \"sql_count_max\" AS \"Maximum\" FROM downsampled.rails_transaction_sql_counts_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Method Call Wall Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"duration_95th\") AS \"value\" FROM downsampled.rails_method_call_timings_per_action_and_method WHERE $timeFilter AND \"action\" =~ /^[[action]]$/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Method Call CPU Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_duration_95th\") AS \"value\" FROM downsampled.rails_method_call_timings_per_action_and_method WHERE $timeFilter AND \"action\" =~ /^[[action]]$/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Method Call Counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"call_count_95th\") AS \"value\" FROM downsampled.rails_method_call_timings_per_action_and_method WHERE $timeFilter AND \"action\" =~ /^[[action]]$/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}