{
 "title": "Broken: Rails Cache Overview",
 "tags": [ "cache" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "process_type", "label": "Process Type", "query": "rails,sidekiq,grape" },
   { "name": "database", "label": "Database", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Total Cache Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_duration_95th\" AS \"95th Percentile\", \"cache_duration_99th\" as \"99th Percentile\", \"cache_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Read Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_read_duration_95th\" AS \"95th Percentile\", \"cache_read_duration_99th\" as \"99th Percentile\", \"cache_read_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Write Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_write_duration_95th\" AS \"95th Percentile\", \"cache_write_duration_99th\" as \"99th Percentile\", \"cache_write_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Delete Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_delete_duration_95th\" AS \"95th Percentile\", \"cache_delete_duration_99th\" as \"99th Percentile\", \"cache_delete_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Exists Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_exists_duration_95th\" AS \"95th Percentile\", \"cache_exists_duration_99th\" as \"99th Percentile\", \"cache_exists_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Read Hits/Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_read_hit_count_mean\" AS \"Hit mean\", \"cache_read_miss_count_mean\" AS \"Miss mean\" FROM downsampled.\"[[process_type]]_transaction_cache_counts_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}