{
 "title": "Broken: Business Stats",
 "tags": [ "events" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "New Repos Source",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Created",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) AS \"Amount\" FROM year.events_per_hour WHERE event = 'create_repository' AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Imported",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) AS \"Amount\" FROM year.events_per_hour WHERE event = 'import_repository' AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Forked",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) AS \"Amount\" FROM year.events_per_hour WHERE event = 'fork_repository' AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pushes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Commits",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) AS \"Amount\" FROM year.events_per_hour WHERE event = 'push_commit' AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Branch",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) AS \"Amount\" FROM year.events_per_hour WHERE event = 'push_branch' AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Tag",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) AS \"Amount\" FROM year.events_per_hour WHERE event = 'push_tag' AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CI Builds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Found new build",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) AS \"Amount\" FROM year.events_per_hour WHERE event = 'build_found' AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Update",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) AS \"Amount\" FROM year.events_per_hour WHERE event = 'update_build' AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Not Found (Redis Hit)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) AS \"Amount\" FROM year.events_per_hour WHERE event = 'build_not_found_cached' AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Etags",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "event" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "events_per_hour",
     "query": "SELECT sum(count) AS \"Amount\" FROM year.events_per_hour WHERE event = '$event' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/etag/" },
      { "condition": "AND", "key": "event", "operator": "!=", "value": "etag_caching_middleware_used" },
      { "condition": "AND", "key": "event", "operator": "!=", "value": "etag_caching_cache_hit" }
     ]
    },
    {
     "alias": "$tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "event" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "events_per_hour",
     "query": "SELECT sum(count) AS \"Amount\" FROM year.events_per_hour WHERE event = '$event' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "etag_caching_cache_hit" }
     ]
    }
   ]
  },
  {
   "title": "Uploads",
   "type": "singlestat",
   "description": "Number of Upload records in the database",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(gitlab_database_rows{query_name=\"uploads\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Orphans and Soft-deleted",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_database_rows{query_name=~\"(orphaned_projects|soft_deleted_projects)\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{query_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Object creations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Projects",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rails_method_calls",
     "select": [
      [
       { "params": [ "call_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "ProjectsController#create" }
     ]
    },
    {
     "alias": "Groups",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rails_method_calls",
     "select": [
      [
       { "params": [ "call_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "GroupsController#create" }
     ]
    },
    {
     "alias": "Snippets",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rails_method_calls",
     "select": [
      [
       { "params": [ "call_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "SnippetsController#create" },
      {
       "condition": "OR",
       "key": "action",
       "operator": "=",
       "value": "Projects::SnippetsController#create"
      }
     ]
    },
    {
     "alias": "Issues",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rails_method_calls",
     "select": [
      [
       { "params": [ "call_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "action",
       "operator": "=",
       "value": "Projects::IssuesController#create"
      }
     ]
    },
    {
     "alias": "Merge requests",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rails_method_calls",
     "query": "SELECT count(\"call_count\") FROM \"rails_method_calls\" WHERE \"action\" = 'Projects::MergeRequestsController#create' AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "call_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "action",
       "operator": "=",
       "value": "Projects::MergeRequestsController#create"
      }
     ]
    }
   ]
  }
 ]
}