{
 "title": "Broken: Method Calls Overview",
 "tags": [ "method" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "process_type", "label": "Process Type", "query": "rails,sidekiq,grape" },
   { "name": "database", "label": "Database", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Method Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT mean(\"duration_95th\") FROM downsampled.[[process_type]]_method_call_timings_per_method WHERE $timeFilter AND method !~ /^(Rugged|Gitlab::Git)/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gitlab::Git Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT mean(\"duration_95th\") FROM downsampled.[[process_type]]_method_call_timings_per_method WHERE $timeFilter AND \"method\" =~ /^Gitlab::Git/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rugged Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT mean(\"duration_95th\") FROM downsampled.[[process_type]]_method_call_timings_per_method WHERE $timeFilter AND \"method\" =~ /^Rugged/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}