{
 "title": "Broken: SQL Timings Overview",
 "description": "Time spent in SQL queries per controller.",
 "tags": [
  "controller",
  "sql",
  "postgresql"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "process_type", "label": "Process Type", "query": "rails,sidekiq,grape" },
   {
    "name": "action",
    "label": "Action",
    "query": "SHOW TAG VALUES FROM gitlab.downsampled.[[process_type]]_transaction_counts_per_action WITH KEY = \"action\""
   },
   { "name": "database", "label": "Database", "query": "influxdb" },
   { "name": "minimum_requests", "label": "Minimum Requests", "query": "10000" },
   { "name": "rarely_used", "label": "Rarely Used Threshold", "query": "30000" },
   { "name": "commonly_used", "label": "Commonly Used Threshold", "query": "100000" },
   {
    "name": "ignore_actions",
    "label": "Actions To Ignore",
    "query": "/^(Gitlab::RequestForgery|RootController|MetricsController)/"
   },
   { "name": "minimum_p99", "label": "Minimum 99th Percentile", "query": "100" },
   { "name": "minimum_sql", "label": "Minimum % Req Time", "query": "0" }
  ]
 },
 "panels": [
  { "title": "Frequently Used (P2)", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controllers with more than [[commonly_used]] requests",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "transactions",
     "query": "SELECT \"action\", \"count\" as \"Amount\", (sql_duration_99th / duration_99th) * 100.0 AS \"Percentage of Request Time\", \"sql_duration_mean\" AS \"Mean\", \"sql_duration_95th\" AS \"95th Percentile\", \"sql_duration_99th\" AS \"99th Percentile\" FROM downsampled.\"[[process_type]]_transaction_timings_per_action_per_day\" WHERE $timeFilter AND action =~ /^[[action]]$/ AND count > [[commonly_used]] AND action !~ [[ignore_actions]] AND sql_duration_99th >= [[minimum_p99]] AND (sql_duration_99th / duration_99th)*100 > [[minimum_sql]] ORDER BY time DESC",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "method" ], "type": "field" }
      ],
      [
       { "params": [ "path" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Commonly Used (P3)", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Controllers with request counts between [[rarely_used]] and [[commonly_used]]",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "transactions",
     "query": "SELECT \"action\", \"count\" as \"Amount\", (sql_duration_99th / duration_99th) * 100.0 AS \"Percentage of Request Time\", \"sql_duration_mean\" AS \"Mean\", \"sql_duration_95th\" AS \"95th Percentile\", \"sql_duration_99th\" AS \"99th Percentile\" FROM downsampled.\"[[process_type]]_transaction_timings_per_action_per_day\" WHERE $timeFilter AND action =~ /^[[action]]$/ AND count > [[rarely_used]] AND count <= [[commonly_used]] AND action !~ [[ignore_actions]] AND sql_duration_99th >= [[minimum_p99]]  AND (sql_duration_99th / duration_99th)*100 > [[minimum_sql]] ORDER BY time DESC",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "method" ], "type": "field" }
      ],
      [
       { "params": [ "path" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Rarely Used (P4)", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Controllers with request counts between [[minimum_requests]] and  [[rarely_used]]",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "transactions",
     "query": "SELECT \"action\", \"count\" as \"Amount\", (sql_duration_99th / duration_99th) * 100.0 AS \"Percentage of Request Time\", \"sql_duration_mean\" AS \"Mean\", \"sql_duration_95th\" AS \"95th Percentile\", \"sql_duration_99th\" AS \"99th Percentile\" FROM downsampled.\"[[process_type]]_transaction_timings_per_action_per_day\" WHERE $timeFilter AND action =~ /^[[action]]$/ AND count <= [[rarely_used]] AND count >= [[minimum_requests]] AND action !~ [[ignore_actions]] AND sql_duration_99th >= [[minimum_p99]]  AND (sql_duration_99th / duration_99th)*100 > [[minimum_sql]] ORDER BY time DESC",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "method" ], "type": "field" }
      ],
      [
       { "params": [ "path" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}