{
 "title": "Broken: Garbage Collector",
 "tags": [ "ruby" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "process_type", "label": "Process Type", "query": "rails,sidekiq" },
   { "name": "database", "label": "Database", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "GC runs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gc_statistics",
     "query": "SELECT \"total\" AS \"Amount\" FROM downsampled.\"[[process_type]]_gc_counts\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "amount" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gc_statistics",
     "query": "SELECT \"duration_95th\" AS \"95th Percentile\", \"duration_99th\" AS \"99th Percentile\", \"duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_gc_timings\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Major/Minor Runs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gc_statistics",
     "query": "SELECT \"major\" AS \"Major\", \"minor\" AS \"Minor\" FROM downsampled.\"[[process_type]]_gc_counts\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "major_gc_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Major" ], "type": "alias" }
      ],
      [
       { "params": [ "minor_gc_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Minor" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}