{
 "title": "Broken: Web Overview",
 "description": "An overview of all web requests",
 "tags": [
  "prometheus",
  "wip"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "process_type", "label": "Process Type", "query": "web,api" },
   { "name": "environment", "label": "Environment", "query": "prd,stg,dev" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(rate(gitlab_transaction_duration_seconds_count{environment = \"$environment\", type != \"sidekiq\"}[1m]) * 60)",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "legendFormat": "Amount",
     "measurement": "transactions",
     "query": "SELECT \"count\" as \"Amount\" FROM downsampled.\"[[process_type]]_transaction_counts_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$process_type Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(rate(gitlab_transaction_duration_seconds_count{environment = \"$environment\", type = \"$process_type\"}[1m]) * 60)",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "legendFormat": "Amount",
     "measurement": "transactions",
     "query": "SELECT \"count\" as \"Amount\" FROM downsampled.\"[[process_type]]_transaction_counts_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_transaction_duration_seconds_bucket{environment = \"$environment\", type = \"$process_type\"}[1m])) by (le))",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "legendFormat": "95th Percentile",
     "measurement": "gitlab.transaction",
     "query": "SELECT \"duration_95th\" AS \"95th Percentile\", \"duration_99th\" as \"99th Percentile\", \"duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitlab_transaction_duration_seconds_bucket{environment = \"$environment\", type = \"$process_type\"}[1m])) by (le))",
     "legendFormat": "99h Percentile"
    },
    {
     "expr": "avg(rate(gitlab_transaction_duration_seconds_sum{environment = \"$environment\", type = \"$process_type\"}[1m]) * 60)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "HTTP Queue Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(gitlab_rails_queue_duration_seconds_sum{environment = \"$environment\", type = \"$process_type\"}[1m]) * 60)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "SQL Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "avg(rate(gitlab_sql_duration_seconds_sum{environment = \"$environment\", type = \"$process_type\"}[1m]) * 60)",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "legendFormat": "Mean",
     "measurement": "gitlab.transaction",
     "query": "SELECT \"sql_duration_95th\" AS \"95th Percentile\", \"sql_duration_99th\" as \"99th Percentile\", \"sql_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_sql_duration_seconds_bucket{environment = \"$environment\", type = \"$process_type\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitlab_sql_duration_seconds_bucket{environment = \"$environment\", type = \"$process_type\"}[1m])) by (le))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "SQL Query Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_sql_duration_seconds_count{environment = \"$environment\", type = \"$process_type\"}[$__interval])) * 60",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}