{
 "title": "Broken: Markdown Overview",
 "tags": [ "markdown" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "process_type", "label": "Process Type", "query": "rails,sidekiq,grape" },
   { "name": "database", "label": "Database", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "New row", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Banzai Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT \"duration_95th\" AS \"95th percentile\", \"duration_99th\" AS \"99th Percentile\", \"duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_markdown_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Cached Renders", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Real Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT \"cached_real_95th\" AS \"95th percentile\", \"cached_real_99th\" AS \"99th Percentile\", \"cached_real_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_markdown_render_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT \"cached_cpu_95th\" AS \"95th percentile\", \"cached_cpu_99th\" AS \"99th Percentile\", \"cached_cpu_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_markdown_render_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Cacheless Renders", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Real Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT \"cacheless_real_95th\" AS \"95th percentile\", \"cacheless_real_99th\" AS \"99th Percentile\", \"cacheless_real_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_markdown_render_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT \"cacheless_cpu_95th\" AS \"95th percentile\", \"cacheless_cpu_99th\" AS \"99th Percentile\", \"cacheless_cpu_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_markdown_render_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Render Counts", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Render With Cache Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT \"cacheless_call_count\" AS \"Without cache\", \"cached_call_count\" AS \"With cache\" FROM downsampled.\"[[process_type]]_markdown_render_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Method Timings", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Slow Banzai::Filter Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT mean(\"duration_95th\") FROM downsampled.[[process_type]]_method_call_timings_per_method WHERE $timeFilter AND method =~ /^Banzai::Filter/ AND \"duration_95th\" >= 100 GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slow Banzai::Renderer Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT mean(\"duration_95th\") FROM downsampled.[[process_type]]_method_call_timings_per_method WHERE $timeFilter AND \"method\" =~ /^Banzai::Renderer/ AND \"duration_95th\" >= 100 GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}