{
 "title": "Chef Client",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "label_values(up{job=\"node\"}, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Oldest Last Run",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg((time() - chef_client_last_run_timestamp_seconds{environment=~\"$environment\"}) > 60 * 60) by (environment,fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chef Client Errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(chef_client_error{environment=~\"$environment\"} == 1) by (environment,fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chef Runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg(chef_client_duration_seconds{environment=~\"$environment\"}) by (environment)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Average {{environment}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(chef_client_duration_seconds{environment=~\"$environment\"}) by (environment)",
     "legendFormat": "Max {{environment}}"
    }
   ]
  },
  {
   "title": "Chef Versions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (chef_version,environment) (chef_client_info{environment=~\"$environment\"})",
     "legendFormat": "{{environment}} - {{chef_version}}"
    }
   ]
  }
 ]
}