{
 "title": "CI - autoscaled machines metrics",
 "description": "Dashboard under development - strange values are possible :)",
 "tags": [ "ci" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "Datacenter",
    "query": "label_values(job_mode:node_cpu_seconds_total:rate1m, dc)"
   },
   {
    "name": "runner_group",
    "label": "Runner Group",
    "query": "label_values(job_mode:node_cpu_seconds_total:rate1m{dc=~\"$dc\"}, runner_group)"
   },
   {
    "name": "cpu_mode",
    "label": "CPU Mode",
    "query": "label_values(job_mode:node_cpu_seconds_total:rate1m{mode!=\"idle\"}, mode)"
   }
  ]
 },
 "panels": [
  {
   "title": "Jobs Run",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(gitlab_runner_jobs_total[$__interval]))"
    }
   ]
  },
  {
   "title": "Filesystem Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(job_rootfs:node_filesystem_size_bytes:sum{dc=~\"$dc\",runner_group=~\"$runner_group\"}) - sum(job_rootfs:node_filesystem_avail_bytes:sum{dc=~\"$dc\",runner_group=~\"$runner_group\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cores Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(job_mode:node_cpu_seconds_total:rate1m{dc=~\"$dc\", runner_group=~\"$runner_group\",mode!=\"idle\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(job:node_memory_total_bytes:sum{dc=~\"$dc\", runner_group=~\"$runner_group\"}) - sum(job:node_memory_available_bytes:sum{dc=~\"$dc\", runner_group=~\"$runner_group\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network IN",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(job:node_network_receive_bytes:rate1m{dc=~\"$dc\",runner_group=~\"$runner_group\",device!=\"docker0\"}) * 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network OUT",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(job:node_network_transmit_bytes:rate1m{dc=~\"$dc\",runner_group=~\"$runner_group\",device!=\"docker0\"}) * 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Filesystem Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(job_rootfs:node_filesystem_avail_bytes:sum{dc=~\"$dc\",runner_group=~\"$runner_group\"})\n  /\nsum(job_rootfs:node_filesystem_size_bytes:sum{dc=~\"$dc\",runner_group=~\"$runner_group\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(job_mode:node_cpu_seconds_total:rate1m{mode!=\"idle\"}) / sum(job:node_cpus:count)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(job:node_memory_available_bytes:sum{dc=~\"$dc\", runner_group=~\"$runner_group\"}) / sum(job:node_memory_total_bytes:sum{dc=~\"$dc\", runner_group=~\"$runner_group\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network IN (Docker)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(job:node_network_transmit_bytes:rate1m{dc=~\"$dc\",runner_group=~\"$runner_group\",device!=\"docker0\"}) * 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network OUT (Docker)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(job:node_network_receive_bytes:rate1m{dc=~\"$dc\",runner_group=~\"$runner_group\",device=\"docker0\"}) * 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs handled by Runners (by runner type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{job=~\"private-runners|shared-runners|shared-runners-gitlab-org|staging-shared-runners\"}) by (job)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{job}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage (cores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dc, runner_group) (avg_over_time(job_mode:node_cpu_seconds_total:rate1m{dc=~\"$dc\", runner_group=~\"$runner_group\",mode!=\"idle\",mode=~\"$cpu_mode\"}[$__interval])) \n  or\nsum by (dc, runner_group) (avg_over_time(runner_machine:node_cpu:irate5m:sum{dc=~\"$dc\", runner_group=~\"$runner_group\",mode!=\"idle\",mode=~\"$cpu_mode\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ dc}} - {{runner_group}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network IN (Docker)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum without (device) (avg_over_time(job:node_network_transmit_bytes:rate1m{dc=~\"$dc\",runner_group=~\"$runner_group\",device=\"docker0\"}[$__interval])) * 8\n  or\nsum without (device) (avg_over_time(runner_machine:node_network_transmit_bytes:irate5m:sum{dc=~\"$dc\",runner_group=~\"$runner_group\",device=\"docker0\"}[$__interval])) * 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{runner_group}} - {{dc}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(job_rootfs:node_filesystem_size_bytes:sum{dc=~\"$dc\",runner_group=~\"$runner_group\"} - job_rootfs:node_filesystem_avail_bytes:sum{dc=~\"$dc\",runner_group=~\"$runner_group\"})\n  or\nrunner_machine:node_filesystem:used:sum{dc=~\"$dc\",runner_group=~\"$runner_group\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{runner_group}} - {{dc}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(job:node_memory_total_bytes:sum{dc=~\"$dc\", runner_group=~\"$runner_group\"} - job:node_memory_available_bytes:sum{dc=~\"$dc\", runner_group=~\"$runner_group\"}) \n  or\nrunner_machine:node_memory:used:sum{dc=~\"$dc\", runner_group=~\"$runner_group\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{runner_group}} - {{dc}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {}
   ]
  },
  {
   "title": "Network OUT (Docker)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum without (device) (avg_over_time(job:node_network_receive_bytes:rate1m{dc=~\"$dc\",runner_group=~\"$runner_group\",device=\"docker0\"}[$__interval])) * 8\n  or \nsum without (device) (avg_over_time(runner_machine:node_network_receive_bytes:irate5m:sum{dc=~\"$dc\",runner_group=~\"$runner_group\",device=\"docker0\"}[$__interval])) * 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{runner_group}} - {{dc}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}