{
 "title": "CI - autoscaling providers",
 "tags": [ "ci" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "gcp_exporter", "label": "GCP exporter", "query": "gcp_exporter_instances_count" },
   {
    "name": "gcp_region",
    "label": "GCP region",
    "query": "label_values(gcp_exporter_region_quota_usage, region)"
   }
  ]
 },
 "panels": [
  { "title": "Google Cloud Platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GCP Machines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(label_replace(gcp_exporter_instances_count{instance=~\"$gcp_exporter\",project=\"gitlab-ci-155816\",zone=~\"(${gcp_region:pipe}).*\"}, \"machine_type_short\", \"$1\", \"machine_type\", \".*/([^/]+)$\"), \"runner_group\", \"$2\", \"tags\", \"(.*,)?(srm|prm|gsrm)(,.*)?\")) by (zone, machine_type_short, runner_group)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{runner_group}} - {{zone}} - {{machine_type_short}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time since last data refresh",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(gcp_exporter_last_data_refresh_timestamp_seconds)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data gathering error rate (1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "max(irate(gcp_exporter_data_refresh_errors_total[1m])) * 60",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GCP Region Quotas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(gcp_exporter_region_quota_usage{instance=~\"$gcp_exporter\",project=\"gitlab-ci-155816\",region=~\"${gcp_region:pipe}\"} / gcp_exporter_region_quota_limit{instance=~\"$gcp_exporter\",project=\"gitlab-ci-155816\",region=~\"${gcp_region:pipe}\"}) > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{quota}} - {{region}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}