{
 "title": "CI Minutes",
 "tags": [ "ci" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "runner_type",
    "label": "Runner Type",
    "query": "gitlab_runner_version_info{job=~\".*\",job!~\"omnibus-runners|gprd-runner\"}"
   },
   {
    "name": "runner_managers",
    "label": "Runner Managers",
    "query": "query_result(label_replace(gitlab_runner_version_info{job=~\"$runner_type\"}, \"fqdn\", \"$1.*\", \"instance\", \"(.*):[0-9]+$\"))"
   },
   { "name": "gitlab_env", "label": "GitLab env", "query": "job_queue_duration_seconds_sum" },
   {
    "name": "gl_monitor_fqdn",
    "label": "GitLab Monitor instance",
    "query": "label_values(ci_running_builds{archivereplica!=\"1\",environment=\"$gitlab_env\"}, fqdn)"
   },
   { "name": "has_minutes", "label": "Has Shared Runners Minutes", "query": "yes,no" },
   {
    "name": "runner_job_failure_reason",
    "label": "Job failure reason",
    "query": "label_values(gitlab_runner_failed_jobs_total, failure_reason)"
   },
   { "name": "jobs_running_for_project", "label": "Jobs running for project", "query": "job_queue_duration_seconds_sum" },
   {
    "name": "runner_request_endpoint_status",
    "label": "Runner request endpoint status",
    "query": "label_values(gitlab_runner_api_request_statuses_total, endpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "private-runners state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"private-runners\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "shared-runners state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"shared-runners\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "shared-runners-gitlab-org state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"shared-runners-gitlab-org\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "staging-shared-runners state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"staging-shared-runners\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs on private-runners",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{job=\"private-runners\"}) / sum(gitlab_runner_concurrent{job=\"private-runners\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs on shared-runners",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{job=\"shared-runners\"}) / sum(gitlab_runner_concurrent{job=\"shared-runners\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs on shared-runners-gitlab-org",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{job=\"shared-runners-gitlab-org\"}) / sum(gitlab_runner_concurrent{job=\"shared-runners-gitlab-org\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs on staging-shared-runners",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{job=\"staging-shared-runners\"})  / sum(gitlab_runner_concurrent{job=\"staging-shared-runners\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GCP Machines",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(gcp_exporter_instances_count{project=\"gitlab-ci-155816\",tags=~\".*docker-machine.*\"}) without (instance))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job minutes",
   "type": "singlestat",
   "description": "Total number of job minutes, for job handled by Runners owned by GitLab Inc.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(gitlab_runner_job_duration_seconds_sum{instance=~\"${runner_managers:pipe}\"}[$__range])) / 60",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Started jobs",
   "type": "singlestat",
   "description": "Total of jobs that were started on GitLab.com",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(gitlab_runner_jobs_total[$__range]))"
    }
   ]
  },
  {
   "title": "Unarchived traces",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ci_unarchived_traces{fqdn=\"$gl_monitor_fqdn\"}",
     "legendFormat": "fqdn"
    }
   ]
  },
  {
   "title": "Cache performance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - sum(gitlab_runner_jobs{exported_stage=~\"(archive|restore)_cache\"}) / sum(gitlab_runner_jobs)"
    }
   ]
  },
  {
   "title": "Jobs at GitLab.com",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ci_pending_builds{fqdn=~\"$gl_monitor_fqdn\", shared_runners=\"yes\",has_minutes=~\"$has_minutes\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "pending jobs for project with shared runners enabled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(ci_pending_builds{fqdn=~\"$gl_monitor_fqdn\", shared_runners=\"no\",has_minutes=~\"$has_minutes\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "pending jobs for project without shared runners enabled",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(ci_running_builds{fqdn=~\"$gl_monitor_fqdn\", shared_runner=\"yes\",has_minutes=~\"$has_minutes\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "running jobs on shared runners",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(ci_running_builds{fqdn=~\"$gl_monitor_fqdn\", shared_runner=\"no\",has_minutes=~\"$has_minutes\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "running jobs on specific runners",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(ci_stale_builds{fqdn=~\"$gl_monitor_fqdn\"})",
     "legendFormat": "stale jobs"
    }
   ]
  },
  {
   "title": "Job queue timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job queue duration histogram percentiles (5m rate)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(job_queue_duration_seconds_bucket{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\"}[5m])) by (shared_runner, jobs_running_for_project, le))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "shared: {{shared_runner}} - running_jobs: {{jobs_running_for_project}} - 50th",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(job_queue_duration_seconds_bucket{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\"}[5m])) by (shared_runner, jobs_running_for_project, le))",
       "legendFormat": "shared: {{shared_runner}} - running_jobs: {{jobs_running_for_project}} - 90th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(job_queue_duration_seconds_bucket{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\"}[5m])) by (shared_runner, jobs_running_for_project, le))",
       "legendFormat": "shared: {{shared_runner}} - running_jobs: {{jobs_running_for_project}} - 95th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(job_queue_duration_seconds_bucket{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\"}[5m])) by (shared_runner, jobs_running_for_project, le))",
       "legendFormat": "shared: {{shared_runner}} - running_jobs: {{jobs_running_for_project}} - 99th"
      }
     ]
    },
    {
     "title": "Job queue duration histogram (5m increase)",
     "type": "graph",
     "description": "The bigger value for all lines, the better it is.\n\n10s line on level 40% means: less than 40% of jobs was queued in less than 10s. So having 1s line at the level of 100% is what would be the best.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(job_queue_duration_seconds_bucket{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\", le=\"1\"}[5m])) by (shared_runner, jobs_running_for_project) / sum(increase(job_queue_duration_seconds_count{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\"}[5m])) by (shared_runner, jobs_running_for_project)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "shared: {{shared_runner}} - running_jobs: {{jobs_running_for_project}} - 1s",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(increase(job_queue_duration_seconds_bucket{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\", le=\"3\"}[5m])) by (shared_runner, jobs_running_for_project) / sum(increase(job_queue_duration_seconds_count{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\"}[5m])) by (shared_runner, jobs_running_for_project)",
       "legendFormat": "shared: {{shared_runner}} - running_jobs: {{jobs_running_for_project}} - 3s"
      },
      {
       "expr": "sum(increase(job_queue_duration_seconds_bucket{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\", le=\"10\"}[5m])) by (shared_runner, jobs_running_for_project) / sum(increase(job_queue_duration_seconds_count{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\"}[5m])) by (shared_runner, jobs_running_for_project)",
       "legendFormat": "shared: {{shared_runner}} - running_jobs: {{jobs_running_for_project}} - 10s"
      },
      {
       "expr": "sum(increase(job_queue_duration_seconds_bucket{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\", le=\"30\"}[5m])) by (shared_runner, jobs_running_for_project) / sum(increase(job_queue_duration_seconds_count{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\"}[5m])) by (shared_runner, jobs_running_for_project)",
       "legendFormat": "shared: {{shared_runner}} - running_jobs: {{jobs_running_for_project}} - 30s"
      },
      {
       "expr": "sum(increase(job_queue_duration_seconds_bucket{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\", le=\"60\"}[5m])) by (shared_runner, jobs_running_for_project) / sum(increase(job_queue_duration_seconds_count{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\"}[5m])) by (shared_runner, jobs_running_for_project)",
       "legendFormat": "shared: {{shared_runner}} - running_jobs: {{jobs_running_for_project}} - 1m"
      },
      {
       "expr": "sum(increase(job_queue_duration_seconds_bucket{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\", le=\"300\"}[5m])) by (shared_runner, jobs_running_for_project) / sum(increase(job_queue_duration_seconds_count{environment=~\"$gitlab_env\", jobs_running_for_project=~\"$jobs_running_for_project\"}[5m])) by (shared_runner, jobs_running_for_project)",
       "legendFormat": "shared: {{shared_runner}} - running_jobs: {{jobs_running_for_project}} - 5m"
      }
     ]
    }
   ]
  },
  {
   "title": "Sidekiq & API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sidekiq Queues",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sidekiq_queue_size{environment=~\"$gitlab_env\",name=~\"pipeline.*\"} and on (fqdn) gitlab:redis_master",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "API Workers Load1",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{tier=\"sv\", environment=\"$gitlab_env\", type=\"api\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg(node_load1{tier=\"sv\", environment=\"$gitlab_env\", type=\"api\"})",
       "legendFormat": "AVG"
      }
     ]
    },
    {
     "title": "`jobs/request` requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gitlab_workhorse_http_request_duration_seconds_count{environment=\"$gitlab_env\", route=~\".*/api/v4/jobs/request.*\"}[5m]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "amount",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Job requests on Runners (5m)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gitlab_runner_api_request_statuses_total{instance=~\"${runner_managers:pipe}\",endpoint=~\"${runner_request_endpoint_status}\"}[5m])) by (job, status, endpoint)",
       "legendFormat": "{{job}} - {{endpoint}} - {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs running on runners owned by GitLab Inc. (part I)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Jobs running on runners owned by GitLab Inc. (by instance)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs running on runners owned by GitLab Inc. (by worker)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (instance, runner)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} - {{runner}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs running on runners owned by GitLab Inc. (by runner type)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Jobs running on runners owned by GitLab Inc. (part II)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "Jobs running on runners owned by GitLab Inc. (by Runner's state)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Jobs running on runners owned by GitLab Inc. (by Runner's stage)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (exported_stage)",
     "legendFormat": "{{exported_stage}}"
    }
   ]
  },
  {
   "title": "Jobs running on runners owned by GitLab Inc. (by Runner's executor_stage)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (executor_stage)",
     "legendFormat": "{{executor_stage}}"
    }
   ]
  },
  {
   "title": "Jobs started on Runners owned by GitLab Inc.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Jobs started on Runners",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_runner_jobs_total{instance=~\"${runner_managers:pipe}\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Runner limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Concurrent by job",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (job) / sum(gitlab_runner_concurrent{instance=~\"${runner_managers:pipe}\"}) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Concurrent by instance",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (instance) / sum(gitlab_runner_concurrent{instance=~\"${runner_managers:pipe}\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Limit by worker",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (instance, runner) / sum(gitlab_runner_limit{instance=~\"${runner_managers:pipe}\"}) by (instance, runner)",
       "legendFormat": "{{instance}} - {{runner}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs failures on Runners",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs failures on Runners (by instance)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(gitlab_runner_failed_jobs_total{instance=~\"${runner_managers:pipe}\",failure_reason=~\"$runner_job_failure_reason\"}[1m])) by (instance, failure_reason)",
       "legendFormat": "{{instance}} - {{failure_reason}}"
      },
      {
       "expr": "AVG(irate(gitlab_runner_failed_jobs_total{instance=~\"${runner_managers:pipe}\",failure_reason=~\"$runner_job_failure_reason\"}[1m]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Jobs failures on Runners (by Runner type)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(gitlab_runner_failed_jobs_total{instance=~\"${runner_managers:pipe}\",failure_reason=~\"$runner_job_failure_reason\"}[1m])) by (job, failure_reason)",
       "legendFormat": "{{job}} - {{failure_reason}}"
      },
      {
       "expr": "AVG(irate(gitlab_runner_failed_jobs_total{instance=~\"${runner_managers:pipe}\",failure_reason=~\"$runner_job_failure_reason\"}[1m]))",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Auto-scale machines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auto-scale machines states",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_autoscaling_machine_states{executor=\"docker+machine\", instance=~\"${runner_managers:pipe}\"}) by (job, state)",
       "legendFormat": "{{job}}: {{state}}"
      }
     ]
    },
    {
     "title": "Auto-scaled machines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_autoscaling_machine_states{executor=\"docker+machine\", instance=~\"${runner_managers:pipe}\"}) by (job, instance)",
       "legendFormat": "{{job}}: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Machine operations rates and stuck machines count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of machine creation / deletion",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_runner_autoscaling_actions_total{executor=\"docker+machine\", instance=~\"${runner_managers:pipe}\"}[1m])) by (job, action)",
       "legendFormat": "{{job}}: {{action}}"
      }
     ]
    },
    {
     "title": "Machines creation timing",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(gitlab_runner_autoscaling_machine_creation_duration_seconds_bucket{executor=\"docker+machine\",instance=~\"${runner_managers:pipe}\"}[$__interval])) by (job,le))",
       "legendFormat": "{{job}}: 50th"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(gitlab_runner_autoscaling_machine_creation_duration_seconds_bucket{executor=\"docker+machine\",instance=~\"${runner_managers:pipe}\"}[$__interval])) by (job,le))",
       "legendFormat": "{{job}}: 90th"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(gitlab_runner_autoscaling_machine_creation_duration_seconds_bucket{executor=\"docker+machine\",instance=~\"${runner_managers:pipe}\"}[$__interval])) by (job,le))",
       "legendFormat": "{{job}}: 99th"
      }
     ]
    },
    {
     "title": "Stuck machines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_jobs{exported_stage=~\"canceled|timedout\",instance=~\"${runner_managers:pipe}\"}) by (instance, stage)",
       "legendFormat": "{{instance}}: {{stage}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Autoscale providers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "GCP Machines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(max(label_replace(label_replace(label_replace(gcp_exporter_instances_count{project=\"gitlab-ci-155816\"}, \"runner_group\", \"$2\", \"tags\", \"(.*,)?(srm|prm|gsrm)(,.*)?\"), \"gitlab_instance\", \"$2\", \"tags\", \"(.*,)?(gitlab-com|dev-gitlab-org)(,.*)?\"), \"runner_subgroup\", \"$2\", \"tags\", \"(.*,)?((.*)-group)(,.*)?\")) by (zone, runner_group, gitlab_instance, runner_subgroup)) by (runner_group)",
       "legendFormat": "{{runner_group}}"
      }
     ]
    }
   ]
  },
  { "title": "Job durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Job durations histogram by runner type",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(gitlab_runner_job_duration_seconds_bucket{instance=~\"${runner_managers:pipe}\"}[5m])) by (job, le))",
     "legendFormat": "25th: {{job}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(gitlab_runner_job_duration_seconds_bucket{instance=~\"${runner_managers:pipe}\"}[5m])) by (job, le))",
     "legendFormat": "50th: {{job}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(gitlab_runner_job_duration_seconds_bucket{instance=~\"${runner_managers:pipe}\"}[5m])) by (job, le))",
     "legendFormat": "75th: {{job}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(gitlab_runner_job_duration_seconds_bucket{instance=~\"${runner_managers:pipe}\"}[4m])) by (job, le))",
     "legendFormat": "90th: {{job}} "
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_runner_job_duration_seconds_bucket{instance=~\"${runner_managers:pipe}\"}[5m])) by (job, le))",
     "legendFormat": "95th: {{job}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitlab_runner_job_duration_seconds_bucket{instance=~\"${runner_managers:pipe}\"}[5m])) by (job, le))",
     "legendFormat": "99th: {{job}}"
    }
   ]
  },
  {
   "title": "Job durations histogram by worker",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(gitlab_runner_job_duration_seconds_bucket{instance=~\"${runner_managers:pipe}\"}[5m])) by (job, runner, le))",
     "legendFormat": "50th: {{job}} - {{runner}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(gitlab_runner_job_duration_seconds_bucket{instance=~\"${runner_managers:pipe}\"}[4m])) by (job, runner, le))",
     "legendFormat": "90th: {{job}} - {{runner}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_runner_job_duration_seconds_bucket{instance=~\"${runner_managers:pipe}\"}[5m])) by (job, runner, le))",
     "legendFormat": "95th: {{job}} - {{runner}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitlab_runner_job_duration_seconds_bucket{instance=~\"${runner_managers:pipe}\"}[5m])) by (job, runner, le))",
     "legendFormat": "99th: {{job}} - {{runner}}"
    }
   ]
  },
  {
   "title": "Jobs distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shared Runners - Running Jobs Origin",
     "type": "graph",
     "description": "What triggered the job, and how many of these are there?",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ci_running_builds{shared_runner=\"yes\",fqdn=~\"$gl_monitor_fqdn\",mirror=\"yes\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Mirror",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(ci_running_builds{shared_runner=\"yes\",fqdn=~\"$gl_monitor_fqdn\",triggered=\"yes\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Trigger Request",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(ci_running_builds{shared_runner=\"yes\",fqdn=~\"$gl_monitor_fqdn\",scheduled=\"yes\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Scheduled",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(ci_running_builds{shared_runner=\"yes\",fqdn=~\"$gl_monitor_fqdn\",scheduled!=\"yes\",triggered!=\"yes\",mirror!=\"yes\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Push",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Specific Runners - Running Jobs Origin",
     "type": "graph",
     "description": "What triggered the job, and how many of these are there?",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ci_running_builds{shared_runner=\"no\",triggered=\"yes\",fqdn=~\"$gl_monitor_fqdn\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Triggered",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(ci_running_builds{shared_runner=\"no\",scheduled=\"yes\",fqdn=~\"$gl_monitor_fqdn\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Scheduled",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(ci_running_builds{shared_runner=\"no\",mirror=\"yes\",fqdn=~\"$gl_monitor_fqdn\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Mirroring",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(ci_running_builds{shared_runner=\"no\",mirror=\"no\",triggered=\"no\",scheduled=\"no\",fqdn=~\"$gl_monitor_fqdn\",has_minutes=~\"$has_minutes\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Push",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Shared runners - jobs distribution by runner",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(ci_running_builds{shared_runner=\"yes\",fqdn=~\"$gl_monitor_fqdn\",has_minutes=~\"$has_minutes\"}) by (runner)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "runner {{runner}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending jobs with shared runners enabled",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(ci_pending_builds{fqdn=~\"$gl_monitor_fqdn\", shared_runners=\"yes\",has_minutes=~\"$has_minutes\"}) by (namespace)",
       "legendFormat": "Namespace: {{namespace}}"
      }
     ]
    },
    {
     "title": "Running jobs on Shared Runners",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "sum(ci_running_builds{fqdn=~\"$gl_monitor_fqdn\", shared_runner=\"yes\",has_minutes=~\"$has_minutes\"}) by (namespace)",
       "legendFormat": "Namespace: {{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runner manager resources usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "instance:node_memory_utilization:ratio{instance=~\"${runner_managers:pipe}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 65 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "instance:node_cpu_utilization:ratio{instance=~\"${runner_managers:pipe}\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 65 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"${runner_managers:pipe}\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=~\"${runner_managers:pipe}\"} / process_max_fds{instance=~\"${runner_managers:pipe}\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk available",
     "type": "graph",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 79 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "instance:node_filesystem_avail:ratio{instance=~\"${runner_managers:pipe}\",fstype=\"ext4\"}",
       "legendFormat": "{{instance}} - {{device}}"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 79 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "instance:node_disk_writes_completed:irate1m{instance=~\"${runner_managers:pipe}\"}",
       "legendFormat": "{{instance}} - writes"
      },
      {
       "expr": "instance:node_disk_reads_completed:irate1m{instance=~\"${runner_managers:pipe}\"}",
       "legendFormat": "{{instance}} - reads"
      }
     ]
    }
   ]
  },
  {
   "title": "Workhorse Long polling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests state counter",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_workhorse_builds_register_handler_requests[5m])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Requests open in given state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_workhorse_builds_register_handler_open) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workhorse Queueing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests handled",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_workhorse_queueing_busy{queue_name=\"ci_api_job_requests\",job=\"gitlab-workhorse-api\"})",
       "legendFormat": "handled"
      },
      {
       "expr": "sum(gitlab_workhorse_queueing_limit{queue_name=\"ci_api_job_requests\",job=\"gitlab-workhorse-api\"})",
       "legendFormat": "handling limit"
      }
     ]
    },
    {
     "title": "Requests queued (max)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(gitlab_workhorse_queueing_waiting{queue_name=\"ci_api_job_requests\",job=\"gitlab-workhorse-api\"})",
       "legendFormat": "max waiting in queue"
      },
      {
       "expr": "max(gitlab_workhorse_queueing_queue_limit{queue_name=\"ci_api_job_requests\",job=\"gitlab-workhorse-api\"})",
       "legendFormat": "queueing limit"
      },
      {
       "expr": "avg(gitlab_workhorse_queueing_waiting{queue_name=\"ci_api_job_requests\",job=\"gitlab-workhorse-api\"})",
       "legendFormat": "average waiting in queue"
      }
     ]
    },
    {
     "title": "Request Queueing Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 45 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(gitlab_workhorse_queueing_waiting_time_bucket{queue_name=\"ci_api_job_requests\",job=\"gitlab-workhorse-api\"}[5m])) by (le))",
       "legendFormat": "50th"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(gitlab_workhorse_queueing_waiting_time_bucket{queue_name=\"ci_api_job_requests\",job=\"gitlab-workhorse-api\"}[5m])) by (le))",
       "legendFormat": "75th"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(gitlab_workhorse_queueing_waiting_time_bucket{queue_name=\"ci_api_job_requests\",job=\"gitlab-workhorse-api\"}[5m])) by (le))",
       "legendFormat": "90th"
      }
     ]
    }
   ]
  },
  {
   "title": "Workhorse Queueing errors and limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests handling limit",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 56 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(gitlab_workhorse_queueing_limit{job=\"gitlab-workhorse-api\",queue_name=\"ci_api_job_requests\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Handling limit",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Requests queueing limit",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 2, "x": 2, "y": 56 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(gitlab_workhorse_queueing_queue_limit{job=\"gitlab-workhorse-api\",queue_name=\"ci_api_job_requests\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Handling limit",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Requests queueing timeout",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 2, "x": 4, "y": 56 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(gitlab_workhorse_queueing_queue_timeout{job=\"gitlab-workhorse-api\",queue_name=\"ci_api_job_requests\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Queueing timeout",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Queueing errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 56 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_workhorse_queueing_errors{queue_name=\"ci_api_job_requests\",job=\"gitlab-workhorse-api\"}[5m])) by (type)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{type}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache performance",
     "type": "graph",
     "description": "Relation of jobs in cache archive/restore stage to all jobs.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_runner_jobs{exported_stage=~\"(archive|restore)_cache\",instance=~\"${runner_managers:pipe}\"}) by (instance) / sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (instance)",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "avg(sum(gitlab_runner_jobs{exported_stage=~\"(archive|restore)_cache\",instance=~\"${runner_managers:pipe}\"}) by (instance) / sum(gitlab_runner_jobs{instance=~\"${runner_managers:pipe}\"}) by (instance))",
       "legendFormat": "AVG"
      }
     ]
    }
   ]
  },
  {
   "title": "Runners errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runners error 5m rate (by job&level)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gitlab_runner_errors_total{instance=~\"${runner_managers:pipe}\"}[5m])) by (job,level)",
       "legendFormat": "{{job}}: {{level}}"
      }
     ]
    },
    {
     "title": "Runners error 5m rate (by instance&level)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gitlab_runner_errors_total{instance=~\"${runner_managers:pipe}\"}[5m])) by (instance,level)",
       "legendFormat": "{{instance}}: {{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runners uptime & version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runners uptime",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{instance=~\"${runner_managers:pipe}\",job=~\"${runner_type}\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Runner versions",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "gitlab_runner_version_info{instance=~\"${runner_managers:pipe}\"}",
       "legendFormat": "{{instance}}: {{version}} ({{revision}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Traces archiving",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Trace archiving failures rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(job_trace_archive_failed_total[$__interval])) by (fqdn)",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "Unarchived traces",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ci_unarchived_traces{fqdn=~\"$gl_monitor_fqdn\"}",
       "legendFormat": "Unarchived traces"
      }
     ]
    }
   ]
  },
  {
   "title": "CI Artifacts operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Artifacts operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gitlab_workhorse_multipart_upload_bytes{type=\"artifacts\"}[1h]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Uploads size",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(increase(gitlab_workhorse_sendfile_bytes{type=\"artifacts\"}[1h]))",
       "legendFormat": "Downloads size"
      }
     ]
    },
    {
     "title": "Artifacts operations - requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gitlab_workhorse_multipart_upload_requests{type=\"artifacts\"}[1h]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Uploads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(increase(gitlab_workhorse_sendfile_requests{type=\"artifacts\"}[1h]))",
       "legendFormat": "Downloads"
      }
     ]
    },
    {
     "title": "Artifacts operations - files",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gitlab_workhorse_multipart_upload_files{type=\"artifacts\"}[1h]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Uploads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Git operations by CI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git operations by CI",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(sum(increase(gitlab_workhorse_git_http_bytes{agent=\"gitlab-ci\"}[1h])) by (direction))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Size ({{direction}})",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Git operations by CI - requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gitlab_workhorse_git_http_requests{agent=\"gitlab-ci\"}[1h]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Requests",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CI bandwidth usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Artifacts uploads vs. all uploads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_workhorse_multipart_upload_bytes{type=\"artifacts\"}[1h])) / sum(rate(gitlab_workhorse_multipart_upload_bytes[1h]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Artifacts uploads vs. all uploads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Artifacts downloads vs. all downloads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_workhorse_sendfile_bytes{type=\"artifacts\"}[1h])) / sum(rate(gitlab_workhorse_sendfile_bytes[1h]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Artifacts downloads vs. all downloads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CI Git HTTP transfer vs. all Git HTTP transfer",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_workhorse_git_http_bytes{agent=\"gitlab-ci\"}[1h])) / sum(rate(gitlab_workhorse_git_http_bytes[1h]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "CI Git HTTP transfer vs. all Git HTTP transfer",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}