{
 "title": "ci-runners: Incident Support: gitlab-application",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5132059854 at Wed Sep 20 18:47:41 UTC 2023",
 "tags": [
  "managed",
  "ci-runners",
  "type:ci-runners",
  "managed",
  "ci-runners:incident-support",
  "ci-runners:incident-gl-app"
 ],
 "time": { "from": "now-3h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "shard",
    "query": "label_values(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",job=~\".*\",job!~\"omnibus-runners|gprd-runner\",shard!=\"default\"}, shard)\n"
   },
   {
    "name": "runner_manager",
    "query": "query_result(label_replace(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",shard=~\"$shard\"}, \"fqdn\", \"$1.*\", \"instance\", \"([^:]*)(:[0-9]+)?$\"))\n"
   },
   {
    "name": "project_jobs_running",
    "query": "label_values(gitlab_runner_job_queue_duration_seconds_sum{environment=~\"$environment\",stage=~\"$stage\"}, project_jobs_running)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  },
  {
   "title": "ci-runners Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ci-runners Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "ci-runners Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ci-runners error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ci-runners error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ci-runners Service | Errors"
    }
   ]
  },
  {
   "title": "ci-runners Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "Jobs running on GitLab Inc. runners (by shard)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 0, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  gitlab_runner_jobs{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Jobs started on runners (by shard)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 4.8, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{ shard }}"
    },
    {
     "expr": "avg (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Pending job queue duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 4.8, "x": 9.6, "y": 1000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(gitlab_runner_job_queue_duration_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", project_jobs_running=~\"$project_jobs_running\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pending jobs queue size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 14.399999999999999, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, runner_type) (\n    increase(gitlab_ci_queue_size_total_bucket{environment=~\"$environment\", stage=~\"$stage\"}[$__rate_interval])\n  )\n)\n",
     "legendFormat": "{{runner_type}}"
    }
   ]
  },
  {
   "title": "gitlab-application caused incident notes",
   "type": "text",
   "gridPos": { "h": 7, "w": 4.8, "x": 19.2, "y": 1000 },
   "content": "Most logic of how pipelines and jobs are being handled is happening in GitLab. Runner is the last\nelement of the chain - it asks for a job and receives the payload **if any job was scheduled by GitLab\nfor that Runner**.\n\n**Please remember: It's Runner that asks for jobs. It's Runner that sends back the responses. Apart of\nCI Web Terminal feature (which we haven't configured on our runners fleet) the communicatation always\ngoes in this direction - from Runner to GitLab.**\n\nTherefore Runners are vulnerable for any problems happening on GitLab side, whether these are problem with\nAPI (that Runner uses to talk with GitLab), problems with skidekiq (which is used to handle many background\ntaksks related to pipelines and jobs handling) or queueing and long polling that we've implemented in\nGitLab Workhose.\n\nKnown problem indicators:\n- increased number of 5xx errors observed by Runner for some requests that they are doing against GitLab's API,\n- increased size of pipeline.* queues in sidekiq,\n- general load increase on API nodes,\n- misbehavior of workhorse long polling,\n- increased timing of workhorse queueing.\n\nGitLab Application problems affecting Runners are usually caused by three reasons:\n- Database slowness that affects every part of the application stack. You can double check this with the dedicated\n  dashboard: open the `ci-runners Incident Dashboards` list and select `ci-runners: Incident Support: database`.\n  If the database is slow, then this should be our main concern and efforts should be shifted there.\n\n  Please note that the `/api/v4/jobs/request` endpoint is known of being the main cause of database problems\n  when it goes for CI (the size of `ci_builds` and complexity of jobs scheduling query is enormous) and usually the\n  main victim of such slowness in the CI area. There is an ongoing work on fixing this part.\n\n- Sidekiq problems. Any Sidekiq problems that affect the time of processing of `pipeline.*` queues may affect the\n  affect the user experience, especially when it goes for transitioning jobs and pipelines between different states.\n  If Sidekiq metrics for `pipeline.*` look strange, double check that we don't have load problem on the sidekiq nodes\n  nor that there are no problems with Redis.\n\n- Workhorse polling and queueing problems. All requests made by Runner are going through GitLab Workhorse. For the\n  most important endpoint - `POST /api/v4/jobs/request` - we've implemented a long polling mechanism that reduces\n  the amount of requests created by Runners. All the requests can be also queued on the Workhorse level if Rails\n  is slow in handling them. Therefore any misconfiguration here may lead to problems with requests handling. Double\n  check that there was no changes in Workhorse configuration or Workhorse itself if there are any problems observed\n  on the Workhorse graphs.\n"
  },
  {
   "title": "Runner requests for request_job [.*]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (\n  increase(\n    gitlab_runner_api_request_statuses_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\",endpoint=\"request_job\",status=~\".*\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Runner requests for update_job [.*]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (\n  increase(\n    gitlab_runner_api_request_statuses_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\",endpoint=\"update_job\",status=~\".*\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Runner requests for patch_trace [.*]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (\n  increase(\n    gitlab_runner_api_request_statuses_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\",endpoint=\"patch_trace\",status=~\".*\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Runner requests for request_job [(4|5)..]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (\n  increase(\n    gitlab_runner_api_request_statuses_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\",endpoint=\"request_job\",status=~\"(4|5)..\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Runner requests for update_job [(4|5)..]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (\n  increase(\n    gitlab_runner_api_request_statuses_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\",endpoint=\"update_job\",status=~\"(4|5)..\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Runner requests for patch_trace [(4|5)..]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (\n  increase(\n    gitlab_runner_api_request_statuses_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\",endpoint=\"patch_trace\",status=~\"(4|5)..\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Sidekiq CI and Runner in flight jobs",
   "type": "graph",
   "description": "This graph shows the rate of the Sidekiq jobs (related to CI/CD and Runner) that have been enqueued but not yet\nfinished. A steep rise here means a backlog of jobs is being built and this means that Sidekiq is most probably\nhaving trouble keeping up.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum by (worker) (\n    ci_sidekiq_jobs_inflight:rate_5m{environment=\"$environment\", stage=\"$stage\"}\n  )\n)\n",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "loadavg5 per core",
   "type": "graph",
   "description": "Loadavg (5 minute) per core, below 1 is better.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5000 },
   "yaxes": [
    { "format": "short", "label": "loadavg5" }
   ],
   "targets": [
    {
     "expr": "avg by (environment, type, stage, fqdn) (node_load5{environment=\"$environment\", stage=\"$stage\", type=\"api\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", environment=\"$environment\", stage=\"$stage\", type=\"api\"})\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "`jobs/request` requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job:gitlab_workhorse_http_request_duration_seconds_count:rate1m{environment=~\"$environment\",stage=~\"$stage\",route=~\".*/api/v4/jobs/request.*\"}\n)\n",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Workhorse long polling - request statuses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  increase(gitlab_workhorse_builds_register_handler_requests{environment=~\"$environment\",stage=~\"$stage\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Workhorse long polling - open requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (\n  gitlab_workhorse_builds_register_handler_open{environment=~\"$environment\",stage=~\"$stage\"}\n)\n",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Workhorse queueing errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (\n  increase(\n    gitlab_workhorse_queueing_errors{environment=~\"$environment\",stage=~\"$stage\",queue_name=\"ci_api_job_requests\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Workhorse queueing - handled requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  gitlab_workhorse_queueing_busy{environment=~\"$environment\",stage=~\"$stage\",queue_name=\"ci_api_job_requests\"}\n)\n",
     "legendFormat": "handled"
    },
    {
     "expr": "sum(\n  gitlab_workhorse_queueing_limit{environment=~\"$environment\",stage=~\"$stage\",queue_name=\"ci_api_job_requests\"}\n)\n",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Workhorse queueing - queued requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  gitlab_workhorse_queueing_waiting{environment=~\"$environment\",stage=~\"$stage\",queue_name=\"ci_api_job_requests\"}\n)\n",
     "legendFormat": "queued"
    },
    {
     "expr": "sum(\n  gitlab_workhorse_queueing_queue_limit{environment=~\"$environment\",stage=~\"$stage\",queue_name=\"ci_api_job_requests\"}\n)\n",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Workhorse queueing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7000 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    rate(\n      gitlab_workhorse_queueing_waiting_time_bucket{environment=~\"$environment\",stage=~\"$stage\",queue_name=\"ci_api_job_requests\"}[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le) (\n    rate(\n      gitlab_workhorse_queueing_waiting_time_bucket{environment=~\"$environment\",stage=~\"$stage\",queue_name=\"ci_api_job_requests\"}[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(\n      gitlab_workhorse_queueing_waiting_time_bucket{environment=~\"$environment\",stage=~\"$stage\",queue_name=\"ci_api_job_requests\"}[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(\n      gitlab_workhorse_queueing_waiting_time_bucket{environment=~\"$environment\",stage=~\"$stage\",queue_name=\"ci_api_job_requests\"}[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "99th percentile"
    }
   ]
  }
 ]
}