{
 "title": "ci-runners: Incident Support: autoscaling-new",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7529110174 at Wed Aug  7 17:27:19 UTC 2024",
 "tags": [
  "managed",
  "ci-runners",
  "type:ci-runners",
  "managed",
  "ci-runners:incident-support",
  "ci-runners:incident-as"
 ],
 "time": { "from": "now-3h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "type",
    "query": "label_values(gitlab_runner_version_info{job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", environment=\"$environment\"}, type)\n"
   },
   {
    "name": "shard",
    "query": "label_values(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",type=~\"$type\",shard!=\"default\"}, shard)\n"
   },
   {
    "name": "runner_manager",
    "query": "query_result(label_replace(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",shard=~\"$shard\"}, \"fqdn\", \"$1.*\", \"instance\", \"([^:]*)(:[0-9]+)?$\"))\n"
   },
   {
    "name": "project_jobs_running",
    "query": "label_values(gitlab_runner_job_queue_duration_seconds_sum{environment=~\"$environment\",stage=~\"$stage\"}, project_jobs_running)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  },
  {
   "title": "ci-runners Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type, __tenant_id__) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ci-runners Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "ci-runners Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ci-runners error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ci-runners error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_errors:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_errors:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type, __tenant_id__) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ci-runners Service | Errors"
    }
   ]
  },
  {
   "title": "ci-runners Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "Jobs running on GitLab Inc. runners (by shard)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 0, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  gitlab_runner_jobs{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Jobs started on runners (by shard)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 4.8, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{ shard }}"
    },
    {
     "expr": "avg (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Pending job queue duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 4.8, "x": 9.6, "y": 1000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(gitlab_runner_job_queue_duration_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", project_jobs_running=~\"$project_jobs_running\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pending jobs queue size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 14.399999999999999, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(runner_type) (\n  gitlab_ci_current_queue_size{environment=~\"$environment\", stage=~\"$stage\"}\n)\n",
     "legendFormat": "{{runner_type}}"
    }
   ]
  },
  {
   "title": "autoscaling-new caused incident notes",
   "type": "text",
   "gridPos": { "h": 7, "w": 4.8, "x": 19.2, "y": 1000 },
   "content": "In short: problems with autoscaling will reduce (even totally) the capacity of our Runners.\n\n**It's recommended to review the graphs after limiting the shard variable to only\nthe part of Runners that we want to analyse.** Otherwise the number of different lines\nmay be overwhelming. Please also remember that **different shards have different autosacling\nsettings**, where the `shared` one is the most outstanding at it creates a VM dedicated for\nevery job and removes it just after the job is finished.\n\n**We're currently in the process of moving to a new autoscaling mechanism.** For now there are no\nknown guidelines as to how to work with it and what to review in case of troubles. We will be\nudpating this description after getting some more experience with using that new method.\n"
  },
  {
   "title": "Fleeting instances saturation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3000 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  fleeting_provisioner_instances{state=~\"running|deleting\", environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}\n)\n/\nsum by(shard) (\n  fleeting_provisioner_max_instances{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Taskscaler tasks saturation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3000 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  fleeting_taskscaler_tasks{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\", state!~\"idle|reserved\"}\n)\n/\nsum by(shard) (\n  fleeting_provisioner_max_instances{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}\n  *\n  fleeting_taskscaler_max_tasks_per_instance{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Taskscaler max use count per instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  fleeting_taskscaler_max_use_count_per_instance{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Fleeting instances states",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard, state) (\n  fleeting_provisioner_instances{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{shard}}: {{state}}"
    }
   ]
  },
  {
   "title": "Fleeting instance operations rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(shard, operation) (\n  rate(\n    fleeting_provisioner_instance_operations_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}: {{operation}}"
    }
   ]
  },
  {
   "title": "Fleeting internal operations rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(shard, operation) (\n  rate(\n    fleeting_provisioner_internal_operations_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}: {{operation}}"
    }
   ]
  },
  {
   "title": "Fleeting missed updates rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  rate(\n    fleeting_provisioner_missed_updates_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Fleeting instance creation timing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    fleeting_provisioner_instance_creation_time_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleeting instance is_running timing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    fleeting_provisioner_instance_is_running_time_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleeting instance deletion timing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    fleeting_provisioner_instance_deletion_time_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleeting instance life duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    fleeting_provisioner_instance_life_duration_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Taskscaler tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 6000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard, state) (\n  fleeting_taskscaler_tasks{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{shard}}: {{state}}"
    }
   ]
  },
  {
   "title": "Taskscaler desired instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4.8, "x": 4.8, "y": 6000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  fleeting_taskscaler_desired_instances{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Taskscaler operations rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4.8, "x": 9.6, "y": 6000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(shard, operation) (\n  rate(\n    fleeting_taskscaler_task_operations_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}: {{operation}}"
    }
   ]
  },
  {
   "title": "Taskscaler scale operations rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4.8, "x": 14.399999999999999, "y": 6000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(shard, operation) (\n  rate(\n    fleeting_taskscaler_scale_operations_total{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{shard}}: {{operation}}"
    }
   ]
  },
  {
   "title": "Taskscaler instance readiness timing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4.8, "x": 19.2, "y": 6000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(\n    fleeting_taskscaler_task_instance_readiness_time_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval]\n  )\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}