{
 "title": "ci-runners: Incident Support: autoscaling",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4012289382 at Tue Mar 28 02:11:40 UTC 2023",
 "tags": [
  "managed",
  "ci-runners",
  "type:ci-runners",
  "managed",
  "ci-runners:incident-support",
  "ci-runners:incident-as"
 ],
 "time": { "from": "now-3h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "shard",
    "query": "label_values(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",job=~\".*\",job!~\"omnibus-runners|gprd-runner\",shard!=\"default\"}, shard)\n"
   },
   {
    "name": "runner_manager",
    "query": "query_result(label_replace(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",shard=~\"$shard\"}, \"fqdn\", \"$1.*\", \"instance\", \"([^:]*)(:[0-9]+)?$\"))\n"
   },
   {
    "name": "jobs_running_for_project",
    "query": "label_values(job_queue_duration_seconds_sum{environment=~\"$environment\",stage=~\"$stage\"}, jobs_running_for_project)\n"
   },
   {
    "name": "gcp_exporter",
    "query": "label_values(gcp_exporter_region_quota_limit{environment=~\"$environment\",stage=~\"$stage\"}, instance)\n"
   },
   {
    "name": "gcp_project",
    "query": "label_values(gcp_exporter_region_quota_limit{environment=~\"$environment\",stage=~\"$stage\"}, project)\n"
   },
   {
    "name": "gcp_region",
    "query": "label_values(gcp_exporter_region_quota_usage{environment=~\"$environment\",stage=~\"$stage\"}, region)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  },
  {
   "title": "ci-runners Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ci-runners Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "ci-runners Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ci-runners error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ci-runners error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",tier=\"runners\",type=\"ci-runners\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ci-runners Service | Errors"
    }
   ]
  },
  {
   "title": "ci-runners Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval])\n",
     "legendFormat": "ci-runners RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\",stage=\"$stage\",tier=\"runners\",type=\"ci-runners\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "Jobs running on GitLab Inc. runners (by shard)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 0, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (gitlab_runner_jobs{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"})",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Jobs started on runners (by shard)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 4.8, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{ shard }}"
    },
    {
     "expr": "avg (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Pending job queue duration histogram",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 4.8, "x": 9.6, "y": 1000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(job_queue_duration_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", jobs_running_for_project=~\"$jobs_running_for_project\"}[$__rate_interval])\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pending jobs queue size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 14.399999999999999, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, runner_type) (\n    increase(gitlab_ci_queue_size_total_bucket{environment=~\"$environment\", stage=~\"$stage\"}[$__rate_interval])\n  )\n)\n",
     "legendFormat": "{{runner_type}}"
    }
   ]
  },
  {
   "title": "autoscaling caused incident notes",
   "type": "text",
   "gridPos": { "h": 7, "w": 4.8, "x": 19.2, "y": 1000 },
   "content": "In short: problems with autoscaling will reduce (even totally) the capacity of our Runners.\n\n**It's recommended to review the graphs after limiting the shard variable to only\nthe part of Runners that we want to analyse.** Otherwise the number of different lines\nmay be overwhelming. Please also remember that **different shards have different autosacling\nsettings**, where the `shared` one is the most outstanding at it creates a VM dedicated for\nevery job and removes it just after the job is finished.\n\nKnown problem indicators:\n- high number of VMs in `creating` state for a longer period,\n- unnatural shape of the `creating` state VMs line,\n- `idle` VMs value constantly near `0`,\n- VM operations going up-and-down in a sinewave-like shape,\n- VMs creation timing increased above the usual average,\n- exceeding GCP quotas.\n\nAutoscaling problems are usually caused by three possible reasons:\n- Exceeding GCP quotas (especially the API ones). For that go to the GCP console\n  to projects where autoscaled VMs are created for the shard (note that we're currently\n  spliting shards between multiple projects **so this needs to be checked in all of them**)\n  and check if we're not exceeding the API quotas. Especially the `read requests` and\n  `operation read requests`.\n- Bug in configuration of autoscaling. Wrong configuration may effect with Docker Machine not\n  being able to create the VM or VM being not accessible after it was created. Double check\n  if there were any changes made in Runner Manager's `config.toml` file, in the `[docker.machine]`\n  section.\n- Docker Machine bug. Very rare, as we've probably already caught all of them, but to be sure\n  check if there was no updates of used Docker Machine version just before the incideent happened.\n"
  },
  {
   "title": "Autoscaled VMs states",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(shard, state) (\n  gitlab_runner_autoscaling_machine_states{environment=~\"$environment\", stage=~\"$stage\", executor=\"docker+machine\", instance=~\"${runner_manager:pipe}\"}\n)\n",
     "legendFormat": "{{shard}}: {{state}}"
    }
   ]
  },
  {
   "title": "Autoscaled VM operations rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (shard, action) (\n  increase(gitlab_runner_autoscaling_actions_total{environment=~\"$environment\", stage=~\"$stage\", executor=\"docker+machine\", instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{shard}}: {{action}}"
    }
   ]
  },
  {
   "title": "Autoscaled VMs creation timing",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3000 },
   "targets": [
    {
     "expr": "sum by (le) (\n  increase(gitlab_runner_autoscaling_machine_creation_duration_seconds_bucket{environment=~\"$environment\", stage=~\"$stage\", executor=\"docker+machine\",instance=~\"${runner_manager:pipe}\"}[$__rate_interval])\n)\n",
     "groupBy": [
      { "params": [ "$__rate_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GCP region quotas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4000 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(project, region, quota) (\n  (\n    gcp_exporter_region_quota_usage{environment=~\"$environment\", stage=~\"$stage\", instance=~\"$gcp_exporter\",project=~\"${gcp_project:pipe}\",region=~\"${gcp_region:pipe}\"}\n    /\n    gcp_exporter_region_quota_limit{environment=~\"$environment\", stage=~\"$stage\", instance=~\"$gcp_exporter\",project=~\"${gcp_project:pipe}\",region=~\"${gcp_region:pipe}\"}\n  ) > 0\n)\n",
     "legendFormat": "{{project}}: {{region}}: {{quota}}"
    },
    { "expr": "0.85", "legendFormat": "Soft SLO" },
    { "expr": "0.9", "legendFormat": "Hard SLO" }
   ]
  },
  {
   "title": "GCP instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (zone, machine_type_short, runner_group) (\n  label_replace(\n    label_replace(\n      gcp_exporter_instances_count{environment=~\"$environment\", stage=~\"$stage\", instance=~\"$gcp_exporter\",project=\"${gcp_project:pipe}\",zone=~\"(${gcp_region:pipe}).*\"},\n      \"machine_type_short\",\n      \"$1\",\n      \"machine_type\",\n      \".*/([^/]+)$\"\n    ),\n    \"runner_group\",\n    \"$2\",\n    \"tags\",\n    \"(.*,)?(srm|prm|gsrm)(,.*)?\"\n  )\n)\n",
     "legendFormat": "{{runner_group}} - {{zone}} - {{machine_type_short}}"
    }
   ]
  }
 ]
}