{
 "title": "ci-runners: Business metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7412578973 at Wed Jul 24 01:10:39 UTC 2024",
 "tags": [
  "managed",
  "ci-runners",
  "type:ci-runners",
  "managed"
 ],
 "time": { "from": "now-14d", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "type",
    "query": "label_values(gitlab_runner_version_info{job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", environment=\"$environment\"}, type)\n"
   },
   {
    "name": "shard",
    "query": "label_values(gitlab_runner_version_info{environment=~\"$environment\",stage=~\"$stage\",type=~\"$type\",shard!=\"default\"}, shard)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  },
  {
   "title": "Started jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1000 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(\n    gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",shard=~\"${shard:pipe}\"}[1d]\n  )\n)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Finished job minutes increase",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2000 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(shard) (\n  increase(gitlab_runner_job_duration_seconds_sum{environment=~\"$environment\",stage=~\"$stage\",shard=~\"${shard:pipe}\"}[1d])\n)/60\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Runner managers mean saturation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3000 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(shard) (gitlab_runner_jobs{environment=\"$environment\", stage=\"$stage\", job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", shard=~\"${shard:pipe}\"})\n/\nsum by(shard) (gitlab_runner_concurrent{environment=\"$environment\", stage=\"$stage\", job=~\"runners-manager|scrapeConfig/monitoring/prometheus-agent-runner\", shard=~\"${shard:pipe}\"})\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Jobs started on runners",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs started on runners (by shard)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4001 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(shard) (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",shard=~\"${shard:pipe}\"}[$__rate_interval])\n)\n",
       "legendFormat": "{{ shard }}"
      },
      {
       "expr": "avg (\n  increase(gitlab_runner_jobs_total{environment=~\"$environment\",stage=~\"$stage\",shard=~\"${shard:pipe}\"}[$__rate_interval])\n)\n",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Finised job minutes increase",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Finished job minutes increase",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4001 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(shard) (\n  increase(gitlab_runner_job_duration_seconds_sum{environment=~\"$environment\",stage=~\"$stage\",shard=~\"${shard:pipe}\"}[$__rate_interval])\n)/60\n",
       "legendFormat": "{{shard}}"
      },
      {
       "expr": "avg (\n  increase(gitlab_runner_job_duration_seconds_sum{environment=~\"$environment\",stage=~\"$stage\",shard=~\"${shard:pipe}\"}[$__rate_interval])\n)/60\n",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Finished job durations histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Finished job durations histogram",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6001 },
     "targets": [
      {
       "expr": "sum by (le) (\n  rate(gitlab_runner_job_duration_seconds_bucket{environment=~\"$environment\",stage=~\"$stage\",shard=~\"${shard:pipe}\"}[$__rate_interval])\n)\n",
       "groupBy": [
        { "params": [ "$__rate_interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{le}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}