{
 "title": "ClickHouse Cloud dashboard - mappelman",
 "description": "ClickHouse internal exporter metrics",
 "tags": [
  "unmanaged",
  "protected"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "Instance",
    "label": "Instance",
    "query": "Observability-Prod : ruy99n66gt.us-central1.gcp.clickhouse.cloud:8443, Observability-Staging : l2fq9dbbdq.us-central1.gcp.clickhouse.cloud:8443"
   },
   {
    "name": "Hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(ClickHouse_MemoryTracking{instance=\"$Instance\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Replicas Online",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(ClickHouse_MemoryTracking{instance=\"$Instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GOB Version",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "kube_pod_container_info{container=\"manager\", cluster=\"opstrace-prod\", namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ClickHouse Version", "type": "timeseries", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 } },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Total amount of memory (bytes) allocated by the server.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouse_MemoryTracking{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(ClickHouse_MemoryTracking{instance=\"$Instance\"})",
     "legendFormat": "Sum all hostnames"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Number of connections to TCP server (clients with native interface), also included server-server distributed query connections. \nNumber of connections to HTTP server",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouse_TCPConnection{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "tcp - {{hostname}}"
    },
    {
     "expr": "ClickHouse_HTTPConnection{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "http - {{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Usage (cores)",
   "type": "timeseries",
   "description": "CPU Usage (cores)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_OSCPUVirtualTimeMicroseconds{instance=\"$Instance\",hostname=~\"$Hostname\"}[1m]) / 1000000",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_OSCPUVirtualTimeMicroseconds{instance=\"$Instance\"}[1m]) / 1000000)",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "CPU Wait",
   "type": "timeseries",
   "description": "CPU Wait",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_OSCPUWaitMicroseconds{instance=\"$Instance\",hostname=~\"$Hostname\"}[1m]) / 1000000",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "OS CPU Usage (Userspace)",
   "type": "timeseries",
   "description": "OS CPU Usage (Userspace)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_OSUserTimeNormalized{instance=\"$Instance\",hostname=~\"$Hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "OS CPU Usage (Kernel)",
   "type": "timeseries",
   "description": "OS CPU Usage (Kernel)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_OSSystemTimeNormalized{instance=\"$Instance\",hostname=~\"$Hostname\"}[1m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "All Queries",
   "type": "timeseries",
   "description": "Number of queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_Query{instance=\"$Instance\",hostname=~\"$Hostname\", table=\"system.events\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_Query{instance=\"$Instance\",table=\"system.events\"}[10m]))",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "Query latencies (avg) across all queries",
   "type": "timeseries",
   "description": "Avg queries latencies",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(ClickHouse_QueryTimeMicroseconds{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval]) / 1000000",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "avg(rate(ClickHouse_QueryTimeMicroseconds{instance=\"$Instance\"}[10m]) / 1000000)",
     "legendFormat": "Avg all Hostnames"
    }
   ]
  },
  {
   "title": "Failed queries across all queries",
   "type": "timeseries",
   "description": "Number of failed queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_FailedQuery{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval]) / rate(ClickHouse_Query{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval]) * 100",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_FailedQuery{instance=\"$Instance\"}[$__rate_interval]) / rate(ClickHouse_Query{instance=\"$Instance\"}[$__rate_interval]) * 100)",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "INSERT queries",
   "type": "timeseries",
   "description": "Same as Queries, but only for INSERT queries.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_InsertQuery{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_InsertQuery{instance=\"$Instance\"}[10m]))",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "INSERT query latencies (avg)",
   "type": "timeseries",
   "description": "Avg INSERT queries latencies",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_InsertQueryTimeMicroseconds{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval]) / 1000000",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "avg(rate(ClickHouse_InsertQueryTimeMicroseconds{instance=\"$Instance\"}[10m]) / 1000000)",
     "legendFormat": "Avg all Hostnames"
    }
   ]
  },
  {
   "title": "Failed INSERT queries",
   "type": "timeseries",
   "description": "Same as Failed queries, but only for INSERT queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_FailedInsertQuery{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval]) / rate(ClickHouse_InsertQuery{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval]) * 100",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_FailedInsertQuery{instance=\"$Instance\"}[$__rate_interval]) / rate(ClickHouse_InsertQuery{instance=\"$Instance\"}[$__rate_interval]) * 100)",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "SELECT queries",
   "type": "timeseries",
   "description": "Same as Queries, but only for SELECT queries.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_SelectQuery{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_SelectQuery{instance=\"$Instance\"}[10m]))",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "SELECT query latencies (avg)",
   "type": "timeseries",
   "description": "Avg SELECT queries latencies",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_SelectQueryTimeMicroseconds{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "avg(rate(ClickHouse_SelectQueryTimeMicroseconds{instance=\"$Instance\"}[10m]))",
     "legendFormat": "Avg all Hostnames"
    }
   ]
  },
  {
   "title": "Failed SELECT queries",
   "type": "timeseries",
   "description": "Same as Failed queries, but only for SELECT queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_FailedSelectQuery{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval]) / rate(ClickHouse_SelectQuery{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval]) * 100",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_FailedSelectQuery{instance=\"$Instance\"}[5m]) / rate(ClickHouse_SelectQuery{instance=\"$Instance\",hostname=~\"$Hostname\"}[5m]) * 100)",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "Queries hitting memory limit",
   "type": "timeseries",
   "description": "Percentage of queries when memory limit exceeded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(ClickHouse_QueryMemoryLimitExceeded{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval]) / rate(ClickHouse_Query{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])) * 100",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum((rate(ClickHouse_QueryMemoryLimitExceeded{instance=\"$Instance\"}[$__rate_interval]) / rate(ClickHouse_Query{instance=\"$Instance\"}[$__rate_interval])) * 100)",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "Query preemted",
   "type": "timeseries",
   "description": "Number of queries that are stopped and waiting due to 'priority' setting.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_QueryPreempted{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Insert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Inserted rows",
   "type": "timeseries",
   "description": "Number of rows INSERTed to all tables.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_InsertedRows{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_InsertedRows{instance=\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "Inserted bytes",
   "type": "timeseries",
   "description": "Number of bytes (uncompressed; for columns as they stored in memory) INSERTed to all tables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_InsertedBytes{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_InsertedBytes{instance=\"$Instance\"}[$__rate_interval]))",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "Delayed inserts",
   "type": "timeseries",
   "description": "Number of times the INSERT of a block to a MergeTree table was throttled due to high number of active data parts for partition.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_DelayedInserts{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Select", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Parts",
   "type": "timeseries",
   "description": "Number of data parts selected to read from a MergeTree table.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_SelectedParts{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_SelectedParts{instance=\"$Instance\"}[10m]))",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "timeseries",
   "description": "Number of rows SELECTed from all tables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_SelectedRows{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_SelectedRows{instance=\"$Instance\"}[10m]))",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "Marks",
   "type": "timeseries",
   "description": "Number of marks (index granules) selected to read from a MergeTree table.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_SelectedMarks{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Ranges",
   "type": "timeseries",
   "description": "Number of (non-adjacent) ranges in all data parts selected to read from a MergeTree table.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_SelectedRanges{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "description": "Number of bytes (uncompressed; for columns as they stored in memory) SELECTed from all tables.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_SelectedBytes{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "collapsed": true,
   "panels": [
    {
     "title": "lseek",
     "type": "timeseries",
     "description": "Number of times the 'lseek' function was called.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_Seek{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "timeseries",
     "description": "Number of files opened",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_FileOpen{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Read from FD",
     "type": "timeseries",
     "description": "Number of reads (read/pread) from a file descriptor. Does not include sockets.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ReadBufferFromFileDescriptorRead{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Write to FD",
     "type": "timeseries",
     "description": "Number of writes (write/pwrite) to a file descriptor. Does not include sockets.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_WriteBufferFromFileDescriptorWrite{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Read from FD failed",
     "type": "timeseries",
     "description": "Number of times the read (read/pread) from a file descriptor have failed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ReadBufferFromFileDescriptorReadFailed{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Read from FD failed",
     "type": "timeseries",
     "description": "Number of times the read (read/pread) from a file descriptor have failed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ReadBufferFromFileDescriptorReadFailed{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Read bytes from FD",
     "type": "timeseries",
     "description": "Number of bytes read from file descriptors. If the file is compressed, this will show the compressed data size.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ReadBufferFromFileDescriptorReadBytes{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Write bytes to FD",
     "type": "timeseries",
     "description": "Number of bytes written to file descriptors. If the file is compressed, this will show compressed data size.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_WriteBufferFromFileDescriptorWriteBytes{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Read compressed bytes",
     "type": "timeseries",
     "description": "Number of bytes (the number of bytes before decompression) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ReadCompressedBytes{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Read uncompressed bytes",
     "type": "timeseries",
     "description": "Number of uncompressed bytes (the number of bytes after decompression) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_CompressedReadBufferBytes{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Compressed blocks",
     "type": "timeseries",
     "description": "Number of compressed blocks (the blocks of data that are compressed independent of each other) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_CompressedReadBufferBlocks{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  { "title": "Merge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "Merge",
   "type": "timeseries",
   "description": "Number of launched background merges.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_Merge{instance=\"$Instance\",hostname=~\"$Hostname\", table=\"system.events\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_Merge{instance=\"$Instance\",table=\"system.events\"}[10m]))",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "Merged rows",
   "type": "timeseries",
   "description": "Rows read for background merges. This is the number of rows before merge.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_MergedRows{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_MergedRows{instance=\"$Instance\"}[10m]))",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "Merge uncompressed bytes",
   "type": "timeseries",
   "description": "Uncompressed bytes (for columns as they stored in memory) that was read for background merges. This is the number before merge.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_MergedUncompressedBytes{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_MergedUncompressedBytes{instance=\"$Instance\"}[10m]))",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "MergeTree compressed bytes",
   "type": "timeseries",
   "description": "Bytes written to filesystem for data INSERTed to MergeTree tables.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_MergeTreeDataWriterCompressedBytes{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum(rate(ClickHouse_MergeTreeDataWriterCompressedBytes{instance=\"$Instance\"}[10m]))",
     "legendFormat": "Sum all Hostnames"
    }
   ]
  },
  {
   "title": "MergeTree rows",
   "type": "timeseries",
   "description": "Number of rows INSERTed to MergeTree tables.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_MergeTreeDataWriterRows{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Merge duration (avg)",
   "type": "timeseries",
   "description": "Avg merge duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_MergesTimeMilliseconds{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval]) / rate(ClickHouse_Merge{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])\n\n",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "avg(rate(ClickHouse_MergesTimeMilliseconds{instance=\"$Instance\"}[10m]) / rate(ClickHouse_Merge{instance=\"$Instance\"}[10m]))",
     "legendFormat": "Avg all Hostnames"
    }
   ]
  },
  {
   "title": "MergeTree uncompressed bytes",
   "type": "timeseries",
   "description": "Uncompressed bytes (for columns as they stored in memory) INSERTed to MergeTree tables.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_MergeTreeDataWriterUncompressedBytes{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "MergeTree blocks",
   "type": "timeseries",
   "description": "Number of blocks INSERTed to MergeTree tables. Each block forms a data part of level zero.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_MergeTreeDataWriterBlocks{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Reserved space",
   "type": "graph",
   "description": "Disk space reserved for currently running background merges. It is slightly more than the total size of currently merging parts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ClickHouse_DiskSpaceReservedForMerge{instance=\"$Instance\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "MergeTree compression ratio",
   "type": "timeseries",
   "description": "Average compression ratio for all MergeTree tables",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(ClickHouse_MergeTreeDataWriterUncompressedBytes{instance=\"$Instance\"}[12h])) / \nsum(rate(ClickHouse_MergeTreeDataWriterCompressedBytes{instance=\"$Instance\"}[12h]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 } },
  {
   "title": "Uncompressed Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_UncompressedCacheHits{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Uncompressed Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_UncompressedCacheMisses{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Mark Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_MarkCacheHits{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Mark Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ClickHouse_MarkCacheMisses{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Parts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 188 } },
  {
   "title": "Temporary",
   "type": "timeseries",
   "description": "The part is generating now, it is not in data_parts list.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouse_PartsTemporary{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Pre commited",
   "type": "timeseries",
   "description": "The part is in data_parts, but not used for SELECTs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouse_PartsPreCommitted{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Commited",
   "type": "timeseries",
   "description": "The part is in data_parts, but not used for SELECTs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouse_PartsCommitted{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Outdated",
   "type": "timeseries",
   "description": "Not active data part, but could be used by only current SELECTs, could be deleted after SELECTs finishes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouse_PartsOutdated{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Deleting",
   "type": "timeseries",
   "description": "Not active data part with identity refcounter, it is deleting right now by a cleaner.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 205 },
   "targets": [
    {
     "expr": "ClickHouse_PartsDeleting{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Delete on destroy",
   "type": "timeseries",
   "description": "Part was moved to another disk and should be deleted in own destructor.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouse_PartsDeleteOnDestroy{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Wide",
   "type": "timeseries",
   "description": "Wide parts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouse_PartsWide{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Compact",
   "type": "timeseries",
   "description": "Compact parts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouse_PartsCompact{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "In-memory",
   "type": "timeseries",
   "description": "In-memory parts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouse_PartsInMemory{instance=\"$Instance\",hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Distributed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 229 },
   "collapsed": true,
   "panels": [
    {
     "title": "Send",
     "type": "timeseries",
     "description": "Number of connections to remote servers sending data that was INSERTed into Distributed tables. Both synchronous and asynchronous mode.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_DistributedSend{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Files to insert",
     "type": "timeseries",
     "description": "Number of pending files to process for asynchronous insertion into Distributed tables. Number of files for every shard is summed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_DistributedFilesToInsert{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Distributed delayed inserts",
     "type": "timeseries",
     "description": "Number of times the INSERT of a block to a Distributed table was throttled due to high number of pending bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_DistributedDelayedInserts{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Distributed rejected inserts",
     "type": "timeseries",
     "description": "Number of times the INSERT of a block to a Distributed table was rejected with 'Too many bytes' exception due to high number of pending bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_DistributedRejectedInserts{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Distributed connection fail at all",
     "type": "timeseries",
     "description": "Total count when distributed connection fails after all retries finished",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_DistributedConnectionFailAtAll{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Distributed connection fail try",
     "type": "timeseries",
     "description": "Total count when distributed connection fails with retry",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_DistributedConnectionFailTry{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Distributed sync insertation timeout",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_DistributedSyncInsertionTimeoutExceeded{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 230 },
   "collapsed": true,
   "panels": [
    {
     "title": "BackgroundPool task",
     "type": "timeseries",
     "description": "Number of active tasks in BackgroundProcessingPool (merges, mutations, or replication queue bookkeeping)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_BackgroundPoolTask{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "BackgroundFetchesPool task",
     "type": "timeseries",
     "description": "Number of active tasks in BackgroundFetchesPool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_BackgroundFetchesPoolTask{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "BackgroundMovePool task",
     "type": "timeseries",
     "description": "Number of active tasks in BackgroundProcessingPool for moves",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_BackgroundMovePoolTask{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "BackgroundSchedulePool task",
     "type": "timeseries",
     "description": "Number of active tasks in BackgroundSchedulePool. This pool is used for periodic ReplicatedMergeTree tasks, like cleaning old data parts, altering data parts, replica re-initialization, etc.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_BackgroundSchedulePoolTask{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "BackgroundBufferFlushSchedulePool task",
     "type": "timeseries",
     "description": "Number of active tasks in BackgroundBufferFlushSchedulePool. This pool is used for periodic Buffer flushes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_BackgroundBufferFlushSchedulePoolTask{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "BackgroundDistributedSchedulePool task",
     "type": "timeseries",
     "description": "Number of active tasks in BackgroundDistributedSchedulePool. This pool is used for distributed sends that is done in background.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_BackgroundDistributedSchedulePoolTask{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "BackgroundMessageBrokerSchedulePool task",
     "type": "timeseries",
     "description": "Number of active tasks in BackgroundProcessingPool for message streaming",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_BackgroundMessageBrokerSchedulePoolTask{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 231 },
   "collapsed": true,
   "panels": [
    {
     "title": "Init",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperInit{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperTransactions{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "List",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperList{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Create",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperCreate{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Remove",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperRemove{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Exists",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 226 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperExists{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Get",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 234 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperGet{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Set",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 234 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperSet{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Multi",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperMulti{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Check",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperCheck{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Close",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 250 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperClose{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Watch response",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 250 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperWatchResponse{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "User Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 258 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperUserExceptions{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Hardware Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 258 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperHardwareExceptions{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Bytes received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 266 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperBytesReceived{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Bytes sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 266 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_ZooKeeperBytesSent{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "timeseries",
     "description": "Number of sessions (connections) to ZooKeeper. Should be no more than one, because using more than one connection to ZooKeeper may lead to bugs due to lack of linearizability (stale reads) that ZooKeeper consistency model allows.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 274 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_ZooKeeperSession{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Ephemeral Node",
     "type": "timeseries",
     "description": "Number of ephemeral nodes hold in ZooKeeper.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 274 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_EphemeralNode{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Watches",
     "type": "timeseries",
     "description": "Number of watches (event subscriptions) in ZooKeeper.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 282 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_ZooKeeperWatch{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "description": "Number of requests to ZooKeeper in fly.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 282 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouse_ZooKeeperRequest{instance=\"$Instance\",hostname=~\"$Hostname\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Remove ephemeral node failed",
     "type": "timeseries",
     "description": "Number of times an error happened while trying to remove ephemeral node. This is not an issue, because our implementation of ZooKeeper library guarantee that the session will expire and the node will be removed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(ClickHouse_CannotRemoveEphemeralNode{instance=\"$Instance\",hostname=~\"$Hostname\"}[$__rate_interval])",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  }
 ]
}