{
 "title": "Cloudflare traffic overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cloudflare_zone",
    "label": "Cloudflare Zone",
    "query": "label_values(cloudflare_zones_http_responses_total, zone)"
   },
   {
    "name": "gitlab_env",
    "label": "GitLab Environment",
    "query": "label_values(haproxy_frontend_http_responses_total, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cloudflare / HAProxy served responses",
   "type": "graph",
   "description": "Note: HAProxy traffic will in almost all cases be higher, as it also includes traffic from the internal load balancer, whereas Cloudflare does not.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zones_http_responses_total{env=\"gprd\", zone=~\"$cloudflare_zone\", edge_response_status=~\"2..\"}[5m])) by (zone)",
     "legendFormat": "Cloudflare {{zone}} 2xx"
    },
    {
     "expr": "sum(rate(cloudflare_zones_http_responses_total{env=\"gprd\", zone=~\"$cloudflare_zone\", edge_response_status=~\"5..\"}[5m])) by (zone)",
     "legendFormat": "Cloudflare {{zone}} 5xx"
    },
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{code=\"2xx\",env=~\"$gitlab_env\", frontend=\"https\"} [5m])) by (env)",
     "legendFormat": "HAProxy {{env}} 2xx"
    },
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{code=\"5xx\",env=~\"$gitlab_env\", frontend=\"https\"} [5m])) by (env)",
     "legendFormat": "HAProxy {{env}} 5xx"
    },
    {
     "expr": "sum(rate(cloudflare_zones_http_responses_total{env=\"gprd\", zone=~\"$cloudflare_zone\", edge_response_status=~\"4..\"}[5m])) by (zone)",
     "legendFormat": "Cloudflare {{zone}} 4xx"
    },
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{code=\"4xx\",env=~\"$gitlab_env\", frontend=\"https\"} [5m])) by (env)",
     "legendFormat": "HAProxy {{env}} 4xx"
    }
   ]
  },
  {
   "title": "Connections by HTTP Protocol version",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zones_http_protocol_requests_total{zone=~\"$cloudflare_zone\"}[5m])) by (client_http_protocol)",
     "legendFormat": "{{client_http_protocol}}"
    }
   ]
  },
  {
   "title": "Cloudflare WAF actions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zones_firewall_events_total{zone=~\"$cloudflare_zone\", env=\"gprd\"}[5m])) by (zone, action)",
     "legendFormat": "{{zone}} {{action}}"
    }
   ]
  }
 ]
}