{
 "title": "cloud-cost: OpenAI Cost Tracking",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6336349947 at Wed Mar  6 22:57:43 UTC 2024",
 "tags": [
  "managed",
  "cloud-cost"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Tokens Spent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Prompt Tokens Spent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=~\".*/prompt\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Completion Tokens Spent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=~\".*/completion\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Prompt Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=~\".*/prompt\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Completion Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=~\".*/completion\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Chat Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=~\"chat/.*\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Chat Prompt Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=\"chat/prompt\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Chat Completion Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=\"chat/completion\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Completions Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=~\"completions/.*\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Completions Prompt Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=\"completions/prompt\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Completions Completion Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=\"completions/completion\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Edits Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=~\"edits/.*\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Edits Prompt Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=\"edits/prompt\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Edits Completion Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=\"edits/completion\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Embeddings Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=~\"embeddings/.*\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Embeddings Prompt Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=\"embeddings/prompt\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Embeddings Completion Tokens Spent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"$environment\", vendor=\"open_ai\", unit=\"tokens\", item=\"embeddings/completion\"}[$__interval]))",
     "legendFormat": "Amount"
    }
   ]
  }
 ]
}