{
 "title": "code_suggestions: Triton",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4787303381 at Wed Aug  2 07:02:16 UTC 2023",
 "tags": [
  "managed",
  "code_suggestions",
  "type:code_suggestions",
  "detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Success / sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by(model, version) (\n  rate(nv_inference_request_success{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Batchsize ( #infer/ #exec)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Average Batch Size" }
   ],
   "targets": [
    {
     "expr": "sum by(model, version) (\n  rate(nv_inference_count{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n/\nsum by(model, version) (\n  rate(nv_inference_exec_count{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Input time / req",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "µs", "label": "Average Input Duration" }
   ],
   "targets": [
    {
     "expr": "sum by(model, version) (\n  rate(nv_inference_compute_input_duration_us{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n/\nsum by(model, version) (\n  rate(nv_inference_request_success{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Request fail / sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops", "label": "Failures per Second" }
   ],
   "targets": [
    {
     "expr": "sum by(model, version) (\n  rate(nv_inference_request_failure{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "DB ratio ( #request / #exec )",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Average Requests per Execution" }
   ],
   "targets": [
    {
     "expr": "sum by(model, version) (\n  rate(nv_inference_request_success{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n/\nsum by(model, version) (\n  rate(nv_inference_exec_count{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Queue time / req",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "µs", "label": "Average Queue Time per Request" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nv_inference_queue_duration_us{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval]))\n/\nsum(rate(nv_inference_request_success{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval]))\n",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    {
     "format": "µs",
     "label": "Average Request Time per Request"
    }
   ],
   "targets": [
    {
     "expr": "sum by(model, version) (\n  rate(nv_inference_request_duration_us{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n/\nsum by(model, version) (\n  rate(nv_inference_request_success{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Output time / req",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    {
     "format": "µs",
     "label": "Average Output Time per Request"
    }
   ],
   "targets": [
    {
     "expr": "sum by(model, version) (\n  rate(nv_inference_compute_output_duration_us{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n/\nsum by(model, version) (\n  rate(nv_inference_request_success{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Inference time / req",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    {
     "format": "µs",
     "label": "Average Inference Time per Request"
    }
   ],
   "targets": [
    {
     "expr": "sum by(model, version) (\n  rate(nv_inference_compute_infer_duration_us{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n/\nsum by(model, version) (\n  rate(nv_inference_request_success{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Average GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit", "label": "GPU Utilization %" }
   ],
   "targets": [
    {
     "expr": "avg(nv_gpu_utilization{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"})\n",
     "legendFormat": "GPU Utilization %"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "W", "label": "Watts" }
   ],
   "targets": [
    {
     "expr": "sum(nv_gpu_power_usage{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"})\n",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}