{
 "title": "Code Suggestions - Real-time Cost Estimation",
 "description": "This dashboard estimates the cost of Vertex AI and Anthropic API calls in real-time. The cost values found on this dashboard ONLY correspond to the usage of the AI models. It does not account for VMs, Storage, or networking. For more details about the exact costs, please visit: https://lookerstudio.google.com/reporting/1e23952a-a508-4bd1-81f5-589a77e8f818/page/p_0bewxyeocd",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dashboard Overview: Real-Time Cost Estimation for Vertex AI and Anthropic API Calls\n\nWelcome to the dashboard designed for monitoring the real-time cost estimates of Vertex AI and Anthropic API usage. Here's a quick guide to help you navigate and understand the displayed information:\n\n## Key Features:\n\n- **Real-Time Cost Estimation**: This dashboard provides up-to-date estimates of costs associated with the use of Vertex AI and Anthropic API services.\n- **AI Model Usage Focus**: Please note that the cost values displayed here are exclusive to the usage of AI models. This does not include expenses related to Virtual Machines (VMs), Storage, or Networking.\n\n## Detailed Cost Insights:\n\n- **Vertex AI Costs**: The cost information for Vertex AI is precise, as we accurately track the unit price per API request.\n- **Anthropic API Costs**: For Anthropic, the real-time metric available is the number of characters transmitted through the API. Since the unit price is based on the number of tokens, we calculate this by dividing the character count by a constant factor, currently set at 3.5 characters per token. This ratio can and will fluctuate over-time. This metric is +- 20% accurate until we refine that ratio.\n\n## Further Information:\n\nFor a more comprehensive breakdown of the exact costs and additional details, please visit our detailed report page: [Google Looker Studio Report](https://lookerstudio.google.com/reporting/1e23952a-a508-4bd1-81f5-589a77e8f818/page/p_0bewxyeocd).\n\n---"
   }
  },
  {
   "title": "Vertex AI - Codey - Cost",
   "type": "barchart",
   "description": "Cost of Codey Input usage on Vertex AI",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "    sum by (vendor, item, unit, feature_category) (\n        increase(gitlab_cloud_cost_spend_entry_total{env=\"gprd\", vendor=\"vertex-ai\", item=\"completions/completion/input\"}[1m])\n    ) * 0.00041/1000",
     "legendFormat": "{{item}}"
    },
    {
     "expr": "    sum by (vendor, item, unit, feature_category) (\n        increase(gitlab_cloud_cost_spend_entry_total{env=\"gprd\", vendor=\"vertex-ai\", item=\"completions/completion/output\"}[1m])\n    ) * 0.00041/1000",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Anthropic - Characters - Cost",
   "type": "barchart",
   "description": "Cost of Codey Input usage on Vertex AI",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "    sum by (vendor, item, unit, feature_category) (\n        increase(gitlab_cloud_cost_spend_entry_total{env=\"gprd\", vendor=\"anthropic\"}[1m])\n    ) / 3.5 * 8 /1000000",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Cost over selected period",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"gprd\", vendor=\"vertex-ai\", item=\"completions/completion/input\"}[$__range])) * 0.00041/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Cost over selected period",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_cloud_cost_spend_entry_total{env=\"gprd\", vendor=\"anthropic\", item=\"completions/completion/input\"}[$__range])) / 3.5 * 8 / 1000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}