{
 "title": "code_suggestions: language info",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Completions by Language",
   "type": "timeseries",
   "description": "Number of requested completions by language",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum by(lang, symbol) (rate(code_suggestions_prompt_language_total[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage by Language",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(100 * sum by(lang) (code_suggestions_prompt_language_total) / on() group_left() sum(code_suggestions_prompt_language_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completions by File Extension",
   "type": "timeseries",
   "description": "Number of requested completions by language",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(extension) (rate(code_suggestions_prompt_language_total[10m])) > 0.1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage by File Extension",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum (code_suggestions_prompt_language_total) by(extension))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Imports statements by Language",
   "type": "timeseries",
   "description": "Number of requested completions by language",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sort_desc(sum by(lang) (rate(code_suggestions_prompt_symbols_total{symbol=\"imports\"}[1h])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}