{
 "title": "code_suggestions: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5591760260 at Wed Nov 22 03:25:50 UTC 2023",
 "tags": [
  "managed",
  "code_suggestions",
  "gitlab",
  "type:code_suggestions",
  "code_suggestions",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "code_suggestions Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "code_suggestions apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "code_suggestions apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "code_suggestions Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "code_suggestions Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "code_suggestions error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "code_suggestions error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "code_suggestions Service | Errors"
    }
   ]
  },
  {
   "title": "code_suggestions Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "code_suggestions RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "ingress SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "ingress apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "ingress apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ingress SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "ingress SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ingress error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ingress error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"ingress\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ingress SLI | Errors"
    }
   ]
  },
  {
   "title": "ingress SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "ingress RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "content": "### Description\n\nIngress-NGINX Controller for Kubernetes to expose service to the internet. Fronted by Cloudflare WAF.\n\n\n\n### Observability Tools\n\n* [GKE Deployment: nginx-ingress-nginx-controller](https://console.cloud.google.com/kubernetes/deployment/us-central1-c/ai-assist/nginx/nginx-ingress-nginx-controller/overview?project=unreview-poc-390200e5)\n* [Stackdriver Logs: GKE Container Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Ecluster%5Fname%3D%22ai%2Dassist%22%0Aresource%2Elabels%2Econtainer%5Fname%3D%22controller%22%0Aresource%2Elabels%2Enamespace%5Fname%3D%22nginx%22%0Aresource%2Elabels%2Eproject%5Fid%3D%22unreview%2Dpoc%2D390200e5%22%0Aresource%2Etype%3D%22k8s%5Fcontainer%22;timeRange=PT30M?project=unreview-poc-390200e5)\n* [Cloudflare: codesuggestions.gitlab.com](https://dash.cloudflare.com/852e9d53d0f8adbd9205389356f2303d/gitlab.com/analytics/traffic?host=codesuggestions.gitlab.com&time-window=30)\n* [Grafana: WAF Overview](/d/waf-main/waf-overview?)\n\n"
  },
  {
   "title": "model_gateway SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "model_gateway apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "model_gateway apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "model_gateway SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "model_gateway SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "model_gateway error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "model_gateway error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"model_gateway\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "model_gateway SLI | Errors"
    }
   ]
  },
  {
   "title": "model_gateway SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "model_gateway RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"model_gateway\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "content": "### Observability Tools\n\n* [GKE Deployment: model-gateway](https://console.cloud.google.com/kubernetes/deployment/us-central1-c/ai-assist/fauxpilot/model-gateway/overview?project=unreview-poc-390200e5)\n* [Stackdriver Logs: GKE Container Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Ecluster%5Fname%3D%22ai%2Dassist%22%0Aresource%2Elabels%2Econtainer%5Fname%3D%22model%2Dgateway%22%0Aresource%2Elabels%2Enamespace%5Fname%3D%22fauxpilot%22%0Aresource%2Elabels%2Eproject%5Fid%3D%22unreview%2Dpoc%2D390200e5%22%0Aresource%2Etype%3D%22k8s%5Fcontainer%22;timeRange=PT30M?project=unreview-poc-390200e5)\n* [📖 Kibana: MLOps logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!(),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: MLOps failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!(),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!(),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!(),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!(),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: MLOps percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!(),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.jsonPayload.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "third_party_model_inference SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"third_party_model_inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "third_party_model_inference apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"third_party_model_inference\",monitor=\"global\",type=\"code_suggestions\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"third_party_model_inference\",monitor=\"global\",type=\"code_suggestions\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"third_party_model_inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "third_party_model_inference apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"third_party_model_inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"third_party_model_inference\",monitor=\"global\",type=\"code_suggestions\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"third_party_model_inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"third_party_model_inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"third_party_model_inference\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"third_party_model_inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"third_party_model_inference\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"third_party_model_inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"third_party_model_inference\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"third_party_model_inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"third_party_model_inference\",monitor=\"global\",type=\"code_suggestions\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "third_party_model_inference SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "third_party_model_inference SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"third_party_model_inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "third_party_model_inference RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"third_party_model_inference\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "content": "### Description\n\nInference requests performed by third party models.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Third Party Models logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.model_engine,params:'vertex-ai',type:phrase),query:(match:(json.jsonPayload.model_engine:(query:'vertex-ai',type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.type,params:code_suggestions,type:phrase),query:(match:(json.type:(query:code_suggestions,type:phrase))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Third Party Models failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.level,json.jsonPayload.method,json.jsonPayload.status_code,json.jsonPayload.path,json.jsonPayload.duration_s,json.jsonPayload.correlation_id),filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.model_engine,params:'vertex-ai',type:phrase),query:(match:(json.jsonPayload.model_engine:(query:'vertex-ai',type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.type,params:code_suggestions,type:phrase),query:(match:(json.type:(query:code_suggestions,type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Third Party Models requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.model_engine,params:'vertex-ai',type:phrase),query:(match:(json.jsonPayload.model_engine:(query:'vertex-ai',type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.type,params:code_suggestions,type:phrase),query:(match:(json.type:(query:code_suggestions,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Third Party Models failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.model_engine,params:'vertex-ai',type:phrase),query:(match:(json.jsonPayload.model_engine:(query:'vertex-ai',type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.type,params:code_suggestions,type:phrase),query:(match:(json.type:(query:code_suggestions,type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Third Party Models sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.model_engine,params:'vertex-ai',type:phrase),query:(match:(json.jsonPayload.model_engine:(query:'vertex-ai',type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.type,params:code_suggestions,type:phrase),query:(match:(json.type:(query:code_suggestions,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Third Party Models sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.model_engine,params:'vertex-ai',type:phrase),query:(match:(json.jsonPayload.model_engine:(query:'vertex-ai',type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.type,params:code_suggestions,type:phrase),query:(match:(json.type:(query:code_suggestions,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Third Party Models percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.model_engine,params:'vertex-ai',type:phrase),query:(match:(json.jsonPayload.model_engine:(query:'vertex-ai',type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.type,params:code_suggestions,type:phrase),query:(match:(json.type:(query:code_suggestions,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Third Party Models percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=8cd9c4c0-f0a7-11ed-a017-0d32180b1390&_a=(filters:!((meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.jsonPayload.model_engine,params:'vertex-ai',type:phrase),query:(match:(json.jsonPayload.model_engine:(query:'vertex-ai',type:phrase)))),(meta:(index:'8cd9c4c0-f0a7-11ed-a017-0d32180b1390',key:json.type,params:code_suggestions,type:phrase),query:(match:(json.type:(query:code_suggestions,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:'@timestamp',interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.url,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.jsonPayload.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "waf SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "waf error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"waf\",monitor=\"global\",type=\"code_suggestions\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"waf\",monitor=\"global\",type=\"code_suggestions\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "waf error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"waf\",monitor=\"global\",type=\"code_suggestions\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"waf\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"waf\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"waf\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"waf\",monitor=\"global\",type=\"code_suggestions\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "waf SLI | Errors"
    }
   ]
  },
  {
   "title": "waf SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"}[$__interval])\n",
     "legendFormat": "waf RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"waf\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"code_suggestions\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "content": "### Description\n\nCloudflare WAF and rate limit rules for codesuggestions.gitlab.com host.\n\n\n\n### Observability Tools\n\n* [Cloudflare: codesuggestions.gitlab.com](https://dash.cloudflare.com/852e9d53d0f8adbd9205389356f2303d/gitlab.com/analytics/traffic?host=codesuggestions.gitlab.com&time-window=30)\n* [Grafana: WAF Overview](/d/waf-main/waf-overview?)\n\n"
  },
  {
   "title": "🔬 SLI Detail: ingress",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 ingress Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",path!=\"/\",status!~\"4.*|5.*\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "ingress Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(nginx_ingress_controller_requests{container=\"controller\",env=\"$environment\",environment=\"$environment\",path!=\"/\",status=~\"^5.*\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "ingress RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(nginx_ingress_controller_requests{container=\"controller\",env=\"$environment\",environment=\"$environment\",path!=\"/\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 ingress Latency - per path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,path) (\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",path!=\"\",status!~\"4.*|5.*\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{path}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for ingress Latency - per path",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (path) (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",path!=\"\",status!~\"4.*|5.*\",type=\"code_suggestions\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (path) (\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"2.5\",path!=\"\",status!~\"4.*|5.*\",type=\"code_suggestions\"}[$__interval])\n  )\n  +\n  sum by (path) (\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"10\",path!=\"\",status!~\"4.*|5.*\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(path) group_left()\n  (\n    sum by () (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",path!=\"\",status!~\"4.*|5.*\",type=\"code_suggestions\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "ingress Errors - per path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (path) (\n  rate(nginx_ingress_controller_requests{container=\"controller\",env=\"$environment\",environment=\"$environment\",path!=\"/\",status=~\"^5.*\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "ingress RPS - per path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (path) (\n  rate(nginx_ingress_controller_requests{container=\"controller\",env=\"$environment\",environment=\"$environment\",path!=\"/\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Estimated p95 ingress Latency - per status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,status) (\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",path!=\"/\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{status}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for ingress Latency - per status",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (status) (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",path!=\"/\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (status) (\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"2.5\",path!=\"/\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n  +\n  sum by (status) (\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"10\",path!=\"/\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(status) group_left()\n  (\n    sum by () (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",path!=\"/\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "ingress Errors - per status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (\n  rate(nginx_ingress_controller_requests{container=\"controller\",env=\"$environment\",environment=\"$environment\",path!=\"/\",status=~\"^5.*\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "ingress RPS - per status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (\n  rate(nginx_ingress_controller_requests{container=\"controller\",env=\"$environment\",environment=\"$environment\",path!=\"/\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Estimated p95 ingress Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",method!=\"\",path!=\"/\",status!~\"4.*|5.*\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for ingress Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method!=\"\",path!=\"/\",status!~\"4.*|5.*\",type=\"code_suggestions\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"2.5\",method!=\"\",path!=\"/\",status!~\"4.*|5.*\",type=\"code_suggestions\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"10\",method!=\"\",path!=\"/\",status!~\"4.*|5.*\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method!=\"\",path!=\"/\",status!~\"4.*|5.*\",type=\"code_suggestions\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "ingress Errors - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(nginx_ingress_controller_requests{container=\"controller\",env=\"$environment\",environment=\"$environment\",method!=\"\",path!=\"/\",status=~\"^5.*\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "ingress RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(nginx_ingress_controller_requests{container=\"controller\",env=\"$environment\",environment=\"$environment\",method!=\"\",path!=\"/\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: model_gateway",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 model_gateway Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",status!~\"4xx|5xx\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "model_gateway Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(http_request_duration_seconds_count{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",status=\"5xx\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "model_gateway RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(http_request_duration_seconds_count{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 model_gateway Latency - per status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,status) (\n    rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{status}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for model_gateway Latency - per status",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (status) (\n  rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (status) (\n    rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"2.5\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n  +\n  sum by (status) (\n    rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"10.0\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(status) group_left()\n  (\n    sum by () (\n  rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "model_gateway Errors - per status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (\n  rate(http_request_duration_seconds_count{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",status=\"5xx\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "model_gateway RPS - per status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (\n  rate(http_request_duration_seconds_count{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",status!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Estimated p95 model_gateway Latency - per handler",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (handler,le) (\n    rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",handler!=\"\",status!~\"4xx|5xx\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{handler}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for model_gateway Latency - per handler",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (handler) (\n  rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",handler!=\"\",le=\"+Inf\",status!~\"4xx|5xx\",type=\"code_suggestions\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (handler) (\n    rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",handler!=\"\",le=\"2.5\",status!~\"4xx|5xx\",type=\"code_suggestions\"}[$__interval])\n  )\n  +\n  sum by (handler) (\n    rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",handler!=\"\",le=\"10.0\",status!~\"4xx|5xx\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(handler) group_left()\n  (\n    sum by () (\n  rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",handler!=\"\",le=\"+Inf\",status!~\"4xx|5xx\",type=\"code_suggestions\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "model_gateway Errors - per handler",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (handler) (\n  rate(http_request_duration_seconds_count{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",handler!=\"\",status=\"5xx\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "model_gateway RPS - per handler",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (handler) (\n  rate(http_request_duration_seconds_count{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",handler!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Estimated p95 model_gateway Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",method!=\"\",status!~\"4xx|5xx\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for model_gateway Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method!=\"\",status!~\"4xx|5xx\",type=\"code_suggestions\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"2.5\",method!=\"\",status!~\"4xx|5xx\",type=\"code_suggestions\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"10.0\",method!=\"\",status!~\"4xx|5xx\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(http_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method!=\"\",status!~\"4xx|5xx\",type=\"code_suggestions\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "model_gateway Errors - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(http_request_duration_seconds_count{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",method!=\"\",status=\"5xx\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "model_gateway RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(http_request_duration_seconds_count{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",method!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: third_party_model_inference",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 third_party_model_inference Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(code_suggestions_inference_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",model_engine!=\"codegen\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "third_party_model_inference RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(code_suggestions_inference_requests_total{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",model_engine!=\"codegen\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 third_party_model_inference Latency - per model_engine",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,model_engine) (\n    rate(code_suggestions_inference_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",model_engine!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{model_engine}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for third_party_model_inference Latency - per model_engine",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (model_engine) (\n  rate(code_suggestions_inference_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",model_engine!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (model_engine) (\n    rate(code_suggestions_inference_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"5.0\",model_engine!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n  +\n  sum by (model_engine) (\n    rate(code_suggestions_inference_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"10.0\",model_engine!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(model_engine) group_left()\n  (\n    sum by () (\n  rate(code_suggestions_inference_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",model_engine!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{model_engine}}"
      }
     ]
    },
    {
     "title": "third_party_model_inference RPS - per model_engine",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (model_engine) (\n  rate(code_suggestions_inference_requests_total{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",model_engine!=\"codegen\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{model_engine}}"
      }
     ]
    },
    {
     "title": "Estimated p95 third_party_model_inference Latency - per model_name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,model_name) (\n    rate(code_suggestions_inference_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",model_engine!=\"codegen\",model_name!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{model_name}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for third_party_model_inference Latency - per model_name",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (model_name) (\n  rate(code_suggestions_inference_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",model_engine!=\"codegen\",model_name!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (model_name) (\n    rate(code_suggestions_inference_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"5.0\",model_engine!=\"codegen\",model_name!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n  +\n  sum by (model_name) (\n    rate(code_suggestions_inference_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"10.0\",model_engine!=\"codegen\",model_name!=\"\",type=\"code_suggestions\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(model_name) group_left()\n  (\n    sum by () (\n  rate(code_suggestions_inference_request_duration_seconds_bucket{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",model_engine!=\"codegen\",model_name!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{model_name}}"
      }
     ]
    },
    {
     "title": "third_party_model_inference RPS - per model_name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (model_name) (\n  rate(code_suggestions_inference_requests_total{container=\"model-gateway\",env=\"$environment\",environment=\"$environment\",model_engine!=\"codegen\",model_name!=\"\",type=\"code_suggestions\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{model_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: waf",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 230 },
   "collapsed": true,
   "panels": [
    {
     "title": "waf Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(cloudflare_zone_requests_status_country_host{env=\"$environment\",environment=\"$environment\",host=~\"codesuggestions.gitlab.com.*\",status=~\"^5.*\",zone=\"gitlab.com\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "waf RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(cloudflare_zone_requests_status_country_host{env=\"$environment\",environment=\"$environment\",host=~\"codesuggestions.gitlab.com.*\",zone=\"gitlab.com\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "waf Errors - per status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (\n  rate(cloudflare_zone_requests_status_country_host{env=\"$environment\",environment=\"$environment\",host=~\"codesuggestions.gitlab.com.*\",status=~\"^5.*\",zone=\"gitlab.com\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "waf RPS - per status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (\n  rate(cloudflare_zone_requests_status_country_host{env=\"$environment\",environment=\"$environment\",host=~\"codesuggestions.gitlab.com.*\",status!=\"\",zone=\"gitlab.com\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "filestore_disk_read_iops_saturation component saturation: Filestore Disk Read IOPS Saturation",
     "type": "graph",
     "description": "Filestore Disk Read IOPS Saturation.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-file for\nmore details\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, instance_name) (\n  clamp_min(\n    clamp_max(\n      (stackdriver_filestore_instance_file_googleapis_com_nfs_server_read_ops_count{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"} / 60)\n      /\n      600\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ instance_name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_read_iops_saturation\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_read_iops_saturation\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_read_iops_saturation\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"filestore_disk_read_iops_saturation\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"filestore_disk_read_iops_saturation\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "filestore_disk_read_throughput_saturation component saturation: Filestore Disk Read Throughput Saturation",
     "type": "graph",
     "description": "Filestore Disk Read Throughput Saturation.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-file for\nmore details\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, instance_name) (\n  clamp_min(\n    clamp_max(\n      (stackdriver_filestore_instance_file_googleapis_com_nfs_server_read_bytes_count{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"} / 60)\n      /\n      100000000\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ instance_name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_read_throughput_saturation\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_read_throughput_saturation\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_read_throughput_saturation\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"filestore_disk_read_throughput_saturation\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"filestore_disk_read_throughput_saturation\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "filestore_disk_utilization component saturation: Filestore Disk Utilization",
     "type": "graph",
     "description": "Filestore Disk utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-file for\nmore details\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, instance_name) (\n  clamp_min(\n    clamp_max(\n      avg_over_time(stackdriver_filestore_instance_file_googleapis_com_nfs_server_used_bytes_percent{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[5m]) / 100\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ instance_name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_utilization\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_utilization\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_utilization\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"filestore_disk_utilization\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"filestore_disk_utilization\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "filestore_disk_write_iops_saturation component saturation: Filestore Disk Write IOPS Saturation",
     "type": "graph",
     "description": "Filestore Disk Write IOPS Saturation.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-file for\nmore details\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, instance_name) (\n  clamp_min(\n    clamp_max(\n      (stackdriver_filestore_instance_file_googleapis_com_nfs_server_write_ops_count{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"} / 60)\n      /\n      1000\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ instance_name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_write_iops_saturation\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_write_iops_saturation\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_write_iops_saturation\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"filestore_disk_write_iops_saturation\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"filestore_disk_write_iops_saturation\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "filestore_disk_write_throughput_saturation component saturation: Filestore Disk Write Throughput Saturation",
     "type": "graph",
     "description": "Filestore Disk Write Throughput Saturation.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-file for\nmore details\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, instance_name) (\n  clamp_min(\n    clamp_max(\n      (stackdriver_filestore_instance_file_googleapis_com_nfs_server_write_bytes_count{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"} / 60)\n      /\n      100000000\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ instance_name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_write_throughput_saturation\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_write_throughput_saturation\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"filestore_disk_write_throughput_saturation\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"filestore_disk_write_throughput_saturation\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"filestore_disk_write_throughput_saturation\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "gcp_quota_limit_s4 component saturation: GCP Quota utilization per environment",
     "type": "graph",
     "description": "GCP Quota utilization / limit ratio\n\nSaturation on a quota may cause problems with creating infrastructure resources on GCP.\n\nTo fix, we can request a quota increase for the specific resource to the GCP support team.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, project, metric, quotaregion) (\n  clamp_min(\n    clamp_max(\n      (\n        gcp_quota_usage{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}\n      /\n        gcp_quota_limit{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}\n      ) > 0\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ project }} {{ metric }} {{ quotaregion }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"gcp_quota_limit_s4\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"gcp_quota_limit_s4\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"gcp_quota_limit_s4\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"gcp_quota_limit_s4\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"gcp_quota_limit_s4\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "gcp_quota_limit_vertex_ai component saturation: GCP Quota utilization per environment",
     "type": "graph",
     "description": "GCP Quota utilization / limit ratio\n\nSaturation on a quota may cause problems with creating infrastructure resources on GCP.\n\nTo fix, we can request a quota increase for the specific resource to the GCP support team.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, base_model) (\n  clamp_min(\n    clamp_max(\n      (\n        sum without (method) (stackdriver_aiplatform_googleapis_com_location_aiplatform_googleapis_com_quota_online_prediction_requests_per_base_model_usage{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"})\n      /\n        stackdriver_aiplatform_googleapis_com_location_aiplatform_googleapis_com_quota_online_prediction_requests_per_base_model_limit{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}\n      ) > 0\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ base_model }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"gcp_quota_limit_vertex_ai\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"gcp_quota_limit_vertex_ai\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"gcp_quota_limit_vertex_ai\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"gcp_quota_limit_vertex_ai\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"gcp_quota_limit_vertex_ai\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. Configured using resource requests.\nWhen this is exhausted, the container may be thottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, pod, container) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[1h])\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        kube_pod_container_resource_requests:labeled{container!=\"\", container!=\"POD\", resource=\"cpu\", env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu_limit component saturation: Kube Container CPU over-utilization",
     "type": "graph",
     "description": "Kubernetes containers can have a limit configured on how much CPU they can consume in\na burst. If we are at this limit, exceeding the allocated requested resources, we\nshould consider revisting the container's HPA configuration\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_container_cpu_limit\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_container_cpu_limit\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_memory component saturation: Kube Container Memory Utilization",
     "type": "graph",
     "description": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      container_memory_working_set_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_container_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_horizontalpodautoscaler_desired_replicas component saturation: Horizontal Pod Autoscaler Desired Replicas",
     "type": "graph",
     "description": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, horizontalpodautoscaler, shard) (\n  clamp_min(\n    clamp_max(\n      kube_horizontalpodautoscaler_status_desired_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects|urgent-other\", namespace!~\"pubsubbeat\"}\n      /\n      kube_horizontalpodautoscaler_spec_max_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects|urgent-other\", namespace!~\"pubsubbeat\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ horizontalpodautoscaler }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"code_suggestions\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-queues-meta\n  redis-cluster-ratelimiting\n  redis-cluster-shared-state\n  redis-pubsub\n  redis-repository-cache\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  search\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\n  praefect\nend\n\nsubgraph sv\n  api\n  code_suggestions\n  consul\n  kas\n  pvs\nend\n\n\n  api --> consul\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> praefect\napi --> pvs\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-queues-meta\napi --> redis-cluster-ratelimiting\napi --> redis-cluster-shared-state\napi --> redis-pubsub\napi --> redis-repository-cache\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\ncode_suggestions --> api\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> praefect\nkas --> redis\npgbouncer --> patroni\npraefect --> cloud-sql\npraefect --> gitaly\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-queues-meta\n  redis-cluster-ratelimiting\n  redis-cluster-shared-state\n  redis-pubsub\n  redis-repository-cache\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  search\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\n  praefect\nend\n\nsubgraph sv\n  api\n  code_suggestions\n  consul\n  kas\n  pvs\nend\n\n\n  api --> consul\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> praefect\napi --> pvs\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-queues-meta\napi --> redis-cluster-ratelimiting\napi --> redis-cluster-shared-state\napi --> redis-pubsub\napi --> redis-repository-cache\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\ncode_suggestions --> api\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> praefect\nkas --> redis\npgbouncer --> patroni\npraefect --> cloud-sql\npraefect --> gitaly\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql[\"cloud-sql (Level 1)\"]\n  patroni[\"patroni (Level 2)\"]\n  pgbouncer[\"pgbouncer (Level 1)\"]\n  redis-cluster-cache[\"redis-cluster-cache (Level 2)\"]\n  redis-cluster-chat-cache[\"redis-cluster-chat-cache (Level 2)\"]\n  redis-cluster-feature-flag[\"redis-cluster-feature-flag (Level 2)\"]\n  redis-cluster-queues-meta[\"redis-cluster-queues-meta (Level 2)\"]\n  redis-cluster-ratelimiting[\"redis-cluster-ratelimiting (Level 2)\"]\n  redis-cluster-shared-state[\"redis-cluster-shared-state (Level 2)\"]\n  redis-pubsub[\"redis-pubsub (Level 2)\"]\n  redis-repository-cache[\"redis-repository-cache (Level 2)\"]\n  redis-sessions[\"redis-sessions (Level 3)\"]\n  redis-sidekiq[\"redis-sidekiq (Level 3)\"]\n  redis-tracechunks[\"redis-tracechunks (Level 3)\"]\n  redis[\"redis (Level 3)\"]\nend\n\nsubgraph inf\n  search[\"search (Level 1)\"]\nend\n\nsubgraph stor\n  gitaly[\"gitaly (Level 3)\"]\n  google-cloud-storage[\"google-cloud-storage (Level 2)\"]\n  praefect[\"praefect (Level 2)\"]\nend\n\nsubgraph sv\n  api[\"api (Level 2)\"]\n  code_suggestions[\"code_suggestions (Level 2)\"]\n  consul[\"consul (Level 1)\"]\n  kas[\"kas (Level 3)\"]\n  pvs[\"pvs (Level 3)\"]\nend\n\n\n  api[\"api (Level 2)\"] --> consul\napi[\"api (Level 2)\"] --> gitaly\napi[\"api (Level 2)\"] --> google-cloud-storage\napi[\"api (Level 2)\"] --> kas\napi[\"api (Level 2)\"] --> patroni\napi[\"api (Level 2)\"] --> pgbouncer\napi[\"api (Level 2)\"] --> praefect\napi[\"api (Level 2)\"] --> pvs\napi[\"api (Level 2)\"] --> redis\napi[\"api (Level 2)\"] --> redis-cluster-cache\napi[\"api (Level 2)\"] --> redis-cluster-chat-cache\napi[\"api (Level 2)\"] --> redis-cluster-feature-flag\napi[\"api (Level 2)\"] --> redis-cluster-queues-meta\napi[\"api (Level 2)\"] --> redis-cluster-ratelimiting\napi[\"api (Level 2)\"] --> redis-cluster-shared-state\napi[\"api (Level 2)\"] --> redis-pubsub\napi[\"api (Level 2)\"] --> redis-repository-cache\napi[\"api (Level 2)\"] --> redis-sessions\napi[\"api (Level 2)\"] --> redis-sidekiq\napi[\"api (Level 2)\"] --> redis-tracechunks\napi[\"api (Level 2)\"] --> search\ncode_suggestions[\"code_suggestions (Level 2)\"] --> api\ngitaly[\"gitaly (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> api\nkas[\"kas (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> kas\nkas[\"kas (Level 3)\"] --> praefect\nkas[\"kas (Level 3)\"] --> redis\npgbouncer[\"pgbouncer (Level 1)\"] --> patroni\npraefect[\"praefect (Level 2)\"] --> cloud-sql\npraefect[\"praefect (Level 2)\"] --> gitaly\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}