{
 "title": "Consul",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "pg_service_nodes",
    "query": "label_values(consul_health_service_status{check=\"service:postgresql\",environment=\"$environment\",service_id=\"postgresql\",service_name=\"postgresql\"}, node)"
   },
   {
    "name": "pg_node_status",
    "query": "label_values(consul_health_service_status{check=\"service:postgresql\",environment=\"$environment\",service_id=\"postgresql\",service_name=\"postgresql\"}, status)"
   },
   {
    "name": "consul_server",
    "query": "label_values(consul_raft_leader, fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$pg_node_status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
     "repeat": "pg_node_status",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consul_health_service_status{check=\"service:postgresql\",environment=\"$environment\",tier=\"inf\", fqdn=\"$consul_server\", status=\"$pg_node_status\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "$pg_node_status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consul_health_service_status{check=\"service:postgresql\",environment=\"$environment\",tier=\"inf\", fqdn=\"$consul_server\", status=\"$pg_node_status\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "$pg_node_status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consul_health_service_status{check=\"service:postgresql\",environment=\"$environment\",tier=\"inf\", fqdn=\"$consul_server\", status=\"$pg_node_status\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "$pg_node_status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consul_health_service_status{check=\"service:postgresql\",environment=\"$environment\",tier=\"inf\", fqdn=\"$consul_server\", status=\"$pg_node_status\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "status critical",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consul_health_node_status{check=\"serfHealth\",environment=\"$environment\",status=\"critical\"} == 1",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  { "title": "Node Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Passing",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"serfHealth\",environment=\"$environment\",status=\"passing\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warning",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"serfHealth\",environment=\"$environment\",status=\"warning\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Critical",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"serfHealth\",environment=\"$environment\",status=\"critical\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(consul_health_node_status{check=\"serfHealth\",environment=\"$environment\",status=\"maintenance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}