{
 "title": "Container Registry - Blob download metrics",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Blob download size (p90)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.9,\n    sum by (le) (\n    rate(registry_storage_blob_download_bytes_bucket{environment=\"gprd\"}[$__interval])\n    )\n)"
    }
   ]
  },
  {
   "title": "Blob download size (p95)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum by (le) (\n    rate(registry_storage_blob_download_bytes_bucket{environment=\"gprd\"}[$__interval])\n    )\n)"
    }
   ]
  },
  {
   "title": "Blob download size (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum by (le) (\n    rate(registry_storage_blob_download_bytes_bucket{environment=\"gprd\"}[$__interval])\n    )\n)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (le) (registry_storage_blob_download_bytes_bucket{env=\"gprd\"})",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}