{
 "title": "container_registry: Application Info",
 "tags": [
  "managed",
  "container_registry",
  "container registry",
  "docker",
  "registry"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Stackdriver Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log messages with severity ERROR",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"ERROR\", cluster_name=\"$cluster\", namespace_id=\"$namespace\"}) / 60",
     "legendFormat": "ERROR msgs per second"
    }
   ]
  },
  {
   "title": "Log messages with severity INFO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"INFO\", cluster_name=\"$cluster\", namespace_id=\"$namespace\"}) / 60",
     "legendFormat": "INFO msgs per second"
    }
   ]
  },
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Registry Process CPU Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\".*registry.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\".*registry.*\", cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\".*registry.*\", cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_http_requests_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (handler, code)",
     "legendFormat": "{{ handler }}: {{ code }}"
    }
   ]
  },
  {
   "title": "In-Flight HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_http_in_flight_requests{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (handler, code)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Registry Action Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(registry_storage_action_seconds_sum{job=~\".*registry.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval])) by (action)",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Cache Requests Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2011 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_storage_cache_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (type)"
    }
   ]
  },
  {
   "title": "Cache Hit %",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2021 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{cluster=\"$cluster\", environment=\"$environment\", namespace=\"$namespace\",exported_type=\"Hit\"}[$__interval])) / sum(rate(registry_storage_cache_total{environment=\"$environment\",exported_type=\"Request\"}[$__interval]))"
    }
   ]
  },
  { "title": "Handler Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "manifest",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3001 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"manifest\",cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "blob_upload_chunk",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3001 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob_upload_chunk\", cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "blob",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3001 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob\",cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "base",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3011 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"base\",cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "tags",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3011 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"tags\", cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "blob_upload",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3011 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{handler=\"blob_upload\", cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  }
 ]
}