{
 "title": "Create::Editor User Timing",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "sitespeed_io" },
   { "name": "device", "query": "$base.*" },
   { "name": "domain", "query": "$base.$device.pageSummary.*" },
   {
    "name": "browser",
    "query": "$base.$device.pageSummary.$domain.$page.*"
   },
   { "name": "connectivity", "query": "cable" },
   {
    "name": "function",
    "query": "min, mean,median,p90,max,stddev"
   },
   {
    "name": "page",
    "query": "$base.$device.pageSummary.$domain.*"
   },
   {
    "name": "metrics",
    "query": "$base.$device.pageSummary.$domain.$page.$browser.$connectivity.browsertime.statistics.timings.userTimings.measures.*"
   }
  ]
 },
 "panels": [
  { "title": "User Timing measures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$metrics",
   "type": "graph",
   "description": "Duration of a measurement",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "repeat": "metrics",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$device.pageSummary.$domain.$page.$browser.$connectivity.browsertime.statistics.timings.userTimings.measures.$metrics.$function, 12)"
    }
   ]
  },
  {
   "title": "$metrics",
   "type": "graph",
   "description": "Duration of a measurement",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$device.pageSummary.$domain.$page.$browser.$connectivity.browsertime.statistics.timings.userTimings.measures.$metrics.$function, 12)"
    }
   ]
  },
  {
   "title": "Performance marks",
   "type": "graph",
   "description": "Performance-related marks",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "sortBy(aliasByNode($base.$device.pageSummary.$domain.$page.$browser.$connectivity.browsertime.statistics.timings.userTimings.marks.*.$function, 12), 'stddev')"
    }
   ]
  },
  { "title": "Web Vitals (core metrics)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Largest Contentful Paint (LCP)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias($base.$device.pageSummary.$domain.$page.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 'Largest Contentful Paint')"
    }
   ]
  },
  {
   "title": "Cumulative Shift (CLS)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias($base.$device.pageSummary.$domain.$page.$browser.$connectivity.browsertime.statistics.pageinfo.layoutShift.p90, 'Layout Shift')"
    }
   ]
  },
  {
   "title": "First Input Delay (FID)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias($base.$device.pageSummary.$domain.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.maxPotentialFid.$function, 'First Input Delay')"
    }
   ]
  }
 ]
}