{
 "title": "Daily Overview",
 "tags": [
  "controller",
  "influxdb"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "process_type", "label": "Process Type", "query": "rails,sidekiq,grape" },
   {
    "name": "action",
    "label": "Action",
    "query": "SHOW TAG VALUES FROM gitlab.downsampled.[[process_type]]_transaction_counts_per_action WITH KEY = \"action\""
   },
   { "name": "database", "label": "Database", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "About", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "# About\n\nThe data on this page is calculated every 12 hours and covers the 12 hours leading up to that point."
  },
  { "title": "General Timings", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Transaction Timings per Action",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "transactions",
     "query": "SELECT \"action\", \"count\" AS \"Amount\", \"duration_mean\" AS \"Mean\", \"duration_95th\" AS \"95th Percentile\", \"duration_99th\" AS \"99th Percentile\" FROM downsampled.\"[[process_type]]_transaction_timings_per_action_per_day\" WHERE $timeFilter AND \"action\" =~ /[[action]]/ ORDER BY time DESC",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "method" ], "type": "field" }
      ],
      [
       { "params": [ "path" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Timings",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Timings per Action",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "transactions",
       "query": "SELECT \"action\", \"count\" as \"Amount\", (sql_duration_99th / duration_99th) * 100.0 AS \"Percentage of Request Time\", \"sql_duration_mean\" AS \"Mean\", \"sql_duration_95th\" AS \"95th Percentile\", \"sql_duration_99th\" AS \"99th Percentile\" FROM downsampled.\"[[process_type]]_transaction_timings_per_action_per_day\" WHERE $timeFilter AND action =~ /[[action]]/ ORDER BY time DESC",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" }
        ],
        [
         { "params": [ "method" ], "type": "field" }
        ],
        [
         { "params": [ "path" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Frequently Running Slow Queries",
     "type": "table",
     "description": "SQL queries of actions that were requested 500 or more times, and with a 99th percentile of >= 200 ms",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "transactions",
       "query": "SELECT \"action\", \"count\" as \"Amount\", (sql_duration_99th / duration_99th) * 100.0 AS \"Percentage of Request Time\", \"sql_duration_mean\" AS \"Mean\", \"sql_duration_95th\" AS \"95th Percentile\", \"sql_duration_99th\" AS \"99th Percentile\" FROM downsampled.\"[[process_type]]_transaction_timings_per_action_per_day\" WHERE $timeFilter AND action =~ /[[action]]/ AND \"count\" >= 500 AND sql_duration_99th > 200 AND action !~ /RequestForgery|RootController/ ORDER BY time DESC",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" }
        ],
        [
         { "params": [ "method" ], "type": "field" }
        ],
        [
         { "params": [ "path" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Git Timings",
   "type": "row",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git Real Timings per Action",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "transactions",
       "query": "SELECT \"action\", \"count\" as \"Amount\", \"duration_mean\" AS \"Mean\", \"duration_95th\" AS \"95th Percentile\", \"duration_99th\" AS \"99th Percentile\" FROM downsampled.\"[[process_type]]_git_timings_per_action_per_day\" WHERE $timeFilter AND action =~ /[[action]]/ ORDER BY time DESC",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" }
        ],
        [
         { "params": [ "method" ], "type": "field" }
        ],
        [
         { "params": [ "path" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Timings",
   "type": "row",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Timings per Action",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "transactions",
       "query": "SELECT \"action\", \"count\" as \"Amount\", \"cache_duration_mean\" AS \"Mean\", \"cache_duration_95th\" AS \"95th Percentile\", \"cache_duration_99th\" AS \"99th Percentile\" FROM downsampled.\"[[process_type]]_transaction_timings_per_action_per_day\" WHERE $timeFilter AND action =~ /[[action]]/ ORDER BY time DESC",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" }
        ],
        [
         { "params": [ "method" ], "type": "field" }
        ],
        [
         { "params": [ "path" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "View Timings",
   "type": "row",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "View Timings per Action",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "transactions",
       "query": "SELECT \"action\" AS \"Action\", \"view\" as \"View\", \"duration_mean\" AS \"Mean\", \"duration_95th\" AS \"95th Percentile\", \"duration_99th\" AS \"99th Percentile\" FROM downsampled.\"[[process_type]]_view_timings_per_action_and_view_per_day\" WHERE $timeFilter AND action =~ /[[action]]/ ORDER BY time DESC",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" }
        ],
        [
         { "params": [ "method" ], "type": "field" }
        ],
        [
         { "params": [ "path" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}