{
 "title": "Dash",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg" }
  ]
 },
 "panels": [
  { "title": "General overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Git Storage Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  node_filesystem_size_bytes{environment=\"$environment\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\"}\n    -\n  node_filesystem_avail_bytes{environment=\"$environment\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\"}\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(node_filesystem_size_bytes{environment=\"$environment\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HAProxy Frontend Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(frontend_code:haproxy_frontend_http_responses_total:irate1m{env=\"$environment\",monitor=\"default\"}[$__interval])) by (frontend)",
     "legendFormat": "Frontend {{ frontend  }}"
    }
   ]
  },
  {
   "title": "Kernel version distribution",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(label_replace(node_uname_info{environment=~\"$environment\"}, \"kernel\", \"$1\", \"release\", \"([0-9]+.[0-9]+.[0-9]+).*\")) by (kernel,environment)",
     "legendFormat": "{{kernel}}"
    }
   ]
  },
  {
   "title": "Workhorse req/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:gitlab_workhorse_http_requests_total:rate1m{env=\"$environment\",monitor=\"app\", route!=\"^/-/\"}[$__interval])",
     "legendFormat": "{{stage}} {{type}}"
    }
   ]
  },
  {
   "title": "Project mirror updates overdue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile(0.5, gitlab_database_rows{query_name=\"mirrors_ready_to_sync\",environment=\"$environment\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "ready to sync",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "quantile(0.5, gitlab_database_rows{query_name=\"mirrors_behind_schedule\",environment=\"$environment\"})",
     "legendFormat": "behind schedule"
    },
    {
     "expr": "quantile(0.5, gitlab_database_rows{query_name=\"mirrors_scheduled_or_started\",environment=\"$environment\"})",
     "legendFormat": "scheduled or started"
    }
   ]
  },
  {
   "title": "Sidekiq Queues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(sidekiq_queue_size{environment=~\"$environment\", name!=\"project_daily_statistics\"}) by (name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HAProxy backends",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 27 },
   "repeat": "backend",
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$environment\",monitor=\"default\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "5xx responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(backend_code:haproxy_server_http_responses_total:irate1m{env=\"$environment\",monitor=\"default\",code=\"5xx\"}[$__interval])) by (backend)",
     "legendFormat": "haproxy 5xx {{ backend }}"
    },
    {
     "expr": "sum without (zone) (avg_over_time(zone:stackdriver_haproxy_errors:rate1m{env=\"$environment\",monitor=\"default\"}[$__interval]))",
     "legendFormat": "SD haproxy {{code}}"
    },
    {
     "expr": "sum without (zone) (zone:stackdriver_haproxy_deadline_exceeded:rate1m{env=\"$environment\",monitor=\"default\"})",
     "legendFormat": "SD haproxy timeout"
    }
   ]
  },
  {
   "title": "HAProxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "HAProxy Backend Responses",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(backend_code:haproxy_server_http_responses_total:irate1m{env=\"$environment\",monitor=\"default\"}[$__interval])) by (backend)",
       "legendFormat": "Backend {{ backend }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Git Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git IO Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{environment=\"$environment\", tier=\"stor\", type=\"gitaly\", device=~\"sd.+\"}[$__interval])) without (device)\n  /\ncount(node_disk_io_time_seconds_total{environment=\"$environment\", tier=\"stor\", type=\"gitaly\", device=~\"sd.+\"}) without (device)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Git CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "instance:node_cpu_in_use:ratio{environment=\"$environment\", tier=\"stor\", type=\"gitaly\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Git Host Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_load1{environment=\"$environment\", tier=\"stor\", type=\"gitaly\"}[$__interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}