{
 "title": "Database Capacity and Saturation Analysis -  90 Days Copy",
 "time": { "from": "2020-05-14T00:00:00.000Z", "to": "2020-06-24T23:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "primary_name",
    "query": "patroni-01-db-gprd.c.gitlab-production.internal"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"gitlabhq_production\", environment=\"gprd\", tier=\"db\", type=\"patroni\"}[10m])"
    }
   ]
  },
  {
   "title": "CPU Usage - Primary Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{fqdn=\"$primary_name\", mode !=\"idle\"}[10m])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{ environment=\"gprd\", tier=\"db\", type=\"patroni\"}"
    }
   ]
  },
  {
   "title": "Context Switches - Primary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches_total{fqdn=\"$primary_name\"}[10m])"
    }
   ]
  },
  { "title": "IO Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "IO Wait Disk reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{environment=\"gprd\", tier=\"db\", type=\"patroni\", device=~\"sdb\"}[10m])) by (fqdn)"
    }
   ]
  },
  {
   "title": "IO Wait Disk Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{environment=\"gprd\", tier=\"db\", type=\"patroni\", device=~\"sdb\"}[10m])) by (fqdn) "
    }
   ]
  },
  {
   "title": "IO Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{environment=\"gprd\", tier=\"db\", type=\"patroni\", device=~\"sdb\"} [10m]) "
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~ \"node_filesystem_size.*\", environment=\"gprd\", tier=\"db\", type=\"patroni\", mountpoint=\"/var/opt/gitlab\"} - {__name__=~\"node_filesystem_free.*\",environment=\"gprd\", tier=\"db\", type=\"patroni\", mountpoint=\"/var/opt/gitlab\"}\n"
    }
   ]
  },
  {
   "title": "Disk Reads Bytes/Sec - Primary Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{fqdn=\"patroni-11-db-gprd.c.gitlab-production.internal\", device!~\"dm.*\"}[10m])"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes Sec - Primary host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{fqdn=\"patroni-11-db-gprd.c.gitlab-production.internal\", device!~\"dm.*\"}[10m])"
    }
   ]
  },
  {
   "title": "Disk Reads Ops per sec - Primary host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{fqdn=\"patroni-11-db-gprd.c.gitlab-production.internal\", device!~\"dm.*\"}[10m])"
    }
   ]
  },
  {
   "title": "Disk Writes Ops Sec - Primary Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{fqdn=\"patroni-11-db-gprd.c.gitlab-production.internal\", device!~\"dm.*\"}[10m])"
    }
   ]
  },
  { "title": "PGBouncer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "PGbouncer Web-API Core Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{fqdn=~\"pgbouncer-01-db-gprd.c.gitlab-production.internal|pgbouncer-02-db-gprd.c.gitlab-production.internal|pgbouncer-03-db-gprd.c.gitlab-production.internal\",mode=\"user\"}[10m])"
    }
   ]
  },
  {
   "title": "PGBouncer Sidekiq - Core utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{fqdn=~\"pgbouncer-sidekiq-01-db-gprd.c.gitlab-production.internal|pgbouncer-sidekiq-02-db-gprd.c.gitlab-production.internal|pgbouncer-sidekiq-03-db-gprd.c.gitlab-production.internal\",mode=\"user\"}[10m])"
    }
   ]
  },
  {
   "title": "PGBouncer Component Average CPU Saturation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{environment=\"gprd\", stage=\"main\", type=\"pgbouncer\", component=\"single_node_cpu\"}[10m]\n      )\n    ) by (component)\n  ,1)\n,0)"
    }
   ]
  },
  { "title": "Network Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Network Bytes Received - Primary Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\", fqdn=\"patroni-11-db-gprd.c.gitlab-production.internal\"}[10m])"
    }
   ]
  },
  {
   "title": "Network Bytes Sent - Primary Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\", fqdn=\"patroni-11-db-gprd.c.gitlab-production.internal\"}[10m])"
    }
   ]
  }
 ]
}