{
 "title": "delivery: Deployment SLO",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6594061683 at Wed Apr 10 14:51:29 UTC 2024",
 "tags": [
  "managed",
  "delivery",
  "release"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "target_slo",
    "label": "target SLO",
    "query": "label_values(delivery_deployment_duration_seconds_bucket, le)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment SLO Explainer",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "content": "This dashboard shows a summary of deployments on gitlab.com.\n\nThis section of the dashboard is governed by the `target SLO` variable.\n\n- __# deployments__ counts the number of deployments in the time range`\n- __Target SLO__ is the amount of seconds we consider acceptable for a complete deployment from gstg-cny (staging canary) to production (gprd), it can be one of the following values:\n  - `12600`: 3.5h\n  - `14400`: 4h\n  - `16200`: 4.5h\n  - `18000`: 5h\n  - `19800`: 5.5h\n  - `21600`: 6h\n  - `23400`: 6.5h\n  - `25200`: 7h\n  - `27000`: 7.5h\n  - `28800`: 8h\n  - `30600`: 8.5h\n  - `32400`: 9h\n  - `34200`: 9.5\n  - `36000`: 10h\n- __Apdex Score__ shows the percentage of deploymens in the time range that matched the `target SLO`.\n- __Apdex__ shows the Apdex score over time\n"
  },
  {
   "title": "# deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(delivery_deployment_duration_seconds_count{job=\"delivery-metrics\",status=\"success\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Target SLO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, count(delivery_deployment_duration_seconds_bucket{job=\"delivery-metrics\",le=\"$target_slo\"}) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(delivery_deployment_duration_seconds_bucket{job=\"delivery-metrics\",status=\"success\",le=\"$target_slo\"}[$__range]))\n/\nsum(rate(delivery_deployment_duration_seconds_count{job=\"delivery-metrics\",status=\"success\"}[$__range]))\n"
    }
   ]
  },
  {
   "title": "Deployment duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "clocks", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "max(delivery_deployment_duration_last_seconds) by (deployment_type, status)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "graph",
   "description": "Apdex is a measure of deployments that complete within an acceptable threshold duration. Actual threshold can be adjusted using the target SLO variable above in this page. Higher is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 200 },
   "yaxes": [
    {
     "format": "percentunit",
     "label": "% Deployments w/ satisfactory duration"
    }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum(rate(delivery_deployment_duration_seconds_bucket{job=\"delivery-metrics\",status=\"success\",le=\"$target_slo\"}[$__range]))\n/\nsum(rate(delivery_deployment_duration_seconds_count{job=\"delivery-metrics\",status=\"success\"}[$__range]))\n,1),0)\n"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}