{
 "title": "delivery: Release Management Toil",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4541957471 at Mon Jun 26 15:30:49 UTC 2023",
 "tags": [
  "managed",
  "delivery",
  "release"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "🚀 Tagged Releases 🚀", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Tagged Releases by Type",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(delivery_packages_tagging_total[$__range])) by (pkg_type,security))"
    }
   ]
  },
  {
   "title": "Auto-deploy Deployments Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "Auto-deploy Deployments Pipeline Duration",
   "type": "bargauge",
   "description": "For all the auto-deploy pipelines in the time range, display total duration per pipeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "delivery_deployment_pipeline_duration_seconds{project_name=\"gitlab-org/release/tools\", pipeline_name=\"Coordinator pipeline\"}",
     "legendFormat": "{{deploy_version}}"
    }
   ]
  },
  {
   "title": "❌ Incomplete/Failed Deployments ❌",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }
  },
  {
   "title": "Total Number of Incomplete Auto-Deployments",
   "type": "stat",
   "description": "Because of of how the delivery_deployment_completed metric works, it will always include the last one that is still deploying by the end of this query range (at the top). That is why this number is 1 less than the number of rows from the Incomplete Auto-Deploy Versions table.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (max_over_time(delivery_deployment_completed[$__range])) < 4"
    }
   ]
  },
  {
   "title": "Incomplete Auto-Deployment Versions",
   "type": "table",
   "description": "Remember to not count the currently deploying version. Because of of how the delivery_deployment_completed metric works, it will always include the last one that is still deploying by the end of this query range (at the top).",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 201 },
   "targets": [
    {
     "expr": "sum by (version) (max_over_time(delivery_deployment_completed[$__range])) < 4"
    }
   ]
  },
  { "title": "❌ Failed Jobs ❌", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 } },
  {
   "title": "Total Number of Job Failures",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_over_time(delivery_deployment_job_duration_seconds{job_status=\"failed\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Number of Job Failures Per Auto-Deploy Version (25 max)",
   "type": "bargauge",
   "description": "For up to 25 latest auto-deploy versions in the time range, display the total number of job failures per version",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 301 },
   "targets": [
    {
     "expr": "count by (deploy_version) (sum_over_time(delivery_deployment_job_duration_seconds{job_status=\"failed\"}[$__range]))",
     "legendFormat": "{{deploy_version}}"
    }
   ]
  },
  { "title": "🔄 Auto Deploy Job Retries 🔄", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 } },
  {
   "title": "Number of auto-deploy job retries per Project",
   "type": "table",
   "description": "This table shows the number of auto-deploy job retries per project for the duration chosen. For further insight, refer to the 'Number of auto-deploy retries per job' table, which separates the retries by job name",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 401 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(delivery_webhooks_auto_deploy_job_retries[$__range])) by (project) != 0)"
    }
   ]
  },
  {
   "title": "Number of auto-deploy retries per job",
   "type": "table",
   "description": "This table shows the number of auto-deploy job retries per project and per job for the duration chosen.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 401 },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(delivery_webhooks_auto_deploy_job_retries[$__range])) by (project, job_name) != 0)"
    }
   ]
  },
  {
   "title": "Increase in deployment pipeline duration due to retry of failed jobs",
   "type": "table",
   "description": "This panel shows how much the deployment pipeline duration was increased by the need to retry failed jobs. For example,\nif a failed job is retried and succeeds after an hour of the failure, the deployment pipeline duration was increased by an hour.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 500 },
   "targets": [
    {
     "expr": "sum by(job_name)(increase(delivery_webhooks_auto_deploy_job_failure_lost_seconds[$__range]) != 0)"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}