{
 "title": "delivery: deployment-metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5048021358 at Fri Sep  8 15:13:42 UTC 2023",
 "tags": [
  "managed",
  "delivery"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "deploy_version",
    "label": "version",
    "query": "label_values(delivery_deployment_merge_request_lead_time_seconds, deploy_version)"
   }
  ]
 },
 "panels": [
  { "title": "MTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MTTP over selected time range",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n                last_over_time(delivery_deployment_merge_request_lead_time_seconds{target_env=\"gprd\", target_stage=\"main\"}[$__range])\n                  unless\n                (\n                  last_over_time(\n                    delivery_deployment_merge_request_lead_time_seconds{target_env=\"gprd\", target_stage=\"main\"}[12h] offset $__range\n                  )\n                )\n              )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adjusted MTTP over selected time range",
   "type": "stat",
   "description": "MTTP over selected time range when ignoring weekends. If the adjusted metric is not available, it\n                    will use the regular (unadjusted) metric. The adjusted metric is available from 7th Aug 2023 onwards.",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\n                (\n                  last_over_time(delivery_deployment_merge_request_adjusted_lead_time_seconds{target_env=\"gprd\", target_stage=\"main\"}[$__range])\n                    or\n                  last_over_time(delivery_deployment_merge_request_lead_time_seconds{target_env=\"gprd\", target_stage=\"main\"}[$__range])\n                )\n                  unless\n                (\n                  last_over_time(delivery_deployment_merge_request_adjusted_lead_time_seconds{target_env=\"gprd\", target_stage=\"main\"}[12h] offset $__range)\n                    or\n                  last_over_time(delivery_deployment_merge_request_lead_time_seconds{target_env=\"gprd\", target_stage=\"main\"}[12h] offset $__range)\n                )\n              )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🚀 Downstream Pipeline statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Downstream Pipelines Duration",
   "type": "bargauge",
   "description": "Duration for each downstream pipelines to complete",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (target_env, target_stage) (delivery_deployment_pipeline_duration_seconds{target_env!=\"\",target_stage!=\"\", deploy_version=\"$deploy_version\", pipeline_name!=\"Coordinator pipeline\"})",
     "legendFormat": "{{target_env, target_stage}}"
    }
   ]
  },
  {
   "title": "Coordinated Pipeline Duration",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delivery_deployment_pipeline_duration_seconds{project_name=\"gitlab-org/release/tools\", pipeline_name=\"Coordinator pipeline\", deploy_version=\"$deploy_version\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipelines overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "last_over_time(delivery_deployment_pipeline_duration_seconds{deploy_version=\"16.0.202304280320-e20d745c2fc.a175ce27071\", pipeline_name!=\"Coordinator pipeline\"}[$__range])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "📊 Merge requests statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Merge requests lead time to production",
   "type": "bargauge",
   "description": "Time it take Merge Request from being merged to production",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "last_over_time(delivery_deployment_merge_request_lead_time_seconds{target_env=\"gprd\", target_stage=\"main\", deploy_version=\"$deploy_version\"}[$__range])",
     "legendFormat": "{{mr_id}}"
    }
   ]
  },
  {
   "title": "Average MR lead time to production for selected version",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_over_time(delivery_deployment_merge_request_lead_time_seconds{target_env=\"gprd\", target_stage=\"main\", deploy_version=\"$deploy_version\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adjusted merge requests lead time to production",
   "type": "bargauge",
   "description": "Time it takes merge requests from being merged to production, adjusted to ignore weekends",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "last_over_time(delivery_deployment_merge_request_adjusted_lead_time_seconds{target_env=\"gprd\", target_stage=\"main\", deploy_version=\"$deploy_version\"}[$__range])",
     "legendFormat": "{{mr_id}}"
    }
   ]
  },
  {
   "title": "Average adjusted MR lead time to production for selected version",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_over_time(delivery_deployment_merge_request_adjusted_lead_time_seconds{target_env=\"gprd\", target_stage=\"main\", deploy_version=\"$deploy_version\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}