{
 "title": "delivery: Deployment Blockers - Playground",
 "description": "Uploaded by mawreendelacruz at Wed Jun 26 11:48:46 UTC 2024",
 "tags": [
  "managed",
  "delivery",
  "release"
 ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "root_cause",
    "query": "label_values(delivery_deployment_blocker_count{root_cause!=\"RootCause::FlakyTest\"},root_cause)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Deployment Blockers\n\nDeployment failures are currently automatically captured under [release/tasks issues](https://gitlab.com/gitlab-org/release/tasks/-/issues).\nRelease managers are responsible for labeling these failures with appropriate `RootCause::*` labels. By the start of the following week (Monday), the `deployments:blockers_report` scheduled pipeline in the [release/tools](https://ops.gitlab.net/gitlab-org/release/tools/-/pipeline_schedules) repo reviews the labeled issues and generates a weekly deployment blockers issue, like this [one](https://gitlab.com/gitlab-org/release/tasks/-/issues/11125).\n\nThis dashboard tracks the trend of recurring root causes for deployment blockers. Each root cause is displayed in separate rows with three panels: one for the count of blockers, one for `gprd` hours blocked, and one for `gstg` hours blocked. At the top, there is an overview of the failure types, including the total calculations for the entire specified time window.\n\nLinks:\n- [List of root causes](https://gitlab.com/gitlab-org/release/tasks/-/labels?subscribed=&sort=relevance&search=RootCause)\n- [Deployments metrics review](https://gitlab.com/groups/gitlab-com/gl-infra/-/epics/1192)\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deployments Blockers per Week",
   "type": "trend",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_blocker_count{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\", target_env=\"gprd\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\", target_env=\"gstg\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_blocker_count{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\", target_env=\"gprd\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\", target_env=\"gstg\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Blockers Count per Root Cause",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_blocker_count{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total gprd Hours Blocked per Root Cause",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (max_over_time(delivery_deployment_hours_blocked{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\", target_env=\"gprd\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total gstg Hours Blocked per Root Cause",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\", target_env=\"gstg\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$root_cause",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "root_cause",
   "targets": [
    {}
   ]
  },
  {
   "title": "Blockers Count for $root_cause",
   "type": "trend",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_blocker_count{root_cause=\"$root_cause\"}[1d]))"
    }
   ]
  },
  {
   "title": "gprd Hours Blocked for $root_cause",
   "type": "trend",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=\"$root_cause\", target_env=\"gprd\"}[1d]))"
    }
   ]
  },
  {
   "title": "gstg Hours Blocked for $root_cause",
   "type": "trend",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=\"$root_cause\", target_env=\"gstg\"}[1d]))"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_blocker_count{root_cause=~\"$root_cause\", root_cause!=\"RootCause::FlakyTest\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=~\"$root_cause\", root_cause!=\"RootCause::FlakyTest\", target_env=\"gprd\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (week, root_cause) (last_over_time(delivery_deployment_hours_blocked{root_cause=~\"$root_cause\", root_cause!=\"RootCause::FlakyTest\", target_env=\"gstg\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "options": {
    "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
   },
   "targets": [
    {}
   ]
  }
 ]
}