{
 "title": "Delivery - deployment blockers metric",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "root_cause",
    "query": {
     "query": "label_values(delivery_deployment_blocker_count{root_cause!=\"RootCause::FlakyTest\"},root_cause)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Deployment Blockers\n\nDeployment failures are currently automatically captured under [release/tasks issues](https://gitlab.com/gitlab-org/release/tasks/-/issues). \nRelease managers are responsible for labeling these failures with appropriate `RootCause::*` labels. By the start of the following week (Monday), the `deployments:blockers_report` scheduled pipeline in the [release/tools](https://ops.gitlab.net/gitlab-org/release/tools/-/pipeline_schedules) repo reviews the labeled issues and generates a weekly deployment blockers issue, like this [one](https://gitlab.com/gitlab-org/release/tasks/-/issues/11125).\n\nThis dashboard tracks the trend of recurring root causes for deployment blockers. Each root cause is displayed in separate rows with three panels: one for the count of blockers, one for `gprd` hours blocked, and one for `gstg` hours blocked. At the top, there is an overview of the failure types, including the total calculations for the entire specified time window.\n\nLinks:\n- [List of root causes](https://gitlab.com/gitlab-org/release/tasks/-/labels?subscribed=&sort=relevance&search=RootCause)\n- [Deployments metrics review](https://gitlab.com/groups/gitlab-com/gl-infra/-/epics/1192)\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (root_cause) (last_over_time(delivery_deployment_blocker_count{root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (root_cause) (last_over_time(delivery_deployment_hours_blocked{target_env=\"gprd\",root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by (root_cause) (last_over_time(delivery_deployment_hours_blocked{target_env=\"gstg\",root_cause=~\".+\", root_cause!=\"RootCause::FlakyTest\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$root_cause", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "root_cause" },
  {
   "title": "Blockers Count for $root_cause",
   "type": "trend",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(week) (last_over_time(delivery_deployment_blocker_count{root_cause=\"$root_cause\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gprd Hours Blocked for $root_cause",
   "type": "trend",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(week) (last_over_time(delivery_deployment_hours_blocked{root_cause=\"$root_cause\",target_env=\"gprd\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gstg Hours Blocked for $root_cause",
   "type": "trend",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(week) (last_over_time(delivery_deployment_hours_blocked{root_cause=\"$root_cause\",target_env=\"gstg\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max by(week) (last_over_time(delivery_deployment_blocker_count{root_cause=\"$root_cause\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(week) (last_over_time(delivery_deployment_hours_blocked{root_cause=\"$root_cause\",target_env=\"gprd\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(week) (last_over_time(delivery_deployment_hours_blocked{root_cause=\"$root_cause\",target_env=\"gstg\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}