{
 "title": "delivery: Deployment Overview",
 "description": "Uploaded by vglafirov at Wed Apr 26 12:22:09 UTC 2023",
 "tags": [
  "managed",
  "delivery"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(delivery_deployment_merge_request_lead_time_seconds, target_env)"
    }
   },
   {
    "name": "target_stage",
    "label": "stage",
    "query": {
     "query": "label_values(delivery_deployment_merge_request_lead_time_seconds{target_env=\"$environment\"}, target_stage)"
    }
   },
   {
    "name": "deploy_version",
    "label": "version",
    "query": {
     "query": "label_values(delivery_deployment_merge_request_lead_time_seconds{target_env=\"$environment\", target_stage=\"$target_stage\"}, deploy_version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "🚀 Deployment statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deployment duration",
   "type": "state-timeline",
   "description": "Deployment duration by Gitlab project",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "delivery_deployment_pipeline_duration_seconds{deploy_version=\"$deploy_version\"}",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Total deployment time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(delivery_deployment_pipeline_duration_seconds{target_env=\"$environment\", target_stage=\"$target_stage\", deploy_version=\"$deploy_version\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📊 Merge requests statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Merge requests lead time",
   "type": "bargauge",
   "description": "Time it take Merge Request from being merged to production",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(delivery_deployment_merge_request_lead_time_seconds{target_env=\"$environment\", target_stage=\"$target_stage\", deploy_version=\"$deploy_version\"}[$__range])",
     "legendFormat": "{{mr_id}}"
    }
   ]
  },
  {
   "title": "Average MR lead time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_over_time(delivery_deployment_merge_request_lead_time_seconds{target_env=\"$environment\", target_stage=\"$target_stage\", deploy_version=\"$deploy_version\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n",
   "targets": [
    {}
   ]
  }
 ]
}