{
 "title": "Delivery rollbacks",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Migrations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pending migrations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delivery_metrics_pending_migrations_total) by (env, stage)",
     "legendFormat": "{{env}}-{{stage}}"
    }
   ]
  },
  {
   "title": "Deployments started and deployments tagged as separate panels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Deployments started",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(delivery_deployment_started_total{target_env=~\".+\"}[1d])) by (target_env)",
     "legendFormat": "{{target_env}}"
    }
   ]
  },
  {
   "title": "Deployments tagged",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(delivery_packages_tagging_total[1d])) by (stage)",
     "legendFormat": "packages_tagged"
    }
   ]
  },
  {
   "title": "Deployments started and deployments tagged displayed by environment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Gstg - Deployments started",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(delivery_packages_tagging_total[1d])) by (stage)",
     "legendFormat": "packages_tagged"
    },
    {
     "expr": "sum(increase(delivery_deployment_started_total{target_env=~\"gstg.*\"}[1d])) by (target_env)",
     "legendFormat": "{{target_env}}"
    }
   ]
  },
  {
   "title": "Gprd - Deployments started",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(delivery_packages_tagging_total[1d])) by (stage)",
     "legendFormat": "packages_tagged"
    },
    {
     "expr": "sum(increase(delivery_deployment_started_total{target_env=~\"gprd.*\"}[1d])) by (target_env)",
     "legendFormat": "{{target_env}}"
    }
   ]
  }
 ]
}