{
 "title": "delivery: Release Management",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5276946365 at Thu Oct 12 07:19:12 UTC 2023",
 "tags": [
  "managed",
  "delivery",
  "release"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "🚀 gprd",
   "type": "stat",
   "description": "Rails revision on Production.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "String" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk(1, count(\n    gitlab_version_info{environment=\"gprd\", stage=\"main\", component=\"gitlab-rails\"}\n  ) by (version)),\n  \"version\", \"$1\",\n  \"version\", \"^([A-Fa-f0-9]{11}).*$\"\n)\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🐤 gprd-cny",
   "type": "stat",
   "description": "Rails revision on Canary.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "String" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk(1, count(\n    gitlab_version_info{environment=\"gprd\", stage=\"cny\", component=\"gitlab-rails\"}\n  ) by (version)),\n  \"version\", \"$1\",\n  \"version\", \"^([A-Fa-f0-9]{11}).*$\"\n)\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🏗 gstg",
   "type": "stat",
   "description": "Rails revision on Staging.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "String" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk(1, count(\n    gitlab_version_info{environment=\"gstg\", stage=\"main\", component=\"gitlab-rails\"}\n  ) by (version)),\n  \"version\", \"$1\",\n  \"version\", \"^([A-Fa-f0-9]{11}).*$\"\n)\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🐣 gstg-cny",
   "type": "stat",
   "description": "Rails revision on Staging Canary.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "String" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk(1, count(\n    gitlab_version_info{environment=\"gstg\", stage=\"cny\", component=\"gitlab-rails\"}\n  ) by (version)),\n  \"version\", \"$1\",\n  \"version\", \"^([A-Fa-f0-9]{11}).*$\"\n)\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🚧 gstg-ref",
   "type": "stat",
   "description": "Rails revision on Staging Ref.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "String" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  topk(1, count(\n    gitlab_version_info{environment=\"gstg-ref\", stage=\"main\", component=\"gitlab-rails\"}\n  ) by (version)),\n  \"version\", \"$1\",\n  \"version\", \"^([A-Fa-f0-9]{11}).*$\"\n)\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🚀 gprd",
   "type": "stat",
   "description": "Package running on Production.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "String" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, count(\n  omnibus_build_info{environment=\"gprd\", stage=\"main\"}\n) by (version))\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🐤 gprd-cny",
   "type": "stat",
   "description": "Package running on Canary.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "String" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, count(\n  omnibus_build_info{environment=\"gprd\", stage=\"cny\"}\n) by (version))\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🏗 gstg",
   "type": "stat",
   "description": "Package running on Staging.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "String" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, count(\n  omnibus_build_info{environment=\"gstg\", stage=\"main\"}\n) by (version))\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🐣 gstg-cny",
   "type": "stat",
   "description": "Package running on Staging Canary.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "String" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, count(\n  omnibus_build_info{environment=\"gstg\", stage=\"cny\"}\n) by (version))\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🚧 gstg-ref",
   "type": "stat",
   "description": "Package running on Staging Ref.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "String" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, count(\n  omnibus_build_info{environment=\"gstg-ref\", stage=\"main\"}\n) by (version))\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Auto-deploy pressure",
   "type": "stat",
   "description": "The number of commits in `master` not yet deployed to each environment.",
   "gridPos": { "h": 15, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delivery_auto_deploy_pressure{job=\"delivery-metrics\"}) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Patch release pressure: S1/S2",
   "type": "bargauge",
   "description": "Number of S1/S2 merge requests merged in previous releases.",
   "gridPos": { "h": 15, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (version) (delivery_release_pressure{severity=~\"severity::1|severity::2\",job=\"delivery-metrics\"})\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Patch release pressure: Total ",
   "type": "bargauge",
   "description": "Number of merge requests merged in previous releases regardless severity.",
   "gridPos": { "h": 15, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (version) (delivery_release_pressure{job=\"delivery-metrics\"})\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Pending migrations",
   "type": "stat",
   "description": "The number of migrations pending execution in each environment.",
   "gridPos": { "h": 15, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil((sum(delivery_metrics_pending_migrations_total{env=~\"gstg|gprd\",stage=\"main\"}) by (env))/2)",
     "legendFormat": "{{env}}"
    }
   ]
  },
  { "title": "🚀 gprd", "type": "row", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "🚀 Auto-deploy pressure",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2002 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "expr": "delivery_auto_deploy_pressure{job=\"delivery-metrics\", role=\"gprd\"}",
     "legendFormat": "Commits"
    }
   ]
  },
  { "title": "🐤 gprd-cny", "type": "row", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4000 } },
  {
   "title": "🐤 Auto-deploy pressure",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4002 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "expr": "delivery_auto_deploy_pressure{job=\"delivery-metrics\", role=\"gprd-cny\"}",
     "legendFormat": "Commits"
    }
   ]
  },
  { "title": "🏗 gstg", "type": "row", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6000 } },
  {
   "title": "🏗 Auto-deploy pressure",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6002 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "expr": "delivery_auto_deploy_pressure{job=\"delivery-metrics\", role=\"gstg\"}",
     "legendFormat": "Commits"
    }
   ]
  },
  { "title": "🐣 gstg-cny", "type": "row", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8000 } },
  {
   "title": "🐣 Auto-deploy pressure",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8002 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "expr": "delivery_auto_deploy_pressure{job=\"delivery-metrics\", role=\"gstg-cny\"}",
     "legendFormat": "Commits"
    }
   ]
  },
  { "title": "🚧 gstg-ref", "type": "row", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10000 } },
  {
   "title": "🚧 Auto-deploy pressure",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10002 },
   "yaxes": [
    { "format": "short", "label": "Commits" }
   ],
   "targets": [
    {
     "expr": "delivery_auto_deploy_pressure{job=\"delivery-metrics\", role=\"gstg-ref\"}",
     "legendFormat": "Commits"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}