{
 "title": "delivery: jobs-duration",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5722590111 at Mon Dec 11 08:31:15 UTC 2023",
 "tags": [
  "managed",
  "delivery"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "deploy_version",
    "label": "Version",
    "query": "label_values(delivery_deployment_job_duration_seconds, deploy_version)"
   },
   {
    "name": "job_name",
    "label": "Job",
    "query": "label_values(delivery_deployment_job_duration_seconds, job_name)"
   }
  ]
 },
 "panels": [
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job Duration",
   "type": "stat",
   "description": "Median duration over the selected time range",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\n          quantile(0.5,\n            last_over_time(delivery_deployment_job_duration_seconds{job_name=\"$job_name\"}[$__range])\n              unless\n            last_over_time(delivery_deployment_job_duration_seconds{job_name=\"$job_name\"}[12h] offset $__range)\n          )",
     "legendFormat": "Median"
    },
    {
     "expr": "max(\n            last_over_time(delivery_deployment_job_duration_seconds{job_name=\"$job_name\"}[$__range])\n              unless\n            last_over_time(delivery_deployment_job_duration_seconds{job_name=\"$job_name\"}[12h] offset $__range)\n          )",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Top 10 job duration per deployment",
   "type": "bargauge",
   "description": "Top 10 job duration per deployment",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, avg by(job_name)(delivery_deployment_job_duration_seconds{deploy_version=\"$deploy_version\"}))",
     "legendFormat": "{{deploy_version}}"
    }
   ]
  },
  {
   "title": "Maximum job duration per project",
   "type": "bargauge",
   "description": "Maximum job duration per project, eg, gprd-gitaly takes most of the duration in `deployer` project.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(project_name)(delivery_deployment_job_duration_seconds)",
     "legendFormat": "{{deploy_version}}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}