{
 "title": "delivery: Deployment Health",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5083514395 at Thu Sep 14 06:40:06 UTC 2023",
 "tags": [
  "managed",
  "delivery",
  "release"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "type",
    "query": "label_values(gitlab_service_ops:rate{environment=\"$environment\"}, type)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deploy Health",
   "type": "graph",
   "description": "Showcases whether or not an environment and its stage is healthy",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "gitlab_deployment_health:stage{env=\"$environment\", stage=\"$stage\"}",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "content": "This panel shows the Deployment Health which is taking into account all\nservices for the provided $environment and $stage selected\n\nValues provided are effectively a boolean.  Where `1` is true, or in the\ncase of metrics, a *healthy* state.  Where `0` is false, or in this case,\n*unhealthy*.\n\nView the **Service Deployment Health** for a breakdown of each\ncontributing service that is rolled into this metric.\n"
  },
  { "title": "Service Breakdown", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Service Deployment Health",
   "type": "graph",
   "description": "Showcases whether or not the environments stage is healthy with a breakdown by the individual services that contribute to the metric",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_deployment_health:service{env=\"$environment\", stage=\"$stage\", type!=\"registry\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "content": "This panel shows the Deployment Health which is showcasing each of the\nservices that are a blocker for deployments.\n\nValues provided are effectively a boolean.  Where `1` is true, or in the\ncase of metrics, a *healthy* state.  Where `0` is false, or in this case,\n*unhealthy*.\n\nWe are using a stack chart to show case each metric individually in an\neasier fashion.\n\nView the **Component Breakdown** for a breakdown of each contributing\nmetric that is rolled into this metrics.\n"
  },
  { "title": "Component Breakdown", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Component Deployment Health",
   "type": "graph",
   "description": "Showcases whether or not the environments stage is healthy with a breakdown by the individual services that contribute to the metric",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_deployment_health:service:apdex{env=\"$environment\", stage=\"$stage\", type=\"$type\"}",
     "legendFormat": "Apdex"
    },
    {
     "expr": "gitlab_deployment_health:service:errors{env=\"$environment\", stage=\"$stage\", type=\"$type\"}",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 2 },
   "content": "This panel shows the Deployment Health which is showcasing each of the\ncontributing factors, Apdex, and Error SLI's and whether or not they\nare within the service boundaries.\n\nValues provided are effectively a boolean.  Where `1` is true, or in the\ncase of metrics, a *healthy* state.  Where `0` is false, or in this case,\n*unhealthy*.\n\nWe're using a stack chart to show case each metric individually in an\neasier fashion.\n"
  },
  {
   "title": "Component Deployment Health Breakdown",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "content": "Utilize the below links to browse to the various dashboards that\nshowcases the burnrates for the various windows of time that contribute\ntowards to deployment health metric for the selected component, stage,\nand environment.\n  - [Error SLO Analysis](https://dashboards.gitlab.net/d/alerts-service_slo_error/alerts-global-service-aggregated-metrics-error-slo-analysis?orgId=1&var-PROMETHEUS_DS=Global&var-environment=$environment&var-type=$type&var-stage=$stage&var-proposed_slo=0.999)\n  - [Apdex SLO Analysis](https://dashboards.gitlab.net/d/alerts-service_slo_apdex/alerts-global-service-aggregated-metrics-apdex-slo-analysis?orgId=1&var-PROMETHEUS_DS=Global&var-environment=$environment&var-type=$type&var-stage=$stage&var-proposed_slo=0.997)\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}