{
 "title": "delivery: Kubernetes Migration Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/1230982425 at Mon May  3 08:33:15 UTC 2021",
 "tags": [
  "managed",
  "delivery",
  "release"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes Migration Summary Explainer",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "content": "This dashboard shows a summary of resource utilization between virtual machines and the Kubernetes clusters for GitLab.com.\nFor a summary of the current migration status see [the tracking epic for the migration](https://gitlab.com/groups/gitlab-com/gl-infra/-/epics/112)\nThis dashboard focuses on the following resources during the migration to help track utilization and cost as services are brought over into the cluster. This only includes services that will be migrated and excludes others that will remain on virtual machines.\n\n**It does not include the following services:**\n  * Pages\n  * Patroni\n  * Redis\n  * Gitaly\n  * Praefect\n\n"
  },
  { "title": "🖥 Virtual Machines", "type": "row", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Available cores",
   "type": "stat",
   "description": "Total number of cores",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_cpus:count{env=\"$environment\",type!~\"web-pages|praefect|camoproxy\"})"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(instance:node_cpu_utilization:ratio{type!~\"web-pages|praefect|camoproxy\"})"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "description": "Total memory",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{type!~\"web-pages|praefect|camoproxy\", env=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Avg Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(instance:node_memory_utilization:ratio{type!~\"web-pages|praefect|camoproxy\", env=\"$environment\"})"
    }
   ]
  },
  { "title": "☸️Kubernetes Cluster", "type": "row", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Available cores",
   "type": "stat",
   "description": "Total number of cores",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(instance:node_cpus:count{cluster!=\"\", env=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Avg CPU utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(instance:node_cpu_utilization:ratio{cluster!=\"\", env=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "description": "Total memory",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster!=\"\", env=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Avg Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(instance:node_memory_utilization:ratio{cluster!=\"\", env=\"$environment\"})"
    }
   ]
  },
  {
   "title": "☸️Pods: replicas, CPUs and Memory in use by Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "gitlab-shell: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-gitlab-shell.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "gitlab-shell: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-gitlab-shell.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "gitlab-shell: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-gitlab-shell.*$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "registry: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-registry.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "registry: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-registry.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "registry: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-registry.*$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "mailroom: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-mailroom.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "mailroom: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-mailroom.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "mailroom: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-mailroom.*$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "sidekiq-catchall: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-sidekiq-catchall.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "sidekiq-catchall: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-sidekiq-catchall.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "sidekiq-catchall: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-sidekiq-catchall.*$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "sidekiq-memory-bound: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-sidekiq-memory-bound.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "sidekiq-memory-bound: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-sidekiq-memory-bound.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "sidekiq-memory-bound: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-sidekiq-memory-bound.*$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "sidekiq-elasticsearch: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-sidekiq-elasticsearch.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "sidekiq-elasticsearch: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-sidekiq-elasticsearch.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "sidekiq-elasticsearch: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-sidekiq-elasticsearch.*$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "sidekiq-low-urgency-cpu-bound: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-sidekiq-low-urgency-cpu-bound.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "sidekiq-low-urgency-cpu-bound: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-sidekiq-low-urgency-cpu-bound.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "sidekiq-low-urgency-cpu-bound: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-sidekiq-low-urgency-cpu-bound.*$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-other: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-sidekiq-urgent-other.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-other: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-sidekiq-urgent-other.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-other: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-sidekiq-urgent-other.*$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "sidekiq-database-throttled: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-sidekiq-database-throttled.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "sidekiq-database-throttled: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-sidekiq-database-throttled.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "sidekiq-database-throttled: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-sidekiq-database-throttled.*$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "sidekiq-gitaly-throttled: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-sidekiq-gitaly-throttled.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "sidekiq-gitaly-throttled: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-sidekiq-gitaly-throttled.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "sidekiq-gitaly-throttled: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-sidekiq-gitaly-throttled.*$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-cpu-bound: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-sidekiq-urgent-cpu-bound.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-cpu-bound: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-sidekiq-urgent-cpu-bound.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-cpu-bound: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-sidekiq-urgent-cpu-bound.*$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "webservice: Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none", "label": "replicas" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-webservice.*\", cluster=~\"${environment}.*\"})"
    }
   ]
  },
  {
   "title": "webservice: CPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "none", "label": "cpus" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{env=~\"$environment\", pod=~\"gitlab-webservice.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "webservice: Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{env=~\"gprd\", node=~\"^.*$\", id!=\"\", container!=\"POD\", pod=~\"^gitlab-webservice.*$\", container!=\"\"})"
    }
   ]
  }
 ]
}