{
 "title": "delivery: Auto-Deploy packages information",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7422010320 at Wed Jul 24 20:48:47 UTC 2024",
 "tags": [
  "managed",
  "delivery",
  "release"
 ],
 "time": { "from": "now-14d", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "📦 Number of packages tagged per day",
   "type": "graph",
   "description": "Number of packages tagged per day.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(delivery_packages_tagging_total{pkg_type=\"auto_deploy\"}[1d])) by (pkg_type)",
     "legendFormat": "Tagged packages"
    },
    {
     "expr": "clamp_min(\n  sum(increase(delivery_packages_tagging_total{pkg_type=\"auto_deploy\"}[1d])) -\n  sum(increase(delivery_deployment_started_total{target_env=\"gprd\"}[1d]))\n, 0)\n",
     "legendFormat": "Not promoted"
    },
    {
     "expr": "sum(increase(delivery_auto_deploy_picks_total[1h])) by (status)",
     "legendFormat": "Pick into Auto-Deploy - {{status}}"
    }
   ]
  },
  {
   "title": "Active coordinated pipelines",
   "type": "graph",
   "description": "Number of deployments pipelines that are running, scheduled, or manual",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(delivery_deployment_pipelines_total{status=~\"scheduled|running|manual|failed\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "🚀 Number of deployments started per day",
   "type": "graph",
   "description": "Number of deployments started per day.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(delivery_deployment_started_total{target_env!=\"gstg-ref\"}[1d])) by (target_env)",
     "legendFormat": "{{target_env}}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}