{
 "title": "delivery: delivery-metrics deployment",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6253182118 at Sun Feb 25 23:46:55 UTC 2024",
 "tags": [
  "managed",
  "delivery"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "delivery-metrics Explainer",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "This dashboard shows information about [delivery-metrics](https://gitlab.com/gitlab-org/release-tools/-/tree/master/metrics) deployment.\n\nThis is for monitoring and debugging and should have no implications on release managers activities.\n"
  },
  {
   "title": "PODs",
   "type": "table",
   "description": "This table shows the pods running delivery-metrics with their revision and build date, except during a deployment, we expect to see only one pod",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "count(delivery_version_info) by (revision, build_date, pod)"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"delivery\",service=\"delivery-metrics\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=\"delivery\",service=\"delivery-metrics\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 200 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{namespace=\"delivery\",service=\"delivery-metrics\"}[$__interval])",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{namespace=\"delivery\",service=\"delivery-metrics\"}[$__interval])",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "go memestat",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=\"delivery\",service=\"delivery-metrics\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"delivery\",service=\"delivery-metrics\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"delivery\",service=\"delivery-metrics\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"delivery\",service=\"delivery-metrics\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 210 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{namespace=\"delivery\",service=\"delivery-metrics\"}[$__interval])",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"delivery\",service=\"delivery-metrics\"}[$__interval])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=\"delivery\",service=\"delivery-metrics\"}[$__interval])",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=\"delivery\",service=\"delivery-metrics\"}[$__interval])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 300 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"delivery\",service=\"delivery-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 300 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{namespace=\"delivery\",service=\"delivery-metrics\"}[$__interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "gorountines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 400 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"delivery\",service=\"delivery-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC duration quintile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 400 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"delivery\",service=\"delivery-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}