{
 "title": "Deployment and Patching",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg,pre" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "prometheus_app", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Majority $environment main version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, count(omnibus_build_info{environment=~\"$environment\"}) by (version))",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Majority $environment canary version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, count(omnibus_build_info{environment=~\"$environment\", stage=\"cny\"}) by (version))",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Fleet deployments",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max(deployer_job_end_time{environment=\"$environment\",check_mode=\"0\", ci_job_name !~ \".*-cny-.*\"} * 1000) by (ci_stage_name, deploy_version)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last successful job completed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(deployer_job_end_time{environment=\"$environment\", check_mode=\"0\", failure=\"0\"} * 1000)"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Timings ( job duration )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "deployer_job_end_time{check_mode=\"0\", environment=\"$environment\", instance !~ '^[0-9]', pipeline_iid=\"\", ci_job_name !~ \".*-cny-.*\"} - deployer_job_start_time{environment=\"$environment\", check_mode=\"0\", instance !~ '^[0-9]', pipeline_iid=\"\", ci_job_name !~ \".*-cny-.*\"}",
     "legendFormat": "{{ ci_job_name }}"
    }
   ]
  },
  {
   "title": "Changes per job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deployer_job_changes{environment=\"$environment\", check_mode=\"0\", instance !~ '^[0-9]', pipeline_iid=\"\", ci_job_name !~ \".*-cny-.*\"}",
     "legendFormat": "{{ ci_job_name }}"
    }
   ]
  },
  {
   "title": "Timing ( job duration / number of changes )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(deployer_job_end_time{environment=\"$environment\", check_mode = \"0\", instance !~ '^[0-9]', pipeline_iid=\"\", ci_job_name !~ \".*-cny-.*\"} - deployer_job_start_time{check_mode = \"0\", instance !~ '^[0-9]', pipeline_iid=\"\", ci_job_name !~ \".*-cny-.*\"}) / deployer_job_changes{check_mode = \"0\", instance !~ '^[0-9]', pipeline_iid=\"\", ci_job_name !~ \".*-cny-.*\"}",
     "legendFormat": "{{ ci_job_name }}"
    }
   ]
  },
  {
   "title": "Job timings for dry-runs (gstg only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dry run timings by job",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "deployer_job_end_time{check_mode=\"1\", instance !~ '^[0-9]', pipeline_iid=\"\"} - deployer_job_start_time{check_mode=\"1\", instance !~ '^[0-9]', pipeline_iid=\"\"}",
       "legendFormat": "{{ ci_job_name }}"
      }
     ]
    },
    {
     "title": "Dry run timings / change",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(deployer_job_end_time{check_mode = \"1\", instance !~ '^[0-9]', pipeline_iid=\"\"} - deployer_job_start_time{check_mode = \"1\", instance !~ '^[0-9]', pipeline_iid=\"\"}) / deployer_job_changes{check_mode = \"1\", instance !~ '^[0-9]', pipeline_iid=\"\"}",
       "legendFormat": "{{ ci_job_name }}"
      }
     ]
    },
    {
     "title": "Last deployer dry-run",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "format": "dateTimeFromNow",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(deployer_job_end_time{environment=\"$environment\", check_mode=\"1\"} * 1000)"
      }
     ]
    },
    {
     "title": "Fleet dry-run  deployments",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 6, "y": 19 },
     "targets": [
      {
       "expr": "max(deployer_job_end_time{environment=\"$environment\",check_mode=\"1\"} * 1000) by (ci_stage_name, deploy_version)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}