{
 "title": "Dynamic Image Resizing",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "image_resize_processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_workhorse_image_resize_processes"
    }
   ]
  },
  {
   "title": "concurrency_limit_exceeds_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_workhorse_image_resize_concurrency_limit_exceeds_total"
    }
   ]
  },
  {
   "title": "rate(completed_total[5m])",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gitlab_workhorse_image_resize_completed_total[1m])"
    }
   ]
  }
 ]
}