{
 "title": "ebpf (moved to host stats > disk performance)",
 "description": "(moved to host stats > disk performance)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(up{job=\"bpf\"}, env)"
   },
   {
    "name": "fqdn",
    "label": "fqdn",
    "query": "label_values(ebpf_exporter_enabled_programs{env=\"$env\"}, fqdn)"
   },
   {
    "name": "device",
    "query": "label_values(ebpf_exporter_bio_latency_seconds_count{env=\"$env\",fqdn=\"$fqdn\"}, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Block IO Latency - Read",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ebpf_exporter_bio_latency_seconds_bucket{env=\"gstg\", fqdn=\"$fqdn\", device=\"$device\", operation=\"read\", le!=\"+Inf\"}[$__interval]))",
     "legendFormat": "{{ le }} "
    }
   ]
  },
  {
   "title": "Block IO Latency - Write",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ebpf_exporter_bio_latency_seconds_bucket{env=\"gstg\", fqdn=\"$fqdn\", device=\"$device\", operation=\"write\", le!=\"+Inf\"}[$__interval]))",
     "legendFormat": "{{ le }} "
    }
   ]
  },
  {
   "title": "Block IO Size - Read",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ebpf_exporter_bio_size_bytes_bucket{env=\"$env\", fqdn=\"$fqdn\", device=\"$device\", operation=\"read\", le!=\"+Inf\"}[$__interval]))",
     "legendFormat": "{{ le }} "
    }
   ]
  },
  {
   "title": "Block IO Size - Write",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ebpf_exporter_bio_size_bytes_bucket{env=\"$env\", fqdn=\"$fqdn\", device=\"$device\", operation=\"write\", le!=\"+Inf\"}[$__interval]))",
     "legendFormat": "{{ le }} "
    }
   ]
  }
 ]
}