{
 "title": "Error Budget",
 "time": { "from": "now-45d", "to": "now" },
 "panels": [
  { "title": "Weekly Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall Service SLO Adherence over the past 7 Days",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort(avg(avg_over_time(slo_observation_status{environment=\"gprd\", stage=~\"|main\"}[1w])) by (environment, tier, type)) ",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Apdex SLO adherence over the past 7 days",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sort(avg_over_time(slo_observation_status{environment=\"gprd\", stage=~\"|main\", slo=\"apdex_ratio\"}[1w]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Error Rate SLO adherence over the past 7 days",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sort(avg_over_time(slo_observation_status{environment=\"gprd\", stage=~\"|main\", slo=\"error_ratio\"}[1w]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Apdex over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Timeseries: Overall GitLab.com Apdex SLO adherence",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.25, avg_over_time(slo_observation_status{environment=\"gprd\", slo=\"apdex_ratio\", stage=~\"|main\", type=~\"gitaly|web|api|git\"}[$__interval]))",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Timeseries: Apdex SLO adherence - per service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(slo_observation_status{environment=\"gprd\", slo=\"apdex_ratio\", stage=~\"|main\"}[$__interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Errors over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Timeseries: Overall GitLab.com Error SLO adherence",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.25, avg_over_time(slo_observation_status{environment=\"gprd\", slo=\"error_ratio\", stage=~\"|main\", type=~\"gitaly|web|api|git\"}[$__interval]))",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Timeseries: Error SLO adherence - per service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(slo_observation_status{environment=\"gprd\", slo=\"error_ratio\", stage=~\"|main\"}[$__interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}