{
 "title": "ext-pvs: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5867687745 at Fri Jan  5 10:59:54 UTC 2024",
 "tags": [
  "managed",
  "ext-pvs",
  "gitlab",
  "type:ext-pvs",
  "ext-pvs",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "ext-pvs Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}[$__interval])\n",
     "legendFormat": "ext-pvs apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}[$__interval])\n",
     "legendFormat": "ext-pvs apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ext-pvs Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "ext-pvs Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ext-pvs error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "ext-pvs error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"ext-pvs\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "ext-pvs Service | Errors"
    }
   ]
  },
  {
   "title": "ext-pvs Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}[$__interval])\n",
     "legendFormat": "ext-pvs RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "runway_ingress SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}[$__interval])\n",
     "legendFormat": "runway_ingress apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}[$__interval])\n",
     "legendFormat": "runway_ingress apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "runway_ingress SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "runway_ingress SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "runway_ingress error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "runway_ingress error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"runway_ingress\",monitor=\"global\",type=\"ext-pvs\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "runway_ingress SLI | Errors"
    }
   ]
  },
  {
   "title": "runway_ingress SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"}[$__interval])\n",
     "legendFormat": "runway_ingress RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"runway_ingress\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"ext-pvs\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "content": "### Description\n\nApplication load balancer serving ingress HTTP requests for the Runway service.\n\n\n\n### Observability Tools\n\n* [Google Cloud Run Console](https://console.cloud.google.com/run/detail/us-east1/ext-pvs/metrics?project=gitlab-runway-production)\n* [Stackdriver Logs: Cloud Run Access Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Eservice%5Fname%3D%22ext%2Dpvs%22%0Aresource%2Etype%3D%22cloud%5Frun%5Frevision%22;timeRange=PT30M?project=gitlab-runway-production)\n* [Stackdriver Logs: Cloud Run Access 5xx Logs](https://console.cloud.google.com/logs/query;query=httpRequest%2Estatus%3E%3D500%0Aresource%2Elabels%2Eservice%5Fname%3D%22ext%2Dpvs%22%0Aresource%2Etype%3D%22cloud%5Frun%5Frevision%22;timeRange=PT30M?project=gitlab-runway-production)\n* [📖 Kibana: PVS logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.mode,json.jsonPayload.validation_status,json.jsonPayload.project_id,json.jsonPayload.correation_id,json.jsonPayload.msg),filters:!((meta:(index:'4858f3a0-a312-11eb-966b-2361593353f9',key:json.resource.labels.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.resource.labels.project_id:(query:'gitlab-runway-production',type:phrase))))),index:'4858f3a0-a312-11eb-966b-2361593353f9')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: PVS failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.jsonPayload.mode,json.jsonPayload.validation_status,json.jsonPayload.project_id,json.jsonPayload.correation_id,json.jsonPayload.msg),filters:!((meta:(index:'4858f3a0-a312-11eb-966b-2361593353f9',key:json.resource.labels.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.resource.labels.project_id:(query:'gitlab-runway-production',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'4858f3a0-a312-11eb-966b-2361593353f9',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),index:'4858f3a0-a312-11eb-966b-2361593353f9')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: PVS requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=4858f3a0-a312-11eb-966b-2361593353f9&_a=(filters:!((meta:(index:'4858f3a0-a312-11eb-966b-2361593353f9',key:json.resource.labels.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.resource.labels.project_id:(query:'gitlab-runway-production',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.timestamp,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: PVS failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=4858f3a0-a312-11eb-966b-2361593353f9&_a=(filters:!((meta:(index:'4858f3a0-a312-11eb-966b-2361593353f9',key:json.resource.labels.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.resource.labels.project_id:(query:'gitlab-runway-production',type:phrase)))),(meta:(field:json.jsonPayload.status_code,index:'4858f3a0-a312-11eb-966b-2361593353f9',key:json.jsonPayload.status_code,params:(gte:500,lte:!n),type:range),query:(range:(json.jsonPayload.status_code:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.timestamp,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: PVS sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=4858f3a0-a312-11eb-966b-2361593353f9&_a=(filters:!((meta:(index:'4858f3a0-a312-11eb-966b-2361593353f9',key:json.resource.labels.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.resource.labels.project_id:(query:'gitlab-runway-production',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.timestamp,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: PVS sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=4858f3a0-a312-11eb-966b-2361593353f9&_a=(filters:!((meta:(index:'4858f3a0-a312-11eb-966b-2361593353f9',key:json.resource.labels.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.resource.labels.project_id:(query:'gitlab-runway-production',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.timestamp,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.validation_status.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.jsonPayload.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: PVS percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=4858f3a0-a312-11eb-966b-2361593353f9&_a=(filters:!((meta:(index:'4858f3a0-a312-11eb-966b-2361593353f9',key:json.resource.labels.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.resource.labels.project_id:(query:'gitlab-runway-production',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.timestamp,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: PVS percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=4858f3a0-a312-11eb-966b-2361593353f9&_a=(filters:!((meta:(index:'4858f3a0-a312-11eb-966b-2361593353f9',key:json.resource.labels.project_id,params:'gitlab-runway-production',type:phrase),query:(match:(json.resource.labels.project_id:(query:'gitlab-runway-production',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.jsonPayload.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.timestamp,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.jsonPayload.validation_status.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.jsonPayload.duration_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.jsonPayload.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "🔬 SLI Detail: runway_ingress",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 runway_ingress Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "ms", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "runway_ingress Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",response_code_class=\"5xx\",type=\"ext-pvs\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "runway_ingress RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 runway_ingress Latency - per revision_name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ms", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,revision_name) (\n    avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",revision_name!=\"\",type=\"ext-pvs\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{revision_name}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for runway_ingress Latency - per revision_name",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (revision_name) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",revision_name!=\"\",type=\"ext-pvs\"}[$__interval])\n)\n\n    -\n    (\n      sum by (revision_name) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"4052.650622296292\",revision_name!=\"\",type=\"ext-pvs\"}[$__interval])\n)\n\n    )\n  )\n  / ignoring(revision_name) group_left()\n  (\n    sum by () (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",revision_name!=\"\",type=\"ext-pvs\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{revision_name}}"
      }
     ]
    },
    {
     "title": "runway_ingress Errors - per revision_name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (revision_name) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",response_code_class=\"5xx\",revision_name!=\"\",type=\"ext-pvs\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "{{revision_name}}"
      }
     ]
    },
    {
     "title": "runway_ingress RPS - per revision_name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (revision_name) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",revision_name!=\"\",type=\"ext-pvs\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "{{revision_name}}"
      }
     ]
    },
    {
     "title": "Estimated p95 runway_ingress Latency - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,response_code) (\n    avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",response_code!=\"\",type=\"ext-pvs\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{response_code}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for runway_ingress Latency - per response_code",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (response_code) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",response_code!=\"\",type=\"ext-pvs\"}[$__interval])\n)\n\n    -\n    (\n      sum by (response_code) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"4052.650622296292\",response_code!=\"\",type=\"ext-pvs\"}[$__interval])\n)\n\n    )\n  )\n  / ignoring(response_code) group_left()\n  (\n    sum by () (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",response_code!=\"\",type=\"ext-pvs\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "runway_ingress Errors - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",response_code!=\"\",response_code_class=\"5xx\",type=\"ext-pvs\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "runway_ingress RPS - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  avg_over_time(stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",environment=\"$environment\",response_code!=\"\",type=\"ext-pvs\"}[$__interval]) / 60\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "runway_container_cpu_utilization component saturation: Runway Container CPU Utilization",
     "type": "graph",
     "description": "Container CPU utilization of the Runway service distributed across all container instances.\n\nFor scaling, refer to https://cloud.google.com/run/docs/configuring/services/cpu.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, type, shard, revision_name) (\n  clamp_min(\n    clamp_max(\n      histogram_quantile(0.9999, sum by(le, environment, type, shard, revision_name)\n        (\n          avg_over_time(\n            stackdriver_cloud_run_revision_run_googleapis_com_container_cpu_utilizations_bucket{job=\"runway-exporter\",env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\"}[30m]\n          )\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ revision_name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_cpu_utilization\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_cpu_utilization\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_cpu_utilization\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"runway_container_cpu_utilization\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"runway_container_cpu_utilization\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "runway_container_instance_utilization component saturation: Runway Container Instance Utilization",
     "type": "graph",
     "description": "Container instance utilization of the Runway service.\n\nFor scaling, refer to https://cloud.google.com/run/docs/configuring/max-instances.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, type, shard, revision_name) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, type, shard, revision_name) (\n        stackdriver_cloud_run_revision_run_googleapis_com_container_instance_count{job=\"runway-exporter\",state=\"active\",env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\"}\n      )\n      /\n      100\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ revision_name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_instance_utilization\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_instance_utilization\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_instance_utilization\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"runway_container_instance_utilization\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"runway_container_instance_utilization\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "runway_container_max_concurrent_requests component saturation: Runway Max Concurrent Requests",
     "type": "graph",
     "description": "Max number of concurrent requests being served by each container instance of the Runway service.\n\nFor scaling, refer to https://cloud.google.com/run/docs/configuring/concurrency.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, type, shard, revision_name) (\n  clamp_min(\n    clamp_max(\n      histogram_quantile(0.9999, sum by(le, environment, type, shard, revision_name)\n        (\n          rate(\n            stackdriver_cloud_run_revision_run_googleapis_com_container_max_request_concurrencies_bucket{job=\"runway-exporter\",state=\"active\",env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\"}[30m]\n          )\n        )\n      ) / 100\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ revision_name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_max_concurrent_requests\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_max_concurrent_requests\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_max_concurrent_requests\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"runway_container_max_concurrent_requests\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"runway_container_max_concurrent_requests\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "runway_container_memory_utilization component saturation: Runway Container Memory Utilization",
     "type": "graph",
     "description": "Container memory utilization of the Runway service distributed across all container instances.\n\nFor scaling, refer to https://cloud.google.com/run/docs/configuring/services/memory-limits.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, type, shard, revision_name) (\n  clamp_min(\n    clamp_max(\n      histogram_quantile(0.9999, sum by(le, environment, type, shard, revision_name)\n        (\n          avg_over_time(\n            stackdriver_cloud_run_revision_run_googleapis_com_container_memory_utilizations_bucket{job=\"runway-exporter\",env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\"}[30m]\n          )\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ revision_name }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_memory_utilization\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_memory_utilization\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"ext-pvs\", component=\"runway_container_memory_utilization\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"runway_container_memory_utilization\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"runway_container_memory_utilization\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph sv\n  ext-pvs\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph sv\n  ext-pvs\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph sv\n  ext-pvs[\"ext-pvs (Level 2)\"]\nend\n\n\n  \n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}