{
 "title": "[draft] vulnerability_occurrence_pipelines deprecation",
 "description": "We are going to drop the vulnerability_occurrence_pipelines. First we need to migrate all application activity off of it. This dashboard helps monitor the situation",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Staging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read Operations",
   "type": "timeseries",
   "description": "Index scans and sequential table scans of the vulnerability_occurrence_pipelines table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (indexrelname, env) (rate(pg_stat_user_indexes_idx_scan{relname=\"vulnerability_occurrence_pipelines\", env=\"gstg\"}[1h]))",
     "legendFormat": "Index Scans - {{indexrelname}}"
    },
    {
     "expr": "sum by (instance) (rate(pg_stat_user_tables_seq_scan{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"}[1h]))",
     "legendFormat": "Sequential Scans ({{instance}})"
    }
   ]
  },
  {
   "title": "Read Operations (findings)",
   "type": "timeseries",
   "description": "Index scans and sequential table scans of the vulnerability_occurrences table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (indexrelname, env) (rate(pg_stat_user_indexes_idx_scan{relname=\"vulnerability_occurrences\", env=\"gstg\"}[1h]))",
     "legendFormat": "Index Scans - {{indexrelname}}"
    },
    {
     "expr": "sum by (instance) (rate(pg_stat_user_tables_seq_scan{relname=\"vulnerability_occurrences\", env=\"gstg\"}[1h]))",
     "legendFormat": "Sequential Scans ({{instance}})"
    }
   ]
  },
  {
   "title": "Write Oprations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(type) (rate(pg_stat_user_tables_n_tup_ins{relname=\"vulnerability_occurrence_pipelines\", env=\"gstg\"}[1h]))",
     "legendFormat": "Inserts - ({{type}})"
    },
    {
     "expr": "sum by (type) (rate(pg_stat_user_tables_n_tup_upd{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"}[1h]))",
     "legendFormat": "Updates - {{type}}"
    },
    {
     "expr": "sum by (type) (rate(pg_stat_user_tables_n_tup_del{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"}[1h]))\n",
     "legendFormat": "Deletes - {{type}}"
    }
   ]
  },
  {
   "title": "Write Oprations (Findings)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(type) (rate(pg_stat_user_tables_n_tup_ins{relname=\"vulnerability_occurrences\", env=\"gstg\"}[1h]))",
     "legendFormat": "Inserts - ({{type}})"
    },
    {
     "expr": "sum by (type) (rate(pg_stat_user_tables_n_tup_upd{relname=\"vulnerability_occurrences\", env=\"gprd\"}[1h]))",
     "legendFormat": "Updates - {{type}}"
    },
    {
     "expr": "sum by (type) (rate(pg_stat_user_tables_n_tup_del{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"}[1h]))\n",
     "legendFormat": "Deletes - {{type}}"
    }
   ]
  },
  {
   "title": "Table Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (type) (pg_stat_user_tables_n_live_tup{relname=\"vulnerability_occurrence_pipelines\", env=\"gstg\"})",
     "legendFormat": "Live Rows - {{type}}"
    },
    {
     "expr": "sum by (type) (pg_stat_user_tables_n_dead_tup{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"})\n",
     "legendFormat": "Dead Rows - {{type}}"
    },
    {
     "expr": "sum by (instance) (pg_total_relation_size{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"})\n",
     "legendFormat": "Total Size - "
    }
   ]
  },
  {
   "title": "Table Statistics (Findings)",
   "type": "timeseries",
   "description": "We will be reading from this table in place of the *_pipelines table, so should see an increase",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (type) (pg_stat_user_tables_n_live_tup{relname=\"vulnerability_occurrences\", env=\"gstg\"})",
     "legendFormat": "Live Rows - {{type}}"
    },
    {
     "expr": "sum by (type) (pg_stat_user_tables_n_dead_tup{relname=\"vulnerability_occurrences\", env=\"gprd\"})\n",
     "legendFormat": "Dead Rows - {{type}}"
    },
    {
     "expr": "sum by (instance) (pg_total_relation_size{relname=\"vulnerability_occurrences\", env=\"gprd\"})\n",
     "legendFormat": "Total Size - "
    }
   ]
  },
  {
   "title": "Production",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table Statistics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum by (type) (pg_stat_user_tables_n_live_tup{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"})",
       "legendFormat": "Live Rows - {{type}}"
      },
      {
       "expr": "sum by (type) (pg_stat_user_tables_n_dead_tup{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"})\n",
       "legendFormat": "Dead Rows - {{type}}"
      },
      {
       "expr": "sum by (instance) (pg_total_relation_size{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"})\n",
       "legendFormat": "Total Size - "
      }
     ]
    },
    {
     "title": "Table Statistics (Findings)",
     "type": "timeseries",
     "description": "We will be reading from this table in place of the *_pipelines table, so should see an increase",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sum by (type) (pg_stat_user_tables_n_live_tup{relname=\"vulnerability_occurrences\", env=\"gprd\"})",
       "legendFormat": "Live Rows - {{type}}"
      },
      {
       "expr": "sum by (type) (pg_stat_user_tables_n_dead_tup{relname=\"vulnerability_occurrences\", env=\"gprd\"})\n",
       "legendFormat": "Dead Rows - {{type}}"
      },
      {
       "expr": "sum by (instance) (pg_total_relation_size{relname=\"vulnerability_occurrences\", env=\"gprd\"})\n",
       "legendFormat": "Total Size - "
      }
     ]
    },
    {
     "title": "Write Oprations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum by(type) (rate(pg_stat_user_tables_n_tup_ins{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"}[1h]))",
       "legendFormat": "Inserts - ({{type}})"
      },
      {
       "expr": "sum by (type) (rate(pg_stat_user_tables_n_tup_upd{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"}[1h]))",
       "legendFormat": "Updates - {{type}}"
      },
      {
       "expr": "sum by (type) (rate(pg_stat_user_tables_n_tup_del{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"}[1h]))\n",
       "legendFormat": "Deletes - {{type}}"
      }
     ]
    },
    {
     "title": "Write Oprations (Findings)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum by(type) (rate(pg_stat_user_tables_n_tup_ins{relname=\"vulnerability_occurrences\", env=\"gprd\"}[1h]))",
       "legendFormat": "Inserts - ({{type}})"
      },
      {
       "expr": "sum by (type) (rate(pg_stat_user_tables_n_tup_upd{relname=\"vulnerability_occurrences\", env=\"gprd\"}[1h]))",
       "legendFormat": "Updates - {{type}}"
      },
      {
       "expr": "sum by (type) (rate(pg_stat_user_tables_n_tup_del{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"}[1h]))\n",
       "legendFormat": "Deletes - {{type}}"
      }
     ]
    },
    {
     "title": "Read Operations",
     "type": "timeseries",
     "description": "Index scans and sequential table scans of the vulnerability_occurrence_pipelines table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "sum by (indexrelname, env) (rate(pg_stat_user_indexes_idx_scan{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"}[1h]))",
       "legendFormat": "Index Scans - {{indexrelname}}"
      },
      {
       "expr": "sum by (instance) (rate(pg_stat_user_tables_seq_scan{relname=\"vulnerability_occurrence_pipelines\", env=\"gprd\"}[1h]))",
       "legendFormat": "Sequential Scans ({{instance}})"
      }
     ]
    },
    {
     "title": "Read Operations (findings)",
     "type": "timeseries",
     "description": "Index scans and sequential table scans of the vulnerability_occurrences table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "sum by (indexrelname, env) (rate(pg_stat_user_indexes_idx_scan{relname=\"vulnerability_occurrences\", env=\"gprd\"}[1h]))",
       "legendFormat": "Index Scans - {{indexrelname}}"
      },
      {
       "expr": "sum by (instance) (rate(pg_stat_user_tables_seq_scan{relname=\"vulnerability_occurrences\", env=\"gprd\"}[1h]))",
       "legendFormat": "Sequential Scans ({{instance}})"
      }
     ]
    }
   ]
  }
 ]
}