{
 "title": "frontend: ci-gateway Git utilisation based on HaProxy",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4508278641 at Tue Jun 20 18:15:24 UTC 2023",
 "tags": [
  "managed",
  "frontend",
  "managed",
  "type:frontend"
 ],
 "time": { "from": "now-24h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(haproxy_frontend_bytes_in_total{frontend=\"https\"}, env)\n"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTPs Git traffic as a percentage of main HTTPs frontend traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_frontend_bytes_out_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "egress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_frontend_bytes_out_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "HTTPs CI Gateway traffic as a percentage of all Git HTTPs backend traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_frontend_bytes_out_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "egress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_out_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n/\nsum by(env) (\n  rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "HTTPs traffic - based on the main HTTPs HaProxy frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_frontend_bytes_out_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "egress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_out_total{frontend=\"https\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "HTTPs Git traffic - based on the HaProxy backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_in_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "egress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_backend_bytes_out_total{backend=~\".*https_git\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "HTTPs CI Gateway traffic - based on the dedicated HaProxy frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval]) + rate(haproxy_frontend_bytes_out_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_in_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "egress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by(env) (\n  rate(haproxy_frontend_bytes_out_total{frontend=\"https_git_ci_gateway\",env=~\"${environment}\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}