{
 "title": "GCP Failover - GCP",
 "description": "Dashboard useful when doing the failover to GCP",
 "tags": [ "gcp-migration" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "app_prometheus", "query": "prometheus" },
   {
    "name": "azure_environment",
    "query": "label_values(up{environment=\"$environment\"}, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Geo repository verification",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(geo_repositories_verified{environment=\"$environment\"}) by (geo_role)",
     "legendFormat": "Verified ({{ geo_role }})"
    },
    {
     "expr": "min(geo_repositories_verification_failed{environment=\"$environment\"} - geo_repositories_checksum_mismatch{environment=\"$environment\"}) by (geo_role)",
     "legendFormat": "Failed ({{ geo_role }})"
    },
    {
     "expr": "min(geo_repositories{environment=\"$environment\"} - geo_repositories_verified{environment=\"$environment\"} - geo_repositories_verification_failed{environment=\"$environment\"}) by (geo_role)",
     "legendFormat": "Unverified ({{ geo_role }})"
    }
   ]
  },
  {
   "title": "Repo checksum mismatch",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(geo_repositories_checksum_mismatch) by (environment)"
    }
   ]
  },
  {
   "title": "Geo wiki verification",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(geo_wikis_verified{environment=\"$environment\"}) by (geo_role)",
     "legendFormat": "Verified ({{ geo_role }})"
    },
    {
     "expr": "min(geo_wikis_verification_failed{environment=\"$environment\"} - geo_wikis_checksum_mismatch{environment=\"$environment\"}) by (geo_role)",
     "legendFormat": "Failed ({{ geo_role }})"
    },
    {
     "expr": "min(geo_wikis{environment=\"$environment\"} - geo_wikis_verified{environment=\"$environment\"} - geo_wikis_verification_failed{environment=\"$environment\"}) by (geo_role)",
     "legendFormat": "Unverified ({{ geo_role }})"
    }
   ]
  },
  {
   "title": "Wiki checksum mismatch",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(geo_wikis_checksum_mismatch) by (environment)"
    }
   ]
  },
  {
   "title": "Redis Master Link",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(redis_master_link_up{environment=\"$environment\",instance!~\".*cache.*\"})"
    }
   ]
  },
  {
   "title": "Redis Cache Master Link",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(redis_master_link_up{environment=\"$environment\", instance=~\".*cache.*\"})"
    }
   ]
  },
  { "title": "Placeholder", "type": "text", "gridPos": { "h": 5, "w": 16, "x": 8, "y": 12 } },
  {
   "title": "Sidekiq Geo queue sizes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_queue_size{environment=\"$environment\",name=~\".*geo.*\"}) by (name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ name }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sidekiq running Geo jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_running_jobs_count{environment=\"$environment\",name=~\".*[Gg]eo.*\"}) by (name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ name }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sidekiq non-Geo queue sizes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_queue_size{environment=\"$environment\",name!~\".*geo.*\"}) by (name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ name }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sidekiq running non-Geo jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_running_jobs_count{environment=\"$environment\",name!~\".*[Gg]eo.*\"}) by (name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ name }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rails requests per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "type:rails_requests_started:rate1m{environment=\"$environment\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}} ({{geo_role}})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL replication delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_replication_lag{environment=\"$environment\", tier=\"db\", type=\"postgres\"} and pg_replication_is_replica==1",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  }
 ]
}