{
 "title": "GCP Migration Status",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Repos Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(avg(geo_repositories_failed{environment=\"gprd\"}))"
    }
   ]
  },
  {
   "title": "Repos Synced",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(geo_repositories_synced{environment=\"gprd\"})"
    }
   ]
  },
  {
   "title": "Repos Synced",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "floor(avg(geo_repositories_verified{environment=\"gprd\"}))\n"
    }
   ]
  },
  {
   "title": "Attachments Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(avg(geo_attachments_failed{environment=\"gprd\"}))"
    }
   ]
  },
  {
   "title": "Attachment Synced",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(geo_attachments{environment=\"gprd\"})"
    }
   ]
  },
  {
   "title": "Wikis Failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(geo_wikis_failed{environment=\"gprd\"})"
    }
   ]
  },
  {
   "title": "Attachment Synced",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(geo_wikis_synced{environment=\"gprd\"})"
    }
   ]
  },
  {
   "title": "Geo DB Replication Lag",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(geo_db_replication_lag_seconds)"
    }
   ]
  }
 ]
}