{
 "title": "General Service Component Metrics",
 "tags": [ "general" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "environment", "query": "label_values(up, environment)" },
   {
    "name": "type",
    "query": "label_values(gitlab_component_ops:rate{environment=\"$environment\"}, type)"
   },
   { "name": "sigma", "query": "0.5,1,1.5,2,2.5,3" }
  ]
 },
 "panels": [
  {
   "title": "Service Component Availability",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability %" }
   ],
   "targets": [
    {
     "expr": "\n      min(\n        min_over_time(\n          gitlab_component_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]\n        )\n      ) by (tier, type, component)\n      ",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "Service Component Operation Rates",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "\n      sum(\n        avg_over_time(\n          gitlab_component_ops:rate{environment=\"$environment\", type=\"$type\"}[$__interval]\n        )\n      ) by (component)\n      ",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "Service Component Apdex",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "\n      avg(\n        avg_over_time(\n          gitlab_component_apdex:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]\n        )\n      ) by (component)\n      ",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "Service Component Error Rates",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Errors per Minute" }
   ],
   "targets": [
    {
     "expr": "\n      sum(\n        avg_over_time(\n          gitlab_component_errors:rate{component=\"\", service=\"\", environment=\"$environment\", type=\"$type\"}[$__interval]\n        )\n      ) by (component) * 60\n      ",
     "legendFormat": "{{ component }} component"
    }
   ]
  }
 ]
}