{
 "title": "general: Filesystems",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7412578973 at Wed Jul 24 01:10:13 UTC 2024",
 "tags": [
  "managed",
  "general",
  "general"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "type",
    "query": "label_values(gitlab_service_ops:rate_1h{environment=\"$environment\"}, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Filesystem Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "min by (device) (node_filesystem_size_bytes{device=~\"/dev/.+\", env=\"$environment\", type=\"$type\", mountpoint!=\"/\", mountpoint!=\"/var/log\"})\n",
     "legendFormat": "Limit ({{device}})"
    },
    {
     "expr": "node_filesystem_size_bytes{device=~\"/dev/.+\", env=\"$environment\", type=\"$type\", mountpoint!=\"/\", mountpoint!=\"/var/log\"}\n-\nnode_filesystem_free_bytes{device=~\"/dev/.+\", env=\"$environment\", type=\"$type\", mountpoint!=\"/\", mountpoint!=\"/var/log\"}\n",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Total Filesystem Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "sum by (device) (node_filesystem_size_bytes{device=~\"/dev/.+\", env=\"$environment\", type=\"$type\", mountpoint!=\"/\", mountpoint!=\"/var/log\"})\n",
     "legendFormat": "Limit ({{device}})"
    },
    {
     "expr": "sum by (device)\n(\n  node_filesystem_size_bytes{device=~\"/dev/.+\", env=\"$environment\", type=\"$type\", mountpoint!=\"/\", mountpoint!=\"/var/log\"}\n  -\n  node_filesystem_free_bytes{device=~\"/dev/.+\", env=\"$environment\", type=\"$type\", mountpoint!=\"/\", mountpoint!=\"/var/log\"}\n)\n",
     "legendFormat": "All Instances ({{device}})"
    }
   ]
  },
  {
   "title": "Filesystem Utilization (ZFS)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "min\n(\n  node_filesystem_size_bytes{device=\"tank/reservation\", env=\"$environment\", type=\"$type\"}\n  + ignoring (device, mountpoint)\n  (\n    node_filesystem_size_bytes{device=\"tank/dataset\", env=\"$environment\", type=\"$type\"}\n    -\n    node_filesystem_free_bytes{device=\"tank/dataset\", env=\"$environment\", type=\"$type\"}\n  )\n)\n",
     "legendFormat": "Absolute Limit"
    },
    {
     "expr": "min (node_filesystem_size_bytes{device=\"tank/dataset\", env=\"$environment\", type=\"$type\"})\n",
     "legendFormat": "Limit excluding reservation"
    },
    {
     "expr": "node_filesystem_size_bytes{device=\"tank/dataset\", env=\"$environment\", type=\"$type\"}\n-\nnode_filesystem_free_bytes{device=\"tank/dataset\", env=\"$environment\", type=\"$type\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Filesystem Utilization (ZFS)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "sum\n(\n  node_filesystem_size_bytes{device=\"tank/reservation\", env=\"$environment\", type=\"$type\"}\n  + ignoring (device, mountpoint)\n  (\n    node_filesystem_size_bytes{device=\"tank/dataset\", env=\"$environment\", type=\"$type\"}\n    -\n    node_filesystem_free_bytes{device=\"tank/dataset\", env=\"$environment\", type=\"$type\"}\n  )\n)\n",
     "legendFormat": "Absolute Limit"
    },
    {
     "expr": "sum (node_filesystem_size_bytes{device=\"tank/dataset\", env=\"$environment\", type=\"$type\"})\n",
     "legendFormat": "Limit excluding reservation"
    },
    {
     "expr": "sum\n(\n  node_filesystem_size_bytes{device=\"tank/dataset\", env=\"$environment\", type=\"$type\"}\n  -\n  node_filesystem_free_bytes{device=\"tank/dataset\", env=\"$environment\", type=\"$type\"}\n)\n",
     "legendFormat": "All Instances"
    }
   ]
  },
  {
   "title": "ZFS ARC Hit Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit", "label": "ZFS ARC Hit Rate" }
   ],
   "targets": [
    {
     "expr": "node_zfs_arc_hits{env=\"$environment\", type=\"$type\"}\n/\n(node_zfs_arc_hits{env=\"$environment\", type=\"$type\"} + node_zfs_arc_misses{env=\"$environment\", type=\"$type\"})\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZFS ARC Demand Hit Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit", "label": "ZFS ARC Demand Hit Rate" }
   ],
   "targets": [
    {
     "expr": "(node_zfs_arc_demand_data_hits{env=\"$environment\", type=\"$type\"} + node_zfs_arc_demand_metadata_hits{env=\"$environment\", type=\"$type\"})\n/\n(\n  node_zfs_arc_demand_data_hits{env=\"$environment\", type=\"$type\"} + node_zfs_arc_demand_metadata_hits{env=\"$environment\", type=\"$type\"}\n  + node_zfs_arc_demand_data_misses{env=\"$environment\", type=\"$type\"} + node_zfs_arc_demand_metadata_misses{env=\"$environment\", type=\"$type\"}\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}