{
 "title": "general: ZFS",
 "tags": [
  "managed",
  "general"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "type",
    "query": "label_values(gitlab_service_ops:rate{environment=\"$environment\"}, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Filesystem Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "\n      min by (instance) (node_filesystem_size_bytes{device=\"tank/reservation\", env=\"$environment\", type = \"$type\"})\n    ",
     "legendFormat": "Absolute Limit"
    },
    {
     "expr": "\n      min by (instance) (node_filesystem_size_bytes{device=\"tank/dataset\", env=\"$environment\", type = \"$type\"})\n    ",
     "legendFormat": "Limit excluding reservation"
    },
    {
     "expr": "\n      node_filesystem_size_bytes{device=\"tank/dataset\", env=\"$environment\", type = \"$type\"}\n      -\n      node_filesystem_free_bytes{device=\"tank/dataset\", env=\"$environment\", type = \"$type\"}\n    ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Filesystem Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "\n      sum by (instance) (node_filesystem_size_bytes{device=\"tank/reservation\", env=\"$environment\", type = \"$type\"})\n    ",
     "legendFormat": "Absolute Limit"
    },
    {
     "expr": "\n      sum by (instance) (node_filesystem_size_bytes{device=\"tank/dataset\", env=\"$environment\", type = \"$type\"})\n    ",
     "legendFormat": "Limit excluding reservation"
    },
    {
     "expr": "\n      sum by (instance)\n      (\n        node_filesystem_size_bytes{device=\"tank/dataset\", env=\"$environment\", type = \"$type\"}\n        -\n        node_filesystem_free_bytes{device=\"tank/dataset\", env=\"$environment\", type = \"$type\"}\n      )\n    ",
     "legendFormat": "All Instances"
    }
   ]
  },
  {
   "title": "ARC Hit Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "ARC Hit Rate" }
   ],
   "targets": [
    {
     "expr": "\n      node_zfs_arc_hits{env=\"$environment\", type=\"$type\"}\n      /\n      (node_zfs_arc_hits{env=\"$environment\", type=\"$type\"} + node_zfs_arc_misses{env=\"$environment\", type=\"$type\"})\n    ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ARC Demand Hit Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "ARC Demand Hit Rate" }
   ],
   "targets": [
    {
     "expr": "\n      (node_zfs_arc_demand_data_hits{env=\"$environment\", type=\"$type\"} + node_zfs_arc_demand_metadata_hits{env=\"$environment\", type=\"$type\"})\n      /\n      (\n        node_zfs_arc_demand_data_hits{env=\"$environment\", type=\"$type\"} + node_zfs_arc_demand_metadata_hits{env=\"$environment\", type=\"$type\"}\n        + node_zfs_arc_demand_data_misses{env=\"$environment\", type=\"$type\"} + node_zfs_arc_demand_metadata_misses{env=\"$environment\", type=\"$type\"}\n      )\n    ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}