{
 "title": "general: Rails Endpoints Traffic Share",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4304835135 at Wed May 17 19:03:34 UTC 2023",
 "tags": [
  "managed",
  "general"
 ],
 "time": { "from": "now-2d/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "product_stage",
    "query": "label_values(gitlab:feature_category:stage_group:mapping{monitor=\"global\"}, product_stage)"
   },
   {
    "name": "stage_group",
    "query": "label_values(gitlab:feature_category:stage_group:mapping{monitor=\"global\", product_stage=~\"$product_stage\"}, stage_group)"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic by urgency (over the last 6h)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "high urgency requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (request_urgency) (\n    sum by (request_urgency, feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"high\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n  / ignoring(request_urgency) group_left() sum(\n    sum by (feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n)\n",
     "legendFormat": "{{ urgency }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (endpoint_id, feature_category) (\n    count_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"high\",stage=\"$stage\"}[6h]) > 0\n  ) * on (feature_category) group_left() group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
    }
   ]
  },
  {
   "title": "medium urgency requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (request_urgency) (\n    sum by (request_urgency, feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"medium\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n  / ignoring(request_urgency) group_left() sum(\n    sum by (feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n)\n",
     "legendFormat": "{{ urgency }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (endpoint_id, feature_category) (\n    count_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"medium\",stage=\"$stage\"}[6h]) > 0\n  ) * on (feature_category) group_left() group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
    }
   ]
  },
  {
   "title": "default urgency requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (request_urgency) (\n    sum by (request_urgency, feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"default\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n  / ignoring(request_urgency) group_left() sum(\n    sum by (feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n)\n",
     "legendFormat": "{{ urgency }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (endpoint_id, feature_category) (\n    count_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"default\",stage=\"$stage\"}[6h]) > 0\n  ) * on (feature_category) group_left() group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
    }
   ]
  },
  {
   "title": "low urgency requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (request_urgency) (\n    sum by (request_urgency, feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"low\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n  / ignoring(request_urgency) group_left() sum(\n    sum by (feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n)\n",
     "legendFormat": "{{ urgency }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (endpoint_id, feature_category) (\n    count_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"low\",stage=\"$stage\"}[6h]) > 0\n  ) * on (feature_category) group_left() group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
    }
   ]
  },
  {
   "title": "Endpoints by urgency (over the last 6h)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "high urgency endpoints ordered by request rate",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "sort_desc(\n  sum by (feature_category, endpoint_id)(\n    sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"high\",stage=\"$stage\"}[6h])\n  ) * on (feature_category) group_left(stage_group, product_stage) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
      }
     ]
    },
    {
     "title": "medium urgency endpoints ordered by request rate",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 101 },
     "targets": [
      {
       "expr": "sort_desc(\n  sum by (feature_category, endpoint_id)(\n    sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"medium\",stage=\"$stage\"}[6h])\n  ) * on (feature_category) group_left(stage_group, product_stage) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
      }
     ]
    },
    {
     "title": "default urgency endpoints ordered by request rate",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 101 },
     "targets": [
      {
       "expr": "sort_desc(\n  sum by (feature_category, endpoint_id)(\n    sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"default\",stage=\"$stage\"}[6h])\n  ) * on (feature_category) group_left(stage_group, product_stage) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
      }
     ]
    },
    {
     "title": "low urgency endpoints ordered by request rate",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 101 },
     "targets": [
      {
       "expr": "sort_desc(\n  sum by (feature_category, endpoint_id)(\n    sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"low\",stage=\"$stage\"}[6h])\n  ) * on (feature_category) group_left(stage_group, product_stage) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Endpoints by traffic %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true,
   "panels": [
    {
     "title": "Endpoints by traffic %",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 401 },
     "targets": [
      {
       "expr": "sort_desc(\n  sum by(endpoint_id, request_urgency, feature_category, env) (\n    sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range]) > 0\n  )\n  / ignoring(endpoint_id, feature_category, request_urgency) group_left\n  sum by(env) (\n    sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range]) > 0\n  )\n) * on(feature_category) group_left(stage_group, product_stage)\nsum by(feature_category, stage_group, product_stage) (\n  gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}\n)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}