{
 "title": "general: Camoproxy",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/369426163 at Wed Dec  4 15:46:35 UTC 2019",
 "tags": [
  "managed",
  "general",
  "general"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(up{job=\"camoproxy\"}, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "description": "Requests per second",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(camo_responses_total{environment=\"$environment\"}[$__interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "description": "Traffic, in bytes per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(camo_response_size_bytes_sum{environment=\"$environment\"}[$__interval]))",
     "legendFormat": "Bytes/s"
    }
   ]
  },
  {
   "title": "Request Failures",
   "type": "graph",
   "description": "Failed requests",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Events/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(camo_proxy_reponses_failed_total{environment=\"$environment\"}[$__interval]))",
     "legendFormat": "Failed Responses"
    },
    {
     "expr": "sum(rate(camo_proxy_content_length_exceeded_total{environment=\"$environment\"}[$__interval]))",
     "legendFormat": "Content Length Exceeded - --max-size exceeded"
    },
    {
     "expr": "sum(rate(camo_proxy_reponses_truncated_total{environment=\"$environment\"}[$__interval]))",
     "legendFormat": "Response Truncated - --max-size exceeded"
    },
    {
     "expr": "sum(rate(camo_responses_total{environment=\"$environment\",code=\"504\"}[$__interval]))",
     "legendFormat": "504 - Gateway Timeout - maybe --timeout exceeded"
    }
   ]
  }
 ]
}