{
 "title": "general: Feature Category Detail - Error Budgets",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4737822408 at Tue Jul 25 15:40:04 UTC 2023",
 "tags": [
  "managed",
  "general",
  "feature_category"
 ],
 "time": { "from": "now-7d", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  { "title": "Sidekiq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Apdex by Feature Category Help",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "content": "This table shows the apdex scores for each Sidekiq worker in the application, aggregated up\nto the feature category level.\n\nTo help understand what this metric means, you can think of it as the percentage of jobs\nfor each feature category that meet their execution SLO.\n\nCurrently we have 3 levels of `urgency` for Sidekiq jobs. High, low and throttled. Each\nlevel has an maximum execution time. The apdex score is effectively the number of jobs\nin each category that meet their execution latency SLO.\n"
  },
  {
   "title": "Error Rate by Feature Category Help",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "content": "This table shows the error ratios for each Sidekiq worker in the application, aggregated up\nto the feature category level.\n\nThis is a percentage of jobs in each feature category that complete successfully.\n"
  },
  {
   "title": "Apdex by Feature Category",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sort_desc(\n  clamp_max(\n    sum by (feature_category) (\n      avg_over_time(gitlab_background_jobs:execution:apdex:ratio_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      *\n      avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n    )\n    /\n      (\n      sum by(feature_category) (\n        avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      )\n    ) > 0,\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Error Rate by Feature Category",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "sort(\n  clamp_max(\n    sum by (feature_category) (\n      avg_over_time(gitlab_background_jobs:execution:error:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n    )\n    /\n      (\n      sum by(feature_category) (\n        avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      ) > 0\n    ),\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Apdex by Queue Help",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 200 },
   "content": "This table shows the apdex scores for each Sidekiq worker in the application.\n\nThe apdex score measures the percentage of jobs that complete within their\nexecution latency SLO.\n\nTo find out what the execution latency SLO for a job is, click through the table\nto the Sidekiq Queue Detail dashboard.\n"
  },
  {
   "title": "Error Rate by Queue Help",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 200 },
   "content": "This table shows the error ratios for each Sidekiq worker in the application.\n\nThis is a percentage of jobs for each worker that complete successfully.\n"
  },
  {
   "title": "Apdex by Queue",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 300 },
   "targets": [
    {
     "expr": "sort_desc(\n  clamp_max(\n    sum by (queue, feature_category) (\n      avg_over_time(gitlab_background_jobs:execution:apdex:ratio_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      *\n      avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n    )\n    /\n      (\n      sum by(queue, feature_category) (\n        avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      )\n    ) > 0,\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Error Rate by Queue",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 300 },
   "targets": [
    {
     "expr": "sort(\n  clamp_max(\n    sum by (queue, feature_category) (\n      avg_over_time(gitlab_background_jobs:execution:error:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n    )\n    /\n    (\n      sum by(queue, feature_category) (\n        avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      )\n    ) > 0,\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Error Budget Queue Attribution Help",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 400 },
   "content": "This charts shows how much each queue contributed to the total degradation of availability\nof the Sidekiq service, over the range for this dashboard. This takes into account\npercentage of time that it missed its queueing latency SLO, percentage of time that it\nmissed its execution latency SLO, and error rates.\n\nThe ratio is measured as a fraction of the entire service, not on a per-queue basis.\n"
  },
  {
   "title": "Error Budget Queue Attribution",
   "type": "graph",
   "description": "Total queue contribution to error budget",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 500 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(8,\n  sum without(attribution) (\n    label_replace(\n      (1 - avg_over_time(gitlab_background_jobs:execution:apdex:ratio_6h{environment=\"$environment\", env=\"$environment\"}[$__range]))\n      *\n      avg_over_time(gitlab_background_jobs:execution:apdex:weight:score_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      / on() group_left()\n      sum(avg_over_time(gitlab_background_jobs:execution:apdex:weight:score_6h{environment=\"$environment\", env=\"$environment\"}[$__range])),\n      \"attribution\", \"execution\", \"\", \"\"\n    )\n    or\n    label_replace(\n      (1 - avg_over_time(gitlab_background_jobs:queue:apdex:ratio_6h{environment=\"$environment\", env=\"$environment\"}[$__range]))\n      *\n      avg_over_time(gitlab_background_jobs:queue:apdex:weight:score_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      / on() group_left()\n      sum(avg_over_time(gitlab_background_jobs:queue:apdex:weight:score_6h{environment=\"$environment\", env=\"$environment\"}[$__range])),\n      \"attribution\", \"queue\", \"\", \"\"\n    )\n    or\n    label_replace(\n      avg_over_time(gitlab_background_jobs:execution:error:rate_6h[$__range])\n      / on() group_left()\n      sum(avg_over_time(gitlab_background_jobs:execution:ops:rate_6h[$__range]))\n      ,\"attribution\", \"errors\", \"\", \"\"\n    )\n  )\n)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 600 } },
  {
   "title": "Error Rate by Feature Category Help",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 600 },
   "content": "This table shows the error ratios for all endpoints on the API service, aggregated up to the feature category level.\n\nThis is a percentage of requests in each feature category that fail.\n"
  },
  {
   "title": "Error Rate by Feature Category",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 700 },
   "targets": [
    {
     "expr": "sort(clamp_max(\n  sum by (feature_category) (\n    avg_over_time(gitlab:component:feature_category:execution:error:ratio_6h{environment=\"$environment\", env=\"$environment\", component=\"rails_request\", type=\"api\"}[$__range])\n  ), 1\n))\n"
    }
   ]
  },
  { "title": "Git", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 900 } },
  {
   "title": "Error Rate by Feature Category Help",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 900 },
   "content": "This table shows the error ratios for all endpoints on the Git service, aggregated up to the feature category level.\n\nThis is a percentage of requests in each feature category that fail.\n"
  },
  {
   "title": "Error Rate by Feature Category",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1000 },
   "targets": [
    {
     "expr": "sort(clamp_max(\n  sum by (feature_category) (\n    avg_over_time(gitlab:component:feature_category:execution:error:ratio_6h{environment=\"$environment\", env=\"$environment\", component=\"rails_request\", type=\"git\"}[$__range])\n  ), 1\n))\n"
    }
   ]
  },
  { "title": "Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1200 } },
  {
   "title": "Error Rate by Feature Category Help",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1200 },
   "content": "This table shows the error ratios for all endpoints on the Web service, aggregated up to the feature category level.\n\nThis is a percentage of requests in each feature category that fail.\n"
  },
  {
   "title": "Error Rate by Feature Category",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1300 },
   "targets": [
    {
     "expr": "sort(clamp_max(\n  sum by (feature_category) (\n    avg_over_time(gitlab:component:feature_category:execution:error:ratio_6h{environment=\"$environment\", env=\"$environment\", component=\"rails_request\", type=\"web\"}[$__range])\n  ), 1\n))\n"
    }
   ]
  }
 ]
}