{
 "title": "general: Network Ingress/Egress Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5101305806 at Fri Sep 15 16:44:04 UTC 2023",
 "tags": [
  "managed",
  "general",
  "general"
 ],
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Explainer",
   "type": "text",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 1 },
   "content": "### What is this?\n\nAmount of ingress / egress traffic **per day**, for nodes (Virtual Machines) and HAProxy Backends\n\n* HAProxy Nodes: Ingress/Egress bytes from the VMs\n  * registry: registry.gitlab.com traffic\n  * fe: gitlab.com traffic (via cloudflare)\n  * pages: *.gitlab.io and pages custom domains\n* Fleet\n  * git (K8s): git-https, git-ssh, websockets\n  * api (K8s): gitlab.com public api, gitlab.com/v4/api/*\n  * web (K8s): gitlab.com web traffic, anything that is not gitlab.com/v4/api/*\n  * web-pages (K8s): *.gitlab.io pages traffic\n* Storage\n  * file: All projects/wikis from local disk, this is where gitaly runs\n  * pages: NFS server for *.gitlab.io gitlab pages\n  * share: Shared cache for job traces and artifacts\n  * patroni: All postgres database servers\n  * redis: All redis clusters\n  * object storagE: All object storage buckets\n"
  },
  {
   "title": "HAProxy Backends",
   "type": "text",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 1 },
   "content": "### HAProxy Backend Network Reporting\n\n**HAProxy backend reporting looks different than egress/ingress node metrics.**\n\nThis is because we are using HAProxy application metrics that allow us to see data\nflowing in and out of individual backends.\n\n* Web / API / HTTPs Git / Git SSH / Websockets - This traffic is served by the HAProxy Fe nodes\n* Registry - This traffic is served by the HAProxy Registry nodes\n* Pages - This traffic is served by the HAProxy Pages nodes\n\nNote that some of the graphs are more lopsided than the node graphs, see the FAQ for an explanation.\n"
  },
  {
   "title": "FAQ",
   "type": "text",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 1 },
   "content": "## FAQ\n\n* Why is the fleet node bandwidth so symetrical? Shouldn't we be sending more than we receive?\n  * Most of our traffic is proxied to storage services, or to object storage.\n* Do clients download direct from object storage?\n  * It depends.\n    * registry: all image pulls are direct from object storage\n    * uploads/lfs/merge-request-diffs: currently set to proxy but we might change that\n      https://gitlab.com/gitlab-com/gl-infra/reliability/-/issues/10117\n* Why for HAProxy Registry backend traffic, is there so much more ingress than egress?\n  * Registry downloads are direct from Object Storage\n* Why for HAProxy HTTPs and SSH Git traffic is egress so much more than ingress?\n  * We are sending more Git data to clients than we are receiving\n* What about canary traffic?\n  * Canary traffic is included in production traffic\n* What is websockets used for?\n  * Websockets is only used right now for the interractive terminal, and actioncable\n"
  },
  {
   "title": "HAProxy data transfer by Backend",
   "type": "row",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "HTTPs Git Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(haproxy_backend_bytes_out_total{device!=\"lo\", backend=~\".*https_git$\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(haproxy_backend_bytes_in_total{device!=\"lo\", backend=~\".*https_git$\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Registry Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(haproxy_backend_bytes_out_total{device!=\"lo\", backend=~\".*registry$\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(haproxy_backend_bytes_in_total{device!=\"lo\", backend=~\".*registry$\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "API Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(haproxy_backend_bytes_out_total{device!=\"lo\", backend=~\".*api$\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(haproxy_backend_bytes_in_total{device!=\"lo\", backend=~\".*api$\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Web Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(haproxy_backend_bytes_out_total{device!=\"lo\", backend=~\".*web$\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(haproxy_backend_bytes_in_total{device!=\"lo\", backend=~\".*web$\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Pages Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(haproxy_backend_bytes_out_total{device!=\"lo\", backend=~\".*pages_https?$\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(haproxy_backend_bytes_in_total{device!=\"lo\", backend=~\".*pages_https?$\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "WebSockets Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(haproxy_backend_bytes_out_total{device!=\"lo\", backend=~\".*websockets$\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(haproxy_backend_bytes_in_total{device!=\"lo\", backend=~\".*websockets$\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "SSH Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(haproxy_backend_bytes_out_total{device!=\"lo\", backend=~\".*ssh$\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(haproxy_backend_bytes_in_total{device!=\"lo\", backend=~\".*ssh$\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  { "title": "HAProxy Nodes", "type": "row", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Fe (HAProxy) Registry Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^fe-registry-[0-9].*\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^fe-registry-[0-9].*\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Fe (HAProxy) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^fe-[0-9].*\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^fe-[0-9].*\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Fe Pages (HAProxy) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^fe-pages-[0-9].*\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^fe-pages-[0-9].*\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Fleet Nodes and Kubernetes Containers",
   "type": "row",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Git Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total:labeled{device!=\"lo\", type=\"git\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(container_network_receive_bytes_total:labeled{device!=\"lo\", type=\"git\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "API Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total:labeled{device!=\"lo\", type=\"api\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(container_network_receive_bytes_total:labeled{device!=\"lo\", type=\"api\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Web Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total:labeled{device!=\"lo\", type=\"web\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(container_network_receive_bytes_total:labeled{device!=\"lo\", type=\"web\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Web Pages Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total:labeled{device!=\"lo\", type=\"web-pages\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(container_network_receive_bytes_total:labeled{device!=\"lo\", type=\"web-pages\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  { "title": "Storage Nodes", "type": "row", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "File (Gitaly) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", type=\"gitaly\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", type=\"gitaly\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Patroni  (Database) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", type=\"patroni\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", type=\"patroni\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Redis  (All) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", type=~\"^redis.*\", env=\"$environment\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", type=~\"^redis.*\", env=\"$environment\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  { "title": "Object Storage", "type": "row", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Object Storage by Bucket data transfer / hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket_name) (sum_over_time(stackdriver_gcs_bucket_storage_googleapis_com_network_sent_bytes_count{env=\"$environment\"}[1h]))",
     "legendFormat": "egress {{ bucket_name }}"
    },
    {
     "expr": "sum by (bucket_name) (sum_over_time(stackdriver_gcs_bucket_storage_googleapis_com_network_received_bytes_count{env=\"$environment\"}[1h])) * -1",
     "legendFormat": "ingress {{ bucket_name }}"
    }
   ]
  }
 ]
}