{
 "title": "General Triage - Missing Component Series Data",
 "description": "$type",
 "tags": [ "general triage" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_ds", "query": "prometheus" },
   { "name": "environment", "query": "label_values(up, environment)" },
   {
    "name": "type",
    "query": "label_values(up{environment=\"$environment\"}, type)"
   },
   {
    "name": "component",
    "query": "label_values(gitlab_component_availability:ratio{environment=\"$environment\", type=\"$type\"}, component)"
   }
  ]
 },
 "panels": [
  { "title": "Per-Component Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "\"$component\" Service Component Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "component_availability",
   "yaxes": [
    { "format": "percentunit", "label": "Availability" }
   ],
   "targets": [
    {
     "expr": "gitlab_component_availability:ratio{environment=\"$environment\", type=\"$type\", component=\"$component\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ component }} ({{ monitor }})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Per-Component Operation Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$component Service Operation Rates",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "repeat": "component_ops",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(gitlab_component_ops:rate{environment=\"$environment\", type=\"$type\", component=\"$component\"}[$__interval])) by (component)",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "Per-Component Apdex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$component Component Apdex",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "repeat": "component_apdex",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio{environment=\"$environment\", type=\"$type\", component=\"$component\"}[$__interval])",
     "legendFormat": "{{ component }} component ({{ monitor }})"
    }
   ]
  },
  { "title": "Per-Component Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "$component Component - Error Rates per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "repeat": "component_errors",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_errors:rate{environment=\"$environment\", type=\"$type\", component=\"$component\"}[$__interval]) * 60",
     "legendFormat": "{{ component }} component"
    }
   ]
  }
 ]
}