{
 "title": "general: Occurence SLAs",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4638929855 at Wed Jul 12 10:39:25 UTC 2023",
 "tags": [
  "managed",
  "general",
  "general",
  "slas",
  "service-levels"
 ],
 "time": { "from": "now-1M/M", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "web_weight", "query": "0,1,5" },
   { "name": "git_weight", "query": "0,1,5" },
   { "name": "api_weight", "query": "0,1,5" },
   { "name": "ci_runners_weight", "query": "0,1,5" },
   { "name": "registry_weight", "query": "0,1,5" },
   { "name": "web_pages_weight", "query": "0,1,5" },
   { "name": "sidekiq_weight", "query": "0,1,5" },
   { "name": "internal_api_weight", "query": "0,1,5" }
  ]
 },
 "panels": [
  { "title": "Overall GitLab availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Overall availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"api\"}[$__range]) * $api_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"ci-runners\"}[$__range]) * $ci_runners_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"git\"}[$__range]) * $git_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"internal-api\"}[$__range]) * $internal_api_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"registry\"}[$__range]) * $registry_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"sidekiq\"}[$__range]) * $sidekiq_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__range]) * $web_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web-pages\"}[$__range]) * $web_pages_weight\n  )\n)\n/\nsum(\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"api\"}[$__range]) * $api_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"ci-runners\"}[$__range]) * $ci_runners_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"git\"}[$__range]) * $git_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"internal-api\"}[$__range]) * $internal_api_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"registry\"}[$__range]) * $registry_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"sidekiq\"}[$__range]) * $sidekiq_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__range]) * $web_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web-pages\"}[$__range]) * $web_pages_weight\n  )\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    sum(\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"api\"}[$__range]) * $api_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"ci-runners\"}[$__range]) * $ci_runners_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"git\"}[$__range]) * $git_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"internal-api\"}[$__range]) * $internal_api_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"registry\"}[$__range]) * $registry_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"sidekiq\"}[$__range]) * $sidekiq_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__range]) * $web_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web-pages\"}[$__range]) * $web_pages_weight\n      )\n    )\n    /\n    sum(\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"api\"}[$__range]) * $api_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"ci-runners\"}[$__range]) * $ci_runners_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"git\"}[$__range]) * $git_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"internal-api\"}[$__range]) * $internal_api_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"registry\"}[$__range]) * $registry_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"sidekiq\"}[$__range]) * $sidekiq_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__range]) * $web_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web-pages\"}[$__range]) * $web_pages_weight\n      )\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Calendar",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"api\"}[1d]) * $api_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"ci-runners\"}[1d]) * $ci_runners_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"git\"}[1d]) * $git_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"internal-api\"}[1d]) * $internal_api_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"registry\"}[1d]) * $registry_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"sidekiq\"}[1d]) * $sidekiq_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[1d]) * $web_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web-pages\"}[1d]) * $web_pages_weight\n  )\n)\n/\nsum(\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"api\"}[1d]) * $api_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"ci-runners\"}[1d]) * $ci_runners_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"git\"}[1d]) * $git_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"internal-api\"}[1d]) * $internal_api_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"registry\"}[1d]) * $registry_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"sidekiq\"}[1d]) * $sidekiq_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[1d]) * $web_weight\n  )\n  or\n  sum by (type)(\n    sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web-pages\"}[1d]) * $web_pages_weight\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Overall GitLab.com SLA over time period",
   "type": "graph",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum(\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"api\"}[$__interval]) * $api_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"ci-runners\"}[$__interval]) * $ci_runners_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"git\"}[$__interval]) * $git_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"internal-api\"}[$__interval]) * $internal_api_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"registry\"}[$__interval]) * $registry_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"sidekiq\"}[$__interval]) * $sidekiq_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__interval]) * $web_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web-pages\"}[$__interval]) * $web_pages_weight\n      )\n    )\n    /\n    sum(\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"api\"}[$__interval]) * $api_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"ci-runners\"}[$__interval]) * $ci_runners_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"git\"}[$__interval]) * $git_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"internal-api\"}[$__interval]) * $internal_api_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"registry\"}[$__interval]) * $registry_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"sidekiq\"}[$__interval]) * $sidekiq_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__interval]) * $web_weight\n      )\n      or\n      sum by (type)(\n        sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web-pages\"}[$__interval]) * $web_pages_weight\n      )\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "Overall SLA"
    }
   ]
  },
  {
   "title": "GitLab Primary Service Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "web availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web\"}[$__range])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web\"}[$__range])\n    ),\n    0\n  ),\n  1\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    clamp_max(\n      clamp_min(\n        sum by () (\n          sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web\"}[$__range])\n        )\n        /\n        sum by () (\n          sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web\"}[$__range])\n        ),\n        0\n      ),\n      1\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Calendar",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum by () (\n  sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web\"}[1d])\n)\n/\nsum by () (\n  sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web\"}[1d])\n)\n"
    }
   ]
  },
  {
   "title": "web SLA over time period",
   "type": "graph",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web\"}[$__interval])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web\"}[$__interval])\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "web SLA"
    }
   ]
  },
  {
   "title": "git availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"git\"}[$__range])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"git\"}[$__range])\n    ),\n    0\n  ),\n  1\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    clamp_max(\n      clamp_min(\n        sum by () (\n          sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"git\"}[$__range])\n        )\n        /\n        sum by () (\n          sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"git\"}[$__range])\n        ),\n        0\n      ),\n      1\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Calendar",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum by () (\n  sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"git\"}[1d])\n)\n/\nsum by () (\n  sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"git\"}[1d])\n)\n"
    }
   ]
  },
  {
   "title": "git SLA over time period",
   "type": "graph",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"git\"}[$__interval])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"git\"}[$__interval])\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "git SLA"
    }
   ]
  },
  {
   "title": "api availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"api\"}[$__range])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"api\"}[$__range])\n    ),\n    0\n  ),\n  1\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    clamp_max(\n      clamp_min(\n        sum by () (\n          sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"api\"}[$__range])\n        )\n        /\n        sum by () (\n          sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"api\"}[$__range])\n        ),\n        0\n      ),\n      1\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Calendar",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum by () (\n  sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"api\"}[1d])\n)\n/\nsum by () (\n  sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"api\"}[1d])\n)\n"
    }
   ]
  },
  {
   "title": "api SLA over time period",
   "type": "graph",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"api\"}[$__interval])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"api\"}[$__interval])\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "api SLA"
    }
   ]
  },
  {
   "title": "ci-runners availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"ci-runners\"}[$__range])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"ci-runners\"}[$__range])\n    ),\n    0\n  ),\n  1\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    clamp_max(\n      clamp_min(\n        sum by () (\n          sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"ci-runners\"}[$__range])\n        )\n        /\n        sum by () (\n          sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"ci-runners\"}[$__range])\n        ),\n        0\n      ),\n      1\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Calendar",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "sum by () (\n  sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"ci-runners\"}[1d])\n)\n/\nsum by () (\n  sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"ci-runners\"}[1d])\n)\n"
    }
   ]
  },
  {
   "title": "ci-runners SLA over time period",
   "type": "graph",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"ci-runners\"}[$__interval])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"ci-runners\"}[$__interval])\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "ci-runners SLA"
    }
   ]
  },
  {
   "title": "registry availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"registry\"}[$__range])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"registry\"}[$__range])\n    ),\n    0\n  ),\n  1\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    clamp_max(\n      clamp_min(\n        sum by () (\n          sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"registry\"}[$__range])\n        )\n        /\n        sum by () (\n          sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"registry\"}[$__range])\n        ),\n        0\n      ),\n      1\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Calendar",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "sum by () (\n  sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"registry\"}[1d])\n)\n/\nsum by () (\n  sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"registry\"}[1d])\n)\n"
    }
   ]
  },
  {
   "title": "registry SLA over time period",
   "type": "graph",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"registry\"}[$__interval])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"registry\"}[$__interval])\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "registry SLA"
    }
   ]
  },
  {
   "title": "web-pages availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web-pages\"}[$__range])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web-pages\"}[$__range])\n    ),\n    0\n  ),\n  1\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    clamp_max(\n      clamp_min(\n        sum by () (\n          sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web-pages\"}[$__range])\n        )\n        /\n        sum by () (\n          sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web-pages\"}[$__range])\n        ),\n        0\n      ),\n      1\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Calendar",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "sum by () (\n  sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web-pages\"}[1d])\n)\n/\nsum by () (\n  sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web-pages\"}[1d])\n)\n"
    }
   ]
  },
  {
   "title": "web-pages SLA over time period",
   "type": "graph",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web-pages\"}[$__interval])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"web-pages\"}[$__interval])\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "web-pages SLA"
    }
   ]
  },
  {
   "title": "sidekiq availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"sidekiq\"}[$__range])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"sidekiq\"}[$__range])\n    ),\n    0\n  ),\n  1\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    clamp_max(\n      clamp_min(\n        sum by () (\n          sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"sidekiq\"}[$__range])\n        )\n        /\n        sum by () (\n          sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"sidekiq\"}[$__range])\n        ),\n        0\n      ),\n      1\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Calendar",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum by () (\n  sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"sidekiq\"}[1d])\n)\n/\nsum by () (\n  sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"sidekiq\"}[1d])\n)\n"
    }
   ]
  },
  {
   "title": "sidekiq SLA over time period",
   "type": "graph",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"sidekiq\"}[$__interval])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"sidekiq\"}[$__interval])\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "sidekiq SLA"
    }
   ]
  },
  {
   "title": "internal-api availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"internal-api\"}[$__range])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"internal-api\"}[$__range])\n    ),\n    0\n  ),\n  1\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    clamp_max(\n      clamp_min(\n        sum by () (\n          sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"internal-api\"}[$__range])\n        )\n        /\n        sum by () (\n          sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"internal-api\"}[$__range])\n        ),\n        0\n      ),\n      1\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Calendar",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 50 },
   "targets": [
    {
     "expr": "sum by () (\n  sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"internal-api\"}[1d])\n)\n/\nsum by () (\n  sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"internal-api\"}[1d])\n)\n"
    }
   ]
  },
  {
   "title": "internal-api SLA over time period",
   "type": "graph",
   "description": "Availability over time, higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(clamp_max(\n  clamp_min(\n    sum by () (\n      sum_over_time(gitlab:availability:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"internal-api\"}[$__interval])\n    )\n    /\n    sum by () (\n      sum_over_time(gitlab:availability:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"main\",type=~\"internal-api\"}[$__interval])\n    ),\n    0\n  ),\n  1\n)\n,1),0)\n",
     "legendFormat": "internal-api SLA"
    }
   ]
  }
 ]
}