{
 "title": "general: Kubernetes Version Matrix",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5580552802 at Tue Nov 21 00:13:57 UTC 2023",
 "tags": [
  "managed",
  "general",
  "general",
  "kubernetes"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Master Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max (kubernetes_build_info{environment=\"$environment\", job=\"apiserver\"}) by (node, gitVersion)\n"
    }
   ]
  },
  {
   "title": "Master Version Over Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (kubernetes_build_info{environment=\"$environment\", job=\"apiserver\"}) by (gitVersion)\n"
    }
   ]
  },
  {
   "title": "Node Versions",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "max(kube_node_info{environment=\"$environment\"}) by (cluster, node, kernel_version, kubelet_version, kubeproxy_version)\n"
    }
   ]
  },
  {
   "title": "Node Versions Over Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (kube_node_info{environment=\"$environment\"}) by (cluster, node, kubelet_version)\n"
    }
   ]
  }
 ]
}