{
 "title": "General Triage: Service",
 "description": "$type",
 "tags": [ "general triage" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_ds", "query": "prometheus" },
   { "name": "environment", "query": "label_values(up, environment)" },
   {
    "name": "type",
    "query": "label_values(up{environment=\"$environment\"}, type)"
   },
   { "name": "sigma", "label": "σ", "query": "0.5,1,1.5,2,2.5,3" },
   {
    "name": "component_availability",
    "query": "label_values(gitlab_component_availability:ratio{environment=\"$environment\", type=\"$type\"}, component)"
   },
   {
    "name": "component_ops",
    "query": "label_values(gitlab_component_ops:rate{environment=\"$environment\", type=\"$type\"}, component)"
   },
   {
    "name": "component_apdex",
    "query": "label_values(gitlab_component_apdex:ratio{environment=\"$environment\", type=\"$type\"}, component)"
   },
   {
    "name": "component_errors",
    "query": "label_values(gitlab_component_errors:rate{environment=\"$environment\", type=\"$type\"}, component)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"} > 0) without (monitor)"
    },
    {
     "expr": "sum(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"pending\"} > 0) without (monitor)"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$type Service Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "repeat": "prometheus_ds",
   "yaxes": [
    { "format": "percentunit", "label": "Availability" }
   ],
   "targets": [
    {
     "expr": "min(min_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval])) by (tier, type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }} service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "min(\nclamp_max(\n  gitlab_service_availability:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\"} + $sigma * gitlab_service_availability:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\"},\n1\n))",
     "legendFormat": "upper"
    },
    {
     "expr": "min(\nclamp_min(\ngitlab_service_availability:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\"} - $sigma * gitlab_service_availability:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\"},\n0\n)\n)",
     "legendFormat": "lower"
    },
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", metric=\"gitlab_service_availability\", type=\"$type\"}[$__interval])) by (alertstate)",
     "legendFormat": "Alert {{alertstate}}"
    },
    {
     "expr": "min(min_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval] offset 1w)) by (tier, type)",
     "legendFormat": "{{ type }} 1 week ago"
    }
   ]
  },
  {
   "title": "Per-Component Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "\"$component_availability\" Service Component Availability",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "repeat": "component_availability",
     "yaxes": [
      { "format": "percentunit", "label": "Availability" }
     ],
     "targets": [
      {
       "expr": "gitlab_component_availability:ratio{environment=\"$environment\", type=\"$type\", component=\"$component_availability\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ component }} ({{ monitor }})",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Operation Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$type Service Operation Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(gitlab_service_ops:rate{environment=\"$environment\", type=\"$type\"}[$__interval])) by (type)",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "sum(\ngitlab_service_ops:rate:avg_over_time_1w{component=\"\", service=\"\", environment=\"$environment\", type=\"$type\"} + \n$sigma * gitlab_service_ops:rate:stddev_over_time_1w{component=\"\", environment=\"$environment\", type=\"$type\"}\n)",
     "legendFormat": "upper"
    },
    {
     "expr": "sum(\nclamp_min(gitlab_service_ops:rate:avg_over_time_1w{component=\"\", service=\"\", environment=\"$environment\", type=\"$type\"} \n- $sigma * gitlab_service_ops:rate:stddev_over_time_1w{component=\"\", environment=\"$environment\", type=\"$type\"}, 0)\n)",
     "legendFormat": "lower"
    },
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", metric=\"gitlab_service_ops\", type=\"$type\"}[$__interval])) by (alertstate)",
     "legendFormat": "Alert {{alertstate}}"
    },
    {
     "expr": "sum(avg_over_time(gitlab_service_ops:rate{environment=\"$environment\", type=\"$type\"}[$__interval] offset 1w)) by (type)",
     "legendFormat": "{{ type }} - 1 week ago"
    }
   ]
  },
  {
   "title": "$type Service Operation Rates (Periodic)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(gitlab_service_ops:rate{environment=\"$environment\", type=\"$type\"}[$__interval])) by (type)",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", metric=\"gitlab_service_ops\", type=\"$type\"}[$__interval])) by (alertstate)",
     "legendFormat": "Alert {{alertstate}}"
    },
    {
     "expr": "sum(avg_over_time(gitlab_service_ops:rate{environment=\"$environment\", type=\"$type\"}[$__interval] offset 1w)) by (type)",
     "legendFormat": "{{ type }} - 1 week ago"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"$type\"}+ \n$sigma * gitlab_service_ops:rate:stddev_over_time_1w{component=\"\", environment=\"$environment\", type=\"$type\"}",
     "legendFormat": "upper"
    },
    {
     "expr": "sum(\nclamp_min(\ngitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"$type\"}  \n- $sigma * gitlab_service_ops:rate:stddev_over_time_1w{component=\"\", environment=\"$environment\", type=\"$type\"}, 0)\n)",
     "legendFormat": "lower"
    }
   ]
  },
  {
   "title": "Per-Component Operation Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "$component_ops Service Operation Rates",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "repeat": "component_ops",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(gitlab_component_ops:rate{environment=\"$environment\", type=\"$type\", component=\"$component_ops\"}[$__interval])) by (component)",
       "legendFormat": "{{ component }} component"
      },
      {
       "expr": "sum(\ngitlab_component_ops:rate:avg_over_time_1w{service=\"\", environment=\"$environment\", type=\"$type\", component=\"$component_ops\"} + \n$sigma * gitlab_component_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_ops\"}\n)",
       "legendFormat": "upper"
      },
      {
       "expr": "sum(\nclamp_min(gitlab_component_ops:rate:avg_over_time_1w{service=\"\", environment=\"$environment\", type=\"$type\", component=\"$component_ops\"} \n- $sigma * gitlab_component_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_ops\"}, 0)\n)",
       "legendFormat": "lower"
      }
     ]
    },
    {
     "title": "$component_ops Service Operation Rates",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(gitlab_component_ops:rate{environment=\"$environment\", type=\"$type\", component=\"$component_ops\"}[$__interval])) by (component)",
       "legendFormat": "{{ component }} component"
      },
      {
       "expr": "sum(\ngitlab_component_ops:rate:avg_over_time_1w{service=\"\", environment=\"$environment\", type=\"$type\", component=\"$component_ops\"} + \n$sigma * gitlab_component_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_ops\"}\n)",
       "legendFormat": "upper"
      },
      {
       "expr": "sum(\nclamp_min(gitlab_component_ops:rate:avg_over_time_1w{service=\"\", environment=\"$environment\", type=\"$type\", component=\"$component_ops\"} \n- $sigma * gitlab_component_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_ops\"}, 0)\n)",
       "legendFormat": "lower"
      }
     ]
    }
   ]
  },
  { "title": "Apdex Score", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "$type Service Apdex",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_apdex:ratio{environment=\"$environment\", type=\"$type\"}[$__interval])) by (type)",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "avg(\nclamp_max(\ngitlab_service_apdex:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\"} + $sigma * gitlab_service_apdex:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\"},\n1))",
     "legendFormat": "upper"
    },
    {
     "expr": "avg(clamp_min(\ngitlab_service_apdex:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\"} - 2 * gitlab_service_apdex:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\"},\n0))",
     "legendFormat": "lower"
    },
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", metric=\"gitlab_service_apdex\", type=\"$type\"}[$__interval])) by (alertstate)",
     "legendFormat": "Alert {{ alertstate }}"
    },
    {
     "expr": "avg(avg_over_time(gitlab_service_apdex:ratio{environment=\"$environment\", type=\"$type\"}[$__interval] offset 1w)) by (type)",
     "legendFormat": "{{ type }} - 1 week ago"
    }
   ]
  },
  {
   "title": "Per-Component Apdex",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "$component_apdex Component Apdex",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "repeat": "component_apdex",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab_component_apdex:ratio{environment=\"$environment\", type=\"$type\", component=\"$component_apdex\"}[$__interval])",
       "legendFormat": "{{ component }} component ({{ monitor }})"
      },
      {
       "expr": "clamp_min(gitlab_component_apdex:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_apdex\"} - $sigma * gitlab_component_apdex:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_apdex\"}, 0)",
       "legendFormat": "lower"
      },
      {
       "expr": "clamp_max(gitlab_component_apdex:ratio:avg_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_apdex\"} + $sigma * gitlab_component_apdex:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_apdex\"}, 1)",
       "legendFormat": "upper"
      }
     ]
    }
   ]
  },
  { "title": "Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "$type Service Error Rates per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(gitlab_service_errors:rate{component=\"\", service=\"\", environment=\"$environment\", type=\"$type\"}[$__interval])) by (type) * 60",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "sum((gitlab_service_errors:rate:avg_over_time_1w{component=\"\", service=\"\", environment=\"$environment\", type=\"$type\"} + $sigma * gitlab_service_errors:rate:stddev_over_time_1w{component=\"\", service=\"\", environment=\"$environment\", type=\"$type\"}) * 60)",
     "legendFormat": "upper"
    },
    {
     "expr": "sum(clamp_min(gitlab_service_errors:rate:avg_over_time_1w{component=\"\", service=\"\", environment=\"$environment\", type=\"$type\"} - $sigma * gitlab_service_errors:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\"}, 0) * 60)",
     "legendFormat": "lower"
    },
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", metric=\"gitlab_service_errors\", type=\"$type\"}[$__interval])) by (alertstate)",
     "legendFormat": "Alert {{alertstate}}"
    },
    {
     "expr": "sum(avg_over_time(gitlab_service_errors:rate{component=\"\", service=\"\", environment=\"$environment\", type=\"$type\"}[$__interval] offset 1w)) by (type) * 60",
     "legendFormat": "{{ type }} - 1 week ago"
    }
   ]
  },
  {
   "title": "Per-Component Error Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "$component_errors Component - Error Rates per Minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "repeat": "component_errors",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab_component_errors:rate{environment=\"$environment\", type=\"$type\", component=\"$component_errors\"}[$__interval]) * 60",
       "legendFormat": "{{ component }} component"
      },
      {
       "expr": "(gitlab_component_errors:rate:avg_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_errors\"} + $sigma * gitlab_component_errors:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_errors\"}) * 60",
       "legendFormat": "upper"
      },
      {
       "expr": "clamp_min((gitlab_component_errors:rate:avg_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_errors\"} - $sigma * gitlab_component_errors:rate:stddev_over_time_1w{environment=\"$environment\", type=\"$type\", component=\"$component_errors\"}) * 60, 0)",
       "legendFormat": "lower"
      }
     ]
    }
   ]
  },
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percentunit", "label": "Used CPU" }
   ],
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{type=\"$type\", environment=\"$environment\", mode=\"idle\"}[$__interval])) by (fqdn)",
     "legendFormat": "{{ fqdn }} "
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "percentunit", "label": "Used Memory %" }
   ],
   "targets": [
    {
     "expr": "avg(\n(node_memory_MemTotal_bytes{type=\"$type\", environment=\"$environment\"} - \n(\n  node_memory_MemFree_bytes{type=\"$type\", environment=\"$environment\"} + \n  node_memory_Buffers_bytes{type=\"$type\", environment=\"$environment\"} + \n  node_memory_Cached_bytes{type=\"$type\", environment=\"$environment\"}\n) \n)\n\n/ node_memory_MemTotal_bytes{type=\"$type\", environment=\"$environment\"}\n) by (fqdn)",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  }
 ]
}