{
 "title": "general: SLO Review",
 "description": "Uploaded by andrewn at Thu  6 May 2021 12:29:47 UTC",
 "tags": [
  "managed",
  "general",
  "general",
  "slos",
  "service-levels"
 ],
 "time": { "from": "now-29d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  { "title": "SLO Review", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Apdex SLO Performance Review",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "(\n  sum by (tier, type, component) (sum_over_time(gitlab_component_apdex:success:rate_1h{env=\"$environment\", stage=\"main\"}[$__range]))\n  /\n  sum by (tier, type, component) (sum_over_time(gitlab_component_apdex:weight:score_1h{env=\"$environment\", stage=\"main\"}[$__range]))\n)\n/ on(type, tier) group_left()\nslo:min:events:gitlab_service_apdex:ratio\n- 1\n"
    }
   ]
  },
  {
   "title": "Error SLO Performance Review",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "(\n  1 - (\n    sum by (tier, type, component) (sum_over_time(gitlab_component_errors:rate_1h{env=\"$environment\", stage=\"main\"}[$__range]))\n    /\n    sum by (tier, type, component) (sum_over_time(gitlab_component_ops:rate_1h{env=\"$environment\", stage=\"main\"}[$__range]))\n  )\n)\n/ on (type, tier) group_left()\n(1 - slo:max:events:gitlab_service_errors:ratio)\n- 1\n"
    }
   ]
  },
  {
   "title": "Apdex SLIs with no SLO",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "(\n  sum by (tier, type, component) (sum_over_time(gitlab_component_apdex:success:rate_1h{env=\"$environment\", stage=\"main\"}[$__range]))\n  /\n  sum by (tier, type, component) (sum_over_time(gitlab_component_apdex:weight:score_1h{env=\"$environment\", stage=\"main\"}[$__range]))\n)\nunless on(type, tier)\nslo:min:events:gitlab_service_apdex:ratio\n"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/general/slo-review.jsonnet)\n"
  }
 ]
}