{
 "title": "general: Incident Overview",
 "description": "Uploaded by andrewn at Mon 29 Jun 2020 08:04:09 UTC",
 "tags": [
  "managed",
  "general",
  "general"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  { "title": "Latencies", "type": "row", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "api Service Apdex Score",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min by (type) (min_over_time(gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval]))\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"api\"})\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "avg by (type) (avg_over_time(gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval]))\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\",stage=\"$stage\",type=\"api\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"api\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\",stage=\"$stage\",type=\"api\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"api\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min by (type) (gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w)\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"api\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "web Service Apdex Score",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min by (type) (min_over_time(gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}[$__interval]))\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"web\"})\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "avg by (type) (avg_over_time(gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}[$__interval]))\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\",stage=\"$stage\",type=\"web\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\",stage=\"$stage\",type=\"web\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min by (type) (gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"} offset 1w)\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"web\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "git Service Apdex Score",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min by (type) (min_over_time(gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval]))\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"git\"})\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "avg by (type) (avg_over_time(gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval]))\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\",stage=\"$stage\",type=\"git\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"git\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\",stage=\"$stage\",type=\"git\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"git\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min by (type) (gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"} offset 1w)\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"git\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "registry Service Apdex Score",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min by (type) (min_over_time(gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval]))\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"registry\"})\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "avg by (type) (avg_over_time(gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval]))\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\",stage=\"$stage\",type=\"registry\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"registry\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\",stage=\"$stage\",type=\"registry\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"registry\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min by (type) (gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w)\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"registry\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  { "title": "Error Rates", "type": "row", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "api Service Error Rate",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max by (type) (max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval]))\n  or\n  sum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"api\"}),\n  1\n)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "clamp_max(\n  avg by (type) (avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])),\n  1\n)\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"api\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"api\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"api\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"api\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max by (type) (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w)\nor\nsum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"api\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "web Service Error Rate",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 60 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max by (type) (max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}[$__interval]))\n  or\n  sum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"web\"}),\n  1\n)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "clamp_max(\n  avg by (type) (avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}[$__interval])),\n  1\n)\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"web\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"web\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"web\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"web\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max by (type) (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"} offset 1w)\nor\nsum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"web\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "git Service Error Rate",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max by (type) (max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval]))\n  or\n  sum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"git\"}),\n  1\n)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "clamp_max(\n  avg by (type) (avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])),\n  1\n)\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"git\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"git\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"git\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"git\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max by (type) (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"} offset 1w)\nor\nsum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"git\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "registry Service Error Rate",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 60 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max by (type) (max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval]))\n  or\n  sum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"registry\"}),\n  1\n)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "clamp_max(\n  avg by (type) (avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])),\n  1\n)\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"registry\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"registry\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"registry\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"registry\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max by (type) (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w)\nor\nsum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"registry\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  { "title": "RPS", "type": "row", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "api Service RPS",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max by (type) (max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval]))\n  or\n  sum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"api\"}),\n  1\n)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "clamp_max(\n  avg by (type) (avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"}[$__interval])),\n  1\n)\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"api\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"api\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"api\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"api\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max by (type) (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"api\"} offset 1w)\nor\nsum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"api\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "web Service RPS",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 110 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max by (type) (max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}[$__interval]))\n  or\n  sum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"web\"}),\n  1\n)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "clamp_max(\n  avg by (type) (avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}[$__interval])),\n  1\n)\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"web\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"web\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"web\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"web\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max by (type) (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"} offset 1w)\nor\nsum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"web\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "git Service RPS",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max by (type) (max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval]))\n  or\n  sum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"git\"}),\n  1\n)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "clamp_max(\n  avg by (type) (avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"}[$__interval])),\n  1\n)\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"git\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"git\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"git\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"git\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max by (type) (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"git\"} offset 1w)\nor\nsum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"git\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "registry Service RPS",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 110 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max by (type) (max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval]))\n  or\n  sum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"registry\"}),\n  1\n)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "clamp_max(\n  avg by (type) (avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])),\n  1\n)\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"registry\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"registry\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\",stage=\"$stage\",type=\"registry\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"registry\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max by (type) (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w)\nor\nsum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"$stage\",type=\"registry\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/general/incident-analysis.jsonnet)\n"
  }
 ]
}