{
 "title": "general: Request apdex participation",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/2075286974 at Wed Feb  9 21:27:03 UTC 2022",
 "tags": [
  "managed",
  "general"
 ],
 "time": { "from": "now-7d/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "product_stage",
    "query": "label_values(gitlab:feature_category:stage_group:mapping{monitor=\"global\"}, product_stage)"
   },
   {
    "name": "stage_group",
    "query": "label_values(gitlab:feature_category:stage_group:mapping{monitor=\"global\", product_stage=~\"$product_stage\"}, stage_group)"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic by urgency (over the last 6h)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "high urgency requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (request_urgency) (\n    sum by (request_urgency, feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"high\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n  / ignoring(request_urgency) group_left() sum(\n    sum by (feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n)\n",
     "legendFormat": "{{ urgency }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (endpoint_id, feature_category) (\n    count_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"high\",stage=\"$stage\"}[6h]) > 0\n  ) * on (feature_category) group_left() group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
    }
   ]
  },
  {
   "title": "medium urgency requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (request_urgency) (\n    sum by (request_urgency, feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"medium\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n  / ignoring(request_urgency) group_left() sum(\n    sum by (feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n)\n",
     "legendFormat": "{{ urgency }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (endpoint_id, feature_category) (\n    count_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"medium\",stage=\"$stage\"}[6h]) > 0\n  ) * on (feature_category) group_left() group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
    }
   ]
  },
  {
   "title": "default urgency requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (request_urgency) (\n    sum by (request_urgency, feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"default\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n  / ignoring(request_urgency) group_left() sum(\n    sum by (feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n)\n",
     "legendFormat": "{{ urgency }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (endpoint_id, feature_category) (\n    count_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"default\",stage=\"$stage\"}[6h]) > 0\n  ) * on (feature_category) group_left() group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
    }
   ]
  },
  {
   "title": "low urgency requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (request_urgency) (\n    sum by (request_urgency, feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"low\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n  / ignoring(request_urgency) group_left() sum(\n    sum by (feature_category)(\n      sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[6h]) > 0\n    ) * on (feature_category) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  )\n)\n",
     "legendFormat": "{{ urgency }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (endpoint_id, feature_category) (\n    count_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"low\",stage=\"$stage\"}[6h]) > 0\n  ) * on (feature_category) group_left() group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
    }
   ]
  },
  {
   "title": "Endpoints by urgency (over the last 6h)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "high urgency endpoints ordered by request rate",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "sort_desc(\n  sum by (feature_category, endpoint_id)(\n    sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"high\",stage=\"$stage\"}[6h])\n  ) * on (feature_category) group_left(stage_group, product_stage) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
      }
     ]
    },
    {
     "title": "medium urgency endpoints ordered by request rate",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 101 },
     "targets": [
      {
       "expr": "sort_desc(\n  sum by (feature_category, endpoint_id)(\n    sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"medium\",stage=\"$stage\"}[6h])\n  ) * on (feature_category) group_left(stage_group, product_stage) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
      }
     ]
    },
    {
     "title": "default urgency endpoints ordered by request rate",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 101 },
     "targets": [
      {
       "expr": "sort_desc(\n  sum by (feature_category, endpoint_id)(\n    sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"default\",stage=\"$stage\"}[6h])\n  ) * on (feature_category) group_left(stage_group, product_stage) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
      }
     ]
    },
    {
     "title": "low urgency endpoints ordered by request rate",
     "type": "table",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 101 },
     "targets": [
      {
       "expr": "sort_desc(\n  sum by (feature_category, endpoint_id)(\n    sum_over_time(application_sli_aggregation:rails_request_apdex:apdex:weight:score_1h{endpoint_id!=\"unknown\",environment=\"$environment\",monitor=\"global\",request_urgency=\"low\",stage=\"$stage\"}[6h])\n  ) * on (feature_category) group_left(stage_group, product_stage) group by (stage_group,product_stage,feature_category) (gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n"
      }
     ]
    }
   ]
  },
  { "title": "Opted in groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "groups opted in to the rails_request component",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 201 },
   "targets": [
    {
     "expr": "(\n  sum by(product_stage,stage_group)(gitlab:ignored_component:stage_group{component=\"rails_requests\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  or\n  sum by (product_stage,stage_group)(0 * gitlab:feature_category:stage_group:mapping{product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n) and sum by (product_stage,stage_group) (sum_over_time(gitlab:component:stage_group:execution:ops:rate_6h{component=\"rails_requests\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}[$__range])) > 0\n"
    },
    {
     "expr": "sum by (product_stage,stage_group)(\n  sum_over_time(gitlab:component:stage_group:execution:ops:rate_6h{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]) > 0\n)\n/ ignoring(product_stage,stage_group) group_left() sum(\n    sum_over_time(gitlab:component:stage_group:execution:ops:rate_6h{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]) > 0\n)\n"
    },
    {
     "expr": "clamp_max(\n  sum by (product_stage,stage_group)(\n    sum_over_time(gitlab:component:stage_group:execution:apdex:success:rate_6h{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]) > 0\n  )\n  /\n  sum by (product_stage,stage_group)(\n    sum_over_time(gitlab:component:stage_group:execution:apdex:weight:score_6h{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]) > 0\n  ),\n  1\n)\n"
    },
    {
     "expr": "clamp_max(\n  sum by (product_stage,stage_group)(\n    sum_over_time(gitlab:component:stage_group:execution:apdex:success:rate_6h{component=\"puma\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]) > 0\n  )\n  /\n  sum by (product_stage,stage_group)(\n    sum_over_time(gitlab:component:stage_group:execution:apdex:weight:score_6h{component=\"puma\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]) > 0\n  ),\n  1\n)\n"
    }
   ]
  },
  { "title": "Opted in traffic over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 } },
  {
   "title": "Traffic opted in",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (\n    sum by (product_stage,stage_group,component)(\n  sum_over_time(gitlab:component:stage_group:execution:ops:rate_6h{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]) > 0\n)\n/ ignoring(product_stage,stage_group,component) group_left() sum(\n    sum_over_time(gitlab:component:stage_group:execution:ops:rate_6h{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]) > 0\n)\n\n  ) unless on (product_stage,stage_group,component) (gitlab:ignored_component:stage_group{component=\"rails_requests\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n)\n",
     "legendFormat": "opted in"
    },
    {
     "expr": "sum (\n  sum by (product_stage,stage_group,component) (gitlab:ignored_component:stage_group{component=\"rails_requests\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"})\n  * (\n    sum by (product_stage,stage_group,component)(\n  sum_over_time(gitlab:component:stage_group:execution:ops:rate_6h{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]) > 0\n)\n/ ignoring(product_stage,stage_group,component) group_left() sum(\n    sum_over_time(gitlab:component:stage_group:execution:ops:rate_6h{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]) > 0\n)\n\n  )\n)\n",
     "legendFormat": "opted out"
    }
   ]
  }
 ]
}