{
 "title": "general: SLAs",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4142236000 at Wed Apr 19 15:33:41 UTC 2023",
 "tags": [
  "managed",
  "general",
  "general",
  "slas",
  "service-levels"
 ],
 "time": { "from": "now-1M/M", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "sla_type",
    "query": "label_values(sla:gitlab:ratio, sla_type)"
   }
  ]
 },
 "panels": [
  { "title": "Overall System Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GitLab.com Availability",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg_over_time(sla:gitlab:ratio{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",sla_type=\"$sla_type\",stage=\"main\"}[$__range])\n"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 -\n  avg(\n    clamp_max(\n      avg_over_time(sla:gitlab:ratio{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",sla_type=\"$sla_type\",stage=\"main\"}[$__range]),\n      1\n    )\n  )\n) * $__range_ms\n"
    }
   ]
  },
  {
   "title": "Calendar",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(sla:gitlab:ratio{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",sla_type=\"$sla_type\",stage=\"main\"}[1d])\n"
    }
   ]
  },
  {
   "title": "Overall SLA over time period - gitlab.com",
   "type": "graph",
   "description": "Rolling average SLO adherence across all primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg_over_time(sla:gitlab:ratio{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",sla_type=\"$sla_type\",stage=\"main\"}[$__interval])\n,1),0)\n",
     "legendFormat": "gitlab.com SLA"
    }
   ]
  },
  { "title": "Primary Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2101 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"web\"}[$__range]),\n    1\n  )\n)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 -\n  avg(\n    clamp_max(\n      avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"web\"}[$__range]),\n      1\n    )\n  )\n) * $__range_ms\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2101 },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"web\"}[1d]),\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "GitLab.com Web: SLA Trends ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2101 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"web\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"git\"}[$__range]),\n    1\n  )\n)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 -\n  avg(\n    clamp_max(\n      avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"git\"}[$__range]),\n      1\n    )\n  )\n) * $__range_ms\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2106 },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"git\"}[1d]),\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Git Access: SLA Trends ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2106 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"git\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"api\"}[$__range]),\n    1\n  )\n)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2111 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 -\n  avg(\n    clamp_max(\n      avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"api\"}[$__range]),\n      1\n    )\n  )\n) * $__range_ms\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2111 },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"api\"}[1d]),\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "GitLab API: SLA Trends ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2111 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"api\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2116 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"ci-runners\"}[$__range]),\n    1\n  )\n)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2116 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 -\n  avg(\n    clamp_max(\n      avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"ci-runners\"}[$__range]),\n      1\n    )\n  )\n) * $__range_ms\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2116 },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"ci-runners\"}[1d]),\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "CI Runners: SLA Trends ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2116 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"ci-runners\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2121 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"registry\"}[$__range]),\n    1\n  )\n)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2121 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 -\n  avg(\n    clamp_max(\n      avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"registry\"}[$__range]),\n      1\n    )\n  )\n) * $__range_ms\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2121 },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"registry\"}[1d]),\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Container Registry: SLA Trends ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2121 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"registry\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2126 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"web-pages\"}[$__range]),\n    1\n  )\n)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2126 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 -\n  avg(\n    clamp_max(\n      avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"web-pages\"}[$__range]),\n      1\n    )\n  )\n) * $__range_ms\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2126 },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"web-pages\"}[1d]),\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "GitLab Pages: SLA Trends ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2126 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"web-pages\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2131 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"sidekiq\"}[$__range]),\n    1\n  )\n)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2131 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 -\n  avg(\n    clamp_max(\n      avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"sidekiq\"}[$__range]),\n      1\n    )\n  )\n) * $__range_ms\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2131 },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"sidekiq\"}[1d]),\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Sidekiq Background Jobs: SLA Trends ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2131 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"sidekiq\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2136 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"internal-api\"}[$__range]),\n    1\n  )\n)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2136 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  1 -\n  avg(\n    clamp_max(\n      avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"internal-api\"}[$__range]),\n      1\n    )\n  )\n) * $__range_ms\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2136 },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"internal-api\"}[1d]),\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "GitLab Internal API: SLA Trends ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2136 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"main\",type=\"internal-api\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "GitLab SLA Dashboard Explainer",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3001 },
   "content": "This dashboard shows the SLA trends for each of the _primary_ services in the GitLab fleet (\"primary\" services are those which are directly user-facing).\n\nRead more details on our [SLA policy is defined in the handbook](https://about.gitlab.com/handbook/engineering/monitoring/).\n\n* For each service we measure two key metrics/SLIs (Service Level Indicators): error-rate and apdex score\n* For each service, for each SLI, we have an SLO target\n  * For error-rate, the SLI should remain _below_ the SLO\n  * For apdex score, the SLI should remain _above_ the SLO\n* The SLA for each service is the percentage of time that the _both_ SLOs are being met\n* The SLA for GitLab.com is the average SLO across each primary service\n\n_To see instanteous SLI values for these services, visit the [`general-public-splashscreen`](d/general-public-splashscreen) dashboard._\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}