{
 "title": "General Triage",
 "tags": [ "general triage" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_ds", "query": "prometheus" },
   { "name": "environment", "query": "label_values(up, environment)" },
   {
    "name": "type",
    "query": "label_values(gitlab_service_availability:ratio{environment=\"$environment\"}, type)"
   }
  ]
 },
 "panels": [
  { "title": "Service Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 0, "y": 1 },
   "repeat": "type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"}[$__interval])) by (alertstate)"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 2.4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"}[$__interval])) by (alertstate)"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 4.8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"}[$__interval])) by (alertstate)"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 7.199999999999999, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"}[$__interval])) by (alertstate)"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 9.6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"}[$__interval])) by (alertstate)"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"}[$__interval])) by (alertstate)"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 14.4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"}[$__interval])) by (alertstate)"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 16.8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"}[$__interval])) by (alertstate)"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 19.2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"}[$__interval])) by (alertstate)"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 21.599999999999998, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(ALERTS{environment=\"$environment\", type=\"$type\", alertstate=\"firing\"}[$__interval])) by (alertstate)"
    }
   ]
  },
  { "title": "Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 0, "y": 5 },
   "repeat": "type",
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 2.4, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 4.8, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 7.199999999999999, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 9.6, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 12, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 14.4, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 16.8, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 19.2, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "$type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2.4, "x": 21.599999999999998, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\"}[$__interval]))"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Service Availability",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability" }
   ],
   "targets": [
    {
     "expr": "min(min_over_time(gitlab_service_availability:ratio{environment=\"$environment\"}[$__interval])) by (tier, type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }} service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Ops Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Service Operation Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops", "label": "Operations per Second (log10)" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(gitlab_service_ops:rate{environment=\"$environment\"}[$__interval])) by (tier, type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }} service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Apdex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Service Apdex Scores",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex Score" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_apdex:ratio{environment=\"$environment\"}[$__interval])) by (tier, type) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }} service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Service Error Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ops", "label": "Errors per Minute" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(gitlab_service_errors:rate{environment=\"$environment\"}[$__interval])) by (tier, type) * 60",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ type }} service",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}