{
 "title": "general: Service Platform Metrics - Stages",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/577548276 at Tue Jun  2 15:09:21 UTC 2020",
 "tags": [
  "managed",
  "general",
  "general"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "type",
    "query": "label_values(gitlab_service_ops:rate{environment=\"$environment\"}, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"$type\", stage!=\"\"}[$__interval]\n  )\n) by (stage)\n",
     "legendFormat": "{{ stage }} stage"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"$type\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"$type\"})\n",
     "legendFormat": "SLO"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"$type\", stage!=\"\"}[$__interval]\n  )\n) by (stage)\n",
     "legendFormat": "{{ stage }} stage"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"$type\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"$type\"})\n",
     "legendFormat": "SLO"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"$type\", stage!=\"\"}[$__interval]\n  )\n) by (stage)\n",
     "legendFormat": "{{ stage }} stage"
    }
   ]
  }
 ]
}