{
 "title": "general: Feature Category Error Budgets",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/538737415 at Tue May  5 12:16:00 UTC 2020",
 "tags": [
  "managed",
  "general",
  "feature_category"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Apdex by Feature Category",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(\n  clamp_max(\n    sum by (feature_category) (\n      avg_over_time(gitlab_background_jobs:execution:apdex:ratio_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      *\n      avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n    )\n    /\n      (\n      sum by(feature_category) (\n        avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      )\n    ) > 0,\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Error Rate by Feature Category",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sort(\n  clamp_max(\n    sum by (feature_category) (\n      avg_over_time(gitlab_background_jobs:execution:error:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n    )\n    /\n      (\n      sum by(feature_category) (\n        avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      ) > 0\n    ),\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Apdex by Queue",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sort_desc(\n  clamp_max(\n    sum by (queue, feature_category) (\n      avg_over_time(gitlab_background_jobs:execution:apdex:ratio_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      *\n      avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n    )\n    /\n      (\n      sum by(queue, feature_category) (\n        avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      )\n    ) > 0,\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Error Rate by Queue",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sort(\n  clamp_max(\n    sum by (queue, feature_category) (\n      avg_over_time(gitlab_background_jobs:execution:error:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n    )\n    /\n    (\n      sum by(queue, feature_category) (\n        avg_over_time(gitlab_background_jobs:execution:ops:rate_6h{environment=\"$environment\", env=\"$environment\"}[$__range])\n      )\n    ) > 0,\n    1\n  )\n)\n"
    }
   ]
  }
 ]
}