{
 "title": "general: Rails Endpoints Violations",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4322942381 at Mon May 22 06:38:11 UTC 2023",
 "tags": [
  "managed",
  "general"
 ],
 "time": { "from": "now-7d/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "product_stage",
    "query": "label_values(gitlab:feature_category:stage_group:mapping{monitor=\"global\"}, product_stage)"
   },
   {
    "name": "stage_group",
    "query": "label_values(gitlab:feature_category:stage_group:mapping{monitor=\"global\", product_stage=~\"$product_stage\"}, stage_group)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rails Request Availability",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "Rails Request Apdex",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      sum_over_time(\n        gitlab:component:stage_group:execution:apdex:success:rate_1h{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      sum_over_time(\n        gitlab:component:stage_group:execution:apdex:weight:score_1h{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "Rails Request Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",product_stage=~\"$product_stage\",stage=\"$stage\",stage_group=~\"$stage_group\"}[$__range]\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "Apdex by endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Endpoints",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 201 },
     "targets": [
      {
       "expr": "ceil(\n  (\n    sum by(endpoint_id, feature_category, request_urgency) (\n      sum_over_time(application_sli_aggregation:rails_request:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n    )\n    * on (feature_category) group_left(stage_group) gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}\n  ) * 60\n)\n"
      },
      {
       "expr": "clamp_max(\n  sum by(endpoint_id, feature_category, request_urgency) (\n    (sum_over_time(application_sli_aggregation:rails_request:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range]) > 0)\n    * on (feature_category) group_left(stage_group) gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}\n  )\n  /\n  sum by(endpoint_id, feature_category, request_urgency) (\n    (sum_over_time(application_sli_aggregation:rails_request:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range]) > 0)\n    * on (feature_category) group_left(stage_group) gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}\n  )\n, 1\n)\n"
      },
      {
       "expr": "clamp_max(\n  sum by(endpoint_id, feature_category, request_urgency) (\n    sum_over_time(application_sli_aggregation:rails_request:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n    * on (feature_category) group_left(stage_group) gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}\n  )\n  /\n  sum by(endpoint_id, feature_category, request_urgency) (\n    sum_over_time(application_sli_aggregation:rails_request:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n    * on (feature_category) group_left(stage_group) gitlab:feature_category:stage_group:mapping{monitor=\"global\",product_stage=~\"$product_stage\",stage_group=~\"$stage_group\"}\n  )\n, 1\n)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}