{
 "title": "general: Capacity Planning",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/799985141 at Mon Oct 19 21:07:53 UTC 2020",
 "tags": [
  "managed",
  "general",
  "general"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Currently Saturated Resources",
   "type": "table",
   "description": "Lists saturated resources that are breaching their soft SLO thresholds at this instant",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(\n  max by (type, stage, component) (\n  clamp_max(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type!=\"\"}\n    ,\n    1\n  ) >= on(component, monitor, env, cluster) group_left slo:max:soft:gitlab_component_saturation:ratio\n)\n\n)\n* on(component) group_left(alert_dashboard, severity)\n(\n  absent(fake_dne{component=\"cgroup_memory\", alert_dashboard=\"sat_cgroup_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"cpu\", alert_dashboard=\"sat_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_inodes\", alert_dashboard=\"sat_disk_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_space\", alert_dashboard=\"sat_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_iops\", alert_dashboard=\"sat_disk_sus_read_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_throughput\", alert_dashboard=\"sat_disk_sus_read_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_iops\", alert_dashboard=\"sat_disk_sus_write_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_throughput\", alert_dashboard=\"sat_disk_sus_write_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_cpu\", alert_dashboard=\"sat_elastic_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_disk_space\", alert_dashboard=\"sat_elastic_disk_space\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_jvm_heap_memory\", alert_dashboard=\"sat_elastic_jvm_heap_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_cpu\", alert_dashboard=\"sat_elastic_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_disk_space\", alert_dashboard=\"sat_elastic_node_disk_space\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_thread_pools\", alert_dashboard=\"sat_elastic_thread_pools\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"go_memory\", alert_dashboard=\"sat_go_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_hpa_instances\", alert_dashboard=\"sat_kube_hpa_instances\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_disk_space\", alert_dashboard=\"sat_kube_pvc_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_inodes\", alert_dashboard=\"sat_kube_pvc_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"memory\", alert_dashboard=\"sat_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"nf_conntrack_entries\", alert_dashboard=\"sat_conntrack\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"open_fds\", alert_dashboard=\"sat_open_fds\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_primary\", alert_dashboard=\"sat_active_db_connections_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_replica\", alert_dashboard=\"sat_active_db_connections_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_async_primary_pool\", alert_dashboard=\"sat_pgbouncer_async_pool_primary\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"pgbouncer_single_core\", alert_dashboard=\"sat_pgbouncer_single_core\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_primary_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_replica_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"praefect_cloudsql_cpu\", alert_dashboard=\"sat_praefect_cloudsql_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"private_runners\", alert_dashboard=\"sat_private_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"rails_db_connection_pool\", alert_dashboard=\"sat_rails_db_connection_pool\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"redis_clients\", alert_dashboard=\"sat_redis_clients\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"redis_memory\", alert_dashboard=\"sat_redis_memory\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"redis_primary_cpu\", alert_dashboard=\"sat_redis_primary_cpu\", severity=\"s1\"})\nor\nabsent(fake_dne{component=\"redis_secondary_cpu\", alert_dashboard=\"sat_redis_secondary_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"shard_cpu\", alert_dashboard=\"sat_shard_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"shared_runners\", alert_dashboard=\"sat_shared_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"shared_runners_gitlab\", alert_dashboard=\"sat_shared_runners_gitlab\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"sidekiq_shard_workers\", alert_dashboard=\"sat_sidekiq_shard_workers\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_cpu\", alert_dashboard=\"sat_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_puma_workers\", alert_dashboard=\"sat_single_node_puma_workers\", severity=\"s2\"})\n)\n"
    }
   ]
  },
  {
   "title": "Resources Currently at Risk of being Saturated",
   "type": "table",
   "description": "Lists saturated resources that, given their current value and weekly variance, have a high probability of breaching their soft thresholds limits within the next few hours",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "(\n  sort_desc(\n  max by (type, stage, component) (\n    clamp_max(\n      gitlab_component_saturation:ratio:avg_over_time_1w{\n        environment=\"$environment\",\n        type!=\"\"\n      } +\n      2 *\n        gitlab_component_saturation:ratio:stddev_over_time_1w{\n          environment=\"$environment\",\n          type!=\"\"\n        }\n      , 1\n    )\n    >= on(component, monitor, env, cluster) group_left slo:max:soft:gitlab_component_saturation:ratio\n  )\n)\n\n)\n* on(component) group_left(alert_dashboard, severity)\n(\n  absent(fake_dne{component=\"cgroup_memory\", alert_dashboard=\"sat_cgroup_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"cpu\", alert_dashboard=\"sat_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_inodes\", alert_dashboard=\"sat_disk_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_space\", alert_dashboard=\"sat_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_iops\", alert_dashboard=\"sat_disk_sus_read_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_throughput\", alert_dashboard=\"sat_disk_sus_read_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_iops\", alert_dashboard=\"sat_disk_sus_write_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_throughput\", alert_dashboard=\"sat_disk_sus_write_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_cpu\", alert_dashboard=\"sat_elastic_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_disk_space\", alert_dashboard=\"sat_elastic_disk_space\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_jvm_heap_memory\", alert_dashboard=\"sat_elastic_jvm_heap_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_cpu\", alert_dashboard=\"sat_elastic_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_disk_space\", alert_dashboard=\"sat_elastic_node_disk_space\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_thread_pools\", alert_dashboard=\"sat_elastic_thread_pools\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"go_memory\", alert_dashboard=\"sat_go_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_hpa_instances\", alert_dashboard=\"sat_kube_hpa_instances\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_disk_space\", alert_dashboard=\"sat_kube_pvc_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_inodes\", alert_dashboard=\"sat_kube_pvc_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"memory\", alert_dashboard=\"sat_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"nf_conntrack_entries\", alert_dashboard=\"sat_conntrack\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"open_fds\", alert_dashboard=\"sat_open_fds\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_primary\", alert_dashboard=\"sat_active_db_connections_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_replica\", alert_dashboard=\"sat_active_db_connections_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_async_primary_pool\", alert_dashboard=\"sat_pgbouncer_async_pool_primary\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"pgbouncer_single_core\", alert_dashboard=\"sat_pgbouncer_single_core\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_primary_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_replica_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"praefect_cloudsql_cpu\", alert_dashboard=\"sat_praefect_cloudsql_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"private_runners\", alert_dashboard=\"sat_private_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"rails_db_connection_pool\", alert_dashboard=\"sat_rails_db_connection_pool\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"redis_clients\", alert_dashboard=\"sat_redis_clients\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"redis_memory\", alert_dashboard=\"sat_redis_memory\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"redis_primary_cpu\", alert_dashboard=\"sat_redis_primary_cpu\", severity=\"s1\"})\nor\nabsent(fake_dne{component=\"redis_secondary_cpu\", alert_dashboard=\"sat_redis_secondary_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"shard_cpu\", alert_dashboard=\"sat_shard_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"shared_runners\", alert_dashboard=\"sat_shared_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"shared_runners_gitlab\", alert_dashboard=\"sat_shared_runners_gitlab\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"sidekiq_shard_workers\", alert_dashboard=\"sat_sidekiq_shard_workers\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_cpu\", alert_dashboard=\"sat_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_puma_workers\", alert_dashboard=\"sat_single_node_puma_workers\", severity=\"s2\"})\n)\n"
    }
   ]
  },
  {
   "title": "Resources Forecasted to be at Risk of Saturation in 14d",
   "type": "table",
   "description": "Lists saturated resources that, given their growth rate over the the past week, and their weekly variance, are likely to breach their soft thresholds limits in the next 14d",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "(\n  sort_desc(\n  max by (type, stage, component) (\n    clamp_max(\n      gitlab_component_saturation:ratio:predict_linear_2w{\n        environment=\"$environment\",\n        type!=\"\"\n      } +\n      2 *\n        gitlab_component_saturation:ratio:stddev_over_time_1w{\n          environment=\"$environment\",\n          type!=\"\"\n        }\n    , 1\n    )\n    >= on(component, monitor, env, cluster) group_left slo:max:soft:gitlab_component_saturation:ratio\n  )\n)\n\n)\n* on(component) group_left(alert_dashboard, severity)\n(\n  absent(fake_dne{component=\"cgroup_memory\", alert_dashboard=\"sat_cgroup_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"cpu\", alert_dashboard=\"sat_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_inodes\", alert_dashboard=\"sat_disk_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_space\", alert_dashboard=\"sat_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_iops\", alert_dashboard=\"sat_disk_sus_read_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_throughput\", alert_dashboard=\"sat_disk_sus_read_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_iops\", alert_dashboard=\"sat_disk_sus_write_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_throughput\", alert_dashboard=\"sat_disk_sus_write_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_cpu\", alert_dashboard=\"sat_elastic_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_disk_space\", alert_dashboard=\"sat_elastic_disk_space\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_jvm_heap_memory\", alert_dashboard=\"sat_elastic_jvm_heap_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_cpu\", alert_dashboard=\"sat_elastic_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_disk_space\", alert_dashboard=\"sat_elastic_node_disk_space\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_thread_pools\", alert_dashboard=\"sat_elastic_thread_pools\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"go_memory\", alert_dashboard=\"sat_go_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_hpa_instances\", alert_dashboard=\"sat_kube_hpa_instances\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_disk_space\", alert_dashboard=\"sat_kube_pvc_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_inodes\", alert_dashboard=\"sat_kube_pvc_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"memory\", alert_dashboard=\"sat_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"nf_conntrack_entries\", alert_dashboard=\"sat_conntrack\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"open_fds\", alert_dashboard=\"sat_open_fds\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_primary\", alert_dashboard=\"sat_active_db_connections_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_replica\", alert_dashboard=\"sat_active_db_connections_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_async_primary_pool\", alert_dashboard=\"sat_pgbouncer_async_pool_primary\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"pgbouncer_single_core\", alert_dashboard=\"sat_pgbouncer_single_core\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_primary_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_replica_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"praefect_cloudsql_cpu\", alert_dashboard=\"sat_praefect_cloudsql_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"private_runners\", alert_dashboard=\"sat_private_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"rails_db_connection_pool\", alert_dashboard=\"sat_rails_db_connection_pool\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"redis_clients\", alert_dashboard=\"sat_redis_clients\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"redis_memory\", alert_dashboard=\"sat_redis_memory\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"redis_primary_cpu\", alert_dashboard=\"sat_redis_primary_cpu\", severity=\"s1\"})\nor\nabsent(fake_dne{component=\"redis_secondary_cpu\", alert_dashboard=\"sat_redis_secondary_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"shard_cpu\", alert_dashboard=\"sat_shard_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"shared_runners\", alert_dashboard=\"sat_shared_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"shared_runners_gitlab\", alert_dashboard=\"sat_shared_runners_gitlab\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"sidekiq_shard_workers\", alert_dashboard=\"sat_sidekiq_shard_workers\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_cpu\", alert_dashboard=\"sat_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_puma_workers\", alert_dashboard=\"sat_single_node_puma_workers\", severity=\"s2\"})\n)\n"
    }
   ]
  }
 ]
}