{
 "title": "general: Incident Budget Explorer",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/3951494137 at Thu Mar 16 23:41:35 UTC 2023",
 "tags": [
  "managed",
  "general",
  "general",
  "slas",
  "service-levels"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "sla_type",
    "query": "label_values(sla:gitlab:ratio, sla_type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall GitLab.com Availability Points Spent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total GitLab.com Availability Basis Points Spent",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - avg(\n  clamp_max(\n    avg_over_time(sla:gitlab:ratio{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",sla_type=\"$sla_type\",stage=\"$stage\"}[$__range]),\n    1\n  )\n)\n) * ($__range_ms / (86400000 * 30.5)) * 100 * 100\n"
    }
   ]
  },
  {
   "title": "Monthly Availability Basis Points Budget",
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - sla:gitlab:target{monitor=\"global\"}) * 100 * 100\n"
    }
   ]
  },
  {
   "title": "Availability - gitlab.com",
   "type": "graph",
   "description": "Rolling average SLO adherence across all primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(sla:gitlab:ratio{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",sla_type=\"$sla_type\",stage=\"$stage\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "gitlab.com SLA"
    }
   ]
  },
  { "title": "Primary Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2101 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"web\"}[$__range]),\n    1\n  )\n)\n) * ($__range_ms / (86400000 * 30.5)) * 100 * 100\n",
     "legendFormat": "GitLab.com Web: Availability Basis Points Spent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 2101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "5", "legendFormat": "Overall Weight" }
   ]
  },
  {
   "title": "GitLab.com Web: Availability ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 2101 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"web\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2106 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"git\"}[$__range]),\n    1\n  )\n)\n) * ($__range_ms / (86400000 * 30.5)) * 100 * 100\n",
     "legendFormat": "Git Access: Availability Basis Points Spent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 2106 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "5", "legendFormat": "Overall Weight" }
   ]
  },
  {
   "title": "Git Access: Availability ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 2106 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"git\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2111 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"api\"}[$__range]),\n    1\n  )\n)\n) * ($__range_ms / (86400000 * 30.5)) * 100 * 100\n",
     "legendFormat": "GitLab API: Availability Basis Points Spent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 2111 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "5", "legendFormat": "Overall Weight" }
   ]
  },
  {
   "title": "GitLab API: Availability ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 2111 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"api\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2116 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"ci-runners\"}[$__range]),\n    1\n  )\n)\n) * ($__range_ms / (86400000 * 30.5)) * 100 * 100\n",
     "legendFormat": "CI Runners: Availability Basis Points Spent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 2116 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Overall Weight" }
   ]
  },
  {
   "title": "CI Runners: Availability ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 2116 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"ci-runners\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2121 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"registry\"}[$__range]),\n    1\n  )\n)\n) * ($__range_ms / (86400000 * 30.5)) * 100 * 100\n",
     "legendFormat": "Container Registry: Availability Basis Points Spent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 2121 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "Overall Weight" }
   ]
  },
  {
   "title": "Container Registry: Availability ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 2121 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"registry\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2126 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"web-pages\"}[$__range]),\n    1\n  )\n)\n) * ($__range_ms / (86400000 * 30.5)) * 100 * 100\n",
     "legendFormat": "GitLab Pages: Availability Basis Points Spent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 2126 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Overall Weight" }
   ]
  },
  {
   "title": "GitLab Pages: Availability ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 2126 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"web-pages\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Availability",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2131 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"internal-api\"}[$__range]),\n    1\n  )\n)\n) * ($__range_ms / (86400000 * 30.5)) * 100 * 100\n",
     "legendFormat": "GitLab Internal API: Availability Basis Points Spent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 2131 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0", "legendFormat": "Overall Weight" }
   ]
  },
  {
   "title": "GitLab Internal API: Availability ",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 2131 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\",environment=\"$environment\",monitor=~\"global|\",stage=\"$stage\",type=\"internal-api\"}[$__interval]),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}