{
 "title": "general: Incident Metrics",
 "description": "Manual",
 "time": { "from": "now-7d/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  { "title": "Headline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Weighted Availability Score - GitLab.com",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(\n      sla:gitlab:ratio{env=~\"ops|$environment\", environment=\"$environment\", stage=\"main\", monitor=~\"global|\"}[$__range]\n    ),\n    1\n  )\n)\n"
    }
   ]
  },
  {
   "title": "GitLab SLA Dashboard Explainer",
   "type": "text",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "content": "This dashboard shows the SLA trends for each of the _primary_ services in the GitLab fleet (\"primary\" services are those which are directly user-facing).\n\n* For each service we measure two key metrics/SLIs (Service Level Indicators): error-rate and apdex score\n* For each service, for each SLI, we have an SLO target\n  * For error-rate, the SLI should remain _below_ the SLO\n  * For apdex score, the SLI should remain _above_ the SLO\n* The SLA for each service is the percentage of time that the _both_ SLOs are being met\n* The SLA for GitLab.com is the average SLO across each primary service\n\n_To see instanteous SLI values for these services, visit the [`general-public-splashscreen`](d/general-public-splashscreen) dashboard._\n"
  },
  {
   "title": "Overall SLA over time period - gitlab.com",
   "type": "graph",
   "description": "Rolling average SLO adherence across all primary services. Higher is better.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  clamp_max(\n    avg_over_time(\n      sla:gitlab:ratio{env=~\"ops|$environment\", environment=\"$environment\", stage=\"main\", monitor=~\"global|\"}[$__interval]\n    ),\n    1\n  )\n)\n,1),0)\n",
     "legendFormat": "gitlab.com SLA"
    }
   ]
  },
  {
   "title": "SLA Trends - Per Primary Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Primary Services Average Availability for Period",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg(\n  clamp_max(\n    avg_over_time(slo_observation_status{env=~\"ops|$environment\", environment=\"$environment\", stage=\"main\", type=~\"api|web|git|registry\"}[$__range]),\n    1\n  )\n) by (type)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "SLA Trends - Primary Services",
   "type": "graph",
   "description": "Rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(\n  avg_over_time(slo_observation_status{env=~\"ops|$environment\", environment=\"$environment\", stage=\"main\", type=~\"api|web|git|registry\"}[$__interval])\n) by (type)\n,1),0)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./general/slas.dashboard.jsonnet)\n"
  }
 ]
}