{
 "title": "Geo event activity",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Geo event activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(delta(geo_cursor_last_event_id[$__interval]))",
     "legendFormat": "Total events"
    },
    {
     "expr": "max(delta(geo_repository_created_max_id[$__interval]))",
     "legendFormat": "Repository created"
    },
    {
     "expr": "max(increase(geo_repositories_synced[$__interval]))",
     "legendFormat": "Repository updated"
    },
    {
     "expr": "max(delta(geo_repository_deleted_max_id[$__interval]))",
     "legendFormat": "Repository deleted"
    }
   ]
  },
  {
   "title": "Sidekiq Jobs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\nrate(sidekiq_jobs_completion_seconds_count{feature_category=~'(geo_replication|disaster_recovery)'}[$__interval])\n)",
     "legendFormat": "{{worker]}}"
    }
   ]
  },
  {
   "title": "resident memory usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" },
    {
     "expr": "sum(process_resident_memory_bytes)",
     "legendFormat": "total resident memory usage"
    }
   ]
  },
  { "title": "Repository", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Repositories Out of Sync",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(geo_repositories - geo_repositories_synced - geo_repositories_failed)",
     "legendFormat": "Out of sync"
    }
   ]
  },
  {
   "title": "Sync Failures",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min(geo_repositories_failed)", "legendFormat": "Sync failures" }
   ]
  },
  {
   "title": "Verification Failures (Primary)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geo_repositories_verification_failed",
     "legendFormat": "Sync failures"
    }
   ]
  },
  {
   "title": "Verification Failures (Secondaries)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "geo_repositories_checksum_failed",
     "legendFormat": "Sync failures"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geo_repositories", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Repository Sync Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(geo_repositories_synced) by (url)",
     "legendFormat": "Repositories synced ({{url}})"
    },
    {
     "expr": "max(geo_repositories_failed) by (url)",
     "legendFormat": "Repositories failed ({{url}})"
    },
    { "expr": "max(geo_repositories) by (url)", "legendFormat": "Total repositories ({{url}})" }
   ]
  },
  {
   "title": "Repository verification (primary)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(geo_repositories_checked - geo_repositories_checked_failed)",
     "legendFormat": "Verified"
    },
    {
     "expr": "max(geo_repositories_checked_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "max(geo_repositories - geo_repositories_checked)",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Repository verification (secondary)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(geo_repositories_checked - geo_repositories_checked_failed) by (url)",
     "legendFormat": "Verified ({{url}})"
    },
    {
     "expr": "max(geo_repositories_checked_failed) by (url)",
     "legendFormat": "Failed ({{url}})"
    },
    {
     "expr": "max(geo_repositories - geo_repositories_checked) by (url)",
     "legendFormat": "Pending ({{url}})"
    }
   ]
  }
 ]
}