{
 "title": "Geo Primary insights",
 "description": "Monitor Geo metrics on the primary",
 "tags": [
  "geo",
  "unmanaged"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "app_prometheus", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Geo event activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(delta(geo_event_log_max_id[$interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(delta(geo_repository_created_max_id[$interval]))",
     "legendFormat": "Repository created"
    },
    {
     "expr": "max(delta(geo_repository_updated_max_id[$interval]))",
     "legendFormat": "Repository updated"
    },
    {
     "expr": "max(delta(geo_repository_deleted_max_id[$interval]))",
     "legendFormat": "Repository deleted"
    },
    {
     "expr": "max(delta(geo_repository_renamed_max_id[$interval]))",
     "legendFormat": "Repository renamed"
    },
    {
     "expr": "max(delta(geo_repositories_changed_max_id[$interval]))",
     "legendFormat": "Repository changed"
    },
    {
     "expr": "max(delta(geo_lfs_object_deleted_max_id[$interval]))",
     "legendFormat": "LFS objects deleted"
    },
    {
     "expr": "max(delta(geo_job_artifact_deleted_max_id[$interval]))",
     "legendFormat": "Job Artifacts deleted"
    },
    {
     "expr": "max(delta(geo_hashed_storage_migrated_max_id[$interval]))",
     "legendFormat": "Hashed migrated repositories"
    },
    {
     "expr": "max(delta(geo_hashed_storage_attachments_max_id[$interval]))",
     "legendFormat": "Hashed migrated attachments"
    }
   ]
  },
  {
   "title": "Repository checking",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(geo_repositories_checked - geo_repositories_checked_failed)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Checked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(geo_repositories_checked_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": " max(geo_repositories - geo_repositories_checked)",
     "legendFormat": "Unchecked"
    }
   ]
  },
  {
   "title": "Repository checksumming",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(geo_repositories_checksummed - geo_repositories_checksum_failed)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Checked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max(geo_repositories_checksum_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": " max(geo_repositories - geo_repositories_checksummed)",
     "legendFormat": "Unchecked"
    }
   ]
  },
  {
   "title": "Wiki checksumming",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(geo_wikis_checksummed - geo_wikis_checksum_failed)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Checked",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expr": "max(geo_wikis_checksum_failed)", "legendFormat": "Failed" },
    {
     "expr": "max(geo_wikis - geo_wikis_checksummed)",
     "legendFormat": "Unchecked"
    }
   ]
  }
 ]
}