{
 "title": "Geo Secondary status",
 "tags": [
  "geo",
  "unmanaged"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "ops,gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "app_prometheus", "query": "prometheus" },
   {
    "name": "events_interval",
    "label": "Events interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(geo_repositories_failed) by (environment)",
     "legendFormat": "Repositories"
    },
    {
     "expr": "min(geo_wikis_failed) by (environment)",
     "legendFormat": "Wikis"
    },
    {
     "expr": "min(geo_lfs_objects_failed) by (environment)",
     "legendFormat": "LFS objects"
    },
    {
     "expr": "min(geo_attachments_failed) by (environment)",
     "legendFormat": "Attachments"
    },
    {
     "expr": "min(geo_job_artifacts_failed) by (environment)",
     "legendFormat": "Job Artifacts"
    },
    {
     "expr": "min(geo_container_repositories_failed) by (environment)",
     "legendFormat": "Container repositories"
    },
    {
     "expr": "min(geo_design_repositories_failed) by (environment)",
     "legendFormat": "Designs"
    }
   ]
  },
  {
   "title": "Out of Sync",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(geo_repositories - geo_repositories_synced - geo_repositories_failed)",
     "legendFormat": "Repositories"
    },
    {
     "expr": "max(geo_wikis - geo_wikis_synced - geo_wikis_failed)",
     "legendFormat": "Wikis"
    },
    {
     "expr": "max(geo_lfs_objects - geo_lfs_objects_synced - geo_lfs_objects_failed)",
     "legendFormat": "LFS objects"
    },
    {
     "expr": "max(geo_attachments - geo_attachments_synced - geo_attachments_failed)",
     "legendFormat": "Attachments"
    },
    {
     "expr": "max(geo_job_artifacts - geo_job_artifacts_synced - geo_job_artifacts_failed)",
     "legendFormat": "Job Artifacts"
    },
    {
     "expr": "max(geo_container_repositories - geo_container_repositories_synced - geo_container_repositories_failed)",
     "legendFormat": "Container repositories"
    },
    {
     "expr": "max(geo_design_repositories - geo_design_repositories_synced - geo_design_repositories_failed)",
     "legendFormat": "Designs"
    }
   ]
  },
  {
   "title": "Repository Failures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "min(geo_repositories_failed) by (environment)"
    }
   ]
  },
  {
   "title": "Repositories Out of Sync",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "min(geo_repositories - geo_repositories_synced - geo_repositories_failed)"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(geo_repositories_synced) by (environment)",
     "legendFormat": "Synced"
    },
    {
     "expr": "min(geo_repositories_failed) by (environment)",
     "legendFormat": "Failed"
    },
    {
     "expr": "min(geo_repositories - geo_repositories_synced - geo_repositories_failed) by (environment)",
     "legendFormat": "Out of sync"
    }
   ]
  },
  {
   "title": "Wiki Failures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "min(geo_wikis_failed) by (environment)"
    }
   ]
  },
  {
   "title": "Wikis Out of Sync",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 13 },
   "targets": [
    {
     "expr": "min(geo_wikis - geo_wikis_synced - geo_wikis_failed)"
    }
   ]
  },
  {
   "title": "Wikis",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(geo_wikis_synced) by (environment)",
     "legendFormat": "Synced"
    },
    {
     "expr": "min(geo_wikis_failed) by (environment)",
     "legendFormat": "Failed"
    },
    {
     "expr": "min(geo_wikis - geo_wikis_failed - geo_wikis_synced) by (environment)",
     "legendFormat": "Out of sync"
    }
   ]
  },
  {
   "title": "Attachment Sync Failures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "min(geo_attachments_failed)  by (environment)"
    }
   ]
  },
  {
   "title": "Attachments Out of Sync",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 19 },
   "targets": [
    {
     "expr": "max(geo_attachments - geo_attachments_synced - geo_attachments_failed)"
    }
   ]
  },
  {
   "title": "Attachments",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(geo_attachments_synced) by (environment)",
     "legendFormat": "Synced"
    },
    {
     "expr": "min(geo_attachments_failed) by (environment)",
     "legendFormat": "Failed"
    },
    {
     "expr": "min(geo_attachments - (geo_attachments_failed + geo_attachments_synced)) by (environment)",
     "legendFormat": "Out of sync"
    }
   ]
  },
  {
   "title": "LFS Object Failures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "min(geo_lfs_objects_failed) by (environment)"
    }
   ]
  },
  {
   "title": "LFS Objects Out of Sync",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 25 },
   "targets": [
    {
     "expr": "min(geo_lfs_objects - geo_lfs_objects_synced - geo_lfs_objects_failed)"
    }
   ]
  },
  {
   "title": "LFS objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(geo_lfs_objects_synced) by (environment)",
     "legendFormat": "Synced"
    },
    {
     "expr": "min(geo_lfs_objects_failed) by (environment)",
     "legendFormat": "Failed"
    },
    {
     "expr": "min(geo_lfs_objects - geo_lfs_objects_failed - geo_lfs_objects_synced) by (environment)",
     "legendFormat": "Out of sync"
    }
   ]
  },
  {
   "title": "Job Artifact Failures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "min(geo_job_artifacts_failed) by (environment)"
    }
   ]
  },
  {
   "title": "Job Artifacts Out of Sync",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 31 },
   "targets": [
    {
     "expr": "min(geo_job_artifacts - geo_job_artifacts_synced - geo_job_artifacts_failed)"
    }
   ]
  },
  {
   "title": "Job artifacts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(geo_job_artifacts_synced) by (environment)",
     "legendFormat": "Synced"
    },
    {
     "expr": "min(geo_job_artifacts_failed) by (environment)",
     "legendFormat": "Failed"
    },
    {
     "expr": "min(geo_job_artifacts - (geo_job_artifacts_failed + geo_job_artifacts_synced)) by (environment)",
     "legendFormat": "Out of sync"
    }
   ]
  },
  {
   "title": "Container repository Failures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "min(geo_container_repositories_failed) by (environment)"
    }
   ]
  },
  {
   "title": "Container repositories Out of Sync",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 37 },
   "targets": [
    {
     "expr": "min(geo_container_repositories - geo_container_repositories_synced - geo_container_repositories_failed)"
    }
   ]
  },
  {
   "title": "Container repositories",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(geo_container_repositories_synced) by (environment)",
     "legendFormat": "Synced"
    },
    {
     "expr": "min(geo_container_repositories_failed) by (environment)",
     "legendFormat": "Failed"
    },
    {
     "expr": "min(geo_container_repositories - (geo_container_repositories_failed + geo_container_repositories_synced)) by (environment)",
     "legendFormat": "Out of sync"
    }
   ]
  },
  {
   "title": "Design Failures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "min(geo_design_repositories_failed) by (environment)"
    }
   ]
  },
  {
   "title": "Designs Out of Sync",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 43 },
   "targets": [
    {
     "expr": "min(geo_design_repositories - geo_design_repositories_synced - geo_design_repositories_failed)"
    }
   ]
  },
  {
   "title": "Design",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(geo_design_repositories_synced) by (environment)",
     "legendFormat": "Synced"
    },
    {
     "expr": "min(geo_design_repositories_failed) by (environment)",
     "legendFormat": "Failed"
    },
    {
     "expr": "min(geo_design_repositories - (geo_design_repositories_failed + geo_design_repositories_synced)) by (environment)",
     "legendFormat": "Out of sync"
    }
   ]
  },
  {
   "title": "Geo db replication lag",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "max(geo_db_replication_lag_seconds) by (environment)"
    }
   ]
  },
  {
   "title": "DB Replication Lag",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 4, "y": 49 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "max(geo_db_replication_lag_seconds)",
     "legendFormat": "DB replication lag"
    }
   ]
  },
  {
   "title": "Geo event log lag",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "min(geo_last_event_timestamp{name=\"gstg-gitlab-geo\"} - geo_cursor_last_event_timestamp{name=\"gstg-gitlab-geo\"})"
    }
   ]
  },
  {
   "title": "Geo event count lag",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 49 },
   "targets": [
    {
     "expr": "min(geo_last_event_id - geo_cursor_last_event_id)"
    }
   ]
  },
  {
   "title": "Repository Verification",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "min(geo_repositories_verified)", "legendFormat": "Verified" },
    {
     "expr": "min(geo_repositories_verification_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "min(geo_repositories_checksum_mismatch)",
     "legendFormat": "Checksum mismatch"
    },
    {
     "expr": "min(geo_repositories - geo_repositories_verified)",
     "legendFormat": "Unverified"
    }
   ]
  },
  {
   "title": "Wiki Verification",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "min(geo_wikis_verified)", "legendFormat": "Verified" },
    {
     "expr": "min(geo_wikis_verification_failed)",
     "legendFormat": "Failed"
    },
    {
     "expr": "min(geo_wikis_checksum_mismatch)",
     "legendFormat": "Checksum mismatch"
    },
    {
     "expr": "min(geo_wikis - geo_wikis_verified)",
     "legendFormat": "Unverified"
    }
   ]
  }
 ]
}