{
 "title": "Git Protocol Versions",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitaly_git_protocol_requests_total{grpc_service=\"gitaly.SmartHTTPService\"}[$__interval])) by (grpc_method,git_protocol)",
     "legendFormat": "Git {{git_protocol}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "HTTP v2 %",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(gitaly_git_protocol_requests_total{grpc_service=\"gitaly.SmartHTTPService\",git_protocol=\"v2\"}[$__interval]))\n /\nsum(rate(gitaly_git_protocol_requests_total{grpc_service=\"gitaly.SmartHTTPService\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "SSH Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitaly_git_protocol_requests_total{grpc_service=\"gitaly.SSHService\"}[$__interval])) by (grpc_method,git_protocol)",
     "legendFormat": "Git {{git_protocol}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "SSH v2 %",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(gitaly_git_protocol_requests_total{grpc_service=\"gitaly.SSHService\",git_protocol=\"v2\"}[$__interval]))\n /\nsum(rate(gitaly_git_protocol_requests_total{grpc_service=\"gitaly.SSHService\"}[$__interval]))"
    }
   ]
  }
 ]
}