{
 "title": "Git storage over time",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Storage over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total storage",
   "type": "graph",
   "gridPos": { "h": 29, "w": 3, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  node_filesystem_size_bytes{environment=\"gprd\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\"}\n    -\n  node_filesystem_avail_bytes{environment=\"gprd\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\"}\n)",
     "legendFormat": "Total used"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{environment=\"gprd\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\"})",
     "legendFormat": "Total capacity"
    }
   ]
  },
  {
   "title": "Total used",
   "type": "graph",
   "gridPos": { "h": 29, "w": 5, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{environment=\"gprd\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\"}) / sum(node_filesystem_size_bytes{environment=\"gprd\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\"} + node_filesystem_avail_bytes{environment=\"gprd\", tier=\"stor\", type=\"gitaly\", device=\"/dev/sdb\"})) * 100",
     "legendFormat": "Percent used"
    },
    { "expr": "100", "legendFormat": "All" }
   ]
  },
  {
   "title": "Usage per shard",
   "type": "graph",
   "gridPos": { "h": 29, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{environment=\"gprd\", tier=\"stor\", type=\"gitaly\", fstype=~\"ext.|xfs\"} - node_filesystem_free_bytes{environment=\"gprd\", tier=\"stor\", type=\"gitaly\", fstype=~\"ext.|xfs\"}  ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}