{
 "title": "git: Kube Containers Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5204445736 at Mon Oct  2 13:49:59 UTC 2023",
 "tags": [
  "managed",
  "git",
  "git",
  "type:git",
  "kube",
  "kube detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  { "title": "git-https deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gitlab-workhorse container/git-https deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 gitlab-workhorse Container CPU"
    }
   ]
  },
  {
   "title": "gitlab-workhorse container/git-https deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p99 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p95 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p75 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p50 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p25 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p10 gitlab-workhorse Container Memory"
    }
   ]
  },
  {
   "title": "gitlab-workhorse container/git-https deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "gitlab-workhorse container/git-https deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"gitlab-workhorse\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "webservice container/git-https deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 webservice Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 webservice Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 webservice Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 webservice Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 webservice Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 webservice Container CPU"
    }
   ]
  },
  {
   "title": "webservice container/git-https deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p99 webservice Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p95 webservice Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p75 webservice Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p50 webservice Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p25 webservice Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p10 webservice Container Memory"
    }
   ]
  },
  {
   "title": "webservice container/git-https deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "webservice container/git-https deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"webservice\",deployment=\"git-https\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "gitlab-shell deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "gitlab-shell container/gitlab-shell deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 gitlab-shell Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 gitlab-shell Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 gitlab-shell Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 gitlab-shell Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 gitlab-shell Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 gitlab-shell Container CPU"
    }
   ]
  },
  {
   "title": "gitlab-shell container/gitlab-shell deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p99 gitlab-shell Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p95 gitlab-shell Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p75 gitlab-shell Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p50 gitlab-shell Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p25 gitlab-shell Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n }\n)\n",
     "legendFormat": "p10 gitlab-shell Container Memory"
    }
   ]
  },
  {
   "title": "gitlab-shell container/gitlab-shell deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "gitlab-shell container/gitlab-shell deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"gitlab-shell\",deployment=\"gitlab-shell\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"git\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}