{
 "title": "git: kube service containers overview",
 "description": "Uploaded by andrewn at Wed 25 Nov 2020 08:57:57 UTC",
 "tags": [
  "managed",
  "git",
  "git",
  "kube",
  "kube overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  { "title": "git-https deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gitlab-workhorse container CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-workhorse\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-workhorse\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-workhorse\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-workhorse\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-workhorse\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-workhorse\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 gitlab-workhorse Container CPU"
    }
   ]
  },
  {
   "title": "gitlab-workhorse container Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-workhorse\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p99 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-workhorse\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p95 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-workhorse\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p75 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-workhorse\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p50 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-workhorse\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p25 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-workhorse\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p10 gitlab-workhorse Container Memory"
    }
   ]
  },
  {
   "title": "webservice container CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"webservice\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 webservice Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"webservice\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 webservice Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"webservice\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 webservice Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"webservice\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 webservice Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"webservice\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 webservice Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"webservice\",\n    deployment=\"git-https\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 webservice Container CPU"
    }
   ]
  },
  {
   "title": "webservice container Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"webservice\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p99 webservice Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"webservice\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p95 webservice Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"webservice\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p75 webservice Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"webservice\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p50 webservice Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"webservice\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p25 webservice Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"webservice\",\n  deployment=\"git-https\"\n }\n)\n",
     "legendFormat": "p10 webservice Container Memory"
    }
   ]
  },
  { "title": "gitlab-shell deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "gitlab-shell container CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-shell\",\n    deployment=\"gitlab-shell\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 gitlab-shell Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-shell\",\n    deployment=\"gitlab-shell\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 gitlab-shell Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-shell\",\n    deployment=\"gitlab-shell\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 gitlab-shell Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-shell\",\n    deployment=\"gitlab-shell\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 gitlab-shell Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-shell\",\n    deployment=\"gitlab-shell\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 gitlab-shell Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    type=\"git\",\n    env=\"$environment\",\n    environment=\"$environment\",\n    stage=\"$stage\",\n    container=\"gitlab-shell\",\n    deployment=\"gitlab-shell\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 gitlab-shell Container CPU"
    }
   ]
  },
  {
   "title": "gitlab-shell container Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-shell\",\n  deployment=\"gitlab-shell\"\n }\n)\n",
     "legendFormat": "p99 gitlab-shell Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-shell\",\n  deployment=\"gitlab-shell\"\n }\n)\n",
     "legendFormat": "p95 gitlab-shell Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-shell\",\n  deployment=\"gitlab-shell\"\n }\n)\n",
     "legendFormat": "p75 gitlab-shell Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-shell\",\n  deployment=\"gitlab-shell\"\n }\n)\n",
     "legendFormat": "p50 gitlab-shell Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-shell\",\n  deployment=\"gitlab-shell\"\n }\n)\n",
     "legendFormat": "p25 gitlab-shell Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  type=\"git\",\n  env=\"$environment\",\n  environment=\"$environment\",\n  stage=\"$stage\",\n  container=\"gitlab-shell\",\n  deployment=\"gitlab-shell\"\n }\n)\n",
     "legendFormat": "p10 gitlab-shell Container Memory"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/git/kube.shared.jsonnet)\n"
  }
 ]
}