{
 "title": "Gitaly Hook Statistics",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg" },
   {
    "name": "method",
    "query": "PreReceiveHook,PostReceiveHook,UpdateHook,ReferenceTransactionHook"
   },
   {
    "name": "endpoint",
    "query": "allowed,pre-receive,post-receive"
   }
  ]
 },
 "panels": [
  {
   "title": "GitLab API: Allowed Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli:rails_request_apdex:success_total_rate5m{endpoint_id=\"POST /api/:version/internal/allowed\",env=\"gprd\",environment=\"gprd\",job=\"gitlab-rails\",stage=\"main\",type=\"api\"}\n)\n > 0",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{endpoint_id=\"POST /api/:version/internal/allowed\",env=\"gprd\",environment=\"gprd\",job=\"gitlab-rails\",stage=\"main\",type=\"api\"}\n  -\n  sli_aggregations:gitlab_sli:rails_request_apdex:success_total_rate5m{endpoint_id=\"POST /api/:version/internal/allowed\",env=\"gprd\",environment=\"gprd\",job=\"gitlab-rails\",stage=\"main\",type=\"api\"}\n\n)\n > 0",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "GitLab API Latency: $endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "repeat": "endpoint",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_gitlab_api_latency_seconds_bucket{environment=\"$environment\",endpoint=\"$endpoint\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitaly_gitlab_api_latency_seconds_bucket{environment=\"$environment\",endpoint=\"$endpoint\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Hook RPC Rate: $method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "repeat": "method",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:rate1m{job=\"gitaly\",environment=\"$environment\",grpc_method=\"$method\"} - sum(gitaly:grpc_server_handled_total:error_rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) without (grpc_code))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(gitaly:grpc_server_handled_total:error_rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Hook RPC Latency: $method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "repeat": "method",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) by (le)) * 1000",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) by (le)) * 1000",
     "legendFormat": "P95"
    }
   ]
  }
 ]
}