{
 "title": "Gitaly Rate Limiting",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Queued Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(gitaly_rate_limiting_in_progress{environment=\"gprd\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }} - {{ grpc_service }} ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Progress requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitaly_rate_limiting_in_progress) by (fqdn, grpc_service)",
     "legendFormat": "{{ fqdn }} - {{ grpc_service }}"
    }
   ]
  },
  {
   "title": "Median Mutex Acquisition Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(gitaly_rate_limiting_acquiring_seconds_bucket{environment=\"gprd\"}[1m])) WITHOUT (instance))\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "p50 - {{ fqdn }} - {{ grpc_method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_rate_limiting_acquiring_seconds_bucket{environment=\"gprd\"}[1m])) WITHOUT (instance))\n",
     "legendFormat": "p99 - {{ fqdn }} - {{ grpc_method }}"
    }
   ]
  }
 ]
}