{
 "title": "Gitaly Metrics - per host",
 "tags": [
  "Gitaly",
  "GitalyMain",
  "unmanaged"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fqdn",
    "query": "label_values(up{job=~\"gitaly.*\"}, fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Level (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{fqdn=\"$fqdn\", grpc_code=\"OK\"}[$__interval])) /\nsum(rate(grpc_server_handled_total{fqdn=\"$fqdn\"}[$__interval])) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Success %",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load 1min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{fqdn=\"$fqdn\"}\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "load1-{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_load5{fqdn=\"$fqdn\"}",
     "legendFormat": "load5-{{fqdn}}"
    },
    {
     "expr": "node_load15{fqdn=\"$fqdn\"}",
     "legendFormat": "load15-{{fqdn}}"
    },
    {
     "expr": "avg(instance:node_cpus:count{fqdn=\"$fqdn\"})",
     "legendFormat": "cpu_count"
    }
   ]
  },
  {
   "title": "Load 15 by CPU Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_load15{fqdn=\"$fqdn\"}) / avg(instance:node_cpus:count{fqdn=\"$fqdn\"})\n",
     "legendFormat": "load_15_per_cpu"
    }
   ]
  },
  {
   "title": "Disk IO *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_ms{fqdn=~\"$fqdn\",device=~\"sd.*\"}[$__interval])) without (device) / 1000\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total{fqdn=~\"$fqdn\",device=~\"sd.*\"}[$__interval])) without (device)",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "% IOWait *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\nsum(rate(node_cpu_seconds_total{mode=\"iowait\", fqdn=\"$fqdn\"}[5m])) / sum(rate(node_cpu_seconds_total{ fqdn=\"$fqdn\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "IOWait",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used System Total CPU %*",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\n1 - avg(rate(node_cpu_seconds_total{fqdn=\"$fqdn\",mode=\"idle\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Used System Total CPU %",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Context Switches *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_context_switches{fqdn=\"$fqdn\"}[$__interval])\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_context_switches_total{fqdn=\"$fqdn\"}[$__interval])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Forks Given *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_forks{fqdn=\"$fqdn\"}[$__interval])\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_forks_total{fqdn=\"$fqdn\"}[$__interval])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable{fqdn=\"$fqdn\"} / node_memory_MemTotal{fqdn=\"$fqdn\"}\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Available {{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_MemAvailable_bytes{fqdn=\"$fqdn\"} / node_memory_MemTotal_bytes{fqdn=\"$fqdn\"}",
     "legendFormat": "Available {{fqdn}}"
    },
    {
     "expr": "node_memory_Cached{fqdn=\"$fqdn\"} / node_memory_MemTotal{fqdn=\"$fqdn\"}",
     "legendFormat": "Cached {{fqdn}}"
    },
    {
     "expr": "node_memory_Cached_bytes{fqdn=\"$fqdn\"} / node_memory_MemTotal_bytes{fqdn=\"$fqdn\"}",
     "legendFormat": "Cached {{fqdn}}"
    }
   ]
  },
  {
   "title": "Mapped Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Mapped{fqdn=\"$fqdn\"}\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Mapped_bytes{fqdn=\"$fqdn\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "GRPC Methods Invocations by Method *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{fqdn=\"$fqdn\"}[$__interval])) by (grpc_method)\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{grpc_method}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failures per Second by Method *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{fqdn=\"$fqdn\",grpc_code!=\"OK\"}[$__interval])) by (grpc_method)\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{grpc_method}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Transmit (bytes) *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes{fqdn=\"$fqdn\",device!=\"lo\"}[$__interval])) without (device)\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{fqdn=\"$fqdn\",device!=\"lo\"}[$__interval])) without (device)",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Network Receive (bytes) *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes{fqdn=\"$fqdn\",device!=\"lo\"}[$__interval])) without (device)\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{fqdn=\"$fqdn\",device!=\"lo\"}[$__interval])) without (device)",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Gitaly Process % CPU *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{fqdn=\"$fqdn\"}[$__interval])) / avg(instance:node_cpus:count{fqdn=\"$fqdn\"})\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total CPU",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(rate(process_cpu_seconds_total{jfqdn=\"$fqdn\"}[$__interval] offset 1w)) / avg(instance:node_cpus:count{fqdn=\"$fqdn\"}  offset 1w)",
     "legendFormat": "Total CPU last week"
    }
   ]
  },
  {
   "title": "Resident Memory Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{fqdn=\"$fqdn\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{fqdn=\"$fqdn\"} ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Times *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_ms{fqdn=\"$fqdn\"}[$__interval]) / 1000\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_disk_read_time_seconds_total{fqdn=\"$fqdn\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Writes *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_ms{fqdn=\"$fqdn\"}[$__interval]) / 1000\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{fqdn=\"$fqdn\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "GRPC messages received *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_received_total{fqdn=\"$fqdn\"}[$__interval])) by (grpc_method)\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ grpc_method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GRPC Messages Sent *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{fqdn=\"$fqdn\"}[$__interval])) by (grpc_method)\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ grpc_method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gitaly goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_goroutines{fqdn=\"$fqdn\"}[$__interval])\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Goroutines",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(rate(go_goroutines{type=\"gitaly\"}[$__interval]))",
     "legendFormat": "Fleet Avg"
    }
   ]
  },
  {
   "title": "Gitaly Running Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(gitaly_commands_running{fqdn=\"$fqdn\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "In flight commands",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(max(gitaly_commands_running))",
     "legendFormat": "Fleet Avg"
    }
   ]
  },
  {
   "title": "Outgoing / Incoming Message Rate (log) *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{fqdn=\"$fqdn\"}[$__interval])) by (grpc_method)\n  /\nsum(rate(grpc_server_msg_received_total{fqdn=\"$fqdn\"}[$__interval])) by (grpc_method)\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ grpc_method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "p99 Gitaly RPC times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{fqdn=\"$fqdn\"}[5m])) by (le, grpc_method)) * 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ grpc_method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gitaly p99 Response Time for All Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{fqdn=\"$fqdn\"}[1m])) by (le)) * 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{fqdn=\"$fqdn\"}[1m])) by (le)) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{fqdn=\"$fqdn\"}[1m])) by (le)) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "avg(histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket[1m])) by (le))) * 1000",
     "legendFormat": "p50 fleet avg"
    }
   ]
  },
  {
   "title": "Connections Accepted *",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(gitaly_connections_total{fqdn=\"$fqdn\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "now",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(gitaly_connections_total{fqdn=\"$fqdn\"}[$__interval] offset 1w)",
     "legendFormat": "now - 1w"
    },
    {
     "expr": "avg(rate(gitaly_connections_total[$__interval]))",
     "legendFormat": "fleet avg"
    }
   ]
  },
  {
   "title": "Host Relative Speed by GRPC Method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg(rate(grpc_server_handling_seconds_sum{fqdn=\"$fqdn\"}[$__interval]) / rate(grpc_server_handling_seconds_count[$__interval]) > 0) by (grpc_type))\n/\n(avg(rate(grpc_server_handling_seconds_sum[$__interval]) / rate(grpc_server_handling_seconds_count[$__interval]) > 0) by (grpc_type))\n\n\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ grpc_type }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GitLab Cgroup CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{fqdn=\"$fqdn\", id=\"/system.slice/gitlab-runsvdir.service\"}[10m])) / avg(instance:node_cpus:count{fqdn=\"$fqdn\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "CPU Usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{fqdn=\"$fqdn\", id=\"/system.slice/gitlab-runsvdir.service\"}[10m]))/ avg(instance:node_cpus:count{fqdn=\"$fqdn\"})",
     "legendFormat": "User CPU"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{fqdn=\"nfs-file-04.stor.gitlab.com\", id=\"/system.slice/gitlab-runsvdir.service\"}[10m]))/ avg(instance:node_cpus:count{fqdn=\"$fqdn\"}) ",
     "legendFormat": "System CPU"
    }
   ]
  },
  {
   "title": "GitLab Cgroup Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{fqdn=\"$fqdn\", id=\"/system.slice/gitlab-runsvdir.service\"}\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}