{
 "title": "Gitaly Request Deadlines",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Unicorn restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  changes(\n    ruby_process_start_time_seconds{\n      environment=\"gprd\",\n      stage=\"main\",\n      job=\"gitlab-rails\"\n    }[1m]\n  )\n)",
     "legendFormat": "gitlab-rails restarts"
    }
   ]
  },
  {
   "title": "Gitaly Success rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{env='gprd', type='gitaly', grpc_code=\"OK\"}[1m])) by (grpc_code)",
     "legendFormat": "Successful Gitaly calls"
    }
   ]
  },
  {
   "title": "Gitaly gRPC error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{env='gprd', type='gitaly', grpc_code!=\"OK\"}[1m]))",
     "legendFormat": "Gitaly error rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{env='gprd', type='gitaly', grpc_code=\"DeadlineExceeded\"}[1m]))",
     "legendFormat": "GitalyDeadlineExceeded"
    }
   ]
  }
 ]
}