{
 "title": "Gitaly Background Maintenance",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(up{job=\"prometheus\"}, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "Repository Maintenance Duration",
   "type": "bargauge",
   "description": "The amount of time each repository maintenance task takes to complete",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(gitaly_daily_maintenance_repo_optimization_seconds_bucket{env=\"$env\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Repo Optimization Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitaly_daily_maintenance_repo_optimization_seconds_count{env=\"$env\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Success Ratio (SLA)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - (sum(gitaly:grpc_server_handled_total:error_rate1m{job=\"gitaly\", environment=\"$env\", grpc_method=\"OptimizeRepository\"}) without (grpc_code) / gitaly:grpc_server_handled_total:rate1m{job=\"gitaly\", environment=\"$env\", grpc_method=\"OptimizeRepository\"})",
     "legendFormat": "{{stage}}: {{shard}}"
    }
   ]
  },
  {
   "title": "Mean Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(1000 * avg(gitaly:grpc_server_handling_seconds:avg5m{job=\"gitaly\", environment=\"$env\", grpc_method=\"OptimizeRepository\"}))",
     "legendFormat": "mean latency"
    }
   ]
  },
  {
   "title": "Total Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:rate1m{job=\"gitaly\",environment=\"$env\",grpc_method=\"OptimizeRepository\"})"
    }
   ]
  },
  {
   "title": "Success Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitaly:grpc_server_handled_total:rate1m{job=\"gitaly\",environment=\"$env\",grpc_method=\"OptimizeRepository\"} - sum(gitaly:grpc_server_handled_total:error_rate1m{job=\"gitaly\", environment=\"$env\", grpc_method=\"OptimizeRepository\"}) without (grpc_code)",
     "legendFormat": "{{stage}}: {{shard}}"
    }
   ]
  },
  {
   "title": "Failures Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:error_rate1m{job=\"gitaly\", environment=\"$env\", grpc_method=\"OptimizeRepository\"}) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  }
 ]
}