{
 "title": "gitaly: Host Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6147291912 at Mon Feb 12 01:42:27 UTC 2024",
 "tags": [
  "managed",
  "gitaly",
  "type:gitaly"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "fqdn",
    "query": "label_values(gitlab_version_info{type=\"gitaly\", component=\"gitaly\", environment=\"$environment\"}, fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Gitaly Per-Node Service Aggregated SLIs Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_node_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}[$__interval])\n",
     "legendFormat": " apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_node_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}[$__interval])\n",
     "legendFormat": " apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_node_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_node_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_node_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_node_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_node_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_node_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "Gitaly Per-Node Service Aggregated SLIs | Latency/Apdex"
    }
   ]
  },
  {
   "title": "Gitaly Per-Node Service Aggregated SLIs Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_node_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": " error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_node_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": " error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_node_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 8, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_node_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_node_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_node_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_node_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_node_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitaly\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "Gitaly Per-Node Service Aggregated SLIs | Errors"
    }
   ]
  },
  {
   "title": "Gitaly Per-Node Service Aggregated SLIs RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_node_ops:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}[$__interval])\n",
     "legendFormat": " RPS"
    },
    {
     "expr": "gitlab_service_node_ops:rate_5m{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  { "title": "🔬 Node SLIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "goserver SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_node_apdex:ratio_5m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}[$__interval])\n",
     "legendFormat": "goserver apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_node_apdex:ratio_5m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}[$__interval])\n",
     "legendFormat": "goserver apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_node_apdex:ratio_5m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_node_apdex:ratio_1h{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_node_apdex:ratio_5m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_node_apdex:ratio_1h{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_node_apdex:ratio_30m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_node_apdex:ratio_6h{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "goserver SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "goserver SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 201 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_node_errors:ratio_5m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "goserver error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_node_errors:ratio_5m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "goserver error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_node_errors:ratio_5m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_node_errors:ratio_1h{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_node_errors:ratio_5m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_node_errors:ratio_1h{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_node_errors:ratio_30m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_node_errors:ratio_6h{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"goserver\",monitor=\"global\",type=\"gitaly\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "goserver SLI | Errors"
    }
   ]
  },
  {
   "title": "goserver SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 201 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_node_ops:rate_5m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"}[$__interval])\n",
     "legendFormat": "goserver RPS"
    },
    {
     "expr": "gitlab_component_node_ops:rate_5m{component=\"goserver\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",monitor=\"global\",type=\"gitaly\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 201 },
   "content": "### Description\n\nThis SLI monitors all Gitaly GRPC requests in aggregate, excluding the OperationService.\nGRPC failures which are considered to be the \"server's fault\" are counted as errors.\nThe apdex score is based on a subset of GRPC methods which are expected to be fast.\n\n\n\n### Observability Tools\n\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/gitaly;type=CPU/cpu?project=gitlab-production)\n* [🐞 Sentry Releases](https://new-sentry.gitlab.net/organizations/gitlab/releases/?project=12&environment=${environment})\n* [🐞 Sentry issues](https://new-sentry.gitlab.net/organizations/gitlab/issues/?project=12&environment=${environment})\n* [📖 Kibana: Gitaly logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.fqdn,params:'$fqdn',type:phrase),query:(match:(json.fqdn:(query:'$fqdn',type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.type,params:gitaly,type:phrase),query:(match:(json.type:(query:gitaly,type:phrase))))),index:'AW5F1OHTiGcMMNRn84Di')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Gitaly slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.fqdn,params:'$fqdn',type:phrase),query:(match:(json.fqdn:(query:'$fqdn',type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.type,params:gitaly,type:phrase),query:(match:(json.type:(query:gitaly,type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.msg,params:unary,type:phrase),query:(match:(json.msg:(query:unary,type:phrase)))),(meta:(field:json.grpc.time_ms,index:'AW5F1OHTiGcMMNRn84Di',key:json.grpc.time_ms,params:(gte:1000,lte:!n),type:range),query:(range:(json.grpc.time_ms:(gte:1000,lte:!n))))),index:'AW5F1OHTiGcMMNRn84Di',sort:!(!(json.grpc.time_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Gitaly failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.fqdn,params:'$fqdn',type:phrase),query:(match:(json.fqdn:(query:'$fqdn',type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.type,params:gitaly,type:phrase),query:(match:(json.type:(query:gitaly,type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.grpc.code,negate:!t,params:OK,type:phrase),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:exists,type:json.grpc.code,value:exists),query:(exists:(field:json.grpc.code)))),index:'AW5F1OHTiGcMMNRn84Di')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.fqdn,params:'$fqdn',type:phrase),query:(match:(json.fqdn:(query:'$fqdn',type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.type,params:gitaly,type:phrase),query:(match:(json.type:(query:gitaly,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.fqdn,params:'$fqdn',type:phrase),query:(match:(json.fqdn:(query:'$fqdn',type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.type,params:gitaly,type:phrase),query:(match:(json.type:(query:gitaly,type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.grpc.code,negate:!t,params:OK,type:phrase),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:exists,type:json.grpc.code,value:exists),query:(exists:(field:json.grpc.code)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.fqdn,params:'$fqdn',type:phrase),query:(match:(json.fqdn:(query:'$fqdn',type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.type,params:gitaly,type:phrase),query:(match:(json.type:(query:gitaly,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.fqdn,params:'$fqdn',type:phrase),query:(match:(json.fqdn:(query:'$fqdn',type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.type,params:gitaly,type:phrase),query:(match:(json.type:(query:gitaly,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.fqdn,params:'$fqdn',type:phrase),query:(match:(json.fqdn:(query:'$fqdn',type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.type,params:gitaly,type:phrase),query:(match:(json.type:(query:gitaly,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.fqdn,params:'$fqdn',type:phrase),query:(match:(json.fqdn:(query:'$fqdn',type:phrase)))),(meta:(index:'AW5F1OHTiGcMMNRn84Di',key:json.type,params:gitaly,type:phrase),query:(match:(json.type:(query:gitaly,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.grpc.time_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "🔬 SLI Detail: goserver",
   "type": "row",
   "gridPos": { "x": 0, "y": 2000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 goserver Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(grpc_server_handling_seconds_bucket{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",grpc_method!~\"CalculateChecksum|CommitLanguages|CommitStats|CreateFork|CreateRepositoryFromURL|FetchInternalRemote|FetchIntoObjectPool|FetchRemote|FetchSourceBranch|FindCommit|FindRemoteRepository|FindRemoteRootRef|Fsck|GarbageCollect|GetArchive|LastCommitForPath|OptimizeRepository|PackObjectsHookWithSidechannel|PostReceiveHook|PostUploadPackWithSidechannel|PreReceiveHook|RepackFull|RepackIncremental|ReplicateRepository|RepositorySize|SSHUploadPackWithSidechannel|UpdateHook|WriteRef\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",type=\"gitaly\"}[$__interval])\n    or\n    rate(grpc_server_handling_seconds_bucket{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",grpc_method=~\"FindCommit|GetArchive|LastCommitForPath|RepositorySize|WriteRef\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",type=\"gitaly\"}[$__interval])\n    or\n    rate(grpc_server_handling_seconds_bucket{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",grpc_service=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",type=\"gitaly\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 goserver"
      }
     ]
    },
    {
     "title": "goserver Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  label_replace(rate(gitaly_service_client_requests_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",grpc_code!~\"AlreadyExists|Canceled|DeadlineExceeded|FailedPrecondition|InvalidArgument|NotFound|OK|PermissionDenied|ResourceExhausted|Unauthenticated\",job=\"gitaly\",type=\"gitaly\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(gitaly_service_client_requests_total{deadline_type!=\"limited\",env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",grpc_code=\"DeadlineExceeded\",job=\"gitaly\",type=\"gitaly\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "goserver"
      }
     ]
    },
    {
     "title": "goserver RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitaly_service_client_requests_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",job=\"gitaly\",type=\"gitaly\"}[$__interval])\n)\n > 0",
       "legendFormat": "goserver"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "x": 0, "y": 3000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "avg(instance:node_cpu_utilization:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "sum(rate(node_network_receive_bytes_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_reads_completed_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_writes_completed_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_read_bytes_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_written_bytes_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Total Time",
     "type": "graph",
     "description": "Total time spent in read operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_read_time_seconds_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Total Time",
     "type": "graph",
     "description": "Total time spent in write operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_write_time_seconds_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "CPU Scheduling Waiting",
     "type": "graph",
     "description": "CPU scheduling waiting on the run queue, as a percentage of time. Aggregated to worst CPU per node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "max by (fqdn) (\n  rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[5m])\n)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg1 per core",
     "type": "graph",
     "description": "Loadavg (1 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "loadavg1" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load1{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg5 per core",
     "type": "graph",
     "description": "Loadavg (5 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg5" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load5{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg15 per core",
     "type": "graph",
     "description": "Loadavg (15 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg15" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load15{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 },
   "collapsed": true,
   "panels": [
    {
     "title": "cgroup_memory component saturation: Cgroup Memory Utilization per Node",
     "type": "graph",
     "description": "Cgroup memory utilization per node.\n\nSome services, notably Gitaly, are configured to run within a cgroup with a memory limit lower than the\nmemory limit for the node. This ensures that a traffic spike to Gitaly does not affect other services on the node.\n\nIf this resource is becoming saturated, this may indicate traffic spikes to Gitaly, abuse or possibly resource leaks in\nthe application. Gitaly or other git processes may be killed by the OOM killer when this resource is saturated.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      (\n        container_memory_usage_bytes{id=\"/system.slice/gitlab-runsvdir.service\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"} -\n        container_memory_cache{id=\"/system.slice/gitlab-runsvdir.service\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"} -\n        container_memory_swap{id=\"/system.slice/gitlab-runsvdir.service\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      )\n      /\n      container_spec_memory_limit_bytes{id=\"/system.slice/gitlab-runsvdir.service\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"cgroup_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"cgroup_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"cgroup_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cgroup_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cgroup_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "cpu component saturation: Average Service CPU Utilization",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a service fleet.\nIf it is becoming saturated, it may indicate that the fleet needs\nhorizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_space component saturation: Disk Space Utilization per Device per Node",
     "type": "graph",
     "description": "Disk space utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      (\n        1 - node_filesystem_avail_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"} / node_filesystem_size_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_space\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_space\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_space\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_sustained_read_iops component saturation: Disk Sustained Read IOPS Utilization per Node",
     "type": "graph",
     "description": "Disk sustained read IOPS utilization per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      rate(node_disk_reads_completed_total{device!=\"sda\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[20m])\n      /\n      node_disk_max_read_iops{device!=\"sda\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_read_iops\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_read_iops\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_read_iops\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_sustained_read_iops\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_sustained_read_iops\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_sustained_read_throughput component saturation: Disk Sustained Read Throughput Utilization per Node",
     "type": "graph",
     "description": "Disk sustained read throughput utilization per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      rate(node_disk_read_bytes_total{device!=\"sda\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[20m])\n      /\n      node_disk_max_read_bytes_seconds{device!=\"sda\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_read_throughput\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_read_throughput\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_read_throughput\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_sustained_read_throughput\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_sustained_read_throughput\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_sustained_write_iops component saturation: Disk Sustained Write IOPS Utilization per Node",
     "type": "graph",
     "description": "Gitaly runs on Google Cloud's Persistent Disk product. This has a published sustained\nmaximum write IOPS value. This value can be exceeded for brief periods.\n\nIf a single node is consistently reaching saturation, it may indicate a noisy-neighbour repository,\npossible abuse or it may indicate that the node needs rebalancing.\n\nMore information can be found at\nhttps://cloud.google.com/compute/docs/disks/performance.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      rate(node_disk_writes_completed_total{device!=\"sda\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[20m])\n      /\n      node_disk_max_write_iops{device!=\"sda\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_write_iops\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_write_iops\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_write_iops\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_sustained_write_iops\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_sustained_write_iops\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_sustained_write_throughput component saturation: Disk Sustained Write Throughput Utilization per Node",
     "type": "graph",
     "description": "Gitaly runs on Google Cloud's Persistent Disk product. This has a published sustained\nmaximum write throughput value. This value can be exceeded for brief periods.\n\nIf a single node is consistently reaching saturation, it may indicate a noisy-neighbour repository,\npossible abuse or it may indicate that the node needs rebalancing.\n\nMore information can be found at\nhttps://cloud.google.com/compute/docs/disks/performance.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      rate(node_disk_written_bytes_total{device!=\"sda\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[20m])\n      /\n      node_disk_max_write_bytes_seconds{device!=\"sda\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_write_throughput\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_write_throughput\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"disk_sustained_write_throughput\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_sustained_write_throughput\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_sustained_write_throughput\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "memory component saturation: Memory Utilization per Node",
     "type": "graph",
     "description": "Memory utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"} or instance:node_memory_utilisation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "single_node_cpu component saturation: Average CPU Utilization per Node",
     "type": "graph",
     "description": "Average CPU utilization per Node.\n\nIf average CPU is saturated, it may indicate that a fleet is in need to horizontal or vertical scaling. It may also indicate\nimbalances in load in a fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      avg without(cpu, mode) (1 - rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[5m]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"single_node_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"single_node_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"single_node_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "go_memory component saturation: Go Memory Utilization per Node",
     "type": "graph",
     "description": "Go's memory allocation strategy can make it look like a Go process is saturating memory when measured using RSS, when in fact\nthe process is not at risk of memory saturation. For this reason, we measure Go processes using the `go_memstat_alloc_bytes`\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      max by (env, environment, tier, type, stage, shard, fqdn) (\n        go_memstats_alloc_bytes{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      )\n      /\n      sum by (env, environment, tier, type, stage, shard, fqdn) (\n        node_memory_MemTotal_bytes{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"go_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"go_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\", component=\"go_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inflight Git Commands on Node",
     "type": "graph",
     "description": "Number of Git commands running concurrently per node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5001 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitaly_commands_running{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "OOM Kills on Node",
     "type": "graph",
     "description": "Number of OOM Kills per server.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5001 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(node_vmstat_oom_kill{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])\n"
      }
     ]
    }
   ]
  },
  {
   "title": "gitaly spawn tokens",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gitaly Spawn Timeouts per Node",
     "type": "graph",
     "description": "Golang uses a global lock on process spawning. In order to control contention on this lock Gitaly uses a safety valve. If a request is unable to obtain the lock within a period, a timeout occurs. These timeouts are serious and should be addressed. Non-zero is bad.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(gitaly_spawn_timeouts_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Gitaly Spawn Token queue length per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitaly_spawn_token_waiting_length{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Gitaly Spawn Token P99 waiting time per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5111 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(gitaly_spawn_waiting_time_seconds_bucket{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])) by (le))\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Gitaly Spawn Token P99 forking time per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5111 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(gitaly_spawn_forking_time_seconds_bucket{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])) by (le))\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "gitaly process activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5200 },
   "collapsed": true,
   "panels": [
    {
     "title": "gitaly processes: CPU Time",
     "type": "graph",
     "description": "Seconds of CPU time for the named process group, per second. Note that this metric is sampled periodically, and thus will greatly under-sample short-lived processes.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5201 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by() (\n  rate(\n    namedprocess_namegroup_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",groupname=~\"gitaly\",type=\"gitaly\"}[$__interval]\n  )\n)\n"
      }
     ]
    },
    {
     "title": "gitaly processes: Open File Descriptors",
     "type": "graph",
     "description": "Maximum number of open file descriptors per host",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5201 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by() (\n    namedprocess_namegroup_open_filedesc{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",groupname=~\"gitaly\",type=\"gitaly\"}\n)\n"
      }
     ]
    },
    {
     "title": "gitaly processes: Number of Processes",
     "type": "graph",
     "description": "Number of processes in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5211 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by() (\n  avg_over_time(namedprocess_namegroup_num_procs{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",groupname=~\"gitaly\",type=\"gitaly\"}[$__interval])\n)\n"
      }
     ]
    },
    {
     "title": "gitaly processes: Number of Threads",
     "type": "graph",
     "description": "Number of threads in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5211 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by() (\n  namedprocess_namegroup_num_threads{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",groupname=~\"gitaly\",type=\"gitaly\"}\n)\n"
      }
     ]
    },
    {
     "title": "gitaly processes: RSS Memory Usage",
     "type": "graph",
     "description": "Resident Memory usage for named process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5221 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by() (\n  namedprocess_namegroup_memory_bytes{memtype=\"resident\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",groupname=~\"gitaly\",type=\"gitaly\"}\n)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "git process activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5300 },
   "collapsed": true,
   "panels": [
    {
     "title": "git processes: CPU Time",
     "type": "graph",
     "description": "Seconds of CPU time for the named process group, per second. Note that this metric is sampled periodically, and thus will greatly under-sample short-lived processes.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5301 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(groupname) (\n  rate(\n    namedprocess_namegroup_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",groupname=~\"git.*\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ groupname}}"
      }
     ]
    },
    {
     "title": "git processes: Open File Descriptors",
     "type": "graph",
     "description": "Maximum number of open file descriptors per host",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5301 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by(groupname) (\n    namedprocess_namegroup_open_filedesc{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",groupname=~\"git.*\",type=\"gitaly\"}\n)\n",
       "legendFormat": "{{ groupname}}"
      }
     ]
    },
    {
     "title": "git processes: Number of Processes",
     "type": "graph",
     "description": "Number of processes in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5311 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(groupname) (\n  avg_over_time(namedprocess_namegroup_num_procs{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",groupname=~\"git.*\",type=\"gitaly\"}[$__interval])\n)\n",
       "legendFormat": "{{ groupname}}"
      }
     ]
    },
    {
     "title": "git processes: Number of Threads",
     "type": "graph",
     "description": "Number of threads in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5311 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(groupname) (\n  namedprocess_namegroup_num_threads{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",groupname=~\"git.*\",type=\"gitaly\"}\n)\n",
       "legendFormat": "{{ groupname}}"
      }
     ]
    },
    {
     "title": "git processes: RSS Memory Usage",
     "type": "graph",
     "description": "Resident Memory usage for named process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5321 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(groupname) (\n  namedprocess_namegroup_memory_bytes{memtype=\"resident\", env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",groupname=~\"git.*\",type=\"gitaly\"}\n)\n",
       "legendFormat": "{{ groupname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gitaly command stats by command",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5500 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time",
     "type": "graph",
     "description": "Seconds of CPU time consumed by gitaly child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5501 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(cmd, subcmd) (\n  rate(\n    gitaly_command_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ cmd}} {{ subcmd}}"
      }
     ]
    },
    {
     "title": "Context switches",
     "type": "graph",
     "description": "Context switches incurred by child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5501 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cmd, subcmd) (\n  rate(\n    gitaly_command_context_switches_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ cmd}} {{ subcmd}}"
      }
     ]
    },
    {
     "title": "Minor page faults",
     "type": "graph",
     "description": "Minor page faults incurred by child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption. The number of page faults serviced without any I/O activity; here I/O activity is avoided by \"reclaiming\" a page frame from the list of pages awaiting reallocation.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5511 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cmd, subcmd) (\n  rate(\n    gitaly_command_minor_page_faults_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ cmd}} {{ subcmd}}"
      }
     ]
    },
    {
     "title": "Major page faults",
     "type": "graph",
     "description": "Major page faults incurred by child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption. The number of page faults serviced that required I/O activity.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5511 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cmd, subcmd) (\n  rate(\n    gitaly_command_major_page_faults_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ cmd}} {{ subcmd}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gitaly command stats by RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5600 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time",
     "type": "graph",
     "description": "Seconds of CPU time consumed by gitaly child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5601 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(grpc_service, grpc_method) (\n  rate(\n    gitaly_command_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ grpc_service}} {{ grpc_method}}"
      }
     ]
    },
    {
     "title": "Context switches",
     "type": "graph",
     "description": "Context switches incurred by child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5601 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(grpc_service, grpc_method) (\n  rate(\n    gitaly_command_context_switches_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ grpc_service}} {{ grpc_method}}"
      }
     ]
    },
    {
     "title": "Minor page faults",
     "type": "graph",
     "description": "Minor page faults incurred by child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption. The number of page faults serviced without any I/O activity; here I/O activity is avoided by \"reclaiming\" a page frame from the list of pages awaiting reallocation.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5611 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(grpc_service, grpc_method) (\n  rate(\n    gitaly_command_minor_page_faults_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ grpc_service}} {{ grpc_method}}"
      }
     ]
    },
    {
     "title": "Major page faults",
     "type": "graph",
     "description": "Major page faults incurred by child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption. The number of page faults serviced that required I/O activity.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5611 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(grpc_service, grpc_method) (\n  rate(\n    gitaly_command_major_page_faults_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ grpc_service}} {{ grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gitaly command stats by commands per RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5700 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Time",
     "type": "graph",
     "description": "Seconds of CPU time consumed by gitaly child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5701 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(grpc_method, cmd, subcmd) (\n  rate(\n    gitaly_command_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ grpc_method}} {{ cmd}} {{ subcmd}}"
      }
     ]
    },
    {
     "title": "Context switches",
     "type": "graph",
     "description": "Context switches incurred by child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5701 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(grpc_method, cmd, subcmd) (\n  rate(\n    gitaly_command_context_switches_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ grpc_method}} {{ cmd}} {{ subcmd}}"
      }
     ]
    },
    {
     "title": "Minor page faults",
     "type": "graph",
     "description": "Minor page faults incurred by child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption. The number of page faults serviced without any I/O activity; here I/O activity is avoided by \"reclaiming\" a page frame from the list of pages awaiting reallocation.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5711 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(grpc_method, cmd, subcmd) (\n  rate(\n    gitaly_command_minor_page_faults_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ grpc_method}} {{ cmd}} {{ subcmd}}"
      }
     ]
    },
    {
     "title": "Major page faults",
     "type": "graph",
     "description": "Major page faults incurred by child processes, per second. These are accounted once the process exits, so the reporting may occur later than the resource consumption. The number of page faults serviced that required I/O activity.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5711 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(grpc_method, cmd, subcmd) (\n  rate(\n    gitaly_command_major_page_faults_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ grpc_method}} {{ cmd}} {{ subcmd}}"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5721 },
     "content": "These metrics are collected whenever a process that was spawned by gitaly exits.\n\n**Contrast to process metrics:**\n\nThese metrics are more complete than the sampled process exporter metrics, in particular\nwe account for all of the resources spent by short-lived processes -- which process sampling\nis prone to miss.\n\n**Pitfalls:**\n\nBecause we only report on exit, long-running processes will only be shown here once they finish.\nOnce they do, all of their spent resources will be accounted for in one go, which may look like\na burst of activity.\n"
    }
   ]
  },
  {
   "title": "gitaly per-RPC metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5800 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gitaly current per-RPC adaptive limit (visible if adaptiveness is enabled)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5802 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(gitaly_concurrency_limiting_current_limit{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",limit=~\"perRPC.*\",type=\"gitaly\"}) by (fqdn, limit)\n",
       "legendFormat": "{{ limit }}"
      }
     ]
    },
    {
     "title": "Request rate by grpc_method",
     "type": "graph",
     "description": "Request rate for the Gitaly server",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5802 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_method, grpc_service) (rate(grpc_server_handled_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval]))\n",
       "legendFormat": "/{{ grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "Response rate by grpc_code",
     "type": "graph",
     "description": "Response rate for the Gitaly server",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5812 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_code) (rate(grpc_server_handled_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval]))\n",
       "legendFormat": "{{grpc_cdoe}}"
      }
     ]
    },
    {
     "title": "In progress requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5812 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitaly_concurrency_limiting_in_progress{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}) by (fqdn, grpc_service, grpc_method)\n",
       "legendFormat": "/{{ grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "Queued requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5822 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitaly_concurrency_limiting_queued{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}) by (fqdn, grpc_service, grpc_method)\n",
       "legendFormat": "/{{ grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "95th queueing time (RPS)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5822 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(gitaly_concurrency_limiting_acquiring_seconds_bucket{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval])) by (le, fqdn, grpc_service, grpc_method))\n",
       "legendFormat": "/{{ grpc_service}}/{{ grpc_method }}"
      }
     ]
    },
    {
     "title": "Dropped requests (RPS)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5832 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitaly_requests_dropped_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval])) by (fqdn, grpc_service, grpc_method, reason)\n",
       "legendFormat": "/{{ grpc_service}}/{{ grpc_method }} ({{ reason }})"
      }
     ]
    }
   ]
  },
  {
   "title": "gitaly pack-objects metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5900 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gitaly current pack-objects adaptive limit (visible if adaptiveness is enabled)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5902 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(gitaly_concurrency_limiting_current_limit{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",limit=\"packObjects\",type=\"gitaly\"}) by (fqdn, limit)\n",
       "legendFormat": "{{ limit }}- Per IP"
      }
     ]
    },
    {
     "title": "Gitaly pack-objects concurrency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5902 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(gitaly_pack_objects_in_progress{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}) by (fqdn)\n",
       "legendFormat": "concurrency by gitaly process"
      }
     ]
    },
    {
     "title": "Gitaly pack-objects queued commands (gauage)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5912 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(gitaly_pack_objects_queued{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}) by (fqdn)\n",
       "legendFormat": "queued commands"
      }
     ]
    },
    {
     "title": "95th queueing time (RPS)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5912 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(gitaly_pack_objects_acquiring_seconds_bucket{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval])) by (le, fqdn))\n",
       "legendFormat": "95th queueing time"
      }
     ]
    },
    {
     "title": "Gitaly pack-objects dropped commands (RPS)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5922 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitaly_pack_objects_dropped_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval])) by (fqdn, reason)\n",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "Gitaly pack-objects cache served bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5922 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitaly_pack_objects_served_bytes_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval])) by (fqdn)\n",
       "legendFormat": "cache served"
      }
     ]
    },
    {
     "title": "Gitaly pack-objects cache generated bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5932 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitaly_pack_objects_generated_bytes_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval])) by (fqdn)\n",
       "legendFormat": "cache generated"
      }
     ]
    },
    {
     "title": "Gitaly pack-objects cache",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5932 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitaly_pack_objects_cache_lookups_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval])) by (result)\n",
       "legendFormat": "{{ result }}"
      }
     ]
    },
    {
     "title": "Gitaly Pack-Objects cache info",
     "type": "text",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5942 },
     "content": "Gitaly is caching short rolling window of <a href=\"https://gitlab.com/gitlab-com/gl-infra/chef-repo/-/blob/master/roles/gprd-base-stor-gitaly-common.json?ref_type=heads#L185\">5 minutes</a> of Git fetch responses. It is independent of (verbatim from <a href=\"https://gitlab.com/gitlab-com/runbooks/-/blob/master/docs/gitaly/gitaly-repos-cgroup.md\">docs</a>):\n\n1. The transport (HTTP or SSH)\n2. Git protocol version (v0 or v2)\n3. The type of fetch, such as full clones, incremental fetches, shallow clones, or partial clones]\n\nHere is the link to docs to understand more about pack-object cache:\nhttps://gitlab.com/gitlab-com/runbooks/-/blob/master/docs/gitaly/gitaly-repos-cgroup.md\n"
    }
   ]
  },
  {
   "title": "cgroup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6000 },
   "collapsed": true,
   "panels": [
    {
     "title": "cgroup: CPU per cgroup",
     "type": "graph",
     "description": "Rate of CPU usage on every cgroup available on the Gitaly node.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6001 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (id) (rate(container_cpu_usage_seconds_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])))\n",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "cgroup: CPU Throttling",
     "type": "graph",
     "description": "Cgroups that are getting CPU throttled. If the cgroup is not visible it is not getting throttled.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6001 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(\n  container_cpu_cfs_throttled_seconds_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval]\n) > 0\n",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "cgroup: Memory usage bytes (parent cgroups)",
     "type": "graph",
     "description": "This metric reflects usage_in_bytes (V1) or memory.current (V2) of cgroups on the Gitaly node. This metric consists of Anonymous Memory + Page Caches + Swap + some Kernel Memory.\nGitaly triggers a massive amount of Git processes accessing files on disk. This usage pattern accumulating Page Caches in repository cgroups and inflate the parent cgroup's usage bytes. A huge portion of page caches could be evictable. Hence, the usage bytes peaking doesn't mean the system is overloaded. Working set metric (Usage Bytes - Inactive File) is a more accurate signal for memory pressure.\n\nFor more information, please this comment: https://gitlab.com/groups/gitlab-org/-/epics/10734#note_1632048830\n",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6011 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (id) (container_memory_usage_bytes{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",id!~\"/gitaly/gitaly-[0-9]+/repos-[0-9]+\",type=\"gitaly\"}))\n",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "cgroup: Top usage bytes (repository cgroups)",
     "type": "graph",
     "description": "This metric reflects usage_in_bytes (V1) or memory.current (V2) of cgroups on the Gitaly node. This metric consists of Anonymous Memory + Page Caches + Swap + some Kernel Memory.\nGitaly triggers a massive amount of Git processes accessing files on disk. This usage pattern accumulating Page Caches in repository cgroups and inflate the parent cgroup's usage bytes. A huge portion of page caches could be evictable. Hence, the usage bytes peaking doesn't mean the system is overloaded. Working set metric (Usage Bytes - Inactive File) is a more accurate signal for memory pressure.\n\nFor more information, please this comment: https://gitlab.com/groups/gitlab-org/-/epics/10734#note_1632048830\n",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6011 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (id) (container_memory_usage_bytes{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",id=~\"/gitaly/gitaly-[0-9]+/repos-[0-9]+\",type=\"gitaly\"}))\n",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "cgroup: Memory working set bytes (parent cgroups)",
     "type": "graph",
     "description": "This metric reflects usage_in_bytes (V1) or memory.current (V2) excluding inactive_file. There are two types of Page Caches in cgroup: active_file and inactive_file. inactive_file are Page Caches which have been moved off the active LRU list. When the cgroup has a memory pressure, they are targeted for eviction first. In contrast, active_file descibres the portion of the memory which has been accessed recently. Gitaly usage pattern accesses Page Caches a lot. So, active page caches are essential for the overall performance; we should not evict them. Thus, the working set metric excludes highly evictable memory portion it acts as a more accurate signal for memory pressure.\n",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6021 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (id) (container_memory_working_set_bytes{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",id!~\"/gitaly/gitaly-[0-9]+/repos-[0-9]+\",type=\"gitaly\"}))\n",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "cgroup: Top working set bytes (repository cgroups)",
     "type": "graph",
     "description": "This metric reflects usage_in_bytes (V1) or memory.current (V2) excluding inactive_file. There are two types of Page Caches in cgroup: active_file and inactive_file. inactive_file are Page Caches which have been moved off the active LRU list. When the cgroup has a memory pressure, they are targeted for eviction first. In contrast, active_file descibres the portion of the memory which has been accessed recently. Gitaly usage pattern accesses Page Caches a lot. So, active page caches are essential for the overall performance; we should not evict them. Thus, the working set metric excludes highly evictable memory portion it acts as a more accurate signal for memory pressure.\n",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6021 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (id) (container_memory_working_set_bytes{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",id=~\"/gitaly/gitaly-[0-9]+/repos-[0-9]+\",type=\"gitaly\"}))\n",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "cgroup: Memory cache bytes (parent cgroups)",
     "type": "graph",
     "description": "This metric reflects cache (V1) or file (V2) in memory.state. It's the total page caches accounted for a cgroup.\n\nPage cache accounting is complicated. Any page created by a process inside a cgroup is accounted for by that cgroup. If the page already exists in memory, the page will eventually get accounted to the cgroup after it keeps accessing that page aggressively. And those pages are also counted in the ancestor cgroup. With the current Gitaly's cgroup architecture, the parent per-pid cgroup accounts for all page caches of its indirect processes.\n\nIf the parent cgroup keeps accumulating Page Caches, it evicts them constantly when direct/indirect processes needs allocation (denoted by failcnt metric).\n",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6031 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (id) (container_memory_cache{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",id!~\"/gitaly/gitaly-[0-9]+/repos-[0-9]+\",type=\"gitaly\"}))\n",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "cgroup: Top cache bytes (repository cgroups)",
     "type": "graph",
     "description": "This metric reflects cache (V1) or file (V2) in memory.state. It's the total page caches accounted for a cgroup.\n\nPage cache accounting is complicated. Any page created by a process inside a cgroup is accounted for by that cgroup. If the page already exists in memory, the page will eventually get accounted to the cgroup after it keeps accessing that page aggressively. And those pages are also counted in the ancestor cgroup. With the current Gitaly's cgroup architecture, the parent per-pid cgroup accounts for all page caches of its indirect processes.\n\nIf the parent cgroup keeps accumulating Page Caches, it evicts them constantly when direct/indirect processes needs allocation (denoted by failcnt metric).\n",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6031 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (id) (container_memory_cache{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",id=~\"/gitaly/gitaly-[0-9]+/repos-[0-9]+\",type=\"gitaly\"}))\n",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "cgroup: failcnt",
     "type": "graph",
     "description": "This metric reflects the changes of failcnt counter. It denotes how frequent the cgroup needs to evict memory. The name is misleading, it's more a \"GC\" counter than failure counter. After a eviction, if the cgroup cannot find enough spaces for allocation, OOM Killer is invoked.\n",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6041 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (id) (increase(container_memory_failcnt{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])) > 0\n",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "OOM Kills on Node",
     "type": "graph",
     "description": "Number of OOM Kills per server.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6041 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(node_vmstat_oom_kill{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__interval])\n"
      }
     ]
    },
    {
     "title": "cgroup runbook",
     "type": "text",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6051 },
     "content": "Gitaly spawns git processes into cgroups to limit their cpu and memory\nusage. This is to cap the maximum amount of cpu/memory used by a single\ngit process and hence affecting other processes on the same host.\nThis helps in fair usage of system resources among all\nthe repositories hosted by a single Gitaly storage server.\n\nHere is the runbook to debug issues related to Gitaly cgroups:\nhttps://gitlab.com/gitlab-com/runbooks/-/blob/master/docs/gitaly/gitaly-repos-cgroup.md\n"
    }
   ]
  },
  {
   "title": "Adaptive limit metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Adaptive limiting backoff events (events that cutoff current limits)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7001 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitaly_concurrency_limiting_backoff_events_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval])) by (fqdn, watcher)\n",
       "legendFormat": "{{ watcher }}"
      }
     ]
    },
    {
     "title": "Adaptive limiting watcher errors (fail to get status from resource watchers)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7001 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitaly_concurrency_limiting_watcher_errors_total{env=\"$environment\",environment=\"$environment\",fqdn=~\"$fqdn\",type=\"gitaly\"}[$__rate_interval])) by (fqdn, watcher)\n",
       "legendFormat": "{{ watcher }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server-side backup metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backup duration by phase",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8001 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99,\n  sum(rate(gitaly_backup_latency_seconds_bucket[5m])) by (fqdn, le, phase)\n)\n",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "BackupRepository RPC status",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8001 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{grpc_method=\"BackupRepository\"}[1m])) by (fqdn, grpc_code)\n",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "BackupRepository RPC latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8011 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(fqdn, le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"BackupRepository\"}[5m])))\n",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Backup bundle upload rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8011 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (rate(gitaly_backup_bundle_bytes_sum[$__rate_interval]))\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}