{
 "title": "Gitaly InfoRef Upload-Pack Caching",
 "description": "Cache invalidation and hit/miss ratio for info-ref caching",
 "tags": [
  "Gitaly",
  "unmanaged"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(up{job=\"prometheus\"}, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " 100 * (sum(rate(gitaly_diskcache_requests_total{env=\"$env\"}[1m])) - sum(rate(gitaly_diskcache_miss_total{env=\"$env\"}[1m]))) / sum(rate(gitaly_diskcache_requests_total{env=\"$env\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cache Invalidation",
   "type": "timeseries",
   "description": "Cache invalidation by RPC. Shows the total number of RPC's, the types of RPC's, and unexpected errors that occur.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gitaly_cacheinvalidator_rpc_total{env=\"$env\"}[1m]))",
     "legendFormat": "Total gRPCs"
    },
    {
     "expr": "sum(rate(gitaly_cacheinvalidator_optype_total{env=\"$env\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Disk Cache Effectiveness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(gitaly_diskcache_requests_total{env=\"$env\"}[1m])) - sum(rate(gitaly_diskcache_miss_total{env=\"$env\"}[1m]))) / sum(rate(gitaly_diskcache_requests_total{env=\"$env\"}[1m]))",
     "legendFormat": "Total Accesses"
    }
   ]
  },
  {
   "title": "Cache Invalidation errors",
   "type": "timeseries",
   "description": "Unexpected errors during invalidation by gRPC method",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gitaly_cacheinvalidator_error_total{env=\"$env\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Disk cache edge cases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gitaly_diskcache_errors_total{env=\"$env\"}[1m])) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Disk Cache Bytes Fetched/Stored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(gitaly_diskcache_bytes_fetched_total{env=\"$env\"}[1m]))",
     "legendFormat": "Bytes fetched"
    },
    {
     "expr": "sum(rate(gitaly_diskcache_bytes_stored_total{env=\"$env\"}[1m]))",
     "legendFormat": "Bytes stored"
    },
    {
     "expr": "sum(rate(gitaly_diskcache_bytes_loser_total{env=\"$env\"}[1m]))",
     "legendFormat": "Loser writes"
    }
   ]
  },
  {
   "title": "Disk Cache Bytes Fetched/Stored Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gitaly_diskcache_bytes_fetched_total{env=\"gprd\"}[1m])) / sum(rate(gitaly_diskcache_bytes_stored_total{env=\"gprd\"}[1m]))\n",
     "legendFormat": "Bytes fetched"
    },
    { "legendFormat": "Bytes stored" }
   ]
  },
  {
   "title": "Disk cache file walkers",
   "type": "graph",
   "description": "Shows stats about the file walkers and how often they check and remove files",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitaly_diskcache_walker_check_total[1m]))",
     "legendFormat": "Checks (sum)"
    },
    {
     "expr": "sum(rate(gitaly_diskcache_walker_removal_total[1m]))",
     "legendFormat": "Removal (sum)"
    },
    {
     "expr": "sum(rate(gitaly_diskcache_walker_error_total[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "InfoRef Upload-Pack Cache Effectiveness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gitaly_inforef_cache_attempt_total{env=\"$env\"}[1m]))\n",
     "legendFormat": "Total Cache Attempts"
    },
    {
     "expr": "sum(rate(gitaly_inforef_cache_hit_miss_total{env=\"$env\",type=\"hit\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(rate(gitaly_inforef_cache_hit_miss_total{env=\"$env\",type=\"miss\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "File walker checks by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gitaly_diskcache_walker_check_total[1m])"
    },
    {
     "expr": "rate(gitaly_diskcache_walker_removal_total[1m])"
    }
   ]
  }
 ]
}