{
 "title": "Gitaly Version Tracker",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gitlab_build_info" }
  ]
 },
 "panels": [
  {
   "title": "Gitaly Version Tracker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "# of Hosts" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_build_info{environment=\"$environment\"}) by (version,tier)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ tier }}: {{ version }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gitaly Version Numbers",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(gitlab_build_info{environment=\"$environment\"}) by (fqdn, version)",
     "legendFormat": "{{ fqdn }} {{ version }}"
    }
   ]
  },
  {
   "title": "Auth version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gitaly_service_client_requests{env=\"$environment\"}[$__interval])) by (auth_version)",
     "legendFormat": "Auth {{auth_version}}"
    },
    {
     "expr": "sum(rate(gitaly_service_client_requests_total{env=\"$environment\"}[$__interval])) by (auth_version)",
     "legendFormat": "Auth {{auth_version}}"
    }
   ]
  }
 ]
}