{
 "title": "gitaly: Gitaly Feature Status",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7747943717 at Wed Sep  4 21:06:35 UTC 2024",
 "tags": [
  "managed",
  "gitaly",
  "gitaly",
  "type:gitaly"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "method",
    "query": "label_values(gitaly:grpc_server_handled_total:rate1m{env=\"$environment\"}, grpc_method)"
   }
  ]
 },
 "panels": [
  { "title": "Feature Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Feature Flags",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitaly_feature_flag_checks_total{env=\"$environment\"}[$__rate_interval])) by (flag, enabled)\n",
     "legendFormat": "{{flag}}: {{enabled}}"
    }
   ]
  },
  {
   "title": "Success Ratio (SLA)",
   "type": "timeseries",
   "description": "This graph represents the percentage of requests that succeed.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum(gitaly:grpc_server_handled_total:error_rate1m{environment=\"$environment\",grpc_method=\"$method\"}) without (grpc_code) / gitaly:grpc_server_handled_total:rate1m{environment=\"$environment\",grpc_method=\"$method\"})\n",
     "legendFormat": "stage: {{stage}}, shard: {{shard}}"
    }
   ]
  },
  {
   "title": "Total Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:rate1m{environment=\"$environment\",grpc_method=\"$method\"}) by (grpc_method)\n",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:rate1m{environment=\"$environment\",grpc_method=\"$method\"} - sum(gitaly:grpc_server_handled_total:error_rate1m{environment=\"$environment\",grpc_method=\"$method\"}) without (grpc_code))\n",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:error_rate1m{environment=\"$environment\",grpc_method=\"$method\"}) by (grpc_code)\n",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{environment=\"$environment\",grpc_method=\"$method\"}) by (le)) * 1000\n",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{environment=\"$environment\",grpc_method=\"$method\"}) by (le)) * 1000\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{environment=\"$environment\",grpc_method=\"$method\"}) by (le)) * 1000\n",
     "legendFormat": "P50"
    },
    {
     "expr": "avg(1000 * avg(gitaly:grpc_server_handling_seconds:avg5m{environment=\"$environment\",grpc_method=\"$method\"}))\n",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Per-Git-command latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(subcmd) (\n  rate(\n    gitaly_command_cpu_seconds_total{environment=\"$environment\",grpc_method=\"$method\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{subcmd}}"
    }
   ]
  },
  {
   "title": "Calls per Second per Tier",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{environment=\"$environment\",grpc_method=\"$method\"}[1m]))\n",
     "legendFormat": "now"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{environment=\"$environment\",grpc_method=\"$method\"}[1m] offset 1w))\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Call Rate vs 1 week prior (log₁₀)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:rate1m {environment=\"$environment\",grpc_method=\"$method\"})\n",
     "legendFormat": "rate (1m)"
    },
    {
     "expr": "sum(gitaly:grpc_server_handled_total:rate1m{environment=\"$environment\",grpc_method=\"$method\"} offset 1w)\n",
     "legendFormat": "rate (1m) -1w"
    }
   ]
  },
  {
   "title": "Server Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{environment=\"$environment\",grpc_method=\"$method\"}[10m])) BY (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "12 hour error anomaly rates (log₁₀)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 250 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gitaly:grpc_server_handled_total:error_rate1m{environment=\"$environment\",grpc_method=\"$method\"}\n",
     "legendFormat": "{{ grpc_code }}"
    },
    {
     "expr": "gitaly:grpc_server_handled_total:error_avg_rate12h{environment=\"$environment\",grpc_method=\"$method\"}\n",
     "legendFormat": "12 hour avg"
    },
    {
     "expr": "gitaly:grpc_server_handled_total:error_avg_rate12h{environment=\"$environment\",grpc_method=\"$method\"} + gitaly:grpc_server_handled_total:error_rate1m_stddev_over_time12h{environment=\"$environment\",grpc_method=\"$method\"}\n",
     "legendFormat": "12 hour 2σ"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}