{
 "title": "Gitaly Housekeeping Statistics",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(gitaly_housekeeping_data_structure_size_bucket, env)"
    }
   },
   {
    "name": "method",
    "query": "OptimizeRepository,PruneUnreachableObjects"
   },
   {
    "name": "data_structures_size",
    "label": "Data structures (size)",
    "query": {
     "query": "label_values(gitaly_housekeeping_data_structure_size_bucket{env=\"$environment\"}, data_structure)"
    }
   },
   {
    "name": "data_structures_count",
    "label": "Data structures (count)",
    "query": {
     "query": "label_values(gitaly_housekeeping_data_structure_count_bucket{env=\"$environment\"}, data_structure)"
    }
   },
   {
    "name": "data_structures_time_since_last_optimization",
    "label": "Data structures (time since last optimization)",
    "query": {
     "query": "label_values(gitaly_housekeeping_time_since_last_optimization_seconds_bucket{env=\"$environment\"}, data_structure)"
    }
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "Optimizations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OptimizeRepository: Performed Optimizations",
   "type": "timeseries",
   "description": "The OptimizeRepository RPC is combining all the different maintenance tasks like repacking objects, repacking references or pruning objects into a single RPC. This metric keeps track of which subtasks get executed as part of OptimizeRepository to improve visibility into what the RPC does.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(gitaly_housekeeping_tasks_total{environment=\"$environment\"}[$__rate_interval])) by (housekeeping_task)",
     "legendFormat": "{{housekeeping_task}}"
    }
   ]
  },
  {
   "title": "OptimizeRepository: Per-Optimization Latencies",
   "type": "timeseries",
   "description": "The OptimizeRepository RPC is combining all the different maintenance tasks like repacking objects, repacking references or pruning objects into a single RPC. This metric keeps track of the latency of each of the subtasks executed as part of OptimizeRepository to improve visibility into what the RPC does.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_housekeeping_tasks_latency_bucket{environment=\"$environment\"}[$__rate_interval])) by (le,housekeeping_task))",
     "legendFormat": "{{housekeeping_task}} (P99)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitaly_housekeeping_tasks_latency_bucket{environment=\"$environment\"}[$__rate_interval])) by (le,housekeeping_task))",
     "legendFormat": "{{housekeeping_task}} (P95)"
    }
   ]
  },
  {
   "title": "OptimizeRepository: Accumulate Per-Optimization Timings",
   "type": "timeseries",
   "description": "The OptimizeRepository RPC is combining all the different maintenance tasks like repacking objects, repacking references or pruning objects into a single RPC. This metric keeps track of the accumulate time spent in each of the subtasks executed as part of OptimizeRepository to improve visibility into what the RPC does.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(gitaly_housekeeping_tasks_latency_sum{environment=\"$environment\"}[$__rate_interval])) by (housekeeping_task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stale File Pruning",
   "type": "timeseries",
   "description": "Gitaly's housekeeping tasks prune files which are not needed for normal operations or which have been left behind by Git processes due to reasons like crashes. This metric counts the number of files and directories we are pruning as part of this housekeeping task.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(gitaly_housekeeping_pruned_files_total{environment=\"$environment\"}[$__rate_interval])) by (filetype)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Repository State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Data structure existence",
   "type": "timeseries",
   "description": "This graph reports the percentage of repositories for which the given data structure is found to exist. Existence of data structures is reported during repository housekeeping.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(gitaly_housekeeping_data_structure_existence_total{exists=\"true\",env=\"$environment\"}[$__rate_interval])) by (data_structure)\n / \nsum(increase(gitaly_housekeeping_data_structure_existence_total{env=\"$environment\"}[$__rate_interval])) by (data_structure)",
     "legendFormat": "{{data_structure}}"
    }
   ]
  },
  {
   "title": "Size of $data_structures_size",
   "type": "heatmap",
   "description": "Total size of the given data structure. This data is reported for a repository whenever it is getting optimized.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "repeat": "data_structures_size",
   "targets": [
    {
     "expr": "sum(increase(gitaly_housekeeping_data_structure_size_bucket{env=\"$environment\",data_structure=\"$data_structures_size\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Count of $data_structures_count",
   "type": "heatmap",
   "description": "Number of instances that exist of the given data structure. This data is reported for a repository whenever it is getting optimized.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "repeat": "data_structures_count",
   "targets": [
    {
     "expr": "sum(increase(gitaly_housekeeping_data_structure_count_bucket{env=\"$environment\", data_structure=\"$data_structures_count\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time since last optimization for $data_structures_time_since_last_optimization",
   "type": "heatmap",
   "description": "Time when $data_structures_time_since_last_optimization has last been optimized",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "repeat": "data_structures_time_since_last_optimization",
   "targets": [
    {
     "expr": "sum(increase(gitaly_housekeeping_time_since_last_optimization_seconds_bucket{env=\"$environment\",data_structure=\"$data_structures_time_since_last_optimization\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Per-RPC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Housekeeping RPC Rate: $method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "repeat": "method",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:rate1m{environment=\"$environment\",grpc_method=\"$method\"} - sum(gitaly:grpc_server_handled_total:error_rate1m{environment=\"$environment\", grpc_method=\"$method\"}) without (grpc_code))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(gitaly:grpc_server_handled_total:error_rate1m{environment=\"$environment\", grpc_method=\"$method\"}) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Housekeeping RPC Latency: $method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "repeat": "method",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{environment=\"$environment\", grpc_method=\"$method\"}) by (le)) * 1000",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{environment=\"$environment\", grpc_method=\"$method\"}) by (le)) * 1000",
     "legendFormat": "P95"
    }
   ]
  }
 ]
}