{
 "title": "Gitaly Concurrency Queue",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" }
  ]
 },
 "panels": [
  {
   "title": "Total Dropped Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gitaly_requests_dropped_total", "legendFormat": "Total Dropped Requests" }
   ]
  },
  {
   "title": "FetchRemote Acquiring Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_rate_limiting_acquiring_seconds_bucket{environment=\"$environment\",grpc_method=\"FetchRemote\"}[5m])) by (le))",
     "legendFormat": "Acquiring Seconds"
    }
   ]
  },
  {
   "title": "FetchRemote Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "max(gitaly_rate_limiting_queued{environment=\"$environment\", grpc_method=\"FetchRemote\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "SSHUploadPackWithSidechannel Acquiring Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_rate_limiting_acquiring_seconds_bucket{environment=\"$environment\",grpc_method=\"SSHUploadPackWithSidechannel\"}[5m])) by (le))",
     "legendFormat": "Acquiring Seconds"
    }
   ]
  },
  {
   "title": "PostUploadPackWithSidechannel Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "max(gitaly_rate_limiting_queued{environment=\"$environment\", grpc_method=\"PostUploadPackWithSidechannel\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "PostUploadPackWithSideChannel Acquiring Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_rate_limiting_acquiring_seconds_bucket{environment=\"$environment\",grpc_method=\"PostUploadPackWithSidechannel\"}[5m])) by (le))",
     "legendFormat": "Acquiring Seconds"
    }
   ]
  },
  {
   "title": "SSHUploadPackWithSidechannel Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "max(gitaly_rate_limiting_queued{environment=\"$environment\", grpc_method=\"SSHUploadPackWithSidechannel\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GetArchive Acquiring Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_rate_limiting_acquiring_seconds_bucket{environment=\"$environment\",grpc_method=\"GetArchive\"}[5m])) by (le))",
     "legendFormat": "Acquiring Seconds"
    }
   ]
  },
  {
   "title": "GerArchive Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "max(gitaly_rate_limiting_queued{environment=\"$environment\", grpc_method=\"GetArchive\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "InfoRefsUploadPack Acquiring Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_rate_limiting_acquiring_seconds_bucket{environment=\"$environment\",grpc_method=\"InfoRefsUploadPack\"}[5m])) by (le))",
     "legendFormat": "Acquiring Seconds"
    }
   ]
  },
  {
   "title": "InfoRefsUploadPack Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "max(gitaly_rate_limiting_queued{environment=\"$environment\", grpc_method=\"InfoRefsUploadPack\"})",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}