{
 "title": "Gitaly Feature Status",
 "tags": [
  "Gitaly",
  "unmanaged"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg" },
   {
    "name": "method",
    "label": "method",
    "query": "grpc_server_handled_total{grpc_code=\"OK\"}"
   },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Success Ratio (SLA)",
   "type": "graph",
   "description": "This graph represents the percentage of requests\nthat succeed.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (sum(gitaly:grpc_server_handled_total:error_rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) without (grpc_code) / gitaly:grpc_server_handled_total:rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Success Rate %",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(1000 * avg(gitaly:grpc_server_handling_seconds:avg5m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}))\n\n\n",
     "legendFormat": "mean latency"
    },
    {
     "expr": "\navg(1000 * avg(gitaly:grpc_server_handling_seconds:avg5m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"} offset 1w))\n",
     "legendFormat": "mean latency (1 week prior)"
    },
    {
     "expr": "avg(1000 * avg(gitaly:grpc_server_handling_seconds:avg24h{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"} + 2 * gitaly:grpc_server_handling_seconds:avg5m_stddev_over_time24h{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}))\n",
     "legendFormat": "latency 2σ"
    }
   ]
  },
  {
   "title": "Total Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:rate1m{job=\"gitaly\",environment=\"$environment\",grpc_method=\"$method\"}) by (grp_method)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{grpc_method}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitaly:grpc_server_handled_total:rate1m{job=\"gitaly\",environment=\"$environment\",grpc_method=\"$method\"} - sum(gitaly:grpc_server_handled_total:error_rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) without (grpc_code)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{grpc_code}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failures Rate (per second)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:error_rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) by (grpc_code)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{grpc_code}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "99th Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) by (le)) * 1000",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"} offset 1w) by (le)) * 1000",
     "legendFormat": "p99 (1 week prior)"
    },
    {
     "expr": "sum(grpc_server_handling_seconds_sum{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) / sum(grpc_server_handling_seconds_count{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) * 1000",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) by (le)) * 1000",
     "legendFormat": "p95 (File Server)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"} offset 1w) by (le)) * 1000",
     "legendFormat": "p95 (File Server) (1 week prior)"
    }
   ]
  },
  {
   "title": "Median Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) by (le)) * 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.5, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"} offset 1w) by (le)) * 1000",
     "legendFormat": "p50 (1 week prior)"
    }
   ]
  },
  {
   "title": "Calls per Second per Tier",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}[1m]))",
     "legendFormat": "now"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}[1m] offset 1w))",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Call Rate vs 1 week prior (log₁₀)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:rate1m {job=\"gitaly\", grpc_method=\"$method\"})\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "rate (1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(gitaly:grpc_server_handled_total:rate1m{job=\"gitaly\", grpc_method=\"$method\"} offset 1w)",
     "legendFormat": "rate (1m) -1w"
    }
   ]
  },
  {
   "title": "Server Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}[10m])) BY (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "12 hour error anomaly rates (log₁₀)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitaly:grpc_server_handled_total:error_rate1m{job=\"gitaly\",environment=\"$environment\",grpc_method=\"$method\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ grpc_code }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "gitaly:grpc_server_handled_total:error_avg_rate12h{job=\"gitaly\",environment=\"$environment\",grpc_method=\"$method\"}",
     "legendFormat": "12 hour avg"
    },
    {
     "expr": "gitaly:grpc_server_handled_total:error_avg_rate12h{job=\"gitaly\",environment=\"$environment\",grpc_method=\"$method\"} +  gitaly:grpc_server_handled_total:error_rate1m_stddev_over_time12h{environment=\"gitaly\", job=\"$job\"}",
     "legendFormat": "12 hour 2σ"
    }
   ]
  },
  {
   "title": "Rate Limiting",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitaly_rate_limiting_in_progress{grpc_method=\"$method\", environment=\"$environment\"}) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "In Progress - {{ fqdn }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(gitaly_rate_limiting_queued{grpc_method=\"$method\", environment=\"$environment\"}) by (fqdn)",
     "legendFormat": "Queued - {{ fqdn }}"
    }
   ]
  }
 ]
}