{
 "title": "Gitaly Catfile Statistics",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg" },
   {
    "name": "method",
    "label": "method",
    "query": "ListBlobs,ListAllBlobs,ListLFSPointers,ListAllLFSPointers,GetLFSPointers,ListAllCommits,ListCommits,FindAllTags,GetTagSignatures,GetTreeEntries\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Active catfile processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gitaly_catfile_processes_total{env=\"$environment\"}[$__rate_interval]))",
     "legendFormat": "Total processes"
    },
    {
     "expr": "sum(rate(gitaly_catfile_cache_total{env=\"$environment\"}[$__rate_interval])) by (type)",
     "legendFormat": "Cache: {{type}}"
    }
   ]
  },
  {
   "title": "Catfile Lookups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gitaly_catfile_lookups_total{env=\"$environment\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Catfile-based method latency: $method",
   "type": "timeseries",
   "description": "Median latency of catfile-based method.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "repeat": "method",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(gitaly:grpc_server_handling_seconds_bucket:rate1m{environment=\"$environment\", grpc_method=\"$method\"}) by (le)) * 1000",
     "legendFormat": "Median latency"
    }
   ]
  },
  {
   "title": "Catfile-based method rate: $method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "repeat": "method",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(gitaly:grpc_server_handled_total:rate1m{environment=\"$environment\",grpc_method=\"$method\"} - sum(gitaly:grpc_server_handled_total:error_rate1m{environment=\"$environment\", grpc_method=\"$method\"}) without (grpc_code))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(gitaly:grpc_server_handled_total:error_rate1m{job=\"gitaly\", environment=\"$environment\", grpc_method=\"$method\"}) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  }
 ]
}