{
 "title": "Gitaly Request Limiting",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg,gstg-ref" }
  ]
 },
 "panels": [
  {
   "title": "Dropped Requests - Queue Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gitaly_requests_dropped_total{env=\"$environment\", reason=\"max_time\"}[$__rate_interval])) by (grpc_method)",
     "legendFormat": "{{reason}} {{grpc_method}}"
    }
   ]
  },
  {
   "title": "Dropped Requests - Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(gitaly_requests_dropped_total{env=\"$environment\", reason=\"max_size\"}[$__rate_interval])) by (grpc_method)\n"
    }
   ]
  },
  {
   "title": "Dropped Requests - Rate Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(gitaly_requests_dropped_total{env=\"$environment\", reason=\"rate\"}[$__rate_interval])) by (grpc_method)\n"
    }
   ]
  },
  {
   "title": "FetchRemote Acquiring Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_concurrency_limiting_acquiring_seconds_bucket{environment=\"$environment\",grpc_method=\"FetchRemote\"}[5m])) by (le))",
     "legendFormat": "Acquiring Seconds"
    }
   ]
  },
  {
   "title": "RepositorySize Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max(gitaly_concurrency_limiting_queued{environment=\"$environment\", grpc_method=\"RepositorySize\"})"
    }
   ]
  },
  {
   "title": "SSHUploadPackWithSidechannel Acquiring Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_concurrency_limiting_acquiring_seconds_bucket{environment=\"$environment\",grpc_method=\"SSHUploadPackWithSidechannel\"}[5m])) by (le))",
     "legendFormat": "Acquiring Seconds"
    }
   ]
  },
  {
   "title": "FetchRemote Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "max(gitaly_concurrency_limiting_queued{environment=\"$environment\", grpc_method=\"FetchRemote\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "PostUploadPackWithSideChannel Acquiring Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_concurrency_limiting_acquiring_seconds_bucket{environment=\"$environment\",grpc_method=\"PostUploadPackWithSidechannel\"}[5m])) by (le))",
     "legendFormat": "Acquiring Seconds"
    }
   ]
  },
  {
   "title": "PostUploadPackWithSidechannel Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "max(gitaly_concurrency_limiting_queued{environment=\"$environment\", grpc_method=\"PostUploadPackWithSidechannel\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "SSHUploadPackWithSidechannel Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "max(gitaly_concurrency_limiting_queued{environment=\"$environment\", grpc_method=\"SSHUploadPackWithSidechannel\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GetArchive Acquiring Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_concurrency_limiting_acquiring_seconds_bucket{environment=\"$environment\",grpc_method=\"GetArchive\"}[5m])) by (le))",
     "legendFormat": "Acquiring Seconds"
    }
   ]
  },
  {
   "title": "InfoRefsUploadPack Acquiring Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_concurrency_limiting_acquiring_seconds_bucket{environment=\"$environment\",grpc_method=\"InfoRefsUploadPack\"}[5m])) by (le))",
     "legendFormat": "Acquiring Seconds"
    }
   ]
  },
  {
   "title": "GerArchive Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "max(gitaly_concurrency_limiting_queued{environment=\"$environment\", grpc_method=\"GetArchive\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "InfoRefsUploadPack Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "max(gitaly_concurrency_limiting_queued{environment=\"$environment\", grpc_method=\"InfoRefsUploadPack\"})",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}