{
 "title": "gitaly: Gitaly multi-project move",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5164311687 at Tue Sep 26 07:47:55 UTC 2023",
 "tags": [
  "managed",
  "gitaly",
  "gitaly",
  "type:gitaly"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  { "title": "Migration Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Repositories on old Gitaly VMs",
   "type": "graph",
   "description": "Total number of repositories that are on the old Gitaly VMs that we are migrating away from.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (gitaly_total_repositories_count{env=\"$environment\",environment=\"$environment\",fqdn=~\"file-(marquee-)?\\\\d+-stor-.*\",prefix=~\"@.*\",type=\"gitaly\"})\n",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Repositories on new Gitaly VMs",
   "type": "graph",
   "description": "Total number of repositories that we have on the new Gitaly VMs.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (gitaly_total_repositories_count{env=\"$environment\",environment=\"$environment\",fqdn=~\"gitaly-.*-stor-.*\",prefix=~\"@.*\",type=\"gitaly\"})\n",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "REDME",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1001 },
   "content": "## Introduction\n\nThis dashboard is to track progress for the [multi-project Gitaly](https://gitlab.com/groups/gitlab-com/gl-infra/-/epics/935) epic\nto migrate from the old infrastructure to the new infrastructure.\n\nYou can track how many repositories we have on the old Gitaly VMs and\nnew Gitaly VMs and check the rate at which we are moving\nthese repositories below. Any failures on moving a repository will show up below as well, and you\ncan check the logs for the failure reason.\n\n## Debugging\n\n- 🪵 [`gitalyctl` Logs](https://dashboards.gitlab.net/explore?orgId=1&left=%7B%22datasource%22:%22R8ugoM-Vk%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22gitalyctl%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22R8ugoM-Vk%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D)\n- [🔥 `gitalyctl` Error Logs](https://dashboards.gitlab.net/explore?orgId=1&left=%7B%22datasource%22:%22R8ugoM-Vk%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22gitalyctl%5C%22%7D%20%7C%20json%20level%3D%5C%22level%5C%22%20%7C%20level%20%3D%20%60error%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22R8ugoM-Vk%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D)\n- [💿 `gstg` API logs](https://nonprod-log.gitlab.net/app/r/s/mGwlo)\n- [💿 `gprd` API logs](https://log.gprd.gitlab.net/app/r/s/nVbro)\n- [🦵 `gstg` sidekiq logs for repository moves](https://nonprod-log.gitlab.net/app/r/s/GS5F1)\n- [🦵 `gprd` sidekiq logs for repository moves](https://log.gprd.gitlab.net/app/r/s/urrqF)\n\n## References\n\n- [Epic](https://gitlab.com/groups/gitlab-com/gl-infra/-/epics/935)\n- [Design Doc](https://gitlab.com/gitlab-com/gl-infra/readiness/-/blob/master/library/gitaly-multi-project/README.md)\n- [Issue Board](https://gitlab.com/groups/gitlab-com/gl-infra/-/boards/5908541?label_name[]=WG%3A%3ADisasterRecovery&group_by=epic)\n"
  },
  { "title": "gitalyctl concurrency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1100 } },
  {
   "title": "Storage Concurrency",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitalyctl_projects_storage_concurrency{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}\n"
    }
   ]
  },
  {
   "title": "Projects Concurrency",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitalyctl_projects_repository_concurrency{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}\n"
    }
   ]
  },
  {
   "title": "Groups Concurrency",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitalyctl_groups_repository_concurrency{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}\n"
    }
   ]
  },
  {
   "title": "Snippets Concurrency",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitalyctl_snippets_repository_concurrency{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}\n"
    }
   ]
  },
  { "title": "gitalyctl logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1200 } },
  {
   "title": "Info Logs",
   "type": "graph",
   "description": "How many info logs we have for gitalyctl",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({namespace=\"gitalyctl\", container=\"gitalyctl\"} |= `info` [$__interval])\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "graph",
   "description": "How many error logs we have for gitalyctl",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({namespace=\"gitalyctl\", container=\"gitalyctl\"} | json level=\"level\" | level = `error` [$__interval])\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "gitalyctl projects repositories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1300 }
  },
  {
   "title": "Active moves",
   "type": "graph",
   "description": "Total number of moves per storage that are currently happening.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (gitalyctl_projects_active_repository_moves{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"})\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "graph",
   "description": "Rate/sec of successful projects repository moves.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (rate(gitalyctl_projects_successful_repository_moves_total{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}[$__rate_interval]))\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "Failure rate",
   "type": "graph",
   "description": "Rate/sec of failed projects repository moves.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (rate(gitalyctl_projects_failed_repository_moves_total{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}[$__rate_interval]))\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "Wait timeout rate",
   "type": "graph",
   "description": "Rate/sec of projects repository moves that tiemout. The timeout is set by project.move_timeout configuration. However, reaching this timeout doesn't necessarily indicate the success or failure of the repository move.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (rate(gitalyctl_projects_timed_out_repository_moves_total{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}[$__rate_interval]))\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  { "title": "gitalyctl groups repositories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1400 } },
  {
   "title": "Active moves",
   "type": "graph",
   "description": "Total number of moves per storage that are currently happening.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (gitalyctl_groups_active_repository_moves{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"})\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "graph",
   "description": "Rate/sec of successful groups repository moves.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (rate(gitalyctl_groups_successful_repository_moves_total{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}[$__rate_interval]))\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "Failure rate",
   "type": "graph",
   "description": "Rate/sec of failed groups repository moves.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (rate(gitalyctl_groups_failed_repository_moves_total{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}[$__rate_interval]))\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "Wait timeout rate",
   "type": "graph",
   "description": "Rate/sec of groups repository moves that tiemout. The timeout is set by project.move_timeout configuration. However, reaching this timeout doesn't necessarily indicate the success or failure of the repository move.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (rate(gitalyctl_groups_timed_out_repository_moves_total{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}[$__rate_interval]))\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "gitalyctl snippets repositories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1500 }
  },
  {
   "title": "Active moves",
   "type": "graph",
   "description": "Total number of moves per storage that are currently happening.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1501 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (gitalyctl_snippets_active_repository_moves{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"})\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "graph",
   "description": "Rate/sec of successful snippets repository moves.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1501 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (rate(gitalyctl_snippets_successful_repository_moves_total{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}[$__rate_interval]))\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "Failure rate",
   "type": "graph",
   "description": "Rate/sec of failed snippets repository moves.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1501 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (rate(gitalyctl_snippets_failed_repository_moves_total{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}[$__rate_interval]))\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "Wait timeout rate",
   "type": "graph",
   "description": "Rate/sec of snippets repository moves that tiemout. The timeout is set by project.move_timeout configuration. However, reaching this timeout doesn't necessarily indicate the success or failure of the repository move.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1501 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage) (rate(gitalyctl_snippets_timed_out_repository_moves_total{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}[$__rate_interval]))\n",
     "legendFormat": "{{ storage }}"
    }
   ]
  },
  {
   "title": "USE method gitalyctl deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1600 }
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1601 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}[$__rate_interval])\n",
     "legendFormat": "{{ cpu }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\", unit=\"core\"}\n",
     "legendFormat": "limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\", unit=\"core\"}\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1601 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\"}[$__rate_interval])\n",
     "legendFormat": "current"
    },
    {
     "expr": "kube_pod_container_resource_limits{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\", unit=\"byte\"}\n",
     "legendFormat": "limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{container=\"gitalyctl\",env=\"ops\",environment=\"ops\",namespace=\"gitalyctl\", unit=\"byte\"}\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}