{
 "title": "GithubImporter: Object Counters",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Issue Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(github_importer_fetched_issue{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "fetched"
    },
    {
     "expr": "sum(rate(github_importer_imported_issue{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "imported"
    }
   ]
  },
  {
   "title": "Issue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_importer_fetched_issue{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "fetched"
    },
    {
     "expr": "sum(rate(github_importer_imported_issue{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "imported"
    }
   ]
  },
  {
   "title": "Pull Request Diff",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(github_importer_fetched_pull_request{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "fetched"
    },
    {
     "expr": "sum(rate(github_importer_imported_pull_request{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "imported"
    }
   ]
  },
  {
   "title": "Pull Request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_importer_fetched_pull_request{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "fetched"
    },
    {
     "expr": "sum(rate(github_importer_imported_pull_request{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "imported"
    }
   ]
  },
  {
   "title": "Issue Fetched",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(github_importer_fetched_issue{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "fetched"
    }
   ]
  },
  {
   "title": "Pull Request Fetched",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(github_importer_fetched_pull_request{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "fetched"
    }
   ]
  },
  {
   "title": "Issue Imported",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(github_importer_imported_issue{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "fetched"
    }
   ]
  },
  {
   "title": "Pull Request Imported",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(github_importer_imported_pull_request{env=\"gprd\"}[$__interval])) * 3600",
     "legendFormat": "fetched"
    }
   ]
  }
 ]
}