{
 "title": "GitHub / GitLab Performance",
 "tags": [
  "product performance",
  "unmanaged"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "function", "query": "min, mean,median,p90,max" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "### Comparison of GitLab and GitHub performance\n\n\n\n"
   },
   "content": "### Comparison of GitLab and GitHub performance\n\n\n\n"
  },
  { "title": "Largest Contentful Paint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Project Home",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.GitLab_Project_Home.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 4)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.github_com.GitHub_Project_Home.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 4)"
    }
   ]
  },
  {
   "title": "Issue List",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.GitLab_Issue_list.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 4)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.github_com.GitHub_Issue_List.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 4)"
    }
   ]
  },
  {
   "title": "Issue Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.GitLab_Issue_Detail.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 4)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.github_com.GitHub_Issue_Detail.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 4)"
    }
   ]
  },
  {
   "title": "MR List",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.GitLab_Merge_List.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 4)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.github_com.GitHub_Merge_List.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 4)"
    }
   ]
  },
  {
   "title": "MR Detail",
   "type": "graph",
   "description": "GitLab being faster is misleading in this case. We paint a large chunk initially, but many details come much later than GitHub: https://forgeperf.org/results/GitLab.patch-discussion.report.html. TTI is 10+ seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.GitLab_Merge_Detail.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 4)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.github_com.GitHub_Merge_Detail.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 4)"
    }
   ]
  }
 ]
}