{
 "title": "GitLab Workhorse [deprecated]",
 "tags": [
  "unmanaged",
  "deprecated"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "prometheus_app", "query": "prometheus" },
   {
    "name": "method",
    "query": "label_values(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"$environment\"},method)"
   },
   {
    "name": "code",
    "query": "label_values(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"$environment\"},code)"
   },
   {
    "name": "type",
    "query": "label_values(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"$environment\"},type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "content": "![](https://media.giphy.com/media/l0HlKrB02QY0f1mbm/giphy.gif)"
  },
  {
   "title": "Deprecation  Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 0 },
   "content": "# Deprecated ⚠️⚠️⚠️⚠️⚠️\n\nThis dashboard is deprecated, please consider switching over to the new service based dashboards:\n\n* [api](/d/api-main/api-overview)\n* [web](/d/git-main/git-overview)\n* [git](/d/web-main/web-overview)\n\n\n"
  },
  {
   "title": "Workhorse Queuing Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"$environment\",method=\"$method\",code=\"$code\", type=\"$type\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Sessions active",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_workhorse_http_sessions_active",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git HTTP operations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 24 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_workhorse_git_http_bytes)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git HTTP operations - requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_workhorse_git_http_requests)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git HTTP active sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_workhorse_git_http_sessions_active) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Static error responses served (1m rate)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_static_error_responses[1m])) by (fqdn)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git HTTP operations 1m rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_git_http_bytes[1m])) by (direction,agent,method,service)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{service}}: {{method}}, {{direction}} ({{agent}})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git HTTP operations 1m rate - requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_git_http_requests[1m])) by (direction,agent,method,service)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{service}}: {{method}} ({{agent}})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git HTTP transfer distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_git_http_bytes{agent=\"gitlab-ci\"}[1h])) / sum(rate(gitlab_workhorse_git_http_bytes[1h]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "gitlab-ci",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(gitlab_workhorse_git_http_bytes{agent=\"logged\"}[1h])) / sum(rate(gitlab_workhorse_git_http_bytes[1h]))",
     "legendFormat": "logged"
    },
    {
     "expr": "sum(rate(gitlab_workhorse_git_http_bytes{agent=\"anonymous\"}[1h])) / sum(rate(gitlab_workhorse_git_http_bytes[1h]))",
     "legendFormat": "anonymous"
    }
   ]
  },
  {
   "title": "Sendfile",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 53 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_workhorse_sendfile_bytes)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sendfile - requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 53 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_workhorse_sendfile_requests)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sendfile 1m rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_sendfile_bytes[1m])) by (type)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sendfile 1m rate - requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_sendfile_requests[1m])) by (type)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Multipart uploads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 63 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_workhorse_multipart_upload_bytes)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Multipart uploads - requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 63 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_workhorse_multipart_upload_requests)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Multipart uploads - files",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 63 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_workhorse_multipart_upload_files)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Multipart uploads 1m rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_multipart_upload_bytes[1m])) by (type)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Multipart uploads 1m rate - requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_multipart_upload_requests[1m])) by (type)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Multipart uploads 1m rate - files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_multipart_upload_files[1m])) by (type)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}