{
 "title": "GitLab Triage Copy",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(gitlab_service_ops:rate, env)"
    }
   },
   {
    "name": "backend",
    "query": {
     "query": "label_values(backend:haproxy_backend_availability:ratio{env=\"$env\"}, backend)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(up{env=\"$env\"}, type)"
    }
   },
   {
    "name": "stage",
    "query": {
     "query": "label_values(up{env=\"$env\"}, stage)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Blackbox and Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GitLab.com",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\",monitor=\"default\",instance=\"https://gitlab.com\", job=\"blackbox-tls-redirect\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "alerts" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(ALERTS{env=\"$env\",monitor=\"default\",alertstate=\"firing\"}[$__interval])) OR vector(0)"
    }
   ]
  },
  {
   "title": "GitLab Registry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\",monitor=\"default\",instance=\"https://registry.gitlab.com\", job=\"blackbox\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Application",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "alerts" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(ALERTS{env=\"$env\",monitor=\"app\",alertstate=\"firing\"}[$__interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Reboots (last 48h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reboots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count(\n    (time() - node_boot_time_seconds{env=\"$env\",monitor=\"default\"}) / \n    3600 < 48\n  ) by (fqdn)\n)"
    }
   ]
  },
  {
   "title": "GitLab Pages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\",instance=\"https://prod.pages-check.gitlab.net\",job=\"blackbox\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "gitlab.com sign-in",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\",instance=\"https://int.${env}.gitlab.net:11443/users/sign_in\",job=\"blackbox\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$env Internal LB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\",instance=\"https://int.${env}.gitlab.net:11443/-/liveness\",job=\"blackbox-internal\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chef errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(avg_over_time(chef_client_error{env=\"$env\"}[$__interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "HAProxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "5xx responses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(backend_code:haproxy_server_http_responses_total:irate1m{env=\"$env\",monitor=\"default\",code=\"5xx\"}[$__interval])) by (backend)",
     "legendFormat": "haproxy 5xx {{ backend }}"
    },
    {
     "expr": "sum without (zone) (avg_over_time(zone:stackdriver_haproxy_errors:rate1m{env=\"$env\",monitor=\"default\"}[$__interval]))",
     "legendFormat": "SD haproxy {{code}}"
    },
    {
     "expr": "sum without (zone) (zone:stackdriver_haproxy_deadline_exceeded:rate1m{env=\"$env\",monitor=\"default\"})",
     "legendFormat": "SD haproxy timeout"
    }
   ]
  },
  {
   "title": "HAProxy Backend Responses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(backend_code:haproxy_server_http_responses_total:irate1m{env=\"$env\",monitor=\"default\"}[$__interval])) by (backend)",
     "legendFormat": "Backend {{ backend }}"
    }
   ]
  },
  {
   "title": "HAProxy Frontend Responses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(frontend_code:haproxy_frontend_http_responses_total:irate1m{env=\"$env\",monitor=\"default\"}[$__interval])) by (frontend)",
     "legendFormat": "Frontend {{ frontend  }}"
    }
   ]
  },
  { "title": "HAProxy Backend Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "$backend",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 33 },
   "repeat": "backend",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Workhorse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Workhorse req/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg_over_time(job:gitlab_workhorse_http_requests_total:rate1m{env=\"$env\", monitor=\"default\", route!=\"^/-/\"}[$__interval])",
     "legendFormat": "{{stage}} {{type}} {{region}}"
    }
   ]
  },
  { "title": "Disk Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Repository Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg_over_time(instance:node_filesystem_avail:ratio{env=\"$env\",monitor=\"default\",type=\"gitaly\",mountpoint=\"/var/opt/gitlab\"}[$__interval])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "$type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 57 },
   "repeat": "type",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{env=\"$env\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{env=\"$env\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{env=\"$env\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Fleet load averages / 5xx HTTP codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 }
  },
  {
   "title": "Fleet load average",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_load1{env=\"$env\",type=~\"api|git|gitaly|postgres|redis|sidekiq|web\", stage=\"$stage\"}) by (type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_load{env=\"$env\",stage=\"$stage\"}"
    }
   ]
  },
  {
   "title": "5xx requests by backend-type",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(backend_code:haproxy_server_http_responses_total:irate1m{env=\"$env\",tier=\"lb\", code=\"5xx\", stage=\"$stage\"}) by (code,backend)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{backend}}-{{code}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Rails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "instance:rails_requests_started:rate1m{env=\"$env\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "status=200 p95 Latency Per Type",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "status:rails_requests_completed_seconds:p95{env=\"$env\",status=\"200\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rails 500 errors by backend type",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type)(rate(rails_requests_completed{env=\"$env\",status=~\"5..\"}[$__interval]))\n  /\nsum by (type)(rate(rails_requests_completed{env=\"$env\",status=~\"(2|5)..\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Gitaly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Gitaly GRPC Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "instance:gitaly_grpc_errors_total:rate1m{env=\"$env\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gitaly p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gitaly:grpc_server_handling_seconds:p95{env=\"$env\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Sidekiq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "sidekiq top3 queues over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(3,sidekiq_queue_size{env=\"$env\"} and on (fqdn) gitlab:redis_master{env=\"$env\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sidekiq load by priority",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_load1{env=\"$env\", tier=\"sv\", type=\"sidekiq\"}) by (priority)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{priority}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "PostgreSQL replication delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_replication_lag{env=\"$env\", tier=\"db\", type=\"patroni\"} and pg_replication_is_replica==1",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "top 3 insert rate by table",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(3, rate(pg_stat_user_tables_n_tup_ins{env=\"$env\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ relname }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "top 5 update rate by table",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,rate(pg_stat_user_tables_n_tup_upd{env=\"$env\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ relname }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_ms{env=\"$env\",tier=\"db\",type=\"patroni\"}[2m])/1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} {{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{env=\"$env\",tier=\"db\",type=\"patroni\"}[2m])",
     "legendFormat": "{{fqdn}} {{device}}"
    }
   ]
  },
  {
   "title": "Process Activity Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"gitlabhq_production\", env=\"$env\", tier=\"db\", type=\"patroni\"}",
     "legendFormat": "{{fqdn}} - {{state}}"
    }
   ]
  },
  {
   "title": "Process Activity Total by Host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"gitlabhq_production\", env=\"$env\", tier=\"db\", type=\"patroni\"}) by (fqdn)",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"gitlabhq_production\", env=\"$env\", tier=\"db\", type=\"patroni\"}[$__interval])",
     "legendFormat": "{{fqdn}} committed"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"gitlabhq_production\", env=\"$env\", tier=\"db\", type=\"patroni\"}[$__interval])",
     "legendFormat": "{{fqdn}} rolled back"
    }
   ]
  },
  {
   "title": "Slow Queries Count (> 1 second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_slow_queries{env=\"$env\", tier=\"db\", type=\"patroni\"}"
    }
   ]
  },
  { "title": "NFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "NFS timeouts rate per client",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(syslog_nfs_timeouts_total{env=\"$env\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NFS IOPS by server",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(node_disk_io_now{env=\"$env\",type=\"gitaly\"}) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Timeouts per NFS Server",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(syslog_nfs_timeouts{env=\"$env\"}[$__interval])) by (nfs_server)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}