{
 "title": "GitLab Web Status",
 "tags": [ "blackbox" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "app_prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "About", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "content": "This dashboard is built using blackbox monitoring. Each metric displayed here is the measurement of an HTTP get request from start to finish.\n\nUse this panel to compare staging vs production, to catch regressions and performance improvement progress"
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Issues as Annonymous User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"https://gitlab.com/.*?/issues/.*?\", job=\"blackbox\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Issues as Authenticated User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"https://gitlab.com.*?/issues/.*?\", job=\"blackbox-with-auth\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Merge Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Merge Request Index",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{job=\"blackbox-with-auth\", instance=~\"https://gitlab.com.*merge_requests$\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Merge Request Show",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{job=\"blackbox-with-auth\", instance=~\"https://gitlab.com.*merge_requests.*[0-9]$\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Merge Request Diff.json",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{job=\"blackbox\", instance=~\"https://gitlab.com.*merge_requests.*.diffs.json\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Project Tree Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\".*tree/master$\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline and Commits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pipelines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{job=\"blackbox\", instance=~\".*pipelines.*\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Commit",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{job=\"blackbox\", instance=~\".*gitlab.com/gitlab-org/.*/commit/.*$\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Tags and Branches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tags",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{job=\"blackbox\", instance=~\".*tags$\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Branches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{job=\"blackbox\", instance=~\".*branches$\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "API latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "API Latency - gitlab.org",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~\"blackbox-with-auth\", instance=~\"https://gitlab.com/api/.*$\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "www-gitlab-com project Latency - gitlab.org",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=~\"blackbox-with-auth\", instance=~\"https://gitlab.com/gitlab-com/www-gitlab-com.*$\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Project Exploration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Project Exploration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"https://gitlab.com/explore.*\", job=\"blackbox\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}