{
 "title": "GitLab Shell",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "label_values(gitlab_shell_request_seconds_count{job=\"mtail\"}, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn,instance)(rate(gitlab_shell_request_seconds_count{job=\"mtail\",environment=~\"$environment\"}[$__interval]))",
     "legendFormat": "{{environment}} {{method}} {{api}}"
    }
   ]
  },
  {
   "title": "Error Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn,instance)(rate(gitlab_shell_request_errors_total{job=\"mtail\",environment=~\"$environment\"}[$__interval]))",
     "legendFormat": "{{environment}} {{code}} {{method}} {{api}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (rate(gitlab_shell_request_seconds_bucket{job=\"mtail\",environment=~\"$environment\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Commands by command",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn,instance,shard)(rate(gitlab_shell_git_commands_total{job=\"mtail\",environment=~\"$environment\"}[$__interval]))",
     "legendFormat": "{{environment}} {{command}}"
    }
   ]
  },
  {
   "title": "Commands by shard",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn,instance,command)(rate(gitlab_shell_git_commands_total{job=\"mtail\",environment=~\"$environment\"}[$__interval]))",
     "legendFormat": "{{environment}} {{shard}}"
    }
   ]
  },
  {
   "title": "Command Access Denined",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn,instance)(rate(gitlab_shell_git_command_access_denied_total{job=\"mtail\",environment=~\"$environment\"}[$__interval]))",
     "legendFormat": "{{environment}} {{command}}"
    }
   ]
  }
 ]
}