{
 "title": "GitLab Pages Traffic",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(gitlab_service_ops:rate, env)"
    }
   },
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Average rate of requests per interval time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gitlab_pages_domains_source_cache_hit{env=\"$env\"}[$interval]))",
     "legendFormat": "Cache Hit"
    },
    {
     "expr": "sum(rate(gitlab_pages_domains_source_cache_miss{env=\"$env\"}[$interval]))",
     "legendFormat": "Cache Miss"
    },
    {
     "expr": "sum(rate(gitlab_pages_domains_source_cache_hit{env=\"$env\"}[$interval])) + sum(rate(gitlab_pages_domains_source_cache_miss{env=\"$env\"}[$interval]))",
     "legendFormat": "Cache Total"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average rate of requests per interval time (Cache Hit) - Detailed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(gitlab_pages_domains_source_cache_hit{env=\"$env\"}[$interval])",
       "legendFormat": "Namespace: {{namespace}}  Node: {{node}}"
      }
     ]
    },
    {
     "title": "Average rate of requests per interval time (Cache Miss) - Detailed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "rate(gitlab_pages_domains_source_cache_miss{env=\"$env\"}[$interval])",
       "legendFormat": "Namespace: {{namespace}}  Node: {{node}}"
      }
     ]
    }
   ]
  }
 ]
}