{
 "title": "GitLab Omnibus Versions",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "app_prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Majority Version",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, count(gitlab_version_info{environment=~\"$environment\", component=\"gitlab-rails\"}) by (version))",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Version distribution",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(gitlab_version_info{environment=~\"$environment\", component=\"gitlab-rails\"}) by (version)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Fleet size",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(gitlab_version_info{environment=~\"$environment\", component=\"gitlab-rails\"})"
    }
   ]
  },
  {
   "title": "Deviating Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "gitlab_version_info{environment=~\"$environment\", component=\"gitlab-rails\"} unless on (version) topk(1, count(gitlab_version_info{environment=~\"$environment\", component=\"gitlab-rails\"}) by (version))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Versions",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "gitlab_version_info{environment=~\"$environment\", component=\"gitlab-rails\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}