{
 "title": "gitlab-static: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4925911874 at Tue Aug 22 22:18:07 UTC 2023",
 "tags": [
  "managed",
  "gitlab-static",
  "gitlab",
  "type:gitlab-static",
  "gitlab-static",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "gitlab-static Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "gitlab-static error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitlab-static\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitlab-static\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "gitlab-static error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitlab-static\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "gitlab-static Service | Errors"
    }
   ]
  },
  {
   "title": "gitlab-static Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}[$__interval])\n",
     "legendFormat": "gitlab-static RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "gitlab_static_net_zone SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"gitlab_static_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "gitlab_static_net_zone error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_static_net_zone\",monitor=\"global\",type=\"gitlab-static\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_static_net_zone\",monitor=\"global\",type=\"gitlab-static\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"gitlab_static_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "gitlab_static_net_zone error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"gitlab_static_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_static_net_zone\",monitor=\"global\",type=\"gitlab-static\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"gitlab_static_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"gitlab_static_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_static_net_zone\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"gitlab_static_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_static_net_zone\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"gitlab_static_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_static_net_zone\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"gitlab_static_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_static_net_zone\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "gitlab_static_net_zone SLI | Errors"
    }
   ]
  },
  {
   "title": "gitlab_static_net_zone SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"gitlab_static_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}[$__interval])\n",
     "legendFormat": "gitlab_static_net_zone RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"gitlab_static_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Description\n\nAggregation of all public traffic for gitlab-static.net.\n\nErrors on this SLI *may* indicate that the WAF has detected\nmalicious traffic and is blocking it or upstream errors\nprocessing the request.\n\n"
  },
  {
   "title": "web_ide_worker SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"web_ide_worker\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "web_ide_worker error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"web_ide_worker\",monitor=\"global\",type=\"gitlab-static\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"web_ide_worker\",monitor=\"global\",type=\"gitlab-static\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"web_ide_worker\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "web_ide_worker error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"web_ide_worker\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"web_ide_worker\",monitor=\"global\",type=\"gitlab-static\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"web_ide_worker\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"web_ide_worker\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"web_ide_worker\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"web_ide_worker\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"web_ide_worker\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"web_ide_worker\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"web_ide_worker\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"web_ide_worker\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"web_ide_worker\",monitor=\"global\",type=\"gitlab-static\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "web_ide_worker SLI | Errors"
    }
   ]
  },
  {
   "title": "web_ide_worker SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"web_ide_worker\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"}[$__interval])\n",
     "legendFormat": "web_ide_worker RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"web_ide_worker\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"gitlab-static\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "content": "### Description\n\nCloudflare Worker used by our VS Code-based Web IDE to pull assets from *.cdn.web-ide.gitlab-static.net.\n\n"
  },
  {
   "title": "🔬 SLI Detail: gitlab_static_net_zone",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "gitlab_static_net_zone Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(cloudflare_zone_requests_status{env=\"ops\",environment=\"ops\",status=~\"5..\",zone=\"gitlab-static.net\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "gitlab_static_net_zone RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(cloudflare_zone_requests_total{env=\"ops\",environment=\"ops\",zone=\"gitlab-static.net\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: web_ide_worker",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "web_ide_worker Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(cloudflare_worker_errors_count{env=\"ops\",environment=\"ops\",script_name=\"gitlab-web-ide-vscode-production\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "web_ide_worker RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(cloudflare_worker_requests_count{env=\"ops\",environment=\"ops\",script_name=\"gitlab-web-ide-vscode-production\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph inf\n  gitlab-static\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph inf\n  gitlab-static\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph inf\n  gitlab-static[\"gitlab-static (Level 1)\"]\nend\n\n\n  \n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}