{
 "title": "GitLab Triage Copy Alb",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(up{job=\"prometheus\"}, env)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(up{job=\"prometheus\",env=\"$env\"}, environment)"
   },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "prometheus_app", "query": "prometheus" },
   {
    "name": "backend",
    "query": "label_values(backend:haproxy_backend_availability:ratio{env=\"$env\"}, backend)"
   },
   {
    "name": "type",
    "query": "label_values(up{environment=\"$environment\"}, type)\t"
   },
   {
    "name": "stage",
    "query": "label_values(up{environment=\"$environment\"}, stage)\t"
   }
  ]
 },
 "panels": [
  { "title": "Blackbox and Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GitLab.com",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\",monitor=\"default\",instance=\"https://gitlab.com\", job=\"blackbox-tls-redirect\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max_over_time(ALERTS{env=\"$env\",monitor=\"default\",alertstate=\"firing\"}[$__interval])) OR vector(0)"
    }
   ]
  },
  {
   "title": "GitLab Registry",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\",monitor=\"default\",instance=\"https://registry.gitlab.com\", job=\"blackbox\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Application",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max_over_time(ALERTS{env=\"$env\",monitor=\"app\",alertstate=\"firing\"}[$__interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Reboots (last 48h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(\n  count(\n    (time() - node_boot_time_seconds{env=\"$env\",monitor=\"default\"}) / \n    3600 < 48\n  ) by (fqdn)\n)"
    }
   ]
  },
  {
   "title": "GitLab Pages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\",instance=\"https://gitlab-examples.gitlab.io\",job=\"blackbox\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "gitlab.com sign-in",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\",instance=\"https://gitlab.com/users/sign_in\",job=\"blackbox\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$environment Internal LB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_success{env=\"$env\",instance=\"https://int.$environment.gitlab.net/-/liveness\",job=\"blackbox-internal\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chef errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(round(avg_over_time(chef_client_error{env=\"$env\"}[$__interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "HAProxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "5xx responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(backend_code:haproxy_server_http_responses_total:irate1m{env=\"$env\",monitor=\"default\",code=\"5xx\"}[$__interval])) by (backend)",
     "legendFormat": "haproxy 5xx {{ backend }}"
    },
    {
     "expr": "sum without (zone) (avg_over_time(zone:stackdriver_haproxy_errors:rate1m{env=\"$env\",monitor=\"default\"}[$__interval]))",
     "legendFormat": "SD haproxy {{code}}"
    },
    {
     "expr": "sum without (zone) (zone:stackdriver_haproxy_deadline_exceeded:rate1m{env=\"$env\",monitor=\"default\"})",
     "legendFormat": "SD haproxy timeout"
    }
   ]
  },
  {
   "title": "HAProxy Backend Responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(backend_code:haproxy_server_http_responses_total:irate1m{env=\"$environment\",monitor=\"default\"}[$__interval])) by (backend)",
     "legendFormat": "Backend {{ backend }}"
    }
   ]
  },
  {
   "title": "HAProxy Frontend Responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(frontend_code:haproxy_frontend_http_responses_total:irate1m{env=\"$env\",monitor=\"default\"}[$__interval])) by (frontend)",
     "legendFormat": "Frontend {{ frontend  }}"
    }
   ]
  },
  { "title": "HAProxy Backend Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 33 },
   "repeat": "backend",
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 33 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 36 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 36 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 36 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 36 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$backend",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 36 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(backend:haproxy_backend_availability:ratio{env=\"$env\",monitor=\"default\",backend=\"$backend\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Workhorse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Workhorse req/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:gitlab_workhorse_http_requests_total:rate1m{env=\"$env\",monitor=\"app\", route!=\"^/-/\"}[$__interval])",
     "legendFormat": "{{stage}} {{type}}"
    }
   ]
  },
  { "title": "Disk Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Repository Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg_over_time(instance:node_filesystem_avail:ratio{env=\"$env\",monitor=\"default\",type=\"gitaly\",mountpoint=\"/var/opt/gitlab\"}[$__interval])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Pages Storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg_over_time(instance:node_filesystem_avail:ratio{fqdn=~\"pages-.*\",mountpoint=\"/var/opt/gitlab\"}[$__interval])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 59 },
   "repeat": "type",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 65 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "$type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 89 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:node_cpu_utilization:avg_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:max_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(job:node_cpu_utilization:min_ratio{environment=\"$environment\", type=\"$type\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Fleet load averages / 5xx HTTP codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }
  },
  {
   "title": "Fleet load average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{type=~\"api|git|gitaly|postgres|redis|sidekiq|web\", stage=\"$stage\"}) by (type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_load{stage=\"$stage\"}"
    }
   ]
  },
  {
   "title": "5xx requests by backend-type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(backend_code:haproxy_server_http_responses_total:irate1m{tier=\"lb\", code=\"5xx\", stage=\"$stage\"}) by (code,backend)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{backend}}-{{code}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rails",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests per second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "instance:rails_requests_started:rate1m",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "status=200 p95 Latency Per Type",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 90 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "status:rails_requests_completed_seconds:p95{status=\"200\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{type}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Rails 500 errors by backend type",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 90 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (type)(rate(rails_requests_completed{status=~\"5..\"}[$__interval]))\n  /\nsum by (type)(rate(rails_requests_completed{status=~\"(2|5)..\"}[$__interval]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{type}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Gitaly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Gitaly GRPC Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance:gitaly_grpc_errors_total:rate1m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gitaly p95 Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "gitaly:grpc_server_handling_seconds:p95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Sidekiq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "sidekiq top3 queues over time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3,sidekiq_queue_size and on (fqdn) gitlab:redis_master)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sidekiq load by priority",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{tier=\"sv\", type=\"sidekiq\"}) by (priority)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{priority}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "PostgreSQL replication delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_replication_lag{environment=\"$environment\", tier=\"db\", type=\"patroni\"} and pg_replication_is_replica==1",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "top 3 insert rate by table",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3,rate(pg_stat_user_tables_n_tup_ins[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ relname }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "top 5 update rate by table",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,rate(pg_stat_user_tables_n_tup_upd[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ relname }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 115 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_ms{tier=\"db\",type=\"patroni\"}[2m])/1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} {{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{tier=\"db\",type=\"patroni\"}[2m])",
     "legendFormat": "{{fqdn}} {{device}}"
    }
   ]
  },
  {
   "title": "Process Activity Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"gitlabhq_production\", environment=\"$environment\", tier=\"db\", type=\"patroni\"}",
     "legendFormat": "{{fqdn}} - {{state}}"
    }
   ]
  },
  {
   "title": "Process Activity Total by Host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"gitlabhq_production\", environment=\"$environment\", tier=\"db\", type=\"patroni\"}) by (fqdn)",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "ops", "label": "Committed" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"gitlabhq_production\", environment=\"$environment\", tier=\"db\", type=\"patroni\"}[$__interval])",
     "legendFormat": "{{fqdn}} committed"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"gitlabhq_production\", environment=\"$environment\", tier=\"db\", type=\"patroni\"}[$__interval])",
     "legendFormat": "{{fqdn}} rolled back"
    }
   ]
  },
  {
   "title": "Slow Queries Count (> 1 second)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 121 },
   "yaxes": [
    { "format": "none", "label": "Committed" }
   ],
   "targets": [
    {
     "expr": "pg_slow_queries{environment=\"$environment\", tier=\"db\", type=\"patroni\"}"
    }
   ]
  },
  { "title": "NFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "NFS timeouts rate per client",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(syslog_nfs_timeouts_total[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NFS IOPS by server",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 128 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(node_disk_io_now{type=\"gitaly\"}) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Timeouts per NFS Server",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(syslog_nfs_timeouts[$__interval])) by (nfs_server)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Kills Per Sec", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "Unicorn",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(job:unicorn_killer_terminations_total:rate1m{type=~\"(web|git|api)\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sidekiq",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 134 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unicorn_killer_terminations_total{type=\"sidekiq\"}[$__interval])) without (instance, fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{priority}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}