{
 "title": "Gitlab SSHD",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(up{job=\"haproxy\"}, environment)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", environment=\"$env\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", environment=\"$env\", namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{env=\"$env\", namespace=\"$namespace\", pod=~\"$pod\", container=\"gitlab-shell\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sessions in flight",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitlab_shell_sshd_in_flight_connections{env=\"$env\", namespace=\"$namespace\", pod=~\"$pod\", container=\"gitlab-shell\"}"
    }
   ]
  },
  {
   "title": "Session duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (rate(gitlab_shell_sshd_session_duration_seconds_bucket{env=\"$env\", namespace=\"$namespace\", pod=~\"$pod\", container=\"gitlab-shell\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(gitlab_sli:shell_sshd_sessions:errors_total{env=\"$env\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])/rate(gitlab_sli:shell_sshd_sessions:total{env=\"$env\", namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (le) (rate(gitlab_shell_http_request_duration_seconds_bucket{env=\"$env\", namespace=\"$namespace\", pod=~\"$pod\", container=\"gitlab-shell\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Session established duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (le) (rate(gitlab_shell_sshd_session_established_duration_seconds_bucket{env=\"$env\", namespace=\"$namespace\", pod=~\"$pod\", container=\"gitlab-shell\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}