{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(go_goroutines, env)"
   },
   {
    "name": "job",
    "query": "label_values(go_goroutines{env=\"$env\"}, job)"
   },
   {
    "name": "instance",
    "query": "label_values(go_goroutines{env=\"$env\",job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - RSS"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Go Stack"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Go Heap"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}[$__interval])"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(up{env=\"$env\",job=\"$job\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}