{
 "title": "google-cloud-storage: Artifact CDN Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7764343875 at Fri Sep  6 13:59:14 UTC 2024",
 "tags": [
  "managed",
  "google-cloud-storage",
  "google-cloud-storage",
  "type:google-cloud-storage"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  { "title": "GCS Bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Total Size",
   "type": "graph",
   "description": "Total size of objects per bucket. Values are measured once per day.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "stackdriver_gcs_bucket_storage_googleapis_com_storage_total_bytes{bucket_name=~\"gitlab-.*-artifacts\", environment=\"$environment\"}",
     "legendFormat": "{{ bucket_name }}"
    }
   ]
  },
  { "title": "Cloud CDN Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Percentage of HTTP Requests CACHE HIT by response",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{cache_result=\"HIT\", environment=\"$environment\", forwarding_rule_name=~\".*artifacts-cdn.*\"}) by (response_code) / sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{environment=\"$environment\", forwarding_rule_name=~\".*artifacts-cdn.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "HTTP Requests CACHE HIT (bytes)",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_request_bytes_count{cache_result=\"HIT\", environment=\"$environment\", forwarding_rule_name=~\".*artifacts-cdn.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "Percentage of HTTP Requests CACHE MISS by response",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*artifacts-cdn.*\"}) by (response_code) / sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{environment=\"$environment\", forwarding_rule_name=~\".*artifacts-cdn.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "HTTP Requests CACHE MISS (bytes)",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2011 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_request_bytes_count{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*artifacts-cdn.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  { "title": "Cloud CDN Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "60th Percentile Latency CACHE HIT",
   "type": "graph",
   "description": "60th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.6,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"HIT\", environment=\"$environment\", forwarding_rule_name=~\".*artifacts-cdn.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "90th Percentile Latency CACHE HIT",
   "type": "graph",
   "description": "90th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"HIT\", environment=\"$environment\", forwarding_rule_name=~\".*artifacts-cdn.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "60th Percentile Latency CACHE MISS",
   "type": "graph",
   "description": "60th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.6,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*artifacts-cdn.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "90th Percentile Latency CACHE MISS",
   "type": "graph",
   "description": "90th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*artifacts-cdn.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  }
 ]
}