{
 "title": "google-cloud-storage: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5310688219 at Tue Oct 17 13:07:05 UTC 2023",
 "tags": [
  "managed",
  "google-cloud-storage",
  "gitlab",
  "type:google-cloud-storage",
  "google-cloud-storage",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "google-cloud-storage Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "google-cloud-storage apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "google-cloud-storage apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "google-cloud-storage Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "google-cloud-storage Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "google-cloud-storage error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "google-cloud-storage error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "google-cloud-storage Service | Errors"
    }
   ]
  },
  {
   "title": "google-cloud-storage Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "google-cloud-storage RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "artifacts_cdn SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"artifacts_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "artifacts_cdn error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"artifacts_cdn\",monitor=\"global\",type=\"google-cloud-storage\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"artifacts_cdn\",monitor=\"global\",type=\"google-cloud-storage\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"artifacts_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "artifacts_cdn error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"artifacts_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"artifacts_cdn\",monitor=\"global\",type=\"google-cloud-storage\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"artifacts_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"artifacts_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"artifacts_cdn\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"artifacts_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"artifacts_cdn\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"artifacts_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"artifacts_cdn\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"artifacts_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"artifacts_cdn\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "artifacts_cdn SLI | Errors"
    }
   ]
  },
  {
   "title": "artifacts_cdn SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"artifacts_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "artifacts_cdn RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"artifacts_cdn\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Observability Tools\n\n* [Google Load Balancer](https://console.cloud.google.com/net-services/loadbalancing/details/http/gprd-artifacts-cdn?project=gitlab-production)\n* [Stackdriver Logs: Loadbalancer Access Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Eurl%5Fmap%5Fname%3D%22gprd%2Dartifacts%2Dcdn%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-production)\n* [Stackdriver Logs: Loadbalancer Access 5xx Logs](https://console.cloud.google.com/logs/query;query=httpRequest%2Estatus%3E%3D500%0Aresource%2Elabels%2Eurl%5Fmap%5Fname%3D%22gprd%2Dartifacts%2Dcdn%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-production)\n\n"
  },
  {
   "title": "pages_range_requests SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"pages_range_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "pages_range_requests apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"pages_range_requests\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"pages_range_requests\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"pages_range_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "pages_range_requests apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"pages_range_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"pages_range_requests\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"pages_range_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"pages_range_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"pages_range_requests\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"pages_range_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"pages_range_requests\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"pages_range_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"pages_range_requests\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"pages_range_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"pages_range_requests\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "pages_range_requests SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "pages_range_requests SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"pages_range_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "pages_range_requests RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"pages_range_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "content": "### Description\n\nMonitors the latency of time-to-first-byte of HTTP range requests issued from GitLab Pages to GCS.\n\n"
  },
  {
   "title": "pages_request_duration SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"pages_request_duration\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "pages_request_duration apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"pages_request_duration\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"pages_request_duration\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"pages_request_duration\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "pages_request_duration apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"pages_request_duration\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"pages_request_duration\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"pages_request_duration\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"pages_request_duration\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"pages_request_duration\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"pages_request_duration\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"pages_request_duration\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"pages_request_duration\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"pages_request_duration\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"pages_request_duration\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"pages_request_duration\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "pages_request_duration SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "pages_request_duration SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"pages_request_duration\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "pages_request_duration RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"pages_request_duration\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "content": "### Description\n\nMonitors the time it takes to get a response from an httprange. Resource hosted in object storage for a request made by the zip VFS.\n\n"
  },
  {
   "title": "pages_total_requests SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"pages_total_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "pages_total_requests RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"pages_total_requests\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "content": "### Description\n\nThe number of requests made by the zip VFS to a Resource with different status codes.\nCould be bigger than the number of requests served.\n\n"
  },
  {
   "title": "registry_storage SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"registry_storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "registry_storage apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"registry_storage\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"registry_storage\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"registry_storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "registry_storage apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"registry_storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"registry_storage\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"registry_storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"registry_storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"registry_storage\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"registry_storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"registry_storage\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"registry_storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"registry_storage\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"registry_storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"registry_storage\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "registry_storage SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "registry_storage SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"registry_storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "registry_storage RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"registry_storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "content": "### Description\n\nAggregation of all container registry GCS storage operations.\n\n"
  },
  {
   "title": "workhorse_upload SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "workhorse_upload apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "workhorse_upload apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "workhorse_upload SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "workhorse_upload SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 71 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "workhorse_upload error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "workhorse_upload error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse_upload\",monitor=\"global\",type=\"google-cloud-storage\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "workhorse_upload SLI | Errors"
    }
   ]
  },
  {
   "title": "workhorse_upload SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"}[$__interval])\n",
     "legendFormat": "workhorse_upload RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"workhorse_upload\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"google-cloud-storage\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 71 },
   "content": "### Description\n\nMonitors the performance of file uploads from Workhorse\nto GCS.\n\n"
  },
  {
   "title": "🔬 SLI Detail: artifacts_cdn",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "artifacts_cdn Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",response_code_class=\"500\",url_map_name=\"gprd-artifacts-cdn\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "artifacts_cdn RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",url_map_name=\"gprd-artifacts-cdn\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "artifacts_cdn Errors - per proxy_continent",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy_continent) (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",proxy_continent!=\"\",response_code_class=\"500\",url_map_name=\"gprd-artifacts-cdn\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{proxy_continent}}"
      }
     ]
    },
    {
     "title": "artifacts_cdn RPS - per proxy_continent",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy_continent) (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",proxy_continent!=\"\",url_map_name=\"gprd-artifacts-cdn\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{proxy_continent}}"
      }
     ]
    },
    {
     "title": "artifacts_cdn Errors - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",response_code!=\"\",response_code_class=\"500\",url_map_name=\"gprd-artifacts-cdn\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "artifacts_cdn RPS - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",response_code!=\"\",url_map_name=\"gprd-artifacts-cdn\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: pages_range_requests",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 pages_range_requests Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(gitlab_pages_httprange_trace_duration_bucket{env=\"$environment\",environment=\"$environment\",request_stage=\"httptrace.ClientTrace.GotFirstResponseByte\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "pages_range_requests RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_pages_httprange_trace_duration_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",request_stage=\"httptrace.ClientTrace.GotFirstResponseByte\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: pages_request_duration",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 pages_request_duration Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(gitlab_pages_httprange_requests_duration_bucket{env=\"$environment\",environment=\"$environment\",request_stage=\"httptrace.ClientTrace.GotFirstResponseByte\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "pages_request_duration RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_pages_httprange_requests_duration_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",request_stage=\"httptrace.ClientTrace.GotFirstResponseByte\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: pages_total_requests",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 230 },
   "collapsed": true,
   "panels": [
    {
     "title": "pages_total_requests RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_pages_httprange_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "pages_total_requests RPS - per type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (\n  rate(gitlab_pages_httprange_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: registry_storage",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 240 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 registry_storage Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "registry_storage RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_storage_action_seconds_count{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 registry_storage Latency - per action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (action,le) (\n    rate(registry_storage_action_seconds_bucket{action!=\"\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{action}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for registry_storage Latency - per action",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (action) (\n  rate(registry_storage_action_seconds_bucket{action!=\"\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      sum by (action) (\n  rate(registry_storage_action_seconds_bucket{action!=\"\",env=\"$environment\",environment=\"$environment\",le=\"1\",stage=\"$stage\"}[$__interval])\n)\n\n    )\n  )\n  / ignoring(action) group_left()\n  (\n    sum by () (\n  rate(registry_storage_action_seconds_bucket{action!=\"\",env=\"$environment\",environment=\"$environment\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "registry_storage RPS - per action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (action) (\n  rate(registry_storage_action_seconds_count{action!=\"\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: workhorse_upload",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 250 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 workhorse_upload Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(gitlab_workhorse_object_storage_upload_time_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "workhorse_upload Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_workhorse_object_storage_upload_requests{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "workhorse_upload RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_workhorse_object_storage_upload_requests{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 workhorse_upload Latency - per type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,type) (\n    rate(gitlab_workhorse_object_storage_upload_time_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type!=\"\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{type}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for workhorse_upload Latency - per type",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (type) (\n  rate(gitlab_workhorse_object_storage_upload_time_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",stage=\"$stage\",type!=\"\"}[$__interval])\n)\n\n    -\n    (\n      sum by (type) (\n  rate(gitlab_workhorse_object_storage_upload_time_bucket{env=\"$environment\",environment=\"$environment\",le=\"25\",stage=\"$stage\",type!=\"\"}[$__interval])\n)\n\n    )\n  )\n  / ignoring(type) group_left()\n  (\n    sum by () (\n  rate(gitlab_workhorse_object_storage_upload_time_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",stage=\"$stage\",type!=\"\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "workhorse_upload Errors - per type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (\n  rate(gitlab_workhorse_object_storage_upload_requests{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "workhorse_upload RPS - per type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (\n  rate(gitlab_workhorse_object_storage_upload_requests{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",stage=\"$stage\",type!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"google-cloud-storage\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"google-cloud-storage\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"google-cloud-storage\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"google-cloud-storage\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"google-cloud-storage\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"google-cloud-storage\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"google-cloud-storage\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph stor\n  google-cloud-storage\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph stor\n  google-cloud-storage\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph stor\n  google-cloud-storage[\"google-cloud-storage (Level 2)\"]\nend\n\n\n  \n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}