{
 "title": "HAProxy [deprecated]",
 "description": "HAProxy backend servers",
 "tags": [
  "haproxy",
  "servers",
  "unmanaged"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": { "query": "label_values(haproxy_up, env)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_up{env=\"$env\"}, fqdn)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(haproxy_up{env=\"$env\"}, instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_bytes_in_total{env=\"$env\",fqdn=~\"$host\"}, backend)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_bytes_in_total{env=\"$env\",fqdn=~\"$host\"}, frontend)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_bytes_in_total{fqdn=~\"$host\", backend=~\"$backend\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{fqdn=~\"$host\", backend=~\"$backend\", server=~\"$server\"}, code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(haproxy_http_response_duration_seconds_bucket{env=\"$env\",fqdn=~\"($host)\", backend_name=~\"$backend\"}[$__interval])\n) > 0",
     "legendFormat": "{{le}} "
    }
   ]
  },
  {
   "title": "Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(haproxy_http_response_duration_seconds_bucket{env=\"$env\",fqdn=~\"($host)\",backend_name=~\"$backend\"}[$__interval])))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(haproxy_http_response_duration_seconds_bucket{env=\"$env\",fqdn=~\"($host)\",backend_name=~\"$backend\"}[$__interval])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(haproxy_http_response_duration_seconds_bucket{env=\"$env\",fqdn=~\"($host)\",backend_name=~\"$backend\"}[$__interval])))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Basic Backend status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backends Up",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(haproxy_backend_up{env=\"$env\",backend=~\"$backend\",instance=~\"($host):$port\"}[$__interval])\n)",
     "legendFormat": "Backends Up"
    }
   ]
  },
  {
   "title": "Basic General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total responses by HTTP code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (\n  rate(haproxy_frontend_http_responses_total{env=\"$env\",frontend=~\"$frontend\",code=~\"$code\",instance=~\"($host):$port\"}[$__interval])\n)",
     "legendFormat": "Frontend {{ code }}"
    },
    {
     "expr": "sum by (code) (\n  rate(haproxy_backend_http_responses_total{env=\"$env\",backend=~\"$backend\",code=~\"$code\",instance=~\"($host):$port\"}[$__interval])\n)",
     "legendFormat": "Backend {{ code }}"
    }
   ]
  },
  {
   "title": "Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",instance=~\"($host):$port\"}[$__interval])*8) by (instance)",
     "legendFormat": "IN Front {{ instance }} "
    },
    {
     "expr": "sum(rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",instance=~\"($host):$port\"}[$__interval])*8) by (instance)",
     "legendFormat": "OUT Front {{ instance }} "
    },
    {
     "expr": "sum by (instance) (\n  rate(haproxy_backend_bytes_in_total{env=\"$env\",backend=~\"$backend\",instance=~\"($host):$port\"}[$__interval])\n) * 8",
     "legendFormat": "IN Back {{ instance }} "
    },
    {
     "expr": "sum by (instance) (\n  rate(haproxy_backend_bytes_out_total{env=\"$env\",backend=~\"$backend\",instance=~\"($host):$port\"}[$__interval])\n) * 8",
     "legendFormat": "OUT Back {{ instance }} "
    }
   ]
  },
  {
   "title": "Total number of connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(haproxy_frontend_connections_total{env=\"$env\",frontend=~\"$frontend\",instance=~\"($host):$port\"}[$__interval])\n)",
     "legendFormat": "Front {{ instance }} "
    },
    {
     "expr": "sum by (instance) (\n  rate(haproxy_backend_connections_total{env=\"$env\",backend=~\"$backend\",instance=~\"($host):$port\"}[$__interval])\n)",
     "legendFormat": "Back {{ instance }} "
    },
    {
     "expr": "sum(rate(haproxy_backend_connection_errors_total{backend=~\"$backend\",instance=~\"($host):$port\"}[$__interval])) by (instance)",
     "legendFormat": "Back errors {{ instance }} "
    }
   ]
  },
  {
   "title": "Total requests / responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_requests_total{frontend=~\"$frontend\",instance=~\"($host):$port\"}[$__interval])) by (instance)",
     "legendFormat": "Requests  {{ instance }} "
    },
    {
     "expr": "sum(rate(haproxy_backend_response_errors_total{backend=~\"$backend\",instance=~\"($host):$port\"}[$__interval])) by (instance)",
     "legendFormat": "Response errors  {{ instance }} "
    },
    {
     "expr": "sum(rate(haproxy_frontend_request_errors_total{frontend=~\"$frontend\",instance=~\"($host):$port\"}[$__interval])) by (instance)",
     "legendFormat": "Requests errors  {{ instance }} "
    },
    {
     "expr": "sum(rate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\",instance=~\"($host):$port\"}[$__interval])) by (instance)",
     "legendFormat": "Backend redispatch  {{ instance }} "
    },
    {
     "expr": "sum(rate(haproxy_backend_retry_warnings_total{backend=~\"$backend\",instance=~\"($host):$port\"}[$__interval])) by (instance)",
     "legendFormat": "Backend retry  {{ instance }} "
    },
    {
     "expr": "sum(rate(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\",instance=~\"($host):$port\"}[$__interval])) by (instance)",
     "legendFormat": "Request denied  {{ instance }} "
    },
    {
     "expr": "sum(haproxy_backend_current_queue{backend=~\"$backend\",instance=~\"($host):$port\"}) by (instance)",
     "legendFormat": "Backend Queued  {{ instance }} "
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(haproxy_frontend_current_sessions{frontend=~\"$frontend\",instance=~\"($host):$port\"}[$__interval])) by (instance)",
     "legendFormat": "Frontend current sessions  {{ instance }} "
    },
    {
     "expr": "sum(avg_over_time(haproxy_backend_current_sessions{backend=~\"$backend\",instance=~\"($host):$port\"}[$__interval])) by (instance)",
     "legendFormat": "Backend current sessions  {{ instance }} "
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_in_total{backend=~\"$backend\",instance=~\"($host):$port\"}[5m])*8",
     "legendFormat": "IN-{{ backend }} {{ instance }}"
    },
    {
     "expr": "rate(haproxy_backend_bytes_out_total{backend=~\"$backend\",instance=~\"($host):$port\"}[5m])*8",
     "legendFormat": "OUT-{{ backend }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Front - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",instance=~\"($host):$port\"}[5m])*8",
     "legendFormat": "IN-{{ frontend }} {{ instance }}"
    },
    {
     "expr": "rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",instance=~\"($host):$port\"}[5m])*8",
     "legendFormat": "OUT-{{ frontend }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Total number of connections OK / Error",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(haproxy_backend_connections_total{backend=~\"$backend\",instance=~\"($host):$port\"}[5m])",
     "legendFormat": "{{ backend }}  / {{ instance }}"
    },
    {
     "expr": "deriv(haproxy_backend_connection_errors_total{backend=~\"$backend\",instance=~\"($host):$port\"}[5m])",
     "legendFormat": "{{ backend }} Error / {{ instance }}"
    }
   ]
  },
  {
   "title": "Front - Total number of connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(haproxy_frontend_connections_total{frontend=~\"$frontend\",instance=~\"($host):$port\"}[5m])",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Maximum observed number of queued requests not assigned to any server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(haproxy_backend_max_queue{backend=~\"$backend\",instance=~\"($host):$port\"}[5m])",
     "legendFormat": "{{ backend }}  / {{ instance }}"
    }
   ]
  },
  {
   "title": "Back - Current number of queued requests not assigned to any server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_queue{backend=~\"$backend\",instance=~\"($host):$port\"}",
     "legendFormat": "{{ backend }} / {{ instance }}"
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Total of redispatch / error / retry warnings",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\", instance=~\"($host):$port\"}[5m])",
     "legendFormat": "Redispatch {{ backend }} / {{ instance }}"
    },
    {
     "expr": "deriv(haproxy_backend_retry_warnings_total{backend=~\"$backend\", instance=~\"($host):$port\"}[5m])",
     "legendFormat": "Retry {{ backend }} / {{ instance }}"
    },
    {
     "expr": "deriv(haproxy_backend_response_errors_total{backend=~\"$backend\", instance=~\"($host):$port\"}[5m])",
     "legendFormat": "Error {{ backend }} / {{ instance }}"
    }
   ]
  },
  {
   "title": "Front - Total HTTP requests OK / Error / Denied",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(haproxy_frontend_http_requests_total{frontend=~\"$frontend\",instance=~\"($host):$port\"}[5m])",
     "legendFormat": "{{ frontend }} / {{ instance }}"
    },
    {
     "expr": "deriv(haproxy_frontend_request_errors_total{frontend=~\"$frontend\", instance=~\"($host):$port\"}[5m])",
     "legendFormat": "{{ frontend }} Error / {{ instance }}"
    },
    {
     "expr": "deriv(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\", instance=~\"($host):$port\"}[5m])",
     "legendFormat": "{{ frontend }} Denied / {{ instance }}"
    }
   ]
  },
  {
   "title": "Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Back - Total of HTTP responses",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_responses_total{backend=~\"$backend\", code=~\"$code\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ code }} {{ backend }}"
      }
     ]
    },
    {
     "title": "Front - Total of HTTP responses",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "deriv(haproxy_frontend_http_responses_total{frontend=~\"$frontend\", code=~\"$code\",instance=~\"$host:$port\"}[5m])",
       "legendFormat": "{{ code }} {{ frontend }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Back - Current number of active sessions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (fqdn,instance) (\n  avg_over_time(haproxy_backend_current_sessions{env=\"$env\",backend=~\"$backend\",fqdn=~\"$host\"}[$__interval])\n)",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Front - Current number of active sessions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_current_sessions{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ frontend }}"
      }
     ]
    },
    {
     "title": "Back - Current number of sessions rate per second over last elapsed second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 103 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (fqdn,instance) (\n  rate(haproxy_backend_sessions_total{env=\"$env\",backend=~\"$backend\",fqdn=~\"$host\"}[$__interval])\n)",
       "legendFormat": "{{ backend }}"
      }
     ]
    },
    {
     "title": "Front - Current number of sessions rate per second over last elapsed second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 103 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_current_session_rate{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ frontend }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 113 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_sessions{backend=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ backend }}"
      },
      {
       "expr": "haproxy_backend_limit_sessions{backend=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ backend }} limit"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of active sessions and limit",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 113 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_max_sessions{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ frontend }}"
      },
      {
       "expr": "haproxy_frontend_limit_sessions{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ frontend }} limit"
      }
     ]
    },
    {
     "title": "Back - Maximum number of sessions rate per second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 123 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_session_rate{backend=~\"$backend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ backend }}"
      }
     ]
    },
    {
     "title": "Front - Maximum number of sessions rate per second and limit",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 123 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_max_session_rate{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ frontend }}"
      },
      {
       "expr": "haproxy_frontend_limit_session_rate{frontend=~\"$frontend\",instance=~\"$host:$port\"}",
       "legendFormat": "{{ frontend }} limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Back - Current health status of the backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_up{backend=~\"$backend\", instance=~\"$(host):$port\"}",
     "legendFormat": "{{ backend }}  / {{ instance }}"
    }
   ]
  },
  {
   "title": "Back - Total weight of the servers in the backend / Active servers backend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_weight{backend=~\"$backend\", instance=~\"($host):$port\"}",
     "legendFormat": "{{ backend }} / {{ instance }} "
    }
   ]
  },
  {
   "title": "By Server Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Current total of incoming / outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_bytes_in_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "IN-{{ backend }} / {{ server }}"
    },
    {
     "expr": "rate(haproxy_server_bytes_out_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])*8",
     "legendFormat": "OUT-{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Total number of connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(haproxy_server_connections_total{backend=~\"$backend\",instance=~\"($host):$port\"}[5m])",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Maximum observed number of queued requests assigned to this server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(haproxy_server_max_queue{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current number of queued requests assigned to this server",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(haproxy_server_current_queue{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Total of HTTP responses OK",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(haproxy_server_http_responses_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])) by (server)",
     "legendFormat": "{{ backend }} {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Total of retry / error / redispatch warnings",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(haproxy_server_retry_warnings_total{backend=~\"$backend\", instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Retry {{ backend }} {{ server }}"
    },
    {
     "expr": "haproxy_server_redispatch_warnings_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
     "legendFormat": "Redispatch {{ backend }} {{ server }}"
    },
    {
     "expr": "deriv(haproxy_server_response_errors_total{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Error {{ backend }} {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Total of HTTP responses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(haproxy_server_http_responses_total{backend=~\"$backend\",server=~\"$server\",code=~\"$code\",instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ backend }} {{ server }} {{ code }}"
    }
   ]
  },
  {
   "title": "By Server Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Current number of active sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_sessions{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current number of sessions rate per second over last elapsed second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_current_session_rate{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Maximum observed number of sessions rate per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_session_rate{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Maximum observed number of active sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_max_sessions{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "By Server Health Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server - Total downtime in seconds",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 185 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_downtime_seconds_total{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Total number of failed health checks",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 185 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_check_failures_total{env=\"$env\",backend=~\"$backend\",instance=~\"$host:$port\"}[$__interval])",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Total of connection errors",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 197 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_server_connection_errors_total{backend=~\"$backend\",instance=~\"$host:$port\"}[$__interval])",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Previously run health check duration, in milliseconds",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 197 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_check_duration_milliseconds{backend=~\"$backend\",server=~\"$server\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current health status of the server",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 209 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_up{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Server - Current weight of the server",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 209 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_weight{backend=~\"$backend\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ backend }} / {{ server }}"
    }
   ]
  },
  {
   "title": "Scrape info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 221 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of errors while parsing CSV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 222 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_exporter_csv_parse_failures{instance=~\"$host:$port\"}",
     "legendFormat": "Exporter csv failures"
    }
   ]
  },
  {
   "title": "Current total HAProxy scrapes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 222 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_exporter_total_scrapes{instance=~\"$host:$port\"}",
     "legendFormat": "HAProxy scrapes"
    }
   ]
  }
 ]
}