{
 "title": "HAProxy Process Overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "gprd,gstg" },
   {
    "name": "fetype",
    "label": "Type",
    "query": "frontend, altssh, pages, registry"
   },
   { "name": "stage", "label": "Stage", "query": "main,cny" }
  ]
 },
 "panels": [
  {
   "title": "HAProxy active ($fetype / $stage)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "repeat": "fetype",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(namedprocess_namegroup_num_procs{type=\"$fetype\", groupname=\"haproxy\", job=\"process_exporter\", environment=\"$env\", stage=\"$stage\"}) by (fqdn)",
     "legendFormat": "{{fqdn}}"
    },
    {
     "expr": "count(up{type=\"$fetype\", job=\"process_exporter\", environment=\"$env\", stage=\"$stage\"}) # Use a metric on the exporter that is always there as nodecount",
     "legendFormat": "Total nodes"
    }
   ]
  },
  {
   "title": "HAProxy nodes (total in $env $stage)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"process_exporter\", environment=\"$env\", stage=\"$stage\", instance=~\".*-lb-.*\"})"
    }
   ]
  },
  {
   "title": "Nodes with active HAProxy ($env $stage)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(namedprocess_namegroup_num_procs{groupname=\"haproxy\", job=\"process_exporter\", environment=\"$env\", stage=\"$stage\"}) by (instance))"
    }
   ]
  },
  {
   "title": "HAProxy processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_num_procs{groupname=\"haproxy\", job=\"process_exporter\", environment=\"$env\"})"
    }
   ]
  },
  {
   "title": "HAProxy CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(irate(namedprocess_namegroup_cpu_user_seconds_total{groupname=\"haproxy\",job=\"process_exporter\",environment=\"$env\", stage=\"$stage\"}[5m])) + (irate(namedprocess_namegroup_cpu_system_seconds_total{groupname=\"haproxy\",job=\"process_exporter\",environment=\"$env\", stage=\"$stage\"}[5m]))",
     "legendFormat": "{{fqdn}}"
    },
    {
     "expr": "avg((irate(namedprocess_namegroup_cpu_user_seconds_total{groupname=\"haproxy\",job=\"process_exporter\",environment=\"$env\", stage=\"$stage\"}[5m])) + (irate(namedprocess_namegroup_cpu_system_seconds_total{groupname=\"haproxy\",job=\"process_exporter\",environment=\"$env\", stage=\"$stage\"}[5m]))) by (type)",
     "legendFormat": "{{type}} avg."
    }
   ]
  },
  {
   "title": "HAProxy active ($fetype / $stage)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(namedprocess_namegroup_num_procs{type=\"$fetype\", groupname=\"haproxy\", job=\"process_exporter\", environment=\"$env\", stage=\"$stage\"}) by (fqdn)",
     "legendFormat": "{{fqdn}}"
    },
    {
     "expr": "count(up{type=\"$fetype\", job=\"process_exporter\", environment=\"$env\", stage=\"$stage\"}) # Use a metric on the exporter that is always there as nodecount",
     "legendFormat": "Total nodes"
    }
   ]
  },
  {
   "title": "HAProxy processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_num_procs{groupname=\"haproxy\", job=\"process_exporter\", environment=\"$env\", stage=\"$stage\"}) by (fqdn)",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "HAProxy active ($fetype / $stage)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(namedprocess_namegroup_num_procs{type=\"$fetype\", groupname=\"haproxy\", job=\"process_exporter\", environment=\"$env\", stage=\"$stage\"}) by (fqdn)",
     "legendFormat": "{{fqdn}}"
    },
    {
     "expr": "count(up{type=\"$fetype\", job=\"process_exporter\", environment=\"$env\", stage=\"$stage\"}) # Use a metric on the exporter that is always there as nodecount",
     "legendFormat": "Total nodes"
    }
   ]
  },
  {
   "title": "HAProxy stepdowns",
   "type": "table",
   "description": "This matches whenever a master process-tree is finished and/or replaced by another.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "changes(namedprocess_namegroup_oldest_start_time_seconds{environment=\"$env\", job=\"process_exporter\", type=~\"$fetype\", stage=\"$stage\"}[$__range]) > 0"
    }
   ]
  },
  {
   "title": "HAProxy active ($fetype / $stage)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(namedprocess_namegroup_num_procs{type=\"$fetype\", groupname=\"haproxy\", job=\"process_exporter\", environment=\"$env\", stage=\"$stage\"}) by (fqdn)",
     "legendFormat": "{{fqdn}}"
    },
    {
     "expr": "count(up{type=\"$fetype\", job=\"process_exporter\", environment=\"$env\", stage=\"$stage\"}) # Use a metric on the exporter that is always there as nodecount",
     "legendFormat": "Total nodes"
    }
   ]
  },
  {
   "title": "HAProxy uptime",
   "type": "table",
   "description": "Uptime of the oldest HAProxy process still running",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "time() - namedprocess_namegroup_oldest_start_time_seconds{environment=\"$env\", job=\"process_exporter\", type=~\"$fetype\", stage=\"$stage\"}"
    }
   ]
  },
  {
   "title": "HAProxy zombie processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_states{state=\"Zombie\",job=\"process_exporter\", environment=\"$env\", stage=\"$stage\", groupname=\"haproxy\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}