{
 "title": "Host Stats Copy",
 "tags": [
  "host",
  "drilldown"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg,ops" },
   { "name": "node", "label": "Host", "query": "label_values(up,fqdn)" },
   { "name": "promethus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CPU and Load Average", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Percentage of all CPU cores/hyperthreads",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "% of all CPUs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{fqdn=\"$node\"}[$__interval])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CS per second" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches{fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Context switches",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_context_switches_total{fqdn=\"$node\"}[$__interval])",
     "legendFormat": "Context switches"
    }
   ]
  },
  {
   "title": "Load per CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_load1{fqdn=\"$node\"}[$__interval]) / instance:node_cpus:count",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per-core CPU usage for soft-interrupt handling",
   "type": "graph",
   "description": "Are soft-interrupts distributed evenly across vCPUs?\n\nShows percentage of CPU time spent by each vCPU on softirq handling.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of vCPUs used" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{fqdn=\"$node\",mode=\"softirq\"}[$__interval])",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Per-core CPU usage for user-mode execution context",
   "type": "graph",
   "description": "Is workload unevenly distributed among vCPUs?\n\nNote that imbalance may be intentional (e.g. a process or container may be restricted to using only a limited number or set of vCPUs).  Unexpected imbalance may be worth investigating.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of vCPUs used" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{fqdn=\"$node\",mode=\"user\"}[$__interval])",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Per-core CPU usage for kernel-mode execution context",
   "type": "graph",
   "description": "Is workload unevenly distributed among vCPUs?\n\nNote that imbalance may be intentional (e.g. a process or container may be restricted to using only a limited number or set of vCPUs).  Unexpected imbalance may be worth investigating.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of vCPUs used" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{fqdn=\"$node\",mode=\"system\"}[$__interval])",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{fqdn=\"$node\"} - node_memory_MemAvailable_bytes{fqdn=\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{fqdn=\"$node\"} - node_memory_SwapFree_bytes{fqdn=\"$node\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_MemTotal_bytes{fqdn=\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{fqdn=\"$node\"}",
     "legendFormat": "Swap Total"
    }
   ]
  },
  {
   "title": "Memory usage by type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_AnonPages_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AnonPages",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Buffers_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Buffers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Slab_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Slab",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Cached_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Cached",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page cache",
   "type": "graph",
   "description": "Most normal (4 KB) memory pages are either:\n* anonymous memory (allocated by a process)\n* file-backed (cached copy of an on-disk block)\n\nWhen something needs a page of memory, typically another page needs to be evicted.  The memory manager has a 2-strikes policy: 1st strike bumps the page from Active to Inactive.  If a page on the Inactive list is not touched, it remains a candidate for eviction.  The kernel tries to keep enough pages on the Inactive list to satisfy memory demands.\n\nTypically the kernel prefers to evict file-backed pages, but if swap is enabled, it can also swap-out anonymous pages.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_anon_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active anonymous",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Active_file_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active file-backed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Inactive_anon_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inactive anonymous",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Inactive_file_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inactive file-backed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap IO",
   "type": "graph",
   "description": "Physical I/O to/from any active swap file or partition.  Some hosts have swap disabled (see /proc/swaps on the host), in which case this metric will always be zero even when the host is under memory pressure.\n\nRaw metric uses a unit size of one 4 KB page, so we multiply by 4096 to convert to bytes.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_vmstat_pswpin{fqdn=\"$node\"}[$__interval]) * 4096",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "swap in from disk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(node_vmstat_pswpout{fqdn=\"$node\"}[$__interval]) * 4096",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "swap out to disk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Disk Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Disk Read Latency (mean latency)",
   "type": "graph",
   "description": "This measures the mean duration for each read operation (including time spent in the I/O queue, not just time from Dispatch to Compete).\n\nGood latency should be a few milliseconds; if the graph's scale is in seconds, you have a problem!\n\nHigh read latency and deep I/O queues often occur together.  They can be caused by either increased service time from the block device (slower physical I/O) or increased demand (request arrival rate).  Note that writes can sometimes stall reads.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_read_time_seconds_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval]) / increase(node_disk_reads_completed_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} read latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Latency (mean latency)",
   "type": "graph",
   "description": "This measures the mean duration for each write operation (including time spent in the I/O queue, not just time from Dispatch to Compete).\n\nWrite latency is often slower (due to larger mean operation size) and often runs in the background, so high write latency may not be as serious as read latency.  However, writes can stall reads if the reads are not getting promptly scheduled and spending time in the I/O queue.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_write_time_seconds_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval]) / increase(node_disk_writes_completed_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} write latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Throughput (bytes/sec)",
   "type": "graph",
   "description": "This measures the mean bytes read per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} read rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Throughput (bytes/sec)",
   "type": "graph",
   "description": "This measures the mean bytes written per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} write rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Throughput (operations/sec)",
   "type": "graph",
   "description": "This measures the mean count of read operations per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} read rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Throughput (operations/sec)",
   "type": "graph",
   "description": "This measures the mean count of write operations per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} write rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Mean Read Operation Size (bytes/operation)",
   "type": "graph",
   "description": "This measures the mean size of read operations for each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_read_bytes_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval]) / increase(node_disk_reads_completed_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} read op size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Mean Write Operation Size (bytes/operation)",
   "type": "graph",
   "description": "This measures the mean size of write operations for each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_written_bytes_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval]) / increase(node_disk_writes_completed_total{fqdn=\"$node\", device!~\"dm.*\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} write op size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault{fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Major Faults",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Available Filesystem Space by Mountpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_filesystem_avail:ratio{fqdn=\"$node\", fstype=~\"ext.|xfs\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mountpoint}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Allocated file descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_filefd_maximum{fqdn=\"$node\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{device!=\"lo\", fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "send {{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_network_receive_bytes{device!=\"lo\", fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "receive {{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\", fqdn=\"$node\"}[$__interval])",
     "legendFormat": "send {{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\", fqdn=\"$node\"}[$__interval])",
     "legendFormat": "receive {{device}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{fqdn=~\"$node\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "current connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP Listen Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_ListenOverflows{fqdn=~\"$node\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TCP overflows rate/min",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_netstat_TcpExt_ListenDrops{fqdn=~\"$node\"}[1m])",
     "legendFormat": "TCP drops/min"
    }
   ]
  }
 ]
}