{
 "title": "Host Stats (Thanos)",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(up{job=\"prometheus\"}, env)"
   },
   {
    "name": "fqdn",
    "label": "Host",
    "query": "label_values(up{env=\"$env\",job=\"node\"}, fqdn)"
   }
  ]
 },
 "panels": [
  { "title": "CPU and Load Average", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Percentage of all CPU cores/hyperthreads",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "% of all CPUs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{env=\"$env\",fqdn=\"$fqdn\", mode !=\"idle\"}[$__interval])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Per-core CPU usage for kernel-mode execution context",
   "type": "graph",
   "description": "Is workload unevenly distributed among vCPUs?\n\nNote that imbalance may be intentional (e.g. a process or container may be restricted to using only a limited number or set of vCPUs).  Unexpected imbalance may be worth investigating.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "# of vCPUs used" }
   ],
   "targets": [
    {
     "expr": "avg by (cpu) (rate(node_cpu_seconds_total{env=\"$env\",fqdn=\"$fqdn\",mode=\"system\"}[$__interval]))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CS per second" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_context_switches_total{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "legendFormat": "Context switches"
    }
   ]
  },
  {
   "title": "Per-core CPU usage for soft-interrupt handling",
   "type": "graph",
   "description": "Are soft-interrupts distributed evenly across vCPUs?\n\nShows percentage of CPU time spent by each vCPU on softirq handling.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of vCPUs used" }
   ],
   "targets": [
    {
     "expr": "avg by (cpu) (rate(node_cpu_seconds_total{env=\"$env\",fqdn=\"$fqdn\",mode=\"softirq\"}[$__interval]))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Per-core CPU usage for user-mode execution context",
   "type": "graph",
   "description": "Is workload unevenly distributed among vCPUs?\n\nNote that imbalance may be intentional (e.g. a process or container may be restricted to using only a limited number or set of vCPUs).  Unexpected imbalance may be worth investigating.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of vCPUs used" }
   ],
   "targets": [
    {
     "expr": "avg by (cpu) (\n  rate(node_cpu_seconds_total{env=\"$env\",fqdn=\"$fqdn\",mode=\"user\"}[$__interval])\n)",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Load per CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(node_load1{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]) / avg_over_time(instance:node_cpus:count[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(node_memory_MemTotal_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval])\n  -\n  avg_over_time(node_memory_MemAvailable_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval])\n)",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(\n  avg_over_time(node_memory_SwapTotal_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]) > 0\n  -\n  avg_over_time(node_memory_SwapFree_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval])\n)",
     "legendFormat": "Swap"
    },
    {
     "expr": "avg(avg_over_time(node_memory_MemTotal_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(avg_over_time(node_memory_SwapTotal_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval])) > 0",
     "legendFormat": "Swap Total"
    }
   ]
  },
  {
   "title": "Memory usage by type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(node_memory_AnonPages_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AnonPages",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(avg_over_time(node_memory_Buffers_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Buffers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(avg_over_time(node_memory_Slab_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Slab",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(avg_over_time(node_memory_Cached_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Cached",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page cache",
   "type": "graph",
   "description": "Most normal (4 KB) memory pages are either:\n* anonymous memory (allocated by a process)\n* file-backed (cached copy of an on-disk block)\n\nWhen something needs a page of memory, typically another page needs to be evicted.  The memory manager has a 2-strikes policy: 1st strike bumps the page from Active to Inactive.  If a page on the Inactive list is not touched, it remains a candidate for eviction.  The kernel tries to keep enough pages on the Inactive list to satisfy memory demands.\n\nTypically the kernel prefers to evict file-backed pages, but if swap is enabled, it can also swap-out anonymous pages.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(node_memory_Active_anon_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active anonymous",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(avg_over_time(node_memory_Active_file_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active file-backed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(avg_over_time(node_memory_Inactive_anon_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inactive anonymous",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(avg_over_time(node_memory_Inactive_file_bytes{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inactive file-backed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OOMs / Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(avg(rate(node_vmstat_oom_kill{env=\"$env\",fqdn=\"$fqdn\"}[$__interval])) * 86400)",
     "legendFormat": "Boom!"
    }
   ]
  },
  {
   "title": "Swap IO",
   "type": "graph",
   "description": "Physical I/O to/from any active swap file or partition.  Some hosts have swap disabled (see /proc/swaps on the host), in which case this metric will always be zero even when the host is under memory pressure.\n\nRaw metric uses a unit size of one 4 KB page, so we multiply by 4096 to convert to bytes.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(node_vmstat_pswpin{env=\"$env\",fqdn=\"$fqdn\"}[$__interval])) * 4096",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "swap in from disk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(increase(node_vmstat_pswpout{env=\"$env\",fqdn=\"$fqdn\"}[$__interval])) * 4096",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "swap out to disk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Disk Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Disk Read Latency (mean latency)",
   "type": "graph",
   "description": "This measures the mean duration for each read operation (including time spent in the I/O queue, not just time from Dispatch to Compete).\n\nGood latency should be a few milliseconds; if the graph's scale is in seconds, you have a problem!\n\nHigh read latency and deep I/O queues often occur together.  They can be caused by either increased service time from the block device (slower physical I/O) or increased demand (request arrival rate).  Note that writes can sometimes stall reads.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (device) (\n  rate(node_disk_read_time_seconds_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n  /\n  rate(node_disk_reads_completed_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Latency (mean latency)",
   "type": "graph",
   "description": "This measures the mean duration for each write operation (including time spent in the I/O queue, not just time from Dispatch to Compete).\n\nWrite latency is often slower (due to larger mean operation size) and often runs in the background, so high write latency may not be as serious as read latency.  However, writes can stall reads if the reads are not getting promptly scheduled and spending time in the I/O queue.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (device) (\n  rate(node_disk_write_time_seconds_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n  /\n  rate(node_disk_writes_completed_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Throughput (bytes/sec)",
   "type": "graph",
   "description": "This measures the mean bytes read per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (device) (\n  rate(node_disk_read_bytes_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Throughput (bytes/sec)",
   "type": "graph",
   "description": "This measures the mean bytes written per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (device) (\n  rate(node_disk_written_bytes_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Throughput (operations/sec)",
   "type": "graph",
   "description": "This measures the mean count of read operations per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "avg by (device) (\n  rate(node_disk_reads_completed_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Throughput (operations/sec)",
   "type": "graph",
   "description": "This measures the mean count of write operations per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "avg by (device) (\n  rate(node_disk_writes_completed_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Mean Read Operation Size (bytes/operation)",
   "type": "graph",
   "description": "This measures the mean size of read operations for each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (device) (\n  rate(node_disk_read_bytes_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n  /\n  rate(node_disk_reads_completed_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Mean Write Operation Size (bytes/operation)",
   "type": "graph",
   "description": "This measures the mean size of write operations for each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (device) (\n  rate(node_disk_written_bytes_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n  /\n  rate(node_disk_writes_completed_total{env=\"$env\",fqdn=\"$fqdn\", device!~\"dm.*\"}[$__interval])\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_vmstat_pgmajfault{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Major Faults",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Available Filesystem Used by Mountpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (mountpoint) (\n  1 - avg_over_time(instance:node_filesystem_avail:ratio{env=\"$env\",fqdn=\"$fqdn\", fstype=~\"ext.|xfs\"}[$__interval])\n)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mountpoint}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Allocated file descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(node_filefd_allocated{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(node_filefd_maximum{env=\"$env\",fqdn=\"$fqdn\"})",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Network Bandwidth Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (device) (\n  rate(node_network_transmit_bytes_total{env=\"$env\",fqdn=\"$fqdn\", device!=\"lo\"}[$__interval])\n)",
     "legendFormat": "Out - {{device}}"
    },
    {
     "expr": "avg by (device) (\n  rate(node_network_receive_bytes_total{env=\"$env\",fqdn=\"$fqdn\", device!=\"lo\"}[$__interval])\n)",
     "legendFormat": "In -  {{device}}"
    }
   ]
  },
  {
   "title": "Count of established TCP connections",
   "type": "graph",
   "description": "Shows point-in-time count of open TCP connections.\n\nNote that there could be microbursts occuring on a smaller time scale than our metrics-polling interval.  To check for this, look for spikes in the nearby counter-based graphs of new incoming and outgoing connections.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(node_netstat_Tcp_CurrEstab{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(max_over_time(node_netstat_Tcp_CurrEstab{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rate of new outgoing and incoming TCP connections",
   "type": "graph",
   "description": "Show this host's new TCP connection rate, split into:\n* Outgoing connections when acting as a client\n* Incoming connections when acting as a server\n\nThese kernel counters are incremented for each newly established outgoing (\"active\") or incoming (\"passive\") TCP connection.  This graph converts the counter to a rate to show the trend.\n\nFor reference, an \"active\" (outgoing) connection is where we are the client sending the initial SYN.  A \"passive\" (incoming) connection is where we are the server-side listener receiving the initial SYN.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "con / sec" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_netstat_Tcp_ActiveOpens{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Outgoing",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(rate(node_netstat_Tcp_PassiveOpens{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Incoming",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "As a client: Retry rate for new outgoing TCP connection requests",
   "type": "graph",
   "description": "This kernel counter indicates the number of times an outgoing TCP SYN packet had to be retransmitted.\n\nThis is not a hard failure (the retry may succeed).  But it always indicates slowness (e.g. the 1st retry occurs after 1 second delay, and each subsequent retry uses exponential backoff).\n\nSpikes could hint at any of:\n* Packet loss along the network path (in either direction, dropping the outgoing SYN or the incoming SYN-ACK)\n* Connection rate-limiting by the remote peer (e.g. firewall, DDoS protection)\n* Saturation on the remote listener, having too many pending connection requests already waiting on is backlog",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_netstat_TcpExt_TCPSynRetrans{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TCP SYN retransmits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "As a server: Drop rate for new incoming TCP connection requests",
   "type": "graph",
   "description": "This kernel counter indicates the number of times an incoming TCP SYN packet had to be dropped by the kernel due to the TCP listener's request backlog already being full.\n\nThis is a hard failure.  The TCP client connecting to this host will see this as a failed connection attempt.  The client may or may not implement retry logic to handle this error.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_netstat_TcpExt_ListenOverflows{env=\"$env\",fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TCP SYN drops",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}