{
 "title": "Host Stats",
 "tags": [
  "host",
  "drilldown",
  "unmanaged"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(prometheus_build_info, env)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(up{env=\"$env\"},fqdn)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU and Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Percentage of all CPU cores/hyperthreads",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "% of all CPUs" }
   ],
   "targets": [
    {
     "expr": "avg by (mode) (\n  rate(node_cpu_seconds_total{env=\"$env\",fqdn=\"$node\",mode!=\"idle\"}[$__rate_interval])\n)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "CS per second" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches_total{env=\"$env\",fqdn=\"$node\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Context switches",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Average per CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_load1{env=\"$env\",fqdn=\"$node\"}[$__interval]) / instance:node_cpus:count{env=\"$env\",fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Per-core CPU usage for soft-interrupt handling",
   "type": "graph",
   "description": "Are soft-interrupts distributed evenly across vCPUs?\n\nShows percentage of CPU time spent by each vCPU on softirq handling.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of vCPUs used" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{env=\"$env\",fqdn=\"$node\",mode=\"softirq\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Per-core CPU usage for user-mode execution context",
   "type": "graph",
   "description": "Is workload unevenly distributed among vCPUs?\n\nNote that imbalance may be intentional (e.g. a process or container may be restricted to using only a limited number or set of vCPUs).  Unexpected imbalance may be worth investigating.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of vCPUs used" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{env=\"$env\",fqdn=\"$node\",mode=\"user\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Per-core CPU usage for kernel-mode execution context",
   "type": "graph",
   "description": "Is workload unevenly distributed among vCPUs?\n\nNote that imbalance may be intentional (e.g. a process or container may be restricted to using only a limited number or set of vCPUs).  Unexpected imbalance may be worth investigating.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# of vCPUs used" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{env=\"$env\",fqdn=\"$node\",mode=\"system\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU scheduler: Scheduling delay for runnable processes",
   "type": "graph",
   "description": "How long did processes in the runnable state have to wait before the kernel scheduler could allocate them a CPU time slice?\n\nScheduling delays indicate CPU contention.  For example, if 50 runnable processes each wait 100 ms to get CPU time, that sums to 5 seconds of delay per wallclock second.\n\nAs a counter metric, this can detect microbursts of CPU contention that occurred on smaller timescale than the metric's polling interval.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    {
     "format": "short",
     "label": "Scheduling delay seconds per wallclock second"
    }
   ],
   "targets": [
    {
     "expr": "rate(node_schedstat_waiting_seconds_total{env=\"$env\",fqdn=\"$node\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU scheduler: Running seconds per core",
   "type": "graph",
   "description": "How much CPU time per wallclock second were active processes scheduled onto each CPU core?  Compare this to the graph of scheduler delays.\n\nCPU cgroups can throttle utilization by their container processes to a limited amount of CPU time or to certain CPU cores.  If so, the scheduler can accrue wait time even without the running time saturating at the host level.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    {
     "format": "short",
     "label": "Scheduled running seconds per wallclock second"
    }
   ],
   "targets": [
    {
     "expr": "rate(node_schedstat_running_seconds_total{env=\"$env\",fqdn=\"$node\"}[$__rate_interval])",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU scheduler: Timeslices issued",
   "type": "graph",
   "description": "How many timeslices were issued by the scheduler on each CPU?\n\nCompare to the context switch rate (which includes additional events like syscalls).\n\nRunning tasks may voluntarily yield back the unused portion of their timeslice, so the number of timeslices scheduled does not necessarily reflect CPU utilization.  Spikes may reflect churn among runnable tasks and huge spikes may incur a noticeable extra scheduler overhead.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    {
     "format": "short",
     "label": "Timeslices issued per wallclock second"
    }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_schedstat_timeslices_total{env=\"$env\",fqdn=\"$node\"}[$__rate_interval]))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval]) - avg_over_time(node_memory_MemAvailable_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "Used"
    },
    {
     "expr": "avg_over_time(node_memory_SwapTotal_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval]) - avg_over_time(node_memory_SwapFree_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "Swap"
    },
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "Total"
    },
    {
     "expr": "avg_over_time(node_memory_SwapTotal_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "Swap Total"
    }
   ]
  },
  {
   "title": "Memory usage by type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_memory_AnonPages_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AnonPages",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(node_memory_Buffers_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Buffers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(node_memory_Slab_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Slab",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(node_memory_Cached_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Cached",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page cache",
   "type": "graph",
   "description": "Most normal (4 KB) memory pages are either:\n* anonymous memory (allocated by a process)\n* file-backed (cached copy of an on-disk block)\n\nWhen something needs a page of memory, typically another page needs to be evicted.  The memory manager has a 2-strikes policy: 1st strike bumps the page from Active to Inactive.  If a page on the Inactive list is not touched, it remains a candidate for eviction.  The kernel tries to keep enough pages on the Inactive list to satisfy memory demands.\n\nTypically the kernel prefers to evict file-backed pages, but if swap is enabled, it can also swap-out anonymous pages.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_memory_Active_anon_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active anonymous",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(node_memory_Active_file_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active file-backed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(node_memory_Inactive_anon_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inactive anonymous",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(node_memory_Inactive_file_bytes{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Inactive file-backed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap IO",
   "type": "graph",
   "description": "Physical I/O to/from any active swap file or partition.  Some hosts have swap disabled (see /proc/swaps on the host), in which case this metric will always be zero even when the host is under memory pressure.\n\nRaw metric uses a unit size of one 4 KB page, so we multiply by 4096 to convert to bytes.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{env=\"$env\",fqdn=\"$node\"}[$__rate_interval]) * 4096",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "swap in from disk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_vmstat_pswpout{env=\"$env\",fqdn=\"$node\"}[$__rate_interval]) * 4096",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "swap out to disk",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Major Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault{env=\"$env\",fqdn=\"$node\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Major Faults",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Page Faults (major + minor)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgfault{env=\"$env\",fqdn=\"$node\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Page Faults",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Read Latency - Histogram",
   "type": "heatmap",
   "description": "This histogram counts disk read ops per second that have a latency falling into each histogram bucket.  Buckets use powers-of-2 sizing, so we have fine-grained measures of low latency events and coarse-grained measures of high latency events.\n\nUnlike the graph of mean latency, this histogram sums across all disks.  If you need to see the latency for a specific disk, you can manually edit the \"device\" label filter.\n\nGood latency should be a few milliseconds; if the graph's scale is in seconds, you have a problem!\n\nHigh read latency and deep I/O queues often occur together.  They can be caused by either increased service time from the block device (slower physical I/O) or increased demand (request arrival rate).  Note that writes can sometimes stall reads.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ebpf_exporter_bio_latency_seconds_bucket{env=\"$env\",fqdn=\"$node\", operation=\"read\", device=~\"sd.*\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Latency - Histogram",
   "type": "heatmap",
   "description": "This histogram counts disk write ops per second that have a latency falling into each histogram bucket.  Buckets use powers-of-2 sizing, so we have fine-grained measures of low latency events and coarse-grained measures of high latency events.\n\nUnlike the graph of mean latency, this histogram sums across all disks.  If you need to see the latency for a specific disk, you can manually edit the \"device\" label filter.\n\nWrite latency is often slower (due to larger mean operation size) and often runs in the background, so high write latency may not be as serious as read latency.\n\nHowever, writes can stall reads if the reads are not getting promptly scheduled and spending time in the I/O queue.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ebpf_exporter_bio_latency_seconds_bucket{env=\"$env\",fqdn=\"$node\", operation=\"write\", device=~\"sd.*\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Latency - Mean Duration per Read Op",
   "type": "graph",
   "description": "This measures the mean duration for each read operation (including time spent in the I/O queue, not just time from Dispatch to Compete).\n\nGood latency should be a few milliseconds; if the graph's scale is in seconds, you have a problem!\n\nHigh read latency and deep I/O queues often occur together.  They can be caused by either increased service time from the block device (slower physical I/O) or increased demand (request arrival rate).  Note that writes can sometimes stall reads.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval]) > 0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} read latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Latency - Mean Duration per Write Op",
   "type": "graph",
   "description": "This measures the mean duration for each write operation (including time spent in the I/O queue, not just time from Dispatch to Compete).\n\nWrite latency is often slower (due to larger mean operation size) and often runs in the background, so high write latency may not be as serious as read latency.\n\nHowever, writes can stall reads if the reads are not getting promptly scheduled and spending time in the I/O queue.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} write latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Latency - Total Duration (sum of IO seconds per wallclock second)",
   "type": "graph",
   "description": "This metric sums the durations of all write IO operations that completed during the sampling interval.  This result is converted to a rate, so the graph shows total IO seconds per wallclock second.\n\nWhen multiple IO requests are concurrently in flight, the sum of IO durations can exceed the wallclock duration -- causing a spike that shows more than 1 second of IO time per second of real time.\n\nFor reference, the underlying raw metric sums the durations of all read or write IO operations that completed since boot.  Kernel exposes these metrics via /proc/diskstats, fields 4 (reads) and 8 (writes).  See kernel source: Documentation/iostats.txt",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} summed read durations",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Latency - Total Duration (sum of IO seconds per wallclock second)",
   "type": "graph",
   "description": "This metric sums the durations of all write IO operations that completed during the sampling interval.  This result is converted to a rate, so the graph shows total IO seconds per wallclock second.\n\nWhen multiple IO requests are concurrently in flight, the sum of IO durations can exceed the wallclock duration -- causing a spike that shows more than 1 second of IO time per second of real time.\n\nFor reference, the underlying raw metric sums the durations of all read or write IO operations that completed since boot.  Kernel exposes these metrics via /proc/diskstats, fields 4 (reads) and 8 (writes).  See kernel source: Documentation/iostats.txt",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} summed write durations",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Throughput (operations/sec)",
   "type": "graph",
   "description": "This measures the mean count of read operations per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} read rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Throughput (operations/sec)",
   "type": "graph",
   "description": "This measures the mean count of write operations per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} write rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Throughput (bytes/sec)",
   "type": "graph",
   "description": "This measures the mean bytes read per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} read rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Throughput (bytes/sec)",
   "type": "graph",
   "description": "This measures the mean bytes written per wall-clock second from each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} write rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Operation Size - Mean (bytes/operation)",
   "type": "graph",
   "description": "This measures the mean size of read operations for each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} read op size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Operation Size - Mean (bytes/operation)",
   "type": "graph",
   "description": "This measures the mean size of write operations for each mounted block device.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval]) / rate(node_disk_writes_completed_total{env=\"$env\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{device}} write op size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Operation Size - Histogram (bytes/operation)",
   "type": "heatmap",
   "description": "This histogram counts disk read ops per second that have a size falling into each histogram bucket.  Buckets use powers-of-2 sizing, so we have fine-grained measures of small op sizes and coarse-grained measures of large op sizes.\n\nUnlike the graph of mean op size, this histogram sums op counters across all disks.  If you need to see the op size histogram for a specific disk, you can manually edit the \"device\" label filter.\n\nCommon patterns:\n* Page size is 4 KB, and many block-devices also set their min I/O size to 4 KB, so that is usually the smallest unit of I/O.  See: /sys/block/sd*/queue/minimum_io_size\n* I/O smaller than 4 KB is an unexpected feature of this histogram.  It may be direct-io (which bypasses the page cache) or journal writes, or it may be measurement error due to 0-byte operations being included in the histogram.  \"biosnoop\" uses kprobes and does not report these.  Research pending.\n* Random I/O tends to form a band starting at the 2-4 KB bucket, because it is typically 1 page (4 KB) or a few contiguous pages.\n* Sequential I/O tends to form a band in the 64-128 KB bucket, because default max read-ahead size is 128 KB (/sys/block/sd*/queue/read_ahead_kb).\n* Some applications have a preferred I/O size.  For example, Postgres uses 8 KB logical blocks (2 kernel pages) for its table and index datafiles, which shows up in the 4-8 KB bucket.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ebpf_exporter_bio_size_bytes_bucket{env=\"$env\",fqdn=\"$node\", operation=\"read\", device=~\"sd.*\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Operation Size - Histogram (bytes/operation)",
   "type": "heatmap",
   "description": "This histogram counts disk write ops per second that have a size falling into each histogram bucket.  Buckets use powers-of-2 sizing, so we have fine-grained measures of small op sizes and coarse-grained measures of large op sizes.\n\nUnlike the graph of mean op size, this histogram sums op counters across all disks.  If you need to see the op size histogram for a specific disk, you can manually edit the \"device\" label filter.\n\nCommon patterns:\n* Page size is 4 KB, and many block-devices also set their min I/O size to 4 KB, so that is usually the smallest unit of I/O.  See: /sys/block/sd*/queue/minimum_io_size\n* I/O smaller than 4 KB is an unexpected feature of this histogram.  It may be direct-io (which bypasses the page cache) or journal writes, or it may be measurement error due to 0-byte operations being included in the histogram.  \"biosnoop\" uses kprobes and does not report these.  Research pending.\n* Random I/O tends to form a band starting at the 2-4 KB bucket, because it is typically 1 page (4 KB) or a few contiguous pages.\n* Sequential I/O tends to form a band in the 64-128 KB bucket, because default max read-ahead size is 128 KB (/sys/block/sd*/queue/read_ahead_kb).\n* Some applications have a preferred I/O size.  For example, Postgres uses 8 KB logical blocks (2 kernel pages) for its table and index datafiles, which shows up in the 4-8 KB bucket.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "sum by (le) (rate(ebpf_exporter_bio_size_bytes_bucket{env=\"$env\",fqdn=\"$node\", operation=\"write\", device=~\"sd.*\"}[$__rate_interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available Filesystem Space by Mountpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(instance:node_filesystem_avail:ratio{env=\"$env\",fqdn=\"$node\", fstype=~\"ext.|xfs\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mountpoint}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Allocated file descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_filefd_allocated{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(node_filefd_maximum{env=\"$env\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{env=\"$env\",device!=\"lo\", fqdn=\"$node\"}[$__rate_interval])",
     "legendFormat": "Outgoing on interface {{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{env=\"$env\",device!=\"lo\", fqdn=\"$node\"}[$__rate_interval])",
     "legendFormat": "Incoming on interface {{device}}"
    }
   ]
  },
  {
   "title": "Network Throughput (packets/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 104 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{env=\"$env\",device!=\"lo\", fqdn=\"$node\"}[$__rate_interval])",
     "legendFormat": "Outgoing on interface {{device}}"
    },
    {
     "expr": "rate(node_network_receive_packets_total{env=\"$env\",device!=\"lo\", fqdn=\"$node\"}[$__rate_interval])",
     "legendFormat": "Incoming on interface {{device}}"
    }
   ]
  },
  {
   "title": "Count of established TCP connections",
   "type": "graph",
   "description": "Shows point-in-time count of open TCP connections.\n\nNote that there could be microbursts occuring on a smaller time scale than our metrics-polling interval.  To check for this, look for spikes in the nearby counter-based graphs of new incoming and outgoing connections.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_netstat_Tcp_CurrEstab{env=\"$env\",fqdn=~\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "current connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rate of new outgoing and incoming TCP connections (conns/s)",
   "type": "graph",
   "description": "Show this host's new TCP connection rate, split into:\n* Outgoing connections when acting as a client\n* Incoming connections when acting as a server\n\nThese kernel counters are incremented for each newly established outgoing (\"active\") or incoming (\"passive\") TCP connection.  This graph converts the counter to a rate to show the trend.\n\nFor reference, an \"active\" (outgoing) connection is where we are the client sending the initial SYN.  A \"passive\" (incoming) connection is where we are the server-side listener receiving the initial SYN.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{fqdn=~\"$node\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Outgoing TCP connections / second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_netstat_Tcp_PassiveOpens{fqdn=~\"$node\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Incoming TCP connections / second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "As a client or server: TCP SYN or SYN-ACK retry rate (packets/s)",
   "type": "graph",
   "description": "This kernel counter indicates the number of retransmits for outgoing TCP packets with the SYN flag set (i.e. both SYN and SYN-ACK count).\n\nThe same counter is used for retransmits from this host whether it is acting as the client or the server for the affected TCP connection, but it only counts the transmit direction (not the receive direction).  In other words, it counts the following cases of retransmits during connection handshakes:\n* as a client (active connection request): resending the initial SYN connection request after reaching retransmit timeout\n* as a server (passive connection response): resending a SYN-ACK reply to a peer's connection request after reachng retransmit timeout\n\nThis is not a hard failure (the retry may succeed).  But it always indicates slowness (e.g. the 1st retry occurs after 1 second delay, and each subsequent retry uses exponential backoff).\n\nSpikes could hint at any of:\n* Packet loss along the network path (in either direction)\n* Connection rate-limiting (e.g. firewall, DDoS protection, native rate limiting)\n* Saturation on the listener side, having too many pending connection requests already waiting on is backlog, leading to SYN retries from clents",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_TCPSynRetrans{env=\"$env\",fqdn=~\"$node\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TCP retransmits / second for SYN + SYN-ACK",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "As a server: Drop rate for new incoming TCP connection requests (packets/s)",
   "type": "graph",
   "description": "This kernel counter indicates the number of times an incoming TCP SYN packet had to be dropped by the kernel due to the TCP listener's request backlog already being full.\n\nThis is a silent drop.  The TCP client connecting to this host will get no reply, the same as with packet loss in transit.  The client may retransmit its SYN until it reaches its own connection timeout.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_ListenOverflows{env=\"$env\",fqdn=~\"$node\"}[$__rate_interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TCP SYN drops / second",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}