{
 "title": "Image Resizing Experiment",
 "time": { "from": "2020-09-15T09:00:00.000Z", "to": "2020-09-15T15:59:59.000Z" },
 "panels": [
  {
   "title": "Concurrency limit exceeds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_workhorse_image_resize_concurrency_limit_exceeds_total"
    }
   ]
  },
  {
   "title": "Resize processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_workhorse_image_resize_processes{job='gitlab-workhorse-web'}"
    }
   ]
  },
  {
   "title": "Completed Resizes Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_workhorse_image_resize_completed_total{job='gitlab-workhorse-web'}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gitlab_workhorse_image_resize_completed_total[1m])"
    }
   ]
  }
 ]
}