{
 "title": "Imported: Unicorn",
 "description": "Unicorn metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "env", "query": "label_values(up, environment)" }
  ]
 },
 "panels": [
  {
   "title": "Unicorn UP %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(up{job=\"gitlab-unicorn\",environment=~\"$env\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker Restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(changes(unicorn_worker_start_time_seconds{job=\"mtail\",prog=\"unicorn.mtail\",environment=~\"$env\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker OOMs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(unicorn_exceeds_memory_limit_total{environment=~\"$env\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker PID Timeouts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(unicorn_pid_timeouts_total{job=\"mtail\",prog=\"unicorn.mtail\",environment=~\"$env\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Killer Terminations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(unicorn_killer_terminations_total{job=\"mtail\",prog=\"unicorn.mtail\",environment=~\"$env\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Worker Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(time() - unicorn_worker_start_time_seconds{environment=~\"$env\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Master Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(time() - unicorn_master_start_time_seconds{environment=\"$env\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker Kills",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(unicorn_killer_terminations_total{environment=~\"$env\"}[$__interval])) by (signal,type)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}} - {{signal}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Worker Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(unicorn_pid_timeouts_total{environment=~\"$env\"}[$__interval])) without (instance, fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}} - {{tier}} {{priority}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top Slowest Controllers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5,\n  sum(rate(gitlab_transaction_duration_seconds_sum{environment=~\"$env\", type=\"web\"}[$__interval])) without (instance, fqdn, action) \n  /\n  sum(rate(gitlab_transaction_duration_seconds_count{environment=~\"$env\",type=\"web\"}[$__interval])) without (instance, fqdn, action)\n)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{controller}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Queued Unicorn Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(unicorn_queued_connections{environment=~\"$env\", type=\"unix\", fqdn=~\"api.*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "api",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(unicorn_queued_connections{environment=~\"$env\", type=\"unix\", fqdn=~\"web.*\"})",
     "legendFormat": "web"
    },
    {
     "expr": "sum(unicorn_queued_connections{environment=~\"$env\", type=\"unix\", fqdn=~\"git.*\"})",
     "legendFormat": "git"
    },
    {
     "expr": "sum(unicorn_queued_connections{environment=~\"$env\", type=\"unix\", fqdn=~\"sidekiq.*\"})",
     "legendFormat": "sidekiq"
    }
   ]
  },
  {
   "title": "Total Active Unicorn Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(unicorn_active_connections{environment=~\"$env\", type=\"unix\", instance=~\"api.*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "api",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(unicorn_active_connections{environment=~\"$env\", type=\"unix\", instance=~\"web.*\"})",
     "legendFormat": "web"
    },
    {
     "expr": "sum(unicorn_active_connections{environment=~\"$env\", type=\"unix\", instance=~\"git.*\"})",
     "legendFormat": "git"
    },
    {
     "expr": "sum(unicorn_active_connections{environment=~\"$env\", type=\"unix\", instance=~\"sidekiq-.*\"})",
     "legendFormat": "sidekiq"
    }
   ]
  },
  {
   "title": "Queued Unicorn Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unicorn_queued_connections{environment=~\"$env\", type=\"unix\", fqdn!~\"sidekiq.*\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}