{
 "title": "Imported: Git Timings",
 "tags": [
  "blackbox",
  "drilldown",
  "triage"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Notes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "The red threshold is the timeout set on the exporter"
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(git_scrape_timeouts_total{instance=\"gitlab.com\",job=\"git-exporter\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Timeouts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Percentage of errors",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "git_scrape_timeouts_total{instance=\"gitlab.com\",job=\"git-exporter\"}\t/ git_scrape_total{instance=\"gitlab.com\",job=\"git-exporter\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Git Pull", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "HTTPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "git_pull_seconds{tier=\"blackbox\",transport=\"https\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{shard}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SSH",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "git_pull_seconds{tier=\"blackbox\",transport=\"ssh\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{shard}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Git Push", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "HTTPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "git_push_seconds{tier=\"blackbox\",transport=\"https\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{shard}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SSH",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "git_push_seconds{tier=\"blackbox\",transport=\"ssh\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{shard}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git over SSH timings for each shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "nfs-file-01",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-01\",tier=\"blackbox\",transport=\"ssh\"}\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-01\",tier=\"blackbox\",transport=\"ssh\"}\n",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-02",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-02\",tier=\"blackbox\",transport=\"ssh\"}\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-02\",tier=\"blackbox\",transport=\"ssh\"}\n",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-03",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-03\",tier=\"blackbox\",transport=\"ssh\"}\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-03\",tier=\"blackbox\",transport=\"ssh\"}\n",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-04",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-04\",tier=\"blackbox\",transport=\"ssh\"}\n",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-04\",tier=\"blackbox\",transport=\"ssh\"}\n",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-05",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-05\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-05\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-06",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-06\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-06\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-07",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-07\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-07\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-08",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-08\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-08\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-09",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-09\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-09\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-10",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-10\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-10\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-11",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-11\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-11\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-12",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-12\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-12\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-13",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-13\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-13\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-14",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-14\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-14\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-15",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-15\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-15\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-16",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-16\",tier=\"blackbox\",transport=\"ssh\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-16\",tier=\"blackbox\",transport=\"ssh\"}",
       "legendFormat": "Push"
      }
     ]
    }
   ]
  },
  {
   "title": "Git over HTTPS timings for each shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "nfs-file-01",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-01\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-01\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-02",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-02\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-02\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-03",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-03\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-03\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-04",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-04\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-04\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-05",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-05\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-05\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-06",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-06\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-06\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-07",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-07\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-07\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-08",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 58 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-08\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-08\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-09",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-09\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-09\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-10",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-10\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-10\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-11",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-11\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-11\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-12",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 65 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-12\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-12\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-13",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-13\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-13\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-14",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 72 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-14\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-14\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-15",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-15\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-15\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    },
    {
     "title": "nfs-file-16",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 72 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "git_pull_seconds{shard=\"nfs-file-16\",tier=\"blackbox\",transport=\"https\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pull",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "git_push_seconds{shard=\"nfs-file-16\",tier=\"blackbox\",transport=\"https\"}",
       "legendFormat": "Push"
      }
     ]
    }
   ]
  }
 ]
}