{
 "title": "Imported: Unicorn Controller",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(up{job=\"gitlab-unicorn\"}, environment)"
   },
   {
    "name": "type",
    "query": "label_values(gitlab_transaction_duration_seconds_count{environment=~\"$env\"}, type)"
   },
   {
    "name": "controller",
    "query": "label_values(gitlab_transaction_duration_seconds_count{environment=~\"$env\",type=\"$type\"}, controller)"
   },
   {
    "name": "action",
    "query": "label_values(gitlab_transaction_duration_seconds_count{environment=~\"$env\",type=\"$type\",controller=\"$controller\"}, action)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rate(gitlab_transaction_duration_seconds_sum{environment=~\"$env\",controller=~\"$controller\",action=~\"$action\"}[$__interval]))\n  /\navg(rate(gitlab_transaction_duration_seconds_count{environment=~\"$env\",controller=~\"$controller\",action=~\"$action\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_transaction_duration_seconds_count{environment=~\"$env\",controller=~\"$controller\",action=~\"$action\"}[$__interval])) by (action)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ action }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(gitlab_transaction_duration_seconds_sum{environment=~\"$env\",controller=~\"$controller\",action=~\"$action\"}[$__interval])) by (action)\n  /\navg(rate(gitlab_transaction_duration_seconds_count{environment=~\"$env\",controller=~\"$controller\",action=~\"$action\"}[$__interval])) by (action)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ action }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Average Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(rate(gitlab_sql_duration_seconds_sum{environment=~\"$env\",controller=~\"$controller\",action=~\"$action\"}[$__interval]))\n  /\navg(rate(gitlab_sql_duration_seconds_count{environment=~\"$env\",controller=~\"$controller\",action=~\"$action\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Latency (All actions)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitlab_transaction_duration_seconds_bucket{environment=~\"$env\",controller=\"$controller\"}[$__interval])) by (le))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "99th",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(gitlab_transaction_duration_seconds_bucket{environment=~\"$env\",controller=\"$controller\"}[$__interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(gitlab_transaction_duration_seconds_bucket{environment=~\"$env\",controller=\"$controller\"}[$__interval])) by (le))",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}