{
 "title": "Imported: Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(go_memstats_alloc_bytes,job)"
   },
   {
    "name": "fqdn",
    "label": "fqdn",
    "query": "go_memstats_alloc_bytes{job=~\"$job\"}"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\",fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\",fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=\"$job\",fqdn=~\"$fqdn\"}[$interval])",
     "legendFormat": "{{fqdn}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job=\"$job\",fqdn=~\"$fqdn\"}[$interval])",
     "legendFormat": "{{fqdn}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\",fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\",fqdn=~\"$fqdn\"}[30s])",
     "legendFormat": "{{fqdn}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\",fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\",fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{job=\"$job\",fqdn=~\"$fqdn\"}[$interval])",
     "legendFormat": "{{fqdn}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\",fqdn=~\"$fqdn\"}[$interval])",
     "legendFormat": "{{fqdn}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{job=\"$job\",fqdn=~\"$fqdn\"}[$interval])",
     "legendFormat": "{{fqdn}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{job=\"$job\",fqdn=~\"$fqdn\"}[$interval])",
     "legendFormat": "{{fqdn}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\",fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{job=\"$job\",fqdn=~\"$fqdn\"}[$interval])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\",fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\",fqdn=~\"$fqdn\"}",
     "legendFormat": "{{fqdn}} - {{quantile}}"
    }
   ]
  }
 ]
}