{
 "title": "importers: Github Importer",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4200435107 at Fri Apr 28 22:13:07 UTC 2023",
 "tags": [
  "managed",
  "importers",
  "sidekiq",
  "managed",
  "group:import"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Import Duration",
   "type": "graph",
   "description": "Lower is better.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(github_importer_total_duration_seconds_bucket{env=\"$environment\"}[$__interval])) by (le, environment))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(github_importer_total_duration_seconds_bucket{env=\"$environment\"}[$__interval])) by (le, environment))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(github_importer_total_duration_seconds_bucket{env=\"$environment\"}[$__interval])) by (le, environment))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(github_importer_total_duration_seconds_bucket{env=\"$environment\"}[$__interval])) by (le, environment))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Projects successfully imported",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(github_importer_imported_projects_total) or vector(0))",
     "legendFormat": "Projects successfully imported"
    }
   ]
  },
  {
   "title": "Total Objects",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum(rate(github_importer_fetched_issue{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_pull_request{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_pull_request_merged_by{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_pull_request_review{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_milestone{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_note{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_diff_note{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_label{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_lfs_object{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_release{env=\"$environment\"}[$__interval])) or vector(0))) * 3600",
     "legendFormat": "fetched"
    },
    {
     "expr": "((sum(rate(github_importer_imported_issue{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_pull_request{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_pull_request_merged_by{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_pull_request_review{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_milestone{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_note{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_diff_note{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_label{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_lfs_object{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_release{env=\"$environment\"}[$__interval])) or vector(0))) * 3600",
     "legendFormat": "imported"
    },
    {
     "expr": "((((sum(rate(github_importer_fetched_issue{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_pull_request{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_pull_request_merged_by{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_pull_request_review{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_milestone{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_note{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_diff_note{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_label{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_lfs_object{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_fetched_release{env=\"$environment\"}[$__interval])) or vector(0))) - ((sum(rate(github_importer_imported_issue{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_pull_request{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_pull_request_merged_by{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_pull_request_review{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_milestone{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_note{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_diff_note{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_label{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_lfs_object{env=\"$environment\"}[$__interval])) or vector(0)) + (sum(rate(github_importer_imported_release{env=\"$environment\"}[$__interval])) or vector(0)))) * 3600) or vector(0)",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "issue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(github_importer_fetched_issue{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "fetched issue"
    },
    {
     "expr": "(sum(rate(github_importer_imported_issue{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "imported issue"
    },
    {
     "expr": "((((sum(rate(github_importer_fetched_issue{env=\"$environment\"}[$__interval])) or vector(0))) - ((sum(rate(github_importer_imported_issue{env=\"$environment\"}[$__interval])) or vector(0)))) * 3600) or vector(0)",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "pull_request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(github_importer_fetched_pull_request{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "fetched pull_request"
    },
    {
     "expr": "(sum(rate(github_importer_imported_pull_request{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "imported pull_request"
    },
    {
     "expr": "((((sum(rate(github_importer_fetched_pull_request{env=\"$environment\"}[$__interval])) or vector(0))) - ((sum(rate(github_importer_imported_pull_request{env=\"$environment\"}[$__interval])) or vector(0)))) * 3600) or vector(0)",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "pull_request_merged_by",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(github_importer_fetched_pull_request_merged_by{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "fetched pull_request_merged_by"
    },
    {
     "expr": "(sum(rate(github_importer_imported_pull_request_merged_by{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "imported pull_request_merged_by"
    },
    {
     "expr": "((((sum(rate(github_importer_fetched_pull_request_merged_by{env=\"$environment\"}[$__interval])) or vector(0))) - ((sum(rate(github_importer_imported_pull_request_merged_by{env=\"$environment\"}[$__interval])) or vector(0)))) * 3600) or vector(0)",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "pull_request_review",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(github_importer_fetched_pull_request_review{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "fetched pull_request_review"
    },
    {
     "expr": "(sum(rate(github_importer_imported_pull_request_review{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "imported pull_request_review"
    },
    {
     "expr": "((((sum(rate(github_importer_fetched_pull_request_review{env=\"$environment\"}[$__interval])) or vector(0))) - ((sum(rate(github_importer_imported_pull_request_review{env=\"$environment\"}[$__interval])) or vector(0)))) * 3600) or vector(0)",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "milestone",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(github_importer_fetched_milestone{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "fetched milestone"
    },
    {
     "expr": "(sum(rate(github_importer_imported_milestone{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "imported milestone"
    },
    {
     "expr": "((((sum(rate(github_importer_fetched_milestone{env=\"$environment\"}[$__interval])) or vector(0))) - ((sum(rate(github_importer_imported_milestone{env=\"$environment\"}[$__interval])) or vector(0)))) * 3600) or vector(0)",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "note",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(github_importer_fetched_note{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "fetched note"
    },
    {
     "expr": "(sum(rate(github_importer_imported_note{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "imported note"
    },
    {
     "expr": "((((sum(rate(github_importer_fetched_note{env=\"$environment\"}[$__interval])) or vector(0))) - ((sum(rate(github_importer_imported_note{env=\"$environment\"}[$__interval])) or vector(0)))) * 3600) or vector(0)",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "diff_note",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(github_importer_fetched_diff_note{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "fetched diff_note"
    },
    {
     "expr": "(sum(rate(github_importer_imported_diff_note{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "imported diff_note"
    },
    {
     "expr": "((((sum(rate(github_importer_fetched_diff_note{env=\"$environment\"}[$__interval])) or vector(0))) - ((sum(rate(github_importer_imported_diff_note{env=\"$environment\"}[$__interval])) or vector(0)))) * 3600) or vector(0)",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "label",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(github_importer_fetched_label{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "fetched label"
    },
    {
     "expr": "(sum(rate(github_importer_imported_label{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "imported label"
    },
    {
     "expr": "((((sum(rate(github_importer_fetched_label{env=\"$environment\"}[$__interval])) or vector(0))) - ((sum(rate(github_importer_imported_label{env=\"$environment\"}[$__interval])) or vector(0)))) * 3600) or vector(0)",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "lfs_object",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(github_importer_fetched_lfs_object{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "fetched lfs_object"
    },
    {
     "expr": "(sum(rate(github_importer_imported_lfs_object{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "imported lfs_object"
    },
    {
     "expr": "((((sum(rate(github_importer_fetched_lfs_object{env=\"$environment\"}[$__interval])) or vector(0))) - ((sum(rate(github_importer_imported_lfs_object{env=\"$environment\"}[$__interval])) or vector(0)))) * 3600) or vector(0)",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "release",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(github_importer_fetched_release{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "fetched release"
    },
    {
     "expr": "(sum(rate(github_importer_imported_release{env=\"$environment\"}[$__interval])) or vector(0)) * 3600",
     "legendFormat": "imported release"
    },
    {
     "expr": "((((sum(rate(github_importer_fetched_release{env=\"$environment\"}[$__interval])) or vector(0))) - ((sum(rate(github_importer_imported_release{env=\"$environment\"}[$__interval])) or vector(0)))) * 3600) or vector(0)",
     "legendFormat": "diff"
    }
   ]
  }
 ]
}