{
 "title": "Imported: Situation Room: Infra#4027",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "method",
    "query": "label_values(grpc_server_started_total{job=\"gitaly\"}, grpc_method)"
   },
   {
    "name": "fqdn",
    "query": "label_values(up{job=~\"gitaly.*\"}, fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load15{fqdn=\"$fqdn\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "load15",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gitaly Method Invocation Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{fqdn=\"$fqdn\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "All GRPC invocations on $fqdn",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_method=\"$method\", fqdn=\"$fqdn\"}[$__interval])) by (grpc_method)",
     "legendFormat": "Method {{ grpc_method }} invocations on $fqdn"
    }
   ]
  },
  {
   "title": "p99 times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{fqdn=\"$fqdn\", grpc_method=\"$method\"}[$__interval])) by (grpc_method,le)\n)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Selected Method Invocation Rates on $fqdn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{fqdn=\"$fqdn\", grpc_method=\"FindCommit\"}[$__interval])) by (grpc_method)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ grpc_method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{fqdn=\"$fqdn\", grpc_method=\"HasLocalBranches\"}[$__interval])) by (grpc_method)",
     "legendFormat": "{{ grpc_method }}"
    }
   ]
  },
  {
   "title": "FindCommit invocations per controller#action",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_find_commit_gitaly_real_duration_seconds_sum{}[$__interval])) by (controller, action)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ controller }}#{{ action }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}