{
 "title": "Imported: GitHub Importer BJK",
 "description": "Prometheus statistics about the GitHub importer",
 "tags": [
  "prometheus",
  "github"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Import Statistics", "type": "row", "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Imports",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(github_importer_imported_projects{environment = \"gprd\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Projects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(increase(github_importer_imported_repositories{environment = \"gprd\"}[$__interval]))",
     "legendFormat": "Repos"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Imports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(github_importer_imported_projects{environment = \"gprd\"}[1d]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Projects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(increase(github_importer_imported_repositories{environment = \"gprd\"}[1d]))",
     "legendFormat": "Repos"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "PRs per Hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_importer_imported_pull_requests{environment = \"gprd\"}[$__interval])) * 3600",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "PRs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Notes per Hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(github_importer_imported_notes{environment=\"gprd\"}[$__interval]) + rate(github_importer_imported_diff_notes{environment=\"gprd\"}[$__interval]))) * 3600",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Notes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Issues per Hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_importer_imported_issues{environment = \"gprd\"}[$__interval])) * 3600",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Issues",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Rate Limiting", "type": "row", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Rate Limit Hit per Hour",
   "type": "graph",
   "description": "The number of times we hit the GitHub API's rate limit.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_importer_rate_limit_hits{environment=\"gprd\"}[$__interval])) * 3600",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Amount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "API Requests per Hour",
   "type": "graph",
   "description": "The number of GitHub API requests performed.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_importer_request_count{environment=\"gprd\"}[$__interval])) * 3600",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Amount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}