{
 "title": "Incident: 405: Failing API Health Checks",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk Read IO Seconds per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{environment=\"gprd\", type=\"gitaly\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Disk Read IO Seconds per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{environment=\"gprd\", type=\"gitaly\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Performance Relative to 1 week ago",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_duration_seconds{instance=~\"^https://gitlab.com.*\"}[$__interval])) / avg(avg_over_time(probe_duration_seconds{instance=~\"^https://gitlab.com.*\"}[$__interval] offset 1w))"
    }
   ]
  },
  {
   "title": "GCP: Average Write Operation Time (log10)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_write_time_seconds_total{type=\"gitaly\", device=\"sdb\"}[$__interval]) / rate(node_disk_writes_completed_total[$__interval])) by (fqdn)",
     "legendFormat": "{{ fqdn }}: sdb"
    }
   ]
  },
  {
   "title": "Performance Relative to 1 week ago",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{instance=~\"^https://gitlab.com.*\"}[$__interval]) / avg_over_time(probe_duration_seconds{instance=~\"^https://gitlab.com.*\"}[$__interval] offset 1w)"
    }
   ]
  },
  {
   "title": "GCP: Average Read Operation Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_read_time_seconds_total{type=\"gitaly\", device=\"sdb\"}[$__interval]) / rate(node_disk_reads_completed_total[$__interval])) by (fqdn, device)",
     "legendFormat": "{{ fqdn }}, {{ device}}"
    }
   ]
  },
  {
   "title": "p95 Workhorse Queuing Waiting Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_workhorse_queueing_waiting_time_bucket{environment=\"gprd\"}[$__interval])) by (le, tier))\n\n\n\n",
     "legendFormat": "{{ tier }}"
    }
   ]
  },
  {
   "title": "Gitaly Unary Durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{job=\"gitaly\", grpc_type=\"unary\", environment=\"gprd\"}[$__interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{job=\"gitaly\", grpc_type=\"unary\", environment=\"gprd\"}[$__interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Workhorse API and Web durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"gprd\", route=~\"^($|\\\\^/api/)\"}[5m])) by (route, le))\n",
     "legendFormat": "p95: {{ route }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"gprd\", route=~\"^($|\\\\^/api/)\"}[5m])) by (route, le))\n",
     "legendFormat": "p99: {{ route }}"
    }
   ]
  },
  {
   "title": "Workhorse Requests in Progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nsum(gitlab_workhorse_http_in_flight_requests) by (type)"
    }
   ]
  },
  {
   "title": "Unicorn Queued Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(unicorn_queued_connections{fqdn=~\"^api.*\"})",
     "legendFormat": "api"
    },
    {
     "expr": "sum(unicorn_queued_connections{fqdn=~\"^web.*\"})",
     "legendFormat": "web"
    }
   ]
  },
  {
   "title": "Workhorse Error Responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"gprd\"}[$__interval])) by (type, code) / ignoring(code)\ngroup_left\nsum(rate(gitlab_workhorse_http_requests_total{environment=\"gprd\"}[$__interval])) by (type) ",
     "legendFormat": "{{ type }}: {{ code }}"
    }
   ]
  },
  {
   "title": "API Backend Health",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(haproxy_server_up{environment=\"gprd\", backend=\"api\"})"
    }
   ]
  },
  {
   "title": "Gitaly Average Durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(grpc_server_handling_seconds_sum{job=\"gitaly\", grpc_type=\"unary\", environment=\"gprd\"}[$__interval]) / \n(rate(grpc_server_handling_seconds_count{job=\"gitaly\", grpc_type=\"unary\", environment=\"gprd\"}[$__interval]) > 0))  "
    }
   ]
  }
 ]
}