{
 "title": "Increase canary traffic",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "prometheus_app", "query": "prometheus" },
   { "name": "environment", "query": "gprd,gstg" }
  ]
 },
 "panels": [
  {
   "title": "Canary backend status codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code, backend) (\n  backend_code:haproxy_server_http_responses_total:irate1m{backend=\"canary_web\"}\n)",
     "legendFormat": "Backend {{ code }} {{ backend }}"
    }
   ]
  },
  {
   "title": "Canary stage workhorse req/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(topk(1, sum(rate(gitlab_workhorse_http_requests_total{code=\"200\", environment=\"gprd\",job=\"gitlab-workhorse-web\", stage=\"cny\", route!=\"^/-/(readiness|liveness)$\"}[1m])) by (fqdn)))",
     "legendFormat": "req/sec for 200 status code"
    }
   ]
  },
  {
   "title": "Main stage workhorse req/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(topk(1, sum(rate(gitlab_workhorse_http_requests_total{code=\"200\", environment=\"gprd\",job=\"gitlab-workhorse-web\", stage=\"main\", route!=\"^/-/(readiness|liveness)$\"}[1m])) by (fqdn)))",
     "legendFormat": "req/sec for 200 status code"
    }
   ]
  },
  {
   "title": "Canary stage workhorse req/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gitlab_workhorse_http_requests_total{environment=\"$environment\",job=\"gitlab-workhorse-git\",stage=\"cny\", route!=\"^/-/health$\"}[1m])",
     "legendFormat": "{{ route }} {{ fqdn }}"
    }
   ]
  }
 ]
}