{
 "title": "Infrastructure Stats",
 "tags": [
  "host",
  "drilldown"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg,ops" },
   {
    "name": "tier",
    "query": "label_values(up{fqdn=~\".*registry.*\"},tier)"
   },
   {
    "name": "type",
    "query": "label_values(up{fqdn=~\".*registry.*\"},type)"
   },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(up{fqdn=~\".*registry.*\",tier=\"$tier\"},fqdn)"
   },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Fleet node stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fleet Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{fqdn=~\".*registry.*\", tier=\"$tier\"} / node_memory_MemTotal_bytes{fqdn=~\".*registry.*\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleet IOWait per CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(instance_mode:node_cpu:rate5m{mode=\"iowait\",fqdn=~\".*registry.*\",tier=\"$tier\"}) by (fqdn) / sum(instance:node_cpus:count) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleet CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(instance_cpu:node_cpu_not_idle:rate5m{fqdn=~\".*registry.*\",environment=\"$environment\",tier=\"$tier\"}) without (cpu) / instance:node_cpus:count{fqdn=~\".*registry.*\",environment=\"$environment\",tier=\"$tier\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleet Load per CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_load1{fqdn=~\".*registry.*\",tier=\"$tier\"}[$__interval]) / instance:node_cpus:count",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleet Swap IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_vmstat_pgpgin{fqdn=~\".*registry.*\",tier=\"$tier\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }} in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "increase(node_vmstat_pgpgout{fqdn=~\".*registry.*\",tier=\"$tier\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }} out",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleet Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault{fqdn=~\".*registry.*\",tier=\"$tier\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleet Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\".*registry.*\",tier=\"$tier\"}[$__interval])) by (fqdn)",
     "legendFormat": "send {{fqdn}}"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\".*registry.*\",tier=\"$tier\"}[$__interval])) by (fqdn)",
     "legendFormat": "receive {{fqdn}}"
    }
   ]
  },
  {
   "title": "Fleet Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "cs p/s" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches_total{fqdn=~\".*registry.*\",tier=\"$tier\"}[$__interval])",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Fleet Available Filesystem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_filesystem_avail:ratio{fqdn=~\".*registry.*\",tier=\"$tier\",fstype=~\"ext.|xfs\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} {{mountpoint}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fleet Allocated file descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{fqdn=~\".*registry.*\",tier=\"$tier\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} Allocated",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_filefd_maximum{fqdn=~\".*registry.*\",tier=\"$tier\"}",
     "legendFormat": "{{fqdn}} Max"
    }
   ]
  }
 ]
}