{
 "title": "internal-api: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4891699520 at Thu Aug 17 11:39:27 UTC 2023",
 "tags": [
  "managed",
  "internal-api",
  "gitlab",
  "type:internal-api",
  "internal-api",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "internal-api Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n",
     "legendFormat": "internal-api apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n",
     "legendFormat": "internal-api apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "internal-api Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "internal-api Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "internal-api error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "internal-api error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "internal-api Service | Errors"
    }
   ]
  },
  {
   "title": "internal-api Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n",
     "legendFormat": "internal-api RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "rails_request SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n",
     "legendFormat": "rails_request apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n",
     "legendFormat": "rails_request apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "rails_request SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "rails_request SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rails_request error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rails_request error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "rails_request SLI | Errors"
    }
   ]
  },
  {
   "title": "rails_request SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n",
     "legendFormat": "rails_request RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "content": "### Description\n\nThe number of requests meeting their duration target based on the urgency\nof the endpoint. By default, a request should take no more than 1s. But\nthis can be adjusted by endpoint.\n\nRead more about this in the [documentation](https://docs.gitlab.com/ee/development/application_slis/rails_request_apdex.html).\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value'))))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase)))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase)))),(meta:(field:json.status,index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "workhorse SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n",
     "legendFormat": "workhorse apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n",
     "legendFormat": "workhorse apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "workhorse SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "workhorse SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "workhorse error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "workhorse error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"workhorse\",monitor=\"global\",type=\"internal-api\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "workhorse SLI | Errors"
    }
   ]
  },
  {
   "title": "workhorse SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"}[$__interval])\n",
     "legendFormat": "workhorse RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"internal-api\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "content": "### Description\n\nAggregation of most web requests that pass through workhorse, monitored via the HTTP interface.\nExcludes health, readiness and liveness requests. Some known slow requests, such as HTTP uploads,\nare excluded from the apdex score.\n\n\n\n### Observability Tools\n\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/workhorse-api;type=CPU/cpu?project=gitlab-production)\n* [🐞 Sentry Releases: gitlab/gitlab-workhorse-gitlabcom](https://sentry.gitlab.net/gitlab/gitlab-workhorse-gitlabcom/releases?environment=${environment})\n* [🐞 Sentry issues](https://sentry.gitlab.net/gitlab/gitlab-workhorse-gitlabcom/issues?environment=${environment})\n* [📖 Kibana: Workhorse logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:'internal-api',type:phrase),query:(match:(json.type.keyword:(query:'internal-api',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Workhorse slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:'internal-api',type:phrase),query:(match:(json.type.keyword:(query:'internal-api',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase)))),(meta:(field:json.duration_ms,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.duration_ms,params:(gte:10000,lte:!n),type:range),query:(range:(json.duration_ms:(gte:10000,lte:!n))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4',sort:!(!(json.duration_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Workhorse failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:'internal-api',type:phrase),query:(match:(json.type.keyword:(query:'internal-api',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase)))),(meta:(field:json.status,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:'internal-api',type:phrase),query:(match:(json.type.keyword:(query:'internal-api',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:'internal-api',type:phrase),query:(match:(json.type.keyword:(query:'internal-api',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase)))),(meta:(field:json.status,index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.status,params:(gte:500,lte:!n),type:range),query:(range:(json.status:(gte:500,lte:!n))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:'internal-api',type:phrase),query:(match:(json.type.keyword:(query:'internal-api',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:'internal-api',type:phrase),query:(match:(json.type.keyword:(query:'internal-api',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:'internal-api',type:phrase),query:(match:(json.type.keyword:(query:'internal-api',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type.keyword,params:'internal-api',type:phrase),query:(match:(json.type.keyword:(query:'internal-api',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(index:'a4f5b470-edde-11ea-81e5-155ba78758d4',key:json.type,params:'internal-api',type:phrase),query:(match:(json.type:(query:'internal-api',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "🔬 SLI Detail: rails_request",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "rails_request Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_rails_request_error_total_rate5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "rails_request RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_rails_request_total_rate5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_request Latency - per endpoint_id",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n    )\n    -\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_success_total_rate5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n    )\n  )\n  / ignoring (endpoint_id) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "rails_request Errors - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli_rails_request_error_total_rate5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "rails_request RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli_rails_request_total_rate5m{endpoint_id!=\"\",env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_request Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_success_total_rate5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "rails_request Errors - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_rails_request_error_total_rate5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "rails_request RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_rails_request_total_rate5m{env=\"$environment\",environment=\"$environment\",feature_category!=\"\",job=\"gitlab-rails\",stage=\"$stage\",type=\"internal-api\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_request Latency - per request_urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (request_urgency) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\",type=\"internal-api\"}\n    )\n    -\n    sum by (request_urgency) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_success_total_rate5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\",type=\"internal-api\"}\n    )\n  )\n  / ignoring (request_urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\",type=\"internal-api\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    },
    {
     "title": "rails_request Errors - per request_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (request_urgency) (\n  sli_aggregations:gitlab_sli_rails_request_error_total_rate5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\",type=\"internal-api\"}\n)\n > 0",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    },
    {
     "title": "rails_request RPS - per request_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (request_urgency) (\n  sli_aggregations:gitlab_sli_rails_request_total_rate5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\",type=\"internal-api\"}\n)\n > 0",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: workhorse",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 workhorse Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p90 overall"
      }
     ]
    },
    {
     "title": "workhorse Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_workhorse_http_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\", job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", code=~\"^5.*\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "workhorse RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_workhorse_http_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\", job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p90 workhorse Latency - per region",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le,region) (\n    rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",region!=\"\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p90 {{region}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for workhorse Latency - per region",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (region) (\n  rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",region!=\"\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (region) (\n    rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",region!=\"\",stage=\"$stage\", le=\"1\"}[$__interval])\n  )\n  +\n  sum by (region) (\n    rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",region!=\"\",stage=\"$stage\", le=\"10\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(region) group_left()\n  (\n    sum by () (\n  rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",region!=\"\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "workhorse Errors - per region",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (region) (\n  rate(gitlab_workhorse_http_requests_total{env=\"$environment\",environment=\"$environment\",region!=\"\",stage=\"$stage\", job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", code=~\"^5.*\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "workhorse RPS - per region",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (region) (\n  rate(gitlab_workhorse_http_requests_total{env=\"$environment\",environment=\"$environment\",region!=\"\",stage=\"$stage\", job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "Estimated p90 workhorse Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le,method) (\n    rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",method!=\"\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p90 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for workhorse Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",method!=\"\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",method!=\"\",stage=\"$stage\", le=\"1\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",method!=\"\",stage=\"$stage\", le=\"10\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",method!=\"\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "workhorse Errors - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(gitlab_workhorse_http_requests_total{env=\"$environment\",environment=\"$environment\",method!=\"\",stage=\"$stage\", job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", code=~\"^5.*\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "workhorse RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(gitlab_workhorse_http_requests_total{env=\"$environment\",environment=\"$environment\",method!=\"\",stage=\"$stage\", job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Estimated p90 workhorse Latency - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le,route) (\n    rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",route!=\"\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p90 {{route}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for workhorse Latency - per route",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (route) (\n  rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",route!=\"\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (route) (\n    rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",route!=\"\",stage=\"$stage\", le=\"1\"}[$__interval])\n  )\n  +\n  sum by (route) (\n    rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",route!=\"\",stage=\"$stage\", le=\"10\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(route) group_left()\n  (\n    sum by () (\n  rate(gitlab_workhorse_http_request_duration_seconds_bucket{job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",route!=\"\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "workhorse Errors - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (\n  rate(gitlab_workhorse_http_requests_total{env=\"$environment\",environment=\"$environment\",route!=\"\",stage=\"$stage\", job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\", code=~\"^5.*\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "workhorse RPS - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (\n  rate(gitlab_workhorse_http_requests_total{env=\"$environment\",environment=\"$environment\",route!=\"\",stage=\"$stage\", job=~\"gitlab-workhorse-api|gitlab-workhorse\", type=\"internal-api\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true,
   "panels": [
    {
     "title": "internal-api Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      deployment=\"internal-api\",env=\"$environment\",environment=\"$environment\",type=\"internal-api\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "internal-api Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    deployment=\"internal-api\",env=\"$environment\",environment=\"$environment\",type=\"internal-api\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "internal-api Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"internal-api\",env=\"$environment\",environment=\"$environment\",type=\"internal-api\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"internal-api\",env=\"$environment\",environment=\"$environment\",type=\"internal-api\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "Node CPU Requests Utilization",
     "type": "graph",
     "description": "Ratio of requested CPU resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by memory requests already.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",type=\"internal-api\",resource=\"cpu\"}\n",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Node Memory Requests Utilization",
     "type": "graph",
     "description": "Ratio of requested Memory resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by CPU requests already.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"}\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",type=\"internal-api\",resource=\"memory\"}\n",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. When this is exhausted, the container may be thottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_rss component saturation: Kube Container Memory Utilization (RSS)",
     "type": "graph",
     "description": "Records the total anonymous (unevictable) memory utilization for containers for this\nservice, as a percentage of the memory limit as configured through Kubernetes.\n\nThis is computed using the container's resident set size (RSS), as opposed to\nkube_container_memory which uses the working set size. For our purposes, RSS is the\nbetter metric as cAdvisor's working set calculation includes pages from the\nfilesystem cache that can (and will) be evicted before the OOM killer kills the\ncgroup.\n\nA container's RSS (anonymous memory usage) is still not precisely what the OOM\nkiller will use, but it's a better approximation of what the container's workload is\nactually using. RSS metrics can, however, be dramatically inflated if a process in\nthe container uses MADV_FREE (lazy-free) memory. RSS will include the memory that is\navailable to be reclaimed without a page fault, but not currently in use.\n\nThe most common case of OOM kills is for anonymous memory demand to overwhelm the\ncontainer's memory limit. On swapless hosts, anonymous memory cannot be evicted from\nthe page cache, so when a container's memory usage is mostly anonymous pages, the\nonly remaining option to relieve memory pressure may be the OOM killer.\n\nAs container RSS approaches container memory limit, OOM kills become much more\nlikely. Consequently, this ratio is a good leading indicator of memory saturation\nand OOM risk.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      container_memory_rss:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_container_rss\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_container_rss\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_container_rss\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_rss\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_rss\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_go_memory component saturation: Go Memory Utilization per Node",
     "type": "graph",
     "description": "Measures Go memory usage as a percentage of container memory limit\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard, cluster, pod) (\n  clamp_min(\n    clamp_max(\n      go_memstats_alloc_bytes{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}\n      / on(env, environment, tier, type, stage, shard, cluster, pod) group_left()\n      topk by(env, environment, tier, type, stage, shard, cluster, pod) (1,\n        container_spec_memory_limit_bytes:labeled{container=~\"gitlab-pages|gitlab-workhorse|kas|registry|thanos-store\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ cluster }} {{ pod }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_go_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_go_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_go_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_horizontalpodautoscaler_desired_replicas component saturation: Horizontal Pod Autoscaler Desired Replicas",
     "type": "graph",
     "description": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, horizontalpodautoscaler, shard) (\n  clamp_min(\n    clamp_max(\n      kube_horizontalpodautoscaler_status_desired_replicas:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects|urgent-other\", namespace!~\"pubsubbeat\"}\n      /\n      kube_horizontalpodautoscaler_spec_max_replicas:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects|urgent-other\", namespace!~\"pubsubbeat\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ horizontalpodautoscaler }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_pool_cpu component saturation: Average Node Pool CPU Utilization",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in the node pool for\na service fleet.\n\nIf it is becoming saturated, it may indicate that the fleet needs horizontal scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard) (\n        rate(node_cpu_seconds_total:labeled{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_pool_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_pool_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_pool_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_pool_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_pool_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_pool_max_nodes component saturation: Kube Pool Max Node Limit",
     "type": "graph",
     "description": "A GKE kubernetes node pool is close to it's maximum number of nodes.\n\nThe maximum is defined in terraform, via the `max_node_count` field of a node pool. The limit is per-zone, so for\nsingle zone clusters the number of nodes will match the limit, for regional clusters, the limit is multiplied by\nthe number of zones the cluster is deployed over.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard, cluster, label_pool, shard) (\n  clamp_min(\n    clamp_max(\n      count by (cluster, env, environment, label_pool, tier, type, stage, shard) (\n        kube_node_labels:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}\n      )\n      / on(cluster, env, environment, label_pool) group_left() (\n        label_replace(\n          terraform_report_google_cluster_node_pool_max_node_count,\n          \"label_pool\", \"$0\", \"pool_name\", \".*\"\n        )\n        * on(cluster, env, environment) group_left()\n        count by (cluster, env, environment) (\n          group by (cluster, env, environment, label_topology_kubernetes_io_zone) (\n            kube_node_labels:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}\n          )\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ cluster }} {{ label_pool }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_pool_max_nodes\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_pool_max_nodes\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"kube_pool_max_nodes\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_pool_max_nodes\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_pool_max_nodes\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "ruby_thread_contention component saturation: Ruby Thread Contention",
     "type": "graph",
     "description": "Ruby (technically Ruby MRI), like some other scripting languages, uses a Global VM lock (GVL) also known as a\nGlobal Interpreter Lock (GIL) to ensure that multiple threads can execute safely. Ruby code is only allowed to\nexecute in one thread in a process at a time. When calling out to c extensions, the thread can cede the lock to\nother thread while it continues to execute.\n\nThis means that when CPU-bound workloads run in a multithreaded environment such as Puma or Sidekiq, contention\nwith other Ruby worker threads running in the same process can occur, effectively slowing thoses threads down as\nthey await GVL entry.\n\nOften the best fix for this situation is to add more workers by scaling up the fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    quantile by(environment, tier, type, stage, shard, fqdn, pod) (\n  0.99,\n  clamp_min(\n    clamp_max(\n      rate(ruby_process_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\"}[1h])\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ pod }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"ruby_thread_contention\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"ruby_thread_contention\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"internal-api\", component=\"ruby_thread_contention\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"ruby_thread_contention\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"ruby_thread_contention\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\n  patroni\n  pgbouncer\n  redis\n  redis-cache\n  redis-sidekiq\nend\n\nsubgraph stor\n  gitaly\n  praefect\nend\n\nsubgraph sv\n  consul\n  internal-api\nend\n\n\n  gitaly --> gitaly\ninternal-api --> consul\ninternal-api --> gitaly\ninternal-api --> patroni\ninternal-api --> pgbouncer\ninternal-api --> praefect\ninternal-api --> redis\ninternal-api --> redis-cache\ninternal-api --> redis-sidekiq\npgbouncer --> patroni\npraefect --> cloud-sql\npraefect --> gitaly\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\n  patroni\n  pgbouncer\n  redis\n  redis-cache\n  redis-sidekiq\nend\n\nsubgraph stor\n  gitaly\n  praefect\nend\n\nsubgraph sv\n  consul\n  internal-api\nend\n\n\n  gitaly --> gitaly\ninternal-api --> consul\ninternal-api --> gitaly\ninternal-api --> patroni\ninternal-api --> pgbouncer\ninternal-api --> praefect\ninternal-api --> redis\ninternal-api --> redis-cache\ninternal-api --> redis-sidekiq\npgbouncer --> patroni\npraefect --> cloud-sql\npraefect --> gitaly\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql[\"cloud-sql (Level 1)\"]\n  patroni[\"patroni (Level 2)\"]\n  pgbouncer[\"pgbouncer (Level 1)\"]\n  redis-cache[\"redis-cache (Level 3)\"]\n  redis-sidekiq[\"redis-sidekiq (Level 3)\"]\n  redis[\"redis (Level 3)\"]\nend\n\nsubgraph stor\n  gitaly[\"gitaly (Level 3)\"]\n  praefect[\"praefect (Level 2)\"]\nend\n\nsubgraph sv\n  consul[\"consul (Level 1)\"]\n  internal-api[\"internal-api (Level 2)\"]\nend\n\n\n  gitaly[\"gitaly (Level 3)\"] --> gitaly\ninternal-api[\"internal-api (Level 2)\"] --> consul\ninternal-api[\"internal-api (Level 2)\"] --> gitaly\ninternal-api[\"internal-api (Level 2)\"] --> patroni\ninternal-api[\"internal-api (Level 2)\"] --> pgbouncer\ninternal-api[\"internal-api (Level 2)\"] --> praefect\ninternal-api[\"internal-api (Level 2)\"] --> redis\ninternal-api[\"internal-api (Level 2)\"] --> redis-cache\ninternal-api[\"internal-api (Level 2)\"] --> redis-sidekiq\npgbouncer[\"pgbouncer (Level 1)\"] --> patroni\npraefect[\"praefect (Level 2)\"] --> cloud-sql\npraefect[\"praefect (Level 2)\"] --> gitaly\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}