{
 "title": "issue 7661",
 "tags": [ "playground" ],
 "time": { "from": "2019-10-15T00:14:07.699Z", "to": "2019-10-29T14:47:21.869Z" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   {
    "name": "Node",
    "query": "query_result(count(count_over_time(kube_node_labels{environment=\"$environment\", cluster=\"$cluster\"}[1w])) by (label_kubernetes_io_hostname))"
   },
   { "name": "Deployment", "query": "gitlab-registry," }
  ]
 },
 "panels": [
  { "title": "Container Registry Version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=\"registry\", cluster=\"$cluster\"}) by (image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Rate of Scale",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kube_replicaset_spec_replicas{replicaset=~\"gitlab-registry-.*\", cluster=\"$cluster\"}[1h])) by (replicaset)",
     "legendFormat": "{{ replicaset }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "avg(sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", image!=\"\", pod_name=~\"^$Deployment.*$\", node=~\"^$Node$\"}[1m])) by (pod_name,node))",
     "legendFormat": "average"
    }
   ]
  }
 ]
}