{
 "title": "John H: Plan PM/Certify Performance",
 "time": { "from": "2019-10-30T15:07:27.026Z", "to": "2019-11-05T13:42:31.642Z" },
 "panels": [
  { "title": "SQL Query and 5xx Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SQL Query Counts by Controller Action",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "action" ], "type": "tag" }
     ],
     "measurement": "rails_transaction_sql_counts_per_action",
     "query": "SELECT mean(\"sql_count_mean\") AS \"Mean SQL Query Count\" FROM \"downsampled\".\"rails_transaction_sql_counts_per_action\" WHERE (\"action\" =~ /Groups::Epic.*/) AND $timeFilter GROUP BY \"action\" ",
     "select": [
      [
       { "params": [ "sql_count_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "Groups::EpicsController#index" }
     ]
    }
   ]
  },
  {
   "title": "Rails Metrics By Product Functionality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Viewing an Epic",
   "type": "graph",
   "description": "Mean request durations for actions involved in showing an epic",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_action",
     "groupBy": [
      { "params": [ "action" ], "type": "tag" }
     ],
     "measurement": "rails_transaction_timings_per_action",
     "query": "SELECT \"duration_mean\" FROM \"downsampled\".\"rails_transaction_timings_per_action\" WHERE ((\"action\" =~ /Groups::EpicsController.*/ AND \"action\" =~ /(show|discussions|realtime_changes)/) OR (\"action\" =~ /Groups::Epics::NotesController.*/ AND \"action\" =~ /(index\\.json)/)) AND $timeFilter GROUP BY \"action\"",
     "select": [
      [
       { "params": [ "duration_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "action",
       "operator": "=",
       "value": "Groups::EpicsController#create.json"
      },
      {
       "condition": "OR",
       "key": "action",
       "operator": "=",
       "value": "Groups::EpicIssuesController#index.json"
      }
     ]
    }
   ]
  },
  {
   "title": "Interacting with an Epic",
   "type": "graph",
   "description": "Mean request duration for actions that involve interacting with an epic; updating description, adding/editing notes, linking epics and issues.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_action",
     "groupBy": [
      { "params": [ "action" ], "type": "tag" }
     ],
     "measurement": "rails_transaction_timings_per_action",
     "query": "SELECT \"duration_mean\" FROM \"downsampled\".\"rails_transaction_timings_per_action\" WHERE ((\"action\" =~ /Groups::EpicsController.*/ AND \"action\" =~ /(update|toggle_award_emoji)/) OR (\"action\" =~ /Groups::Epics::NotesController.*/ AND \"action\" =~ /(create\\.json|update\\.json)/) OR (\"action\" =~ /Groups::EpicIssuesController.*/ AND \"action\" =~ /(create\\.json|update\\.json|destroy\\.json)/) OR (\"action\" =~ /Groups::EpicLinksController.*/ AND \"action\" =~ /(create\\.json|update\\.json|destroy\\.json)/)) AND $timeFilter GROUP BY \"action\"",
     "select": [
      [
       { "params": [ "duration_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "action",
       "operator": "=",
       "value": "Groups::EpicsController#create.json"
      },
      {
       "condition": "OR",
       "key": "action",
       "operator": "=",
       "value": "Groups::EpicIssuesController#index.json"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rails_transaction_timings_per_action",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "Groups::EpicI" }
     ]
    }
   ]
  },
  {
   "title": "Viewing Epics List and Roadmap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_action",
     "groupBy": [
      { "params": [ "action" ], "type": "tag" }
     ],
     "measurement": "rails_transaction_timings_per_action",
     "query": "SELECT \"duration_mean\" FROM \"downsampled\".\"rails_transaction_timings_per_action\" WHERE ((\"action\" =~ /Groups::RoadmapController.*/ AND \"action\" =~ /(show)/) OR (\"action\" =~ /Groups::EpicsController.*/ AND \"action\" =~ /(index)/)) AND $timeFilter GROUP BY \"action\"",
     "select": [
      [
       { "params": [ "duration_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "action",
       "operator": "=",
       "value": "Groups::EpicsController#create.json"
      },
      {
       "condition": "OR",
       "key": "action",
       "operator": "=",
       "value": "Groups::EpicIssuesController#index.json"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rails_transaction_timings_per_action",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "Groups::EpicI" }
     ]
    }
   ]
  },
  {
   "title": "Creating and Destroying Epics",
   "type": "graph",
   "description": "Mean request durations for actions involved in creating and destroying an epic",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_action",
     "groupBy": [
      { "params": [ "action" ], "type": "tag" }
     ],
     "measurement": "rails_transaction_timings_per_action",
     "query": "SELECT \"duration_mean\" FROM \"downsampled\".\"rails_transaction_timings_per_action\" WHERE ((\"action\" =~ /Groups::EpicsController.*/ AND \"action\" =~ /(create|destroy)/)) AND $timeFilter GROUP BY \"action\"",
     "select": [
      [
       { "params": [ "duration_mean" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "action",
       "operator": "=",
       "value": "Groups::EpicsController#create.json"
      },
      {
       "condition": "OR",
       "key": "action",
       "operator": "=",
       "value": "Groups::EpicIssuesController#index.json"
      }
     ]
    }
   ]
  },
  { "title": "Epics API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Epics API Response Durations",
   "type": "graph",
   "description": "Mean request duration through the API for Epics",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Throughput" }
   ],
   "targets": [
    {
     "alias": "$tag_action",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grape_git_timings_per_action",
     "query": "SELECT count FROM \"downsampled\".\"grape_transaction_counts_per_action\" WHERE \"action\" =~ /Grape#.*epics.*/  AND $timeFilter GROUP BY \"action\"",
     "select": [
      [
       { "params": [ "duration_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "Grape#GET /api/" }
     ]
    }
   ]
  },
  {
   "title": "Other Useful Epics Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "EpicsController Mean Response Time",
     "type": "graph",
     "description": "Mean request duration by action for the Groups::EpicsController",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_action",
       "groupBy": [
        { "params": [ "action" ], "type": "tag" }
       ],
       "measurement": "rails_transaction_timings_per_action",
       "query": "SELECT \"duration_mean\" FROM \"downsampled\".\"rails_transaction_timings_per_action\" WHERE \"action\" =~ /Groups::EpicsController.*/ AND $timeFilter GROUP BY \"action\"",
       "select": [
        [
         { "params": [ "duration_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        {
         "key": "action",
         "operator": "=",
         "value": "Groups::EpicsController#create.json"
        },
        {
         "condition": "OR",
         "key": "action",
         "operator": "=",
         "value": "Groups::EpicIssuesController#index.json"
        }
       ]
      }
     ]
    },
    {
     "title": "Epic Issues and Links Controllers Response Times",
     "type": "graph",
     "description": "Mean request duration by action for the Groups::EpicIssuesController and Groups::EpicLinksController",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_action",
       "groupBy": [
        { "params": [ "action" ], "type": "tag" }
       ],
       "measurement": "rails_transaction_timings_per_action",
       "query": "SELECT \"duration_mean\" FROM \"downsampled\".\"rails_transaction_timings_per_action\" WHERE \"action\" =~ /Groups::EpicIssues.*/ OR \"action\" =~ /Groups::EpicLinks.*/ AND $timeFilter GROUP BY \"action\"",
       "select": [
        [
         { "params": [ "duration_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        {
         "key": "action",
         "operator": "=",
         "value": "Groups::EpicsController#create.json"
        },
        {
         "condition": "OR",
         "key": "action",
         "operator": "=",
         "value": "Groups::EpicIssuesController#index.json"
        }
       ]
      }
     ]
    },
    {
     "title": "Epics::NotesController Response Times",
     "type": "graph",
     "description": "Mean request duration by action for the Groups::Epics::NotesController",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_action",
       "groupBy": [
        { "params": [ "action" ], "type": "tag" }
       ],
       "measurement": "rails_transaction_timings_per_action",
       "query": "SELECT \"duration_mean\" FROM \"downsampled\".\"rails_transaction_timings_per_action\" WHERE \"action\" =~ /Groups::Epics::NotesController.*/ AND $timeFilter GROUP BY \"action\"",
       "select": [
        [
         { "params": [ "duration_mean" ], "type": "field" }
        ]
       ],
       "tags": [
        {
         "key": "action",
         "operator": "=",
         "value": "Groups::EpicsController#create.json"
        },
        {
         "condition": "OR",
         "key": "action",
         "operator": "=",
         "value": "Groups::EpicIssuesController#index.json"
        }
       ]
      }
     ]
    }
   ]
  }
 ]
}