{
 "title": "Kamil - Puma vs Unicorn",
 "description": "works only for dev.gitlab.org, due to specific dev.gitlab.org data source",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "ops,pre" },
   { "name": "node", "label": "Host", "query": "label_values(up,fqdn)" },
   { "name": "promethus", "query": "prometheus" },
   { "name": "prometheus_app", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(instance:node_cpu_utilization:ratio{fqdn=\"$node\"}[$__interval])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "cs p/s" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches{fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Context switches",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(node_context_switches_total{fqdn=\"$node\"}[$__interval])",
     "legendFormat": "Context switches"
    }
   ]
  },
  {
   "title": "Load per CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_load1{fqdn=\"$node\"}[$__interval]) / instance:node_cpus:count",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{fqdn=\"$node\"} - node_memory_MemAvailable_bytes{fqdn=\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{fqdn=\"$node\"} - node_memory_SwapFree_bytes{fqdn=\"$node\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_MemTotal_bytes{fqdn=\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{fqdn=\"$node\"}",
     "legendFormat": "Swap Total"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{fqdn=~\"$node\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "current connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC wasted memory",
   "type": "graph",
   "description": "% of requests processed in less than 50ms",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ruby_gc_stat_heap_allocatable_pages*16384) by (job)",
     "legendFormat": "Malloc freeable pages: {{job}}"
    },
    {
     "expr": "(sum(ruby_gc_stat_heap_free_slots)-sum(ruby_gc_stat_heap_tomb_pages*409))/sum(ruby_gc_stat_heap_available_slots)",
     "legendFormat": "GC memory fragmentation: {{job}}"
    }
   ]
  },
  {
   "title": "Ruby Memory",
   "type": "graph",
   "description": "The RSS as visible by system",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ruby_memory_bytes) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Puma Workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(puma_max_threads)", "legendFormat": "Max Threads" },
    { "expr": "sum(puma_idle_threads)", "legendFormat": "Idle Threads" },
    { "expr": "sum(puma_active_connections)", "legendFormat": "Active Requests" },
    { "expr": "sum(puma_queued_connections)", "legendFormat": "Queued Requests" },
    {
     "expr": "sum(irate(puma_killer_terminations_total[$__interval]))",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "GC apdex",
   "type": "graph",
   "description": "% of cycles processed in less than 50ms",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " sum(rate(ruby_gc_duration_seconds_bucket{le=\"0.05\"}[5m])) by (job)\n/\n  sum(rate(ruby_gc_duration_seconds_count[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC cycles",
   "type": "graph",
   "description": "GC operations per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ruby_gc_stat_count[$__interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC data",
   "type": "graph",
   "description": "% of requests processed in less than 50ms",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ruby_gc_stat_heap_available_slots*40) by (job)",
     "legendFormat": "GC owned: {{job}}"
    },
    {
     "expr": "sum(ruby_gc_stat_heap_free_slots*40) by (job)",
     "legendFormat": "GC free: {{job}}"
    },
    {
     "expr": "sum(ruby_gc_stat_heap_marked_slots*40) by (job)",
     "legendFormat": "GC old memory: {{job}}"
    },
    {
     "expr": "sum((ruby_gc_stat_heap_allocatable_pages+ruby_gc_stat_heap_allocated_pages)*16384) by (job)",
     "legendFormat": "Allocated pages: {{job}}"
    },
    {
     "expr": "sum(ruby_gc_stat_heap_tomb_pages*16384) by (job)",
     "legendFormat": "Full free pages: {{job}}"
    }
   ]
  },
  {
   "title": "Puma Apdex",
   "type": "graph",
   "description": "This represent Apdex score of queueing requests on Puma/Unicorn: the % of requests that are queued for less than 50ms\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_rails_queue_duration_seconds_bucket{le=\"0.05\"}[5m])) by (job)/sum(rate(gitlab_rails_queue_duration_seconds_count[5m])) by (job)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Queueing apdex {{job}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}