{
 "title": "Kamil: CI decomposition results",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "POST /api/jobs/request (mean ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{controller=\"Grape\",action=\"POST /api/jobs/request\",env=\"gprd\"}[10m]))",
     "legendFormat": "current_week"
    },
    {
     "expr": "sum(avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{controller=\"Grape\",action=\"POST /api/jobs/request\",env=\"gprd\"}[10m] offset 1w))",
     "legendFormat": "last_week"
    }
   ]
  },
  {
   "title": "GraphQL Controller (mean ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{controller=\"GraphqlController\",env=\"gprd\"}[10m]))",
     "legendFormat": "current_week"
    },
    {
     "expr": "sum(avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{controller=\"GraphqlController\",env=\"gprd\"}[10m] offset 1w))",
     "legendFormat": "last_week"
    }
   ]
  },
  {
   "title": "PUT /api/jobs/:id (mean ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{controller=\"Grape\",action=\"PUT /api/jobs/:id\",env=\"gprd\"}[10m]))",
     "legendFormat": "current_week"
    },
    {
     "expr": "sum(avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{controller=\"Grape\",action=\"PUT /api/jobs/:id\",env=\"gprd\"}[10m] offset 1w))",
     "legendFormat": "last_week"
    }
   ]
  },
  {
   "title": "Merge Requests Controller (mean ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{controller=\"Projects::MergeRequestsController\",env=\"gprd\"}[10m]))",
     "legendFormat": "current_week"
    },
    {
     "expr": "sum(avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{controller=\"Projects::MergeRequestsController\",env=\"gprd\"}[10m] offset 1w))",
     "legendFormat": "last_week"
    }
   ]
  }
 ]
}