{
 "title": "kas: Redis client metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4435758715 at Thu Jun  8 07:14:29 UTC 2023",
 "tags": [
  "managed",
  "kas",
  "kas"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "Connection found in pool",
   "type": "graph",
   "description": "Number of times a connection was found in the pool",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "times" }
   ],
   "targets": [
    {
     "expr": "sum (increase(redis_pool_hit_total{env=\"$environment\", stage=\"$stage\", app=\"kas\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Connection not found in pool",
   "type": "graph",
   "description": "Number of times a connection was not found in the pool",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "times" }
   ],
   "targets": [
    {
     "expr": "sum (increase(redis_pool_miss_total{env=\"$environment\", stage=\"$stage\", app=\"kas\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Timeout retrieving connection from pool",
   "type": "graph",
   "description": "Number of times a timeout occurred when looking for a connection in the pool",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "times" }
   ],
   "targets": [
    {
     "expr": "sum (increase(redis_pool_timeout_total{env=\"$environment\", stage=\"$stage\", app=\"kas\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Number of idle connections in pool",
   "type": "graph",
   "description": "Current number of idle connections in the pool",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "sum (redis_pool_conn_idle_current{env=\"$environment\", stage=\"$stage\", app=\"kas\"})\n"
    }
   ]
  },
  {
   "title": "Removed stale connections",
   "type": "graph",
   "description": "Number of times a connection was removed from the pool because it was stale",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "connections" }
   ],
   "targets": [
    {
     "expr": "sum (increase(redis_pool_conn_stale_total{env=\"$environment\", stage=\"$stage\", app=\"kas\"}[$__rate_interval]))\n"
    }
   ]
  }
 ]
}