{
 "title": "kas: Miscellaneous metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4923058058 at Tue Aug 22 15:40:01 UTC 2023",
 "tags": [
  "managed",
  "kas",
  "kas"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "OK gRPC calls/second",
   "type": "graph",
   "description": "OK gRPC calls",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method) (\n  rate(grpc_server_handled_total{env=\"$environment\",stage=\"$stage\",type=\"kas\", grpc_code=\"OK\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Not OK gRPC calls/second",
   "type": "graph",
   "description": "Not OK gRPC calls",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method, grpc_code) (\n  rate(grpc_server_handled_total{env=\"$environment\",stage=\"$stage\",type=\"kas\", grpc_code!=\"OK\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{grpc_service}}/{{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Agent connections rate limit exceeded",
   "type": "graph",
   "description": "The total number of times configured rate limit of new agent connections was exceeded",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "times" }
   ],
   "targets": [
    {
     "expr": "sum (increase(agent_server_rate_exceeded_total{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]))\n"
    }
   ]
  }
 ]
}