{
 "title": "kas: GitOps metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5175551080 at Wed Sep 27 12:34:09 UTC 2023",
 "tags": [
  "managed",
  "kas",
  "kas"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "Flux: Git push notifications sent",
   "type": "graph",
   "description": "The total number of sent Git Push notifications to agentks in Flux module",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum (increase(flux_git_push_notifications_total{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Flux: Git push notifications dropped",
   "type": "graph",
   "description": "The total number of dropped Git push notifications in Flux module",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum (increase(flux_dropped_git_push_notifications_total{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Git push notifications RPCs",
   "type": "graph",
   "description": "Git push gRPC notifications",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_code) (\n  rate(grpc_server_handled_total{env=\"$environment\",stage=\"$stage\",type=\"kas\",\n    grpc_service=\"gitlab.agent.notifications.rpc.Notifications\",\n    grpc_method=\"GitPushEvent\"\n  }[$__rate_interval])\n)\n",
     "legendFormat": "gitlab.agent.notifications.rpc.Notifications/GitPushEvent {{grpc_code}}"
    }
   ]
  },
  {
   "title": "OK gRPC calls/second",
   "type": "graph",
   "description": "OK gRPC calls related to GitOps",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method) (\n  rate(grpc_server_handled_total{env=\"$environment\",stage=\"$stage\",type=\"kas\", grpc_code=\"OK\",\n    grpc_service=~\"gitlab.agent.gitops.rpc.Gitops|gitlab.agent.flux.rpc.GitLabFlux\"\n  }[$__rate_interval])\n)\n",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Not OK gRPC calls/second",
   "type": "graph",
   "description": "Not OK gRPC calls related to GitOps",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method, grpc_code) (\n  rate(grpc_server_handled_total{env=\"$environment\",stage=\"$stage\",type=\"kas\", grpc_code!=\"OK\",\n    grpc_service=~\"gitlab.agent.gitops.rpc.Gitops|gitlab.agent.flux.rpc.GitLabFlux\"\n  }[$__rate_interval])\n)\n",
     "legendFormat": "{{grpc_service}}/{{grpc_method}} {{grpc_code}}"
    }
   ]
  }
 ]
}