{
 "title": "kas: CI tunnel",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7397849007 at Mon Jul 22 14:27:56 UTC 2024",
 "tags": [
  "managed",
  "kas",
  "kas"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "Routing latency (success)",
   "type": "heatmap",
   "description": "Time it takes kas to find a suitable reverse tunnel from an agent",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (rate(tunnel_routing_duration_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\", status=\"success\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Routing latency (request aborted)",
   "type": "heatmap",
   "description": "Time it takes kas to find a suitable reverse tunnel from an agent",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (rate(tunnel_routing_duration_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\", status=\"aborted\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Routing request timed out for recently connected agents",
   "type": "graph",
   "description": "CI tunnel request routing took longer than 20s for agents that have recently connected (within the last 15 minutes)",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum (increase(tunnel_routing_timeout_connected_recently_total{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Routing request timed out for disconnected agents",
   "type": "graph",
   "description": "CI tunnel request routing took longer than 20s for agents that are disconnected",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum (increase(tunnel_routing_timeout_not_connected_recently_total{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "OK gRPC calls/second",
   "type": "graph",
   "description": "OK gRPC calls related to CI tunnel",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method) (\n  rate(grpc_server_handled_total{env=\"$environment\",stage=\"$stage\",type=\"kas\", grpc_code=\"OK\",\n    grpc_service=~\"gitlab.agent.reverse_tunnel.rpc.ReverseTunnel|gitlab.agent.kubernetes_api.rpc.KubernetesApi\"\n  }[$__rate_interval])\n)\n",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Not OK gRPC calls/second",
   "type": "graph",
   "description": "Not OK gRPC calls related to CI tunnel",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method, grpc_code) (\n  rate(grpc_server_handled_total{env=\"$environment\",stage=\"$stage\",type=\"kas\", grpc_code!=\"OK\",\n    grpc_service=~\"gitlab.agent.reverse_tunnel.rpc.ReverseTunnel|gitlab.agent.kubernetes_api.rpc.KubernetesApi\"\n  }[$__rate_interval])\n)\n",
     "legendFormat": "{{grpc_service}}/{{grpc_method}} {{grpc_code}}"
    }
   ]
  }
 ]
}