{
 "title": "kas: Redis metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6651129169 at Wed Apr 17 16:07:20 UTC 2024",
 "tags": [
  "managed",
  "kas",
  "kas"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  { "title": "Rueidis metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dial Latency",
   "type": "graph",
   "description": "Rueidis dial latency in seconds",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1000 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (\nrate(rueidis_dial_latency_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]))\n)\n",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (\nrate(rueidis_dial_latency_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]))\n)\n",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (\nrate(rueidis_dial_latency_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]))\n)\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (\nrate(rueidis_dial_latency_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]))\n)\n",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Number of connections",
   "type": "graph",
   "description": "Rueidis number of connections",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rueidis_dial_conns{env=\"$environment\",stage=\"$stage\",type=\"kas\"}\n)\n"
    }
   ]
  },
  {
   "title": "Total dial attemps and dial successes",
   "type": "graph",
   "description": "Rueidis total number of dial attempts and dial successes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1010 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  increase(rueidis_dial_attempt_total{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval])\n)\n",
     "legendFormat": "Attempts"
    },
    {
     "expr": "sum (\n  increase(rueidis_dial_success_total{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval])\n)\n",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Total dial failures",
   "type": "graph",
   "description": "Rueidis total number of dial failures, calculated by `attempts - success`.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1010 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  increase(rueidis_dial_attempt_total{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval])\n)\n-\nsum (\n  increase(rueidis_dial_success_total{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  { "title": "KAS Redis client metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Number of tunnels_by_agent_id agent hash keys GC'ed",
   "type": "graph",
   "description": "`tunnels_by_agent_id` - Expiring Hash: number of deleted keys during GC and ScanAndGC",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum ( increase(redis_expiring_hash_api_scan_and_gc_deleted_keys_count_total{expiring_hash_name=\"tunnels_by_agent_id\", env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]) )\n",
     "legendFormat": "ScanAndGC"
    },
    {
     "expr": "sum ( increase(redis_expiring_hash_gc_deleted_keys_count_total{expiring_hash_name=\"tunnels_by_agent_id\", env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]) )\n",
     "legendFormat": "GC"
    }
   ]
  },
  {
   "title": "Number of connected agents agent hash keys GC'ed",
   "type": "graph",
   "description": "`connected_agents` - Expiring Hash: number of deleted keys during GC and ScanAndGC",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3000 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum ( increase(redis_expiring_hash_api_scan_and_gc_deleted_keys_count_total{expiring_hash_name=\"connected_agents\", env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]) )\n",
     "legendFormat": "ScanAndGC"
    },
    {
     "expr": "sum ( increase(redis_expiring_hash_gc_deleted_keys_count_total{expiring_hash_name=\"connected_agents\", env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]) )\n",
     "legendFormat": "GC"
    }
   ]
  },
  {
   "title": "Number of connections by agent id agent hash keys GC'ed",
   "type": "graph",
   "description": "`connections_by_agent_id` - Expiring Hash: number of deleted keys during GC and ScanAndGC",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3010 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum ( increase(redis_expiring_hash_api_scan_and_gc_deleted_keys_count_total{expiring_hash_name=\"connections_by_agent_id\", env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]) )\n",
     "legendFormat": "ScanAndGC"
    },
    {
     "expr": "sum ( increase(redis_expiring_hash_gc_deleted_keys_count_total{expiring_hash_name=\"connections_by_agent_id\", env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]) )\n",
     "legendFormat": "GC"
    }
   ]
  },
  {
   "title": "Number of connections by project id agent hash keys GC'ed",
   "type": "graph",
   "description": "`connections_by_project_id` - Expiring Hash: number of deleted keys during GC and ScanAndGC",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3010 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum ( increase(redis_expiring_hash_api_scan_and_gc_deleted_keys_count_total{expiring_hash_name=\"connections_by_project_id\", env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]) )\n",
     "legendFormat": "ScanAndGC"
    },
    {
     "expr": "sum ( increase(redis_expiring_hash_gc_deleted_keys_count_total{expiring_hash_name=\"connections_by_project_id\", env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]) )\n",
     "legendFormat": "GC"
    }
   ]
  }
 ]
}