{
 "title": "kas: Miscellaneous metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5688215662 at Tue Dec  5 22:08:27 UTC 2023",
 "tags": [
  "managed",
  "kas",
  "kas"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  { "title": "Rate limiter metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate limiter delay (allowed, agent_connection)",
   "type": "heatmap",
   "description": "Rate limiter delay for an allowed request",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1000 },
   "targets": [
    {
     "expr": "sum by (le) (\n            rate(limiter_block_duration_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\", allowed=\"true\", limiter_name=\"agent_connection\"}[$__rate_interval])\n          )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate limiter delay (denied, agent_connection)",
   "type": "heatmap",
   "description": "Rate limiter delay for a denied request",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1000 },
   "targets": [
    {
     "expr": "sum by (le) (\n            rate(limiter_block_duration_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\", allowed=\"false\", limiter_name=\"agent_connection\"}[$__rate_interval])\n          )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate limiter delay (allowed, gitaly_client_global)",
   "type": "heatmap",
   "description": "Rate limiter delay for an allowed request",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1010 },
   "targets": [
    {
     "expr": "sum by (le) (\n            rate(limiter_block_duration_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\", allowed=\"true\", limiter_name=\"gitaly_client_global\"}[$__rate_interval])\n          )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate limiter delay (denied, gitaly_client_global)",
   "type": "heatmap",
   "description": "Rate limiter delay for a denied request",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1010 },
   "targets": [
    {
     "expr": "sum by (le) (\n            rate(limiter_block_duration_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\", allowed=\"false\", limiter_name=\"gitaly_client_global\"}[$__rate_interval])\n          )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate limiter delay (allowed, gitlab_client)",
   "type": "heatmap",
   "description": "Rate limiter delay for an allowed request",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1020 },
   "targets": [
    {
     "expr": "sum by (le) (\n            rate(limiter_block_duration_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\", allowed=\"true\", limiter_name=\"gitlab_client\"}[$__rate_interval])\n          )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate limiter delay (denied, gitlab_client)",
   "type": "heatmap",
   "description": "Rate limiter delay for a denied request",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1020 },
   "targets": [
    {
     "expr": "sum by (le) (\n            rate(limiter_block_duration_seconds_bucket{env=\"$environment\",stage=\"$stage\",type=\"kas\", allowed=\"false\", limiter_name=\"gitlab_client\"}[$__rate_interval])\n          )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "gRPC metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "OK gRPC calls/second",
   "type": "graph",
   "description": "OK gRPC calls",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3000 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method) (\n  rate(grpc_server_handled_total{env=\"$environment\",stage=\"$stage\",type=\"kas\", grpc_code=\"OK\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Not OK gRPC calls/second",
   "type": "graph",
   "description": "Not OK gRPC calls",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3000 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method, grpc_code) (\n  rate(grpc_server_handled_total{env=\"$environment\",stage=\"$stage\",type=\"kas\", grpc_code!=\"OK\"}[$__rate_interval])\n)\n",
     "legendFormat": "{{grpc_service}}/{{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 } },
  {
   "title": "CPU throttling",
   "type": "graph",
   "description": "CPU throttling of kas",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5000 },
   "yaxes": [
    { "format": "short", "label": "time" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_cfs_throttled_seconds_total{env=\"$environment\",stage=\"$stage\",type=\"kas\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Go GC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5000 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "1000*go_gc_duration_seconds{env=\"$environment\",stage=\"$stage\",type=\"kas\",quantile=\"1\"}\n"
    }
   ]
  },
  {
   "title": "Go goroutines",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5010 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{env=\"$environment\",stage=\"$stage\",type=\"kas\"}\n"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6000 } },
  {
   "title": "Running version",
   "type": "graph",
   "description": "Running version of kas",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7000 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "count by (version, stage) (gitlab_build_info{env=\"$environment\",type=\"kas\"})\n"
    }
   ]
  }
 ]
}