{
 "title": "Latency comparisons",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "quantile", "query": "0.5,0.6,0.9,0.95,0.99" }
  ]
 },
 "panels": [
  {
   "title": "Workhorse 200",
   "type": "graph",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by (le) (rate(gitlab_workhorse_http_request_duration_seconds_bucket{env=\"gprd\",monitor=\"app\",instance=~\"web-0.*\",job=\"gitlab-workhorse-web\",route=\"\",code=\"200\"}[$__interval])))",
     "legendFormat": "web-0*"
    },
    {
     "expr": "histogram_quantile($quantile, sum by (le) (rate(gitlab_workhorse_http_request_duration_seconds_bucket{env=\"gprd\",monitor=\"app\",instance=~\"web-1.*\",job=\"gitlab-workhorse-web\",route=\"\",code=\"200\"}[$__interval])))",
     "legendFormat": "web-1*"
    }
   ]
  },
  {
   "title": "Rails HTTP 200",
   "type": "graph",
   "gridPos": { "h": 18, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by (le) (rate(gitlab_transaction_duration_seconds_bucket{env=\"gprd\",instance=~\"web-0.*\",job=\"gitlab-rails\"}[$__interval])))",
     "legendFormat": "web-0*"
    },
    {
     "expr": "histogram_quantile($quantile, sum by (le) (rate(gitlab_transaction_duration_seconds_bucket{env=\"gprd\",instance=~\"web-1.*\",job=\"gitlab-rails\"}[$__interval])))",
     "legendFormat": "web-1*"
    }
   ]
  },
  {
   "title": "Rails HTTP",
   "type": "graph",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum by (le) (rate(http_request_duration_seconds_bucket{env=\"gprd\",instance=~\"web-0.*\",job=\"gitlab-rails\",status=\"200\"}[2m])))",
     "legendFormat": "web-0*"
    },
    {
     "expr": "histogram_quantile($quantile, sum by (le) (rate(http_request_duration_seconds_bucket{env=\"gprd\",instance=~\"web-1.*\",job=\"gitlab-rails\",status=\"200\"}[2m])))",
     "legendFormat": "web-1*"
    }
   ]
  }
 ]
}