{
 "title": "Logging",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg,ops,dr,pre" }
  ]
 },
 "panels": [
  {
   "title": "Fluentd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fluentd Output Records by type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_num_records_total{env=\"$environment\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Fluentd Output Records by tag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_num_records_total{env=\"$environment\"}[$__rate_interval])) by (tag)",
     "legendFormat": "{{ tag }}"
    }
   ]
  },
  {
   "title": "Fluentd Output Records by type and tag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_num_records_total{env=\"$environment\"}[$__rate_interval])) by (type,tag)",
     "legendFormat": "{{ type }}:{{ tag }}"
    }
   ]
  },
  {
   "title": "StackDriver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "StackDriver Global Ingested Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg_over_time(stackdriver_global_logging_googleapis_com_billing_bytes_ingested{env=\"$environment\"}[$__rate_interval]) / 60",
     "legendFormat": "{{ resource_type }}"
    }
   ]
  },
  {
   "title": "StackDriver Log Entry Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(stackdriver_gce_instance_logging_googleapis_com_log_entry_count{env=\"$environment\"}[$__rate_interval])) by (log)",
     "legendFormat": "{{ log }}"
    }
   ]
  },
  {
   "title": "StackDriver Dropped Log Entry Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(stackdriver_gce_instance_logging_googleapis_com_dropped_log_entry_count{env=\"$environment\"}[$__rate_interval])) by (log)",
     "legendFormat": "{{ log }}"
    }
   ]
  },
  {
   "title": "Fluentd SD plugin dropped messages per minute",
   "type": "timeseries",
   "description": "Using the mtail metric, this  tracks the number of dropped messages by the fluentd stackdriver plugin",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(td_agent_dropped_log_messages_total{env=\"$environment\"}[$__rate_interval]) * 60 != 0) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fluentd SD plugin dropped messages per minute",
   "type": "timeseries",
   "description": "Using the mtail metric, this  tracks the number of dropped messages by the fluentd stackdriver plugin",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(td_agent_dropped_log_messages_total{env=\"$environment\"}[$__rate_interval]) * 60 != 0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PubSub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PubSub Topics Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "stackdriver_pubsub_topic_pubsub_googleapis_com_topic_byte_cost{env=\"$environment\"} / 60",
     "legendFormat": "{{topic_id}}"
    }
   ]
  },
  {
   "title": "PubSub Subscriptions Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_byte_cost{env=\"$environment\"} / 60) by (subscription_id)",
     "legendFormat": "{{subscription_id}}"
    }
   ]
  },
  {
   "title": "PubSub Topic Message Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "stackdriver_pubsub_topic_pubsub_googleapis_com_topic_send_message_operation_count{env=\"$environment\"} / 60",
     "legendFormat": "{{topic_id}} - {{env}}"
    }
   ]
  },
  {
   "title": "Backlog Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_backlog_bytes{env=\"$environment\"}) by (subscription_id)",
     "legendFormat": "{{subscription_id}}"
    }
   ]
  },
  {
   "title": "Unacked message build-up rate",
   "type": "timeseries",
   "description": "Rate of change of unacked messages. If this is flat and positive, it's likely that all new messages are being dropped.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (topic_id) (deriv(stackdriver_pubsub_topic_pubsub_googleapis_com_topic_num_unacked_messages_by_region[5m]))",
     "legendFormat": "{{topic_id}}"
    }
   ]
  },
  {
   "title": "UnAcked Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(stackdriver_pubsub_topic_pubsub_googleapis_com_topic_num_unacked_messages_by_region{env=\"$environment\"}) by (topic_id)",
     "legendFormat": "{{topic_id}}"
    }
   ]
  },
  {
   "title": "Oldest  UnAcked Message",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(stackdriver_pubsub_subscription_pubsub_googleapis_com_subscription_oldest_unacked_message_age{env=\"$environment\"}) by (subscription_id)",
     "legendFormat": "{{subscription_id}}"
    }
   ]
  }
 ]
}