{
 "title": "Loki Trial Web Overview",
 "tags": [ "unmanaged" ],
 "time": { "from": "2023-09-06T14:00:00.000Z", "to": "2023-09-06T14:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "environment", "query": { "query": "label_values(environment)" } },
   { "name": "stage", "query": { "query": "label_values(stage)" } },
   {
    "name": "job",
    "label": "job",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Web Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "rails_request SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "rails_request apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"web\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"web\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "rails_request apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\",type=\"web\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "rails_request SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rails_request error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"web\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"web\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rails_request error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"rails_request\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\",type=\"web\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Slow routes over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk (6, sum by (route) (count_over_time({job=\"$job\", env=\"$environment\"} | json | __error__!=\"JSONParserErr\" | cluster=\"gprd-us-east1-d\" | duration_s > 2 [5m])))"
    }
   ]
  },
  {
   "title": "Slow controllers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk (6, sum by (controller) (count_over_time({job=\"$job\", env=\"$environment\"} | json | __error__!=\"JSONParserErr\" | cluster=\"gprd-us-east1-d\" | duration_s > 2 [5m])))"
    }
   ]
  },
  { "title": "Slow routes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Top 6 by slow Route duration > 5s",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (topk (6, sum by (route) (count_over_time({job=\"$job\", env=\"$environment\"} | json | __error__!=\"JSONParserErr\" | route=~\".+\" | cluster=\"gprd-us-east1-d\" | duration_s > 2 [5m]))))"
    }
   ]
  },
  {
   "title": "User Requests with >4s DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (username) (count_over_time({job=\"$job\", env=\"$environment\"} | json | __error__!=\"JSONParserErr\" | route=~\".+\" | cluster=\"gprd-us-east1-d\" | db_duration_s > 4 [5m]))"
    }
   ]
  },
  {
   "title": "Slow Controllers (duration > 5s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "count of controllers with >5s duration",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(6, sum by (controller) (count_over_time({job=\"$job\", env=\"$environment\"} | json | __error__!=\"JSONParserErr\" | cluster=\"gprd-us-east1-d\" | controller=~\".+\" | duration_s > 5 [5m] ))))"
    }
   ]
  },
  {
   "title": "Top 10 Slow controllers over 5s duration",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (6, sum by (controller) (count_over_time({job=\"$job\", env=\"$environment\"} | json | __error__!=\"JSONParserErr\" | cluster=\"gprd-us-east1-d\" | duration_s > 5 [5m])))"
    }
   ]
  },
  { "title": "Raw Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{job=\"gitlab/webservice\", env=\"$environment\"} | json | subcomponent=\"production_json\" | duration_s > 5"
    }
   ]
  }
 ]
}