{
 "title": "Loki Trial - Support Investigations",
 "tags": [ "unmanaged" ],
 "time": { "from": "2023-09-07T12:00:00.000Z", "to": "2023-09-07T12:29:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {}
   },
   { "name": "ProjectPath" },
   { "name": "Correlation_id" }
  ]
 },
 "panels": [
  { "title": "Filtered Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (path) (count_over_time({ app=\"$app\", env=\"gprd\"} | json |~ \"$ProjectPath\" [1m] ))"
    }
   ]
  },
  {
   "title": "Filtered by path",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{ app=\"$app\", env=\"gprd\" } |~ \"$ProjectPath\" "
    }
   ]
  },
  {
   "title": "Raw logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw logs (filer by Correlation_id)",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "{app=\"$app\"} | json | correlation_id = \"$Correlation_id\""
      }
     ]
    }
   ]
  }
 ]
}