{
 "title": "Loose Foreign Keys",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Environment",
    "label": "Environment",
    "query": "Production : gprd, Staging : gstg"
   }
  ]
 },
 "panels": [
  {
   "title": "LooseForeignKeys::CleanupWorker runtime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_completion_seconds_sum{env=\"$Environment\",worker=\"LooseForeignKeys::CleanupWorker\"}[1m]))",
     "legendFormat": "Total runtime"
    },
    {
     "expr": "sum(rate(sidekiq_jobs_db_seconds_sum{env=\"$Environment\",worker=\"LooseForeignKeys::CleanupWorker\"}[1m]))",
     "legendFormat": "DB runtime"
    }
   ]
  },
  {
   "title": "Processed deleted parent rows",
   "type": "timeseries",
   "description": "The rate at which the system processes rows in the loose_foreign_keys_deleted_records database table. Processing one row means that the system deleted all children associations and updated the row status to processed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(loose_foreign_key_processed_deleted_records{env=\"$Environment\"}[1m])) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Deleted children rows",
   "type": "timeseries",
   "description": "The number of deleted children rows.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(loose_foreign_key_deletions{env=\"$Environment\"}[1m])) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Child row updates",
   "type": "timeseries",
   "description": "The rate at which the children rows are being updated. This usually means that the foreign key column is nullified.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(loose_foreign_key_updates{env=\"$Environment\"}[1m])) by (table)",
     "legendFormat": "{{table}}"
    }
   ]
  }
 ]
}