{
 "title": "Low urgency CPU bound",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Low urgency CPU bound CPU usage vs requests/limits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"gitlab\",env=\"gprd\",pod=~\"gitlab-sidekiq-low-urgency-cpu-bound.*\", container_name!=\"POD\"}[5m])) by (pod_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"gitlab\",env=\"gprd\",pod=~\"gitlab-sidekiq-low-urgency-cpu-bound.*\", container_name!=\"POD\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"gitlab\",env=\"gprd\",pod=~\"gitlab-sidekiq-low-urgency-cpu-bound.*\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of low urgency pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"gitlab\",env=\"gprd\",pod=~\"gitlab-sidekiq-low-urgency-cpu-bound.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low urgency CPU bound shard saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "clamp_min(\n    clamp_max(\n      max(\n        max_over_time(gitlab_component_saturation:ratio{env=\"gprd\",stage=\"main\",type=\"sidekiq\", component=\"ruby_thread_contention\",shard=~\"low-urgency-cpu-bound\"}[1h])\n    )\n  ,1)\n,0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}