{
 "title": "mailroom: Application Info",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/357620951 at Thu Nov 21 15:30:22 UTC 2019",
 "tags": [
  "managed",
  "mailroom",
  "mailroom"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "namespace", "query": "gitlab," },
   { "name": "Deployment", "query": "gitlab-mailroom," }
  ]
 },
 "panels": [
  { "title": "Stackdriver Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log messages with severity ERROR",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"ERROR\", pod_id=~\"^$Deployment.*\", cluster_name=\"$cluster\", namespace_id=\"$namespace\"}) / 60",
     "legendFormat": "ERROR msgs per second"
    }
   ]
  },
  {
   "title": "Log messages with severity INFO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"INFO\", pod_id=~\"^$Deployment.*\", cluster_name=\"$cluster\", namespace_id=\"$namespace\"}) / 60",
     "legendFormat": "INFO msgs per second"
    }
   ]
  },
  { "title": "Mailroom Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Unread Emails",
   "type": "graph",
   "description": "Number of unread messages",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(imap_nb_unread_messages_in_mailbox{environment=~\"$environment\"})",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}