{
 "title": "mailroom: Kube Containers Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4359303070 at Fri May 26 15:11:54 UTC 2023",
 "tags": [
  "managed",
  "mailroom",
  "mailroom",
  "type:mailroom",
  "kube",
  "kube detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  { "title": "mailroom deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "mailroom container/mailroom deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 mailroom Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 mailroom Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 mailroom Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 mailroom Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 mailroom Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 mailroom Container CPU"
    }
   ]
  },
  {
   "title": "mailroom container/mailroom deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n }\n)\n",
     "legendFormat": "p99 mailroom Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n }\n)\n",
     "legendFormat": "p95 mailroom Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n }\n)\n",
     "legendFormat": "p75 mailroom Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n }\n)\n",
     "legendFormat": "p50 mailroom Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n }\n)\n",
     "legendFormat": "p25 mailroom Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n }\n)\n",
     "legendFormat": "p10 mailroom Container Memory"
    }
   ]
  },
  {
   "title": "mailroom container/mailroom deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "mailroom container/mailroom deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"mailroom\",deployment=\"mailroom\",env=\"$environment\",environment=\"$environment\",type=\"mailroom\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}