{
 "title": "marquee: Customer Dashboard",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4790767134 at Wed Aug  2 14:25:57 UTC 2023",
 "tags": [
  "managed",
  "marquee"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "customer_id", "label": "customer_id" }
  ]
 },
 "panels": [
  {
   "title": "Web Latency (logn scale)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "marquee_customers_request_duration_seconds{env=\"$environment\", salesforce_url=\"https://gitlab.my.salesforce.com/${customer_id}\"}\n",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Web Requests / Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(marquee_customers_requests_total{env=\"$environment\", salesforce_url=\"https://gitlab.my.salesforce.com/${customer_id}\"}[$__interval])\n",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Web Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(marquee_customers_requests_server_errors_total{env=\"$environment\", salesforce_url=\"https://gitlab.my.salesforce.com/${customer_id}\"}[$__interval])\n",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(rate(marquee_customers_requests_server_errors_total{env=\"$environment\", salesforce_url=\"https://gitlab.my.salesforce.com/${customer_id}\"}[$__interval])\n/\nrate(marquee_customers_requests_total{env=\"$environment\", salesforce_url=\"https://gitlab.my.salesforce.com/${customer_id}\"}[$__interval])\n,1),0)\n",
     "legendFormat": "Error Rate (%)"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}