{
 "title": "memcached",
 "description": "Prometheus dashboard for memcached servers",
 "tags": [
  "prometheus",
  "memcached",
  "unmanaged"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "env",
    "query": {
     "query": "label_values(memcached_version,env)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(memcached_version,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(memcached_version,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Slab Items",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (slab) (\n  avg_over_time(memcached_slab_current_items{env=\"$env\",job=\"$job\",instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "{{slab}}"
    }
   ]
  },
  {
   "title": "% Hit ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(rate(memcached_commands_total{env=\"$env\",job=\"$job\",instance=~\"$instance\",status=\"miss\"}[$__interval]))\n  /\n  sum(rate(memcached_commands_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}[$__interval])) > 0\n) or vector(0)",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_connections{env=\"$env\",job=\"$job\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Get / Set ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  sum (rate(memcached_commands_total{env=\"$env\",job=\"$job\",instance=~\"$instance\", command=\"set\"}[$__interval]))\n  /\n  sum (rate(memcached_commands_total{env=\"$env\",job=\"$job\",instance=~\"$instance\", command=\"get\"}[$__interval])) > 0\n) or vector(0)",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (rate(memcached_commands_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}[$__interval])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "evicts / reclaims",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(memcached_items_evicted_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "evicts"
    },
    {
     "expr": "sum(rate(memcached_items_reclaimed_total{env=\"$env\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "reclaims"
    }
   ]
  },
  {
   "title": "Read / written bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(memcached_read_bytes_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "read from network"
    },
    {
     "expr": "sum(rate(memcached_written_bytes_total{env=\"$env\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "written to network"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"})\n/\nsum(memcached_limit_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"})",
     "legendFormat": "% used memory used"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_items{env=\"$env\",job=\"$job\",instance=~\"$instance\"})",
     "legendFormat": "items "
    }
   ]
  }
 ]
}