{
 "title": "Memory Usage [deprecated]",
 "tags": [ "influxdb" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT allocated_memory_99th AS \"99th Percentile\" FROM downsampled.sidekiq_allocated_memory_per_action WHERE $timeFilter GROUP by action",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT allocated_memory_max AS \"99th Percentile\" FROM downsampled.sidekiq_allocated_memory_per_action WHERE $timeFilter GROUP by action",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT allocated_memory_max AS \"99th Percentile\" FROM downsampled.sidekiq_allocated_memory_per_action WHERE $timeFilter GROUP by action",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Allocated Memory for Grape API",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  allocated_memory_99th AS \"99th Percentile\" FROM downsampled.grape_allocated_memory_per_action WHERE $timeFilter GROUP by action",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}