{
 "title": "Method Calls Overview [deprecated]",
 "tags": [
  "method",
  "influxdb"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "process_type", "label": "Process Type", "query": "rails,sidekiq,grape" },
   { "name": "database", "label": "Database", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "content": "![](https://media.giphy.com/media/l0HlKrB02QY0f1mbm/giphy.gif)"
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "content": "# InfluxDB is Deprecated\nInfluxDB is deprecated in 13.0. This dashboad will be removed after 2020-05-22.\n\n\n\n"
  },
  {
   "title": "Method Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT mean(\"duration_95th\") FROM downsampled.[[process_type]]_method_call_timings_per_method WHERE $timeFilter AND method !~ /^(Rugged|Gitlab::Git)/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gitlab::Git Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT mean(\"duration_95th\") FROM downsampled.[[process_type]]_method_call_timings_per_method WHERE $timeFilter AND \"method\" =~ /^Gitlab::Git/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rugged Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "method_calls",
     "query": "SELECT mean(\"duration_95th\") FROM downsampled.[[process_type]]_method_call_timings_per_method WHERE $timeFilter AND \"method\" =~ /^Rugged/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}