{
 "title": "Migration Detail - Missing graph",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/2297863832 at Wed Apr  6 09:39:38 UTC 2022",
 "tags": [
  "managed",
  "registry",
  "unmanaged"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(gitlab_service_ops:rate, environment)"
    }
   },
   { "name": "stage", "query": "main,cny," },
   { "name": "migration_path", "label": "migration_path", "query": "old,new" }
  ]
 },
 "panels": [
  { "title": "General Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top-level namespaces",
   "type": "graph",
   "description": "Number of top-level namespaces registered in the metadata database.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"registry_top_level_namespaces\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "graph",
   "description": "Number of repositories registered in the metadata database. Not available in production.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"registry_repositories\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Manifests",
   "type": "graph",
   "description": "Number of manifests registered in the metadata database. Not available in production.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"registry_manifests\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Blobs",
   "type": "graph",
   "description": "Number of blobs registered in the metadata database. Not available in production.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"registry_blobs\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "New code path traffic share",
   "type": "stat",
   "description": "Percentage of requests handled by the new code path.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(registry_http_requests_total{environment=\"$environment\", stage=\"$stage\", migration_path=\"new\"}[$__interval]))\n/\nsum (rate(registry_http_requests_total{environment=\"$environment\", stage=\"$stage\", migration_path=~\"new|old\"}[$__interval]))",
     "legendFormat": "New"
    }
   ]
  },
  { "title": "Phase 2 - Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Import API RPS",
   "type": "timeseries",
   "description": "Per-second rate of requests for the `/gitlab/v1/import/{name}` endpoint. These are used by Rails to start, cancel and query the status of (pre)imports.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method) (\n  rate(registry_http_requests_total{env=\"$environment\",stage=\"$stage\", route=\"/gitlab/v1/import/{name}\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Import API p90 latency",
   "type": "timeseries",
   "description": "p90 latency of requests for the `/gitlab/v1/import/{name}` endpoint. These are used by Rails to start, cancel and query the status of (pre)imports.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (method,le) (\n     rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",route=\"/gitlab/v1/import/{name}\" ,stage=\"$stage\"}[$__interval])\n  )\n)"
    }
   ]
  },
  {
   "title": "Import API error rate",
   "type": "timeseries",
   "description": "Error rate of requests for the `/gitlab/v1/import/{name}` endpoint. These are used by Rails to start, cancel and query the status of (pre)imports.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method) (\n  rate(registry_http_requests_total{code=~\"5..\",env=\"$environment\",stage=\"$stage\", route=\"/gitlab/v1/import/{name}\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Import rate",
   "type": "timeseries",
   "description": "Per-second rate of repository (pre)imports.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (exported_type) (\n    rate(registry_http_imports_total{environment=\"$environment\", stage=\"$stage\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Inflight imports",
   "type": "timeseries",
   "description": "The number of active (pre)imports.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (exported_type) (registry_http_in_flight_imports{environment=\"$environment\", stage=\"$stage\"})"
    }
   ]
  },
  {
   "title": "Import p90 latency",
   "type": "timeseries",
   "description": "p90 latency of repository (pre)imports.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (exported_type, le) (\n    rate(registry_http_import_duration_seconds_bucket{environment=\"$environment\", stage=\"$stage\", attempted=\"true\"}[$__interval])\n  )\n)"
    }
   ]
  },
  {
   "title": "Failed import rate",
   "type": "timeseries",
   "description": "Per-second rate of failed repository (pre)imports.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (exported_type) (\n    rate(registry_http_imports_total{environment=\"$environment\", stage=\"$stage\", error=\"true\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Noop import rate",
   "type": "timeseries",
   "description": "Per-second rate of repository (pre)imports that did not initiated.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (exported_type) (\n    rate(registry_http_imports_total{environment=\"$environment\", stage=\"$stage\", attempted=\"false\"}[$__interval])\n)"
    }
   ]
  },
  {
   "title": "Failed import p90 latency",
   "type": "timeseries",
   "description": "p90 latency of failed repository (pre)imports.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (exported_type, le) (\n    rate(registry_http_import_duration_seconds_bucket{environment=\"$environment\", stage=\"$stage\", attempted=\"true\", error=\"true\"}[$__interval])\n  )\n)"
    }
   ]
  },
  {
   "title": "Worker saturation per instance",
   "type": "timeseries",
   "description": "The saturation percentage of import workers per registry instance. Each registry instance can have up to `migration.maxconcurrentimports` goroutines processing imports (workers).",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(registry_http_import_worker_saturation{environment=\"$environment\", stage=\"$stage\"})"
    }
   ]
  },
  {
   "title": "Phase 2 Progress - Rails (General)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }
  },
  {
   "title": "Pending",
   "type": "timeseries",
   "description": "Count container repositories that have not yet been (pre)imported into the new registry.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"container_repositories_migration_pending\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Imported",
   "type": "timeseries",
   "description": "Count of container repositories that have been successfully imported into the new registry.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"container_repositories_import_done\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Importing",
   "type": "timeseries",
   "description": "Count of container repositories that are currently being imported into the new registry.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"container_repositories_importing\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Pre-imported",
   "type": "timeseries",
   "description": "Count of container repositories that are currently being pre-imported into the new registry.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"container_repositories_pre_importing\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Pre-importing",
   "type": "timeseries",
   "description": "Count of container repositories that have been pre-imported and are now pending of a final import into the new registry.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"container_repositories_pre_importing\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Skipped",
   "type": "timeseries",
   "description": "Count of container repositories imports that were skipped because they do not match a given requirement (such as the max number of tags).",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"container_repositories_import_skipped\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Aborted",
   "type": "timeseries",
   "description": "Count of container repositories imports that were aborted because an unexpected error occurred.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"container_repositories_import_aborted\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Potentially stalled",
   "type": "timeseries",
   "description": "Count of container repositories that are potentially stalled in a transient import state.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"container_repositories_stalled_pre_importing\", environment=\"$environment\"})",
     "legendFormat": "pre_importing"
    },
    {
     "expr": "avg (gitlab_database_rows{query_name=\"container_repositories_stalled_pre_import_done\", environment=\"$environment\"})",
     "legendFormat": "pre_import_done"
    },
    {
     "expr": "avg (gitlab_database_rows{query_name=\"container_repositories_stalled_importing\", environment=\"$environment\"})",
     "legendFormat": "importing"
    }
   ]
  },
  {
   "title": "Phase 2 Progress - Rails (Free tier)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 }
  },
  {
   "title": "% Free Complete",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(gitlab_database_rows{query_name=\"container_repositories_import_done_free\", environment=\"${environment}\"}) / avg(gitlab_database_rows{query_name=\"container_repositories_migration_all_free\", environment=\"${environment}\"})"
    }
   ]
  },
  {
   "title": "Pending Free",
   "type": "timeseries",
   "description": "Count of container repositories imports that were aborted because an unexpected error occurred.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(gitlab_database_rows{query_name=\"container_repositories_migration_pending_free\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Done Free",
   "type": "timeseries",
   "description": "Count of container repositories imports that were aborted because an unexpected error occurred.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(gitlab_database_rows{query_name=\"container_repositories_import_done_free\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "🔬 server Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 }
  },
  {
   "title": "Estimated p90 server Latency - Overall",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
     "legendFormat": "p90 overall {{migration_path}}"
    }
   ]
  },
  {
   "title": "server Errors - Overall",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum by () (\n  rate(registry_http_requests_total{code=~\"5..\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "overall {{migration_path}}"
    }
   ]
  },
  {
   "title": "server RPS - Overall",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by () (\n  rate(registry_http_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "overall {{migration_path}}"
    }
   ]
  },
  {
   "title": "Estimated p90 server Latency - per route",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (route,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
     "legendFormat": "p90 {{migration_path}} {{route}}"
    }
   ]
  },
  {
   "title": "Apdex attribution for server Latency - per route",
   "type": "graph",
   "description": "Attributes apdex downscoring",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 98 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max((\n  sum by (route) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (route) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"2.5\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n  +\n  sum by (route) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"25\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(route) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
     "legendFormat": "{{migration_path}} {{route}}"
    }
   ]
  },
  {
   "title": "server Errors - per route",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum by (route) (\n  rate(registry_http_requests_total{code=~\"5..\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "{{migration_path}} {{route}}"
    }
   ]
  },
  {
   "title": "server RPS - per route",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 98 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (route) (\n  rate(registry_http_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "{{migration_path}} {{route}}"
    }
   ]
  },
  {
   "title": "Estimated p90 server Latency - per method",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (method,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
     "legendFormat": "p90 {{migration_path}} {{method}}"
    }
   ]
  },
  {
   "title": "Apdex attribution for server Latency - per method",
   "type": "graph",
   "description": "Attributes apdex downscoring",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 108 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max((\n  sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"2.5\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"25\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(method) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
     "legendFormat": "{{migration_path}} {{method}}"
    }
   ]
  },
  {
   "title": "server Errors - per method",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (\n  rate(registry_http_requests_total{code=~\"5..\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "{{migration_path}} {{method}}"
    }
   ]
  },
  {
   "title": "server RPS - per method",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 108 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (\n  rate(registry_http_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "{{migration_path}} {{method}}"
    }
   ]
  },
  {
   "title": "🔬 server_route_manifest_reads Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "panels": [
    {
     "title": "Estimated p90 server_route_manifest_reads Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_reads RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "Estimated p90 server_route_manifest_reads Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (method,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{migration_path}} {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_manifest_reads Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"0.5\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"1\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(method) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{migration_path}} {{method}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_reads RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "{{migration_path}} {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 server_route_manifest_writes Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 server_route_manifest_writes Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_writes RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "Estimated p90 server_route_manifest_writes Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (method,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{migration_path}} {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_manifest_writes Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"10\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"25\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(method) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{migration_path}} {{method}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_writes RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "{{migration_path}} {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 storage Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 storage Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "storage RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_storage_action_seconds_count{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "Estimated p90 storage Latency - per action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (action,le) (\n    rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{migration_path}} {{action}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for storage Latency - per action",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (action) (\n  rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\", le=\"+Inf\"}[$__interval])\n)\n\n  -\n  (\n    sum by (action) (\n  rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\", le=\"1\"}[$__interval])\n)\n\n  )\n)\n/ ignoring(action) group_left()\n(\n  sum by () (\n  rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\", le=\"+Inf\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{migration_path}} {{action}}"
      }
     ]
    },
    {
     "title": "storage RPS - per action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (action) (\n  rate(registry_storage_action_seconds_count{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "{{migration_path}} {{action}}"
      }
     ]
    }
   ]
  }
 ]
}