{
 "title": "Mimir / Memcached",
 "description": "Monitors Kubernetes Memcached Pods. Shows memory usage, hit rate, evicts and reclaims rate, items in cache, network stats, commands rate. Requires Memcached Exporter for Prometheus.",
 "tags": [
  "memcached",
  "protected",
  "mimir"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(memcached_up,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(memcached_up{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(memcached_up{namespace=\"$namespace\", job=\"$job\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version Matrix",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "memcached_version{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  { "title": "Memcached Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) / sum(memcached_limit_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (irate (memcached_commands_total{status=\"hit\",command=\"get\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[5m])) / sum (irate (memcached_commands_total{command=\"get\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[5m]\n))",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "Evicts & Reclaims rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (irate (memcached_items_evicted_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "evicts"
    },
    {
     "expr": "sum (irate (memcached_items_reclaimed_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "reclaims"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_current_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_limit_bytes{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Hit & Miss ratio",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_commands_total{status=\"hit\",command=\"get\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) / sum (memcached_commands_total{command=\"get\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})",
     "legendFormat": "hit"
    },
    {
     "expr": "sum (memcached_commands_total{status=\"miss\",command=\"get\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) / sum (memcached_commands_total{command=\"get\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Evicts (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_items_evicted_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Reclaims (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_items_reclaimed_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (memcached_current_items{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (irate (memcached_read_bytes_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum (irate (memcached_written_bytes_total{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "written"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (memcached_current_connections{namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Get & Set ratio",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_commands_total{command=\"get\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) / (sum (memcached_commands_total{command=\"get\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) + sum (memcached_commands_total{command=\"set\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}))",
     "legendFormat": "Get"
    },
    {
     "expr": "sum (memcached_commands_total{command=\"set\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"})  / (sum (memcached_commands_total{command=\"get\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}) + sum (memcached_commands_total{command=\"set\",namespace=~\"$namespace\", job=~\"$job\", pod=~\"$pod\"}))",
     "legendFormat": "Set"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (irate (memcached_commands_total{job=~\"$job\", pod=~\"$pod\", namespace=~\"$namespace\"}[5m])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}