{
 "title": "Mimir / Overview resources",
 "tags": [
  "mimir",
  "protected",
  "unmanaged"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(cortex_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(cortex_build_info{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"distributor|ingester|mimir-write\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"distributor|ingester|mimir-write\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"distributor|ingester|mimir-write\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance, device) (\n  label_replace(\n    rate(\n      node_disk_written_bytes_total{cluster=\"ops-gitlab-gke\"}[$__rate_interval]\n    ),\n  \"instance\",\n  \"$1\",\n  \"instance\",\n  \"([^:]+)(:[0-9]+)?\"\n  )\n) + ignoring(pod) group_right() (\n  label_replace(\n    label_replace(\n      count by(\n        instance,\n        pod,\n        device\n      )\n      (\n        container_fs_writes_bytes_total{\n          cluster=~\"ops-gitlab-gke\", namespace=~\"$namespace\",\n          container=~\"distributor|ingester|mimir-write\",\n          device!~\".*sda.*\"\n        }\n      ),\n      \"device\",\n      \"$1\",\n      \"device\",\n      \"/dev/(.*)\"\n    ),\n    \"instance\",\n    \"$1\",\n    \"instance\",\n    \"([^:]+)(:[0-9]+)?\"\n    ) * 0\n)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance, device) (\n  label_replace(\n    rate(\n      node_disk_read_bytes_total{cluster=\"ops-gitlab-gke\"}[$__rate_interval]\n    ),\n  \"instance\",\n  \"$1\",\n  \"instance\",\n  \"([^:]+)(:[0-9]+)?\"\n  )\n) + ignoring(pod) group_right() (\n  label_replace(\n    label_replace(\n      count by(\n        instance,\n        pod,\n        device\n      )\n      (\n        container_fs_writes_bytes_total{\n          cluster=~\"ops-gitlab-gke\", namespace=~\"$namespace\",\n          container=~\"distributor|ingester|mimir-write\",\n          device!~\".*sda.*\"\n        }\n      ),\n      \"device\",\n      \"$1\",\n      \"device\",\n      \"/dev/(.*)\"\n    ),\n    \"instance\",\n    \"$1\",\n    \"instance\",\n    \"([^:]+)(:[0-9]+)?\"\n    ) * 0\n)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk space utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (\n  kubelet_volume_stats_used_bytes{cluster=~\"ops-gitlab-gke\", namespace=~\"$namespace\"} /\n  kubelet_volume_stats_capacity_bytes{cluster=~\"ops-gitlab-gke\", namespace=~\"$namespace\"}\n)\nand\ncount by(persistentvolumeclaim) (\n  kube_persistentvolumeclaim_info{\n    cluster=~\"ops-gitlab-gke\", namespace=~\"$namespace\",\n    persistentvolumeclaim=~\".*(distributor|ingester|mimir-write).*\"\n  }\n)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"query-frontend|querier|ruler-query-frontend|ruler-querier|mimir-read\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"query-frontend|querier|ruler-query-frontend|ruler-querier|mimir-read\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"query-frontend|querier|ruler-query-frontend|ruler-querier|mimir-read\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"query-scheduler|ruler-query-scheduler|ruler|store-gateway|compactor|alertmanager|overrides-exporter|mimir-backend\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"query-scheduler|ruler-query-scheduler|ruler|store-gateway|compactor|alertmanager|overrides-exporter|mimir-backend\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"query-scheduler|ruler-query-scheduler|ruler|store-gateway|compactor|alertmanager|overrides-exporter|mimir-backend\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance, device) (\n  label_replace(\n    rate(\n      node_disk_written_bytes_total{cluster=\"ops-gitlab-gke\"}[$__rate_interval]\n    ),\n  \"instance\",\n  \"$1\",\n  \"instance\",\n  \"([^:]+)(:[0-9]+)?\"\n  )\n) + ignoring(pod) group_right() (\n  label_replace(\n    label_replace(\n      count by(\n        instance,\n        pod,\n        device\n      )\n      (\n        container_fs_writes_bytes_total{\n          cluster=~\"ops-gitlab-gke\", namespace=~\"$namespace\",\n          container=~\"query-scheduler|ruler-query-scheduler|ruler|store-gateway|compactor|alertmanager|overrides-exporter|mimir-backend\",\n          device!~\".*sda.*\"\n        }\n      ),\n      \"device\",\n      \"$1\",\n      \"device\",\n      \"/dev/(.*)\"\n    ),\n    \"instance\",\n    \"$1\",\n    \"instance\",\n    \"([^:]+)(:[0-9]+)?\"\n    ) * 0\n)",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance, device) (\n  label_replace(\n    rate(\n      node_disk_read_bytes_total{cluster=\"ops-gitlab-gke\"}[$__rate_interval]\n    ),\n  \"instance\",\n  \"$1\",\n  \"instance\",\n  \"([^:]+)(:[0-9]+)?\"\n  )\n) + ignoring(pod) group_right() (\n  label_replace(\n    label_replace(\n      count by(\n        instance,\n        pod,\n        device\n      )\n      (\n        container_fs_writes_bytes_total{\n          cluster=~\"ops-gitlab-gke\", namespace=~\"$namespace\",\n          container=~\"query-scheduler|ruler-query-scheduler|ruler|store-gateway|compactor|alertmanager|overrides-exporter|mimir-backend\",\n          device!~\".*sda.*\"\n        }\n      ),\n      \"device\",\n      \"$1\",\n      \"device\",\n      \"/dev/(.*)\"\n    ),\n    \"instance\",\n    \"$1\",\n    \"instance\",\n    \"([^:]+)(:[0-9]+)?\"\n    ) * 0\n)",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk space utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (\n  kubelet_volume_stats_used_bytes{cluster=~\"ops-gitlab-gke\", namespace=~\"$namespace\"} /\n  kubelet_volume_stats_capacity_bytes{cluster=~\"ops-gitlab-gke\", namespace=~\"$namespace\"}\n)\nand\ncount by(persistentvolumeclaim) (\n  kube_persistentvolumeclaim_info{\n    cluster=~\"ops-gitlab-gke\", namespace=~\"$namespace\",\n    persistentvolumeclaim=~\".*(query-scheduler|ruler-query-scheduler|ruler|store-gateway|compactor|alertmanager|overrides-exporter|mimir-backend).*\"\n  }\n)\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}