{
 "title": "msmiley - 2021-02-01 db perf regression due to bulk-update of namespaces table for CI minutes refresh Copy",
 "tags": [ "unmanaged" ],
 "time": { "from": "2021-02-01T00:00:00.000Z", "to": "2021-02-01T03:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(up{env=\"gprd\",type=\"patroni\",job=~\"node(-exporter)?\"}, fqdn)"
   },
   {
    "name": "relname",
    "label": "Table Name",
    "query": "namespaces, namespace_statistics, project_statistics, ci_runner_namespaces, projects, project_features, project_ci_cd_settings, ci_builds, taggings"
   }
  ]
 },
 "panels": [
  {
   "title": "Suspected distinctive indicators of the pathology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Percentage of all CPU cores/hyperthreads",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "% of all CPUs" }
   ],
   "targets": [
    {
     "expr": "avg by (mode) (\n  rate(node_cpu_seconds_total{env=\"gprd\",fqdn=\"$node\",mode!=\"idle\"}[$__rate_interval])\n)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Anonymous memory usage (mostly shared_buffers + work_mem)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(node_memory_AnonPages_bytes{env=\"gprd\",fqdn=\"$node\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AnonPages",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average rows per scan of index: index_project_features_on_project_id (table project_features)",
   "type": "graph",
   "description": "Symptom:\nLarge spikes in the number of tuples read and fetched using this index without a corresponding large increase in the number of IndexScans for the same index.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_read{env=\"gprd\", type=\"patroni\", relname=\"project_features\", indexrelname=\"index_project_features_on_project_id\", fqdn=\"$node\"}[1m]) / rate(pg_stat_user_indexes_idx_scan{env=\"gprd\", type=\"patroni\", relname=\"project_features\", indexrelname=\"index_project_features_on_project_id\", fqdn=\"$node\"}[1m])",
     "legendFormat": "rows/scan read"
    },
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_fetch{env=\"gprd\", type=\"patroni\", relname=\"project_features\", indexrelname=\"index_project_features_on_project_id\", fqdn=\"$node\"}[1m]) / rate(pg_stat_user_indexes_idx_scan{env=\"gprd\", type=\"patroni\", relname=\"project_features\", indexrelname=\"index_project_features_on_project_id\", fqdn=\"$node\"}[1m])",
     "legendFormat": "rows/scan returned"
    }
   ]
  },
  {
   "title": "Rows per second across all scans of index: index_project_features_on_project_id (table project_features)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_read{env=\"gprd\", type=\"patroni\", relname=\"project_features\", indexrelname=\"index_project_features_on_project_id\", fqdn=\"$node\"}[1m])",
     "legendFormat": "rows/second read"
    },
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_fetch{env=\"gprd\", type=\"patroni\", relname=\"project_features\", indexrelname=\"index_project_features_on_project_id\", fqdn=\"$node\"}[1m])",
     "legendFormat": "rows/second returned"
    }
   ]
  },
  {
   "title": "Average rows per scan of index: index_ci_runner_namespaces_on_runner_id_and_namespace_id (table ci_runner_namespaces)",
   "type": "graph",
   "description": "Symptom:\nLarge spikes in the number of tuples read and fetched using this index without a corresponding large increase in the number of IndexScans for the same index.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_read{env=\"gprd\", type=\"patroni\", relname=\"ci_runner_namespaces\", indexrelname=\"index_ci_runner_namespaces_on_runner_id_and_namespace_id\", fqdn=\"$node\"}[1m]) / rate(pg_stat_user_indexes_idx_scan{env=\"gprd\", type=\"patroni\", relname=\"ci_runner_namespaces\", indexrelname=\"index_ci_runner_namespaces_on_runner_id_and_namespace_id\", fqdn=\"$node\"}[1m])",
     "legendFormat": "rows/scan read"
    },
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_fetch{env=\"gprd\", type=\"patroni\", relname=\"ci_runner_namespaces\", indexrelname=\"index_ci_runner_namespaces_on_runner_id_and_namespace_id\", fqdn=\"$node\"}[1m]) / rate(pg_stat_user_indexes_idx_scan{env=\"gprd\", type=\"patroni\", relname=\"ci_runner_namespaces\", indexrelname=\"index_ci_runner_namespaces_on_runner_id_and_namespace_id\", fqdn=\"$node\"}[1m])",
     "legendFormat": "rows/scan returned"
    }
   ]
  },
  {
   "title": "Rows per second across all scans of index: index_ci_runner_namespaces_on_runner_id_and_namespace_id (table ci_runner_namespaces)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_read{env=\"gprd\", type=\"patroni\", relname=\"ci_runner_namespaces\", indexrelname=\"index_ci_runner_namespaces_on_runner_id_and_namespace_id\", fqdn=\"$node\"}[1m])",
     "legendFormat": "rows/second read"
    },
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_fetch{env=\"gprd\", type=\"patroni\", relname=\"ci_runner_namespaces\", indexrelname=\"index_ci_runner_namespaces_on_runner_id_and_namespace_id\", fqdn=\"$node\"}[1m])",
     "legendFormat": "rows/second returned"
    }
   ]
  },
  {
   "title": "Average rows per scan of index: index_namespaces_on_type_and_id_partial (table namespaces)",
   "type": "graph",
   "description": "Symptom:\nLarge spikes in the number of tuples read and fetched using this index without a corresponding large increase in the number of IndexScans for the same index.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_read{env=\"gprd\", type=\"patroni\", relname=\"namespaces\", indexrelname=\"index_namespaces_on_type_and_id_partial\", fqdn=\"$node\"}[1m]) / rate(pg_stat_user_indexes_idx_scan{env=\"gprd\", type=\"patroni\", relname=\"namespaces\", indexrelname=\"index_namespaces_on_type_and_id_partial\", fqdn=\"$node\"}[1m])",
     "legendFormat": "rows/scan read"
    },
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_fetch{env=\"gprd\", type=\"patroni\", relname=\"namespaces\", indexrelname=\"index_namespaces_on_type_and_id_partial\", fqdn=\"$node\"}[1m]) / rate(pg_stat_user_indexes_idx_scan{env=\"gprd\", type=\"patroni\", relname=\"namespaces\", indexrelname=\"index_namespaces_on_type_and_id_partial\", fqdn=\"$node\"}[1m])",
     "legendFormat": "rows/scan returned"
    }
   ]
  },
  {
   "title": "Host metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "graph",
     "description": "Percentage of all CPU cores/hyperthreads",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percentunit", "label": "% of all CPUs" }
     ],
     "targets": [
      {
       "expr": "avg by (mode) (\n  rate(node_cpu_seconds_total{env=\"gprd\",fqdn=\"$node\",mode!=\"idle\"}[$__rate_interval])\n)",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Memory usage by type",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_memory_AnonPages_bytes{env=\"gprd\",fqdn=\"$node\"}[$__interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "AnonPages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Read Throughput (bytes/sec)",
     "type": "graph",
     "description": "This measures the mean bytes read per wall-clock second from each mounted block device.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{env=\"gprd\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{device}} read rate",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Write Throughput (bytes/sec)",
     "type": "graph",
     "description": "This measures the mean bytes written per wall-clock second from each mounted block device.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total{env=\"gprd\",fqdn=\"$node\", device!~\"dm.*\"}[$__rate_interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{device}} write rate",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Postgres metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Size of table: $relname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_total_relation_size_bytes{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Rows per second changed for table: $relname (only tracked on primary db)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}",
     "legendFormat": "approx dead rows"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}[1m])",
     "legendFormat": "update rows/sec"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_hot_upd{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}[1m])",
     "legendFormat": "hot-update rows/sec"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}[1m])",
     "legendFormat": "insert rows/sec"
    },
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}[1m])",
     "legendFormat": "delete rows/sec"
    }
   ]
  },
  {
   "title": "IndexScans summed across all indexes of table: $relname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_idx_scan{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}[1m])",
     "legendFormat": "{{relname}} IndexScans"
    },
    {
     "expr": "rate(pg_stat_user_tables_idx_tup_fetch{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}[1m])",
     "legendFormat": "{{relname}} Index Tuples fetched"
    },
    {
     "expr": "rate(pg_stat_user_tables_idx_tup_fetch{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}[1m]) / rate(pg_stat_user_tables_idx_scan{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}[1m])",
     "legendFormat": "Tuples per IndexScan"
    }
   ]
  },
  {
   "title": "IndexScans for each index of table: $relname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_scan{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}[1m])",
     "legendFormat": "{{indexrelname}}"
    }
   ]
  },
  {
   "title": "Index tuples read for each index of table: $relname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_read{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}[1m])",
     "legendFormat": "{{indexrelname}}"
    }
   ]
  },
  {
   "title": "Index tuples fetched for each index of table: $relname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_fetch{env=\"gprd\", type=\"patroni\", relname=\"$relname\", fqdn=\"$node\"}[1m])",
     "legendFormat": "{{indexrelname}}"
    }
   ]
  }
 ]
}