{
 "title": "msmiley - Cloud NAT errors by client VM Copy",
 "time": { "from": "2020-09-09T10:00:00.000Z", "to": "2020-09-09T11:00:00.000Z" },
 "panels": [
  {
   "title": "Cloud NAT errors by client VM name",
   "type": "graph",
   "description": "NAT errors typically mean the Cloud NAT service dropped an outgoing connection attempt.  Common causes for such an error include:\n* All NAT source ports may be already in-use for this client host and destination IP+port.\n* Client's chosen source port for the connection attempt maps to an existing NAT entry for that connection's 5-tuple that is still in cool-down (120 seconds).",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackdriver_nat_gateway_logging_googleapis_com_user_nat_errors_by_vm{environment=\"gprd\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Sidekiq Catchall - Rate of new outgoing TCP connections per minute",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_netstat_Tcp_ActiveOpens{type=\"sidekiq\", shard=\"catchall\", environment=\"gprd\"}[1m])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Sidekiq Catchall - Retry rate for new outgoing TCP connection requests",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_netstat_TcpExt_TCPSynRetrans{type=\"sidekiq\", shard=\"catchall\", environment=\"gprd\"}[1m])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  }
 ]
}