{
 "title": "Multilevel Cache Experiment",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "fqdn1",
    "label": "fqdn1",
    "query": "label_values(up{environment=\"gprd\", type=~\"web|api\"}, fqdn)"
   },
   {
    "name": "fqdn2",
    "label": "fqdn2",
    "query": "label_values(up{environment=\"gprd\", type=~\"web|api\"}, fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Workhorse Latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{fqdn=~\"$fqdn1\", route!=\"^/api/v4/jobs/request\\\\z\"}[$__interval])) by (le, fqdn))",
     "legendFormat": "1 - {{ fqdn }}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{fqdn=~\"$fqdn2\", route!=\"^/api/v4/jobs/request\\\\z\"}[$__interval])) by (le, fqdn))",
     "legendFormat": "2 - {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Workhorse 5XX responses",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_workhorse_http_requests_total{fqdn=~\"$fqdn1\", code=~\"^5.*\"}[$__interval])) by (fqdn)",
     "legendFormat": "1 - {{ fqdn }}"
    },
    {
     "expr": "sum(increase(gitlab_workhorse_http_requests_total{fqdn=~\"$fqdn2\", code=~\"^5.*\"}[$__interval])) by (fqdn)",
     "legendFormat": "2 - {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Rails Latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(gitlab_transaction_duration_seconds_bucket{fqdn=~\"$fqdn1\"}[$__interval])) by (le, fqdn))",
     "legendFormat": "1 - {{ fqdn }}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(gitlab_transaction_duration_seconds_bucket{fqdn=~\"$fqdn2\"}[$__interval])) by (le, fqdn))",
     "legendFormat": "2 - {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Rails Cache Latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(gitlab_cache_operation_duration_seconds_bucket{fqdn=~\"$fqdn1\"}[$__interval])) by (le, fqdn))",
     "legendFormat": "1 - {{ fqdn }}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(gitlab_cache_operation_duration_seconds_bucket{fqdn=~\"$fqdn2\"}[$__interval])) by (le, fqdn))",
     "legendFormat": "2 - {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Rails Cache Total Time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_cache_operation_duration_seconds_sum{fqdn=~\"$fqdn1\"}[$__interval])) by (fqdn)",
     "legendFormat": "1 - {{ fqdn }}"
    },
    {
     "expr": "sum(rate(gitlab_cache_operation_duration_seconds_sum{fqdn=~\"$fqdn2\"}[$__interval])) by (fqdn)",
     "legendFormat": "2 - {{ fqdn }}"
    }
   ]
  }
 ]
}