{
 "title": "nat: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4891699520 at Thu Aug 17 11:35:13 UTC 2023",
 "tags": [
  "managed",
  "nat",
  "gitlab",
  "type:nat",
  "nat",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "nat Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "nat error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"nat\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"nat\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "nat error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"nat\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "nat Service | Errors"
    }
   ]
  },
  {
   "title": "nat Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}[$__interval])\n",
     "legendFormat": "nat RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"nat\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "received_tcp_packets SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"received_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "received_tcp_packets error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"received_tcp_packets\",monitor=\"global\",type=\"nat\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"received_tcp_packets\",monitor=\"global\",type=\"nat\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"received_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "received_tcp_packets error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"received_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"received_tcp_packets\",monitor=\"global\",type=\"nat\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"received_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"received_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"received_tcp_packets\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"received_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"received_tcp_packets\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"received_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"received_tcp_packets\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"received_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"received_tcp_packets\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "received_tcp_packets SLI | Errors"
    }
   ]
  },
  {
   "title": "received_tcp_packets SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"received_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}[$__interval])\n",
     "legendFormat": "received_tcp_packets RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"received_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Description\n\nMonitors GCP Cloud NAT TCP packets received.\nRequest rate is measures in IP packets, received by the Cloud NAT.\nErrors are dropped packets.\n\nHigh error rates could lead to network issues, including application errors, container fetch failures, etc.\n\n\n\n### Observability Tools\n\n* [Cloud NAT Stackdriver Dropped Packet Logs](https://console.cloud.google.com/logs/query;query=%2DjsonPayload%2Eallocation%5Fstatus%3D%22OK%22%0Aresource%2Etype%3D%22nat%5Fgateway%22;timeRange=PT30M?project=gitlab-production)\n\n"
  },
  {
   "title": "sent_tcp_packets SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"sent_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "sent_tcp_packets error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"sent_tcp_packets\",monitor=\"global\",type=\"nat\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"sent_tcp_packets\",monitor=\"global\",type=\"nat\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"sent_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "sent_tcp_packets error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"sent_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"sent_tcp_packets\",monitor=\"global\",type=\"nat\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"sent_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"sent_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"sent_tcp_packets\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"sent_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"sent_tcp_packets\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"sent_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"sent_tcp_packets\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"sent_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"sent_tcp_packets\",monitor=\"global\",type=\"nat\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "sent_tcp_packets SLI | Errors"
    }
   ]
  },
  {
   "title": "sent_tcp_packets SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"sent_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"}[$__interval])\n",
     "legendFormat": "sent_tcp_packets RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"sent_tcp_packets\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"nat\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "content": "### Description\n\nMonitors GCP Cloud NAT TCP packets sent.\nRequest rate is measures in IP packets, sent by the Cloud NAT.\nErrors are dropped packets.\n\nHigh error rates could lead to network issues, including application errors, container fetch failures, etc.\n\n\n\n### Observability Tools\n\n* [Cloud NAT Stackdriver Dropped Packet Logs](https://console.cloud.google.com/logs/query;query=%2DjsonPayload%2Eallocation%5Fstatus%3D%22OK%22%0Aresource%2Etype%3D%22nat%5Fgateway%22;timeRange=PT30M?project=gitlab-production)\n\n"
  },
  {
   "title": "🔬 SLI Detail: received_tcp_packets",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "received_tcp_packets Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sum by (environment) (\n    avg_over_time(\n      stackdriver_nat_gateway_router_googleapis_com_nat_dropped_received_packets_count{metric_prefix=\"router.googleapis.com/nat\",  ip_protocol=\"6\", project_id=~\"gitlab-staging-1|gitlab-production\"}[$__interval]\n    )\n  )\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "received_tcp_packets RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sum by (environment) (\n    avg_over_time(\n      stackdriver_nat_gateway_router_googleapis_com_nat_received_packets_count{metric_prefix=\"router.googleapis.com/nat\",  ip_protocol=\"6\", project_id=~\"gitlab-staging-1|gitlab-production\"}[$__interval]\n    )\n  )\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: sent_tcp_packets",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "sent_tcp_packets Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sum by (environment) (\n    avg_over_time(\n      stackdriver_nat_gateway_router_googleapis_com_nat_dropped_sent_packets_count{metric_prefix=\"router.googleapis.com/nat\",  ip_protocol=\"6\", project_id=~\"gitlab-staging-1|gitlab-production\"}[$__interval]\n    )\n  )\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "sent_tcp_packets RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sum by (environment) (\n    avg_over_time(\n      stackdriver_nat_gateway_router_googleapis_com_nat_sent_packets_count{metric_prefix=\"router.googleapis.com/nat\",  ip_protocol=\"6\", project_id=~\"gitlab-staging-1|gitlab-production\"}[$__interval]\n    )\n  )\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "nat_gateway_port_allocation component saturation: Cloud NAT Gateway Port Allocation",
     "type": "graph",
     "description": "Each NAT IP address on a Cloud NAT gateway offers 64,512 TCP source ports and 64,512 UDP source ports.\n\nWhen these are exhausted, processes may experience connection problems to external destinations. In the application these\nmay manifest as SMTP connection drops or webhook delivery failures. In Kubernetes, nodes may fail while\nattempting to download images from external repositories.\n\nMore details in the Cloud NAT documentation: https://cloud.google.com/nat/docs/ports-and-addresses\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, shard, gateway_name, project_id) (\n  clamp_min(\n    clamp_max(\n      sum without(nat_ip) (\n        stackdriver_nat_gateway_router_googleapis_com_nat_allocated_ports{\n          job=\"stackdriver\",\n          project_id=\"gitlab-production\",\n          env=\"$environment\",environment=\"$environment\",type=\"nat\"\n        }\n      )\n      /\n      ( 64512 * 48 )\n      or\n      sum without(nat_ip) (\n        stackdriver_nat_gateway_router_googleapis_com_nat_allocated_ports{\n          job=\"stackdriver\",\n          project_id=\"gitlab-staging-1\",\n          env=\"$environment\",environment=\"$environment\",type=\"nat\"\n        }\n      )\n      /\n      ( 64512 * 16 )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ gateway_name }} {{ project_id }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"nat\", component=\"nat_gateway_port_allocation\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"nat\", component=\"nat_gateway_port_allocation\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"nat\", component=\"nat_gateway_port_allocation\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"nat_gateway_port_allocation\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"nat_gateway_port_allocation\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "nat_host_port_allocation component saturation: Cloud NAT Host Port Allocation",
     "type": "graph",
     "description": "Cloud NAT will allocate a set of NAT ports to each host in a cluster. When these are all allocated,\nCloud NAT may be unable to allocate any more.\n\nWhen this happens, processes may experience connection problems to external destinations. In the application these\nmay manifest as SMTP connection drops or webhook delivery failures. In Kubernetes, nodes may fail while\nattempting to download images from external repositories.\n\nMore details in the Cloud NAT documentation: https://cloud.google.com/nat/docs/ports-and-addresses.\n\nNote: when reviewing the detail chart for this saturation point, the instance_id can be resolved using\n`gcloud compute instances list --project gitlab-production --filter \"id=$instance_id\"`.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, shard, instance_id, nat_gateway_name, zone) (\n  clamp_min(\n    clamp_max(\n      sum without(ip_protocol) (\n        max_over_time(\n          stackdriver_gce_instance_compute_googleapis_com_nat_port_usage{\n            job=\"stackdriver\",\n            project_id=~\"gitlab-production|gitlab-staging-1\",\n            env=\"$environment\",environment=\"$environment\",type=\"nat\"\n          }[5m]\n        )\n      )\n      /\n      sum without (nat_ip) (\n        max_over_time(\n          stackdriver_gce_instance_compute_googleapis_com_nat_allocated_ports{\n            job=\"stackdriver\",\n            project_id=~\"gitlab-production|gitlab-staging-1\",\n            env=\"$environment\",environment=\"$environment\",type=\"nat\"\n          }[5m]\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ instance_id }} {{ nat_gateway_name }} {{ zone }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"nat\", component=\"nat_host_port_allocation\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"nat\", component=\"nat_host_port_allocation\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"nat\", component=\"nat_host_port_allocation\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"nat_host_port_allocation\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"nat_host_port_allocation\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\n  patroni\n  pgbouncer\n  redis\n  redis-cache\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-ratelimiting\n  redis-db-load-balancing\n  redis-registry-cache\n  redis-repository-cache\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  nat\n  search\nend\n\nsubgraph lb\n  frontend\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\n  praefect\nend\n\nsubgraph sv\n  api\n  consul\n  git\n  kas\n  pvs\n  registry\n  web\nend\n\n\n  api --> consul\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> praefect\napi --> pvs\napi --> redis\napi --> redis-cache\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-ratelimiting\napi --> redis-repository-cache\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\nfrontend --> api\nfrontend --> git\nfrontend --> registry\nfrontend --> web\ngit --> consul\ngit --> gitaly\ngit --> google-cloud-storage\ngit --> patroni\ngit --> pgbouncer\ngit --> praefect\ngit --> pvs\ngit --> redis\ngit --> redis-cache\ngit --> redis-sidekiq\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> praefect\nkas --> redis\nnat --> frontend\npgbouncer --> patroni\npraefect --> cloud-sql\npraefect --> gitaly\nregistry --> api\nregistry --> redis-registry-cache\nweb --> consul\nweb --> gitaly\nweb --> google-cloud-storage\nweb --> patroni\nweb --> pgbouncer\nweb --> praefect\nweb --> pvs\nweb --> redis\nweb --> redis-cache\nweb --> redis-cluster-cache\nweb --> redis-cluster-chat-cache\nweb --> redis-cluster-feature-flag\nweb --> redis-cluster-ratelimiting\nweb --> redis-db-load-balancing\nweb --> redis-repository-cache\nweb --> redis-sessions\nweb --> redis-sidekiq\nweb --> search\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\n  patroni\n  pgbouncer\n  redis\n  redis-cache\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-ratelimiting\n  redis-db-load-balancing\n  redis-registry-cache\n  redis-repository-cache\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  nat\n  search\nend\n\nsubgraph lb\n  frontend\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\n  praefect\nend\n\nsubgraph sv\n  api\n  consul\n  git\n  kas\n  pvs\n  registry\n  web\nend\n\n\n  api --> consul\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> praefect\napi --> pvs\napi --> redis\napi --> redis-cache\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-ratelimiting\napi --> redis-repository-cache\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\nfrontend --> api\nfrontend --> git\nfrontend --> registry\nfrontend --> web\ngit --> consul\ngit --> gitaly\ngit --> google-cloud-storage\ngit --> patroni\ngit --> pgbouncer\ngit --> praefect\ngit --> pvs\ngit --> redis\ngit --> redis-cache\ngit --> redis-sidekiq\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> praefect\nkas --> redis\nnat --> frontend\npgbouncer --> patroni\npraefect --> cloud-sql\npraefect --> gitaly\nregistry --> api\nregistry --> redis-registry-cache\nweb --> consul\nweb --> gitaly\nweb --> google-cloud-storage\nweb --> patroni\nweb --> pgbouncer\nweb --> praefect\nweb --> pvs\nweb --> redis\nweb --> redis-cache\nweb --> redis-cluster-cache\nweb --> redis-cluster-chat-cache\nweb --> redis-cluster-feature-flag\nweb --> redis-cluster-ratelimiting\nweb --> redis-db-load-balancing\nweb --> redis-repository-cache\nweb --> redis-sessions\nweb --> redis-sidekiq\nweb --> search\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql[\"cloud-sql (Level 1)\"]\n  patroni[\"patroni (Level 2)\"]\n  pgbouncer[\"pgbouncer (Level 1)\"]\n  redis-cache[\"redis-cache (Level 3)\"]\n  redis-cluster-cache[\"redis-cluster-cache (Level 2)\"]\n  redis-cluster-chat-cache[\"redis-cluster-chat-cache (Level 2)\"]\n  redis-cluster-feature-flag[\"redis-cluster-feature-flag (Level 2)\"]\n  redis-cluster-ratelimiting[\"redis-cluster-ratelimiting (Level 2)\"]\n  redis-db-load-balancing[\"redis-db-load-balancing (Level 2)\"]\n  redis-registry-cache[\"redis-registry-cache (Level 2)\"]\n  redis-repository-cache[\"redis-repository-cache (Level 2)\"]\n  redis-sessions[\"redis-sessions (Level 3)\"]\n  redis-sidekiq[\"redis-sidekiq (Level 3)\"]\n  redis-tracechunks[\"redis-tracechunks (Level 3)\"]\n  redis[\"redis (Level 3)\"]\nend\n\nsubgraph inf\n  nat[\"nat (Level 1)\"]\n  search[\"search (Level 1)\"]\nend\n\nsubgraph lb\n  frontend[\"frontend (Level 3)\"]\nend\n\nsubgraph stor\n  gitaly[\"gitaly (Level 3)\"]\n  google-cloud-storage[\"google-cloud-storage (Level 2)\"]\n  praefect[\"praefect (Level 2)\"]\nend\n\nsubgraph sv\n  api[\"api (Level 2)\"]\n  consul[\"consul (Level 1)\"]\n  git[\"git (Level 2)\"]\n  kas[\"kas (Level 3)\"]\n  pvs[\"pvs (Level 3)\"]\n  registry[\"registry (Level 2)\"]\n  web[\"web (Level 2)\"]\nend\n\n\n  api[\"api (Level 2)\"] --> consul\napi[\"api (Level 2)\"] --> gitaly\napi[\"api (Level 2)\"] --> google-cloud-storage\napi[\"api (Level 2)\"] --> kas\napi[\"api (Level 2)\"] --> patroni\napi[\"api (Level 2)\"] --> pgbouncer\napi[\"api (Level 2)\"] --> praefect\napi[\"api (Level 2)\"] --> pvs\napi[\"api (Level 2)\"] --> redis\napi[\"api (Level 2)\"] --> redis-cache\napi[\"api (Level 2)\"] --> redis-cluster-cache\napi[\"api (Level 2)\"] --> redis-cluster-chat-cache\napi[\"api (Level 2)\"] --> redis-cluster-feature-flag\napi[\"api (Level 2)\"] --> redis-cluster-ratelimiting\napi[\"api (Level 2)\"] --> redis-repository-cache\napi[\"api (Level 2)\"] --> redis-sessions\napi[\"api (Level 2)\"] --> redis-sidekiq\napi[\"api (Level 2)\"] --> redis-tracechunks\napi[\"api (Level 2)\"] --> search\nfrontend[\"frontend (Level 3)\"] --> api\nfrontend[\"frontend (Level 3)\"] --> git\nfrontend[\"frontend (Level 3)\"] --> registry\nfrontend[\"frontend (Level 3)\"] --> web\ngit[\"git (Level 2)\"] --> consul\ngit[\"git (Level 2)\"] --> gitaly\ngit[\"git (Level 2)\"] --> google-cloud-storage\ngit[\"git (Level 2)\"] --> patroni\ngit[\"git (Level 2)\"] --> pgbouncer\ngit[\"git (Level 2)\"] --> praefect\ngit[\"git (Level 2)\"] --> pvs\ngit[\"git (Level 2)\"] --> redis\ngit[\"git (Level 2)\"] --> redis-cache\ngit[\"git (Level 2)\"] --> redis-sidekiq\ngitaly[\"gitaly (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> api\nkas[\"kas (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> kas\nkas[\"kas (Level 3)\"] --> praefect\nkas[\"kas (Level 3)\"] --> redis\nnat[\"nat (Level 1)\"] --> frontend\npgbouncer[\"pgbouncer (Level 1)\"] --> patroni\npraefect[\"praefect (Level 2)\"] --> cloud-sql\npraefect[\"praefect (Level 2)\"] --> gitaly\nregistry[\"registry (Level 2)\"] --> api\nregistry[\"registry (Level 2)\"] --> redis-registry-cache\nweb[\"web (Level 2)\"] --> consul\nweb[\"web (Level 2)\"] --> gitaly\nweb[\"web (Level 2)\"] --> google-cloud-storage\nweb[\"web (Level 2)\"] --> patroni\nweb[\"web (Level 2)\"] --> pgbouncer\nweb[\"web (Level 2)\"] --> praefect\nweb[\"web (Level 2)\"] --> pvs\nweb[\"web (Level 2)\"] --> redis\nweb[\"web (Level 2)\"] --> redis-cache\nweb[\"web (Level 2)\"] --> redis-cluster-cache\nweb[\"web (Level 2)\"] --> redis-cluster-chat-cache\nweb[\"web (Level 2)\"] --> redis-cluster-feature-flag\nweb[\"web (Level 2)\"] --> redis-cluster-ratelimiting\nweb[\"web (Level 2)\"] --> redis-db-load-balancing\nweb[\"web (Level 2)\"] --> redis-repository-cache\nweb[\"web (Level 2)\"] --> redis-sessions\nweb[\"web (Level 2)\"] --> redis-sidekiq\nweb[\"web (Level 2)\"] --> search\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}