{
 "title": "nduff - sidekiq debug",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4679452170 at Tue Jul 18 14:17:00 UTC 2023",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", environment=\"gprd\", pod=~\"gitlab-sidekiq-urgent-other.+\", container!=\"\"}[1m])) by (pod, container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", environment=\"gprd\", pod=~\"gitlab-sidekiq-urgent-other.+\"}[1m])) by (pod, container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{env=\"gprd\", pod=~\"gitlab-sidekiq-urgent-other.+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{env=\"gprd\", pod=~\"gitlab-sidekiq-urgent-other.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HPA autoscaling",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{env=\"gprd\", horizontalpodautoscaler=\"gitlab-sidekiq-urgent-other-v2\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}