{
 "title": "nduff - thanos memcached",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memcached Operation Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (operation, name) (rate(thanos_memcached_operation_failures_total{env=\"gprd\", cluster=\"gprd-gitlab-gke\", namespace=\"monitoring\"}[1m]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memcahced Operation Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, operation, name) (rate(thanos_memcached_operation_duration_seconds_bucket{env=\"gprd\", cluster=\"gprd-gitlab-gke\", namespace=\"monitoring\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memcached Data Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, operation, name) (rate(thanos_memcached_operation_data_size_bytes_bucket{env=\"gprd\", cluster=\"gprd-gitlab-gke\", namespace=\"monitoring\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memcached Get Multi Gate Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, operation, name) (rate(thanos_memcached_getmulti_gate_duration_seconds_bucket{env=\"gprd\", cluster=\"gprd-gitlab-gke\", namespace=\"monitoring\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memcached Skipped Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (operation, name, reason) (rate(thanos_memcached_operation_skipped_total{env=\"gprd\", cluster=\"gprd-gitlab-gke\", namespace=\"monitoring\"}[1m]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memcached Client DNS Lookup Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (name) (rate(thanos_memcached_dns_failures_total{env=\"gprd\", cluster=\"gprd-gitlab-gke\", namespace=\"monitoring\"}[1m]))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Hit %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (name) (rate(thanos_cache_memcached_hits_total{env=\"gprd\", cluster=\"gprd-gitlab-gke\", namespace=\"monitoring\"}[1m])) / sum by (name) (rate(thanos_cache_memcached_requests_total{env=\"gprd\", cluster=\"gprd-gitlab-gke\", namespace=\"monitoring\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (memcached_current_connections{env=\"gprd\", cluster=\"gprd-gitlab-gke\", namespace=\"monitoring\"}) by (pod)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum (memcached_max_connections{env=\"gprd\", cluster=\"gprd-gitlab-gke\", namespace=\"monitoring\"}) by (pod)",
     "legendFormat": "max connections"
    }
   ]
  }
 ]
}