{
 "title": "nduff: query frontend",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/3809339561 at Tue Feb 21 19:57:51 UTC 2023",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\", environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(thanos_build_info{environment=\"$environment\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(thanos_build_info{namespace=\"$namespace\", job=~\".+query-frontend\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\", resource=\"cpu\"}) by (pod))",
     "legendFormat": "requests"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\", resource=\"cpu\"}) by (pod))",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$job.+\", cluster=\"$cluster\", container=\"query-frontend\"}[$__rate_interval])) by (container) / sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$job.+\", cluster=\"$cluster\", container=\"query-frontend\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\", resource=\"memory\"}) by (pod))",
     "legendFormat": "requests"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\", resource=\"memory\"}) by (pod))",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Pod Terminatinos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by (reason) (kube_pod_container_status_last_terminated_reason{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\", container=\"query-frontend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Frontend API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of requests",
   "type": "graph",
   "description": "Shows rate of requests against Query Frontend for the given time.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, handler, code) (rate(http_requests_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))",
     "legendFormat": "{{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Rate of queries",
   "type": "graph",
   "description": "Shows rate of queries passing through Query Frontend",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, handler, code) (rate(thanos_query_frontend_queries_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", op=\"query_range\"}[$interval]))",
     "legendFormat": "{{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests against Query Frontend.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(http_requests_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\",code=~\"5..\"}[$interval])) / sum by (job) (rate(http_requests_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(http_request_duration_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(http_request_duration_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Show rate of cache requests.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, tripperware) (rate(cortex_cache_request_duration_seconds_count{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{tripperware}}"
    }
   ]
  },
  {
   "title": "Querier cache gets vs misses",
   "type": "graph",
   "description": "Show rate of Querier cache gets vs misses.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, tripperware) (rate(querier_cache_gets_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Cache gets - {{job}} {{tripperware}}"
    },
    {
     "expr": "sum by (job, tripperware) (rate(querier_cache_misses_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Cache misses - {{job}} {{tripperware}}"
    }
   ]
  },
  {
   "title": "Cortex fetched keys",
   "type": "graph",
   "description": "Shows rate of cortex fetched keys.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, tripperware) (rate(cortex_cache_fetched_keys_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{tripperware}}"
    }
   ]
  },
  {
   "title": "Cortex cache hits",
   "type": "graph",
   "description": "Shows rate of cortex cache hits.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, tripperware) (rate(cortex_cache_hits_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{tripperware}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
     "legendFormat": "alloc all {{instance}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
     "legendFormat": "alloc heap {{instance}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[30s])",
     "legendFormat": "alloc rate all {{instance}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[30s])",
     "legendFormat": "alloc rate heap {{instance}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
     "legendFormat": "inuse heap {{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
     "legendFormat": "inuse stack {{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
     "legendFormat": "{{quantile}} {{instance}}"
    }
   ]
  }
 ]
}