{
 "title": "Network Ingress / Egress",
 "time": { "from": "now-120d", "to": "now" },
 "panels": [
  {
   "title": "Fe (HAProxy) Registry Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^fe-registry-[0-9].*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^fe-registry-[0-9].*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Fe (HAProxy) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^fe-[0-9].*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^fe-[0-9].*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Fe Pages (HAProxy) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^fe-pages-[0-9].*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^fe-pages-[0-9].*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Fe Registry (HAProxy) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^fe-registry-[0-9].*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^fe-registry-[0-9].*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Git Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^git-.*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^git-.*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "API Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^api-.*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^api-.*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Web Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^web-[0-9]+.*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^web-[0-9]+.*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Web-Pages Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^web-pages.*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^web-pages.*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "File (Gitaly) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^file-.*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^file-.*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Pages Storage (NFS) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^pages-.*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^pages-.*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Object storage  Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket_name) (stackdriver_gcs_bucket_storage_googleapis_com_network_sent_bytes_count) * 1440",
     "legendFormat": "{{ bucket_name }}"
    },
    {
     "expr": "sum by (bucket_name) (stackdriver_gcs_bucket_storage_googleapis_com_network_received_bytes_count) * 1440 * -1",
     "legendFormat": "{{ bucket_name }}"
    }
   ]
  },
  {
   "title": "Share Cache Storage (Traces / Artifacts) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"^share-.*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"^share-.*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Patroni  (Database) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", type=\"patroni\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", type=\"patroni\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Redis  (All) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", type=~\"^redis.*\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\",type=~\"^redis.*\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Share Cache Storage (Traces / Artifacts) Data Transfer / 24h",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device!=\"lo\", type=\"patroni\", env=\"gprd\"}[1d]))",
     "legendFormat": "egress"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device!=\"lo\", type=\"patroni\", env=\"gprd\"}[1d])) * -1",
     "legendFormat": "ingress"
    }
   ]
  }
 ]
}