{
 "title": "Object Storage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bucket Sizes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "stackdriver_gcs_bucket_storage_googleapis_com_storage_total_bytes",
     "legendFormat": "{{ bucket_name }}"
    }
   ]
  },
  { "title": "API request count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "API request count by response code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gcs_bucket_storage_googleapis_com_api_request_count / 60) by (response_code, bucket_name)",
     "legendFormat": "{{ bucket_name }} {{ response_code }}"
    }
   ]
  },
  {
   "title": "API request count by method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gcs_bucket_storage_googleapis_com_api_request_count / 60) by (method, bucket_name)",
     "legendFormat": "{{ bucket_name }} {{ method }}"
    }
   ]
  },
  { "title": "Bytes Received and Sent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Bytes received by response code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gcs_bucket_storage_googleapis_com_network_received_bytes_count / 60) by (response_code, bucket_name)",
     "legendFormat": "{{ bucket_name }} {{ response_code }}"
    }
   ]
  },
  {
   "title": "Bytes sent by response code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gcs_bucket_storage_googleapis_com_network_sent_bytes_count / 60) by (response_code, bucket_name)",
     "legendFormat": "{{ bucket_name }} {{ response_code }}"
    }
   ]
  },
  {
   "title": "Bytes received by method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gcs_bucket_storage_googleapis_com_network_received_bytes_count / 60) by (method, bucket_name)",
     "legendFormat": "{{ bucket_name }} {{ method }}"
    }
   ]
  },
  {
   "title": "Bytes sent by method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gcs_bucket_storage_googleapis_com_network_sent_bytes_count / 60) by (method, bucket_name)",
     "legendFormat": "{{ bucket_name }} {{ method }}"
    }
   ]
  }
 ]
}