{
 "title": "observability: Gatekeeper",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6074486344 at Thu Feb  1 15:39:55 UTC 2024",
 "tags": [
  "managed",
  "observability",
  "k8s",
  "gos",
  "gitlab-observability"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "Node",
    "query": "query_result(count(count_over_time(kube_node_labels{environment=\"$environment\", cluster=\"$cluster\"}[1w])) by (label_kubernetes_io_hostname))"
   },
   { "name": "environment", "label": "Environment", "query": "gstg,gprd" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_container_info{env=\"$environment\",cluster=~\"opstrace-.*\"}, cluster)"
   },
   {
    "name": "gatekeeperPods",
    "label": "Gatekeeper pods",
    "query": "label_values(kube_pod_container_info{env=\"$environment\",cluster=~\"opstrace-.*\", container=\"gatekeeper\"}, pod)"
   },
   { "name": "Deployment", "query": "gatekeeper," },
   { "name": "namespace", "query": "default," }
  ]
 },
 "panels": [
  { "title": "Gatekeeper version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Version",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_info{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", container_id!=\"\", pod=~\"^$Deployment.*$\"}) by (image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Active Replicaset",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_replicaset_spec_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", replicaset=~\"^$Deployment.*\"}) by (replicaset)",
     "legendFormat": "{{ replicaset }}"
    }
   ]
  },
  { "title": "Deployment Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Deployment Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", pod=~\"^$Deployment.*$\"}) / sum (kube_node_status_allocatable{resource=\"memory\", unit= \"byte\", env=~\"$environment\", node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", pod=~\"^$Deployment.*$\"}[2m])) / sum (machine_cpu_cores{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(kube_deployment_status_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"}) or vector(0)) - ((sum(kube_deployment_status_replicas_available{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"}) or vector(0)))) / (sum(kube_deployment_status_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", pod=~\"^$Deployment.*$\"})"
    }
   ]
  },
  {
   "title": "Memory Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable{env=~\"$environment\", cluster=\"$cluster\", resource=\"memory\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "CPU Cores Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", pod=~\"^$Deployment.*$\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{env=~\"$environment\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pods available (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"})"
    }
   ]
  },
  {
   "title": "Pods total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", image!=\"\", pod=~\"^$Deployment.*$\"}[1m])) by (pod,node)",
     "legendFormat": "real: {{ pod }}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", resource=\"cpu\", unit=\"core\", pod=~\"^$Deployment.*$\"}) by (pod,node)",
     "legendFormat": "rqst: {{ pod }}"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 211 },
   "targets": [
    {
     "expr": "sum(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{env=~\"$environment\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(namespace,pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", env=~\"$environment\"} * on(namespace,pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{env=~\"$environment\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod) / sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", env=~\"$environment\"} * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 } },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\", container=\"gatekeeper\"}) by (pod)",
     "legendFormat": "real: {{ pod }}"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 311 },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{env=~\"$environment\", container!=\"\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", env=~\"$environment\"} * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{env=~\"$environment\", container!=\"\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod) /sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", env=~\"$environment\"} * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 } },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 401 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  { "title": "Login statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 } },
  {
   "title": "Logins",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 501 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(login_failures{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "failures"
    },
    {
     "expr": "sum(rate(login_starts{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "starts"
    },
    {
     "expr": "sum(rate(login_successes{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "successes"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 600 } },
  {
   "title": "Logins",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 601 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(object_type) (rate(cache_gets{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "get - {{object_type}}"
    },
    {
     "expr": "sum(rate(login_successes{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum (rate(cache_misses{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache sets by type",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 601 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(object_type) (rate(cache_sets{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "{{object_type}}"
    }
   ]
  },
  {
   "title": "Redis GET time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 611 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cache_get_time_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis SET time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 611 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cache_set_time_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Master PING time",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 621 },
   "targets": [
    {
     "expr": "sum by(le) (increase(master_ping_time_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Master failovers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 621 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(master_failovers{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "{{object_type}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 700 } },
  {
   "title": "Requests total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 701 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(uri, method, code) (rate(gin_uri_request_total{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$gatekeeperPods\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{ uri }} - {{code}}"
    }
   ]
  }
 ]
}