{
 "title": "observability: Tracing",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5570806381 at Sun Nov 19 23:49:24 UTC 2023",
 "tags": [
  "managed",
  "observability",
  "gitlab-observability"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "Node",
    "query": "query_result(count(count_over_time(kube_node_labels{environment=\"$environment\", cluster=\"$cluster\"}[1w])) by (label_kubernetes_io_hostname))"
   },
   { "name": "environment", "label": "Environment", "query": "gstg,gprd" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_container_info{env=\"$environment\", cluster=~\"opstrace-.*\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels{namespace=~\"tenant-.*\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Deployment Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Version - otel-collector",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(\n  kube_pod_container_info{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}\n) by (image)\n",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Up - otel-collector/metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\", job=\"otel-collector\", endpoint=\"metrics\"}\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Process uptime - otel-collector",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "otelcol_process_uptime{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Query API uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",container=\"trace-query-api\",env=\"$environment\",namespace=\"default\", endpoint=\"metrics\"}\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "HTTP Receiver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Accepted Spans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(otelcol_receiver_accepted_spans{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}[1m])\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Refused Spans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(otelcol_receiver_refused_spans{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}[1m])\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "ClickHouse Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Spans Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(custom_spans_received{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}[1m])\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Spans Ingested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(custom_spans_ingested{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}[1m])\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Traces Total Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(custom_traces_size_bytes{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}[1m])\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Resource Utilisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 } },
  {
   "title": "CPU - otel-collector (millicores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}[2m])\n) by (namespace) * 1000\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Usage (max) - otel-collector (GBs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}) / (1024*1024*1024)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU - trace-query-api (millicores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",container=\"trace-query-api\",env=\"$environment\",namespace=\"default\"}[2m])\n) * 1000\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage (max) - trace-query-api (GBs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"trace-query-api\",env=\"$environment\",namespace=\"default\"}) / (1024*1024*1024)\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "Pipeline Scalability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 } },
  {
   "title": "Memory-Limiter Refused Spans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(otelcol_processor_refused_spans{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}[1m])\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Exporter Queue Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "otelcol_exporter_queue_capacity{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Exporter Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "otelcol_exporter_queue_size{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Exporter Enqueue Failed Spans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(otelcol_exporter_enqueue_failed_spans{cluster=\"$cluster\",container=\"otel-collector\",env=\"$environment\",namespace=\"$namespace\"}[1m])\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Trace Query API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 } },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 501 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(http_requests_total{cluster=\"$cluster\",container=\"trace-query-api\",env=\"$environment\",namespace=\"default\"}[1m])\n) by (path, code)\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "95th percentile Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 501 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(http_requests_duration_seconds_bucket{cluster=\"$cluster\",container=\"trace-query-api\",env=\"$environment\",namespace=\"default\"}[1m])\n  ) by (le)\n)\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "95th percentile Response Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 501 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(http_response_size_bucket{cluster=\"$cluster\",container=\"trace-query-api\",env=\"$environment\",namespace=\"default\"}[1m])\n  ) by (le)\n)\n",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}