{
 "title": "observability: Ingress-nginx",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5450170080 at Thu Nov  2 22:55:22 UTC 2023",
 "tags": [
  "managed",
  "observability",
  "k8s",
  "gos",
  "gitlab-observability"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "Node",
    "query": "query_result(count(count_over_time(kube_node_labels{environment=\"$environment\", cluster=\"$cluster\"}[1w])) by (label_kubernetes_io_hostname))"
   },
   { "name": "environment", "label": "Environment", "query": "gstg,gprd" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_container_info{env=\"$environment\", cluster=~\"opstrace-.*\"}, cluster)"
   },
   {
    "name": "nginxPods",
    "label": "Nginx pods",
    "query": "label_values(kube_pod_container_info{env=\"$environment\", cluster=~\"opstrace-.*\", container=\"nginx-ingress\"}, pod)"
   },
   { "name": "Deployment", "query": "nginx-ingress," },
   { "name": "namespace", "query": "default," }
  ]
 },
 "panels": [
  { "title": "Ingress-nginx version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Version",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_info{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", container_id!=\"\", pod=~\"^$Deployment.*$\"}) by (image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Active Replicaset",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_replicaset_spec_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", replicaset=~\"^$Deployment.*\"}) by (replicaset)",
     "legendFormat": "{{ replicaset }}"
    }
   ]
  },
  { "title": "Deployment Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Deployment Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", pod=~\"^$Deployment.*$\"}) / sum (kube_node_status_allocatable{resource=\"memory\", unit= \"byte\", env=~\"$environment\", node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", pod=~\"^$Deployment.*$\"}[2m])) / sum (machine_cpu_cores{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(kube_deployment_status_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"}) or vector(0)) - ((sum(kube_deployment_status_replicas_available{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"}) or vector(0)))) / (sum(kube_deployment_status_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", pod=~\"^$Deployment.*$\"})"
    }
   ]
  },
  {
   "title": "Memory Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable{env=~\"$environment\", cluster=\"$cluster\", resource=\"memory\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "CPU Cores Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", pod=~\"^$Deployment.*$\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{env=~\"$environment\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pods available (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"})"
    }
   ]
  },
  {
   "title": "Pods total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", image!=\"\", pod=~\"^$Deployment.*$\"}[1m])) by (pod,node)",
     "legendFormat": "real: {{ pod }}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", resource=\"cpu\", unit=\"core\", pod=~\"^$Deployment.*$\"}) by (pod,node)",
     "legendFormat": "rqst: {{ pod }}"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 211 },
   "targets": [
    {
     "expr": "sum(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{env=~\"$environment\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(namespace,pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", env=~\"$environment\"} * on(namespace,pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{env=~\"$environment\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod) / sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", env=~\"$environment\"} * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 } },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\", container=\"nginx-ingress\"}) by (pod)",
     "legendFormat": "real: {{ pod }}"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 311 },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{env=~\"$environment\", container!=\"\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", env=~\"$environment\"} * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{env=~\"$environment\", container!=\"\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod) /sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", env=~\"$environment\"} * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 } },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 401 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  { "title": "Request Handling Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 } },
  {
   "title": "Requests per second by HTTP status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 601 },
   "yaxes": [
    { "format": "short", "label": "conn/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\"}[$__rate_interval])) by (status) > 0 ",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Requests duration by HTTP status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 601 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (status, le) (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{status}} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (status, le) (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{status}} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (status, le) (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{status}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (status, le) (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{status}} p99"
    }
   ]
  },
  {
   "title": "Requests per second by ingress",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 611 },
   "yaxes": [
    { "format": "short", "label": "req/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\"}[$__rate_interval])) by (host, path) > 0 ",
     "legendFormat": "{{host}}{{path}}"
    }
   ]
  },
  {
   "title": "Requests duration by ingress",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 611 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (host,path, le) (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\"}[$__interval])\n))\n",
     "legendFormat": "{{host}}{{path}} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (host,path, le) (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\"}[$__interval])\n))\n",
     "legendFormat": "{{host}}{{path}} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (host,path, le) (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\"}[$__interval])\n))\n",
     "legendFormat": "{{host}}{{path}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (host,path, le) (\n  rate(nginx_ingress_controller_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\"}[$__interval])\n))\n",
     "legendFormat": "{{host}}{{path}} p99"
    }
   ]
  },
  {
   "title": "Connections per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 621 },
   "yaxes": [
    { "format": "short", "label": "conn/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_connections_total{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\"}[$__rate_interval])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Response Error Rate by Method and Path",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 621 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, host, path) (rate(nginx_ingress_controller_request_duration_seconds_count{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$nginxPods\", status =~ \"[4-5].*\"}[$__rate_interval]))",
     "legendFormat": "{{ method }} {{ host }}{{ path }}"
    }
   ]
  }
 ]
}