{
 "title": "observability: Ingress",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7760649883 at Fri Sep  6 06:48:18 UTC 2024",
 "tags": [
  "managed",
  "observability",
  "k8s",
  "gitlab-observability"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "Node",
    "query": "query_result(count(count_over_time(kube_node_labels{environment=\"$environment\", cluster=\"$cluster\"}[1w])) by (label_kubernetes_io_hostname))"
   },
   { "name": "environment", "label": "Environment", "query": "gstg,gprd" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_container_info{env=\"$environment\", cluster=~\"opstrace-.*\"}, cluster)"
   },
   {
    "name": "pods",
    "label": "Traefik pods",
    "query": "label_values(kube_pod_container_info{env=\"$environment\", cluster=~\"opstrace-.*\", container=\"traefik\"}, pod)"
   },
   { "name": "Deployment", "query": "traefik" },
   { "name": "namespace", "query": "default," }
  ]
 },
 "panels": [
  { "title": "Traefik version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Version",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_info{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", container_id!=\"\", pod=~\"^$Deployment.*$\"}) by (image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Active Replicaset",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_replicaset_spec_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", replicaset=~\"^$Deployment.*\"}) by (replicaset)",
     "legendFormat": "{{ replicaset }}"
    }
   ]
  },
  { "title": "Deployment Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Deployment Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", pod=~\"^$Deployment.*$\"}) / sum (kube_node_status_allocatable{resource=\"memory\", unit= \"byte\", env=~\"$environment\", node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", pod=~\"^$Deployment.*$\"}[2m])) / sum (machine_cpu_cores{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(kube_deployment_status_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"}) or vector(0)) - ((sum(kube_deployment_status_replicas_available{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"}) or vector(0)))) / (sum(kube_deployment_status_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", pod=~\"^$Deployment.*$\"})"
    }
   ]
  },
  {
   "title": "Memory Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable{env=~\"$environment\", cluster=\"$cluster\", resource=\"memory\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "CPU Cores Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", pod=~\"^$Deployment.*$\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{env=~\"$environment\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pods available (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"})"
    }
   ]
  },
  {
   "title": "Pods total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$Deployment.*\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", image!=\"\", pod=~\"^$Deployment.*$\"}[1m])) by (pod,node)",
     "legendFormat": "real: {{ pod }}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", resource=\"cpu\", unit=\"core\", pod=~\"^$Deployment.*$\"}) by (pod,node)",
     "legendFormat": "rqst: {{ pod }}"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 211 },
   "targets": [
    {
     "expr": "sum(label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{env=~\"$environment\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(namespace,pod) group_left(workload) (mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"} or mixin_pod:workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"})) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", env=~\"$environment\"} * on(namespace,pod) group_left(workload) (mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"} or mixin_pod:workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) ) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{env=~\"$environment\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(pod) group_left(workload) (mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"} or mixin_pod:workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"})) by (pod)\n/\nsum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", env=~\"$environment\"} * on(pod) group_left(workload) (mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"} or mixin_pod:workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"})) by (pod)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 } },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\", container=\"traefik\"}) by (pod)",
     "legendFormat": "real: {{ pod }}"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 311 },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{env=~\"$environment\", container!=\"\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(pod) group_left(workload) (mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"} or mixin_pod:workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"})) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", env=~\"$environment\"} * on(pod) group_left(workload) (mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"} or mixin_pod:workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"})) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{env=~\"$environment\", container!=\"\"}, \"pod\", \"$1\", \"pod\", \"(.*)\") * on(pod) group_left(workload) (mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"} or mixin_pod:workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod) /sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", env=~\"$environment\"} * on(pod) group_left(workload) (mixin_pod_workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"} or mixin_pod:workload{env=~\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", workload=~\"^$Deployment.*\"}) by (pod)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 } },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 401 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{env=~\"$environment\", cluster=\"$cluster\", node=~\"^$Node.*$\", namespace=\"$namespace\", id!=\"/\",pod=~\"^$Deployment.*$\"}[1m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  { "title": "Request Handling Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 } },
  {
   "title": "Requests per second by HTTP status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 601 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    traefik_service_requests_total{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\"}[$__rate_interval]\n  )\n) by (code) > 0\n",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Requests duration by HTTP status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 611 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (code, le) (\n  rate(traefik_service_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{code}} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (code, le) (\n  rate(traefik_service_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{code}} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (code, le) (\n  rate(traefik_service_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{code}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (code, le) (\n  rate(traefik_service_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\"}[$__interval])\n))\n",
     "legendFormat": "HTTP {{code}} p99"
    }
   ]
  },
  {
   "title": "Requests per second by Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 621 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    traefik_service_requests_total{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\"}[$__rate_interval]\n  )\n) by (service) > 0\n",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Requests duration by Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 631 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (service, le) (\n  rate(traefik_service_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\"}[$__interval])\n))\n",
     "legendFormat": "{{service}} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (service, le) (\n  rate(traefik_service_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\"}[$__interval])\n))\n",
     "legendFormat": "{{service}} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (service, le) (\n  rate(traefik_service_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\"}[$__interval])\n))\n",
     "legendFormat": "{{service}} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (service, le) (\n  rate(traefik_service_request_duration_seconds_bucket{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\"}[$__interval])\n))\n",
     "legendFormat": "{{service}} p99"
    }
   ]
  },
  {
   "title": "Open Connections per Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 641 },
   "yaxes": [
    { "format": "short", "label": "conn/sec" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    traefik_service_open_connections{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\"}[$__rate_interval]\n  )\n) by (service) > 0\n",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Error Rate by Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 651 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    traefik_service_requests_total{env=\"$environment\", cluster=~\"$cluster\", pod=~\"$pods\", code =~ \"[4-5].*\"}[$__rate_interval]\n  )\n) by (method, service, code) > 0\n",
     "legendFormat": "{{ method }} {{ service }} {{code}}"
    }
   ]
  }
 ]
}