{
 "title": "OPEN ALERTS OF ALERTMANAGER",
 "description": "Dashboard to visualize only Open(LIVE) Alerts of AlertManager instead of looking in Slack, Teams, and Emails.",
 "tags": [
  "alertmanager",
  "open-alerts",
  "shubhamc183",
  "unmanaged"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "alertmanager",
    "label": "Alertmanager",
    "query": "camptocamp-prometheus-alertmanager-datasource"
   },
   { "name": "region", "label": "Region", "query": "label_values(region)" },
   {
    "name": "severity",
    "label": "Severity",
    "query": "label_values(region=~\"$region\")"
   },
   {
    "name": "alertname",
    "label": "Alert",
    "query": "label_values(region=~\"$region\", severity=~\"$severity\")"
   },
   {
    "name": "team",
    "label": "Product",
    "query": "label_values(region=~\"$region\", severity=~\"$severity\", alertname=~\"$alertname\")"
   },
   {
    "name": "env",
    "label": "ENV",
    "query": "label_values(region=~\"$region\", severity=~\"$severity\", alertname=~\"$alertname\", team=~\"$team\")"
   },
   {
    "name": "host",
    "label": "Node",
    "query": "label_values(region=~\"$region\", severity=~\"$severity\", alertname=~\"$alertname\", team=~\"$team\", env=~\"$env\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "region=~\"$region\", severity=~\"$severity\",alertname=~\".*\", team=~\"$team\",env=~\"$env\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Total Critical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "region=~\"$region\", severity=~\"critical\",alertname=~\".*\", team=~\"$team\",env=~\"$env\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Total Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "region=~\"$region\", severity=~\"warning\",alertname=~\".*\", team=~\"$team\",env=~\"$env\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Instance Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "region=~\"$region\", severity=~\"$severity\",alertname=~\"InstanceDown\", team=~\"$team\",env=~\"$env\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "Service Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "region=~\"$region\", severity=~\"$severity\",alertname=~\"ServiceDown\", team=~\"$team\",env=~\"$env\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "MemoryUtilization-WARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "region=~\"$region\", severity=~\"$severity\",alertname=~\".*MemoryUtilization-WARN\", team=~\"$team\",env=~\"$env\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "CpuUtilization-WARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "region=~\"$region\", severity=~\"$severity\",alertname=~\".*CpuUtilization-WARN\", team=~\"$team\",env=~\"$env\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "DiskUtilization - WARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "region=~\"$region\", severity=~\"$severity\",alertname=~\".*DiskUtilization - WARN\", team=~\"$team\",env=~\"$env\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "single"
    }
   ]
  },
  {
   "title": "OPEN ALERTS",
   "type": "table-old",
   "description": "MAKE SURE TO SCROLL TO BOTTOM AND CHECK FOR MORE ALERTS",
   "gridPos": { "h": 98, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "region=~\"$region\", severity=~\"$severity\",alertname=~\"$alertname\", team=~\"$team\",env=~\"$env\"",
     "labelSelector": "*",
     "legendFormat": "{{ msg }}",
     "target": "Query",
     "type": "table"
    }
   ]
  }
 ]
}