{
 "title": "ops-gitlab-net: Kube Containers Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4963082134 at Mon Aug 28 06:41:48 UTC 2023",
 "tags": [
  "managed",
  "ops-gitlab-net",
  "ops-gitlab-net",
  "type:ops-gitlab-net",
  "kube",
  "kube detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "gitaly deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gitaly container/gitaly deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 gitaly Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 gitaly Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 gitaly Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 gitaly Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 gitaly Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 gitaly Container CPU"
    }
   ]
  },
  {
   "title": "gitaly container/gitaly deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p99 gitaly Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p95 gitaly Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p75 gitaly Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p50 gitaly Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p25 gitaly Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p10 gitaly Container Memory"
    }
   ]
  },
  {
   "title": "gitaly container/gitaly deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "gitaly container/gitaly deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"gitaly\",deployment=\"gitaly\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "kas deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "kas container/kas deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 kas Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 kas Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 kas Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 kas Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 kas Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 kas Container CPU"
    }
   ]
  },
  {
   "title": "kas container/kas deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p99 kas Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p95 kas Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p75 kas Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p50 kas Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p25 kas Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p10 kas Container Memory"
    }
   ]
  },
  {
   "title": "kas container/kas deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "kas container/kas deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"kas\",deployment=\"kas\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "registry deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "registry container/registry deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 registry Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 registry Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 registry Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 registry Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 registry Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 registry Container CPU"
    }
   ]
  },
  {
   "title": "registry container/registry deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p99 registry Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p95 registry Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p75 registry Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p50 registry Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p25 registry Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p10 registry Container Memory"
    }
   ]
  },
  {
   "title": "registry container/registry deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "registry container/registry deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"registry\",deployment=\"registry\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "sidekiq deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "sidekiq container/sidekiq deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 sidekiq Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 sidekiq Container CPU"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p99 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p95 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p75 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p50 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p25 sidekiq Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p10 sidekiq Container Memory"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "sidekiq container/sidekiq deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"sidekiq\",deployment=\"sidekiq\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "webservice deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "gitlab-workhorse container/webservice deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 gitlab-workhorse Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 gitlab-workhorse Container CPU"
    }
   ]
  },
  {
   "title": "gitlab-workhorse container/webservice deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p99 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p95 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p75 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p50 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p25 gitlab-workhorse Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p10 gitlab-workhorse Container Memory"
    }
   ]
  },
  {
   "title": "gitlab-workhorse container/webservice deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "gitlab-workhorse container/webservice deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"gitlab-workhorse\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "webservice container/webservice deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 webservice Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 webservice Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 webservice Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 webservice Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 webservice Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 webservice Container CPU"
    }
   ]
  },
  {
   "title": "webservice container/webservice deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p99 webservice Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p95 webservice Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p75 webservice Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p50 webservice Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p25 webservice Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n }\n)\n",
     "legendFormat": "p10 webservice Container Memory"
    }
   ]
  },
  {
   "title": "webservice container/webservice deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "webservice container/webservice deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"webservice\",deployment=\"webservice\",type=\"ops-gitlab-net\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}