{
 "title": "ops-gitlab-net: Capacity Review",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4887639872 at Wed Aug 16 20:52:50 UTC 2023",
 "tags": [
  "managed",
  "ops-gitlab-net",
  "ops-gitlab-net",
  "type:ops-gitlab-net",
  "capacity-review"
 ],
 "time": { "from": "now-15d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "open_fds: Open file descriptor utilization per instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(2)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"open_fds\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"open_fds\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Open file descriptor utilization per instance",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{stage=\"main\",type=\"ops-gitlab-net\", component=\"open_fds\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"open_fds\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"open_fds\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 2 },
   "content": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n"
  },
  {
   "title": "kube_horizontalpodautoscaler_desired_replicas: Horizontal Pod Autoscaler Desired Replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_horizontalpodautoscaler_desired_replicas\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_horizontalpodautoscaler_desired_replicas\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Horizontal Pod Autoscaler Desired Replicas",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 102 },
   "content": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n"
  },
  {
   "title": "ruby_thread_contention: Ruby Thread Contention",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"ruby_thread_contention\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"ruby_thread_contention\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Ruby Thread Contention",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{stage=\"main\",type=\"ops-gitlab-net\", component=\"ruby_thread_contention\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"ruby_thread_contention\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"ruby_thread_contention\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"ruby_thread_contention\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"ruby_thread_contention\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 202 },
   "content": "Ruby (technically Ruby MRI), like some other scripting languages, uses a Global VM lock (GVL) also known as a\nGlobal Interpreter Lock (GIL) to ensure that multiple threads can execute safely. Ruby code is only allowed to\nexecute in one thread in a process at a time. When calling out to c extensions, the thread can cede the lock to\nother thread while it continues to execute.\n\nThis means that when CPU-bound workloads run in a multithreaded environment such as Puma or Sidekiq, contention\nwith other Ruby worker threads running in the same process can occur, effectively slowing thoses threads down as\nthey await GVL entry.\n\nOften the best fix for this situation is to add more workers by scaling up the fleet.\n"
  },
  {
   "title": "cloudsql_cpu: CloudSQL CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"cloudsql_cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"cloudsql_cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "CloudSQL CPU Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 302 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{stage=\"main\",type=\"ops-gitlab-net\", component=\"cloudsql_cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"cloudsql_cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"cloudsql_cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cloudsql_cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cloudsql_cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 302 },
   "content": "CloudSQL CPU utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details\n"
  },
  {
   "title": "cloudsql_disk: CloudSQL Disk Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 401 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 401 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 401 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"cloudsql_disk\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 401 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"cloudsql_disk\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "CloudSQL Disk Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 402 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{stage=\"main\",type=\"ops-gitlab-net\", component=\"cloudsql_disk\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"cloudsql_disk\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"cloudsql_disk\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cloudsql_disk\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cloudsql_disk\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 402 },
   "content": "CloudSQL Disk utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details\n"
  },
  {
   "title": "cloudsql_memory: CloudSQL Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 501 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 501 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 501 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"cloudsql_memory\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 501 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"cloudsql_memory\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "CloudSQL Memory Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 502 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{stage=\"main\",type=\"ops-gitlab-net\", component=\"cloudsql_memory\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"cloudsql_memory\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"cloudsql_memory\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cloudsql_memory\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cloudsql_memory\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 502 },
   "content": "CloudSQL Memory utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details\n"
  },
  {
   "title": "kube_go_memory: Go Memory Utilization per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 600 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 601 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 601 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 601 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_go_memory\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 601 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_go_memory\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Go Memory Utilization per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 602 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_go_memory\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_go_memory\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_go_memory\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 602 },
   "content": "Measures Go memory usage as a percentage of container memory limit\n"
  },
  {
   "title": "kube_container_cpu: Kube Container CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 700 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 701 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 701 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 701 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 701 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Kube Container CPU Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 702 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_container_cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_container_cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_container_cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 702 },
   "content": "Kubernetes containers are allocated a share of CPU. When this is exhausted, the container may be thottled.\n"
  },
  {
   "title": "kube_container_rss: Kube Container Memory Utilization (RSS)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 800 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 801 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 801 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 801 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_rss\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 801 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_rss\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"ops-gitlab-net\"}\n"
    }
   ]
  },
  {
   "title": "Kube Container Memory Utilization (RSS)",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 802 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_container_rss\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_container_rss\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{stage=\"main\",type=\"ops-gitlab-net\", component=\"kube_container_rss\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_rss\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_rss\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 802 },
   "content": "Records the total anonymous (unevictable) memory utilization for containers for this\nservice, as a percentage of the memory limit as configured through Kubernetes.\n\nThis is computed using the container's resident set size (RSS), as opposed to\nkube_container_memory which uses the working set size. For our purposes, RSS is the\nbetter metric as cAdvisor's working set calculation includes pages from the\nfilesystem cache that can (and will) be evicted before the OOM killer kills the\ncgroup.\n\nA container's RSS (anonymous memory usage) is still not precisely what the OOM\nkiller will use, but it's a better approximation of what the container's workload is\nactually using. RSS metrics can, however, be dramatically inflated if a process in\nthe container uses MADV_FREE (lazy-free) memory. RSS will include the memory that is\navailable to be reclaimed without a page fault, but not currently in use.\n\nThe most common case of OOM kills is for anonymous memory demand to overwhelm the\ncontainer's memory limit. On swapless hosts, anonymous memory cannot be evicted from\nthe page cache, so when a container's memory usage is mostly anonymous pages, the\nonly remaining option to relieve memory pressure may be the OOM killer.\n\nAs container RSS approaches container memory limit, OOM kills become much more\nlikely. Consequently, this ratio is a good leading indicator of memory saturation\nand OOM risk.\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}