{
 "title": "OSQuery",
 "description": "Uptycs OSQueryd Metrics",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "environment", "label": "environment", "query": "gprd, gstg" }
  ]
 },
 "panels": [
  {
   "title": "osqueryd fleet CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (env) (rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"osqueryd\",environment=\"$environment\",mode=\"user\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "avg by (env) (rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"osqueryd\",environment=\"$environment\",mode=\"system\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "avg by (env) (rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"osqueryd\",environment=\"$environment\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "top5 CPU User Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5,rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"osqueryd\",environment=\"$environment\",mode=\"user\"}[1h]))",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "top5 CPU System Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5,rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"osqueryd\",environment=\"$environment\",mode=\"system\"}[1h]))",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "osqueryd fleet IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (env) (rate(namedprocess_namegroup_write_bytes_total{groupname=\"osqueryd\",environment=\"$environment\"}[5m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum by (env) (rate(namedprocess_namegroup_read_bytes_total{groupname=\"osqueryd\",environment=\"$environment\"}[5m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "top5 write IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(5,rate(namedprocess_namegroup_write_bytes_total{groupname=\"osqueryd\",environment=\"$environment\"}[2h]))",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "top5 read IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(5,rate(namedprocess_namegroup_read_bytes_total{groupname=\"osqueryd\",environment=\"$environment\"}[2h]))",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "avg. memory usage per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{groupname=\"osqueryd\", environment=\"$environment\"}) / count(up{environment=\"$environment\"})",
     "legendFormat": "memory per node"
    }
   ]
  },
  {
   "title": "top5 memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,namedprocess_namegroup_memory_bytes{groupname=\"osqueryd\",environment=\"$environment\"})",
     "legendFormat": "{{fqdn}}"
    }
   ]
  }
 ]
}