{
 "title": "Page timing metrics",
 "tags": [
  "pages",
  "page timings"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "sitespeed_io" },
   { "name": "path", "query": "$base.*" },
   { "name": "group", "label": "domain", "query": "$base.$path.pageSummary.*" },
   {
    "name": "page",
    "query": "$base.$path.pageSummary.$group.*"
   },
   {
    "name": "browser",
    "query": "$base.$path.pageSummary.$group.$page.*"
   },
   {
    "name": "connectivity",
    "query": "$base.$path.pageSummary.$group.$page.$browser.*"
   },
   {
    "name": "function",
    "query": "min, mean,median,p90,max,stddev"
   }
  ]
 },
 "panels": [
  { "title": "Page metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Visual Metrics [$function]",
   "type": "graph",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.serverResponseTime.$function, 'TTFB')"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LargestImage.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.PerceptualSpeedIndex.$function, 10)"
    },
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, 'Fully Loaded')"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "The total number of requests.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.requests, 8)"
    }
   ]
  },
  {
   "title": "Total size",
   "type": "graph",
   "description": "The total transfer size over the wire (compressed size if your asset is compressed) of all assets on the page. The content size is the uncompressed size for compressed text/css/html/js/font content.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentSize, 8)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.transferSize, 8)"
    }
   ]
  },
  {
   "title": "DOM Elements",
   "type": "graph",
   "description": "The number of DOM elements on the page.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domElements, 'DOM elements')"
    }
   ]
  },
  {
   "title": "Visual Metrics stddev",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.stddev, 10)"
    }
   ]
  },
  {
   "title": "CPU long tasks  [$function]",
   "type": "graph",
   "description": "Metrics from the Long Task API. CPU tasks that takes more than 50 ms to run. Enable collecting long tasks with --cpu [Chrome only].",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.tasks.$function, 'Total long tasks')"
    },
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.beforeFirstPaint.tasks.$function, 'Before first paint')"
    },
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.beforeFirstContentfulPaint.tasks.$function, 'Before first contentful paint')"
    },
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.afterLoadEventEnd.tasks.$function, 'After load event end')"
    }
   ]
  },
  {
   "title": "CPU longest long tasks",
   "type": "graph",
   "description": "The longest CPU task. Enable collecting long tasks with --cpu [Chrome only].",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.durations.max, 'Longest long task')"
    }
   ]
  },
  {
   "title": "Long Tasks Total Durations  [$function]",
   "type": "graph",
   "description": "Metrics from the Long Task API. CPU tasks that takes more than 50 ms to run. Enable collecting long tasks with --cpu [Chrome only].",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.totalDuration.$function, 'Total long tasks')"
    },
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.beforeFirstPaint.totalDuration.$function, 'Before First Paint')"
    },
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.beforeFirstContentfulPaint.totalDuration.$function, 'Before First Contentful Paint')"
    },
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.afterLoadEventEnd.totalDuration.$function, 'After Load Event End')"
    }
   ]
  },
  {
   "title": "Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Visual Change",
     "type": "graph",
     "description": "The Visual Metrics are collected by recording and analysing a video of the screen.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), 10)"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "Speed Index",
     "type": "graph",
     "description": "The Visual Metrics are collected by recording and analysing a video of the screen.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 10)"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "TTFB/Server response time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "alias(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.serverResponseTime.$function, '24h'), 'TTFB')"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.serverResponseTime.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "Fully Loaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), 10)"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "First Visual Change History",
     "type": "graph",
     "description": "The Visual Metrics are collected by recording and analysing a video of the screen.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
      }
     ]
    }
   ]
  },
  { "title": "PageXray", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Document height",
   "type": "singlestat",
   "description": "The document height in pixels.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.documentHeight"
    }
   ]
  },
  {
   "title": "Domains",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.totalDomains"
    }
   ]
  },
  {
   "title": "Cookies",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.cookieStats.total"
    }
   ]
  },
  {
   "title": "DOM depth (avg)",
   "type": "singlestat",
   "description": "The average DOM depth of the page.",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domDepth.avg"
    }
   ]
  },
  {
   "title": "DOM depth (max)",
   "type": "singlestat",
   "description": "The max depth of DOM elements on the page.",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domDepth.max"
    }
   ]
  },
  {
   "title": "Local storage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 27 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.localStorageSize"
    }
   ]
  },
  {
   "title": "Cache expire [$function]",
   "type": "singlestat",
   "description": "The $function cache expire time of all responses for the page.",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 27 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.expireStats.$function"
    }
   ]
  },
  {
   "title": "Last modified  [$function]",
   "type": "singlestat",
   "description": "The $function last modified time of all responses for the page.",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 27 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.lastModifiedStats.$function"
    }
   ]
  },
  {
   "title": "Iframes",
   "type": "singlestat",
   "description": "The total number of iframes used on the page.",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.iframes"
    }
   ]
  },
  {
   "title": "Score",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coach Total Score",
     "type": "singlestat",
     "description": "The coach score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using best practices.",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.score"
      }
     ]
    },
    {
     "title": "Performance Score",
     "type": "singlestat",
     "description": "The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.performance.score"
      }
     ]
    },
    {
     "title": "Accessibility Score",
     "type": "singlestat",
     "description": "The accessibility score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using accessibility best practices.",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.accessibility.score"
      }
     ]
    },
    {
     "title": "Best practice score",
     "type": "singlestat",
     "description": "The best practice score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using web best practices.",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.bestpractice.score"
      }
     ]
    },
    {
     "title": "Privacy Score",
     "type": "singlestat",
     "description": "The privacy score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using user privacy best practices.",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "$base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.privacy.score"
      }
     ]
    }
   ]
  },
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Timings  [$function]",
   "type": "graph",
   "description": "Timing metrics collected using browser APIs like the Navigation Timing API.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.firstPaint.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.loadEventEnd.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.domContentLoadedTime.$function, 11)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.serverResponseTime.$function, 11)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.timeToContentfulPaint.$function, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.timeToFirstInteractive.$function, 10)"
    }
   ]
  },
  {
   "title": "Element Timings  [$function]",
   "type": "graph",
   "description": "Timings collected using the [Element Timing API](https://wicg.github.io/element-timing/).",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.elementTimings.*.renderTime.$function, 11)"
    }
   ]
  },
  {
   "title": "User Timings  [$function]",
   "type": "graph",
   "description": "All User Timing marks created on the page using the [User Timing API](https://www.w3.org/TR/user-timing/).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.userTimings.marks.*.$function, 12)"
    }
   ]
  },
  { "title": "Size drill down", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "HTML size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.html.contentSize, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.html.transferSize, 10)"
    }
   ]
  },
  {
   "title": "JavaScript size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.javascript.contentSize, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.javascript.transferSize, 10)"
    }
   ]
  },
  {
   "title": "CSS size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.css.contentSize, 10)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.css.transferSize, 10)"
    }
   ]
  },
  {
   "title": "Image size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.image.contentSize, 10)"
    }
   ]
  },
  {
   "title": "CPU [Chrome only, enable with --cpu]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }
  },
  {
   "title": "CPU [Chrome only]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.categories.*.median, 11)"
    }
   ]
  },
  {
   "title": "CPU time spent per event",
   "type": "graph",
   "description": "The CPU metrics are collected from Chrome when you add --chrome.timeline to your run. The trace log is analyzed and sorted by type.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.events.*.median, 11)"
    }
   ]
  },
  {
   "title": "Third party",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Third party request by category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.thirdparty.category.*.requests.$function, 9)"
      }
     ]
    },
    {
     "title": "Third party tools by category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.thirdparty.category.*.tools.$function, 9)"
      }
     ]
    },
    {
     "title": "CPU time spent per tool/domain - enable using --thirdParty.cpu  [Chrome only]",
     "type": "graph",
     "description": "Activate by adding --thirdParty.cpu  to to your run.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.thirdparty.tool.*.cpu.$function, 9)"
      }
     ]
    }
   ]
  },
  {
   "title": "Axe violations (enable with --axe.enable)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Violations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.axe.violations.*.$function, 9)"
      }
     ]
    }
   ]
  },
  {
   "title": "JavaScript heap [Chrome only]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "JS Heap size [Chrome only]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cdp.performance.JSHeapTotalSize.$function, 11)"
      },
      {
       "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cdp.performance.JSHeapUsedSize.$function, 11)"
      }
     ]
    }
   ]
  },
  {
   "title": "Layout shift [Chrome only]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Layout Shift  [$function]",
     "type": "graph",
     "description": "Layout shift measured using the [Layout Instability API](https://web.dev/layout-instability-api).",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.pageinfo.layoutShift.$function, 'Layout shift')"
      }
     ]
    }
   ]
  },
  {
   "title": "Response codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response codes",
     "type": "graph",
     "description": "All requests and their HTTP Status Code.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.responseCodes.*, 9)"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Console error and warnings",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.console.*.$function, 10)"
      }
     ]
    },
    {
     "title": "Errors collecting the metrics",
     "type": "graph",
     "description": "Show number of errors from Browsertime and other tools.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.errors.$function, 10)"
      }
     ]
    }
   ]
  }
 ]
}