{
 "title": "pages: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/993187816 at Thu Jan 28 16:34:52 UTC 2021",
 "tags": [
  "managed",
  "pages",
  "type:pages",
  "tier:lb",
  "pages",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   { "name": "sigma", "query": "0.5,1,1.5,2,2.5,3" }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "pages Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "pages error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"}))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"}))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "pages error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} offset 1w\n,\n  1\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "pages Service | Errors"
    }
   ]
  },
  {
   "title": "pages Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"}[$__interval])\n",
     "legendFormat": "pages RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "loadbalancer SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "loadbalancer error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"}))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"}))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "loadbalancer error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} offset 1w\n,\n  1\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"pages\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "loadbalancer SLI | Errors"
    }
   ]
  },
  {
   "title": "loadbalancer SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"}[$__interval])\n",
     "legendFormat": "loadbalancer RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"pages\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Description\n\nThis SLI models requests passing through the loadbalancer in front of the pages service.\n5xx requests for unencrypted HTTP traffic, and connection errors (not 5xx requests) for\nHTTPS traffic are considered to be errors. The loadbalancer is unable to determine the\nstatus code of HTTPS traffic as it passes through the loadbalancer encrypted.\n\n"
  },
  {
   "title": "🔬 loadbalancer Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "loadbalancer Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  label_replace(rate(haproxy_backend_http_responses_total{type=\"pages\",job=\"haproxy\",code=\"5xx\", env=\"$environment\",environment=\"$environment\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(haproxy_server_connection_errors_total{type=\"pages\", job=\"haproxy\", env=\"$environment\",environment=\"$environment\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "loadbalancer RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(haproxy_server_sessions_total{type=\"pages\", backend=~\"pages_https|pages_http\", env=\"$environment\",environment=\"$environment\"}[$__interval])\n)\n",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "avg(instance:node_cpu_utilization:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "sum(rate(node_network_receive_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_reads_completed_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_writes_completed_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_read_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_written_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Total Time",
     "type": "graph",
     "description": "Total time spent in read operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_read_time_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Total Time",
     "type": "graph",
     "description": "Total time spent in write operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_write_time_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "CPU Scheduling Waiting",
     "type": "graph",
     "description": "CPU scheduling waiting on the run queue, as a percentage of time. Aggregated to worst CPU per node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "max by (fqdn) (\n  rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[5m])\n)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg1 per core",
     "type": "graph",
     "description": "Loadavg (1 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "loadavg1" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, tier, stage, fqdn) (node_load1{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"})\n/\ncount by (environment, type, tier, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg5 per core",
     "type": "graph",
     "description": "Loadavg (5 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg5" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, tier, stage, fqdn) (node_load5{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"})\n/\ncount by (environment, type, tier, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg15 per core",
     "type": "graph",
     "description": "Loadavg (15 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg15" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, tier, stage, fqdn) (node_load15{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"})\n/\ncount by (environment, type, tier, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu component saturation: Average Service CPU Utilization",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a service fleet.\nIf it is becoming saturated, it may indicate that the fleet needs\nhorizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"cpu\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"cpu\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"cpu\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_inodes component saturation: Disk inode Utilization per Device per Node",
     "type": "graph",
     "description": "Disk inode utilization per device per node.\n\nIf this is too high, its possible that a directory is filling up with\nfiles. Consider logging in an checking temp directories for large numbers\nof files\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      1 - (\n        node_filesystem_files_free{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}\n        /\n        node_filesystem_files{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"disk_inodes\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"disk_inodes\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"disk_inodes\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_space component saturation: Disk Space Utilization per Device per Node",
     "type": "graph",
     "description": "Disk space utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      (\n        1 - instance:node_filesystem_avail:ratio{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"disk_space\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"disk_space\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"disk_space\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "memory component saturation: Memory Utilization per Node",
     "type": "graph",
     "description": "Memory utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn) (\n  clamp_min(\n    clamp_max(\n      instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"memory\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"memory\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"memory\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "nf_conntrack_entries component saturation: conntrack Entries per Node",
     "type": "graph",
     "description": "Netfilter connection tracking table utilization per node.\n\nWhen saturated, new connection attempts (incoming SYN packets) are dropped with no reply, leaving clients to slowly retry (and typically fail again) over the next several seconds.  When packets are being dropped due to this condition, kernel will log the event as: \"nf_conntrack: table full, dropping packet\".\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn, instance) (\n  clamp_min(\n    clamp_max(\n      max_over_time(node_nf_conntrack_entries{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[1m])\n      /\n      node_nf_conntrack_entries_limit{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"nf_conntrack_entries\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"nf_conntrack_entries\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"nf_conntrack_entries\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"open_fds\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"open_fds\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"open_fds\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "shard_cpu component saturation: Average CPU Utilization per Shard",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a shard of a\nservice fleet. If it is becoming saturated, it may indicate that the\nshard needs horizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"shard_cpu\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"shard_cpu\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"shard_cpu\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "single_node_cpu component saturation: Average CPU Utilization per Node",
     "type": "graph",
     "description": "Average CPU utilization per Node.\n\nIf average CPU is satured, it may indicate that a fleet is in need to horizontal or vertical scaling. It may also indicate\nimbalances in load in a fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn) (\n  clamp_min(\n    clamp_max(\n      avg without(cpu, mode) (1 - rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\"}[5m]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"single_node_cpu\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"single_node_cpu\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"pages\", component=\"single_node_cpu\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "📆 Capacity Planning",
   "type": "row",
   "gridPos": { "x": 0, "y": 100000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Currently Saturated Resources",
     "type": "table",
     "description": "Lists saturated resources that are breaching their soft SLO thresholds at this instant",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "(\n  max by (type, stage, component) (\n  clamp_max(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"pages\", stage=~\"|$stage\"}\n    ,\n    1\n  ) >= on(component, monitor, env, cluster) group_left slo:max:soft:gitlab_component_saturation:ratio\n)\n\n)\n* on(component) group_left(alert_dashboard, severity)\n(\n  absent(fake_dne{component=\"cgroup_memory\", alert_dashboard=\"sat_cgroup_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"cpu\", alert_dashboard=\"sat_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_inodes\", alert_dashboard=\"sat_disk_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_space\", alert_dashboard=\"sat_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_iops\", alert_dashboard=\"sat_disk_sus_read_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_throughput\", alert_dashboard=\"sat_disk_sus_read_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_iops\", alert_dashboard=\"sat_disk_sus_write_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_throughput\", alert_dashboard=\"sat_disk_sus_write_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_cpu\", alert_dashboard=\"sat_elastic_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_disk_space\", alert_dashboard=\"sat_elastic_disk_space\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_jvm_heap_memory\", alert_dashboard=\"sat_elastic_jvm_heap_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_cpu\", alert_dashboard=\"sat_elastic_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_disk_space\", alert_dashboard=\"sat_elastic_node_disk_space\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_thread_pools\", alert_dashboard=\"sat_elastic_thread_pools\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"go_memory\", alert_dashboard=\"sat_go_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_container_cpu\", alert_dashboard=\"sat_kube_container_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_container_memory\", alert_dashboard=\"sat_kube_container_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_hpa_instances\", alert_dashboard=\"sat_kube_hpa_instances\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_disk_space\", alert_dashboard=\"sat_kube_pvc_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_inodes\", alert_dashboard=\"sat_kube_pvc_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"memory\", alert_dashboard=\"sat_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"nf_conntrack_entries\", alert_dashboard=\"sat_conntrack\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"open_fds\", alert_dashboard=\"sat_open_fds\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_primary\", alert_dashboard=\"sat_active_db_connections_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_replica\", alert_dashboard=\"sat_active_db_connections_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_async_primary_pool\", alert_dashboard=\"sat_pgbouncer_async_pool_primary\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"pgbouncer_single_core\", alert_dashboard=\"sat_pgbouncer_single_core\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_primary_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_replica_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"praefect_cloudsql_cpu\", alert_dashboard=\"sat_praefect_cloudsql_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"private_runners\", alert_dashboard=\"sat_private_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"rails_db_connection_pool\", alert_dashboard=\"sat_rails_db_connection_pool\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"redis_clients\", alert_dashboard=\"sat_redis_clients\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"redis_memory\", alert_dashboard=\"sat_redis_memory\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"redis_primary_cpu\", alert_dashboard=\"sat_redis_primary_cpu\", severity=\"s1\"})\nor\nabsent(fake_dne{component=\"redis_secondary_cpu\", alert_dashboard=\"sat_redis_secondary_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"ruby_thread_contention\", alert_dashboard=\"sat_ruby_thread_contention\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"shard_cpu\", alert_dashboard=\"sat_shard_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"shared_runners\", alert_dashboard=\"sat_shared_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"shared_runners_gitlab\", alert_dashboard=\"sat_shared_runners_gitlab\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"sidekiq_shard_workers\", alert_dashboard=\"sat_sidekiq_shard_workers\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_cpu\", alert_dashboard=\"sat_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_puma_workers\", alert_dashboard=\"sat_single_node_puma_workers\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"workhorse_image_scaling\", alert_dashboard=\"sat_wh_image_scaling\", severity=\"s4\"})\n)\n"
      }
     ]
    },
    {
     "title": "Resources Currently at Risk of being Saturated",
     "type": "table",
     "description": "Lists saturated resources that, given their current value and weekly variance, have a high probability of breaching their soft thresholds limits within the next few hours",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "(\n  sort_desc(\n  max by (type, stage, component) (\n    clamp_max(\n      gitlab_component_saturation:ratio:avg_over_time_1w{\n        environment=\"$environment\",\n        type=\"pages\", stage=~\"|$stage\"\n      } +\n      2 *\n        gitlab_component_saturation:ratio:stddev_over_time_1w{\n          environment=\"$environment\",\n          type=\"pages\", stage=~\"|$stage\"\n        }\n      , 1\n    )\n    >= on(component, monitor, env, cluster) group_left slo:max:soft:gitlab_component_saturation:ratio\n  )\n)\n\n)\n* on(component) group_left(alert_dashboard, severity)\n(\n  absent(fake_dne{component=\"cgroup_memory\", alert_dashboard=\"sat_cgroup_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"cpu\", alert_dashboard=\"sat_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_inodes\", alert_dashboard=\"sat_disk_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_space\", alert_dashboard=\"sat_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_iops\", alert_dashboard=\"sat_disk_sus_read_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_throughput\", alert_dashboard=\"sat_disk_sus_read_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_iops\", alert_dashboard=\"sat_disk_sus_write_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_throughput\", alert_dashboard=\"sat_disk_sus_write_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_cpu\", alert_dashboard=\"sat_elastic_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_disk_space\", alert_dashboard=\"sat_elastic_disk_space\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_jvm_heap_memory\", alert_dashboard=\"sat_elastic_jvm_heap_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_cpu\", alert_dashboard=\"sat_elastic_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_disk_space\", alert_dashboard=\"sat_elastic_node_disk_space\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_thread_pools\", alert_dashboard=\"sat_elastic_thread_pools\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"go_memory\", alert_dashboard=\"sat_go_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_container_cpu\", alert_dashboard=\"sat_kube_container_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_container_memory\", alert_dashboard=\"sat_kube_container_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_hpa_instances\", alert_dashboard=\"sat_kube_hpa_instances\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_disk_space\", alert_dashboard=\"sat_kube_pvc_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_inodes\", alert_dashboard=\"sat_kube_pvc_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"memory\", alert_dashboard=\"sat_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"nf_conntrack_entries\", alert_dashboard=\"sat_conntrack\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"open_fds\", alert_dashboard=\"sat_open_fds\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_primary\", alert_dashboard=\"sat_active_db_connections_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_replica\", alert_dashboard=\"sat_active_db_connections_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_async_primary_pool\", alert_dashboard=\"sat_pgbouncer_async_pool_primary\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"pgbouncer_single_core\", alert_dashboard=\"sat_pgbouncer_single_core\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_primary_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_replica_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"praefect_cloudsql_cpu\", alert_dashboard=\"sat_praefect_cloudsql_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"private_runners\", alert_dashboard=\"sat_private_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"rails_db_connection_pool\", alert_dashboard=\"sat_rails_db_connection_pool\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"redis_clients\", alert_dashboard=\"sat_redis_clients\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"redis_memory\", alert_dashboard=\"sat_redis_memory\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"redis_primary_cpu\", alert_dashboard=\"sat_redis_primary_cpu\", severity=\"s1\"})\nor\nabsent(fake_dne{component=\"redis_secondary_cpu\", alert_dashboard=\"sat_redis_secondary_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"ruby_thread_contention\", alert_dashboard=\"sat_ruby_thread_contention\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"shard_cpu\", alert_dashboard=\"sat_shard_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"shared_runners\", alert_dashboard=\"sat_shared_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"shared_runners_gitlab\", alert_dashboard=\"sat_shared_runners_gitlab\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"sidekiq_shard_workers\", alert_dashboard=\"sat_sidekiq_shard_workers\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_cpu\", alert_dashboard=\"sat_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_puma_workers\", alert_dashboard=\"sat_single_node_puma_workers\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"workhorse_image_scaling\", alert_dashboard=\"sat_wh_image_scaling\", severity=\"s4\"})\n)\n"
      }
     ]
    },
    {
     "title": "Resources Forecasted to be at Risk of Saturation in 14d",
     "type": "table",
     "description": "Lists saturated resources that, given their growth rate over the the past week, and their weekly variance, are likely to breach their soft thresholds limits in the next 14d",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "(\n  sort_desc(\n  max by (type, stage, component) (\n    clamp_max(\n      gitlab_component_saturation:ratio:predict_linear_2w{\n        environment=\"$environment\",\n        type=\"pages\", stage=~\"|$stage\"\n      } +\n      2 *\n        gitlab_component_saturation:ratio:stddev_over_time_1w{\n          environment=\"$environment\",\n          type=\"pages\", stage=~\"|$stage\"\n        }\n    , 1\n    )\n    >= on(component, monitor, env, cluster) group_left slo:max:soft:gitlab_component_saturation:ratio\n  )\n)\n\n)\n* on(component) group_left(alert_dashboard, severity)\n(\n  absent(fake_dne{component=\"cgroup_memory\", alert_dashboard=\"sat_cgroup_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"cpu\", alert_dashboard=\"sat_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_inodes\", alert_dashboard=\"sat_disk_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_space\", alert_dashboard=\"sat_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_iops\", alert_dashboard=\"sat_disk_sus_read_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_read_throughput\", alert_dashboard=\"sat_disk_sus_read_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_iops\", alert_dashboard=\"sat_disk_sus_write_iops\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"disk_sustained_write_throughput\", alert_dashboard=\"sat_disk_sus_write_throughput\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_cpu\", alert_dashboard=\"sat_elastic_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_disk_space\", alert_dashboard=\"sat_elastic_disk_space\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"elastic_jvm_heap_memory\", alert_dashboard=\"sat_elastic_jvm_heap_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_cpu\", alert_dashboard=\"sat_elastic_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_single_node_disk_space\", alert_dashboard=\"sat_elastic_node_disk_space\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"elastic_thread_pools\", alert_dashboard=\"sat_elastic_thread_pools\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"go_memory\", alert_dashboard=\"sat_go_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_container_cpu\", alert_dashboard=\"sat_kube_container_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_container_memory\", alert_dashboard=\"sat_kube_container_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"kube_hpa_instances\", alert_dashboard=\"sat_kube_hpa_instances\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_disk_space\", alert_dashboard=\"sat_kube_pvc_disk_space\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"kube_persistent_volume_claim_inodes\", alert_dashboard=\"sat_kube_pvc_inodes\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"memory\", alert_dashboard=\"sat_memory\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"nf_conntrack_entries\", alert_dashboard=\"sat_conntrack\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"open_fds\", alert_dashboard=\"sat_open_fds\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_primary\", alert_dashboard=\"sat_active_db_connections_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pg_active_db_connections_replica\", alert_dashboard=\"sat_active_db_connections_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_async_primary_pool\", alert_dashboard=\"sat_pgbouncer_async_pool_primary\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"pgbouncer_single_core\", alert_dashboard=\"sat_pgbouncer_single_core\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_primary_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_primary\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"pgbouncer_sync_replica_pool\", alert_dashboard=\"sat_pgbouncer_sync_pool_replica\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"praefect_cloudsql_cpu\", alert_dashboard=\"sat_praefect_cloudsql_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"private_runners\", alert_dashboard=\"sat_private_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"rails_db_connection_pool\", alert_dashboard=\"sat_rails_db_connection_pool\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"redis_clients\", alert_dashboard=\"sat_redis_clients\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"redis_memory\", alert_dashboard=\"sat_redis_memory\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"redis_primary_cpu\", alert_dashboard=\"sat_redis_primary_cpu\", severity=\"s1\"})\nor\nabsent(fake_dne{component=\"redis_secondary_cpu\", alert_dashboard=\"sat_redis_secondary_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"ruby_thread_contention\", alert_dashboard=\"sat_ruby_thread_contention\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"shard_cpu\", alert_dashboard=\"sat_shard_cpu\", severity=\"s3\"})\nor\nabsent(fake_dne{component=\"shared_runners\", alert_dashboard=\"sat_shared_runners\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"shared_runners_gitlab\", alert_dashboard=\"sat_shared_runners_gitlab\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"sidekiq_shard_workers\", alert_dashboard=\"sat_sidekiq_shard_workers\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_cpu\", alert_dashboard=\"sat_single_node_cpu\", severity=\"s4\"})\nor\nabsent(fake_dne{component=\"single_node_puma_workers\", alert_dashboard=\"sat_single_node_puma_workers\", severity=\"s2\"})\nor\nabsent(fake_dne{component=\"workhorse_image_scaling\", alert_dashboard=\"sat_wh_image_scaling\", severity=\"s4\"})\n)\n"
      }
     ]
    },
    {
     "title": "Long-term Resource Saturation",
     "type": "graph",
     "description": "Resource saturation levels for saturation components for this service. Lower is better.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(\n  max(\n    gitlab_component_saturation:ratio{\n      type=\"pages\",\n      environment=\"$environment\",\n      stage=~\"|$stage\"\n    }\n  ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "{{ component }}"
      }
     ]
    },
    {
     "title": "Long-term Resource Saturation - Rolling 1w average trend",
     "type": "graph",
     "description": "Percentage of time that resource is within capacity SLOs. Higher is better.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio:avg_over_time_1w{\n        type=\"pages\",\n        environment=\"$environment\",\n        stage=~\"$stage|\"\n      }\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "{{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "content": "graph TD\n  subgraph lb\n  pages\nend\n\n\n  \n",
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "content": "graph TD\n  subgraph lb\n  pages\nend\n\n\n  \n",
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./pages/main.dashboard.jsonnet)\n"
  }
 ]
}