{
 "title": "patroni: Marginalia Sampler",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6313027828 at Mon Mar  4 15:56:14 UTC 2024",
 "tags": [
  "managed",
  "patroni",
  "type:patroni"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "fqdn",
    "query": "label_values(pg_stat_activity_marginalia_sampler_active_count{env=\"$environment\", environment=\"$environment\"}, fqdn)"
   },
   {
    "name": "application",
    "query": "label_values(pg_stat_activity_marginalia_sampler_active_count{env=\"$environment\", environment=\"$environment\"}, application)"
   },
   {
    "name": "endpoint",
    "query": "label_values(pg_stat_activity_marginalia_sampler_active_count{env=\"$environment\", environment=\"$environment\", application=~\"$application\"}, endpoint)"
   },
   {
    "name": "state",
    "query": "label_values(pg_stat_activity_marginalia_sampler_active_count{env=\"$environment\", environment=\"$environment\"}, state)"
   },
   {
    "name": "wait_event_type",
    "query": "label_values(pg_stat_activity_marginalia_sampler_active_count{env=\"$environment\", environment=\"$environment\"}, wait_event_type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unaggregated Series",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,\n  avg_over_time(pg_stat_activity_marginalia_sampler_active_count{env=\"$environment\", environment=\"$environment\", application=~\"$application\", fqdn=~\"$fqdn\", endpoint=~\"$endpoint\", state=~\"$state\", wait_event_type=~\"$wait_event_type\"}[$__interval])\n)\n"
    }
   ]
  },
  {
   "title": "Aggregated By Endpoint",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,\n  sum by (endpoint) (\n    avg_over_time(pg_stat_activity_marginalia_sampler_active_count{env=\"$environment\", environment=\"$environment\", application=~\"$application\", fqdn=~\"$fqdn\", endpoint=~\"$endpoint\", state=~\"$state\", wait_event_type=~\"$wait_event_type\"}[$__interval])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Aggregated By State and Wait Event Type",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,\n  sum by (state, wait_event_type) (\n    avg_over_time(pg_stat_activity_marginalia_sampler_active_count{env=\"$environment\", environment=\"$environment\", application=~\"$application\", fqdn=~\"$fqdn\", endpoint=~\"$endpoint\", state=~\"$state\", wait_event_type=~\"$wait_event_type\"}[$__interval])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}