{
 "title": "Performance - Manage",
 "tags": [ "product performance" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "function", "query": "min, mean,median,p90,max" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "### Synthetic tests of GitLab.com pages for the Manage group.\n\nFor more information, please see: https://gitlab.com/gitlab-org/gitlab/-/issues/221018\n\n\n\n"
  },
  { "title": "Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Value Stream Analytics",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/value_stream_analytics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Analytics_Value_Stream.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Analytics_Value_Stream.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Analytics_Value_Stream.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "Access", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Groups - List",
   "type": "graph",
   "description": "https://gitlab.com/dashboard/groups",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Access_Group_List.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Access_Group_List.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Access_Group_List.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "Import", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Project - New",
   "type": "graph",
   "description": "https://gitlab.com/projects/new",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Project_Creation.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Project_Creation.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Project_Creation.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Project - Import - GitHub",
   "type": "graph",
   "description": "https://gitlab.com/import/github/new",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Github.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Github.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Github.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Project - Import - BitBucket Cloud",
   "type": "graph",
   "description": "https://gitlab.com/import/bitbucket/status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_BitbucketCloud.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_BitbucketCloud.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_BitbucketCloud.chrome.cable.browsertime.statistics, 10)"
    }
   ]
  },
  {
   "title": "Project - Import - BitBucket Server",
   "type": "graph",
   "description": "https://gitlab.com/import/bitbucket_server/new",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_BitBucketServer.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_BitBucketServer.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_BitBucketServer.chrome.cable.browsertime.statistics, 10)"
    }
   ]
  },
  {
   "title": "Project - Import - Fogbugz",
   "type": "graph",
   "description": "https://gitlab.com/import/fogbugz/new",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Fogbugz.chrome.cable.browsertime.statistics, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Fogbugz.chrome.cable.browsertime.statistics, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Fogbugz.chrome.cable.browsertime.statistics, 10)"
    }
   ]
  },
  {
   "title": "Project - Import - Gitea",
   "type": "graph",
   "description": "https://gitlab.com/import/gitea/new",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Gitea.chrome.cable.browsertime.statistics.pageinfo.layoutShift.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Gitea.chrome.cable.browsertime.statistics, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Gitea.chrome.cable.browsertime.statistics, 10)"
    }
   ]
  },
  {
   "title": "Project - Import - Manifest",
   "type": "graph",
   "description": "https://gitlab.com/import/gitea/new",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Gitea.chrome.cable.browsertime.statistics.errors.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Gitea.chrome.cable.browsertime.statistics, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Import_Importer_Gitea.chrome.cable.browsertime.statistics, 10)"
    }
   ]
  }
 ]
}