{
 "title": "Performance - Create",
 "tags": [ "product performance" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "function", "query": "min, mean,median,p90,max" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "### Synthetic tests of GitLab.com pages for the Create group.\n\nFor more information, please see: https://gitlab.com/gitlab-org/gitlab/-/issues/221018\n\n\n\n"
  },
  { "title": "Source Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "MR List",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/merge_requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_MR_List.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_MR_List.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_MR_List.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "MR Detail - Small",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34944",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_MR_Small.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_MR_Small.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_MR_Small.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "MR Detail - Large",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/22439",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_MR_Large.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_MR_Large.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_MR_Large.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Repo Nav - Small",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/language-tools/go/linters/goargs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_Repo_Small.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_Repo_Small.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_Repo_Small.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Repo Nav - Small",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/language-tools/go/linters/goargs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_Repo_Small.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_Repo_Small.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.SourceCode_Repo_Small.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Snippets - Explore",
   "type": "graph",
   "description": "https://gitlab.com/explore/snippets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Editor_Snippets_Explore.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Editor_Snippets_Explore.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Editor_Snippets_Explore.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Snippet - Textual",
   "type": "graph",
   "description": "https://gitlab.com/snippets/1985939",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Editor_Snippets_Textual.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Editor_Snippets_Textual.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Editor_Snippets_Textual.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Snippet - Markdown",
   "type": "graph",
   "description": "https://gitlab.com/snippets/1985940",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Editor_Snippets_Markdown.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Editor_Snippets_Markdown.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Editor_Snippets_Markdown.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  { "title": "Knowledge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Designs - Collection",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/issues/1/designs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Design_Collection.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Design_Collection.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Design_Collection.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Designs - Single Image",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/issues/1/designs/10-2500x1667.jpg",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Design_Single.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Design_Single.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Design_Single.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - History",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/many-changes/history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_History.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_History.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_History.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - Pages",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/pages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_Pages.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_Pages.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_Pages.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - AsciiDoc",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/formats/asciidoc/formatted-1mb",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_AsciiDoc.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_AsciiDoc.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_AsciiDoc.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - Page 5",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/pages?page=5",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_Page5.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_Page5.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_Page5.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - RDoc",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/formats/rdoc/formatted-1mb",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_RDoc.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_RDoc.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Knowledge_Wiki_RDoc.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  }
 ]
}