{
 "title": "Performance - Verify",
 "tags": [ "product performance" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "function", "query": "min, mean,median,p90,max" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "### Synthetic tests of GitLab.com pages for the Verify group.\n\nFor more information, please see: https://gitlab.com/gitlab-org/gitlab/-/issues/221018\n\n\n\n"
  },
  { "title": "Verify", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Pipelines List",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_List.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_List.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_List.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_List.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Job List",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Job_List.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Job_List.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Job_List.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Job_List.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Pipeline Schedules",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipeline_schedules",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_Schedules.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_Schedules.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_Schedules.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_Schedules.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Job List - Filtered",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines?page=1&scope=all&username=stanhu&ref=master",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_ListFiltered.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_ListFiltered.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_ListFiltered.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_ListFiltered.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Pipeline Charts",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines/charts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_ListFiltered.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_ListFiltered.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_ListFiltered.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_ListFiltered.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Job Detail",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/jobs/549614535",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Job_Detail.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Job_Detail.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Job_Detail.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Job_Detail.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Pipeline Detail",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines/145395337",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_View.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_View.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_View.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_View.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "DAG View",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines/145395337/dag",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_DAG.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_DAG.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_DAG.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_DAG.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "Testing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Code Quality Report",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/graphs/master/charts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_CodeQuality.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_CodeQuality.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_CodeQuality.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Verify_Pipeline_CodeQuality.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  }
 ]
}