{
 "title": "Performance - Enablement",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "function", "query": "min, mean,median,p90,max" }
  ]
 },
 "panels": [
  { "title": "Global Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Basic Global Search - Projects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Basic_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Basic_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Basic_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Advanced Global Search - Projects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Advanced_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Advanced_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Advanced_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  },
  {
   "title": "Basic Search - GitHub/GitLab",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Basic_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 3, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Basic_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 3, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.github_com.GitHub_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 3, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.github_com.GitHub_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 3, 10)"
    }
   ]
  },
  {
   "title": "Advanced Global Search - Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Advanced_Search_Code.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Advanced_Search_Code.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.Advanced_Search_Code.chrome.cable.browsertime.statistics.visualMetrics.Heading.$function, 10)"
    }
   ]
  }
 ]
}