{
 "title": "Performance POC",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "pre,testbed" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "prometheus_app", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg without (mode,cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) or ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)) * 100) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Workhorse HTTP Requests p/s",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(irate(gitlab_workhorse_http_requests_total[1m]))"
    },
    {
     "expr": "sum by (job)(irate(gitlab_workhorse_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "NGINX Stats",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(nginx_vts_main_connections{status=~\"active|writing|reading|waiting\"})",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "sum by (job)(irate(nginx_vts_server_requests_total[5m]))",
     "legendFormat": "Incoming Requests"
    },
    {
     "expr": "sum by (job)(irate(nginx_vts_upstream_requests_total[5m]))",
     "legendFormat": "Upstream Requests"
    },
    {
     "expr": "avg by (job)(nginx_vts_server_request_seconds)",
     "legendFormat": "Avg Incoming Requests Duration p/sec"
    },
    {
     "expr": "avg by (job)(nginx_vts_upstream_request_seconds)",
     "legendFormat": "Avg Upstream Requests Duration p/sec"
    },
    {
     "expr": "sum(irate(nginx_vts_server_cache_total[5m])) by (job)",
     "legendFormat": "Cache Count"
    }
   ]
  },
  {
   "title": "Redis Cache Queries",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gitlab_cache_operation_duration_seconds_count[30s])) by (controller, action)"
    }
   ]
  },
  {
   "title": "SQL Transactions",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gitlab_sql_duration_seconds_count[30s]))"
    }
   ]
  },
  {
   "title": "Gitaly p95",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Workhorse p95",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "Workhorse p95"
    }
   ]
  },
  {
   "title": "Ruby Heap GC Slots",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ruby_gc_stat_heap_live_slots)",
     "legendFormat": " Ruby Heap Live Slots"
    },
    {
     "expr": "sum(ruby_gc_stat_heap_free_slots)",
     "legendFormat": "Ruby Heap Free Slots"
    }
   ]
  },
  {
   "title": "Ruby GC Cycles",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(irate(ruby_gc_stat_count[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Controller - Action Requests",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gitlab_transaction_duration_seconds_count[30s])) by (controller, action) > 0",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  }
 ]
}