{
 "title": "Performance & Memory - Overview",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg node memory allocated",
     "type": "graph",
     "description": "Average node memory allocated in AnonPages  (user space memory) as reported through /proc/meminfo.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "AnonPages (GB)" }
     ],
     "targets": [
      {
       "expr": "avg (node_memory_AnonPages_bytes{environment=\"gprd\", type=\"web\"} / 1024 / 1024 / 1024)",
       "legendFormat": "web"
      },
      {
       "expr": "avg (node_memory_AnonPages_bytes{environment=\"gprd\", type=\"api\"} / 1024 / 1024 / 1024)",
       "legendFormat": "api"
      },
      {
       "expr": "avg (node_memory_AnonPages_bytes{environment=\"gprd\", type=\"sidekiq\"} / 1024 / 1024 / 1024)",
       "legendFormat": "sidekiq"
      }
     ]
    }
   ]
  },
  {
   "title": "Ruby VM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web memory breakdown (all, GB)",
     "type": "graph",
     "description": "Memory breakdown of the web component in GB",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "avg(ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"web\"}) / 1014 / 1024 / 1024",
       "legendFormat": "USS"
      },
      {
       "expr": "avg(ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"web\"}) / 1014 / 1024 / 1024",
       "legendFormat": "PSS"
      },
      {
       "expr": "avg(ruby_process_resident_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"web\"}) / 1014 / 1024 / 1024",
       "legendFormat": "RSS"
      },
      {
       "expr": "(avg((ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"web\"}) - (ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"web\"})) * count(avg(ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"web\"}) by (pid))) / 1024 / 1024 / 1024",
       "legendFormat": "shared"
      }
     ]
    },
    {
     "title": "Web memory breakdown (real, %)",
     "type": "graph",
     "description": "Memory breakdown of estimated physical memory use of the web component in percent. Physical means accounting for shared memory between processes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (type) (ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"web\"}) / 1014 / 1024 / 1024",
       "legendFormat": "USS"
      },
      {
       "expr": "avg by (type) (ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"web\"}) / 1014 / 1024 / 1024",
       "legendFormat": "PSS"
      },
      {
       "expr": "avg((ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"web\"}) - (ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"web\"})) by (type) / 1024 / 1024 / 1024",
       "legendFormat": "shared"
      }
     ]
    },
    {
     "title": "API memory breakdown (all, GB)",
     "type": "graph",
     "description": "Memory breakdown of the api component in GB",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "avg(ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"api\"}) / 1014 / 1024 / 1024",
       "legendFormat": "USS"
      },
      {
       "expr": "avg(ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"api\"}) / 1014 / 1024 / 1024",
       "legendFormat": "PSS"
      },
      {
       "expr": "avg(ruby_process_resident_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"api\"}) / 1014 / 1024 / 1024",
       "legendFormat": "RSS"
      },
      {
       "expr": "(avg((ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"api\"}) - (ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"api\"})) * count(avg(ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"api\"}) by (pid))) / 1024 / 1024 / 1024",
       "legendFormat": "shared"
      }
     ]
    },
    {
     "title": "API memory breakdown (real, %)",
     "type": "graph",
     "description": "Memory breakdown of estimated physical memory use of the api component in percent. Physical means accounting for shared memory between processes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (type) (ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"api\"}) / 1014 / 1024 / 1024",
       "legendFormat": "USS"
      },
      {
       "expr": "avg by (type) (ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"api\"}) / 1014 / 1024 / 1024",
       "legendFormat": "PSS"
      },
      {
       "expr": "avg((ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"api\"}) - (ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"api\"})) by (type) / 1024 / 1024 / 1024",
       "legendFormat": "shared"
      }
     ]
    },
    {
     "title": "Sidekiq memory breakdown (all, GB)",
     "type": "graph",
     "description": "Memory breakdown of the sidekiq component in GB",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "avg(ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"}) / 1014 / 1024 / 1024",
       "legendFormat": "USS"
      },
      {
       "expr": "avg(ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"}) / 1014 / 1024 / 1024",
       "legendFormat": "PSS"
      },
      {
       "expr": "avg(ruby_process_resident_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"}) / 1014 / 1024 / 1024",
       "legendFormat": "RSS"
      },
      {
       "expr": "(avg((ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"}) - (ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"})) * count(avg(ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"}) by (pid))) / 1024 / 1024 / 1024",
       "legendFormat": "shared"
      }
     ]
    },
    {
     "title": "Sidekiq memory breakdown (real, %)",
     "type": "graph",
     "description": "Memory breakdown of estimated physical memory use of the sidekiq component in percent. Physical means accounting for shared memory between processes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (type) (ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"}) / 1014 / 1024 / 1024",
       "legendFormat": "USS"
      },
      {
       "expr": "avg by (type) (ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"}) / 1014 / 1024 / 1024",
       "legendFormat": "PSS"
      },
      {
       "expr": "avg((ruby_process_proportional_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"}) - (ruby_process_unique_memory_bytes{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"})) by (type) / 1024 / 1024 / 1024",
       "legendFormat": "shared"
      }
     ]
    },
    {
     "title": "Total allocated pages",
     "type": "graph",
     "description": "heap_total_allocated_pages as reported by `GC.stat`",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg (ruby_gc_stat_total_allocated_pages{environment=\"gprd\", stage=\"main\", type=\"web\"})",
       "legendFormat": "web"
      },
      {
       "expr": "avg (ruby_gc_stat_total_allocated_pages{environment=\"gprd\", stage=\"main\", type=\"api\"})",
       "legendFormat": "api"
      },
      {
       "expr": "avg (ruby_gc_stat_total_allocated_pages{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"})",
       "legendFormat": "sidekiq"
      }
     ]
    },
    {
     "title": "Allocated heap pages",
     "type": "graph",
     "description": "heap_allocated_pages as reported by `GC.stat`",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg (ruby_gc_stat_heap_allocated_pages{environment=\"gprd\", stage=\"main\", type=\"web\"})",
       "legendFormat": "web"
      },
      {
       "expr": "avg (ruby_gc_stat_heap_allocated_pages{environment=\"gprd\", stage=\"main\", type=\"api\"})",
       "legendFormat": "api"
      },
      {
       "expr": "avg (ruby_gc_stat_heap_allocated_pages{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"})",
       "legendFormat": "sidekiq"
      }
     ]
    },
    {
     "title": "Minor GCs",
     "type": "graph",
     "description": "minor_gc_count as reported by `GC.stat`",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg (ruby_gc_stat_minor_gc_count{environment=\"gprd\", stage=\"main\", type=\"web\"})",
       "legendFormat": "web"
      },
      {
       "expr": "avg (ruby_gc_stat_minor_gc_count{environment=\"gprd\", stage=\"main\", type=\"api\"})",
       "legendFormat": "api"
      },
      {
       "expr": "avg (ruby_gc_stat_minor_gc_count{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"})",
       "legendFormat": "sidekiq"
      }
     ]
    },
    {
     "title": "Major GCs",
     "type": "graph",
     "description": "major_gc_count as reported by `GC.stat`",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg (ruby_gc_stat_major_gc_count{environment=\"gprd\", stage=\"main\", type=\"web\"})",
       "legendFormat": "web"
      },
      {
       "expr": "avg (ruby_gc_stat_major_gc_count{environment=\"gprd\", stage=\"main\", type=\"api\"})",
       "legendFormat": "api"
      },
      {
       "expr": "avg (ruby_gc_stat_major_gc_count{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"})",
       "legendFormat": "sidekiq"
      }
     ]
    },
    {
     "title": "Object allocations/sec",
     "type": "graph",
     "description": "The total_allocated_objects count as reported by `GC.stat`, as a per-second-rate over a 1 hour sample set, averaged over all application processes.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (type) (rate(ruby_gc_stat_total_allocated_objects{environment=\"gprd\", stage=\"main\", type=\"web\"}[1h]))",
       "legendFormat": "web"
      },
      {
       "expr": "avg by (type) (rate(ruby_gc_stat_total_allocated_objects{environment=\"gprd\", stage=\"main\", type=\"api\"}[1h]))",
       "legendFormat": "api"
      },
      {
       "expr": "avg by (type) (rate(ruby_gc_stat_total_allocated_objects{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"}[1h]))",
       "legendFormat": "sidekiq"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global slow queries (>1s) per minute",
     "type": "graph",
     "description": "Average number of slow queries across a moving 1 hour window per minute and across the entire DB cluster.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(pg_slow_queries{environment=\"gprd\", tier=\"db\", stage=\"main\", type=\"patroni\"}[1h]) * 60)",
       "legendFormat": "slow queries/min"
      }
     ]
    },
    {
     "title": "Time spent in database",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "percent" }
     ],
     "targets": [
      {
       "expr": "job_environment:gitlab_sql_duration_seconds_sum:rate5m{environment=\"gprd\", stage=\"main\", type=\"web\"} / job_environment:gitlab_transaction_duration_seconds_sum:rate5m{environment=\"gprd\", stage=\"main\", type=\"web\"} * 100",
       "legendFormat": "web"
      },
      {
       "expr": "job_environment:gitlab_sql_duration_seconds_sum:rate5m{environment=\"gprd\", stage=\"main\", type=\"api\"} / job_environment:gitlab_transaction_duration_seconds_sum:rate5m{environment=\"gprd\", stage=\"main\", type=\"api\"} * 100",
       "legendFormat": "api"
      },
      {
       "expr": "avg(job_environment:gitlab_sql_duration_seconds_sum:rate5m{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"}) / avg(job_environment:gitlab_transaction_duration_seconds_sum:rate5m{environment=\"gprd\", stage=\"main\", type=\"sidekiq\"}) * 100",
       "legendFormat": "sidekiq"
      }
     ]
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow API endpoints",
     "type": "graph",
     "description": "API endpoints that take 2 seconds or more in the 95th",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short", "label": "sec/transaction" }
     ],
     "targets": [
      {
       "expr": "avg by (action) (controller_action:gitlab_transaction_duration_seconds:p95{environment=\"gprd\", stage=\"main\", type=\"api\"}) > 2"
      }
     ]
    },
    {
     "title": "Slow API endpoints (list)",
     "type": "table-old",
     "description": "API endpoints that take 2 seconds or more in the 95th",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sort_desc(avg by (action) (controller_action:gitlab_transaction_duration_seconds:p95{environment=\"gprd\", stage=\"main\", type=\"api\"})) > 2"
      }
     ]
    },
    {
     "title": "Slow Web endpoints",
     "type": "graph",
     "description": "Web endpoints that take 2 seconds or more in the 95th",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "sec/transaction" }
     ],
     "targets": [
      {
       "expr": "avg by (action) (controller_action:gitlab_transaction_duration_seconds:p95{environment=\"gprd\", stage=\"main\", type=\"web\"}) > 2"
      }
     ]
    }
   ]
  }
 ]
}