{
 "title": "pgbouncer Detail",
 "tags": [
  "postgresql",
  "pgbouncer",
  "unmanaged"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg" },
   {
    "name": "fqdn",
    "label": "Host",
    "query": {
     "query": "label_values(pgbouncer_pools_client_active_connections,fqdn)"
    }
   },
   {
    "name": "user",
    "label": "User",
    "query": {
     "query": "label_values(pgbouncer_pools_client_active_connections,user)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pgbouncer_pools_client_active_connections{fqdn=\"$fqdn\"},database)"
    }
   },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Active Client Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{fqdn=\"$fqdn\",database=\"$database\",user=\"$user\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fqdn={{ fqdn }},database={{ database}}, user={{ user }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Waiting Client Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer_pools_client_waiting_connections{fqdn=\"$fqdn\",database=\"$database\",user=\"$user\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fqdn={{ fqdn }},database={{ database}}, user={{ user }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pools_server_active_connections{fqdn=\"$fqdn\",database=\"$database\",user=\"$user\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "sv_active (fqdn={{ fqdn }},database={{ database}}, user={{ user }})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Wait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pgbouncer_pools_client_maxwait_seconds{fqdn=\"$fqdn\",database=\"$database\",user=\"$user\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "fqdn={{ fqdn }},database={{ database}}, user={{ user }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP Problems",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_ListenDrops{environment=\"$environment\",tier=\"db\",fqdn=\"$fqdn\"}[$__interval]) * -1",
     "legendFormat": "TCP Drops"
    },
    {
     "expr": "rate(node_netstat_TcpExt_ListenOverflows{environment=\"$environment\",tier=\"db\",fqdn=\"$fqdn\"}[$__interval])",
     "legendFormat": "TCP Overflow"
    }
   ]
  }
 ]
}