{
 "title": "pgbouncer-ci: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4277162666 at Fri May 12 16:32:25 UTC 2023",
 "tags": [
  "managed",
  "pgbouncer-ci",
  "gitlab",
  "type:pgbouncer-ci",
  "pgbouncer-ci",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "pgbouncer-ci Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "pgbouncer-ci error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"pgbouncer-ci\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"pgbouncer-ci\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "pgbouncer-ci error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"pgbouncer-ci\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"pgbouncer-ci\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"pgbouncer-ci\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"pgbouncer-ci\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"pgbouncer-ci\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "pgbouncer-ci Service | Errors"
    }
   ]
  },
  {
   "title": "pgbouncer-ci Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}[$__interval])\n",
     "legendFormat": "pgbouncer-ci RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "service SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"service\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "service error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"service\",monitor=\"global\",type=\"pgbouncer-ci\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"service\",monitor=\"global\",type=\"pgbouncer-ci\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"service\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "service error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"service\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"service\",monitor=\"global\",type=\"pgbouncer-ci\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"service\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"service\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"service\",monitor=\"global\",type=\"pgbouncer-ci\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"service\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"service\",monitor=\"global\",type=\"pgbouncer-ci\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"service\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"service\",monitor=\"global\",type=\"pgbouncer-ci\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"service\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"service\",monitor=\"global\",type=\"pgbouncer-ci\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "service SLI | Errors"
    }
   ]
  },
  {
   "title": "service SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"service\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"}[$__interval])\n",
     "legendFormat": "service RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"service\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"pgbouncer-ci\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Description\n\nAll transactions destined for the Postgres primary instance are routed through the pgbouncer service.\nThis SLI models those transactions in aggregate.\n\nError rate uses mtail metrics from pgbouncer logs.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: pgbouncer logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.pg_message),filters:!((meta:(key:json.type.keyword,params:'pgbouncer-ci',type:phrase),query:(match:(json.type.keyword:(query:'pgbouncer-ci',type:phrase)))),(meta:(key:json.tag.keyword,params:postgres.pgbouncer,type:phrase),query:(match:(json.tag.keyword:(query:postgres.pgbouncer,type:phrase)))),(meta:(key:json.type,params:'pgbouncer-ci',type:phrase),query:(match:(json.type:(query:'pgbouncer-ci',type:phrase))))),index:'97f04200-024b-11eb-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: pgbouncer requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97f04200-024b-11eb-81e5-155ba78758d4&_a=(filters:!((meta:(key:json.type.keyword,params:'pgbouncer-ci',type:phrase),query:(match:(json.type.keyword:(query:'pgbouncer-ci',type:phrase)))),(meta:(key:json.tag.keyword,params:postgres.pgbouncer,type:phrase),query:(match:(json.tag.keyword:(query:postgres.pgbouncer,type:phrase)))),(meta:(key:json.type,params:'pgbouncer-ci',type:phrase),query:(match:(json.type:(query:'pgbouncer-ci',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "🔬 SLI Detail: service",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "service Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(pgbouncer_pooler_errors_total{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"pgbouncer-ci\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "service RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  label_replace(rate(pgbouncer_stats_sql_transactions_pooled_total{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"pgbouncer-ci\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(pgbouncer_stats_queries_pooled_total{env=\"$environment\",environment=\"$environment\",tier=\"db\",type=\"pgbouncer-ci\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "service Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  rate(pgbouncer_pooler_errors_total{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"pgbouncer-ci\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "service RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  label_replace(rate(pgbouncer_stats_sql_transactions_pooled_total{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"pgbouncer-ci\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(pgbouncer_stats_queries_pooled_total{env=\"$environment\",environment=\"$environment\",fqdn!=\"\",tier=\"db\",type=\"pgbouncer-ci\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "service Errors - per error",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (error) (\n  rate(pgbouncer_pooler_errors_total{env=\"$environment\",environment=\"$environment\",error!=\"\",tier=\"db\",type=\"pgbouncer-ci\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{error}}"
      }
     ]
    },
    {
     "title": "service RPS - per error",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (error) (\n  label_replace(rate(pgbouncer_stats_sql_transactions_pooled_total{env=\"$environment\",environment=\"$environment\",error!=\"\",tier=\"db\",type=\"pgbouncer-ci\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(pgbouncer_stats_queries_pooled_total{env=\"$environment\",environment=\"$environment\",error!=\"\",tier=\"db\",type=\"pgbouncer-ci\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "{{error}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "avg(instance:node_cpu_utilization:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "sum(rate(node_network_receive_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_reads_completed_total{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_writes_completed_total{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_read_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_written_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Total Time",
     "type": "graph",
     "description": "Total time spent in read operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_read_time_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Total Time",
     "type": "graph",
     "description": "Total time spent in write operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_write_time_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "CPU Scheduling Waiting",
     "type": "graph",
     "description": "CPU scheduling waiting on the run queue, as a percentage of time. Aggregated to worst CPU per node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "max by (fqdn) (\n  rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m])\n)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg1 per core",
     "type": "graph",
     "description": "Loadavg (1 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "loadavg1" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load1{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg5 per core",
     "type": "graph",
     "description": "Loadavg (5 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg5" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load5{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg15 per core",
     "type": "graph",
     "description": "Loadavg (15 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg15" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load15{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu component saturation: Average Service CPU Utilization",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a service fleet.\nIf it is becoming saturated, it may indicate that the fleet needs\nhorizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_inodes component saturation: Disk inode Utilization per Device per Node",
     "type": "graph",
     "description": "Disk inode utilization per device per node.\n\nIf this is too high, its possible that a directory is filling up with\nfiles. Consider logging in an checking temp directories for large numbers\nof files\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      1 - (\n        node_filesystem_files_free{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}\n        /\n        node_filesystem_files{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"disk_inodes\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"disk_inodes\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"disk_inodes\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_space component saturation: Disk Space Utilization per Device per Node",
     "type": "graph",
     "description": "Disk space utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      (\n        1 - node_filesystem_avail_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"} / node_filesystem_size_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"disk_space\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"disk_space\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"disk_space\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "memory component saturation: Memory Utilization per Node",
     "type": "graph",
     "description": "Memory utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"} or instance:node_memory_utilisation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "nf_conntrack_entries component saturation: conntrack Entries per Node",
     "type": "graph",
     "description": "Netfilter connection tracking table utilization per node.\n\nWhen saturated, new connection attempts (incoming SYN packets) are dropped with no reply, leaving clients to slowly retry (and typically fail again) over the next several seconds.  When packets are being dropped due to this condition, kernel will log the event as: \"nf_conntrack: table full, dropping packet\".\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, instance) (\n  clamp_min(\n    clamp_max(\n      max_over_time(node_nf_conntrack_entries{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[1m])\n      /\n      node_nf_conntrack_entries_limit{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"nf_conntrack_entries\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"nf_conntrack_entries\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"nf_conntrack_entries\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "node_schedstat_waiting component saturation: Node Scheduler Waiting Time",
     "type": "graph",
     "description": "Measures the amount of scheduler waiting time that processes are waiting\nto be scheduled, according to [`CPU Scheduling Metrics`](https://www.robustperception.io/cpu-scheduling-metrics-from-the-node-exporter).\n\nA high value indicates that a node has more processes to be run than CPU time available\nto handle them, and may lead to degraded responsiveness and performance from the application.\n\nAdditionally, it may indicate that the fleet is under-provisioned.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, shard) (\n  clamp_min(\n    clamp_max(\n      avg without (cpu) (rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[1h]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"node_schedstat_waiting\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"node_schedstat_waiting\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"node_schedstat_waiting\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pgbouncer_async_primary_pool component saturation: Postgres Async (Sidekiq) primary Connection Pool Utilization per Node",
     "type": "graph",
     "description": "pgbouncer async connection pool utilization per database node, for primary database connections.\n\nSidekiq maintains it's own pgbouncer connection pool. When this resource is saturated,\ndatabase operations may queue, leading to additional latency in background processing.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        avg_over_time(pgbouncer_pools_server_active_connections{user=\"gitlab\", database=\"gitlabhq_production_sidekiq\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_testing_connections{user=\"gitlab\", database=\"gitlabhq_production_sidekiq\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_used_connections{user=\"gitlab\", database=\"gitlabhq_production_sidekiq\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_login_connections{user=\"gitlab\", database=\"gitlabhq_production_sidekiq\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m])\n      )\n      / on(environment, tier, type, stage, shard, fqdn, instance) group_left()\n      sum by (environment, tier, type, stage, shard, fqdn, instance) (\n        avg_over_time(pgbouncer_databases_pool_size{name=\"gitlabhq_production_sidekiq\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"pgbouncer_async_primary_pool\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"pgbouncer_async_primary_pool\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"pgbouncer_async_primary_pool\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pgbouncer_async_primary_pool\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pgbouncer_async_primary_pool\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pgbouncer_client_conn_primary component saturation: PGBouncer Client Connections per Process (Primary)",
     "type": "graph",
     "description": "Client connections per pgbouncer process for Primary connections.\n\npgbouncer is configured to use a `max_client_conn` setting. This limits the total number of client connections per pgbouncer.\n\nWhen this limit is reached, client connections may be refused, and `max_client_conn` errors may appear in the pgbouncer logs.\n\nThis could affect users as Rails clients are left unable to connect to the database. Another potential knock-on effect\nis that Rails clients could fail their readiness checks for extended periods during a deployment, leading to saturation of\nthe older nodes.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      max_over_time(pgbouncer_used_clients{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m])\n      /\n      15000\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"pgbouncer_client_conn_primary\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"pgbouncer_client_conn_primary\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"pgbouncer_client_conn_primary\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pgbouncer_client_conn_primary\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pgbouncer_client_conn_primary\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "pgbouncer_sync_primary_pool component saturation: Postgres Sync (Web/API/Git) primary Connection Pool Utilization per Node",
     "type": "graph",
     "description": "pgbouncer sync connection pool Saturation per database node, for primary database connections.\n\nWeb/api/git applications use a separate connection pool to sidekiq.\n\nWhen this resource is saturated, web/api database operations may queue, leading to rails worker\nsaturation and 503 errors in the web.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        avg_over_time(pgbouncer_pools_server_active_connections{user=~\"gitlab|gitlab-registry\", database=~\"gitlabhq_registry|gitlabhq_production\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_testing_connections{user=~\"gitlab|gitlab-registry\", database=~\"gitlabhq_registry|gitlabhq_production\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_used_connections{user=~\"gitlab|gitlab-registry\", database=~\"gitlabhq_registry|gitlabhq_production\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_login_connections{user=~\"gitlab|gitlab-registry\", database=~\"gitlabhq_registry|gitlabhq_production\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m])\n      )\n      / on(environment, tier, type, stage, shard, fqdn, instance) group_left()\n      sum by (environment, tier, type, stage, shard, fqdn, instance) (\n        avg_over_time(pgbouncer_databases_pool_size{name=~\"gitlabhq_registry|gitlabhq_production\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"pgbouncer_sync_primary_pool\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"pgbouncer_sync_primary_pool\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"pgbouncer_sync_primary_pool\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pgbouncer_sync_primary_pool\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pgbouncer_sync_primary_pool\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "shard_cpu component saturation: Average CPU Utilization per Shard",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a shard of a\nservice fleet. If it is becoming saturated, it may indicate that the\nshard needs horizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard, shard) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"shard_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"shard_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"shard_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "single_node_cpu component saturation: Average CPU Utilization per Node",
     "type": "graph",
     "description": "Average CPU utilization per Node.\n\nIf average CPU is saturated, it may indicate that a fleet is in need to horizontal or vertical scaling. It may also indicate\nimbalances in load in a fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      avg without(cpu, mode) (1 - rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\"}[5m]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"single_node_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"single_node_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"pgbouncer-ci\", component=\"single_node_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  { "title": "pgbouncer Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Queries Pooled per Node",
   "type": "graph",
   "description": "Total number of SQL queries pooled - stats_total_query_count",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_queries_pooled_total{type=\"pgbouncer-ci\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Total Time in Queries per Node",
   "type": "graph",
   "description": "Total number of seconds spent by pgbouncer when actively connected to PostgreSQL, executing queries - stats.total_query_time",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2000 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_queries_duration_seconds_total{type=\"pgbouncer-ci\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "SQL Transactions Pooled per Node",
   "type": "graph",
   "description": "Total number of SQL transactions pooled - stats.total_xact_count",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2010 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_sql_transactions_pooled_total{type=\"pgbouncer-ci\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Time in Transaction per Server",
   "type": "graph",
   "description": "Total number of seconds spent by pgbouncer when connected to PostgreSQL in a transaction, either idle in transaction or executing queries - stats.total_xact_time",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2010 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_server_in_transaction_seconds_total{type=\"pgbouncer-ci\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  { "title": "pgbouncer Connection Pooling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "Server Connection Pool Active Connections per Node",
   "type": "graph",
   "description": "Number of active connections per node",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(pgbouncer_pools_server_active_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Connection Saturation per Pool",
   "type": "graph",
   "description": "Shows connection saturation per pgbouncer pool. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "percentunit", "label": "Server Pool Utilization" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (database, env, environment, shard, stage, type) (\n  pgbouncer_pools_server_active_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_testing_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_used_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_login_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"}\n)\n/\nsum by (database, env, environment, shard, stage, type) (\n  label_replace(\n    pgbouncer_databases_pool_size{type=\"pgbouncer-ci\", environment=\"$environment\"},\n    \"database\", \"gitlabhq_production_sidekiq\", \"name\", \"gitlabhq_production_sidekiq\"\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ database }} pool"
    }
   ]
  },
  {
   "title": "Connection Saturation per Pool per Node",
   "type": "graph",
   "description": "Shows connection saturation per pgbouncer pool, per pgbouncer node. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3011 },
   "yaxes": [
    { "format": "percentunit", "label": "Server Pool Utilization" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (database, env, environment, fqdn, job, shard, stage, type) (\n  pgbouncer_pools_server_active_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_testing_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_used_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"} +\n  pgbouncer_pools_server_login_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"}\n)\n/\nsum by (database, env, environment, fqdn, job, shard, stage, type) (\n  label_replace(\n    pgbouncer_databases_pool_size{type=\"pgbouncer-ci\", environment=\"$environment\"},\n    \"database\", \"gitlabhq_production_sidekiq\", \"name\", \"gitlabhq_production_sidekiq\"\n  )\n)\n,1),0)\n",
     "legendFormat": "{{ fqdn }} {{ database }} pool"
    }
   ]
  },
  {
   "title": "Total Connection Wait Time",
   "type": "graph",
   "description": "Total aggregated time spend waiting for a backend connection. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3011 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum by (database, environment, type) (rate(pgbouncer_stats_client_wait_seconds_total{type=\"pgbouncer-ci\", environment=\"$environment\", database!=\"pgbouncer\"}[$__interval]) / on() group_left() (vector((time() < bool 1588233600) * 1000000) == 1000000 or vector(1)))\n",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "Average Wait Time per SQL Transaction",
   "type": "graph",
   "description": "Average time spent waiting for a backend connection from the pool. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3021 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum by (database, environment, type, fqdn, job) (rate(pgbouncer_stats_client_wait_seconds_total{type=\"pgbouncer-ci\", environment=\"$environment\", database!=\"pgbouncer\"}[$__interval]) / on() group_left() (vector((time() < bool 1588233600) * 1000000) == 1000000 or vector(1)))\n/\nsum by (database, environment, type, fqdn, job) (rate(pgbouncer_stats_sql_transactions_pooled_total{type=\"pgbouncer-ci\", environment=\"$environment\", database!=\"pgbouncer\"}[$__interval]))\n",
     "legendFormat": "{{ fqdn }} {{ job }} {{ database }}"
    }
   ]
  },
  {
   "title": "Waiting Client Connections per Pool (⚠️ possibly inaccurate, occassionally polled value, do not make assumptions based on this)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3021 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(pgbouncer_pools_client_waiting_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"}[$__interval])) by (database)\n",
     "legendFormat": "{{ database }} pool"
    }
   ]
  },
  {
   "title": "Active Backend Server Connections per Database",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3031 },
   "yaxes": [
    { "format": "short", "label": "Active Connections" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(pgbouncer_pools_server_active_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"}[$__interval])) by (database)\n",
     "legendFormat": "{{ database }} database"
    }
   ]
  },
  {
   "title": "Active Backend Server Connections per User",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3031 },
   "yaxes": [
    { "format": "short", "label": "Active Connections" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(pgbouncer_pools_server_active_connections{type=\"pgbouncer-ci\", environment=\"$environment\", user=\"gitlab\", database!=\"pgbouncer\"}[$__interval])) by (user)\n",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "pgbouncer Single Threaded CPU Saturation per Node",
   "type": "graph",
   "description": "pgbouncer is single-threaded. This graph shows maximum utilization across all cores on each host. Lower is better.\n\nMissing data? [https://gitlab.com/gitlab-com/gl-infra/reliability/-/issues/9980](https://gitlab.com/gitlab-com/gl-infra/reliability/-/issues/9980)\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3041 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum(\n  rate(\n    namedprocess_namegroup_cpu_seconds_total{groupname=~\"pgbouncer.*\", type=\"pgbouncer-ci\", environment=\"$environment\"}[5m]\n  )\n) by (groupname, fqdn, type, stage, environment)\n,1),0)\n",
     "legendFormat": "{{ groupname }} {{ fqdn }}"
    }
   ]
  },
  { "title": "pgbouncer Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 } },
  {
   "title": "Sent Bytes",
   "type": "graph",
   "description": "Total volume in bytes of network traffic sent by pgbouncer, shown as bytes - stats.total_sent",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4001 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_sent_bytes_total{type=\"pgbouncer-ci\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "graph",
   "description": "Total volume in bytes of network traffic received by pgbouncer, shown as bytes - stats.total_received",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4001 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_received_bytes_total{type=\"pgbouncer-ci\", environment=\"$environment\"}[$__interval])) by (fqdn)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "pgbouncer Client Transaction Utilisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5000 }
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  patroni-ci\n  pgbouncer-ci\nend\n\n\n  patroni-ci --> patroni\npgbouncer-ci --> patroni-ci\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni\n  patroni-ci\n  pgbouncer-ci\nend\n\n\n  patroni-ci --> patroni\npgbouncer-ci --> patroni-ci\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  patroni-ci[\"patroni-ci (Level 2)\"]\n  patroni[\"patroni (Level 2)\"]\n  pgbouncer-ci[\"pgbouncer-ci (Level 1)\"]\nend\n\n\n  patroni-ci[\"patroni-ci (Level 2)\"] --> patroni\npgbouncer-ci[\"pgbouncer-ci (Level 1)\"] --> patroni-ci\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}