{
 "title": "plantuml: PlantUML Overview",
 "tags": [
  "managed",
  "plantuml",
  "plantuml"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info, cluster)"
   },
   {
    "name": "project_id",
    "query": "label_values(stackdriver_gke_container_logging_googleapis_com_log_entry_count, project_id)"
   }
  ]
 },
 "panels": [
  { "title": "Stackdriver Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error messages",
   "type": "graph",
   "description": "Stackdriver Errors",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"ERROR\", cluster_name=\"$cluster\", namespace_id=\"plantuml\"}) / 60",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Info messages",
   "type": "graph",
   "description": "Stackdriver Errors",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"INFO\", cluster_name=\"$cluster\", namespace_id=\"plantuml\"}) / 60",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  { "title": "Stackdriver LoadBalancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "HTTP Requests CACHE HIT",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{cache_result!=\"MISS\", project_id=\"$project_id\", forwarding_rule_name=~\".*plantuml.*\"}) by (response_code) / 60",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "HTTP Requests bytes CACHE HIT",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_request_bytes_count{cache_result!=\"MISS\", project_id=\"$project_id\", forwarding_rule_name=~\".*plantuml.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "HTTP Requests CACHE MISS",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{cache_result=\"MISS\", project_id=\"$project_id\", forwarding_rule_name=~\".*plantuml.*\"}) by (response_code) / 60",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "HTTP Requests bytes CACHE MISS",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_request_bytes_count{cache_result=\"MISS\", project_id=\"$project_id\", forwarding_rule_name=~\".*plantuml.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  }
 ]
}