{
 "title": "plantuml: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4737822408 at Tue Jul 25 15:37:33 UTC 2023",
 "tags": [
  "managed",
  "plantuml",
  "gitlab",
  "type:plantuml",
  "plantuml",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "plantuml Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "plantuml error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"plantuml\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"plantuml\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "plantuml error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"plantuml\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"plantuml\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"plantuml\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"plantuml\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"plantuml\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "plantuml Service | Errors"
    }
   ]
  },
  {
   "title": "plantuml Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}[$__interval])\n",
     "legendFormat": "plantuml RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"plantuml\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "loadbalancer SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "loadbalancer error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"plantuml\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"plantuml\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "loadbalancer error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"plantuml\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"plantuml\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"plantuml\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"plantuml\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"loadbalancer\",monitor=\"global\",type=\"plantuml\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "loadbalancer SLI | Errors"
    }
   ]
  },
  {
   "title": "loadbalancer SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"}[$__interval])\n",
     "legendFormat": "loadbalancer RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"plantuml\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Observability Tools\n\n* [Google Load Balancer](https://console.cloud.google.com/net-services/loadbalancing/details/http/k8s-um-plantuml-plantuml--58df01f69d082883?project=gitlab-production)\n* [Stackdriver Logs: Loadbalancer Access Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Eurl%5Fmap%5Fname%3D%22k8s%2Dum%2Dplantuml%2Dplantuml%2D%2D58df01f69d082883%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-production)\n* [Stackdriver Logs: Loadbalancer Access 5xx Logs](https://console.cloud.google.com/logs/query;query=httpRequest%2Estatus%3E%3D500%0Aresource%2Elabels%2Eurl%5Fmap%5Fname%3D%22k8s%2Dum%2Dplantuml%2Dplantuml%2D%2D58df01f69d082883%22%0Aresource%2Etype%3D%22http%5Fload%5Fbalancer%22;timeRange=PT30M?project=gitlab-production)\n* [Stackdriver Nginx Access Logs](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Enamespace%5Fname%3D%22plantuml%22%0Aresource%2Etype%3D%22k8s%5Fcontainer%22;timeRange=PT30M?project=gitlab-production)\n\n"
  },
  {
   "title": "🔬 SLI Detail: loadbalancer",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "loadbalancer Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",response_code_class=\"500\",url_map_name=\"k8s-um-plantuml-plantuml--58df01f69d082883\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "loadbalancer RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",url_map_name=\"k8s-um-plantuml-plantuml--58df01f69d082883\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "loadbalancer Errors - per proxy_continent",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy_continent) (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",proxy_continent!=\"\",response_code_class=\"500\",url_map_name=\"k8s-um-plantuml-plantuml--58df01f69d082883\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{proxy_continent}}"
      }
     ]
    },
    {
     "title": "loadbalancer RPS - per proxy_continent",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (proxy_continent) (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",proxy_continent!=\"\",url_map_name=\"k8s-um-plantuml-plantuml--58df01f69d082883\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{proxy_continent}}"
      }
     ]
    },
    {
     "title": "loadbalancer Errors - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",response_code!=\"\",response_code_class=\"500\",url_map_name=\"k8s-um-plantuml-plantuml--58df01f69d082883\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    },
    {
     "title": "loadbalancer RPS - per response_code",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (response_code) (\n  rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{env=\"$environment\",environment=\"$environment\",project_id=\"gitlab-production\",response_code!=\"\",url_map_name=\"k8s-um-plantuml-plantuml--58df01f69d082883\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{response_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true,
   "panels": [
    {
     "title": "plantuml Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      deployment=\"plantuml\",env=\"$environment\",environment=\"$environment\",type=\"plantuml\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "plantuml Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    deployment=\"plantuml\",env=\"$environment\",environment=\"$environment\",type=\"plantuml\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "plantuml Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"plantuml\",env=\"$environment\",environment=\"$environment\",type=\"plantuml\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"plantuml\",env=\"$environment\",environment=\"$environment\",type=\"plantuml\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. When this is exhausted, the container may be thottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"plantuml\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"plantuml\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"plantuml\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_memory component saturation: Kube Container Memory Utilization",
     "type": "graph",
     "description": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      container_memory_working_set_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"plantuml\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"plantuml\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"kube_container_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_horizontalpodautoscaler_desired_replicas component saturation: Horizontal Pod Autoscaler Desired Replicas",
     "type": "graph",
     "description": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, horizontalpodautoscaler, shard) (\n  clamp_min(\n    clamp_max(\n      kube_horizontalpodautoscaler_status_desired_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects|urgent-other\", namespace!~\"pubsubbeat\"}\n      /\n      kube_horizontalpodautoscaler_spec_max_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects|urgent-other\", namespace!~\"pubsubbeat\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ horizontalpodautoscaler }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",type=\"plantuml\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"plantuml\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",type=\"plantuml\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"plantuml\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"plantuml\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  { "title": "Stackdriver Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Error messages",
   "type": "graph",
   "description": "Stackdriver Errors",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"ERROR\", namespace_id=\"plantuml\"}) by (cluster, container) / 60",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Info messages",
   "type": "graph",
   "description": "Stackdriver Errors",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"INFO\", namespace_id=\"plantuml\"}) by (cluster, container) / 60",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "Stackdriver LoadBalancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "HTTP Requests CACHE HIT",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{cache_result!=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*plantuml.*\"}) by (response_code) / 60",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "HTTP Requests bytes CACHE HIT",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_request_bytes_count{cache_result!=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*plantuml.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "HTTP Requests CACHE MISS",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*plantuml.*\"}) by (response_code) / 60",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "HTTP Requests bytes CACHE MISS",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2011 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_request_bytes_count{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*plantuml.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "Stackdriver LoadBalancer Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 }
  },
  {
   "title": "90th Percentile Latency CACHE MISS",
   "type": "graph",
   "description": "90th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*plantuml.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "60th Percentile Latency CACHE MISS",
   "type": "graph",
   "description": "60th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.6,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*plantuml.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "90th Percentile Latency CACHE HIT",
   "type": "graph",
   "description": "90th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"HIT\", environment=\"$environment\", forwarding_rule_name=~\".*plantuml.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "60th Percentile Latency CACHE HIT",
   "type": "graph",
   "description": "60th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.6,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"HIT\", environment=\"$environment\", forwarding_rule_name=~\".*plantuml.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph sv\n  plantuml\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph sv\n  plantuml\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph sv\n  plantuml[\"plantuml (Level 1)\"]\nend\n\n\n  \n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}