{
 "title": "plantuml: Capacity Review",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4727686289 at Mon Jul 24 11:58:19 UTC 2023",
 "tags": [
  "managed",
  "plantuml",
  "plantuml",
  "type:plantuml",
  "capacity-review"
 ],
 "time": { "from": "now-15d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "open_fds: Open file descriptor utilization per instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(2)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"open_fds\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"plantuml\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"open_fds\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"plantuml\"}\n"
    }
   ]
  },
  {
   "title": "Open file descriptor utilization per instance",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"open_fds\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"open_fds\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"open_fds\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 2 },
   "content": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n"
  },
  {
   "title": "kube_horizontalpodautoscaler_desired_replicas: Horizontal Pod Autoscaler Desired Replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_horizontalpodautoscaler_desired_replicas\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"plantuml\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_horizontalpodautoscaler_desired_replicas\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"plantuml\"}\n"
    }
   ]
  },
  {
   "title": "Horizontal Pod Autoscaler Desired Replicas",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 102 },
   "content": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n"
  },
  {
   "title": "kube_container_cpu: Kube Container CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"plantuml\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"plantuml\"}\n"
    }
   ]
  },
  {
   "title": "Kube Container CPU Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"kube_container_cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"kube_container_cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"kube_container_cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 202 },
   "content": "Kubernetes containers are allocated a share of CPU. When this is exhausted, the container may be thottled.\n"
  },
  {
   "title": "kube_container_memory: Kube Container Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_memory\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"plantuml\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_memory\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"plantuml\"}\n"
    }
   ]
  },
  {
   "title": "Kube Container Memory Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 302 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"kube_container_memory\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"kube_container_memory\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"plantuml\", component=\"kube_container_memory\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 302 },
   "content": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}