{
 "title": "Platform Triage",
 "tags": [ "general" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "\n      sort(\n        sum(\n          ALERTS{environment=\"$environment\", type!=\"\", severity=\"critical\", alertstate=\"firing\"} * 10000\n          or\n          ALERTS{environment=\"$environment\", type!=\"\", severity=\"error\", alertstate=\"firing\"} * 100\n          or\n          ALERTS{environment=\"$environment\", type!=\"\", severity=\"warn\", alertstate=\"firing\"}\n        ) by (type)\n      )\n      "
    }
   ]
  },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "\n      clamp_min(\n        avg(\n          gitlab_service_apdex:ratio{environment=\"$environment\", stage=\"$stage\"}\n        ) by (type),\n        0.85\n      )\n      ",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "\n      clamp_min(\n        avg(\n            gitlab_service_apdex:ratio{environment=\"$environment\", stage=\"$stage\"}\n        ) by (type)\n        <= on(type) group_left\n        avg(slo:min:gitlab_service_apdex:ratio) by (type),\n        0.85\n      )\n      ",
     "legendFormat": "{{ type }} SLO violation"
    }
   ]
  },
  {
   "title": "Anomaly detection: Latency: Apdex Score",
   "type": "graph",
   "description": "Each timeseries represents the distance, in standard deviations, that each service is away from its normal range. The further from zero, the more anomalous",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Sigma σ" }
   ],
   "targets": [
    {
     "expr": "\n      clamp_min(\n        clamp_max(\n          avg(\n                \n      (\n        gitlab_service_apdex:ratio{environment=\"$environment\", stage=\"$stage\"}\n        - gitlab_service_apdex:ratio:avg_over_time_1w{environment=\"$environment\", stage=\"$stage\"}\n      )\n      /\n      gitlab_service_apdex:ratio:stddev_over_time_1w{environment=\"$environment\", stage=\"$stage\"}\n  \n            ) by (type),\n          0.5),\n        -12)\n      ",
     "legendFormat": "{{ type }} service"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "\n      clamp_max(\n        avg(\n          max_over_time(\n            gitlab_service_errors:ratio{environment=\"$environment\", stage=\"$stage\"}[$__interval]\n          )\n        ) by (type),\n        0.15\n      )\n      ",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "\n      clamp_max(\n        avg(\n          gitlab_service_errors:ratio{environment=\"$environment\", stage=\"$stage\"}\n        ) by (type)\n        >= on(type) group_left\n        avg(slo:max:gitlab_service_errors:ratio) by (type),\n        0.15\n      )\n      ",
     "legendFormat": "{{ type }} SLO violation"
    }
   ]
  },
  {
   "title": "Anomaly detection: Error Ratio",
   "type": "graph",
   "description": "Each timeseries represents the distance, in standard deviations, that each service is away from its normal range. The further from zero, the more anomalous",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Sigma σ" }
   ],
   "targets": [
    {
     "expr": "\n      clamp_min(\n        clamp_max(\n          avg(\n                \n      (\n        gitlab_service_errors:ratio{environment=\"$environment\", stage=\"$stage\"}\n        - gitlab_service_errors:ratio:avg_over_time_1w{environment=\"$environment\", stage=\"$stage\"}\n      )\n      /\n      gitlab_service_errors:ratio:stddev_over_time_1w{environment=\"$environment\", stage=\"$stage\"}\n  \n            ) by (type),\n          12),\n        -0.5)\n      ",
     "legendFormat": "{{ type }} service"
    }
   ]
  },
  {
   "title": "Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "\n      sum(\n        gitlab_service_ops:rate{environment=\"$environment\", stage=\"$stage\"}\n      ) by (type)\n      ",
     "legendFormat": "{{ type }} service"
    }
   ]
  },
  {
   "title": "Anomaly detection: Requests per second",
   "type": "graph",
   "description": "Each timeseries represents the distance, in standard deviations, that each service is away from its normal range. The further from zero, the more anomalous",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Sigma σ" }
   ],
   "targets": [
    {
     "expr": "\n      clamp_min(\n        clamp_max(\n          avg(\n                \n      (\n        gitlab_service_ops:rate{environment=\"$environment\", stage=\"$stage\"}\n        -\n        gitlab_service_ops:rate:prediction{environment=\"$environment\", stage=\"$stage\"}\n      )\n      /\n      gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", stage=\"$stage\"}\n  \n            ) by (type),\n          6),\n        -3)\n      ",
     "legendFormat": "{{ type }} service"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "graph",
   "description": "Availability measures the ratio of component processes in the service that are currently healthy and able to handle requests. The closer to 100% the better.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability %" }
   ],
   "targets": [
    {
     "expr": "\n      min(\n        min_over_time(\n          gitlab_service_availability:ratio{environment=\"$environment\", stage=\"$stage\"}[$__interval]\n        )\n      ) by (type)\n      ",
     "legendFormat": "{{ type }} service"
    }
   ]
  },
  {
   "title": "Anomaly detection: Availability",
   "type": "graph",
   "description": "Each timeseries represents the distance, in standard deviations, that each service is away from its normal range. The further from zero, the more anomalous",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Sigma σ" }
   ],
   "targets": [
    {
     "expr": "\n      clamp_min(\n        clamp_max(\n          avg(\n                \n      (\n      gitlab_service_availability:ratio{environment=\"$environment\", stage=\"$stage\"}\n      -\n      gitlab_service_availability:ratio:avg_over_time_1w{environment=\"$environment\", stage=\"$stage\"}\n      )\n      /\n      gitlab_service_availability:ratio:stddev_over_time_1w{environment=\"$environment\", stage=\"$stage\"}\n  \n            ) by (type),\n          0.5),\n        -12)\n      ",
     "legendFormat": "{{ type }} service"
    }
   ]
  }
 ]
}