{
 "title": "PostgreSQL Tuple Statistics",
 "tags": [
  "postgresql",
  "unmanaged"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(pg_stat_database_tup_deleted, env)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_stat_database_tup_deleted{env=\"$env\"}, fqdn)"
    }
   },
   {
    "name": "db",
    "label": "db",
    "query": {
     "query": "label_values(pg_stat_database_tup_deleted{env=\"$env\",fqdn=\"$instance\"}, datname)"
    }
   },
   {
    "name": "top_dead_tup",
    "label": "top_dead_tup",
    "query": {
     "query": "query_result(topk(20, max_over_time(pg_stat_user_tables_n_dead_tup{env=\"gprd\",fqdn=\"$instance\",datname=\"$db\"}[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tuple Operations Per Host",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_deleted{env=\"$env\",fqdn=\"$instance\",datname=\"$db\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deletes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{env=\"$env\",fqdn=\"$instance\",datname=\"$db\"}[$__interval])",
     "legendFormat": "Inserts"
    },
    {
     "expr": "rate(pg_stat_database_tup_fetched{env=\"$env\",fqdn=\"$instance\",datname=\"$db\"}[$__interval])",
     "legendFormat": "Rows Read"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{env=\"$env\",fqdn=\"$instance\",datname=\"$db\"}[$__interval])",
     "legendFormat": "Updates"
    }
   ]
  },
  {
   "title": "Tuple Writes Per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_deleted{env=\"$env\",fqdn=\"$instance\",datname=\"$db\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deletes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{env=\"$env\",fqdn=\"$instance\",datname=\"$db\"}[$__interval])",
     "legendFormat": "Inserts"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{env=\"$env\",fqdn=\"$instance\",datname=\"$db\"}[$__interval])",
     "legendFormat": "Updates"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sequential Reads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_tup_read{env=\"$env\",fqdn=\"$instance\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{relname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index Reads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_idx_tup_fetch{env=\"$env\",fqdn=\"$instance\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{relname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index Tuple Reads",
   "type": "graph",
   "description": "Number of index entries returned by scans on this index",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_read{env=\"$env\",fqdn=\"$instance\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{relname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inserts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops", "label": "Amount" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins{env=\"$env\",fqdn=\"$instance\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{relname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Updates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Updates",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops", "label": "Amount" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_user_tables_n_tup_upd{fqdn=\"$instance\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HOT Updates",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ops", "label": "Amount" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_user_tables_n_tup_hot_upd{fqdn=\"$instance\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Deletes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Deletes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops", "label": "Amount" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_user_tables_n_tup_del{fqdn=\"$instance\"}[5m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{relname}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Dead Tuples (top 15)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dead Tuple Rates",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_dead_tup{env=\"$env\",fqdn=\"$instance\",datname=\"$db\",relname=~\"$top_dead_tup\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{relname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Dead Tuples",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{env=\"$env\",fqdn=\"$instance\",datname=\"$db\",relname=~\"$top_dead_tup\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{relname}} - {{schemaname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dead Tuples Percentage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(pg_stat_user_tables_n_dead_tup{env=\"$env\",fqdn=\"$instance\",datname=\"$db\",relname=~\"$top_dead_tup\"}) \n/ \n(pg_stat_user_tables_n_live_tup{env=\"$env\",fqdn=\"$instance\",datname=\"$db\",relname=~\"$top_dead_tup\"} + pg_stat_user_tables_n_dead_tup{env=\"$env\",fqdn=\"$instance\",datname=\"$db\",relname=~\"$top_dead_tup\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{relname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vacuuming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Autovacuum Per Table",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_autovacuum_count{fqdn=\"$instance\"}[1h])*60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{relname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Autovacuum ANALYZE Per Table",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_autoanalyze_count{fqdn=\"$instance\"}[60m])*60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{relname}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}