{
 "title": "PostgreSQL Bloat",
 "tags": [
  "postgresql",
  "unmanaged"
 ],
 "time": { "from": "now-9d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(gitlab_database_bloat_btree_bloat_size{environment=\"$environment\"},fqdn)"
    }
   },
   {
    "name": "index",
    "label": "Index",
    "query": {
     "query": "label_values(gitlab_database_bloat_btree_bloat_size{environment=\"$environment\"},query_name)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(gitlab_database_bloat_table_bloat_size{environment=\"$environment\"},query_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bloat ratios (total)",
   "type": "graph",
   "description": "This is based on gitlab-monitor and a live estimation of the database bloat (without an error bound)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(gitlab_database_bloat_table_bloat_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\"}[$__interval]))\n/ sum(avg_over_time(gitlab_database_bloat_table_real_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Table bloat in % of real size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(avg_over_time(gitlab_database_bloat_btree_bloat_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\"}[$__interval]))\n/ sum(avg_over_time(gitlab_database_bloat_btree_real_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\"}[$__interval]))",
     "legendFormat": "Index bloat in % of real size"
    }
   ]
  },
  {
   "title": "Bloat size (total, estimation)",
   "type": "graph",
   "description": "This is based on gitlab-monitor and a live estimation of the database bloat (without an error bound)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(gitlab_database_bloat_table_bloat_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Overall bloat size (tables)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(avg_over_time(gitlab_database_bloat_btree_bloat_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\"}[$__interval]))",
     "legendFormat": "Overall bloat size (indexes)"
    }
   ]
  },
  {
   "title": "Bloat statistics for selected Table",
   "type": "graph",
   "description": "This is based on gitlab-monitor and a live estimation of the database bloat (without an error bound)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_database_bloat_table_bloat_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\", query_name=\"$table\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bloat size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(gitlab_database_bloat_table_bloat_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\", query_name=\"$table\"}[$__interval])\n/ avg_over_time(gitlab_database_bloat_table_real_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\", query_name=\"$table\"}[$__interval])",
     "legendFormat": "Bloat in % of real size"
    },
    {
     "expr": "avg_over_time(gitlab_database_bloat_table_real_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\", query_name=\"$table\"}[$__interval])",
     "legendFormat": "Real size"
    }
   ]
  },
  {
   "title": "Bloat statistics for selected Index",
   "type": "graph",
   "description": "This is based on gitlab-monitor and a live estimation of the database bloat (without an error bound)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_database_bloat_btree_bloat_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\", query_name=\"$index\"}[$__interval])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bloat size",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(gitlab_database_bloat_btree_bloat_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\", query_name=\"$index\"}[$__interval])\n/ avg_over_time(gitlab_database_bloat_btree_real_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\", query_name=\"$index\"}[$__interval])",
     "legendFormat": "Bloat in % of real size"
    },
    {
     "expr": "avg_over_time(gitlab_database_bloat_btree_real_size{monitor=\"db\",env=\"$environment\", fqdn=\"$instance\", query_name=\"$index\"}[$__interval])",
     "legendFormat": "Real size"
    }
   ]
  },
  {
   "title": "Site overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Locks across all Patroni hosts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_locks_count{environment=\"$environment\", type=\"patroni\"}) by (mode)",
     "legendFormat": "Number of  {{mode}} locks"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "ops", "label": "Committed" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"gitlabhq_production\", monitor=\"db\",env=\"$environment\", tier=\"db\", type=\"patroni\"}[$__interval])",
     "legendFormat": "{{fqdn}} committed"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"gitlabhq_production\", monitor=\"db\",env=\"$environment\", tier=\"db\", type=\"patroni\"}[$__interval])",
     "legendFormat": "{{fqdn}} rolled back"
    }
   ]
  },
  {
   "title": "Replication lag (patroni nodes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(postgres:pg_replication_lag_bytes{monitor=\"db\",env=\"$environment\", type=\"patroni\"}[$__interval]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(avg_over_time(postgres:pg_replication_lag_bytes{monitor=\"db\",env=\"$environment\", type=\"patroni\"}[$__interval]))",
     "legendFormat": "Max"
    },
    {
     "expr": "min(avg_over_time(postgres:pg_replication_lag_bytes{monitor=\"db\",env=\"$environment\", type=\"patroni\"}[$__interval]))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Slow Queries Count (> 1 second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Committed" }
   ],
   "targets": [
    {
     "expr": "pg_slow_queries{monitor=\"db\",env=\"$environment\", tier=\"db\", type=\"patroni\"}"
    }
   ]
  },
  {
   "title": "SQL Timings rails [production only]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"sql_duration_95th\" AS \"95th Percentile\", \"sql_duration_99th\" as \"99th Percentile\", \"sql_duration_mean\" AS \"Mean\" FROM downsampled.\"rails_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile(0.95, quantile_over_time(0.95, job_environment:gitlab_sql_duration_seconds:p95{monitor=\"app\",env=\"$environment\"}[$__interval]))",
     "legendFormat": "95th"
    },
    {
     "expr": "quantile(0.99, quantile_over_time(0.99, job_environment:gitlab_sql_duration_seconds:p99{monitor=\"app\",env=\"$environment\"}[$__interval]))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(\n  0.50, \n  sum by (le) (\n    avg_over_time(job_environment:gitlab_sql_duration_seconds_bucket:rate1m{monitor=\"app\",env=\"$environment\"}[$__interval])\n  )\n) > 0",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "5xx responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(backend_code:haproxy_server_http_responses_total:irate1m{code=\"5xx\"}[$__interval])) by (backend)",
     "legendFormat": "haproxy 5xx {{ backend }}"
    },
    {
     "expr": "sum without (zone) (avg_over_time(zone:stackdriver_haproxy_errors:rate1m[$__interval]))",
     "legendFormat": "SD haproxy {{code}}"
    },
    {
     "expr": "sum without (zone) (zone:stackdriver_haproxy_deadline_exceeded:rate1m)",
     "legendFormat": "SD haproxy timeout"
    }
   ]
  },
  {
   "title": "Performed Checkpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoints_req{env=\"$environment\", tier=\"db\", type=\"patroni\"}[$__interval])*60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} - requested",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoints_timed{env=\"$environment\", tier=\"db\", type=\"patroni\"}[$__interval])*60",
     "legendFormat": "{{fqdn}} - scheduled"
    }
   ]
  }
 ]
}