{
 "title": "Postgres 14 upgrade (Nik, tmp) – MAIN cluster",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(prometheus_build_info, env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "🏃🏻‍♀️ Logical replication lag (all slots in env)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(pg_replication_slots_confirmed_flush_lsn_bytes{env=\"$env\", type=\"patroni\", slot_type=\"logical\"}) by (fqdn, slot_type, slot_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TPS (commits)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "🏹 🥇 Source leader TPS (commits) ✅",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$env\", fqdn=~\"patroni-main-2004-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯 🥇 Target leader TPS (commits) ✅",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$env\", fqdn=~\"patroni-main-v14-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🏹 👥 Source standbys TPS (commits) ✅",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$env\", fqdn=~\"patroni-main-2004-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯 👥 Target standbys TPS (commits) ✅",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$env\", fqdn=~\"patroni-main-v14-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TPS rollbacks – ERROR RATES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "🏹 🥇 Source leader rollback TPS – ERRORS ❌",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$env\", fqdn=~\"patroni-main-2004-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯 🥇 Target leader rollback TPS – ERRORS ❌",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$env\", fqdn=~\"patroni-main-v14-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🏹 👥 Source standbys roolback TPS – ERRORS ❌",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$env\", fqdn=~\"patroni-main-2004-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯 👥 Target standbys rollback TPS – ERRORS ❌",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$env\", fqdn=~\"patroni-main-v14-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuple stats: ins/upd/del, index fetches, seq reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "🏹 Source writes (tuple ins/upd/del)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(pg_stat_user_tables_n_tup_ins{env=\"$env\",fqdn=~\"patroni-main-2004-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_del{env=\"$env\",fqdn=~\"patroni-main-2004-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_upd{env=\"$env\",fqdn=~\"patroni-main-2004-.*\"}[1m])) by (instance)\nand on(instance) pg_replication_is_replica==0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🎯 Target writes (tuple ins/upd/del)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(pg_stat_user_tables_n_tup_ins{env=\"$env\",fqdn=~\"patroni-main-v14-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_del{env=\"$env\",fqdn=~\"patroni-main-v14-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_upd{env=\"$env\",fqdn=~\"patroni-main-v14-.*\"}[1m])) by (instance)\nand on(instance) pg_replication_is_replica==0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🏹 Source index tuple fetches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_idx_tup_fetch{env=\"$env\", instance=~\"(patroni-main-2004-.*)\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🎯 Target index tuple fetches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_idx_tup_fetch{env=\"$env\", instance=~\"(patroni-main-v14-.*)\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🏹 Source seq tuple reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_seq_tup_read{env=\"$env\", instance=~\"(patroni-main-2004-.*)\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🎯 Target seq tuple reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_seq_tup_read{env=\"$env\", instance=~\"(patroni-main-v14-.*)\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Backups (TODO, WIP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "🏹 Source WALs archived",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "WALs/s" } },
   "targets": [
    {
     "expr": "sum(rate(walg_backup_completed_count{env=\"$env\", fqdn=~\"patroni-main-2004-.*\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯 Target WALs archived",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "WALs/s" } },
   "targets": [
    {
     "expr": "sum(rate(walg_backup_completed_count{env=\"$env\", fqdn=~\"patroni-main-v14-.*\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}