{
 "title": "postgresql: Postgres upgrade using logical",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7622137885 at Tue Aug 20 13:30:49 UTC 2024",
 "tags": [
  "managed",
  "postgresql",
  "postgresql"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(pg_settings_server_version_num, fqdn)"
   },
   {
    "name": "source_version",
    "query": "query_result(min by(__name__) (pg_settings_server_version_num{fqdn=~\"patroni-main.*\"}))"
   },
   {
    "name": "destination_version",
    "query": "label_values(pg_settings_server_version_num{fqdn=~\"patroni-${cluster}.*\"}, fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Context",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "content": "# **$environment** **$cluster** **source_version**"
  },
  {
   "title": "Cluster on the left",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "content": "🏹 Source cluster: PG${source_version}, Ubuntu 20.04"
  },
  {
   "title": "Logical replication lag (all slots in $environment)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(pg_replication_slots_confirmed_flush_lsn_bytes{env=\"$environment\", slot_type=\"logical\"}) by (fqdn, slot_type, slot_name)\n"
    }
   ]
  },
  {
   "title": "Useful links",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "content": "\n- [Ansible playbooks](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/tree/master/pg-upgrade-logical)\n- [Inventory in Ansible](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/tree/master/pg-upgrade-logical/inventory)\n- [CR template](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/blob/master/.gitlab/issue_templates/pg14_upgrade.md) (individual CRs are to be located at ops.gitlab.net)\n- [Diagram illustrating the process](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/blob/master/.gitlab/issue_templates/pg14_upgrade.md#high-level-overview)\n    "
  },
  {
   "title": "Cluster on the right",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "content": "🎯 Target cluster: PG${destination_version} "
  },
  {
   "title": "Physical lags",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "🏹 🏃🏻‍♀️ Physical replication lag on source standbys, in seconds",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum(pg_replication_lag{env=\"$environment\", fqdn=~\"(patroni-${cluster}-v${source_version}|patroni-${cluster}-[0-9]+).*\"}) by (fqdn)\n"
      }
     ]
    },
    {
     "title": "🎯 🏃🏻‍♀️ Physical replication lag on target standbys, in seconds",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "seconds" }
     ],
     "targets": [
      {
       "expr": "sum(pg_replication_lag{env=\"$environment\", fqdn=~\"patroni-${cluster}-v${destination_version}-.*\"}) by (fqdn)\n"
      }
     ]
    },
    {
     "title": "🏹 🏃🏻‍♀️ Physical replication lag on source standbys, in bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(postgres:pg_replication_lag_bytes{env=\"$environment\", fqdn=~\"(patroni-${cluster}-v${source_version}|patroni-${cluster}-[0-9]+).*\"}) by (fqdn)\n"
      }
     ]
    },
    {
     "title": "🎯 🏃🏻‍♀️ Physical replication lag on target standbys, in bytes",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(postgres:pg_replication_lag_bytes{env=\"$environment\", fqdn=~\"patroni-${cluster}-v${destination_version}-.*\"}) by (fqdn)\n"
      }
     ]
    }
   ]
  },
  {
   "title": "TPS (commits)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "🏹 🥇 Source leader TPS (commits) ✅",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$environment\", fqdn=~\"(patroni-${cluster}-v${source_version}|patroni-${cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🎯 🥇 Target leader TPS (commits) ✅",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$environment\", fqdn=~\"patroni-${cluster}-v${destination_version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🏹 👥 Source standbys TPS (commits) ✅",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$environment\", fqdn=~\"(patroni-${cluster}-v${source_version}|patroni-${cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🎯 👥 Target standbys TPS (commits) ✅",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops/sec" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$environment\", fqdn=~\"patroni-${cluster}-v${destination_version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    }
   ]
  },
  {
   "title": "TPS rollbacks – ERROR RATES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "🏹 🥇 Source leader rollback TPS – ERRORS ❌",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "err/s" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$environment\", fqdn=~\"(patroni-${cluster}-v${source_version}|patroni-${cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🎯 🥇 Target leader rollback TPS – ERRORS ❌",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "err/s" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$environment\", fqdn=~\"patroni-${cluster}-v${destination_version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🏹 👥 Source standbys roolback TPS – ERRORS ❌",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "err/s" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$environment\", fqdn=~\"(patroni-${cluster}-v${source_version}|patroni-${cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🎯 👥 Target standbys rollback TPS – ERRORS ❌",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "err/s" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$environment\", fqdn=~\"patroni-${cluster}-v${destination_version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Tuple stats: ins/upd/del, index fetches, seq reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "🏹 Source writes (tuple ins/upd/del)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(pg_stat_user_tables_n_tup_ins{env=\"$environment\", fqdn=~\"(patroni-${cluster}-v${source_version}|patroni-${cluster}-[0-9]+).*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_del{env=\"$environment\", fqdn=~\"(patroni-${cluster}-v${source_version}|patroni-${cluster}-[0-9]+).*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_upd{env=\"$environment\", fqdn=~\"(patroni-${cluster}-v${source_version}|patroni-${cluster}-[0-9]+).*\"}[1m])) by (instance)\nand on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🎯 Target writes (tuple ins/upd/del)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(pg_stat_user_tables_n_tup_ins{env=\"$environment\", fqdn=~\"patroni-${cluster}-v${destination_version}-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_del{env=\"$environment\", fqdn=~\"patroni-${cluster}-v${destination_version}-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_upd{env=\"$environment\", fqdn=~\"patroni-${cluster}-v${destination_version}-.*\"}[1m])) by (instance)\nand on(instance) pg_replication_is_replica==0\n"
      }
     ]
    },
    {
     "title": "🏹 Source index tuple fetches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_idx_tup_fetch{env=\"$environment\", fqdn=~\"(patroni-${cluster}-v${source_version}|patroni-${cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🎯 Target index tuple fetches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_idx_tup_fetch{env=\"$environment\", fqdn=~\"patroni-${cluster}-v${destination_version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🏹 Source seq tuple reads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_seq_tup_read{env=\"$environment\", fqdn=~\"(patroni-${cluster}-v${source_version}|patroni-${cluster}-[0-9]+).*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    },
    {
     "title": "🎯 Target seq tuple reads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ops/s" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_seq_tup_read{env=\"$environment\", fqdn=~\"patroni-${cluster}-v${destination_version}-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1\n"
      }
     ]
    }
   ]
  }
 ]
}