{
 "title": "Postgres IO",
 "tags": [
  "postgresql",
  "unmanaged"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(up{tier=\"db\"},environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "query IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=~\"pg.query.*\"}[$__interval])",
     "legendFormat": "read_bytes.{{fqdn}}.{{groupname}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=~\"pg.query.*\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}.{{groupname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Write IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=~\"pg.checkpointer\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  },
  {
   "title": "wal receiver IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=\"pg.wal receiver\"}[$__interval])",
     "legendFormat": "read_bytes.{{fqdn}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=\"pg.wal receiver\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  },
  {
   "title": "autovacumm IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=\"pg.autovacuum worker\"}[1m])",
     "legendFormat": "read_bytes.{{fqdn}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=\"pg.autovacuum worker\"}[1m])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  },
  {
   "title": "wal sender IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=\"pg.wal sender\"}[$__interval])",
     "legendFormat": "read_bytes.{{fqdn}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=\"pg.wal sender\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  },
  {
   "title": "bgwriter IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=\"pg.writer\"}[$__interval])",
     "legendFormat": "read_bytes.{{fqdn}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=\"pg.writer\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  },
  {
   "title": "Stat collector IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{environment=\"$environment\",groupname=\"pg.stats collector\"}[$__interval])",
     "legendFormat": "read_bytes.{{fqdn}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{environment=\"$environment\",groupname=\"pg.stats collector\"}[$__interval])",
     "legendFormat": "write_bytes.{{fqdn}}"
    }
   ]
  }
 ]
}