{
 "title": "Postgres 14 upgrade using logical (all envs, all clusters)   (Nik, tmp)",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "label_values(prometheus_build_info, env)"
    }
   },
   { "name": "cluster", "query": "main,ci,registry" }
  ]
 },
 "panels": [
  { "title": "Context", "type": "text", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 }, "options": { "content": "#  **$env** **$cluster**" } },
  {
   "title": "🏃🏻‍♀️ Logical replication lag (all slots in $env)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(pg_replication_slots_confirmed_flush_lsn_bytes{env=\"$env\", slot_type=\"logical\"}) by (fqdn, slot_type, slot_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Useful links",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "- [Ansible playbooks](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/tree/master/pg-upgrade-logical)\n- [Inventory in Ansible](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/tree/master/pg-upgrade-logical/inventory)\n- [CR template](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/blob/master/.gitlab/issue_templates/pg14_upgrade.md) (individual CRs are to be located at ops.gitlab.net)\n- [Diagram illustrating the process](https://gitlab.com/gitlab-com/gl-infra/db-migration/-/blob/master/.gitlab/issue_templates/pg14_upgrade.md#high-level-overview)"
   }
  },
  {
   "title": "Cluster on the left",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "options": {
    "content": "🏹 Source cluster: PG12, Ubuntu 20.04 (prefixes contain hard-coded `v12` and/or `2004`)"
   }
  },
  {
   "title": "Cluster on the right",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "options": {
    "content": "🎯 Target cluster: PG14 (prefixes contain hard-coded `v14`)"
   }
  },
  { "title": "TPS (commits)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "🏹 🥇 Source leader TPS (commits) ✅",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$env\", fqdn=~\"(patroni-${cluster}-2004|patroni-v12-${cluster})-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯 🥇 Target leader TPS (commits) ✅",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$env\", fqdn=~\"patroni-${cluster}-v14-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🏹 👥 Source standbys TPS (commits) ✅",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$env\", fqdn=~\"(patroni-${cluster}-2004|patroni-v12-${cluster})-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯 👥 Target standbys TPS (commits) ✅",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_commit{env=\"$env\", fqdn=~\"patroni-${cluster}-v14-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TPS rollbacks – ERROR RATES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "🏹 🥇 Source leader rollback TPS – ERRORS ❌",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$env\", fqdn=~\"(patroni-${cluster}-2004|patroni-v12-${cluster})-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯 🥇 Target leader rollback TPS – ERRORS ❌",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$env\", fqdn=~\"patroni-${cluster}-v14-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🏹 👥 Source standbys roolback TPS – ERRORS ❌",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$env\", fqdn=~\"(patroni-${cluster}-2004|patroni-v12-${cluster})-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯 👥 Target standbys rollback TPS – ERRORS ❌",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "(sum(irate(pg_stat_database_xact_rollback{env=\"$env\", fqdn=~\"patroni-${cluster}-v14-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuple stats: ins/upd/del, index fetches, seq reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "🏹 Source writes (tuple ins/upd/del)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(pg_stat_user_tables_n_tup_ins{env=\"$env\", fqdn=~\"(patroni-${cluster}-2004|patroni-v12-${cluster})-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_del{env=\"$env\", fqdn=~\"(patroni-${cluster}-2004|patroni-v12-${cluster})-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_upd{env=\"$env\", fqdn=~\"(patroni-${cluster}-2004|patroni-v12-${cluster})-.*\"}[1m])) by (instance)\nand on(instance) pg_replication_is_replica==0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🎯 Target writes (tuple ins/upd/del)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(pg_stat_user_tables_n_tup_ins{env=\"$env\", fqdn=~\"patroni-${cluster}-v14-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_del{env=\"$env\", fqdn=~\"patroni-${cluster}-v14-.*\"}[1m])\n+\nirate(pg_stat_user_tables_n_tup_upd{env=\"$env\", fqdn=~\"patroni-${cluster}-v14-.*\"}[1m])) by (instance)\nand on(instance) pg_replication_is_replica==0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🏹 Source index tuple fetches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_idx_tup_fetch{env=\"$env\", fqdn=~\"(patroni-${cluster}-2004|patroni-v12-${cluster})-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🎯 Target index tuple fetches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_idx_tup_fetch{env=\"$env\", fqdn=~\"patroni-${cluster}-v14-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🏹 Source seq tuple reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_seq_tup_read{env=\"$env\", fqdn=~\"(patroni-${cluster}-2004|patroni-v12-${cluster})-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "🎯 Target seq tuple reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "(sum(rate(pg_stat_user_tables_seq_tup_read{env=\"$env\", fqdn=~\"patroni-${cluster}-v14-.*\"}[1m])) by (instance)) and on(instance) pg_replication_is_replica==1",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups (daily full backups and continuous WAL archiving)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "🏹 Source WALs archived",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "WALs/s" } },
   "targets": [
    {
     "expr": "sum(rate(walg_backup_completed_count{env=\"$env\", fqdn=~\"(patroni-${cluster}-2004|patroni-v12-${cluster})-.*\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯 Target WALs archived",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "WALs/s" } },
   "targets": [
    {
     "expr": "sum(rate(walg_backup_completed_count{env=\"$env\", fqdn=~\"patroni-${cluster}-v14-.*\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🏹 Source full backups (chat at least 2 days)",
   "type": "timeseries",
   "description": "IMPORTANT: look at least 2 day interval. If you see 2 rows, then a gap, then another 2 rows, then you have a recent (< 24 hours) successful backup. The gap is the period of time when the backups were executing. You can use a timestamp converter https://www.epochconverter.com/ to convert the timestamps into human-readable date/time if you want to check when the backup finished.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gitlab_job_success_timestamp_seconds{resource=\"walg-basebackup\", env=\"$env\", type=~\"${env}-patroni-${cluster}-(pg12|2004).*\"} > gitlab_job_start_timestamp_seconds{resource=\"walg-basebackup\", env=\"$env\", type=~\"${env}-patroni-${cluster}-(pg12|2004).*\"} and on (resource, env, type) gitlab_job_failed == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯  Target full backups (chat at least 2 days)",
   "type": "timeseries",
   "description": "IMPORTANT: look at least 2 day interval. If you see 2 rows, then a gap, then another 2 rows, then you have a recent (< 24 hours) successful backup. The gap is the period of time when the backups were executing. You can use a timestamp converter https://www.epochconverter.com/ to convert the timestamps into human-readable date/time if you want to check when the backup finished.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "WALs/s" } },
   "targets": [
    {
     "expr": "gitlab_job_success_timestamp_seconds{resource=\"walg-basebackup\", env=\"$env\", type=~\"${env}-patroni-${cluster}-(v14).*\"} > gitlab_job_start_timestamp_seconds{resource=\"walg-basebackup\", env=\"$env\", type=~\"${env}-patroni-${cluster}-(v14).*\"} and on (resource, env, type) gitlab_job_failed == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🏹 Source full backup start time",
   "type": "timeseries",
   "description": "you should be able to see an increase of the value every time the backup starts (around midnight). If the last increase was more than 24 hours ago then it means that the last backup hasn't started as it should have, and you'll need to investigate why the job failed to start.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gitlab_job_start_timestamp_seconds{resource=\"walg-basebackup\", env=\"$env\", type=~\"${env}-patroni-${cluster}-(pg12|2004).*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯  Target full backup start time",
   "type": "timeseries",
   "description": "you should be able to see an increase of the value every time the backup starts (around midnight). If the last increase was more than 24 hours ago then it means that the last backup hasn't started as it should have, and you'll need to investigate why the job failed to start.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gitlab_job_start_timestamp_seconds{resource=\"walg-basebackup\", env=\"$env\", type=~\"${env}-patroni-${cluster}-(v14).*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🏹 Source full backup failures ❌",
   "type": "timeseries",
   "description": "If the value is > 0 for any time in the past 24 hours, then you'll need to investigate why the job failed.\n\n\nThe backup job is triggered by crond (user: gitlab-psql) and any replica is eligible to run the job but it only runs on the one that acquires the consul lock.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gitlab_job_failed{resource=\"walg-basebackup\", env=\"$env\", type=~\"${env}-patroni-${cluster}-(pg12|2004).*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🎯  Target full backup failures ❌",
   "type": "timeseries",
   "description": "If the value is > 0 for any time in the past 24 hours, then you'll need to investigate why the job failed.\n\n\nThe backup job is triggered by crond (user: gitlab-psql) and any replica is eligible to run the job but it only runs on the one that acquires the consul lock.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gitlab_job_failed{resource=\"walg-basebackup\", env=\"$env\", type=~\"${env}-patroni-${cluster}-(v14).*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}