{
 "title": "PostgreSQL Query Drill-Down",
 "tags": [
  "postgresql",
  "unmanaged"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" },
   {
    "name": "fqdn",
    "query": {
     "query": "label_values(pg_stat_statements_calls{environment=\"$environment\"},fqdn)"
    }
   },
   {
    "name": "queryid",
    "query": {
     "query": "label_values(pg_stat_statements_calls{environment=\"$environment\", fqdn=\"$fqdn\"},queryid)"
    }
   },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Query Calls per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_calls{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Time seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_seconds_total{environment=\"$environment\",queryid=\"$queryid\", fqdn=\"$fqdn\"}[5m])) by(fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Time per call seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_seconds_total{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m]) / rate(pg_stat_statements_calls{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Rows (rows/s)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_rows{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Rows Processed per call",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_rows{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m]) / rate(pg_stat_statements_calls{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Read per second",
   "type": "graph",
   "description": "Data read through shared buffers (tables, indexes, etc.)",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_read{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])*8) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Read per call",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_read{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m]) * 8 / rate(pg_stat_statements_calls{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Written per second",
   "type": "graph",
   "description": "Data written through shared buffers (tables, indexes, etc.)",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_written{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])*8) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Written per call",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_written{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m]) * 8 / rate(pg_stat_statements_calls{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Dirtied per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_dirtied{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])*8) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Dirtied per call",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_dirtied{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m]) * 8 / rate(pg_stat_statements_calls{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Hits per second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_shared_blks_hit{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])*8) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Hits per call",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_shared_blks_hit{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m]) * 8 / rate(pg_stat_statements_calls{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp Blocks",
   "type": "graph",
   "description": "Data written through shared buffers (tables, indexes, etc.)",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_temp_bytes_read{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])*8) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} - Read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(pg_stat_statements_temp_bytes_written{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])*8) by (fqdn)",
     "legendFormat": "{{fqdn}} - Written"
    }
   ]
  },
  {
   "title": "Temp Blocks per Call",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_temp_blks_read{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])*8 / rate(pg_stat_statements_calls{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}} - Read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rate(pg_stat_statements_temp_blks_written{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])*8 / rate(pg_stat_statements_calls{environment=\"$environment\",queryid=\"$queryid\",fqdn=~\"$fqdn\"}[5m])",
     "legendFormat": "{{fqdn}} - Written"
    }
   ]
  }
 ]
}