{
 "title": "Postgres table stats",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_stat_database_tup_deleted{environment=\"$environment\"},fqdn)"
    }
   },
   { "name": "tablename", "query": "project_mirror_data" }
  ]
 },
 "panels": [
  {
   "title": "Dead vs. Live Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{fqdn=\"$instance\",relname=\"$tablename\"}",
     "legendFormat": "dead tuples"
    },
    {
     "expr": "pg_stat_user_tables_n_live_tup{fqdn=\"$instance\",relname=\"$tablename\"}",
     "legendFormat": "live tuples"
    },
    {
     "expr": "pg_stat_user_tables_n_dead_tup{fqdn=\"$instance\",relname=\"$tablename\"} / ( pg_stat_user_tables_n_dead_tup{fqdn=\"$instance\",relname=\"$tablename\"} + pg_stat_user_tables_n_live_tup{fqdn=\"$instance\",relname=\"$tablename\"} )",
     "legendFormat": "ratio of dead / dead_or_alive"
    }
   ]
  },
  {
   "title": "Vacuum Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(pg_stat_user_tables_autovacuum_count{fqdn=\"$instance\",relname=\"$tablename\"}[$__interval])",
     "legendFormat": "autovacuum count delta"
    }
   ]
  },
  {
   "title": "Tuples Inserted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_ins{fqdn=\"$instance\",relname=\"$tablename\"}[$__interval])",
     "legendFormat": "tuples inserted per second"
    }
   ]
  },
  {
   "title": "Tuples Deleted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_del{fqdn=\"$instance\",relname=\"$tablename\"}[$__interval])",
     "legendFormat": "tuples deleted per second"
    }
   ]
  },
  {
   "title": "Tuples Updated (standard heap+index update)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_upd{fqdn=\"$instance\",relname=\"$tablename\"}[$__interval])",
     "legendFormat": "tuples per second updated (standard only)"
    }
   ]
  },
  {
   "title": "Tuples Updated (heap-only tuples)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_n_tup_hot_upd{fqdn=\"$instance\",relname=\"$tablename\"}[$__interval])",
     "legendFormat": "tuples per second updated (heap-only)"
    }
   ]
  },
  {
   "title": "SeqScan read tuples/second",
   "type": "graph",
   "description": "Note: Some tuples read may be discarded by subsequently applied filters.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_seq_tup_read{fqdn=\"$instance\",relname=\"$tablename\"}[$__interval])",
     "legendFormat": "tuples per second read via SeqScan"
    }
   ]
  },
  {
   "title": "IndexScan fetch tuples/second",
   "type": "graph",
   "description": "Note: Some tuples fetched may be discarded by subsequently applied filters.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_idx_tup_fetch{fqdn=\"$instance\",relname=\"$tablename\"}[$__interval])",
     "legendFormat": "tuples per second read via IndexScan"
    }
   ]
  },
  {
   "title": "IndexScan read tuples/second",
   "type": "graph",
   "description": "Note: Some tuples read may be discarded by subsequently applied filters.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_user_indexes_idx_tup_fetch{fqdn=\"$instance\",relname=\"$tablename\"}[$__interval])",
     "legendFormat": "{{indexrelname}}"
    }
   ]
  }
 ]
}