{
 "title": "PostgreSQL Top Queries",
 "tags": [
  "postgresql",
  "unmanaged"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" },
   {
    "name": "fqdn",
    "label": "Host",
    "query": "label_values(pg_stat_database_tup_deleted,fqdn)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_deleted, datname)"
   },
   {
    "name": "user",
    "label": "User",
    "query": "gitlab,gitlab_repmgr,gitlab-consul,pgbouncer,gitlab-monitor,postgres_exporter,gitlab-psql"
   },
   {
    "name": "interval",
    "label": "Time Range",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Most called queries",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_calls{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Slowest Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Slowest Queries (Total Time Consumed per second)",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_time_milliseconds{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "test1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Slowest Queries (Average Runtime)",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_statements_time_milliseconds{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval]) / (rate(pg_stat_statements_calls{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval])>1/6000))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Highest shared_blks_dirtied",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_dirtied{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval]) * 8))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "test1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Highest shared_blks_read",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_read{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval]) * 8))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "test1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Temp Data Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Temp Data Read",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_temp_blks_read{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval]) * 8)) > 0",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "test1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Temp Data Read per execution",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_statements_temp_blks_read{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval]) / (rate(pg_stat_statements_calls{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval])>1/6000)) > 0",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Temp Data Written",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Temp Data Written",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_temp_blks_written{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval]) * 8)) > 0",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "test1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Temp Data Written per execution",
     "type": "table-old",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_statements_temp_blks_written{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval]) / (rate(pg_stat_statements_calls{datname=\"$datname\",environment=\"$environment\",user=\"$user\",fqdn=~\"$fqdn\"}[$interval])>1/6000)) > 0",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "New Slow Queries (Very Slow)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "New Slow Queries (ms/s)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,sum(rate(pg_stat_statements_seconds_total{environment=\"$environment\"}[10m])) by (queryid)) unless topk(20,sum(rate(pg_stat_statements_seconds_total{environment=\"$environment\"}[10m] offset 7d)) by (queryid))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}