{
 "title": "praefect: Praefect",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/396451807 at Wed Jan  8 03:17:21 UTC 2020",
 "tags": [
  "managed",
  "praefect",
  "type:praefect"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   { "name": "sigma", "query": "0.5,1,1.5,2,2.5,3" }
  ]
 },
 "panels": [
  {
   "title": "🗞️ Headline Metrics - 𝘦𝘹𝘱𝘢𝘯𝘥 𝘬𝘦𝘺 𝘴𝘦𝘳𝘷𝘪𝘤𝘦 𝘮𝘦𝘵𝘳𝘪𝘤𝘴 𝘳𝘰𝘸 𝘧𝘰𝘳 𝘥𝘦𝘵𝘢𝘪𝘭𝘴",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"praefect\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"praefect\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"praefect\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"praefect\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"praefect\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"praefect\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"praefect\", stage=\"\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"praefect\", stage=\"\"}\n",
     "legendFormat": "upper normal (legacy)"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"praefect\", stage=\"\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"praefect\", stage=\"\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal (legacy)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "title": "👩‍⚕️ Service Health",
   "type": "row",
   "gridPos": { "x": 0, "y": 1000 },
   "collapsed": true,
   "panels": [
    {
     "title": "7d Latency SLA",
     "type": "singlestat",
     "description": "Percentage time the latency SLI for this service is within SLO",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(avg_over_time(slo_observation_status{slo=\"apdex_ratio\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[7d]))\n"
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "sort(\n  max(\n  ALERTS{environment=\"$environment\", type=\"praefect\", stage=~\"|$stage\", severity=\"s1\", alertstate=\"firing\"} * 4\n  or\n  ALERTS{environment=\"$environment\", type=\"praefect\", stage=~\"|$stage\", severity=\"s2\", alertstate=\"firing\"} * 3\n  or\n  ALERTS{environment=\"$environment\", type=\"praefect\", stage=~\"|$stage\", severity=\"s3\", alertstate=\"firing\"} * 2\n  or\n  ALERTS{environment=\"$environment\", type=\"praefect\", alertstate=\"firing\"}\n  ) by (alertname, severity)\n)\n"
      }
     ]
    },
    {
     "title": "7d Error Rate SLA",
     "type": "singlestat",
     "description": "Percentage time the error ratio SLI for this service is within SLO",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg_over_time(slo_observation_status{slo=\"error_ratio\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[7d])\n"
      }
     ]
    }
   ]
  },
  {
   "title": "🏅 Key Service Metrics",
   "type": "row",
   "gridPos": { "x": 0, "y": 4000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency: Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
       "legendFormat": "{{ type }} service"
      },
      {
       "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
       "legendFormat": "{{ type }} service (legacy)"
      },
      {
       "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"praefect\"})\n",
       "legendFormat": "Degradation SLO"
      },
      {
       "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"praefect\"})) - 1\n",
       "legendFormat": "Outage SLO"
      },
      {
       "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
       "legendFormat": "last week"
      }
     ]
    },
    {
     "title": "Error Ratios",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "% Requests in Error" }
     ],
     "targets": [
      {
       "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
       "legendFormat": "{{ type }} service"
      },
      {
       "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"praefect\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
       "legendFormat": "{{ type }} service (legacy)"
      },
      {
       "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"praefect\"})\n",
       "legendFormat": "Degradation SLO"
      },
      {
       "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"praefect\"}))\n",
       "legendFormat": "Outage SLO"
      },
      {
       "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
       "legendFormat": "last week"
      }
     ]
    },
    {
     "title": "Component Availability",
     "type": "graph",
     "description": "Availability measures the ratio of component processes in the service that are currently healthy and able to handle requests. The closer to 100% the better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Availability %" }
     ],
     "targets": [
      {
       "expr": "min(\n  min_over_time(\n    gitlab_component_availability:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
       "legendFormat": "{{ component }} component"
      }
     ]
    },
    {
     "title": "RPS - Service Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (type)\n",
       "legendFormat": "{{ type }} service"
      },
      {
       "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"praefect\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
       "legendFormat": "{{ type }} service (legacy)"
      },
      {
       "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval] offset 1w\n  )\n) by (type)\n",
       "legendFormat": "last week"
      },
      {
       "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n",
       "legendFormat": "upper normal"
      },
      {
       "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"},\n    0\n  )\n)\n",
       "legendFormat": "lower normal"
      },
      {
       "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"praefect\", stage=\"\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"praefect\", stage=\"\"}\n",
       "legendFormat": "upper normal (legacy)"
      },
      {
       "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"praefect\", stage=\"\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"praefect\", stage=\"\"},\n    0\n  )\n)\n",
       "legendFormat": "lower normal (legacy)"
      }
     ]
    },
    {
     "title": "Saturation",
     "type": "graph",
     "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
       "legendFormat": "{{ component }} component"
      }
     ]
    }
   ]
  },
  {
   "title": "🔩 Service Component Metrics",
   "type": "row",
   "gridPos": { "x": 0, "y": 5000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Component Latency: Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min(\n  min_over_time(\n    gitlab_component_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
       "legendFormat": "{{ component }} component"
      },
      {
       "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"praefect\"})\n",
       "legendFormat": "SLO"
      }
     ]
    },
    {
     "title": "Component Error Rates - modified scale: (1 + n) log10",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors per Minute" }
     ],
     "targets": [
      {
       "expr": "1 +\n(\n  60 *\n  max(\n    max_over_time(\n      gitlab_component_errors:rate{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n    )\n  ) by (component)\n)\n",
       "legendFormat": "{{ component }} component"
      }
     ]
    },
    {
     "title": "Component Availability",
     "type": "graph",
     "description": "Availability measures the ratio of component processes in the service that are currently healthy and able to handle requests. The closer to 100% the better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Availability %" }
     ],
     "targets": [
      {
       "expr": "min(\n  min_over_time(\n    gitlab_component_availability:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
       "legendFormat": "{{ component }} component"
      }
     ]
    },
    {
     "title": "Component RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "reqps", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "1 +\nmax(\n  avg_over_time(\n    gitlab_component_ops:rate{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
       "legendFormat": "{{ component }} component"
      }
     ]
    },
    {
     "title": "Saturation",
     "type": "graph",
     "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]\n  )\n) by (component)\n",
       "legendFormat": "{{ component }} component"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "x": 0, "y": 6000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "avg(instance:node_cpu_utilization:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{environment=\"$environment\", type=\"praefect\", stage=\"$stage\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "sum(rate(node_network_receive_bytes_total{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(instance:node_memory_utilization:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_reads_completed_total{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_writes_completed_total{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_read_bytes_total{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_written_bytes_total{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Total Time",
     "type": "graph",
     "description": "Total time spent in read operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_read_time_seconds_total{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Total Time",
     "type": "graph",
     "description": "Total time spent in write operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_write_time_seconds_total{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6000 },
   "collapsed": true,
   "panels": [
    {
     "title": "cgroup_memory component saturation: Cgroup Memory Saturation per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    (\n  container_memory_usage_bytes{id=\"/system.slice/gitlab-runsvdir.service\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"} -\n  container_memory_cache{id=\"/system.slice/gitlab-runsvdir.service\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"} -\n  container_memory_swap{id=\"/system.slice/gitlab-runsvdir.service\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n)\n/\ncontainer_spec_memory_limit_bytes{id=\"/system.slice/gitlab-runsvdir.service\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cgroup_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cgroup_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "cpu component saturation: Average CPU Saturation per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    avg(1 - rate(node_cpu_seconds_total{mode=\"idle\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])) by (fqdn)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_space component saturation: Disk Utilization per Device per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n  (\n    1 -\n    instance:node_filesystem_avail:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\" ,fstype=~\"ext.|xfs\"}\n  )\n) by (device, fqdn)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_sustained_read_iops component saturation: Disk Sustained Read IOPS Saturation per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    rate(node_disk_reads_completed_total{type=\"gitaly\", device=\"sdb\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]) / (60000)\nor\nrate(node_disk_reads_completed_total{type=\"nfs\", device=\"sdb\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]) / (15000)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_sustained_read_iops\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_sustained_read_iops\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_sustained_read_throughput component saturation: Disk Sustained Read Throughput Saturation per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    rate(node_disk_read_bytes_total{type=\"gitaly\", device=\"sdb\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]) / (1258291200)\nor\nrate(node_disk_read_bytes_total{type=\"nfs\", device=\"sdb\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]) / (838860800)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_sustained_read_throughput\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_sustained_read_throughput\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_sustained_write_iops component saturation: Disk Sustained Write IOPS Saturation per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    rate(node_disk_writes_completed_total{type=\"gitaly\", device=\"sdb\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]) / (30000)\nor\nrate(node_disk_writes_completed_total{type=\"nfs\", device=\"sdb\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]) / (15000)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_sustained_write_iops\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_sustained_write_iops\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_sustained_write_throughput component saturation: Disk Sustained Write Throughput Saturation per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    rate(node_disk_written_bytes_total{type=\"gitaly\", device=\"sdb\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]) / (419430400)\nor\nrate(node_disk_written_bytes_total{type=\"nfs\", device=\"sdb\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval]) / (419430400)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_sustained_write_throughput\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_sustained_write_throughput\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "memory component saturation: Memory Utilization per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    instance:node_memory_utilization:ratio{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor saturation per instance",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n  label_replace(\n    process_open_fds{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n    /\n    process_max_fds{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n    , \"client\", \"general\", \"\", \"\"\n  )\n  or\n  label_replace(\n    ruby_file_descriptors{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n    /\n    ruby_process_max_fds{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n    , \"client\", \"ruby\", \"\", \"\"\n  )\n) by (job, instance)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }}: {{ instance }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "single_node_cpu component saturation: Average CPU Saturation per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    avg(1 - rate(node_cpu_seconds_total{mode=\"idle\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])) by (fqdn)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "go_memory component saturation: Go Memory Saturation per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    sum by (fqdn, type, tier, stage, environment) (\n  go_memstats_alloc_bytes{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n)\n/\nsum by (fqdn, type, tier, stage, environment) (\n  node_memory_MemTotal_bytes{environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 proxy Component Detail",
   "type": "row",
   "gridPos": { "x": 0, "y": 7000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated proxy Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.995000,\n  sum by (le) (\n    rate(grpc_server_handling_seconds_bucket{job=\"praefect\", grpc_type=\"unary\", grpc_method!~\"GarbageCollect|Fsck|RepackFull|RepackIncremental|CommitLanguages|CreateRepositoryFromURL|UserRebase|UserSquash|CreateFork|UserUpdateBranch|FindRemoteRepository|UserCherryPick|FetchRemote|UserRevert|FindRemoteRootRef\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p99.5 proxy"
      }
     ]
    },
    {
     "title": "proxy RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(grpc_server_handled_total{job=\"praefect\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "proxy"
      }
     ]
    },
    {
     "title": "proxy Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  changes(grpc_server_handled_total{job=\"praefect\", grpc_code!~\"^(OK|NotFound|Unauthenticated|AlreadyExists|FailedPrecondition)$\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "proxy"
      }
     ]
    },
    {
     "title": "Estimated proxy Latency - per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.995000,\n  sum by (fqdn, le) (\n    rate(grpc_server_handling_seconds_bucket{job=\"praefect\", grpc_type=\"unary\", grpc_method!~\"GarbageCollect|Fsck|RepackFull|RepackIncremental|CommitLanguages|CreateRepositoryFromURL|UserRebase|UserSquash|CreateFork|UserUpdateBranch|FindRemoteRepository|UserCherryPick|FetchRemote|UserRevert|FindRemoteRootRef\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p99.5 {{ fqdn }}"
      }
     ]
    },
    {
     "title": "proxy RPS - per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  rate(grpc_server_handled_total{job=\"praefect\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "proxy Errors - per Node",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  changes(grpc_server_handled_total{job=\"praefect\", grpc_code!~\"^(OK|NotFound|Unauthenticated|AlreadyExists|FailedPrecondition)$\", environment=\"$environment\", type=\"praefect\", stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "📆 Capacity Planning",
   "type": "row",
   "gridPos": { "x": 0, "y": 8000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Currently Saturated Resources",
     "type": "table",
     "description": "Lists saturated resources that are breaching their soft SLO thresholds at this instant",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "max by (type, stage, component) (\n  clamp_max(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"praefect\", stage=~\"|$stage\"}\n    ,\n    1\n  ) >= on(component, monitor, env, cluster) group_left slo:max:soft:gitlab_component_saturation:ratio\n)\n"
      }
     ]
    },
    {
     "title": "Resources Currently at Risk of being Saturated",
     "type": "table",
     "description": "Lists saturated resources that, given their current value and weekly variance, have a high probability of breaching their soft thresholds limits within the next few hours",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sort_desc(\n  max by (type, stage, component) (\n    clamp_max(\n      gitlab_component_saturation:ratio:avg_over_time_1w{\n        environment=\"$environment\",\n        type=\"praefect\", stage=~\"|$stage\"\n      } +\n      2 *\n        gitlab_component_saturation:ratio:stddev_over_time_1w{\n          environment=\"$environment\",\n          type=\"praefect\", stage=~\"|$stage\"\n        }\n      , 1\n    )\n    >= on(component, monitor, env, cluster) group_left slo:max:soft:gitlab_component_saturation:ratio\n  )\n)\n"
      }
     ]
    },
    {
     "title": "Resources Forecasted to be at Risk of Saturation in 14d",
     "type": "table",
     "description": "Lists saturated resources that, given their growth rate over the the past week, and their weekly variance, are likely to breach their soft thresholds limits in the next 14d",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sort_desc(\n  max by (type, stage, component) (\n    clamp_max(\n      gitlab_component_saturation:ratio:predict_linear_2w{\n        environment=\"$environment\",\n        type=\"praefect\", stage=~\"|$stage\"\n      } +\n      2 *\n        gitlab_component_saturation:ratio:stddev_over_time_1w{\n          environment=\"$environment\",\n          type=\"praefect\", stage=~\"|$stage\"\n        }\n    , 1\n    )\n    >= on(component, monitor, env, cluster) group_left slo:max:soft:gitlab_component_saturation:ratio\n  )\n)\n"
      }
     ]
    },
    {
     "title": "Long-term Resource Saturation",
     "type": "graph",
     "description": "Resource saturation levels for saturation components for this service. Lower is better.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(\n  max(\n    gitlab_component_saturation:ratio{\n      type=\"praefect\",\n      environment=\"$environment\",\n      stage=~\"|$stage\"\n    }\n  ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "{{ component }}"
      }
     ]
    },
    {
     "title": "Long-term Resource Saturation - Rolling 1w average trend",
     "type": "graph",
     "description": "Percentage of time that resource is within capacity SLOs. Higher is better.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio:avg_over_time_1w{\n        type=\"praefect\",\n        environment=\"$environment\",\n        stage=~\"$stage|\"\n      }\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "{{ component }}"
      }
     ]
    }
   ]
  }
 ]
}