{
 "title": "Praefect",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(up{type=\"gitaly\"}, environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Completed Verification Jobs by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(gitaly_praefect_verification_jobs_completed_total{environment=\"$environment\"}[$__interval])) by (virtual_storage, storage)\n",
     "legendFormat": "{{virtual_storage}}/{{storage}}"
    },
    {
     "expr": "sum(increase(gitaly_praefect_verification_jobs_completed_total{environment=\"$environment\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Completed Verification Jobs by Result",
   "type": "timeseries",
   "description": "The number of completed verification jobs and their results. \n- error means the job failed and has to be retried\n- invalid means an expected replica did not exist\n- valid means the expected replica existed",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(gitaly_praefect_verification_jobs_completed_total{environment=\"$environment\"}[$__interval])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Stale Verification Leases Released",
   "type": "timeseries",
   "description": "The number of leases that had to be released due to the verification worker not expectedly releasing the lease on job completion.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(gitaly_praefect_stale_verification_leases_released_total{environment=\"$environment\"}[$__interval]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Unavailable Repositories",
   "type": "stat",
   "description": "Number of repositories that don't have any up to date replicas available.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(gitaly_praefect_unavailable_repositories{environment=\"$environment\"}) by (virtual_storage)",
     "legendFormat": "{{virtual_storage}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{type=\"praefect\", job=\"praefect\", environment=\"$environment\"}",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Accessor vs. Mutator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method_type)(rate(gitaly_praefect_method_types{environment=\"$environment\"}[5m]))",
     "legendFormat": "{{ method_type }}"
    }
   ]
  },
  {
   "title": "Memory - Allocated Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{type=\"praefect\", job=\"praefect\", environment=\"$environment\"}",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Deployed Praefect Versions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_build_info{job=\"praefect\",environment=\"$environment\"}) by (version)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Total RPC Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{type=\"praefect\", grpc_code=\"OK\",environment=\"$environment\"}[1m]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{type=\"praefect\", grpc_code!=\"OK\"}[1m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{type=\"praefect\", job=\"praefect\", environment=\"gprd\"}",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_goroutines{type=\"praefect\", job=\"praefect\", environment=\"$environment\"}[5m])",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{type=\"praefect\", job=\"praefect\", environment=\"$environment\"}[5m])",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Network Bytes Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{type=\"praefect\", device!=\"lo\", env=\"$environment\"}[5m])",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Network Bytes Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{type=\"praefect\", device!=\"lo\", env=\"$environment\"}[5m])",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Praefect Added Latency",
   "type": "graph",
   "description": "Latency that Praefect adds to RPCs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (grpc_method) (rate(grpc_client_handled_total{env=\"$environment\", type=\"praefect\"}[10m])) - sum by (grpc_method) (rate(grpc_server_handled_total{env=\"$environment\",  type=\"praefect\"}[10m]))",
     "legendFormat": "{{ grpc_method }}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (increase(gitaly_praefect_transactions_total{env=\"$environment\"}[$__rate_interval]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Replication Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(gitaly_praefect_replication_queue_depth{environment=\"$environment\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Transaction Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(gitaly_praefect_transactions_delay_seconds_bucket{env=\"$environment\"}[$__rate_interval])))",
     "legendFormat": "Server-side delay"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(gitaly_hook_transaction_voting_delay_seconds_bucket{env=\"$environment\"}[$__rate_interval])))",
     "legendFormat": "Hook-side delay"
    }
   ]
  },
  {
   "title": "Replication Jobs In Flight",
   "type": "graph",
   "description": "Replication jobs in flight graphed by change type on the positive Y-axis and by instance on the negative Y-axis.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "By Change Type" }
   ],
   "targets": [
    {
     "expr": "sum(gitaly_praefect_replication_jobs{environment=\"$environment\"}) by (change_type)",
     "legendFormat": "{{change_type}}"
    },
    {
     "expr": "sum(gitaly_praefect_replication_jobs{environment=\"$environment\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "0", "legendFormat": "zeroline" },
    {}
   ]
  },
  {
   "title": "Subtransactions per Transaction",
   "type": "bargauge",
   "description": "Number of subtransactions created as part of a transaction",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(gitaly_praefect_subtransactions_per_transaction_total_bucket{env=\"$environment\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Replication Reason",
   "type": "graph",
   "description": "Reason why replication jobs have been scheduled.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitaly_praefect_tx_replications_total{env=\"$environment\"}[$__rate_interval])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Voters per Transaction",
   "type": "bargauge",
   "description": "Number of voters registered for transactions",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(gitaly_praefect_voters_per_transaction_total_bucket{env=\"$environment\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Replication Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_praefect_replication_latency_bucket{env=\"$environment\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(gitaly_praefect_replication_latency_bucket{env=\"$environment\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gitaly_praefect_replication_latency_bucket{env=\"$environment\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Replication Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitaly_praefect_replication_delay_bucket{env=\"$environment\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(gitaly_praefect_replication_delay_bucket{env=\"$environment\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(gitaly_praefect_replication_delay_bucket{env=\"$environment\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}