{
 "title": "Pre-receive Secret Detection – Overview",
 "description": "This dashboard gives an overview of the components the Pre-receive SD feature interacts and monitors their stability and performance.",
 "tags": [
  "secret-detection",
  "pre-receive-secret-detection",
  "secure",
  "gitaly",
  "rails",
  "workhorse",
  "unmanaged"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Pre-receive Secret Detection – Overview\n\nPlease read the associated [runbook](https://handbook.gitlab.com/handbook/engineering/development/sec/secure/secret-detection/runbooks/pre-receive-secret-detection-monitoring/) for more information on how to read and update this dashboard."
   }
  },
  { "title": "🐎 Workhorse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Processed `git-receive-pack` Requests",
   "type": "timeseries",
   "description": "This panel displays the number of HTTP requests that have been processed by `workhorse` over time, increasing in range of 24 hours. The panel partitions these requests by the HTTP verb/method and response code. This panel can be used to determine if the amount of `git-receive-pack` requests with a response code that isn't `200` had increased recently, indicating an issue with processing such requests.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(code, method) (increase(gitlab_workhorse_git_http_requests{exported_service=\"git-receive-pack\", stage=\"main\", env=\"gprd\", code!=\"0\"}[24h]))",
     "legendFormat": "{{code}} | {{method}}"
    }
   ]
  },
  {
   "title": "Total Established Gitaly Connections",
   "type": "timeseries",
   "description": "This panel displays the total number of `Gitaly` connections that have been established by `workhorse` at a given time. This panel can be used to determine if there's a sudden drop in connections between both components, which may indicate a performance or an availability issue.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count by(status) (gitlab_workhorse_gitaly_connections_total{env=\"gprd\", stage=\"main\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Latency for `/.git/git-receive-pack` Request [All Nodes]",
   "type": "timeseries",
   "description": "This panel displays the average latency (duration) in seconds for the `/.git/git-receive-pack` request for all nodes running `workhorse`. This panel can be used to determine if there is an increase in response times for that specific request, which could indicate performance degradation issue if it surpassed a certain thershold.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_request_duration_seconds_sum{env=\"gprd\", stage=\"main\", route=\"^/.+\\\\.git/git-receive-pack\\\\z\"}[24h])) / sum(rate(gitlab_workhorse_http_request_duration_seconds_count{env=\"gprd\", stage=\"main\", route=\"^/.+\\\\.git/git-receive-pack\\\\z\"}[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "⚙️ Gitaly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "🚂 Rails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } }
 ]
}