{
 "title": "PreProd",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "pre,testbed" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "prometheus_app", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "repeat": "type",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(instance:node_cpu_in_use:ratio{environment=\"$environment\"}[$__interval])) by (fqdn)",
     "legendFormat": "{{ fqdn }} avg"
    },
    {
     "expr": "max(max_over_time(instance:node_cpu_in_use:ratio{environment=\"$environment\"}[$__interval])) by (fqdn)",
     "legendFormat": "{{ fqdn }} max"
    },
    {
     "expr": "min(min_over_time(instance:node_cpu_in_use:ratio{environment=\"$environment\"}[$__interval])) by (fqdn)",
     "legendFormat": "{{ fqdn }} min"
    }
   ]
  },
  {
   "title": "Memory Overview",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (fqdn)",
     "legendFormat": "{{ fqdn }} Used"
    },
    {
     "expr": "sum(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) by (fqdn)",
     "legendFormat": "{{ fqdn }} Swap"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes) by (fqdn)",
     "legendFormat": "{{ fqdn }} Total"
    },
    {
     "expr": "sum(node_memory_SwapTotal_bytes) by (fqdn)",
     "legendFormat": "{{ fqdn }} Swap Total"
    }
   ]
  },
  { "title": "NFS (Cloud filestorage)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "NFS Operation counts sampled at 60 second intervals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
   "repeat": "type",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nstackdriver_filestore_instance_file_googleapis_com_nfs_server_read_ops_count",
     "legendFormat": "read ops"
    },
    {
     "expr": "stackdriver_filestore_instance_file_googleapis_com_nfs_server_write_ops_count",
     "legendFormat": "write ops"
    },
    {
     "expr": "stackdriver_filestore_instance_file_googleapis_com_nfs_server_write_bytes_count",
     "legendFormat": "write bytes"
    },
    {
     "expr": "stackdriver_filestore_instance_file_googleapis_com_nfs_server_read_bytes_count",
     "legendFormat": "read bytes"
    }
   ]
  },
  {
   "title": "Procedure call counts sampled at 60 second intervals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nstackdriver_filestore_instance_file_googleapis_com_nfs_server_procedure_call_count",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Milliseconds on disk, sampled at 60 second intervals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nstackdriver_filestore_instance_file_googleapis_com_nfs_server_write_milliseconds_count",
     "legendFormat": "write"
    },
    {
     "expr": "stackdriver_filestore_instance_file_googleapis_com_nfs_server_read_milliseconds_count",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Rails",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exceptions Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_transaction_event_rails_exception_total{environment=\"$environment\"}[$__interval]))",
       "legendFormat": "cny"
      }
     ]
    },
    {
     "title": "Exceptions Rate by Controller",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_transaction_event_rails_exception_total{environment=\"$environment\"}[$__interval])) by (controller)",
       "legendFormat": "{{ controller }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workhorse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workhorse req/sec by method and route",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"$environment\",job=\"gitlab-workhorse\"}[1m])) by (route,method)",
       "legendFormat": "{{ method }} {{ route }} "
      }
     ]
    },
    {
     "title": "Workhorse req/sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"$environment\",job=\"gitlab-workhorse\", route!=\"^/-/\"}[1m]))",
       "legendFormat": "web"
      }
     ]
    }
   ]
  }
 ]
}