{
 "title": "product-intelligence: Product Intelligence",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4375215043 at Tue May 30 14:11:37 UTC 2023",
 "tags": [
  "managed",
  "product-intelligence",
  "product_intelligence"
 ],
 "time": { "from": "now-7d", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  { "title": "Snowplow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GitLab.com Backend sucessful events ratio 1h",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_snowplow_successful_events_total{env=\"$environment\"}[1h])) / sum(rate(gitlab_snowplow_events_total{env=\"$environment\"}[1h]))\n",
     "legendFormat": "$environment"
    }
   ]
  },
  {
   "title": "GitLab.com Backend Events total 1h",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gitlab_snowplow_events_total{env=\"$environment\"}[1h]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(increase(gitlab_snowplow_successful_events_total{env=\"$environment\"}[1h]))",
     "legendFormat": "Successfull"
    },
    {
     "expr": "sum(increase(gitlab_snowplow_failed_events_total{env=\"$environment\"}[1h]))",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "Redis Hll", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GitLab.com events fired 1h",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(redis_commands_total{cmd=\"pfadd\",env=\"$environment\"}[1h]) and on(fqdn) redis_instance_info { role=\"master\" }\n",
     "legendFormat": "Environment {{ environment }}"
    }
   ]
  }
 ]
}