{
 "title": "Product Intelligence - Redis Monitoring",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "7 days ago",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"gprd\",environment=\"gprd\",stage=\"main\",type=\"redis\"}[$__interval]\n  )\n) by (component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"gprd\",environment=\"gprd\",stage=\"main\",type=\"redis\"}[$__interval]\n  )\n) by (component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  { "title": "Redis HLL comands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "PFADD - 7 days ago",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{environment=\"gprd\", type=\"redis\", cmd=\"pfadd\"}[1m])\n  and on (instance) redis_instance_info{role=\"master\"}\n) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "PFADD - Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{environment=\"gprd\", type=\"redis\", cmd=\"pfadd\"}[1m])\n  and on (instance) redis_instance_info{role=\"master\"}\n) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "PFCOUNT - 7 days ago",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{environment=\"gprd\", type=\"redis\", cmd=\"pfcount\"}[1m])\n  and on (instance) redis_instance_info{role=\"master\"}\n) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "PFCOUNT - Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{environment=\"gprd\", type=\"redis\", cmd=\"pfcount\"}[1m])\n  and on (instance) redis_instance_info{role=\"master\"}\n) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  { "title": "Redis CPU per Node - Primary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "7 days ago",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(max(\n  max_over_time(instance:redis_cpu_usage:rate1m{environment=\"gprd\", type=\"redis\", fqdn=~\"redis-\\\\d\\\\d.*\"}[$__interval])\n    and on (instance) redis_instance_info{role=\"master\"}\n) by (fqdn)\n,1),0)",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(max(\n  max_over_time(instance:redis_cpu_usage:rate1m{environment=\"gprd\", type=\"redis\", fqdn=~\"redis-\\\\d\\\\d.*\"}[$__interval])\n    and on (instance) redis_instance_info{role=\"master\"}\n) by (fqdn)\n,1),0)",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Memory saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "7 days ago",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(\n  label_replace(redis_memory_used_rss_bytes{environment=\"gprd\", type=\"redis\"}, \"memtype\", \"rss\",\"\",\"\")\n  or\n  label_replace(redis_memory_used_bytes{environment=\"gprd\", type=\"redis\"}, \"memtype\", \"used\",\"\",\"\")\n) by (type, tier, stage, environment, fqdn)\n/ on(fqdn) group_left\nnode_memory_MemTotal_bytes{environment=\"gprd\", type=\"redis\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "max(slo:max:soft:gitlab_component_saturation:ratio{component=\"redis_memory\", environment=\"gprd\"})",
       "legendFormat": "Degradation SLO"
      },
      {
       "expr": "max(slo:max:hard:gitlab_component_saturation:ratio{component=\"redis_memory\", environment=\"gprd\"})",
       "legendFormat": "Outage SLO"
      }
     ]
    },
    {
     "title": "Current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(\n  label_replace(redis_memory_used_rss_bytes{environment=\"gprd\", type=\"redis\"}, \"memtype\", \"rss\",\"\",\"\")\n  or\n  label_replace(redis_memory_used_bytes{environment=\"gprd\", type=\"redis\"}, \"memtype\", \"used\",\"\",\"\")\n) by (type, tier, stage, environment, fqdn)\n/ on(fqdn) group_left\nnode_memory_MemTotal_bytes{environment=\"gprd\", type=\"redis\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "max(slo:max:soft:gitlab_component_saturation:ratio{component=\"redis_memory\", environment=\"gprd\"})",
       "legendFormat": "Degradation SLO"
      },
      {
       "expr": "max(slo:max:hard:gitlab_component_saturation:ratio{component=\"redis_memory\", environment=\"gprd\"})",
       "legendFormat": "Outage SLO"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "7 days ago",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(redis_memory_used_bytes{environment=\"gprd\", type=\"redis\"}[$__interval])",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(redis_memory_used_bytes{environment=\"gprd\", type=\"redis\"}[$__interval])",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "7 days ago",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "sum(\n  avg_over_time(\n    gitlab_component_ops:rate_5m{component=\"rails_redis_client\",env=\"gprd\",environment=\"gprd\",monitor!~\"global|\",stage=\"main\",type=\"redis\"}[$__interval]\n  )\n) by (component)",
       "legendFormat": "{{component}} RPS"
      }
     ]
    },
    {
     "title": "Current",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "sum(\n  avg_over_time(\n    gitlab_component_ops:rate_5m{component=\"rails_redis_client\",env=\"gprd\",environment=\"gprd\",monitor!~\"global|\",stage=\"main\",type=\"redis\"}[$__interval]\n  )\n) by (component)",
       "legendFormat": "{{component}} RPS"
      }
     ]
    }
   ]
  }
 ]
}