{
 "title": "product: Performance - Secure",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5288059752 at Fri Oct 13 11:43:56 UTC 2023",
 "tags": [
  "managed",
  "product",
  "product performance"
 ],
 "time": { "from": "now-30d", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "function", "query": "min, mean, median, p90, max" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "### Synthetic tests of GitLab.com pages for the Secure group.\n\nFor more information, please see: https://about.gitlab.com/handbook/product/product-processes/#page-load-performance-metrics\n\n\n\n"
  },
  { "title": "Threat Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Merge Request",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-examples/security/security-reports/-/merge_requests/39",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Merge_Request.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Merge_Request.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Merge_Request.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Instance Security Dashboard",
   "type": "graph",
   "description": "https://gitlab.com/-/security/dashboard",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Instance_Security_Dashboard.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Instance_Security_Dashboard.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Instance_Security_Dashboard.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Instance Vulnerability Report",
   "type": "graph",
   "description": "https://gitlab.com/-/security/vulnerabilities",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Instance_Vulnerability_Report.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Instance_Vulnerability_Report.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Instance_Vulnerability_Report.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Instance Vulnerability Report",
   "type": "graph",
   "description": " https://gitlab.com/-/security/dashboard/settings",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Instance_Dashboard_Settings.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Instance_Dashboard_Settings.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Instance_Dashboard_Settings.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Group Security Dashboard",
   "type": "graph",
   "description": "https://gitlab.com/groups/gitlab-examples/security/-/security/dashboard",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1021 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Group_Security_Dashboard.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Group_Security_Dashboard.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Group_Security_Dashboard.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Group Vulnerability Report",
   "type": "graph",
   "description": "https://gitlab.com/groups/gitlab-examples/security/-/security/vulnerabilities",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1021 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Group_Vulnerability_Report.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Group_Vulnerability_Report.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Group_Vulnerability_Report.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Project Security Dashboard",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-examples/security/simply-simple-notes/-/security/dashboard",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1031 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Project_Security_Dashboard.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Project_Security_Dashboard.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Project_Security_Dashboard.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Project Vulnerability Report",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-examples/security/simply-simple-notes/-/security/vulnerability_report",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1031 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Project_Vulnerability_Report.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Project_Vulnerability_Report.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Project_Vulnerability_Report.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Vulnerability Details Page",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-examples/security/security-reports/-/security/vulnerabilities/26231",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1041 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Standalone_Vulnerability.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Standalone_Vulnerability.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Standalone_Vulnerability.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Security Configuration",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-examples/security/security-reports/-/security/configuration",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1041 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Security_Configuration.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Security_Configuration.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Security_Configuration.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "Composition Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "License Compliance",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-examples/security/security-reports/-/licenses#licenses",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_License_Compliance.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_License_Compliance.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_License_Compliance.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Dependency List",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-examples/security/security-reports/-/dependencies",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Dependency_List.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Dependency_List.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Secure_Dependency_List.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "DAST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "On-Demand Scans",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-examples/security/security-reports/-/on_demand_scans",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.On_Demand_Scans.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.On_Demand_Scans.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.On_Demand_Scans.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "DAST Profiles",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-examples/security/security-reports/-/security/configuration/dast_scans",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.DAST_Profiles.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.DAST_Profiles.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.DAST_Profiles.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "SAST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 } },
  {
   "title": "SAST Config UI",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-examples/security/security-reports/-/security/configuration/sast",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SAST_Config_UI.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SAST_Config_UI.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SAST_Config_UI.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "Fuzz Testing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5000 } },
  {
   "title": "API Fuzzing Config UI",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-examples/security/security-reports/-/security/configuration/api_fuzzing",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.API_Fuzzing_Config_UI.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.API_Fuzzing_Config_UI.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.API_Fuzzing_Config_UI.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  }
 ]
}