{
 "title": "Production 895",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total time in  `INSERT INTO \"ci_job_artifacts`",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_time_milliseconds{queryid=~\"2108463555|2873427309|2374882523\", environment=\"gprd\"}[$__interval]))",
     "legendFormat": "total query time"
    }
   ]
  },
  {
   "title": "Total time in  project_statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_time_milliseconds{queryid=\"898968504\", environment=\"gprd\"}[$__interval])) by (queryid)",
     "legendFormat": "{{ queryid }}"
    },
    {
     "expr": "sum(rate(pg_stat_statements_time_milliseconds{queryid=\"898968504\", environment=\"gprd\"}[$__interval])) by (queryid)",
     "legendFormat": "UPDATE \"project_statistics\" SET build_artifacts_size = COALESCE(build_artifacts_size, ?) + (?), storage_size = COALESCE(storage_size, ?) + (?) WHERE \"project_statistics\".\"project_id\" = ?"
    }
   ]
  },
  {
   "title": "UPDATE \"project_statistics\" SET build_artifacts_size =....",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_time_milliseconds{queryid=\"898968504\", environment=\"gprd\"}[$__interval])) / \nsum(rate(pg_stat_statements_calls{queryid=\"898968504\", environment=\"gprd\"}[$__interval])) ",
     "legendFormat": "Average time per insert"
    },
    {
     "expr": "sum(rate(pg_stat_statements_time_milliseconds{queryid=\"898968504\", environment=\"gprd\"}[$__interval])) by (queryid)",
     "legendFormat": "Total time"
    }
   ]
  },
  {
   "title": "SELECT with LIMIT vs SELECT without LIMIT",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_time_milliseconds{queryid=\"3046840721\"}[$__interval])) by (queryid)  \n/\nsum(rate(pg_stat_statements_calls{queryid=\"3046840721\"}[$__interval])) by (queryid)  ",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(rate(pg_stat_statements_time_milliseconds{queryid=\"4058000184\"}[$__interval])) by (queryid)  \n/\nsum(rate(pg_stat_statements_calls{queryid=\"4058000184\"}[$__interval])) by (queryid)  ",
     "legendFormat": "No Limit"
    }
   ]
  },
  {
   "title": "Idle in Transaction vs Web Apdex",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(pg_stat_activity_count{environment=\"gprd\", datname=\"gitlabhq_production\", fqdn=\"patroni-04-db-gprd.c.gitlab-production.internal\", state=\"idle in transaction\"}[$__interval])",
     "legendFormat": "activity: idle in transaction"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio{type=\"web\", environment=\"gprd\", stage=\"main\"}[$__interval])",
     "legendFormat": "web apdex"
    }
   ]
  },
  {
   "title": "Idle in Transaction vs Web Apdex",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(pg_stat_activity_count{environment=\"gprd\", datname=\"gitlabhq_production\", fqdn=\"patroni-04-db-gprd.c.gitlab-production.internal\", state=\"idle in transaction\"}[$__interval])",
     "legendFormat": "activity: idle in transaction"
    },
    {
     "expr": "1 -  avg_over_time(gitlab_service_apdex:ratio{type=\"web\", environment=\"gprd\", stage=\"main\"}[$__interval])",
     "legendFormat": "inverted web apdex"
    }
   ]
  },
  {
   "title": "Web Apdex Score v. SELECT internal_ids FOR UPDATE time",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(pg_stat_statements_time_milliseconds{queryid=\"2722666312\"}[$__interval]))",
     "legendFormat": "QueryTime"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio{type=\"web\", environment=\"gprd\", stage=\"main\"}[$__interval])",
     "legendFormat": "Web Apdex"
    }
   ]
  },
  {
   "title": "Relative Query Rates compared to 1hr before",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_calls{user=\"gitlab\", queryid=~\"3589441560|2687552202|2725112711|1872435845|541675883|1850364306|3046840721|372766009|1024354833|1847148074|2869434099|3470580987|1870450709|3261529960|2112300417|4110719723|2410196384|3147930916|2869637736|1471483198|813146095|1562312218|4070001059|2700573270|3734280165|1890462193|3662628805|4198375393|3709830407|473577831\", fqdn=\"patroni-04-db-gprd.c.gitlab-production.internal\"}[$__interval]) / \nrate(pg_stat_statements_calls{user=\"gitlab\", queryid=~\"3589441560|2687552202|2725112711|1872435845|541675883|1850364306|3046840721|372766009|1024354833|1847148074|2869434099|3470580987|1870450709|3261529960|2112300417|4110719723|2410196384|3147930916|2869637736|1471483198|813146095|1562312218|4070001059|2700573270|3734280165|1890462193|3662628805|4198375393|3709830407|473577831\"}[12h] offset 1h)",
     "legendFormat": "queryid: {{ queryid }}"
    }
   ]
  },
  {
   "title": "Relative Query Times compared to 1hr before",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_time_milliseconds{user=\"gitlab\", queryid=~\"3589441560|2687552202|2725112711|1872435845|541675883|1850364306|3046840721|372766009|1024354833|1847148074|2869434099|3470580987|1870450709|3261529960|2112300417|4110719723|2410196384|3147930916|2869637736|1471483198|813146095|1562312218|4070001059|2700573270|3734280165|1890462193|3662628805|4198375393|3709830407|473577831\", fqdn=\"patroni-04-db-gprd.c.gitlab-production.internal\"}[$__interval]) / \nrate(pg_stat_statements_time_milliseconds{user=\"gitlab\", queryid=~\"3589441560|2687552202|2725112711|1872435845|541675883|1850364306|3046840721|372766009|1024354833|1847148074|2869434099|3470580987|1870450709|3261529960|2112300417|4110719723|2410196384|3147930916|2869637736|1471483198|813146095|1562312218|4070001059|2700573270|3734280165|1890462193|3662628805|4198375393|3709830407|473577831\"}[12h] offset 1h)",
     "legendFormat": "queryid: {{ queryid }}"
    }
   ]
  },
  {
   "title": "Activity Count for States",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{environment=\"gprd\", datname=\"gitlabhq_production\", fqdn=\"patroni-04-db-gprd.c.gitlab-production.internal\"  }",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Call Times to Selected Queries",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_time_milliseconds{queryid=~\"3947237136|3703971970|3102967301|3046840721|3673560211|3005246559|898968504|870097139|578096850|596031129|2125684799|1388599055|2807305590|473577831|2623032823|3185894468|2722666312|2217086282|20394130|1372870422|3329616449|1001373568|1851880515|1361492350|3440423021|1850364306|2897729848|647063698|2388959352|190420834\", fqdn=\"patroni-04-db-gprd.c.gitlab-production.internal\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Call Times to Selected Queries",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_time_milliseconds{queryid=~\"3100829838|1507605447|3703971970|870097139|596031129\", fqdn=\"patroni-04-db-gprd.c.gitlab-production.internal\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Total Query Time per Server",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_statements_time_milliseconds{environment=\"gprd\", type=\"patroni\"}[$__interval])) by (fqdn)",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  }
 ]
}