{
 "title": "production-2848",
 "time": { "from": "2020-10-19T08:45:00.000Z", "to": "2020-10-19T11:15:00.000Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "# WIP\n\nThis dashboard contains the timeline and relevant metrics for [production-2848](https://gitlab.com/gitlab-com/gl-infra/production/-/issues/2848).\n"
   }
  },
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Loadbalancer / Pages traffic ratio",
   "type": "graph",
   "description": "The target ratio is, that egress of HAProxy and web nodes should be equal (100%). Anything above the target ratio over-utilizes the loadbalancers, anything below under-utilizes the loadbalancer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{fqdn=~\"fe-pages-.*\", env=\"gprd\"}[30s])) / sum(rate(node_network_transmit_bytes_total{fqdn=~\"web-pages-.*\", env=\"gprd\"}[30s])) > 1",
     "legendFormat": "Loadbalancer Over-utilization"
    },
    { "expr": "vector(1)", "legendFormat": "target ratio" },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{fqdn=~\"fe-pages-.*\", env=\"gprd\"}[30s])) / sum(rate(node_network_transmit_bytes_total{fqdn=~\"web-pages-.*\", env=\"gprd\"}[30s])) < 1",
     "legendFormat": "Loadbalancer Under-utilization"
    }
   ]
  },
  {
   "title": "Pages vs node data rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_pages_http_response_size_bytes_sum[30s]))",
     "legendFormat": "GitLab Pages daemon sent"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{fqdn=~\"web-pages-.*\", env=\"gprd\"}[30s]))",
     "legendFormat": "Node sent"
    }
   ]
  },
  {
   "title": "GitLab Pages HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_pages_http_requests_total[30s])) by (code)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Node network (pages web servers)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{fqdn=~\"web-pages-.*\", env=\"gprd\"}[30s]))",
     "legendFormat": "Egress {{fqdn}}"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{fqdn=~\"web-pages-.*\", env=\"gprd\"}[30s]))",
     "legendFormat": "Ingress {{fqdn}}"
    }
   ]
  },
  {
   "title": "GitLab Pages Served throughput (app-side)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gitlab_pages_http_response_size_bytes_sum{env=\"gprd\"}[30s])) * 8"
    }
   ]
  },
  {
   "title": "GitLab Pages Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max by (type) (max_over_time(gitlab_service_errors:ratio_5m{env=\"gprd\",environment=\"gprd\",monitor=\"global\",stage=\"main\",type=\"pages\"}[30s]))\n  or\n  sum by (type) (gitlab_service_errors:ratio_5m{env=\"gprd\",environment=\"gprd\",monitor!~\"global|\",stage=\"main\",type=\"pages\"}),\n  1\n)\n"
    }
   ]
  },
  { "title": "Loadbalancer node metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "TCP Syn Retransmissions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    {
     "format": "none",
     "label": "Syn restans per second (5m rate)"
    }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_netstat_TcpExt_TCPSynRetrans{fqdn=~\"fe-pages-.*\", env=\"gprd\"}[30s])) by (fqdn)",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "TCP Resets (sent)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    {
     "format": "short",
     "label": "TCP resets per second (5m rate)"
    }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_OutRsts{fqdn=~\"fe-pages-.*\", env=\"gprd\"}[30s])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Established TCP connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    {
     "format": "short",
     "label": "currently established TCP connections"
    }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{fqdn=~\"fe-pages-.*\", env=\"gprd\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Node network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{fqdn=~\"fe-pages-.*\", env=\"gprd\"}[30s]))",
     "legendFormat": "Egress {{fqdn}}"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{fqdn=~\"fe-pages-.*\", env=\"gprd\"}[30s]))",
     "legendFormat": "Ingress {{fqdn}}"
    }
   ]
  },
  {
   "title": "HAProxy load imbalance",
   "type": "graph",
   "description": "This is the standard deviation of connection distribution. This should be as close to 0 as possible. If this is higher, this means another load balancer is taking more connections than the others.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "stddev(node_netstat_Tcp_CurrEstab{fqdn=~\"fe-pages-.*\", env=\"gprd\"})or vector(0)",
     "legendFormat": "HAProxy load imbalance"
    }
   ]
  },
  { "title": "References", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "GitLab.com Traffic curve (as a reference - excluding pages)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(backend_code:haproxy_server_http_responses_total:rate5m{backend!=\"pages_http\"})"
    }
   ]
  }
 ]
}