{
 "title": "product: Error Budgets - learn",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/1299969292 at Thu May 27 20:37:16 UTC 2021",
 "tags": [
  "managed",
  "product",
  "product performance"
 ],
 "time": { "from": "now-28d", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 400 },
   "content": "### [Error budget](https://about.gitlab.com/handbook/engineering/error-budgets/)\n\nThese error budget panels show an aggregate of SLIs across all components.\nHowever, not all components have been implemented yet.\n\nThe [handbook](https://about.gitlab.com/handbook/engineering/error-budgets/)\nexplains how these budgets are used.\n\nRead more about how the error budgets are calculated in the\n[stage group dashboard documentation](https://docs.gitlab.com/ee/development/stage_group_dashboards.html#error-budget).\n\nThe error budget is compared to our SLO of 99.95% and is always in\na range of 28 days from the selected end date in Grafana.\n\n### Availability\n\nThe availability shows the percentage of operations labeled with one of the\ncategories owned by learn with satisfactory completion.\n\n### Budget remaining\n\nThe error budget in minutes is calculated based on the 99.95%.\nThere are 40320 minutes in 28 days, we allow 0.05% of failures, which\nmeans the budget in minutes is 20 minutes.\n\nThe budget remaining shows how many minutes have not been spent in the\npast 28 days.\n\n### Minutes spent\n\nThis shows the total minutes spent over the past 28 days.\n\nFor example, if there were 403200 (28 * 24 * 60) operations in 28 days.\nThis would be 1 every minute. If 10 of those were unsatisfactory, that\nwould mean 10 minutes of the budget were spent.\n"
  },
  {
   "title": "Applied Machine Learning's Error Budgets (past 28d)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "# Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    )\n  ),\n1)\n",
     "legendFormat": "%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "# Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    )\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "Budget remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 100 },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209\n-\n(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 104 },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209\n-\n(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n\n"
    }
   ]
  },
  {
   "title": "Budget spent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n"
    }
   ]
  },
  {
   "title": "Extra links",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 100 },
   "content": "- [Applied Machine Learning's handbook page](https://about.gitlab.com/handbook/product/categories/#applied-ml-group)\n* [Grafana: Applied Machine Learning's group dashboard](/d/group-learn-applied_ml?)\n\n"
  },
  {
   "title": "DataOps's Error Budgets (past 28d)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 200 },
   "targets": [
    {
     "expr": "# Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    )\n  ),\n1)\n",
     "legendFormat": "%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 204 },
   "targets": [
    {
     "expr": "# Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    )\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "Budget remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 200 },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209\n-\n(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 204 },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209\n-\n(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n\n"
    }
   ]
  },
  {
   "title": "Budget spent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 200 },
   "targets": [
    {
     "expr": "(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 204 },
   "targets": [
    {
     "expr": "(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"dataops\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n"
    }
   ]
  },
  {
   "title": "Extra links",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 200 },
   "content": "- [DataOps's handbook page](https://about.gitlab.com/handbook/product/categories/#dataops-group)\n* [Grafana: DataOps's group dashboard](/d/group-learn-dataops?)\n\n"
  },
  {
   "title": "MLOps's Error Budgets (past 28d)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 }
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 300 },
   "targets": [
    {
     "expr": "# Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    )\n  ),\n1)\n",
     "legendFormat": "%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 304 },
   "targets": [
    {
     "expr": "# Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    )\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "Budget remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 300 },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209\n-\n(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 304 },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209\n-\n(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n\n"
    }
   ]
  },
  {
   "title": "Budget spent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 300 },
   "targets": [
    {
     "expr": "(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 304 },
   "targets": [
    {
     "expr": "(\n  (\n     1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum by ()(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      )\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum by ()(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"mlops\"}[28d]\n    )\n  ),\n1)\n\n  ) * 2419200\n)\n"
    }
   ]
  },
  {
   "title": "Extra links",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 300 },
   "content": "- [MLOps's handbook page](https://about.gitlab.com/handbook/product/categories/#mlops-group)\n* [Grafana: MLOps's group dashboard](/d/group-learn-mlops?)\n\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./product/learn.error_budget.jsonnet)\n"
  }
 ]
}