{
 "title": "product: Performance - Enablement",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5489742955 at Wed Nov  8 15:25:41 UTC 2023",
 "tags": [
  "managed",
  "product",
  "product performance"
 ],
 "time": { "from": "now-30d", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "function", "query": "min, mean, median, p90, max" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "### Synthetic tests of GitLab.com pages for the Enablement group.\n\nFor more information, please see: https://about.gitlab.com/handbook/product/product-processes/#page-load-performance-metrics\n\n\n\n"
  },
  { "title": "Global Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Basic Global Search - Projects",
   "type": "graph",
   "description": "https://gitlab.com/search?utf8=%E2%9C%93&snippets=&scope=&repository_ref=&search=gitlab",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Basic_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Basic_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Basic_Search_Projects.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Advanced Global Search - Projects",
   "type": "graph",
   "description": "https://gitlab.com/search?utf8=%E2%9C%93&snippets=&scope=&repository_ref=&search=gitlab&group_id=6543",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Advanced_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Advanced_Search_Projects.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Advanced_Search_Projects.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Advanced Global Search - Code",
   "type": "graph",
   "description": "https://gitlab.com/search?group_id=6543&repository_ref=&scope=blobs&search=gitlab&snippets=",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Advanced_Search_Code.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Advanced_Search_Code.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Advanced_Search_Code.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  }
 ]
}