{
 "title": "Product Analytics",
 "description": "Dashboard for monitoring the product analytics service.",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dashboardCluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({namespace=\"analytics\"},cluster)"
    }
   },
   { "name": "dashboardMimirDataSource", "label": "Mimir data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Kafka Ready Replicas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"analytics\", cluster=\"$dashboardCluster\", statefulset=\"gitlab-product-analytics-kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Ready Replicas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"analytics\", cluster=\"$dashboardCluster\", statefulset=\"gitlab-product-analytics-vector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zookeeper Ready Replicas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"analytics\", cluster=\"$dashboardCluster\", statefulset=\"gitlab-product-analytics-zookeeper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cube Workers Ready Replicas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"analytics\", cluster=\"$dashboardCluster\", statefulset=\"gitlab-product-analytics-cube-cubestore-workers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cube Routers Ready Replicas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"analytics\", cluster=\"$dashboardCluster\", statefulset=\"gitlab-product-analytics-cube-cubestore-router\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analytics Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", cluster=\"$dashboardCluster\", namespace=\"analytics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analytics Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by(container) (container_memory_usage_bytes{job=\"kubelet\", cluster=\"$dashboardCluster\", namespace=\"analytics\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}