{
 "title": "Product Analytics Service Health",
 "tags": [
  "unmanaged",
  "protected"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dashboardCluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "dashboardLokiDataSource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Kafka consumer group lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{cluster=\"$dashboardCluster\"}) by (consumergroup, topic) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSL errors",
   "type": "timeseries",
   "description": "SSL errors from Vector, Kafka, or the Snowplow Enricher",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"vector\", pod_name=~`^$dashboardCluster\\-.*$`} |~ `SSL handshake failed` [$__interval])) or vector(0)",
     "legendFormat": "Vector errors"
    },
    {
     "expr": "sum(count_over_time({container_name=\"kafka\", pod_name=~`^$dashboardCluster\\-.*$`} |~ `SSL handshake failed` [$__interval])) or vector(0)",
     "legendFormat": "Kafka errors"
    },
    {
     "expr": "sum(count_over_time({container_name=\"snowplow-enricher\", pod_name=~`^$dashboardCluster\\-.*$`} |~ `SSL handshake failed` [$__interval])) or vector(0)",
     "legendFormat": "Snowplow Enricher Errors"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "table",
   "description": "Status of the certificates. Values are True, False or Unknown.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(avg by (name, namespace, condition, exported_namespace) (certmanager_certificate_ready_status{cluster=\"$dashboardCluster\"} == 1), \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    },
    {
     "expr": "label_join(avg by (name, namespace, exported_namespace) (certmanager_certificate_renewal_timestamp_seconds{cluster=\"$dashboardCluster\"} - time()), \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    },
    {
     "expr": "label_join(avg by (name, namespace, exported_namespace) (certmanager_certificate_expiration_timestamp_seconds{cluster=\"$dashboardCluster\"} - time()), \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    }
   ]
  },
  {
   "title": "ClickHouse Row Inserts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(ClickHouse_InsertedRows{cluster=\"$dashboardCluster\"}[$__rate_interval])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "ClickHouse Database Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ClickHouse_NumberOfDatabases{cluster=\"$dashboardCluster\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Vector Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"vector\",severity=\"ERROR\",pod_name=~`^$dashboardCluster\\-.*$`} |~ \"WARN\"[$__interval])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Vector errors from log-based metrics ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "stackdriver_k_8_s_container_logging_googleapis_com_user_vector_errors{cluster=\"$dashboardCluster\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Vector Enriched Events Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_events_total{component_id=\"clickhouse_enriched_events\",host=~`^$dashboardCluster\\-.*$`}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vector Bad Events Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(vector_component_sent_events_total{component_id=\"clickhouse_bad_events\",host=~`^$dashboardCluster\\-.*$`}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Vector Error Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{container_name=\"vector\",severity=\"ERROR\",pod_name=~`^$dashboardCluster\\-.*$`} |~ \"WARN\""
    }
   ]
  },
  {
   "title": "Cube API Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"cube-api\", pod_name=~`^$dashboardCluster\\-.*$`}[$__interval])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Cube Error Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "{container_name=\"cube-api\", pod_name=~`^$dashboardCluster\\-.*$`}"
    }
   ]
  },
  {
   "title": "Configurator logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "{container_name=\"snowplow-configurator\", pod_name=~`^$dashboardCluster\\-.*$`} != `/healthz`"
    }
   ]
  }
 ]
}