{
 "title": "product: Performance - Verify",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6762450133 at Thu May  2 07:54:30 UTC 2024",
 "tags": [
  "managed",
  "product",
  "product performance"
 ],
 "time": { "from": "now-30d", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   { "name": "function", "query": "min, mean, median, p90, max" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "### Synthetic tests of GitLab.com pages for the Verify group.\n\nFor more information, please see: https://about.gitlab.com/handbook/product/product-processes/#page-load-performance-metrics\n\n\n\n"
  },
  { "title": "Pipeline Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Pipeline - List",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_List.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_List.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_List.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Pipeline - Filtered List",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines?page=1&scope=all&username=stanhu&ref=master",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_ListFiltered.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_ListFiltered.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_ListFiltered.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Pipeline - Schedules",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipeline_schedules",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Schedules.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Schedules.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Schedules.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Pipeline - Charts",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines/charts",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Charts.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Charts.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Charts.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Job - List",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/jobs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1021 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Job_List.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Job_List.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Job_List.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Job - Detail",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/jobs/549614535",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1021 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Job_Detail.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Job_Detail.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Job_Detail.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "Pipeline Page", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Pipeline - View",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines/145395337/",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_View.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_View.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_View.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Pipeline - DAG",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines/145395337/dag",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_DAG.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_DAG.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_DAG.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Pipeline - Jobs",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines/145395337/builds",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Jobs.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Jobs.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Jobs.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Pipeline - Failed Jobs",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines/761771916/failures",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Failed_Jobs.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Failed_Jobs.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Failed_Jobs.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Pipeline - Tests",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines/852269772/test_report",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2021 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Test_Report.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Test_Report.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Test_Report.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "Pipeline Authoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "Pipeline Editor - Home",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/ci/editor",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Editor.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Editor.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_Editor.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "Testing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 } },
  {
   "title": "Code Quality",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/pipelines/145395337/codequality_report",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_CodeQuality.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_CodeQuality.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Pipeline_CodeQuality.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Code Coverage",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/graphs/master/charts",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Testing_CodeCoverageGraph.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Testing_CodeCoverageGraph.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Verify_Testing_CodeCoverageGraph.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  }
 ]
}