{
 "title": "product: Performance - Create",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6161549649 at Tue Feb 13 12:55:54 UTC 2024",
 "tags": [
  "managed",
  "product",
  "product performance"
 ],
 "time": { "from": "now-30d", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "function", "query": "min, mean, median, p90, max" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "### Synthetic tests of GitLab.com pages for the Create group.\n\nFor more information, please see: https://about.gitlab.com/handbook/product/product-processes/#page-load-performance-metrics\n\n\n\n"
  },
  { "title": "Soure Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "MR List",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/merge_requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_MR_List.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_MR_List.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_MR_List.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "MR Detail - Small",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34944",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_MR_Small.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_MR_Small.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_MR_Small.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "MR Detail - Large",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/22439",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_MR_Large.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_MR_Large.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_MR_Large.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Repo Nav - Small",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/language-tools/go/linters/goargs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_Repo_Small.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_Repo_Small.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_Repo_Small.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Repo Nav - Large",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-org/gitlab/-/tree/master",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1021 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_Repo_Large.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_Repo_Large.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.SourceCode_Repo_Large.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "Editor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Snippets - Explore",
   "type": "graph",
   "description": "https://gitlab.com/explore/snippets",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Explore.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Explore.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Explore.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Snippets - Textual",
   "type": "graph",
   "description": "https://gitlab.com/snippets/1985939",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Textual.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Textual.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Textual.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Snippets - Markdown",
   "type": "graph",
   "description": "https://gitlab.com/snippets/1985940",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Markdown.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Markdown.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Markdown.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Snippets - Multi-file",
   "type": "graph",
   "description": "https://gitlab.com/snippets/2020132",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Multifile.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Multifile.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_Snippets_Multifile.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "WebIDE - about.gitlab.com",
   "type": "graph",
   "description": "https://gitlab.com/-/ide/project/gitlab-com/www-gitlab-com/edit/master/-/",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2021 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_WebIDE_about_repo.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_WebIDE_about_repo.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_WebIDE_about_repo.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "WebIDE - Team page",
   "type": "graph",
   "description": "https://gitlab.com/-/ide/project/gitlab-com/www-gitlab-com/edit/master/-/data/team.yml",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2021 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_WebIDE_team_page.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_WebIDE_team_page.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_WebIDE_team_page.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Single File Editor - Team.yml",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/www-gitlab-com/-/edit/master/data/team.yml",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2031 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_SingleFile_team_page.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_SingleFile_team_page.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Editor_SingleFile_team_page.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  { "title": "Knowledge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "Design - Collection",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/issues/1/designs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Design_Collection.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Design_Collection.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Design_Collection.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Design - Single Image",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/issues/1/designs/10-2500x1667.jpg",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Design_Single.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Design_Single.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Design_Single.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - History",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/many-changes/history",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_History.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_History.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_History.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - Pages",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/pages",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Pages.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Pages.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Pages.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - AsciiDoc",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/formats/asciidoc/formatted-100kb",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3021 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_AsciiDoc.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_AsciiDoc.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_AsciiDoc.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - Page 5",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/pages?page=5",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3021 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Page5.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Page5.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Page5.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - RDoc",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/formats/rdoc/formatted-100kb",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3031 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_RDoc.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_RDoc.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_RDoc.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - Markdown",
   "type": "graph",
   "description": "\t\thttps://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/formats/markdown/formatted-100kb",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3031 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Markdown.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Markdown.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Markdown.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Wiki - Org",
   "type": "graph",
   "description": "https://gitlab.com/gitlab-com/create-knowledge-load-performance-tests/-/wikis/formats/org/formatted-100kb",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3041 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Org.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Org.chrome.cable.browsertime.statistics.visualMetrics.LastVisualChange.$function, 10)"
    },
    {
     "target": "aliasByNode(sitespeed_io.desktop.gitlab.pageSummary.gitlab_com.Knowledge_Wiki_Org.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  }
 ]
}