{
 "title": "Prometheus Performance",
 "tags": [ "prometheus" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "label_values(up{job=\"prometheus\"}, environment)"
   },
   {
    "name": "fqdn",
    "query": "label_values(up{job=\"prometheus\",env=\"$environment\"}, fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(process_resident_memory_bytes{job=\"prometheus\",environment=\"$environment\",fqdn=~\"$fqdn\"}[$__interval]) \n* on (instance) group_left (version) prometheus_build_info{environment=\"$environment\",fqdn=~\"$fqdn\"}",
     "legendFormat": "RSS {{fqdn}} - {{version}}"
    },
    {
     "expr": "max_over_time(go_memstats_alloc_bytes{job=\"prometheus\",environment=\"$environment\",fqdn=~\"$fqdn\"}[$__interval])",
     "legendFormat": "Go Alloc {{fqdn}}"
    },
    {
     "expr": "increase(prometheus_tsdb_compaction_duration_seconds_count{environment=\"$environment\",fqdn=~\"$fqdn\"}[$__interval])",
     "legendFormat": "Compaction {{fqdn}}"
    }
   ]
  },
  {
   "title": "Peak over last hour",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  max_over_time(process_resident_memory_bytes{job=\"prometheus\",environment=\"$environment\",fqdn=~\"$fqdn\"}[$__interval])\n  /\n  quantile_over_time(0.1, process_resident_memory_bytes{job=\"prometheus\",environment=\"$environment\",fqdn=~\"$fqdn\"}[1h])\n)\n* on (instance) group_left (version) prometheus_build_info{environment=\"$environment\",fqdn=~\"$fqdn\"}\n\n",
     "legendFormat": "{{fqdn}} - {{version}}"
    }
   ]
  },
  {
   "title": "Go Alloc Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\",environment=\"$environment\",fqdn=~\"$fqdn\"}[$__interval])",
     "legendFormat": "{{fqdn}} - {{version}}"
    }
   ]
  }
 ]
}