{
 "title": "Public Dashboard Splashscreen",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "content": "\n# GitLab Public Dashboards\n\nWelcome to the GitLab public dashboard. GitLab [values transparency](https://about.gitlab.com/handbook/values/#transparency), so we maintain a public copy of our internal dashboards.\n\nDue to privacy reasons and more strict query limitations not all dashboards may work correctly.\n\nWe also sync a copy of the [dashboard source](https://gitlab.com/gitlab-org/grafana-dashboards).\n\nSome dashboards are also [automatically generated](https://gitlab.com/gitlab-com/runbooks/tree/master/dashboards) using [grafonnet-lib](https://github.com/grafana/grafonnet-lib).\n\n"
  },
  {
   "title": "Web/API Apdex",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_apdex:ratio{env=\"gprd\",type=~\"(api|web)\"}[$__interval])) by (tier, type) ",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Gitaly Apdex",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_apdex:ratio{env=\"gprd\",type=~\"gitaly\"}[$__interval])) by (tier, type) ",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Registry Apdex",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(gitlab_service_apdex:ratio{env=\"gprd\",type=~\"registry\"}[$__interval])) by (tier, type) ",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}