{
 "title": "public: GitLab Dashboards",
 "tags": [
  "managed",
  "public"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   { "name": "environment", "query": "gprd" }
  ]
 },
 "panels": [
  { "title": "Welcome", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "content": "# GitLab Public Dashboards\n\nWelcome to the GitLab public dashboard. GitLab [values transparency](https://about.gitlab.com/handbook/values/#transparency),\nso we maintain a public copy of our internal dashboards.\n\nDue to privacy reasons and more strict query limitations not all dashboards may work correctly.\n\nWe also sync a copy of the [dashboard source](https://gitlab.com/gitlab-org/grafana-dashboards).\n\nSome dashboards are also [automatically generated](https://gitlab.com/gitlab-com/runbooks/tree/master/dashboards)\nusing [grafonnet-lib](https://github.com/grafana/grafonnet-lib).\n"
  },
  { "title": "FRONTEND SERVICES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1001 },
   "content": "This graphs show the frontend services that GitLab customer traffic will be initially handled by. Any issues in this\nfleet are more likely to be user-impacting.\n"
  },
  {
   "title": "Web Frontend: gitlab.com web traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1100 }
  },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1101 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1101 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"web\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"web\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"web\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"web\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"web\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"web\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"main\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"main\"}\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"main\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"main\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"\"}\n",
     "legendFormat": "upper normal (legacy)"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"web\", stage=\"\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"web\", stage=\"\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal (legacy)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1101 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"web\", stage=\"main\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "API: gitlab.com/api traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1200 } },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1201 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"api\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"api\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"api\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"api\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"api\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"api\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"api\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1201 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"api\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"api\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"api\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"api\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"api\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"api\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"api\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"api\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"api\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"api\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"api\", stage=\"main\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"api\", stage=\"main\"}\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"api\", stage=\"main\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"api\", stage=\"main\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"api\", stage=\"\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"api\", stage=\"\"}\n",
     "legendFormat": "upper normal (legacy)"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"api\", stage=\"\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"api\", stage=\"\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal (legacy)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1201 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"api\", stage=\"main\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "Git: git ssh and https traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1300 } },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1301 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"git\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"git\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"git\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"git\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"git\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"git\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"git\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1301 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"git\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"git\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"git\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"git\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"git\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"git\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"git\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"git\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"git\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"git\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"git\", stage=\"main\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"git\", stage=\"main\"}\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"git\", stage=\"main\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"git\", stage=\"main\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"git\", stage=\"\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"git\", stage=\"\"}\n",
     "legendFormat": "upper normal (legacy)"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"git\", stage=\"\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"git\", stage=\"\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal (legacy)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1301 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"git\", stage=\"main\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "CI Runners", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1400 } },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1401 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"ci-runners\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"ci-runners\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1401 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"ci-runners\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"ci-runners\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1401 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"ci-runners\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"ci-runners\", stage=\"\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"ci-runners\", stage=\"\"}\n",
     "legendFormat": "upper normal (legacy)"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"ci-runners\", stage=\"\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"ci-runners\", stage=\"\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal (legacy)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1401 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "Container Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1500 } },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1501 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"registry\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"registry\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"registry\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"registry\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"registry\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"registry\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min(\n  min_over_time(\n    gitlab_service_apdex:ratio{environment=\"$environment\", type=\"registry\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1501 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"registry\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"registry\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"registry\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"registry\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"registry\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"registry\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max(\n  max_over_time(\n    gitlab_service_errors:ratio{environment=\"$environment\", type=\"registry\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1501 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"registry\", stage=\"main\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"registry\", stage=\"\"}[$__interval]\n  )\n) by (type)\n",
     "legendFormat": "{{ type }} service (legacy)"
    },
    {
     "expr": "max(\n  avg_over_time(\n    gitlab_service_ops:rate{environment=\"$environment\", type=\"registry\", stage=\"main\"}[$__interval] offset 1w\n  )\n) by (type)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"registry\", stage=\"main\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"registry\", stage=\"main\"}\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"registry\", stage=\"main\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"registry\", stage=\"main\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal"
    },
    {
     "expr": "gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"registry\", stage=\"\"} +\n2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"registry\", stage=\"\"}\n",
     "legendFormat": "upper normal (legacy)"
    },
    {
     "expr": "avg(\n  clamp_min(\n    gitlab_service_ops:rate:prediction{environment=\"$environment\", type=\"registry\", stage=\"\"} -\n    2 * gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\", type=\"registry\", stage=\"\"},\n    0\n  )\n)\n",
     "legendFormat": "lower normal (legacy)"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1501 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{environment=\"$environment\", type=\"registry\", stage=\"main\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  }
 ]
}