{
 "title": "Puma vs. Unicorn Node stats (9 prod node comparison)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "type", "query": "web,api" }
  ]
 },
 "panels": [
  {
   "title": "avg memory puma",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{fqdn=~\"^...-0[1-9].*\", type=\"$type\"} - node_memory_MemAvailable_bytes{fqdn=~\"^...-0[1-9].*\", type=\"$type\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(node_memory_SwapTotal_bytes{fqdn=~\"^...-0[1-9].*\", type=\"$type\"} - node_memory_SwapFree_bytes{fqdn=~\"^...-0[1-9].*\", type=\"$type\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "avg(node_memory_MemTotal_bytes{fqdn=~\"^...-0[1-9].*\", type=\"$type\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(node_memory_SwapTotal_bytes{fqdn=~\"^...-0[1-9].*\", type=\"$type\"})",
     "legendFormat": "Swap Total"
    }
   ]
  },
  {
   "title": "avg memory unicorn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{fqdn=~\"^...-1[1-9].*\", type=\"$type\"} - node_memory_MemAvailable_bytes{fqdn=~\"^...-1[1-9].*\", type=\"$type\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(node_memory_SwapTotal_bytes{fqdn=~\"^...-1[1-9].*\", type=\"$type\"} - node_memory_SwapFree_bytes{fqdn=~\"^...-1[1-9].*\", type=\"$type\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "avg(node_memory_MemTotal_bytes{fqdn=~\"^...-1[1-9].*\", type=\"$type\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(node_memory_SwapTotal_bytes{fqdn=~\"^...-1[1-9].*\", type=\"$type\"})",
     "legendFormat": "Swap Total"
    }
   ]
  },
  {
   "title": "avg CPU usage puma",
   "type": "graph",
   "description": "Percentage of all CPU cores/hyperthreads",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "% of all CPUs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{fqdn=~\"^...-0[1-9].*\", type=\"$type\", mode !=\"idle\"}[$__interval])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "avg CPU usage unicorn",
   "type": "graph",
   "description": "Percentage of all CPU cores/hyperthreads",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "% of all CPUs" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{fqdn=~\"^...-1[1-9].*\", type=\"$type\", mode !=\"idle\"}[$__interval])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}