{
 "title": "Puma/Unicorn on Canary",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   { "name": "environment", "query": "gprd,gstg" },
   { "name": "prometheus_app", "query": "prometheus" },
   {
    "name": "node",
    "label": "Puma node",
    "query": "label_values(puma_workers,fqdn)"
   },
   {
    "name": "node2",
    "label": "Unicorn node",
    "query": "label_values(unicorn_workers,fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Puma workhorse req/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{fqdn=\"$node\", environment=\"$environment\",job=\"gitlab-workhorse-web\", stage=\"cny\", route!=\"^/-/health$\"}[1m])) / count(gitlab_workhorse_http_in_flight_requests{ fqdn=\"$node\",stage=\"cny\", type=\"web\"})",
     "legendFormat": "puma web"
    },
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{fqdn=\"$node\",environment=\"$environment\",job=\"gitlab-workhorse-api\",stage=\"cny\", route!=\"^/-/health$\"}[1m])) / count(gitlab_workhorse_http_in_flight_requests{ fqdn=\"$node\",stage=\"cny\", type=\"api\"})",
     "legendFormat": "puma api"
    },
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{fqdn=\"$node\",environment=\"$environment\",job=\"gitlab-workhorse-git\",stage=\"cny\", route!=\"^/-/health$\"}[1m])) / count(gitlab_workhorse_http_in_flight_requests{fqdn=\"$node\", stage=\"cny\", type=\"git\"})",
     "legendFormat": "puma git"
    }
   ]
  },
  {
   "title": "Unicorn workhorse req/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{fqdn=\"$node2\", environment=\"$environment\",job=\"gitlab-workhorse-web\", route!=\"^/-/health$\"}[1m])) / count(gitlab_workhorse_http_in_flight_requests{ fqdn=\"$node2\", type=\"web\"})",
     "legendFormat": "unicon web"
    },
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{fqdn=\"$node2\",environment=\"$environment\",job=\"gitlab-workhorse-api\", route!=\"^/-/health$\"}[1m])) / count(gitlab_workhorse_http_in_flight_requests{ fqdn=\"$node2\", type=\"api\"})",
     "legendFormat": "unicon api"
    },
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{fqdn=\"$node2\",environment=\"$environment\",job=\"gitlab-workhorse-git\",route!=\"^/-/health$\"}[1m])) / count(gitlab_workhorse_http_in_flight_requests{fqdn=\"$node2\", type=\"git\"})",
     "legendFormat": "unicon git"
    }
   ]
  },
  {
   "title": "Puma Workhorse HTTP request Duration (web/get/200s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{fqdn=\"$node\", environment=\"$environment\",method=\"get\",code=\"200\", type=\"web\", route!=\"^/-/health$\", stage=\"cny\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unicorn HTTP request Duration (web/get/200s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{fqdn=\"$node2\", environment=\"$environment\",method=\"get\",code=\"200\", type=\"web\", route!=\"^/-/health$\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "puma memory usage by type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_AnonPages_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AnonPages",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Buffers_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Buffers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Slab_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Slab",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Cached_bytes{fqdn=\"$node\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Cached",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "puma memory Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{fqdn=\"$node\"} - node_memory_MemAvailable_bytes{fqdn=\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{fqdn=\"$node\"} - node_memory_SwapFree_bytes{fqdn=\"$node\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_MemTotal_bytes{fqdn=\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{fqdn=\"$node\"}",
     "legendFormat": "Swap Total"
    }
   ]
  },
  {
   "title": "unicorn memory usage by type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_AnonPages_bytes{fqdn=\"$node2\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AnonPages",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Buffers_bytes{fqdn=\"$node2\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Buffers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Slab_bytes{fqdn=\"$node2\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Slab",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Cached_bytes{fqdn=\"$node2\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Cached",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unicorn Memory Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{fqdn=\"$node2\"} - node_memory_MemAvailable_bytes{fqdn=\"$node2\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{fqdn=\"$node2\"} - node_memory_SwapFree_bytes{fqdn=\"$node2\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_MemTotal_bytes{fqdn=\"$node2\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{fqdn=\"$node2\"}",
     "legendFormat": "Swap Total"
    }
   ]
  },
  {
   "title": "Puma CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(instance:node_cpu_utilization:ratio{fqdn=\"$node\"}[$__interval])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Unicorn CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(instance:node_cpu_utilization:ratio{fqdn=\"$node2\"}[$__interval])",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}