{
 "title": "Q3 OKR - Improve performance by 25%",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "function", "query": "min, mean,median,p90,max" }
  ]
 },
 "panels": [
  {
   "title": "Q3 OKR - Improve the response time performance of the top 5 most visited pages on GitLab.com by 25%",
   "type": "text",
   "description": "https://gitlab.com/gitlab-com/Product/-/issues/1344",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "### Q3 OKR - Improve the response time performance of the top 5 most visited pages on GitLab.com by 25%\n\nFor more information, please see: https://gitlab.com/gitlab-com/Product/-/issues/1344\n\n\n\n"
  },
  {
   "title": "Project Home",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.GitLab_Project_Home.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Issue List",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.GitLab_Issue_list.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "Issue Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.GitLab_Issue_Detail.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "MR List",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.GitLab_Merge_List.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  },
  {
   "title": "MR Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sitespeed_io.desktop.pageSummary.gitlab_com.GitLab_Merge_Detail.chrome.cable.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 10)"
    }
   ]
  }
 ]
}