{
 "title": "qmnguyen0711/api: Rails Controller Copy",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/950300858 at Thu Jan  7 21:13:55 UTC 2021",
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "type", "query": "api" },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "controller",
    "query": "label_values(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment=\"$environment\", type=\"$type\"}, controller)"
   },
   {
    "name": "action",
    "query": "label_values(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment=\"$environment\", type=\"$type\", controller=\"$controller\"}, action)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n         \n${controller:lucence}"
   }
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(controller_action:gitlab_transaction_duration_seconds:p99{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])",
     "legendFormat": "{{ action }} - p99"
    },
    {
     "expr": "avg_over_time(controller_action:gitlab_transaction_duration_seconds:p95{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])",
     "legendFormat": "{{ action }} - p95"
    },
    {
     "expr": "avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n/\navg_over_time(controller_action:gitlab_transaction_duration_seconds_count:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "{{ action }} - mean"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(controller_action:gitlab_transaction_duration_seconds_count:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  { "title": "SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "SQL Requests per Controller Request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn,instance) (\nrate(gitlab_sql_duration_seconds_count{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n)\n/\navg_over_time(controller_action:gitlab_transaction_duration_seconds_count:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "SQL Latency per Controller Request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(controller_action:gitlab_sql_duration_seconds_sum:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n/\navg_over_time(controller_action:gitlab_transaction_duration_seconds_count:rate1m{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "SQL Latency per SQL Request",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn,instance) (\nrate(gitlab_sql_duration_seconds_sum{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n)\n/\nsum without (fqdn,instance) (\nrate(gitlab_sql_duration_seconds_count{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n)\n",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Cache Operations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn, instance) (\nrate(gitlab_cache_operations_total{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n)\n",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  { "title": "Elasticsearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Elasticsearch Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (controller, action, le) (\n  rate(http_elasticsearch_requests_duration_seconds_bucket{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n))\n",
     "legendFormat": "{{ action }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (controller, action, le) (\n  rate(http_elasticsearch_requests_duration_seconds_bucket{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n))\n",
     "legendFormat": "{{ action }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (controller, action, le) (\n  rate(http_elasticsearch_requests_duration_seconds_bucket{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n))\n",
     "legendFormat": "{{ action }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (controller, action, le) (\n  rate(http_elasticsearch_requests_duration_seconds_bucket{action=~\"$action\",controller=\"$controller\",environment=\"$environment\",stage=\"$stage\",type=\"api\"}[$__interval])\n))\n",
     "legendFormat": "{{ action }} p99"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "options": {
    "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./api/rails-controller.dashboard.jsonnet)\n"
   },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./api/rails-controller.dashboard.jsonnet)\n"
  }
 ]
}