{
 "title": "Queue Detail",
 "tags": [
  "type:sidekiq",
  "detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "queue",
    "query": "label_values(sidekiq_jobs_completion_seconds_count{environment=\"$environment\", type=\"sidekiq\"}, queue)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queue Attribute: Latency Sensitive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (queue) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__range])) by (queue, latency_sensitive)),\n  \"latency_sensitive\", \"unknown\", \"latency_sensitive\", \"\"\n)\n",
     "legendFormat": "{{ latency_sensitive }} ({{ queue }})"
    }
   ]
  },
  {
   "title": "Queue Attribute: Feature Category",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (queue) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__range])) by (queue, feature_category)),\n  \"feature_category\", \"unknown\", \"feature_category\", \"\"\n)\n",
     "legendFormat": "{{ feature_category }} ({{ queue }})"
    }
   ]
  },
  {
   "title": "Queue Attribute: Priority",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (queue) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__range])) by (queue, priority)),\n  \"priority\", \"unknown\", \"priority\", \"\"\n)\n",
     "legendFormat": "{{ priority }} ({{ queue }})"
    }
   ]
  },
  {
   "title": "Queue Attribute: External Dependencies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (queue) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__range])) by (queue, external_dependencies)),\n  \"external_dependencies\", \"none\", \"external_dependencies\", \"\"\n)\n",
     "legendFormat": "{{ external_dependencies }} ({{ queue }})"
    }
   ]
  },
  {
   "title": "Queue Attribute: Resource Boundary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n  topk by (queue) (1, sum(rate(sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__range])) by (queue, boundary)),\n  \"boundary\", \"none\", \"boundary\", \"\"\n)\n",
     "legendFormat": "{{ boundary }} ({{ queue }})"
    }
   ]
  },
  {
   "title": "Max Queuing Duration SLO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "vector(60.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\", latency_sensitive=\"no\"}\nor\nvector(10.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\", latency_sensitive=\"yes\"}\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Max Execution Duration SLO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "vector(300.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\", latency_sensitive=\"no\"}\nor\nvector(10.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\", latency_sensitive=\"yes\"}\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (queue, le) (\n  rate(sidekiq_jobs_queue_duration_seconds_bucket{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__interval])\n))\n",
     "legendFormat": "p95 {{ queue }}"
    }
   ]
  },
  {
   "title": "Execution Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 100 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (queue, le) (\n  rate(sidekiq_jobs_completion_seconds_bucket{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__interval])\n))\n",
     "legendFormat": "p95 {{ queue }}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (\n  rate(sidekiq_jobs_completion_seconds_count{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__interval])\n)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (\n  changes(sidekiq_jobs_failed_total{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__interval])\n)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Queue Time per Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (fqdn, queue, le) (\n  rate(sidekiq_jobs_queue_duration_seconds_bucket{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__interval])\n))\n",
     "legendFormat": "p95 {{ queue }} - {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Execution Time per Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 110 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (fqdn, queue, le) (\n  rate(sidekiq_jobs_completion_seconds_bucket{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__interval])\n))\n",
     "legendFormat": "p95 {{ queue }} - {{ fqdn }}"
    }
   ]
  },
  {
   "title": "QPS per Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn, queue) (\n  rate(sidekiq_jobs_completion_seconds_count{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__interval])\n)\n",
     "legendFormat": "{{ queue }} - {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Error Rate per Node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn, queue) (\n  changes(sidekiq_jobs_failed_total{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__interval])\n)\n",
     "legendFormat": "{{ queue }} - {{ fqdn }}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (queue, le) (\n  rate(sidekiq_jobs_cpu_seconds_bucket{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (queue, le) (\n  rate(sidekiq_jobs_cpu_seconds_bucket{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", queue=~\"$queue\"}[$__interval])\n))\n",
     "legendFormat": "{{ queue }} p90"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/sidekiq/queue-detail.dashboard.jsonnet)\n"
  }
 ]
}