{
 "title": "Rack::Attack Rollout",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Web Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (stage) (avg_over_time(gitlab_component_ops:rate{env=\"gprd\",monitor=\"global\",type=\"web\",component=\"puma\"}[$__interval]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "API Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (stage) (avg_over_time(gitlab_component_ops:rate{env=\"gprd\",monitor=\"global\",type=\"api\",component=\"puma\"}[$__interval]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Git Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (stage) (avg_over_time(gitlab_component_ops:rate{env=\"gprd\",monitor=\"global\",type=\"git\",component=\"puma\"}[$__interval]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Web 429 Responses by Feature Category",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (feature_category) (avg_over_time(sli_aggregations:http_requests_total_rate1m{env=\"gprd\",type=\"web\",status=\"429\"}[$__interval]))",
     "legendFormat": "{{feature_category}}"
    }
   ]
  },
  {
   "title": "API 429 Responses by Feature Category",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (feature_category) (avg_over_time(sli_aggregations:http_requests_total_rate1m{env=\"gprd\",type=\"api\",status=\"429\"}[$__interval]))",
     "legendFormat": "{{feature_category}}"
    }
   ]
  },
  {
   "title": "Git 429 Responses by Feature Category",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (feature_category) (avg_over_time(sli_aggregations:http_requests_total_rate1m{env=\"gprd\",type=\"git\",status=\"429\"}[$__interval]))",
     "legendFormat": "{{feature_category}}"
    }
   ]
  },
  {
   "title": "Web 429 Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (stage) (avg_over_time(sli_aggregations:http_requests_total_rate1m{env=\"gprd\",type=\"web\",status=\"429\"}[$__interval])) /\nsum by (stage) (avg_over_time(gitlab_component_ops:rate{env=\"gprd\",monitor=\"global\",type=\"web\",component=\"puma\"}[$__interval]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "API 429 Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (stage) (avg_over_time(sli_aggregations:http_requests_total_rate1m{env=\"gprd\",type=\"api\",status=\"429\"}[$__interval])) /\nsum by (stage) (avg_over_time(gitlab_component_ops:rate{env=\"gprd\",monitor=\"global\",type=\"api\",component=\"puma\"}[$__interval]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Git 429 Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (stage) (avg_over_time(sli_aggregations:http_requests_total_rate1m{env=\"gprd\",type=\"git\",status=\"429\"}[$__interval])) /\nsum by (stage) (avg_over_time(gitlab_component_ops:rate{env=\"gprd\",monitor=\"global\",type=\"git\",component=\"puma\"}[$__interval]))",
     "legendFormat": "{{stage}}"
    }
   ]
  }
 ]
}