{
 "title": "Rails Cache Overview [deprecated]",
 "tags": [
  "cache",
  "influxdb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "process_type", "label": "Process Type", "query": "rails,sidekiq,grape" },
   { "name": "database", "label": "Database", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "content": "![](https://media.giphy.com/media/l0HlKrB02QY0f1mbm/giphy.gif)"
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "content": "# InfluxDB is Deprecated\nInfluxDB is deprecated in 13.0. This dashboad will be removed after 2020-05-22.\n\n\n\n"
  },
  {
   "title": "Total Cache Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_duration_95th\" AS \"95th Percentile\", \"cache_duration_99th\" as \"99th Percentile\", \"cache_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Read Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_read_duration_95th\" AS \"95th Percentile\", \"cache_read_duration_99th\" as \"99th Percentile\", \"cache_read_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Write Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_write_duration_95th\" AS \"95th Percentile\", \"cache_write_duration_99th\" as \"99th Percentile\", \"cache_write_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Delete Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_delete_duration_95th\" AS \"95th Percentile\", \"cache_delete_duration_99th\" as \"99th Percentile\", \"cache_delete_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Exists Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_exists_duration_95th\" AS \"95th Percentile\", \"cache_exists_duration_99th\" as \"99th Percentile\", \"cache_exists_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Read Hits/Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "gitlab.transaction",
     "query": "SELECT \"cache_read_hit_count_mean\" AS \"Hit mean\", \"cache_read_miss_count_mean\" AS \"Miss mean\" FROM downsampled.\"[[process_type]]_transaction_cache_counts_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}