{
 "title": "Rails Controllers [deprecated]",
 "tags": [
  "controller",
  "influxdb",
  "migrate"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "action",
    "label": "Action",
    "query": "SHOW TAG VALUES FROM gitlab.downsampled.rails_transaction_counts_per_action WITH KEY = \"action\""
   },
   { "name": "database", "label": "Database", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Note", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "content": "![](https://media.giphy.com/media/l0HlKrB02QY0f1mbm/giphy.gif)"
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "content": "# InfluxDB is Deprecated\nInfluxDB is deprecated in 13.0. This dashboad will be removed after 2020-05-22.\n\nTry the new [Prometheus version of this dashboard](/d/rPsQXrImk/rails-controller)\n"
  },
  { "title": "Last Hour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\", 95) FROM rails_transactions WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"sql_duration\", 95) FROM rails_transactions WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\", 95) AS \"95th Percentile\" FROM rails_method_calls WHERE $timeFilter AND \"action\" =~ /^[[action]]$/ AND method =~ /^(Gitlab::Git|Rugged)/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "View Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"view_duration\", 95) FROM rails_transactions WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"cache_duration\", 95) FROM rails_transactions WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (sum(cache_read_hit_count) / (sum(cache_read_hit_count) + sum(cache_read_miss_count))) * 100 FROM rails_transactions WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"count\" AS \"Amount\" FROM downsampled.rails_transaction_counts_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"duration_95th\" AS \"95th Percentile\", \"duration_99th\" AS \"99th Percentile\", \"duration_mean\" AS \"Mean\" FROM downsampled.rails_transaction_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Queue Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"rails_queue_duration_95th\" AS \"95th Percentile\", \"rails_queue_duration_99th\" AS \"99th Percentile\", \"rails_queue_duration_mean\" AS \"Mean\" FROM downsampled.rails_transaction_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"cache_duration_95th\" AS \"95th Percentile\", \"cache_duration_99th\" AS \"99th Percentile\", \"cache_duration_mean\" AS \"Mean\" FROM downsampled.rails_transaction_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"duration_95th\" AS \"95th Percentile\", \"duration_99th\" AS \"99th Percentile\", \"duration_mean\" AS \"Mean\" FROM downsampled.rails_git_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Timings",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"sql_duration_95th\" AS \"95th Percentile\", \"sql_duration_99th\" AS \"99th Percentile\", \"sql_duration_mean\" AS \"Mean\", \"sql_duration_max\" AS \"Maximum\" FROM downsampled.rails_transaction_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "SQL Query Counts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"sql_count_95th\" AS \"95th Percentile\", \"sql_count_99th\" AS \"99th Percentile\", \"sql_count_mean\" AS \"Mean\", \"sql_count_max\" AS \"Maximum\" FROM downsampled.rails_transaction_sql_counts_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "SQL Timings Heatmap",
     "type": "heatmap",
     "description": "A heatmap of the 99th percentile of SQL timings",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rails_transactions",
       "query": "SELECT percentile(\"sql_duration\", 99) AS \"99th Percentile\" FROM rails_transactions WHERE $timeFilter AND action = '[[action]]' GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "action", "operator": "=", "value": "select tag value" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Read Hit/Miss Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"cache_read_hit_count_mean\" AS \"Hit mean\", \"cache_read_miss_count_mean\" AS \"Miss mean\" FROM downsampled.rails_transaction_cache_counts_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Method Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Method Call Wall Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_method",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration_95th\") AS \"value\" FROM downsampled.rails_method_call_timings_per_action_and_method WHERE $timeFilter AND \"action\" =~ /^[[action]]$/ GROUP BY \"method\", time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Method Call CPU Time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_method",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_duration_95th\") AS \"value\" FROM downsampled.rails_method_call_timings_per_action_and_method WHERE $timeFilter AND \"action\" =~ /^[[action]]$/ GROUP BY \"method\", time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Method Call Counts",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_method",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"call_count_95th\") AS \"value\" FROM downsampled.rails_method_call_timings_per_action_and_method WHERE $timeFilter AND \"action\" =~ /^[[action]]$/ GROUP BY \"method\", time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT allocated_memory_95th AS \"95th Percentile\", allocated_memory_99th AS \"99th Percentile\", allocated_memory_mean AS \"Mean\", allocated_memory_max AS \"Maximum\"  FROM downsampled.rails_allocated_memory_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}