{
 "title": "Rails Controllers 2 [deprecated]",
 "tags": [
  "controller",
  "influxdb"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "action",
    "label": "Action",
    "query": "SHOW TAG VALUES FROM gitlab.downsampled.rails_transaction_counts_per_action WITH KEY = \"action\""
   },
   { "name": "database", "label": "Database", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "content": "![](https://media.giphy.com/media/l0HlKrB02QY0f1mbm/giphy.gif)"
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "content": "# Deprecated - See [replacement dashboard](/d/rPsQXrImk/rails-controller)\nInfluxDB is deprecated in 13.0. This dashboad will be removed 2020-05-20"
  },
  { "title": "Last Hour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\", 95) FROM rails_transactions WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"sql_duration\", 95) FROM rails_transactions WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\", 95) AS \"95th Percentile\" FROM rails_method_calls WHERE $timeFilter AND \"action\" =~ /^[[action]]$/ AND method =~ /^(Gitlab::Git|Rugged)/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "View Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"view_duration\", 95) FROM rails_transactions WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"cache_duration\", 95) FROM rails_transactions WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (sum(cache_read_hit_count) / (sum(cache_read_hit_count) + sum(cache_read_miss_count))) * 100 FROM rails_transactions WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"count\" AS \"Amount\" FROM downsampled.rails_transaction_counts_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"duration_95th\" AS \"95th Percentile\", \"duration_99th\" AS \"99th Percentile\", \"duration_mean\" AS \"Mean\" FROM downsampled.rails_transaction_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Queue Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"rails_queue_duration_95th\" AS \"95th Percentile\", \"rails_queue_duration_99th\" AS \"99th Percentile\", \"rails_queue_duration_mean\" AS \"Mean\" FROM downsampled.rails_transaction_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "View Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"view_duration_95th\" AS \"95th Percentile\", \"view_duration_99th\" AS \"99th Percentile\", \"view_duration_mean\" AS \"Mean\" FROM downsampled.rails_transaction_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"cache_duration_95th\" AS \"95th Percentile\", \"cache_duration_99th\" AS \"99th Percentile\", \"cache_duration_mean\" AS \"Mean\" FROM downsampled.rails_transaction_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Git Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"duration_95th\" AS \"95th Percentile\", \"duration_99th\" AS \"99th Percentile\", \"duration_mean\" AS \"Mean\" FROM downsampled.rails_git_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "SQL Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"sql_duration_95th\" AS \"95th Percentile\", \"sql_duration_99th\" AS \"99th Percentile\", \"sql_duration_mean\" AS \"Mean\", \"sql_duration_max\" AS \"Maximum\" FROM downsampled.rails_transaction_timings_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Query Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"sql_count_95th\" AS \"95th Percentile\", \"sql_count_99th\" AS \"99th Percentile\", \"sql_count_mean\" AS \"Mean\", \"sql_count_max\" AS \"Maximum\" FROM downsampled.rails_transaction_sql_counts_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Timings Heatmap",
   "type": "heatmap",
   "description": "A heatmap of the 99th percentile of SQL timings",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rails_transactions",
     "query": "SELECT percentile(\"sql_duration\", 99) AS \"99th Percentile\" FROM rails_transactions WHERE $timeFilter AND action = '[[action]]' GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "action", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Cache Read Hit/Miss Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"cache_read_hit_count_mean\" AS \"Hit mean\", \"cache_read_miss_count_mean\" AS \"Miss mean\" FROM downsampled.rails_transaction_cache_counts_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "New Redis Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"new_redis_connections_95th\" AS \"95th Percentile\", \"new_redis_connections_99th\" AS \"99th Percentile\", \"new_redis_connections_mean\" AS \"Mean\", \"new_redis_connections_max\" AS \"Maximum\" FROM downsampled.rails_transaction_new_redis_connection_counts_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Method Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Method Call Wall Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"duration_95th\") AS \"value\" FROM downsampled.rails_method_call_timings_per_action_and_method WHERE $timeFilter AND \"action\" =~ /^[[action]]$/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Method Call CPU Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"cpu_duration_95th\") AS \"value\" FROM downsampled.rails_method_call_timings_per_action_and_method WHERE $timeFilter AND \"action\" =~ /^[[action]]$/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Method Call Counts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"call_count_95th\") AS \"value\" FROM downsampled.rails_method_call_timings_per_action_and_method WHERE $timeFilter AND \"action\" =~ /^[[action]]$/ GROUP BY \"method\", time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT allocated_memory_95th AS \"95th Percentile\", allocated_memory_99th AS \"99th Percentile\", allocated_memory_mean AS \"Mean\", allocated_memory_max AS \"Maximum\"  FROM downsampled.rails_allocated_memory_per_action WHERE $timeFilter AND \"action\" =~ /^[[action]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Transaction Details",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "transactions",
     "query": "SELECT \"duration\" AS \"Duration\", \"allocated_memory\" AS \"Memory\", \"sql_count\" AS \"Queries\", \"request_method\" AS \"Method\", \"action\" AS \"Action\", \"request_uri\" AS \"URI\" FROM \"rails_transactions\" WHERE $timeFilter AND \"action\" ='[[action]]' ORDER BY time DESC LIMIT 100",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ],
      [
       { "params": [ "method" ], "type": "field" }
      ],
      [
       { "params": [ "path" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}