{
 "title": "Rails [deprecated]",
 "tags": [
  "drilldown",
  "triage",
  "unmanaged",
  "deprecated"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "prometheus_app", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "content": "![](https://media.giphy.com/media/l0HlKrB02QY0f1mbm/giphy.gif)"
  },
  {
   "title": "Deprecation  Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 0 },
   "content": "# Deprecated ⚠️⚠️⚠️⚠️⚠️\n\nThis dashboard is deprecated, please consider switching over to the new service based dashboards:\n\n* [api](/d/api-main/api-overview)\n* [git](/d/git-main/git-overview)\n* [web](/d/web-main/web-overview)\n\n\n"
  },
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exceptions Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_transaction_event_rails_exception_total{environment=\"$environment\", stage=\"main\"}[$__interval]))",
       "legendFormat": "exception rate"
      },
      {
       "expr": "sum(rate(gitlab_transaction_event_rails_exception_total{environment=\"$environment\",  stage=\"cny\"}[$__interval]))",
       "legendFormat": "canary exception rate"
      }
     ]
    },
    {
     "title": "Exceptions Rate by Controller",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_transaction_event_rails_exception_total{stage=\"main\", environment=\"$environment\"}[$__interval])) by (controller)",
       "legendFormat": "{{ controller }}"
      },
      {
       "expr": "sum(rate(gitlab_transaction_event_rails_exception_total{stage=\"cny\", environment=\"$environment\"}[$__interval])) by (controller)",
       "legendFormat": "cny { controller }}"
      }
     ]
    }
   ]
  },
  {
   "title": "500s (mtail)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web percentage of 500s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (type)(rate(rails_requests_completed{type=\"web\",status=~\"5..\",environment=\"$environment\"}[$__interval]))\n  /\nsum by (type)(rate(rails_requests_completed{type=\"web\",environment=\"$environment\"}[$__interval]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{type}} - {{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Git percentage of 500s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (type)(rate(rails_requests_completed{type=\"git\",status=~\"5..\",environment=\"$environment\"}[$__interval]))\n  /\nsum by (type)(rate(rails_requests_completed{type=\"git\",environment=\"$environment\"}[$__interval]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{type}} - {{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "API percentage of 500s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (type)(rate(rails_requests_completed{type=\"api\",status=~\"5..\",environment=\"$environment\"}[$__interval]))\n  /\nsum by (type)(rate(rails_requests_completed{type=\"api\",environment=\"$environment\"}[$__interval]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{type}} - {{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Web Latencies for 200s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(status:rails_requests_completed_seconds:p50{ environment=\"$environment\", type=\"web\", status=\"200\"}[$__interval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "avg",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "max_over_time(status:rails_requests_completed_seconds:p50{ environment=\"$environment\", type=\"web\", status=\"200\"}[$__interval])",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "p95",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(status:rails_requests_completed_seconds:p95{environment=\"$environment\", type=\"web\", status=\"200\"}[$__interval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "avg",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "max_over_time(status:rails_requests_completed_seconds:p95{environment=\"$environment\", type=\"web\", status=\"200\"}[$__interval])",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "API Latencies for 200s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(status:rails_requests_completed_seconds:p50{environment=\"$environment\", type=\"api\", status=\"200\"}[$__interval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "avg",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "max_over_time(status:rails_requests_completed_seconds:p50{environment=\"$environment\", type=\"api\", status=\"200\"}[$__interval])",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "p95",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(status:rails_requests_completed_seconds:p95{environment=\"$environment\", type=\"api\", status=\"200\"}[$__interval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "avg",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "max_over_time(status:rails_requests_completed_seconds:p95{environment=\"$environment\", type=\"api\", status=\"200\"}[$__interval])",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Git Latencies for 200s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(status:rails_requests_completed_seconds:p50{environment=\"$environment\", type=\"git\", status=\"200\"}[$__interval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "avg",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "max_over_time(status:rails_requests_completed_seconds:p50{environment=\"$environment\", type=\"git\", status=\"200\"}[$__interval])",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "p95",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(status:rails_requests_completed_seconds:p95{environment=\"$environment\", type=\"git\", status=\"200\"}[$__interval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "avg",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "max_over_time(status:rails_requests_completed_seconds:p95{environment=\"$environment\", type=\"git\", status=\"200\"}[$__interval])",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Rails Latencies Per Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "status:rails_requests_completed_seconds:p95{environment=\"$environment\", type=\"web\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "API",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "status:rails_requests_completed_seconds:p95{type=\"api\", environment=\"$environment\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Git",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "status:rails_requests_completed_seconds:p95{type=\"git\", environment=\"$environment\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Rails Requests Per Verb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(rails_requests_started{environment=\"$environment\", type=\"web\"}[1m])) without (instance, fqdn)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{verb}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "API",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(rails_requests_started{environment=\"$environment\", type=\"api\"}[1m])) without (instance, fqdn)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{verb}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Git",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(rails_requests_started{environment=\"$environment\", type=\"git\"}[1m])) without (instance, fqdn)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{verb}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Web Latencies Per Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "instance:rails_requests_completed_seconds:p50{type=\"web\", environment=\"$environment\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "p95",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "instance:rails_requests_completed_seconds:p95{type=\"web\", environment=\"$environment\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "API Latencies Per Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "instance:rails_requests_completed_seconds:p50{type=\"api\", environment=\"$environment\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "p95",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "instance:rails_requests_completed_seconds:p95{type=\"api\", environment=\"$environment\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Git Latencies Per Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "instance:rails_requests_completed_seconds:p50{type=\"git\", environment=\"$environment\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "p95",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "instance:rails_requests_completed_seconds:p95{type=\"git\", environment=\"$environment\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Web Latencies Per Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "status:rails_requests_completed_seconds:p50{environment=\"$environment\", type=\"web\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "p95",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "status:rails_requests_completed_seconds:p95{environment=\"$environment\", type=\"web\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "API Latencies Per Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "status:rails_requests_completed_seconds:p50{environment=\"$environment\", type=\"api\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "p95",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "status:rails_requests_completed_seconds:p95{environment=\"$environment\", type=\"api\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Git API Latencies Per Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "p50",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "status:rails_requests_completed_seconds:p50{environment=\"$environment\", type=\"git\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "p95",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "status:rails_requests_completed_seconds:p95{environment=\"$environment\", type=\"git\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{status}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Qeueus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "WIP: Rails Queues - gitlab_rails_queue_duration_seconds_bucket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, tier, type, le) (rate(gitlab_rails_queue_duration_seconds_bucket[$__interval]))"
    }
   ]
  },
  {
   "title": "WIP - gitlab_transaction_rails_queue_duration_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, tier, type) (rate(gitlab_transaction_rails_queue_duration_total{environment=\"$environment\", type=\"git\"}[$__interval]))",
     "legendFormat": "{{type}} service"
    },
    {
     "expr": "sum by (environment, tier, type) (rate(gitlab_transaction_rails_queue_duration_total{environment=\"$environment\", type=\"git\"}[$__interval] offset 1w))",
     "legendFormat": "1 week ago"
    },
    {
     "expr": "sum(rate(gitlab_transaction_rails_queue_duration_total{environment=\"$environment\", type=\"git\"}[1w]) + 1 * rate(gitlab_transaction_rails_queue_duration_total{environment=\"$environment\", type=\"git\"}[1w]))  by (environment, tier, type)",
     "legendFormat": "upper"
    }
   ]
  },
  {
   "title": "WIP - http_request_duration_seconds_bucket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, tier, type) (rate(http_request_duration_seconds_bucket{environment=\"$environment\", type=\"git\"}[$__interval]))",
     "legendFormat": "{{type}} service"
    },
    {
     "expr": "sum by (environment, tier, type) (rate(http_request_duration_seconds_bucket{environment=\"$environment\", type=\"git\"}[$__interval] offset 1w))",
     "legendFormat": "1 week ago"
    }
   ]
  }
 ]
}