{
 "title": "Rails Controller",
 "tags": [ "rails" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(up{job=\"gitlab-unicorn\"}, environment)"
   },
   {
    "name": "type",
    "query": "label_values(up{job=\"gitlab-unicorn\",environment=\"$env\"}, type)"
   },
   {
    "name": "stage",
    "query": "label_values(up{job=\"gitlab-unicorn\",environment=\"$env\",type=\"$type\"}, stage)"
   },
   {
    "name": "controller",
    "query": "label_values(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment=\"$env\",type=\"$type\",stage=\"$stage\"}, controller)"
   },
   {
    "name": "action",
    "query": "label_values(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment=\"$env\",type=\"$type\",stage=\"$stage\",controller=\"$controller\"}, action)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{environment=\"$env\",controller=\"$controller\",stage=\"$stage\",action=~\"$action\"}[$__interval]))\n  /\navg(avg_over_time(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment=\"$env\",controller=\"$controller\",stage=\"$stage\",action=~\"$action\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment=\"$env\",controller=\"$controller\",stage=\"$stage\",action=~\"$action\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ action }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "99th Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(controller_action:gitlab_transaction_duration_seconds:p99{environment=\"$env\",controller=\"$controller\",stage=\"$stage\",action=~\"$action\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ action }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Average Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(controller_action:gitlab_sql_duration_seconds_sum:rate1m{environment=\"$env\",controller=\"$controller\",stage=\"$stage\",action=~\"$action\"}[$__interval]))\n  /\navg(avg_over_time(controller_action:gitlab_sql_duration_seconds_count:rate1m{environment=\"$env\",controller=\"$controller\",stage=\"$stage\",action=~\"$action\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Histograms by Action", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Action Latency - $action",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "repeat": "action",
   "targets": [
    {
     "expr": "avg_over_time(controller_action:gitlab_transaction_duration_seconds_bucket:rate1m{environment=\"$env\",controller=\"$controller\",stage=\"$stage\",action=~\"$action\"}[$__interval])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "SQL Histograms by action",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Action Latency - $action",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "repeat": "action",
     "targets": [
      {
       "expr": "avg_over_time(controller_action:gitlab_sql_duration_seconds_bucket:rate1m{environment=\"$env\",controller=\"$controller\",stage=\"$stage\",action=~\"$action\"}[$__interval])",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}