{
 "title": "Rate Limiting (WIP)",
 "description": "This is a work in progress dashboard to surface rate limiting metrics at all layers of the GitLab stack (Cloudflare, HAProxy, RackAttack, ApplicationRateLimiter, etc).\n\nOwner: Production Engineering::Foundations",
 "tags": [
  "unmanaged",
  "protected"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Rate Limiting (WIP)\n\nThis dashboard shows the rate limiting metrics at each layer of GitLab, beginning with the edge and working it's way down to the application.\n\nSome of these metrics don't exist (yet), but they'll be surfaced here once they do!\n\nMore detail available in: https://gitlab.com/gitlab-com/gl-infra/production-engineering/-/issues/25743"
   }
  },
  { "title": "Cloudflare", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 6 },
   "options": {
    "content": "# Cloudflare\n\nThe edge of our network - applies IP based rate limits and other high level blocks.\n\n## Links\n\n- [Cloudflare Dashboard: Rate Limit configuration](https://dash.cloudflare.com/852e9d53d0f8adbd9205389356f2303d/gitlab.com/security/waf/rate-limiting-rules)\n  - Managed in [config-mgmt](https://ops.gitlab.net/gitlab-com/gl-infra/config-mgmt/-/blob/main/environments/gprd/cloudflare-rate-limits-waf-and-rules.tf)\n- [Cloudflare Dashboard: Firewall Events](https://dash.cloudflare.com/852e9d53d0f8adbd9205389356f2303d/gitlab.com/security/events)\n\n"
   }
  },
  {
   "title": "Cloudflare rate limited response rate",
   "type": "timeseries",
   "description": "(request rate/60s)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum by (status) (rate(cloudflare_zone_requests_status{zone=\"gitlab.com\", status=\"429\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudflare percentage of rate limited requests",
   "type": "timeseries",
   "description": "What percentage of requests were rate limited in this period of time?",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($B / $A) * 100", "type": "math" }
   ]
  },
  {
   "title": "Cloudflare ratelimit block events",
   "type": "timeseries",
   "description": "request rate/60s",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum by (action) (rate(cloudflare_zone_firewall_events_count{zone=\"gitlab.com\", source=\"ratelimit\",action=\"block\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudflare events by source",
   "type": "timeseries",
   "description": "request rate/60s",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum by (source,action) (rate(cloudflare_zone_firewall_events_count{zone=\"gitlab.com\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HAProxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "options": {
    "content": "# HAProxy\n\nProvides rate limiting for GitLab Pages\n\n- The metrics are only by `4xx` which could mean rate limited responses, or any other client side error status, such as unauthenticated. It doesn't provide the most value. \n\n## Links\n\n- HAProxy BigQuery "
   }
  },
  {
   "title": "HAProxy 4xx response rate by backend",
   "type": "timeseries",
   "description": "We don't have the granularity to differentiate between 4xx client errors with HAProxy.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "sum by (backend)(rate(haproxy_backend_http_responses_total{code=\"4xx\",env=\"gprd\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HAProxy 4xx response rate: pages_http",
   "type": "timeseries",
   "description": "We know Pages uses HAProxy for rate limiting, so specifically filter on this.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum by (backend) (rate(haproxy_backend_http_responses_total{code=\"4xx\",env=\"gprd\", backend=\"pages_http\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application::Rack Attack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "# Application::RackAttack\n\n\n\nTODO:\n\n- Generate metrics! We currently only have logs :(\n  - Related [issue](https://gitlab.com/gitlab-com/gl-infra/production-engineering/-/work_items/25767)\n\n## Links\n\n- [RackAttack Kibana logs](https://log.gprd.gitlab.net/app/discover#/view/0026cc97-6b9a-445a-a364-7197e04053a2?_g=())\n- [Support Rate Limit Kibana dashboard](https://log.gprd.gitlab.net/app/r/s/AJDZC)"
   }
  },
  {
   "title": "Application::ApplicationRateLimiter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "# Application::ApplicationRateLimiter\n\nIntelligent application rate limits\n\nTODO:\n\n- Generate metrics! We currently only have logs :(\n  - Related [issue](https://gitlab.com/gitlab-com/gl-infra/production-engineering/-/work_items/25767)\n\n## Links\n\n- [ApplicationRateLimiter Kibana Logs](https://log.gprd.gitlab.net/app/discover#/view/2d2cf10e-b22a-4c07-bbda-45bb665c31ee?_g=()) "
   }
  }
 ]
}