{
 "title": "rcas: 2019-10-13 October 13 / Sunday night Crypto Miner Limit Takedown",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/558737542 at Tue May 19 11:18:12 UTC 2020",
 "tags": [
  "managed",
  "rcas",
  "rca"
 ],
 "time": { "from": "2019-10-13T12:00:00.000Z", "to": "2019-10-14T02:00:00Z" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Intro",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "# RCA dashboard for https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/8153\n\n## Production incident: https://gitlab.com/gitlab-com/gl-infra/production/issues/1245\n\n## Working doc: https://docs.google.com/document/d/1e_2FYIF7yTv90wUubgLEhVYsq03WBno1pOg6lQhPOaE/edit\n"
  },
  {
   "title": "CPU utilization on patroni-02, the postgres primary",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "content": "# This graph shows how this incident applied CPU saturation pressure to our Postgres primary database. This had a knock-on effect to the rest of the site.\n"
  },
  {
   "title": "Postgres Primary Average CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(instance:node_cpu_utilization:ratio{fqdn=\"patroni-02-db-gprd.c.gitlab-production.internal\", environment=\"gprd\"}) by (fqdn)\n,1),0)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Sidekiq pipeline latencies go up",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "content": "# ExpireJobCacheWorker and StageUpdateWorker jobs slowed down. Here is the rate at which these jobs were executed.\n\n## Side note: at present, we do not record the enqueue rate for Sidekiq jobs. We should as this is an important metric for understanding queueing systems.\n"
  },
  {
   "title": "ExpireJobCacheWorker,StageUpdateWorker Sidekiq job rates ",
   "type": "graph",
   "description": "Sidekiq ExpireJobCacheWorker,StageUpdateWorker pipeline (CI) jobs starting per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_completion_seconds_count{queue=~\"pipeline_cache:expire_job_cache|pipeline_processing:stage_update\", environment=\"gprd\", env=\"gprd\"}[$__interval])) by (queue)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Sidekiq pipeline latencies go up",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "content": "# Some CI pipeline worker queries slowed down, putting pressure on the Postgres primary and slowing down Sidekiq jobs that ran them\n"
  },
  {
   "title": "ExpireJobCacheWorker,StageUpdateWorker latency ",
   "type": "graph",
   "description": "p90 Processing time for ExpireJobCacheWorker,StageUpdateWorker pipeline (CI) jobs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(sidekiq_jobs_completion_seconds_bucket{queue=~\"pipeline_cache:expire_job_cache|pipeline_processing:stage_update\", environment=\"gprd\", env=\"gprd\"}[$__interval])) by (le, queue))\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Sidekiq queue lengths",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "content": "# As sidekiq slowed down, thousands of duplicate jobs were queued up\n\n## https://gitlab.com/gitlab-com/gl-infra/scalability/issues/42 is intended to address this issue\n"
  },
  {
   "title": "Sidekiq Queue Lengths per Queue",
   "type": "graph",
   "description": "The number of jobs queued up to be executed. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "max_over_time(sidekiq_queue_size{environment=\"gprd\"}[$__interval]) and on(fqdn) (redis_connected_slaves != 0)\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Total CI Minutes on Shared Runners",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "content": "# Total CI Minutes spiked but quickly dropped down as the user was blocked, banned and ran out of minutes\n\n## This shows how little impact this had on CI. However the downstream impact was much worse that the actual CI impact.\n"
  },
  {
   "title": "Sidekiq Queue Lengths per Queue",
   "type": "graph",
   "description": "The number of jobs queued up to be executed. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "s", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sum(rate(job_queue_duration_seconds_sum{shared_runner=\"true\", environment=\"gprd\"}[$__interval]))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Impact on web performance",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "content": "# This chart shows that the impact of this issue on web performance was relatively brief, lasting between 17h35 and 17h54UTC\n"
  },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min by (type) (min_over_time(gitlab_service_apdex:ratio{env=\"$environment\", environment=\"$environment\", monitor=\"global\", stage=\"main\", type=\"web\"}[$__interval]))\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\", monitor!~\"global|\", stage=\"main\", type=\"web\"})\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"web\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min by (type) (gitlab_service_apdex:ratio{env=\"$environment\", environment=\"$environment\", monitor=\"global\", stage=\"main\", type=\"web\"} offset 1w)\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\", monitor!~\"global|\", stage=\"main\", type=\"web\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "CI Runner 1m SLO",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
   "content": "# Our CI-Runners SLO is currently being focused on (see https://gitlab.com/gitlab-com/www-gitlab-com/issues/5341) but strangely it seems to have improved during the outage\n\n## This may be down to reporting. We should investigate this in more detail\n"
  },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min by (type) (min_over_time(gitlab_service_apdex:ratio{env=\"$environment\", environment=\"$environment\", monitor=\"global\", stage=\"main\", type=\"ci-runners\"}[$__interval]))\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\", monitor!~\"global|\", stage=\"main\", type=\"ci-runners\"})\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"ci-runners\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"ci-runners\", stage=\"main\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"ci-runners\"})) - 1\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "min by (type) (gitlab_service_apdex:ratio{env=\"$environment\", environment=\"$environment\", monitor=\"global\", stage=\"main\", type=\"ci-runners\"} offset 1w)\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\", monitor!~\"global|\", stage=\"main\", type=\"ci-runners\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Postgres Transaction Rollbacks",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
   "content": "# During the incident, we saw a high rate of postgres rollbacks. The cause of this has not been full investigated yet, although its not an unexpected outcome.\n"
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max by (type) (max_over_time(gitlab_service_errors:ratio{env=\"$environment\", environment=\"$environment\", monitor=\"global\", stage=\"main\", type=\"patroni\"}[$__interval]))\n  or\n  sum by (type) (gitlab_service_errors:ratio{environment=\"$environment\", monitor!~\"global|\", stage=\"main\", type=\"patroni\"}),\n  1\n)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"patroni\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"patroni\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "2 * (avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"patroni\", stage=\"main\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"patroni\"}))\n",
     "legendFormat": "Outage SLO"
    },
    {
     "expr": "max by (type) (gitlab_service_errors:ratio{env=\"$environment\", environment=\"$environment\", monitor=\"global\", stage=\"main\", type=\"patroni\"} offset 1w)\nor\nsum by (type) (gitlab_service_errors:ratio{environment=\"$environment\", monitor!~\"global|\", stage=\"main\", type=\"patroni\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  }
 ]
}