{
 "title": "rcas: Gitaly n+1 calls causing bad latency and sidekiq queues to grow",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/647698575 at Mon Jul 20 22:34:30 UTC 2020",
 "tags": [
  "managed",
  "rcas",
  "rca"
 ],
 "time": { "from": "2019-08-07 22:00:00", "to": "2019-08-08 18:00:00" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU on Gitaly",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "content": "The RCA issue for this incident is at https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/7479.\n\n\"Group Zero\" is a pseudonym for the group who pushed the extremely large tag sets to GitLab.com.\n\n\"Group Zero\" seems to start generating push activity at about 23h00 hours.\n\nThe first sign of a problem was CPU spikes on some Gitaly nodes.\nThis occurred as Gitaly struggled with _O(n^2)_ `FindAllTag` queries,\ngenerated by `PostReceiveWorkers`.\n"
  },
  {
   "title": "Gitaly Node CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(avg(instance_cpu:node_cpu_seconds_not_idle:rate1m{type=\"gitaly\", environment=\"gprd\"}) by (fqdn)\n,1),0)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "FindAllTags",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "content": "The `FindAllTags` will return multiple messages for each request made.\nThis is to ensure that each messages is kept reasonably small.\nBy calculating the average message size, we can detect if Gitaly is having\nto deal with very large tag payloads.\n"
  },
  {
   "title": "FindAllTags Response Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    {
     "format": "short",
     "label": "Average messages per FindAllTags request"
    }
   ],
   "targets": [
    {
     "expr": "grpc_server_msg_sent_total{grpc_method=\"FindAllTags\", environment=\"gprd\"}\n/\ngrpc_server_started_total{grpc_method=\"FindAllTags\", environment=\"gprd\"}\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "content": "Queue lengths increased for several reasons:\n\n1. \"Group Zero\" created `post_receive` jobs taking several hours, which starved the Sidekiq workers from performing other tasks.\n1. `post_receive` jobs calling `FindAllTags` put additional load on Gitaly servers which slowed other background tasks down\n"
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sidekiq_queue_size{environment=\"gprd\", name=~\"web_hook|project_service|post_receive\", type=\"redis-sidekiq\"} and on(fqdn) (redis_connected_slaves != 0)\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "content": "This chart shows the sum total amount of time spent processing jobs in each queue.\nThe `PostReceive` queue timings appear to be tied to the `FindAllTags` issue, but it\nappears that there may still be a pathologic repository causing high processing time.\n"
  },
  {
   "title": "Processing Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Total Processing Time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_completion_seconds_sum{environment=\"gprd\", queue=~\"web_hook|project_service|post_receive\"}[1m])) by (queue)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "PostReceive Latency",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "content": "`PostRecieve` latency. Lower is better. As a retrospective item, [we have now added](https://gitlab.com/gitlab-com/runbooks/merge_requests/1318) per-worker latency monitoring.\nthis shows the p80 latency of the `PostReceive` worker. This rose due to Gitaly latency caused by the `FindAllTags` issue and the huge payloads being processes.\n"
  },
  {
   "title": "p80 Latency for PostReceive jobs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "PostReceive latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.8, sum(rate(sidekiq_jobs_completion_seconds_bucket{environment=\"gprd\", queue=\"post_receive\"}[$__interval])) by (le, environment, stage, tier, type, queue))\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  }
 ]
}