{
 "title": "rcas: 2019-11-14",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/625927578 at Mon Jul  6 17:42:12 UTC 2020",
 "tags": [
  "managed",
  "rcas",
  "rca"
 ],
 "time": { "from": "2019-11-11T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "content": "# Workhorse 502s and 503s\n\nThe rate at which we're experiencing 502 and 503 errors is elevated.\nThis could be due to timeouts.\n\nBut what is causing the timeouts?\n\nLower is better.\n"
  },
  {
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{code=~\"503|502\", environment=\"gprd\", env=\"gprd\"}[2h]))\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 12 },
   "content": "# Web Apdex\n\nWhat percentage of web requests complete within the cutoff threshold?\n\nWe can see that latency spikes lead to the 502/503 errors we see in Workhorse, in the top panel\n\nHigher is better.\n"
  },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min by (type) (min_over_time(gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__interval]))\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\",monitor!~\"global|\",stage=\"main\",type=\"web\"})\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "avg by (type) (avg_over_time(gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__interval]))\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{type=\"web\"})))\nor\navg(slo:min:gitlab_service_apdex:ratio{type=\"web\"})\n",
     "legendFormat": "6h Degradation SLO"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{type=\"web\"})))\nor\n(2 * avg(slo:min:gitlab_service_apdex:ratio{type=\"web\"}) - 1)\n",
     "legendFormat": "1h Outage SLO"
    },
    {
     "expr": "min by (type) (gitlab_service_apdex:ratio{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"} offset 1w)\nor\nmin by (type) (gitlab_service_apdex:ratio{environment=\"$environment\",monitor!~\"global|\",stage=\"main\",type=\"web\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 24 },
   "content": "# Web Errors\n\nWhat percentage of web requests fail?\n\nLower is better.\n"
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max by (type) (max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__interval]))\n  or\n  sum by (type) (gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"main\",type=\"web\"}),\n  1\n)\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "clamp_max(\n  avg by (type) (avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__interval])),\n  1\n)\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{type=\"web\"}))\nor\navg(slo:max:gitlab_service_errors:ratio{type=\"web\"})\n",
     "legendFormat": "6h Degradation SLO"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{type=\"web\"}))\nor\n(2 * avg(slo:max:gitlab_service_errors:ratio{type=\"web\"}))\n",
     "legendFormat": "1h Outage SLO"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 36 },
   "content": "# pgbouncer Sync (web/api) pool Saturation\n"
  },
  {
   "title": "pgbouncer_sync_primary_pool component saturation: Postgres Sync (Web/API/Git) primary Connection Pool Saturation per Node",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        avg_over_time(pgbouncer_pools_server_active_connections{user=\"gitlab\", database=\"gitlabhq_production\", environment=\"$environment\", type=\"pgbouncer\", stage=\"main\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_testing_connections{user=\"gitlab\", database=\"gitlabhq_production\", environment=\"$environment\", type=\"pgbouncer\", stage=\"main\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_used_connections{user=\"gitlab\", database=\"gitlabhq_production\", environment=\"$environment\", type=\"pgbouncer\", stage=\"main\"}[5m]) +\n        avg_over_time(pgbouncer_pools_server_login_connections{user=\"gitlab\", database=\"gitlabhq_production\", environment=\"$environment\", type=\"pgbouncer\", stage=\"main\"}[5m])\n      )\n      / on(environment, tier, type, stage, fqdn, instance) group_left()\n      sum by (environment, tier, type, stage, fqdn, instance) (\n        avg_over_time(pgbouncer_databases_pool_size{name=\"gitlabhq_production\", environment=\"$environment\", type=\"pgbouncer\", stage=\"main\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
     "legendFormat": "{{ fqdn }} {{ instance }}"
    },
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{environment=\"$environment\", type=\"pgbouncer\", stage=\"main\", component=\"pgbouncer_sync_primary_pool\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"pgbouncer_sync_primary_pool\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"pgbouncer_sync_primary_pool\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 48 },
   "content": "### Is this being caused by more database traffic?\n\n# Patroni QPS\n\nIt doesn't appear to be. Patroni QPS seems to be stable over the long term.\n"
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg by (type)\n(avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"patroni\"}[$__interval]) or avg_over_time(gitlab_service_ops:rate{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"patroni\"}[$__interval]))\nor\nsum by (type) (gitlab_service_ops:rate_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"main\",type=\"patroni\"} or gitlab_service_ops:rate{environment=\"$environment\",monitor!~\"global|\",stage=\"main\",type=\"patroni\"})\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "avg by (type) (\n  gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"patroni\"} offset 1w\n  or\n  gitlab_service_ops:rate{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"patroni\"} offset 1w\n)\nor\nsum by (type) (\n  gitlab_service_ops:rate_5m{environment=\"$environment\",monitor!~\"global|\",stage=\"main\",type=\"patroni\"} offset 1w\n  or\n  gitlab_service_ops:rate{environment=\"$environment\",monitor!~\"global|\",stage=\"main\",type=\"patroni\"} offset 1w\n)\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"patroni\"}\n    + (2) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"patroni\"}\n  )\n  or\n  (\n      sum by (type) (gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor!~\"global|\",stage=\"main\",type=\"patroni\"})\n      + (2) *\n      sum by (type) (gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor!~\"global|\",stage=\"main\",type=\"patroni\"})\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"patroni\"}\n    + (-2) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"patroni\"}\n  )\n  or\n  (\n      sum by (type) (gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor!~\"global|\",stage=\"main\",type=\"patroni\"})\n      + (-2) *\n      sum by (type) (gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor!~\"global|\",stage=\"main\",type=\"patroni\"})\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  }
 ]
}