{
 "title": "rcas: 2019-07-01 Degraded performance on GitLab.com",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/819823187 at Thu Oct 29 17:37:14 UTC 2020",
 "tags": [
  "managed",
  "rcas",
  "rca",
  "redis-cache"
 ],
 "time": { "from": "2019-07-01 00:00:00", "to": "2019-07-04 00:00:00" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Web apdex",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "content": "Slowdown in webservices was the first sign of a problem.\n"
  },
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min by (type) (min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__interval]))\n",
     "legendFormat": "{{ type }} service"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{type=\"web\", monitor=\"global\"})))\n",
     "legendFormat": "6h Degradation SLO"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{type=\"web\"})))\n",
     "legendFormat": "1h Outage SLO"
    },
    {
     "expr": "avg by (type) (avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"}[$__interval]))\n",
     "legendFormat": "{{ type }} service (avg)"
    },
    {
     "expr": "min by (type) (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"main\",type=\"web\"} offset 1w)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "A slowdown across multiple services in the fleet",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "content": "Single core saturation in the main Redis cache cluster lead to slowdowns across multiple other services.\n"
  },
  {
   "title": "Single core saturation on the redis-cache fleet",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{environment=\"$environment\", type=\"redis-cache\", mode=\"idle\", fqdn=~\"redis-cache-\\\\d\\\\d.*\"}[$__interval]))\n,1),0)\n",
     "legendFormat": "Max Single Core Saturation"
    }
   ]
  },
  {
   "title": "Redis-cache network traffic",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "content": "Huge volumes of traffic, particularly application settings, was being sent from the cache to the web instances at a very high rate.\n"
  },
  {
   "title": "Single core saturation on the redis-cache fleet",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_output_bytes_total{environment=\"$environment\", type=\"redis-cache\"}[$__interval]))\n",
     "legendFormat": "send {{ fqdn }}"
    },
    {
     "expr": "sum(rate(redis_net_input_bytes_total{environment=\"$environment\", type=\"redis-cache\"}[$__interval]))\n",
     "legendFormat": "receive {{ fqdn }}"
    }
   ]
  },
  { "title": "Redis CPU", "type": "text", "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 } },
  {
   "title": "Redis CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(max(\n  (\n    rate(redis_cpu_user_seconds_total{environment=\"gprd\", type=\"redis-cache\"}[$__interval]) + rate(redis_cpu_sys_seconds_total{environment=\"gprd\", type=\"redis-cache\"}[$__interval])\n  )\n  or\n  (\n    rate(redis_used_cpu_user{environment=\"gprd\", type=\"redis-cache\"}[$__interval]) + rate(redis_used_cpu_sys{environment=\"gprd\", type=\"redis-cache\"}[$__interval])\n  )\n)\n,1),0)\n",
     "legendFormat": "Redis CPU"
    }
   ]
  }
 ]
}