{
 "title": "Rebalancing with Edits",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/817884584 at Wed Oct 28 22:12:30 UTC 2020",
 "time": { "from": "2020-10-05T00:00:00.000Z", "to": "2020-10-08T23:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Balacing",
   "type": "graph",
   "description": "Balancing Ranking. Equal is better.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(\n  max(rate(node_disk_read_bytes_total{environment=\"gprd\", type=\"gitaly\", device=\"sdb\"}[6h])) by (fqdn)\n  / ignoring(fqdn) group_left\n  sum(rate(node_disk_read_bytes_total{environment=\"gprd\", type=\"gitaly\", device=\"sdb\"}[6h]))\n\n  +\n\n  max(rate(node_disk_written_bytes_total{environment=\"gprd\", type=\"gitaly\", device=\"sdb\"}[6h])) by (fqdn)\n  / ignoring(fqdn) group_left\n  sum(rate(node_disk_written_bytes_total{environment=\"gprd\", type=\"gitaly\", device=\"sdb\"}[6h]))\n\n  +\n\n  max(rate(node_disk_reads_completed_total{environment=\"gprd\", type=\"gitaly\", device=\"sdb\"}[6h])) by (fqdn)\n  / ignoring(fqdn) group_left\n  sum(max(rate(node_disk_reads_completed_total{environment=\"gprd\", type=\"gitaly\", device=\"sdb\"}[6h])) by (fqdn))\n\n  +\n\n  max(rate(node_disk_writes_completed_total{environment=\"gprd\", type=\"gitaly\", device=\"sdb\"}[6h])) by (fqdn)\n  / ignoring(fqdn) group_left\n  sum(max(rate(node_disk_writes_completed_total{environment=\"gprd\", type=\"gitaly\", device=\"sdb\"}[6h])) by (fqdn))\n\n  +\n\n  sum(rate(grpc_client_started_total{environment=\"gprd\", type=\"gitaly\"}[6h])) by (fqdn)\n  / ignoring(fqdn) group_left\n  sum(rate(grpc_client_started_total{environment=\"gprd\", type=\"gitaly\"}[6h]))\n\n  +\n\n  sum(rate(grpc_client_started_total{environment=\"gprd\", type=\"gitaly\"}[6h])) by (fqdn)\n  / ignoring(fqdn) group_left\n  sum(rate(grpc_client_started_total{environment=\"gprd\", type=\"gitaly\"}[6h]))\n\n  +\n\n  avg(instance:node_filesystem_avail:ratio{environment=\"gprd\", type=\"gitaly\",device=\"/dev/sdb\"}) by (fqdn)\n  / ignoring(fqdn) group_left\n  sum(avg(instance:node_filesystem_avail:ratio{environment=\"gprd\", type=\"gitaly\",device=\"/dev/sdb\"}) by (fqdn))\n)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Disk read bytes/second average",
   "type": "graph",
   "description": "Average read throughput. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(rate(node_disk_read_bytes_total{environment=\"$environment\", type=\"gitaly\", device=\"sdb\"}[$__range])) by (fqdn))\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Disk write bytes/second average",
   "type": "graph",
   "description": "Average write throughput. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(rate(node_disk_written_bytes_total{environment=\"$environment\", type=\"gitaly\", device=\"sdb\"}[$__range])) by (fqdn))\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Disk read operation/second average",
   "type": "graph",
   "description": "Average write throughput. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(rate(node_disk_reads_completed_total{environment=\"$environment\", type=\"gitaly\", device=\"sdb\"}[$__range])) by (fqdn))\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Disk write operation/second average",
   "type": "graph",
   "description": "Average write throughput. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sort_desc(max(rate(node_disk_writes_completed_total{environment=\"$environment\", type=\"gitaly\", device=\"sdb\"}[$__range])) by (fqdn))\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Total Gitaly Request Time",
   "type": "graph",
   "description": "Average seconds of Gitaly utilization per server per second. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(grpc_server_handling_seconds_sum{environment=\"$environment\", type=\"gitaly\"}[$__range])) by (fqdn))\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Gitaly-Ruby Request Rate",
   "type": "graph",
   "description": "Average number of Gitaly Ruby Requests/second. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(grpc_client_started_total{environment=\"$environment\", type=\"gitaly\"}[$__range])) by (fqdn))\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Disk Space Left",
   "type": "graph",
   "description": "Disk free space available %. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(\n  avg_over_time(instance:node_filesystem_avail:ratio{environment=\"$environment\", type=\"gitaly\",device=\"/dev/sdb\"}[$__range])\n)\n",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  }
 ]
}