{
 "title": "redis eviction spikes",
 "tags": [ "unmanaged" ],
 "time": { "from": "2020-03-22T04:28:52.231Z", "to": "2020-03-22T08:28:52.231Z" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gprd,gstg,ops" },
   { "name": "promethus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(up{env=\"$environment\"},fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(scrape_duration_seconds{env=\"$environment\",job=\"gitlab-redis\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "max_over_time(scrape_duration_seconds{env=\"$environment\",job=\"gitlab-redis\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys{env=\"$environment\",fqdn=\"$node\"})",
     "legendFormat": "keys"
    }
   ]
  },
  {
   "title": "Evicted / Expired Keys",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(redis_evicted_keys_total{env=\"$environment\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "evicted keys"
    },
    {
     "expr": "rate(redis_expired_keys_total{env=\"$environment\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "expired keys"
    }
   ]
  },
  {
   "title": "Current and new incoming TCP connections",
   "type": "graph",
   "description": "This metric is from the kernel's perspective for the whole host, not necessarily to the redis-server process.\n\nAn ESTABLISHED connection does not necessarily imply that the listener has yet called \"accept\"; just that the kernel has completed the handshake.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Established connections" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{fqdn=~\"$node\"}",
     "legendFormat": "Established TCP connection"
    },
    {
     "expr": "rate(node_netstat_Tcp_PassiveOpens{fqdn=\"$node\"}[$__interval])",
     "legendFormat": "New TCP Connections"
    }
   ]
  },
  {
   "title": "Allocated memory as accounted by jemalloc",
   "type": "graph",
   "description": "This metric is reported by redis INFO MEMORY as \"allocator_allocated\".  Its value it collected periodically by Redis' \"serverCron\" (src/server.c), which calls \"zmalloc_get_allocator_info\" (src/zmalloc.c).\n\nje_mallctl(\"stats.allocated\", allocated, ...)\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(redis_allocator_allocated_bytes{env=\"$environment\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "avg_over_time(redis_allocator_allocated_bytes{env=\"$environment\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "min_over_time(redis_allocator_allocated_bytes{env=\"$environment\",fqdn=\"$node\"}[$__interval])",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Connected Redis clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(redis_connected_clients{fqdn=\"$node\"}[$__interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "max_over_time(redis_connected_clients{fqdn=\"$node\"}[$__interval])",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Redis CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "vCPUs" }
   ],
   "targets": [
    {
     "expr": "instance:redis_cpu_usage:rate1m{fqdn=\"$node\"}",
     "legendFormat": "redis CPU usage"
    }
   ]
  }
 ]
}