{
 "title": "Redis Stats - old",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Connections and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Primary Connected Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{environment=\"$environment\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary Connections Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "ops", "label": "Conns per sec" }
   ],
   "targets": [
    {
     "expr": "redis:connections_received:irate1m{environment=\"$environment\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Blocked Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_blocked_clients{environment=\"$environment\"}",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "Connected Secondaries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_slaves{environment=\"$environment\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{environment=\"$environment\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Operation Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_command_call_duration_seconds_count{environment=~\"$environment\"}[1m]) > 0",
     "legendFormat": "{{fqdn }} {{ cmd }}"
    }
   ]
  },
  { "title": "Redis Primary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Commands Executed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis:commands_processed:irate1m{environment=\"$environment\"} and on (fqdn) gitlab:redis_master",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Keys Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(redis:keyspace_hits:irate1m{environment=\"$environment\"} / (redis:keyspace_hits:irate1m{environment=\"$environment\"} + redis:keyspace_misses:irate1m{environment=\"$environment\"})) and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "hits - {{fqdn}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "redis:net_input_bytes:irate1m{environment=\"$environment\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "incoming {{fqdn}}"
    },
    {
     "expr": "redis:net_output_bytes:irate1m and on (fqdn) gitlab:redis_master",
     "legendFormat": "outgoing {{fqdn}}"
    }
   ]
  },
  { "title": "Redis Secondaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Commands Executed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis:commands_processed:irate1m{environment=\"$environment\"} unless on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Keys Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(redis:keyspace_hits:irate1m{environment=\"$environment\"} / (redis:keyspace_hits:irate1m{environment=\"$environment\"} + redis:keyspace_misses:irate1m{environment=\"$environment\"})) unless on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "hits - {{fqdn}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "redis:net_input_bytes:irate1m{environment=\"$environment\"} unless on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "incoming {{fqdn}}"
    },
    {
     "expr": "redis:net_output_bytes:irate1m{environment=\"$environment\"} unless on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "outgoing {{fqdn}}"
    }
   ]
  },
  { "title": "Command Calls & Keys Lifecycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cmd:redis_command_call_duration_seconds_count:irate1m{environment=\"$environment\"} > 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Primary Expired/Evicted",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "ops", "label": "Keys per sec" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(redis:expired_keys:irate1m{environment=\"$environment\"}[$__interval]) and on (fqdn) avg_over_time(gitlab:redis_master{environment=\"$environment\"}[$__interval])",
     "legendFormat": "expired - {{fqdn}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(redis:evicted_keys:irate1m{environment=\"$environment\"}[$__interval]) and on (fqdn) avg_over_time(gitlab:redis_master{environment=\"$environment\"}[$__interval])",
     "legendFormat": "evicted - {{fqdn}}",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Keys on Primary",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_db_keys{environment=\"$environment\"} - redis_db_keys_expiring{environment=\"$environment\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "persistent {{fqdn}}"
    },
    {
     "expr": "redis_db_keys_expiring{environment=\"$environment\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "expiring {{fqdn}}"
    }
   ]
  },
  { "title": "Workhorse Watcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Connections creation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_redis_total_connections{environment=\"$environment\"}[30s]))"
    }
   ]
  },
  {
   "title": "Received messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_keywather_total_messages{environment=\"$environment\"}[30s]))"
    }
   ]
  },
  {
   "title": "Notification watchers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_keywatcher_keywatchers{environment=\"$environment\"}[30s]))"
    }
   ]
  }
 ]
}