{
 "title": "Redis [deprecated]",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis",
  "deprecated",
  "unmanaged"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "prometheus_app", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(redis_instance_info{env=\"$environment\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "content": "![](https://media.giphy.com/media/l0HlKrB02QY0f1mbm/giphy.gif)"
  },
  {
   "title": "Deprecation  Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 0 },
   "content": "# Deprecated ⚠️⚠️⚠️⚠️⚠️\n\nThis dashboard is deprecated, please consider switching over to the new service based dashboards:\n\n* [redis](/d/redis-main/redis-overview)\n* [redis-sidekiq](/d/redis-sidekiq-main/redis-sidekiq-overview)\n* [redis-cache](/d/redis-cache-main/redis-cache-overview)\n\n\n\n"
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_user{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(redis_cpu_sys_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_sys{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Sys"
    }
   ]
  },
  {
   "title": "CPU $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_user{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(redis_cpu_sys_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_sys{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Sys"
    }
   ]
  },
  {
   "title": "CPU $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_user{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(redis_cpu_sys_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_sys{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Sys"
    }
   ]
  },
  {
   "title": "CPU $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_user{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(redis_cpu_sys_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_sys{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Sys"
    }
   ]
  },
  {
   "title": "CPU $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_user{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(redis_cpu_sys_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_sys{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Sys"
    }
   ]
  },
  {
   "title": "CPU $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_user{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(redis_cpu_sys_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_sys{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Sys"
    }
   ]
  },
  {
   "title": "CPU $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_user{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(redis_cpu_sys_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_sys{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Sys"
    }
   ]
  },
  {
   "title": "CPU $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_user{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(redis_cpu_sys_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_sys{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Sys"
    }
   ]
  },
  {
   "title": "CPU $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_user{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(redis_cpu_sys_seconds_total{env=\"$environment\",instance=~\"$instance\"}[$__interval]) or\nrate(redis_used_cpu_sys{env=\"$environment\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Sys"
    }
   ]
  },
  { "title": "Connections and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Primary Connected Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{environment=\"$environment\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary Connections Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "ops", "label": "Conns per sec" }
   ],
   "targets": [
    {
     "expr": "redis:connections_received:irate1m{environment=\"$environment\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connected Secondaries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_slaves{environment=\"$environment\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Primary Used Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{environment=\"$environment\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Redis Primary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Commands Executed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{env=\"$environment\"}[$__interval]) and on (instance) gitlab:redis_master",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Keys Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  redis:keyspace_hits:irate1m{environment=\"$environment\"} /\n  (redis:keyspace_hits:irate1m{environment=\"$environment\"} + redis:keyspace_misses:irate1m{environment=\"$environment\"})\n) and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "hits - {{fqdn}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "redis:net_input_bytes:irate1m{env=\"$environment\",instance=~\"$instance\"} and on (fqdn) gitlab:redis_master{env=\"$environment\"}",
     "legendFormat": "incoming {{fqdn}}"
    },
    {
     "expr": "redis:net_output_bytes:irate1m{env=\"$environment\",instance=~\"$instance\"} and on (fqdn) gitlab:redis_master{env=\"$environment\"}",
     "legendFormat": "outgoing {{fqdn}}"
    }
   ]
  },
  {
   "title": "Packets per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{device!=\"lo\",env=\"$environment\",type=~\"redis.*\"}[$__interval]) and on (fqdn) gitlab:redis_master{env=\"$environment\"}",
     "legendFormat": "incoming {{fqdn}}"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{device!=\"lo\",env=\"$environment\",type=~\"redis.*\"}[$__interval]) and on (fqdn) gitlab:redis_master{env=\"$environment\"}",
     "legendFormat": "outgoing {{fqdn}}"
    }
   ]
  },
  { "title": "Redis Secondaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Commands Executed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis:commands_processed:irate1m{environment=\"$environment\"} unless on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Keys Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(redis:keyspace_hits:irate1m{environment=\"$environment\"} / (redis:keyspace_hits:irate1m{environment=\"$environment\"} + redis:keyspace_misses:irate1m{environment=\"$environment\"})) unless on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "hits - {{fqdn}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "redis:net_input_bytes:irate1m{environment=\"$environment\",instance=~\"$instance\"} unless on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "incoming {{fqdn}}"
    },
    {
     "expr": "redis:net_output_bytes:irate1m{environment=\"$environment\",instance=~\"$instance\"} unless on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "outgoing {{fqdn}}"
    }
   ]
  },
  {
   "title": "Redis Master Link Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "redis_master_link_up{environment=\"$environment\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Command Calls & Keys Lifecycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cmd) (\n  rate(redis_commands_total{env=\"$environment\",instance=~\"$instance\"}[$__interval])\n) > 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Primary Expired/Evicted",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "ops", "label": "Keys per sec" }
   ],
   "targets": [
    {
     "expr": "redis:expired_keys:irate1m{environment=\"$environment\",instance=~\"$instance\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "expired - {{fqdn}}"
    },
    {
     "expr": "redis:evicted_keys:irate1m{environment=\"$environment\",instance=~\"$instance\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "evicted - {{fqdn}}"
    }
   ]
  },
  {
   "title": "Keys on Primary",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_db_keys{environment=\"$environment\"} - redis_db_keys_expiring{environment=\"$environment\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "persistent {{fqdn}}"
    },
    {
     "expr": "redis_db_keys_expiring{environment=\"$environment\"} and on (fqdn) gitlab:redis_master{environment=\"$environment\"}",
     "legendFormat": "expiring {{fqdn}}"
    }
   ]
  },
  { "title": "Workhorse Watcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Connections creation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_redis_total_connections{env=\"$environment\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Received messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_keywather_total_messages{env=\"$environment\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Notification watchers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_keywatcher_keywatchers{env=\"$environment\"}[$__interval]))"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "BG Save Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(redis_rdb_current_bgsave_duration_sec{env=\"$environment\",instance=~\"$instance\"}[$__interval]))  by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Redis Changes Since Last DB Save",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(redis_rdb_changes_since_last_save{env=\"$environment\",instance=~\"$instance\"}[20m]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "IOWait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(instance_mode:node_cpu_seconds:rate1m{tier=\"db\",type=\"redis\",environment=\"gprd\", mode=\"iowait\"}) by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Redis Commands per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total{environment=\"gprd\"}[$__interval]))  by (fqdn)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ fqdn }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}