{
 "title": "redis-cluster-queues-meta: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5146407361 at Fri Sep 22 13:19:25 UTC 2023",
 "tags": [
  "managed",
  "redis-cluster-queues-meta",
  "gitlab",
  "type:redis-cluster-queues-meta",
  "redis-cluster-queues-meta",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "shard",
    "query": "label_values(gitlab:redis_cluster_nodes:count{environment=\"$environment\"}, shard)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "redis-cluster-queues-meta Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n",
     "legendFormat": "redis-cluster-queues-meta apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n",
     "legendFormat": "redis-cluster-queues-meta apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "redis-cluster-queues-meta Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "redis-cluster-queues-meta Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "redis-cluster-queues-meta error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "redis-cluster-queues-meta error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "redis-cluster-queues-meta Service | Errors"
    }
   ]
  },
  {
   "title": "redis-cluster-queues-meta Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n",
     "legendFormat": "redis-cluster-queues-meta RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "primary_server SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"primary_server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n",
     "legendFormat": "primary_server RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"primary_server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "content": "### Description\n\nOperations on the Redis primary for Redis Cluster Queues Metadata instance.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Redis logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.redis_message),filters:!((meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type.keyword,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type.keyword:(query:'redis-cluster-queues-meta',type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type:(query:'redis-cluster-queues-meta',type:phrase))))),index:'AWSQX_Vf93rHTYrsexmk')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Redis requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWSQX_Vf93rHTYrsexmk&_a=(filters:!((meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type.keyword,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type.keyword:(query:'redis-cluster-queues-meta',type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type:(query:'redis-cluster-queues-meta',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Redis Slowlog logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.command,json.exec_time_s),filters:!((meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.tag,params:redis.slowlog,type:phrase),query:(match:(json.tag:(query:redis.slowlog,type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type.keyword,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type.keyword:(query:'redis-cluster-queues-meta',type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type:(query:'redis-cluster-queues-meta',type:phrase))))),index:'AWSQX_Vf93rHTYrsexmk')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Redis Slowlog requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWSQX_Vf93rHTYrsexmk&_a=(filters:!((meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.tag,params:redis.slowlog,type:phrase),query:(match:(json.tag:(query:redis.slowlog,type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type.keyword,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type.keyword:(query:'redis-cluster-queues-meta',type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type:(query:'redis-cluster-queues-meta',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Redis Slowlog sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWSQX_Vf93rHTYrsexmk&_a=(filters:!((meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.tag,params:redis.slowlog,type:phrase),query:(match:(json.tag:(query:redis.slowlog,type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type.keyword,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type.keyword:(query:'redis-cluster-queues-meta',type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type:(query:'redis-cluster-queues-meta',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.exec_time_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.exec_time_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Redis Slowlog sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWSQX_Vf93rHTYrsexmk&_a=(filters:!((meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.tag,params:redis.slowlog,type:phrase),query:(match:(json.tag:(query:redis.slowlog,type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type.keyword,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type.keyword:(query:'redis-cluster-queues-meta',type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type:(query:'redis-cluster-queues-meta',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.exec_time_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.hostname.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.exec_time_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Redis Slowlog percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWSQX_Vf93rHTYrsexmk&_a=(filters:!((meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.tag,params:redis.slowlog,type:phrase),query:(match:(json.tag:(query:redis.slowlog,type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type.keyword,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type.keyword:(query:'redis-cluster-queues-meta',type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type:(query:'redis-cluster-queues-meta',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.exec_time_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.exec_time_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Redis Slowlog percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWSQX_Vf93rHTYrsexmk&_a=(filters:!((meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.tag,params:redis.slowlog,type:phrase),query:(match:(json.tag:(query:redis.slowlog,type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type.keyword,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type.keyword:(query:'redis-cluster-queues-meta',type:phrase)))),(meta:(index:'AWSQX_Vf93rHTYrsexmk',key:json.type,params:'redis-cluster-queues-meta',type:phrase),query:(match:(json.type:(query:'redis-cluster-queues-meta',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.exec_time_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.hostname.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.exec_time_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',labels:(filter:!t,rotate:0,show:!t,truncate:100),name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.exec_time_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "rails_redis_client SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n",
     "legendFormat": "rails_redis_client apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n",
     "legendFormat": "rails_redis_client apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "rails_redis_client SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "rails_redis_client SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rails_redis_client error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "rails_redis_client error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"rails_redis_client\",monitor=\"global\",type=\"redis-cluster-queues-meta\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "rails_redis_client SLI | Errors"
    }
   ]
  },
  {
   "title": "rails_redis_client SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n",
     "legendFormat": "rails_redis_client RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"rails_redis_client\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "content": "### Description\n\nAggregation of all Redis Cluster Queues Metadata operations issued from the Rails codebase\nthrough `Gitlab::Redis::Wrapper` subclasses.\n\n"
  },
  {
   "title": "secondary_servers SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"secondary_servers\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"}[$__interval])\n",
     "legendFormat": "secondary_servers RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"secondary_servers\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",type=\"redis-cluster-queues-meta\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "content": "### Description\n\nOperations on the Redis secondaries for the Redis Cluster Queues Metadata instance.\n\n"
  },
  {
   "title": "🔬 SLI Detail: primary_server",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "primary_server RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(redis_commands_processed_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[$__interval]) and on (instance) redis_instance_info{role=\"master\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "primary_server RPS - per instance",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (\n  rate(redis_commands_processed_total{env=\"$environment\",environment=\"$environment\",instance!=\"\",type=\"redis-cluster-queues-meta\"}[$__interval]) and on (instance) redis_instance_info{role=\"master\"}\n)\n > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: rails_redis_client",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 rails_redis_client Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(gitlab_redis_client_requests_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",storage=\"queues_metadata\",type!=\"ops-gitlab-net\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "rails_redis_client Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_redis_client_exceptions_total{env=\"$environment\",environment=\"$environment\",storage=\"queues_metadata\",type!=\"ops-gitlab-net\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "rails_redis_client RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_redis_client_requests_total{env=\"$environment\",environment=\"$environment\",storage=\"queues_metadata\",type!=\"ops-gitlab-net\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 rails_redis_client Latency - per type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,type) (\n    rate(gitlab_redis_client_requests_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",storage=\"queues_metadata\",type!=\"\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{type}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_redis_client Latency - per type",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (type) (\n  rate(gitlab_redis_client_requests_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",storage=\"queues_metadata\",type!=\"\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (type) (\n    rate(gitlab_redis_client_requests_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"0.5\",storage=\"queues_metadata\",type!=\"\"}[$__interval])\n  )\n  +\n  sum by (type) (\n    rate(gitlab_redis_client_requests_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"0.75\",storage=\"queues_metadata\",type!=\"\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(type) group_left()\n  (\n    sum by () (\n  rate(gitlab_redis_client_requests_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",storage=\"queues_metadata\",type!=\"\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "rails_redis_client Errors - per type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (\n  rate(gitlab_redis_client_exceptions_total{env=\"$environment\",environment=\"$environment\",storage=\"queues_metadata\",type!=\"ops-gitlab-net\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "rails_redis_client RPS - per type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (\n  rate(gitlab_redis_client_requests_total{env=\"$environment\",environment=\"$environment\",storage=\"queues_metadata\",type!=\"ops-gitlab-net\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: secondary_servers",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "collapsed": true,
   "panels": [
    {
     "title": "secondary_servers RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(redis_commands_processed_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[$__interval]) and on (instance) redis_instance_info{role=\"slave\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "secondary_servers RPS - per instance",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (\n  rate(redis_commands_processed_total{env=\"$environment\",environment=\"$environment\",instance!=\"\",type=\"redis-cluster-queues-meta\"}[$__interval]) and on (instance) redis_instance_info{role=\"slave\"}\n)\n > 0",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "avg(instance:node_cpu_utilization:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "sum(rate(node_network_receive_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_reads_completed_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_writes_completed_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_read_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_written_bytes_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Total Time",
     "type": "graph",
     "description": "Total time spent in read operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_read_time_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Total Time",
     "type": "graph",
     "description": "Total time spent in write operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_write_time_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "CPU Scheduling Waiting",
     "type": "graph",
     "description": "CPU scheduling waiting on the run queue, as a percentage of time. Aggregated to worst CPU per node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "max by (fqdn) (\n  rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[5m])\n)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg1 per core",
     "type": "graph",
     "description": "Loadavg (1 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "loadavg1" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load1{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg5 per core",
     "type": "graph",
     "description": "Loadavg (5 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg5" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load5{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg15 per core",
     "type": "graph",
     "description": "Loadavg (15 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg15" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load15{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true,
   "panels": [
    {
     "title": "redis Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"redis\",env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "redis Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"redis\",env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "redis Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"redis\",env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"redis\",env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "Node CPU Requests Utilization",
     "type": "graph",
     "description": "Ratio of requested CPU resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by memory requests already.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\",resource=\"cpu\"}\n",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Node Memory Requests Utilization",
     "type": "graph",
     "description": "Ratio of requested Memory resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by CPU requests already.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"}\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\",resource=\"memory\"}\n",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu component saturation: Average Service CPU Utilization",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a service fleet.\nIf it is becoming saturated, it may indicate that the fleet needs\nhorizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_inodes component saturation: Disk inode Utilization per Device per Node",
     "type": "graph",
     "description": "Disk inode utilization per device per node.\n\nIf this is too high, its possible that a directory is filling up with\nfiles. Consider logging in an checking temp directories for large numbers\nof files\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      1 - (\n        node_filesystem_files_free{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n        /\n        node_filesystem_files{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"disk_inodes\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"disk_inodes\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"disk_inodes\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_space component saturation: Disk Space Utilization per Device per Node",
     "type": "graph",
     "description": "Disk space utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      (\n        1 - node_filesystem_avail_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"} / node_filesystem_size_bytes{fstype=~\"ext.|xfs\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"disk_space\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"disk_space\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"disk_space\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. When this is exhausted, the container may be thottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, shard, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_container_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_memory component saturation: Kube Container Memory Utilization",
     "type": "graph",
     "description": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      container_memory_working_set_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_container_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_container_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_horizontalpodautoscaler_desired_replicas component saturation: Horizontal Pod Autoscaler Desired Replicas",
     "type": "graph",
     "description": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, horizontalpodautoscaler, shard) (\n  clamp_min(\n    clamp_max(\n      kube_horizontalpodautoscaler_status_desired_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects|urgent-other\", namespace!~\"pubsubbeat\"}\n      /\n      kube_horizontalpodautoscaler_spec_max_replicas:labeled{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|urgent-authorized-projects|urgent-other\", namespace!~\"pubsubbeat\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ horizontalpodautoscaler }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_pool_cpu component saturation: Average Node Pool CPU Utilization",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in the node pool for\na service fleet.\n\nIf it is becoming saturated, it may indicate that the fleet needs horizontal scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard) (\n        rate(node_cpu_seconds_total:labeled{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_pool_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_pool_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_pool_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_pool_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_pool_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_pool_max_nodes component saturation: Kube Pool Max Node Limit",
     "type": "graph",
     "description": "A GKE kubernetes node pool is close to it's maximum number of nodes.\n\nThe maximum is defined in terraform, via the `max_node_count` field of a node pool. The limit is per-zone, so for\nsingle zone clusters the number of nodes will match the limit, for regional clusters, the limit is multiplied by\nthe number of zones the cluster is deployed over.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, shard, cluster, label_pool, shard) (\n  clamp_min(\n    clamp_max(\n      count by (cluster, env, environment, label_pool, tier, type, stage, shard) (\n        kube_node_labels:labeled{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n      )\n      / on(cluster, env, environment, label_pool) group_left() (\n        label_replace(\n          terraform_report_google_cluster_node_pool_max_node_count,\n          \"label_pool\", \"$0\", \"pool_name\", \".*\"\n        )\n        * on(cluster, env, environment) group_left()\n        count by (cluster, env, environment) (\n          group by (cluster, env, environment, label_topology_kubernetes_io_zone) (\n            kube_node_labels:labeled{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n          )\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ cluster }} {{ label_pool }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_pool_max_nodes\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_pool_max_nodes\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"kube_pool_max_nodes\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_pool_max_nodes\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_pool_max_nodes\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "memory component saturation: Memory Utilization per Node",
     "type": "graph",
     "description": "Memory utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"} or instance:node_memory_utilisation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "nf_conntrack_entries component saturation: conntrack Entries per Node",
     "type": "graph",
     "description": "Netfilter connection tracking table utilization per node.\n\nWhen saturated, new connection attempts (incoming SYN packets) are dropped with no reply, leaving clients to slowly retry (and typically fail again) over the next several seconds.  When packets are being dropped due to this condition, kernel will log the event as: \"nf_conntrack: table full, dropping packet\".\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, instance) (\n  clamp_min(\n    clamp_max(\n      max_over_time(node_nf_conntrack_entries{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[1m])\n      /\n      node_nf_conntrack_entries_limit{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"nf_conntrack_entries\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"nf_conntrack_entries\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"nf_conntrack_entries\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "node_schedstat_waiting component saturation: Node Scheduler Waiting Time",
     "type": "graph",
     "description": "Measures the amount of scheduler waiting time that processes are waiting\nto be scheduled, according to [`CPU Scheduling Metrics`](https://www.robustperception.io/cpu-scheduling-metrics-from-the-node-exporter).\n\nA high value indicates that a node has more processes to be run than CPU time available\nto handle them, and may lead to degraded responsiveness and performance from the application.\n\nAdditionally, it may indicate that the fleet is under-provisioned.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, shard) (\n  clamp_min(\n    clamp_max(\n      avg without (cpu) (rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[1h]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"node_schedstat_waiting\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"node_schedstat_waiting\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"node_schedstat_waiting\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "redis_cluster_clients component saturation: Redis Client Utilization per Node",
     "type": "graph",
     "description": "Redis client utilization per node.\n\nA redis server has a maximum number of clients that can connect. When this resource is saturated,\nnew clients may fail to connect.\n\nMore details at https://redis.io/topics/clients#maximum-number-of-clients\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, instance, shard) (\n  clamp_min(\n    clamp_max(\n      max_over_time(redis_connected_clients{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[1m])\n      /\n      redis_config_maxclients{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_cluster_clients\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_cluster_clients\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_cluster_clients\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"redis_cluster_clients\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"redis_cluster_clients\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "redis_cluster_memory component saturation: Redis Memory Utilization per Node",
     "type": "graph",
     "description": "Redis memory utilization per node.\n\nAs Redis memory saturates node memory, the likelyhood of OOM kills, possibly to the Redis process,\nbecome more likely.\n\nFor caches, consider lowering the `maxmemory` setting in Redis. For non-caching Redis instances,\nthis has been caused in the past by credential stuffing, leading to large numbers of web sessions.\n\nThis threshold is kept deliberately low, since Redis RDB snapshots could consume a significant amount of memory,\nespecially when the rate of change in Redis is high, leading to copy-on-write consuming more memory than when the\nrate-of-change is low.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, instance, shard) (\n  clamp_min(\n    clamp_max(\n      max by (environment, tier, type, stage, shard, fqdn, instance, shard) (\n        label_replace(redis_memory_used_rss_bytes{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}, \"memtype\", \"rss\",\"\",\"\")\n        or\n        label_replace(redis_memory_used_bytes{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}, \"memtype\", \"used\",\"\",\"\")\n      )\n      /\n      avg by (environment, tier, type, stage, shard, fqdn, instance, shard) (\n        node_memory_MemTotal_bytes{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_cluster_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_cluster_memory\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_cluster_memory\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"redis_cluster_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"redis_cluster_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "redis_cluster_primary_cpu component saturation: Redis Primary CPU Utilization per Node",
     "type": "graph",
     "description": "Redis Primary CPU Utilization per Node.\n\nThe core server of redis is single-threaded; this thread is only able to scale to full use of a single CPU on a given server.\nWhen the primary Redis thread is saturated, major slowdowns should be expected across the application, so avoid if at all\npossible.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, instance, shard) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard, fqdn, instance, shard) (\n        rate(\n          namedprocess_namegroup_thread_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", groupname=\"redis-server\", threadname=\"redis-server\"}[5m])\n      )\n      and on (fqdn) redis_instance_info{role=\"master\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_cluster_primary_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_cluster_primary_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_cluster_primary_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"redis_cluster_primary_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"redis_cluster_primary_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "redis_secondary_cpu component saturation: Redis Secondary CPU Utilization per Node",
     "type": "graph",
     "description": "Redis Secondary CPU Utilization per Node.\n\nRedis is single-threaded. A single Redis server is only able to scale as far as a single CPU on a single host.\nCPU saturation on a secondary is not as serious as critical as saturation on a primary, but could lead to\nreplication delays.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn, instance, shard) (\n  clamp_min(\n    clamp_max(\n      (\n        rate(redis_cpu_user_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[5m])\n        +\n        rate(redis_cpu_sys_seconds_total{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[5m])\n      )\n      and on (instance) redis_instance_info{role!=\"master\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_secondary_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_secondary_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"redis_secondary_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"redis_secondary_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"redis_secondary_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "shard_cpu component saturation: Average CPU Utilization per Shard",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a shard of a\nservice fleet. If it is becoming saturated, it may indicate that the\nshard needs horizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard, shard) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"shard_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"shard_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"shard_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "single_node_cpu component saturation: Average CPU Utilization per Node",
     "type": "graph",
     "description": "Average CPU utilization per Node.\n\nIf average CPU is saturated, it may indicate that a fleet is in need to horizontal or vertical scaling. It may also indicate\nimbalances in load in a fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, fqdn) (\n  clamp_min(\n    clamp_max(\n      avg without(cpu, mode) (1 - rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\"}[5m]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"single_node_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"single_node_cpu\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"redis-cluster-queues-meta\", component=\"single_node_cpu\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Clients" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(redis_connected_clients{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Blocked Clients",
   "type": "graph",
   "description": "Blocked clients are waiting for a state change event using commands such as BLPOP. Blocked clients are not a sign of an issue on their own.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Blocked Clients" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(redis_blocked_clients{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Connections Received",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_connections_received_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Operation Rate - Primary",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "short", "label": "Operations/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval]) and on (pod, fqdn) redis_instance_info{role=\"master\", environment=\"$environment\"} ) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Operation Rate - Replicas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "short", "label": "Operations/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval]) and on (pod, fqdn) redis_instance_info{role=\"slave\", environment=\"$environment\"} ) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Redis CPU per Node - Primary",
   "type": "graph",
   "description": "redis is single-threaded. This graph shows maximum utilization across all cores on each host. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(max(\n  max_over_time(instance:redis_cpu_usage:rate1m{environment=\"$environment\", type=\"redis-cluster-queues-meta\"}[$__interval])\n    and on (pod, fqdn) redis_instance_info{role=\"master\", environment=\"$environment\"}\n) by (fqdn, pod)\n,1),0)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Redis CPU per Node - Replicas",
   "type": "graph",
   "description": "redis is single-threaded. This graph shows maximum utilization across all cores on each host. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2011 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(max(\n  max_over_time(instance:redis_cpu_usage:rate1m{environment=\"$environment\", type=\"redis-cluster-queues-meta\"}[$__interval])\n    and on (pod, fqdn) redis_instance_info{role=\"slave\", environment=\"$environment\"}\n) by (fqdn, pod)\n,1),0)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Redis Network Out - Primary",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2021 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_output_bytes_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n and on (pod, fqdn) redis_instance_info{role=\"master\", environment=\"$environment\"}\n) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Redis Network Out - Replicas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2021 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_output_bytes_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n and on (pod, fqdn) redis_instance_info{role=\"slave\", environment=\"$environment\"}\n) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Redis Network In - Primary",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2031 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n  and on (pod, fqdn) redis_instance_info{role=\"master\", environment=\"$environment\"}\n) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Redis Network In - Replicas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2031 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n  and on (pod, fqdn) redis_instance_info{role=\"slave\", environment=\"$environment\"}\n) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Slowlog Events - Primary",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2041 },
   "yaxes": [
    { "format": "short", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "sum(changes(redis_slowlog_last_id{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n  and on (pod, fqdn) redis_instance_info{role=\"master\", environment=\"$environment\"}\n) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Slowlog Events - Replicas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2041 },
   "yaxes": [
    { "format": "short", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "sum(changes(redis_slowlog_last_id{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n  and on (pod, fqdn) redis_instance_info{role=\"slave\", environment=\"$environment\"}\n) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Operation Rate per Command - Primary",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2051 },
   "yaxes": [
    { "format": "short", "label": "Operations/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n  and on (pod, fqdn) redis_instance_info{role=\"master\", environment=\"$environment\"}\n) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Operation Rate per Command - Replicas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2051 },
   "yaxes": [
    { "format": "short", "label": "Operations/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n  and on (pod, fqdn) redis_instance_info{role=\"slave\", environment=\"$environment\"}\n) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Average Operation Latency - Primary",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2061 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n  and on (pod, fqdn) redis_instance_info{role=\"master\", environment=\"$environment\"}\n) by (cmd)\n/\nsum(rate(redis_commands_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Average Operation Latency - Replicas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2061 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n  and on (pod, fqdn) redis_instance_info{role=\"slave\", environment=\"$environment\"}\n) by (cmd)\n/\nsum(rate(redis_commands_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Operation Latency - Primary",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2071 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n  and on (pod, fqdn) redis_instance_info{role=\"master\", environment=\"$environment\"}\n) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Operation Latency - Replicas",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2071 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n  and on (pod, fqdn) redis_instance_info{role=\"slave\", environment=\"$environment\"}\n) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  { "title": "Redis Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "description": "Redis holds all data in memory. Avoid memory saturation in Redis at all cost ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(max(\n  label_replace(redis_memory_used_rss_bytes{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}, \"memtype\", \"rss\",\"\",\"\")\n  or\n  label_replace(redis_memory_used_bytes{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}, \"memtype\", \"used\",\"\",\"\")\n) by (type, stage, environment, fqdn)\n/ on (fqdn) group_left\nnode_memory_MemTotal_bytes{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}\n,1),0)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    },
    {
     "expr": "max(slo:max:soft:gitlab_component_saturation:ratio{component=\"redis_memory\", environment=\"$environment\"})\n",
     "legendFormat": "Degradation SLO"
    },
    {
     "expr": "max(slo:max:hard:gitlab_component_saturation:ratio{component=\"redis_memory\", environment=\"$environment\"})\n",
     "legendFormat": "Outage SLO"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(redis_memory_used_bytes{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Memory Used Rate of Change",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3011 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_memory_used_bytes{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Redis RSS Usage",
   "type": "graph",
   "description": "Depending on the memory allocator used, Redis may not return memory to the operating system at the same rate that applications release keys. RSS indicates the operating systems perspective of Redis memory usage. So, even if usage is low, if RSS is high, the OOM killer may terminate the Redis process",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3011 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(redis_memory_used_rss_bytes{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Memory Fragmentation",
   "type": "graph",
   "description": "The fragmentation ratio in Redis should ideally be around 1.0 and generally below 1.5. The higher the value, the more wasted memory.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3021 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_rss_bytes{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"} / redis_memory_used_bytes{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Expired Keys",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3021 },
   "yaxes": [
    { "format": "short", "label": "Keys" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Keys Rate of Change",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3031 },
   "yaxes": [
    { "format": "short", "label": "Keys/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_db_keys{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 } },
  {
   "title": "Connected Secondaries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4001 },
   "yaxes": [
    { "format": "short", "label": "Secondaries" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(redis_connected_slaves{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  {
   "title": "Replication Offset",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4001 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "redis_master_repl_offset{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}\n- on(fqdn) group_right\nredis_connected_slave_offset_bytes{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}\n",
     "legendFormat": "secondary {{ slave_ip }}"
    }
   ]
  },
  {
   "title": "Resync Events",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4011 },
   "yaxes": [
    { "format": "short", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "sum(increase(redis_slave_resync_total{environment=\"$environment\",shard=~\"$shard\",type=\"redis-cluster-queues-meta\"}[$__interval])) by (fqdn, pod)\n",
     "legendFormat": "{{ pod }} {{ fqdn }}"
    }
   ]
  },
  { "title": "Cluster Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5000 } },
  {
   "title": "Number of Shards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5000 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (shard) (redis_cluster_size{environment=\"$environment\", shard=~\"$shard\", type=\"redis-cluster-queues-meta\"}))\n"
    }
   ]
  },
  {
   "title": "Redis Cluster Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5000 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_cluster_known_nodes{environment=\"$environment\", type=\"redis-cluster-queues-meta\"})\n"
    }
   ]
  },
  {
   "title": "Redis Cluster Slots OK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5000 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_cluster_slots_ok{environment=\"$environment\", shard=~\"$shard\", type=\"redis-cluster-queues-meta\"})\n"
    }
   ]
  },
  {
   "title": "Redis Cluster Slots Assigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5000 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_cluster_slots_assigned{environment=\"$environment\", shard=~\"$shard\", type=\"redis-cluster-queues-meta\"})\n"
    }
   ]
  },
  {
   "title": "Redis Cluster Slots Pfailed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5000 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_cluster_slots_pfail{environment=\"$environment\", shard=~\"$shard\", type=\"redis-cluster-queues-meta\"})\n"
    }
   ]
  },
  {
   "title": "Redis Cluster Slots Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5000 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redis_cluster_slots_fail{environment=\"$environment\", shard=~\"$shard\", type=\"redis-cluster-queues-meta\"})\n"
    }
   ]
  },
  {
   "title": "Shard Sizes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5004 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(redis_cluster_size{environment=\"$environment\", shard=~\"$shard\", type=\"redis-cluster-queues-meta\"}[$__interval])) by (shard)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Redis Cluster Redirection",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5008 },
   "yaxes": [
    { "format": "short", "label": "Redirections" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab:redis_cluster_redirections:irate1m{environment=$\"environment\", type=\"redis-cluster-queues-meta}) by (redirection_type)\n",
     "legendFormat": "{{ redirection_type }}"
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  redis-cluster-queues-meta\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  redis-cluster-queues-meta\nend\n\n\n  \n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  redis-cluster-queues-meta[\"redis-cluster-queues-meta (Level 2)\"]\nend\n\n\n  \n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}