{
 "title": "registry: Redis Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4757416433 at Fri Jul 28 03:22:08 UTC 2023",
 "tags": [
  "managed",
  "registry",
  "container registry",
  "docker",
  "registry",
  "redis",
  "cache"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   { "name": "Deployment", "query": "gitlab-registry," },
   {
    "name": "cluster",
    "query": "label_values(registry_redis_pool_stats_total_conns{environment=\"$environment\"}, cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(registry_redis_pool_stats_total_conns{environment=\"$environment\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "stat",
   "description": "The per-second rate of all Redis operations performed on the application side.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (\n  rate(registry_redis_single_commands_count{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval])\n)\n"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "stat",
   "description": "The number of Redis keys.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  max_over_time(\n    redis_db_keys{deployment=\"redis-registry-cache\", db=\"db0\", env=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "The p90 latency of all Redis operations performed on the application side.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_redis_single_commands_bucket{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "description": "The total number of established connections both in use and idle.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  max_over_time(\n    registry_redis_pool_stats_total_conns{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Connection Pool Saturation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  sum (registry_redis_pool_stats_total_conns{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"})\n  -\n  sum (registry_redis_pool_stats_idle_conns{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"})\n)\n/\nsum (registry_redis_pool_stats_max_conns{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"})\n"
    }
   ]
  },
  {
   "title": "Connection Pool Hit Ratio",
   "type": "stat",
   "description": "The percentage of time a free connection was found in the pool.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (registry_redis_pool_stats_hits{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"})\n/\n(\n  sum (registry_redis_pool_stats_hits{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"})\n  +\n  sum (registry_redis_pool_stats_misses{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"})\n)\n"
    }
   ]
  },
  { "title": "Single Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "RPS (Aggregate)",
   "type": "graph",
   "description": "The per-second rate of all single command operations performed on the application side.",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(registry_redis_single_commands_count{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval])\n)\n"
    }
   ]
  },
  {
   "title": "RPS (Per Command)",
   "type": "graph",
   "description": "The per-second rate of each single command operation performed on the application side.",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (\n  rate(registry_redis_single_commands_count{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval])\n)\n",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Latency (Aggregate)",
   "type": "graph",
   "description": "The p90 latency of all single command operations performed on the application side.",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_redis_single_commands_bucket{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Latency (Per Query)",
   "type": "graph",
   "description": "The p90 latency of each single command operation performed on the application side.",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 1001 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (le, command) (\n    rate(registry_redis_single_commands_bucket{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval])\n  )\n)\n",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  { "title": "Connection Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Hits",
   "type": "graph",
   "description": "The number of times a free connection was found in the pool.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_redis_pool_stats_hits{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Misses",
   "type": "graph",
   "description": "The number of times a free connection was not found in the pool.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 2001 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_redis_pool_stats_misses{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Open",
   "type": "graph",
   "description": "The total number of established connections both in use and idle.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_redis_pool_stats_total_conns{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "In Use",
   "type": "graph",
   "description": "The total number of connections currently in use.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2001 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_redis_pool_stats_total_conns{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval]))\n-\nsum(rate(registry_redis_pool_stats_idle_conns{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval]))\n"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "graph",
   "description": "The number of idle connections in the pool.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_redis_pool_stats_idle_conns{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Stale",
   "type": "graph",
   "description": "The number of stale connections removed from the pool.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 2011 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_redis_pool_stats_stale_conns{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "description": "The number of times a wait timeout occurred.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 2011 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_redis_pool_stats_timeouts{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation. Lower is better.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2011 },
   "yaxes": [
    { "format": "percentunit", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max((\n  sum (registry_redis_pool_stats_total_conns{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"})\n  -\n  sum (registry_redis_pool_stats_idle_conns{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"})\n)\n/\nsum (registry_redis_pool_stats_max_conns{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", exported_instance=~\"$instance\"})\n,1),0)\n"
    }
   ]
  }
 ]
}