{
 "title": "registry: Rails Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4903290496 at Fri Aug 18 19:48:03 UTC 2023",
 "tags": [
  "managed",
  "registry",
  "container registry",
  "registry",
  "rails"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   { "name": "Deployment", "query": "gitlab-registry," }
  ]
 },
 "panels": [
  { "title": "Repository Async Deletions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "In-progress",
   "type": "graph",
   "description": "The number of in-progress async container repository deletions.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg (\n    gitlab_database_rows{query_name=\"container_repositories_delete_ongoing\", environment=\"$environment\"}\n)\n"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "graph",
   "description": "The number of failed async container repository deletions.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg (\n    gitlab_database_rows{query_name=\"container_repositories_delete_failed\", environment=\"$environment\"}\n)\n"
    }
   ]
  },
  {
   "title": "Scheduled",
   "type": "graph",
   "description": "The number of scheduled async container repository deletions.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg (\n  gitlab_database_rows{query_name=\"container_repositories_delete_scheduled\", environment=\"$environment\"}\n)\n"
    }
   ]
  },
  {
   "title": "Staled",
   "type": "graph",
   "description": "The number of staled async container repository deletions.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg (\n  gitlab_database_rows{query_name=\"container_repositories_delete_staled\", environment=\"$environment\"}\n)\n"
    }
   ]
  },
  { "title": "Tag Cleanup Policies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Enabled",
   "type": "graph",
   "description": "The number of enabled tag cleanup policies.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg (\n  gitlab_database_rows{query_name=\"container_repositories_cleanup_enabled\", environment=\"$environment\"}\n)\n"
    }
   ]
  },
  {
   "title": "In-progress",
   "type": "graph",
   "description": "The number of in-progress tag cleanup policies.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg (\n  gitlab_database_rows{query_name=\"container_repositories_cleanup_ongoing\", environment=\"$environment\"}\n)\n"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "graph",
   "description": "The number of pending tag cleanup policies.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg (\n  gitlab_database_rows{query_name=\"container_repositories_cleanup_pending\", environment=\"$environment\"}\n)\n"
    }
   ]
  },
  {
   "title": "Scheduled",
   "type": "graph",
   "description": "The number of scheduled tag cleanup policies.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg (\n  gitlab_database_rows{query_name=\"container_repositories_cleanup_scheduled\", environment=\"$environment\"}\n)\n"
    }
   ]
  },
  {
   "title": "Staled",
   "type": "graph",
   "description": "The number of staled tag cleanup policies.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg (\n  gitlab_database_rows{query_name=\"container_repositories_cleanup_staled\", environment=\"$environment\"}\n)\n"
    }
   ]
  },
  {
   "title": "Unfinished",
   "type": "graph",
   "description": "The number of unfinished tag cleanup policies.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg (\n  gitlab_database_rows{query_name=\"container_repositories_cleanup_unfinished\", environment=\"$environment\"}\n)\n"
    }
   ]
  }
 ]
}