{
 "title": "registry: Database Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6762450133 at Thu May  2 07:54:17 UTC 2024",
 "tags": [
  "managed",
  "registry",
  "container registry",
  "docker",
  "registry"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   { "name": "Deployment", "query": "gitlab-registry," },
   {
    "name": "cluster",
    "query": "label_values(go_sql_dbstats_connections_in_use{app=\"registry\", environment=\"$environment\"}, cluster)"
   },
   {
    "name": "shard",
    "query": "label_values(gitlab_database_bloat_btree_bloat_size{type=\"patroni-registry\", environment=\"$environment\"}, shard)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "stat",
   "description": "The per-second rate of all database queries performed on the application side.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (\n  rate(registry_database_queries_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval])\n)\n"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "The p90 latency of all database query performed on the application side.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_database_query_duration_seconds_bucket{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "description": "The total number of established connections both in use and idle.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n  max_over_time(\n    go_sql_dbstats_connections_open{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Connection Pool Saturation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (go_sql_dbstats_connections_open{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"})\n/\nsum (go_sql_dbstats_connections_max_open{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"})\n"
    }
   ]
  },
  {
   "title": "Table Bloat",
   "type": "stat",
   "description": "The aggregate table bloat saturation.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  gitlab_component_saturation:ratio{type=\"patroni-registry\", environment=\"$environment\", component=\"pg_table_bloat\", shard=~\"$shard\"}[$__interval]\n)\n"
    }
   ]
  },
  {
   "title": "B-tree Bloat",
   "type": "stat",
   "description": "The aggregate B-tree bloat saturation.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time(\n  gitlab_component_saturation:ratio{type=\"patroni-registry\", environment=\"$environment\", component=\"pg_btree_bloat\", shard=~\"$shard\"}[$__interval]\n)\n"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "description": "Estimated database size.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  gitlab_database_bloat_table_real_size{type=\"patroni-registry\", environment=\"$environment\", shard=~\"$shard\"}\n)\n+\nsum (\n  gitlab_database_bloat_btree_real_size{type=\"patroni-registry\", environment=\"$environment\", shard=~\"$shard\"}\n)\n"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "RPS (Aggregate)",
   "type": "graph",
   "description": "The per-second rate of all database queries performed on the application side.",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(registry_database_queries_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval])\n)\n"
    }
   ]
  },
  {
   "title": "RPS (Per Query)",
   "type": "graph",
   "description": "The per-second rate of each database query performed on the application side.",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 1001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(registry_database_queries_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval])\n)\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Latency (Aggregate)",
   "type": "graph",
   "description": "The p90 latency of all database query performed on the application side.",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_database_query_duration_seconds_bucket{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Latency (Per Query)",
   "type": "graph",
   "description": "The p90 latency of each database query performed on the application side.",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 1001 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (le, name) (\n    rate(registry_database_query_duration_seconds_bucket{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval])\n  )\n)\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "Connection Pool (Aggregate)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Open",
   "type": "graph",
   "description": "The total number of established connections both in use and idle.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_dbstats_connections_open{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "In Use",
   "type": "graph",
   "description": "The total number of connections currently in use.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2001 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_dbstats_connections_in_use{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "graph",
   "description": "The total aggregated number of idle connections.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2001 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_dbstats_connections_idle{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation. Lower is better.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "percentunit", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum (go_sql_dbstats_connections_open{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"})\n/\nsum (go_sql_dbstats_connections_max_open{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"})\n,1),0)\n"
    }
   ]
  },
  {
   "title": "Wait Time",
   "type": "graph",
   "description": "The total aggregated time blocked waiting for a new connection. Lower is better.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2011 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_sql_dbstats_connections_wait_seconds_total{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Waits",
   "type": "graph",
   "description": "The total number of connections waited for.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2011 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_sql_dbstats_connections_waits_total{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Closed (Max Idle Count)",
   "type": "graph",
   "description": "The total number of connections closed due to the maximum idle count limit.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2021 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_sql_dbstats_connections_max_idle_closed_count_total{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Closed (Max Idle Time)",
   "type": "graph",
   "description": "The total number of connections closed due to the maximum idle time limit.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2021 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_sql_dbstats_connections_max_idle_time_closed_count_total{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Closed (Max Lifetime)",
   "type": "graph",
   "description": "The total number of connections closed due to the maximum lifetime limit.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2021 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_sql_dbstats_connections_max_lifetime_closed_count_total{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Connection Pool (Per Pod)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open",
     "type": "graph",
     "description": "The number of established connections both in use and idle per pod.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3001 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "sum(go_sql_dbstats_connections_open{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "In Use",
     "type": "graph",
     "description": "The number of connections currently in use per pod.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3001 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "sum(go_sql_dbstats_connections_in_use{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Idle",
     "type": "graph",
     "description": "The number of idle connections per pod.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3001 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "sum(go_sql_dbstats_connections_idle{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Saturation",
     "type": "graph",
     "description": "Saturation per pod. Lower is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3011 },
     "yaxes": [
      { "format": "percentunit", "label": "Utilization" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(sum by (pod) (go_sql_dbstats_connections_open{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"})\n/\nsum by (pod) (go_sql_dbstats_connections_max_open{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"})\n,1),0)\n",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Wait Time",
     "type": "graph",
     "description": "The aggregated time blocked waiting for a new connection per pod. Lower is better.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 3011 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "sum(rate(go_sql_dbstats_connections_wait_seconds_total{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Waits",
     "type": "graph",
     "description": "The number of connections waited for per pod.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 3011 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "sum(max_over_time(go_sql_dbstats_connections_waits_total{app=\"registry\", environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Table Bloat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Saturation (Aggregate)",
     "type": "graph",
     "description": "The aggregate table bloat saturation.",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 4001 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max_over_time(\n  gitlab_component_saturation:ratio{type=\"patroni-registry\", environment=\"$environment\", component=\"pg_table_bloat\"}[$__interval]\n)\n,1),0)\n"
      }
     ]
    },
    {
     "title": "Saturation (Per Table)",
     "type": "graph",
     "description": "The table bloat saturation. Limited to the top 20 entries.",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 4001 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk (\n  20,\n  max by (query_name) (gitlab_database_bloat_table_bloat_ratio{type=\"patroni-registry\", environment=\"$environment\", shard=~\"$shard\", query_name!~\"pg_.*\"})\n)\n",
       "legendFormat": "{{ query_name }}"
      }
     ]
    },
    {
     "title": "Bloat Size",
     "type": "graph",
     "description": "The table bloat size. Limited to the top 20 entries.",
     "gridPos": { "h": 13, "w": 6, "x": 12, "y": 4001 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk (\n  20,\n  max by (query_name) (gitlab_database_bloat_table_bloat_size{type=\"patroni-registry\", environment=\"$environment\", shard=~\"$shard\", query_name!~\"pg_.*\"})\n)\n",
       "legendFormat": "{{ query_name }}"
      }
     ]
    },
    {
     "title": "Real Size",
     "type": "graph",
     "description": "The table real size. Limited to the top 20 entries.",
     "gridPos": { "h": 13, "w": 6, "x": 18, "y": 4001 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk (\n  20,\n  max by (query_name) (gitlab_database_bloat_table_real_size{type=\"patroni-registry\", environment=\"$environment\", shard=~\"$shard\", query_name!~\"pg_.*\"})\n)\n",
       "legendFormat": "{{ query_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "B-tree Bloat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Saturation (Aggregate)",
     "type": "graph",
     "description": "The aggregate B-tree bloat saturation.",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 5001 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max_over_time(\n  gitlab_component_saturation:ratio{type=\"patroni-registry\", environment=\"$environment\", component=\"pg_btree_bloat\"}[$__interval]\n)\n,1),0)\n"
      }
     ]
    },
    {
     "title": "Saturation (Per Index)",
     "type": "graph",
     "description": "The B-tree bloat saturation per index. Limited to the top 20 entries.",
     "gridPos": { "h": 13, "w": 6, "x": 6, "y": 5001 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk (\n  20,\n  max by (query_name) (gitlab_database_bloat_btree_bloat_ratio{type=\"patroni-registry\", environment=\"$environment\", shard=~\"$shard\", query_name!~\"pg_.*\"})\n)\n",
       "legendFormat": "{{ query_name }}"
      }
     ]
    },
    {
     "title": "Bloat Size",
     "type": "graph",
     "description": "The B-tree bloat size per index. Limited to the top 20 entries.",
     "gridPos": { "h": 13, "w": 6, "x": 12, "y": 5001 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk (\n  20,\n  max by (query_name) (gitlab_database_bloat_btree_bloat_size{type=\"patroni-registry\", environment=\"$environment\", shard=~\"$shard\", query_name!~\"pg_.*\"})\n)\n",
       "legendFormat": "{{ query_name }}"
      }
     ]
    },
    {
     "title": "Real Size",
     "type": "graph",
     "description": "The B-tree real size per index. Limited to the top 20 entries.",
     "gridPos": { "h": 13, "w": 6, "x": 18, "y": 5001 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk (\n  20,\n  max by (query_name) (gitlab_database_bloat_btree_real_size{type=\"patroni-registry\", environment=\"$environment\", shard=~\"$shard\", query_name!~\"pg_.*\"})\n)\n",
       "legendFormat": "{{ query_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CloudSQL (pre only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6000 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "graph",
     "description": "CPU utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6001 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization{database_id=~\".+:registry-db.+\", environment=\"$environment\"}",
       "legendFormat": "{{ database_id }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6001 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_memory_utilization{database_id=~\".+:registry-db.+\", environment=\"$environment\"}",
       "legendFormat": "{{ database_id }}"
      }
     ]
    },
    {
     "title": "Disk Utilization",
     "type": "graph",
     "description": "Data utilization in bytes.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6001 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_disk_bytes_used{database_id=~\".+:registry-db.+\", environment=\"$environment\"}",
       "legendFormat": "{{ database_id }}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "description": "Delta count of number of transactions. Sampled every 60 seconds.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6011 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (database_id) (\n  avg_over_time(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_postgresql_transaction_count{database_id=~\".+:registry-db.+\", environment=\"$environment\"}[$__interval])\n)\n",
       "legendFormat": "{{ database_id }}"
      }
     ]
    }
   ]
  }
 ]
}