{
 "title": "registry: Application Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4133321089 at Tue Apr 18 13:32:48 UTC 2023",
 "tags": [
  "managed",
  "registry",
  "container registry",
  "docker",
  "registry"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   { "name": "Deployment", "query": "gitlab-(cny-)?registry," },
   {
    "name": "cluster",
    "query": "label_values(registry_storage_action_seconds_count{environment=\"$environment\"}, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(gitlab_build_info{app=\"registry\", cluster=~\"$cluster\", environment=\"$environment\", namespace=\"$namespace\", stage=\"$stage\"}) by (cluster, version)",
     "legendFormat": "{{ cluster }}: {{ version }}"
    }
   ]
  },
  { "title": "Host Resources Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Process CPU Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=~\"^$Deployment.*\", cluster=~\"$cluster\", namespace=\"$namespace\", environment=\"$environment\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1001 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\"^$Deployment.*\", cluster=~\"$cluster\", namespace=\"$namespace\", environment=\"$environment\", stage=\"$stage\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{service=~\"^$Deployment.*\", cluster=~\"$cluster\", namespace=\"$namespace\", environment=\"$environment\", stage=\"$stage\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "HTTP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_http_requests_total{cluster=~\"$cluster\", namespace=\"$namespace\", environment=\"$environment\", stage=\"$stage\"}[1m])) by (method, route, code)",
     "legendFormat": "{{ method }} {{ route }}: {{ code }}"
    }
   ]
  },
  {
   "title": "In-Flight Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(registry_http_in_flight_requests{cluster=~\"$cluster\", namespace=\"$namespace\", environment=\"$environment\", stage=\"$stage\"}) by (method, route, code)",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  { "title": "Storage Drivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "Action Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(registry_storage_action_seconds_sum{job=~\".*registry.*\", cluster=~\"$cluster\", namespace=\"$namespace\", environment=\"$environment\", stage=\"$stage\"}[$__interval])) by (action)",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 } },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4001 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_storage_cache_total{cluster=~\"$cluster\", namespace=\"$namespace\", environment=\"$environment\", stage=\"$stage\"}[1m])) by (type)"
    }
   ]
  },
  {
   "title": "Hit %",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4001 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{cluster=~\"$cluster\", environment=\"$environment\", namespace=\"$namespace\", stage=\"$stage\", exported_type=\"Hit\"}[$__interval])) / sum(rate(registry_storage_cache_total{cluster=~\"$cluster\", environment=\"$environment\", namespace=\"$namespace\", stage=\"$stage\", exported_type=\"Request\"}[$__interval]))"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5000 } },
  {
   "title": "Uploaded Bytes",
   "type": "stat",
   "description": "The number of bytes uploaded to the registry.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5001 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(registry_storage_blob_upload_bytes_sum{environment=\"$environment\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Downloaded Bytes",
   "type": "stat",
   "description": "The number of bytes downloaded from the registry.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5001 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(registry_storage_blob_download_bytes_sum{environment=\"$environment\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  }
 ]
}