{
 "title": "registry: Overview with migration_path",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/1476083129 at Wed Aug  4 10:15:19 UTC 2021",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   { "name": "migration_path", "query": "old,new" }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "registry Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "registry apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "registry apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "registry Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "registry error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"}))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"}))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "registry error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"}))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "registry Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "registry RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "registry Service | Latency/Apdex"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "registry Service | Errors"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "database SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "database apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "database apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "database SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "database RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": {
    "content": "### Description\n\nAggregation of all container registry database operations.\n\n"
   },
   "content": "### Description\n\nAggregation of all container registry database operations.\n\n"
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"database\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "database SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "garbagecollector SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "garbagecollector apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "garbagecollector apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "garbagecollector SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "garbagecollector RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "options": {
    "content": "### Description\n\nAggregation of all container registry online garbage collection operations.\n\n"
   },
   "content": "### Description\n\nAggregation of all container registry online garbage collection operations.\n\n"
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"garbagecollector\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "garbagecollector SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "loadbalancer SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "loadbalancer error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"}))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"}))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "loadbalancer error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"}))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "loadbalancer SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "loadbalancer RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "options": {
    "content": "### Description\n\nMeasures aggregated HTTP request traffic through the HAProxy.\n5xx responses are considered to be failures.\n\n"
   },
   "content": "### Description\n\nMeasures aggregated HTTP request traffic through the HAProxy.\n5xx responses are considered to be failures.\n\n"
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"loadbalancer\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "loadbalancer SLI | Errors"
    }
   ]
  },
  {
   "title": "server SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "server SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "server error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"}))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"}))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "server error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"}))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "server SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "options": {
    "content": "### Description\n\nAggregation of all registry requests.\n\n\n\n### Observability Tools\n\n* [GKE Deployment: gitlab-registry](https://console.cloud.google.com/kubernetes/deployment/us-east1/gprd-gitlab-gke/gitlab/gitlab-registry/overview?project=gitlab-production)\n* [Stackdriver Logs: GKE Container Logs](https://console.cloud.google.com/logs/query;query=labels%2E%22k8s%2Dpod%2Ftype%22%3D%22registry%22%0Aresource%2Elabels%2Ecluster%5Fname%3D%22gprd%2Dgitlab%2Dgke%22%0Aresource%2Elabels%2Econtainer%5Fname%3D%22registry%22%0Aresource%2Elabels%2Enamespace%5Fname%3D%22gitlab%22%0Aresource%2Elabels%2Eproject%5Fid%3D%22gitlab%2Dproduction%22%0Aresource%2Etype%3D%22k8s%5Fcontainer%22;timeRange=PT30M?project=gitlab-production)\n* [📖 Kibana: Registry logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.remote_ip,json.duration_ms,json.code,json.msg,json.status,json.error,json.method,json.uri),filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),index:'97ce8e90-63ad-11ea-8617-2347010d3aab')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Registry slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.remote_ip,json.duration_ms,json.code,json.msg,json.status,json.error,json.method,json.uri),filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase)))),(query:(range:(json.duration_ms:(gte:10000))))),index:'97ce8e90-63ad-11ea-8617-2347010d3aab',sort:!(!(json.duration_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Registry failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.remote_ip,json.duration_ms,json.code,json.msg,json.status,json.error,json.method,json.uri),filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase)))),(query:(range:(json.status:(gte:500))))),index:'97ce8e90-63ad-11ea-8617-2347010d3aab')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase)))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/gitlab-registry;type=CPU/cpu?project=gitlab-production)\n\n"
   },
   "content": "### Description\n\nAggregation of all registry requests.\n\n\n\n### Observability Tools\n\n* [GKE Deployment: gitlab-registry](https://console.cloud.google.com/kubernetes/deployment/us-east1/gprd-gitlab-gke/gitlab/gitlab-registry/overview?project=gitlab-production)\n* [Stackdriver Logs: GKE Container Logs](https://console.cloud.google.com/logs/query;query=labels%2E%22k8s%2Dpod%2Ftype%22%3D%22registry%22%0Aresource%2Elabels%2Ecluster%5Fname%3D%22gprd%2Dgitlab%2Dgke%22%0Aresource%2Elabels%2Econtainer%5Fname%3D%22registry%22%0Aresource%2Elabels%2Enamespace%5Fname%3D%22gitlab%22%0Aresource%2Elabels%2Eproject%5Fid%3D%22gitlab%2Dproduction%22%0Aresource%2Etype%3D%22k8s%5Fcontainer%22;timeRange=PT30M?project=gitlab-production)\n* [📖 Kibana: Registry logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.remote_ip,json.duration_ms,json.code,json.msg,json.status,json.error,json.method,json.uri),filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),index:'97ce8e90-63ad-11ea-8617-2347010d3aab')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Registry slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.remote_ip,json.duration_ms,json.code,json.msg,json.status,json.error,json.method,json.uri),filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase)))),(query:(range:(json.duration_ms:(gte:10000))))),index:'97ce8e90-63ad-11ea-8617-2347010d3aab',sort:!(!(json.duration_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Registry failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.remote_ip,json.duration_ms,json.code,json.msg,json.status,json.error,json.method,json.uri),filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase)))),(query:(range:(json.status:(gte:500))))),index:'97ce8e90-63ad-11ea-8617-2347010d3aab')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase)))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Registry percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=97ce8e90-63ad-11ea-8617-2347010d3aab&_a=(filters:!((query:(match:(json.type.keyword:(query:registry,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:registry,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/gitlab-registry;type=CPU/cpu?project=gitlab-production)\n\n"
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server SLI | Latency/Apdex"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"server\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"registry\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server SLI | Errors"
    }
   ]
  },
  {
   "title": "server_route_manifest_reads SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_manifest_reads apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_manifest_reads apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "server_route_manifest_reads SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_manifest_reads RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "options": {
    "content": "### Description\n\nAll read-requests (HEAD or GET) for the manifest endpoints on\nthe registry.\nFetch the manifest identified by name and reference where reference can be\na tag or digest. A HEAD request can also be issued to this endpoint to\nobtain resource information without receiving all data.\n\n"
   },
   "content": "### Description\n\nAll read-requests (HEAD or GET) for the manifest endpoints on\nthe registry.\nFetch the manifest identified by name and reference where reference can be\na tag or digest. A HEAD request can also be issued to this endpoint to\nobtain resource information without receiving all data.\n\n"
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"server_route_manifest_reads\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server_route_manifest_reads SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "server_route_manifest_writes SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_manifest_writes apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_manifest_writes apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "server_route_manifest_writes SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "server_route_manifest_writes RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "options": {
    "content": "### Description\n\nAll write-requests (put, delete) for the manifest endpoints on\nthe registry.\n\nPut the manifest identified by name and reference where reference can be\na tag or digest.\n\nDelete the manifest identified by name and reference. Note that a manifest\ncan only be deleted by digest.\n\n"
   },
   "content": "### Description\n\nAll write-requests (put, delete) for the manifest endpoints on\nthe registry.\n\nPut the manifest identified by name and reference where reference can be\na tag or digest.\n\nDelete the manifest identified by name and reference. Note that a manifest\ncan only be deleted by digest.\n\n"
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"server_route_manifest_writes\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "server_route_manifest_writes SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "storage SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "storage apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "storage apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "storage SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}[$__interval])\n",
     "legendFormat": "storage RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "options": {
    "content": "### Description\n\nAggregation of all container registry GCS storage operations.\n\n"
   },
   "content": "### Description\n\nAggregation of all container registry GCS storage operations.\n\n"
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"storage\",env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"registry\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"registry\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "storage SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "🔬 database Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 database Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_database_query_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall"
      }
     ]
    },
    {
     "title": "database RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_database_queries_total{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p90 database Latency - per name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (name,le) (\n    rate(registry_database_query_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{name}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for database Latency - per name",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (name) (\n  rate(registry_database_query_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (name) (\n    rate(registry_database_query_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\", le=\"1\"}[$__interval])\n  )\n  +\n  sum by (name) (\n    rate(registry_database_query_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\", le=\"2.5\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(name) group_left()\n(\n  sum by () (\n  rate(registry_database_query_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "database RPS - per name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (\n  rate(registry_database_queries_total{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 garbagecollector Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 garbagecollector Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_gc_run_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall"
      }
     ]
    },
    {
     "title": "garbagecollector RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_gc_runs_total{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p90 garbagecollector Latency - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (worker,le) (\n    rate(registry_gc_run_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{worker}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for garbagecollector Latency - per worker",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (worker) (\n  rate(registry_gc_run_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (worker) (\n    rate(registry_gc_run_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\", le=\"1\"}[$__interval])\n  )\n  +\n  sum by (worker) (\n    rate(registry_gc_run_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\", le=\"2\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(worker) group_left()\n(\n  sum by () (\n  rate(registry_gc_run_duration_seconds_bucket{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "garbagecollector RPS - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (\n  rate(registry_gc_runs_total{type=\"registry\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "{{worker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 server Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 server Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall"
      }
     ]
    },
    {
     "title": "server Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_requests_total{code=~\"5..\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "server RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p90 server Latency - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (route,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{route}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server Latency - per route",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (route) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (route) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"2.5\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n  +\n  sum by (route) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"25\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(route) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "server Errors - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (\n  rate(registry_http_requests_total{code=~\"5..\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "server RPS - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (\n  rate(registry_http_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Estimated p90 server Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (method,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"2.5\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"25\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(method) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server Errors - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_requests_total{code=~\"5..\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 server_route_manifest_reads Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 server_route_manifest_reads Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall"
      }
     ]
    },
    {
     "title": "server_route_manifest_reads RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p90 server_route_manifest_reads Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (method,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_manifest_reads Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"0.5\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"1\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(method) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_reads RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 server_route_manifest_writes Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 server_route_manifest_writes Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall"
      }
     ]
    },
    {
     "title": "server_route_manifest_writes RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p90 server_route_manifest_writes Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (method,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_manifest_writes Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"10\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"25\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(method) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_writes RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 storage Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 storage Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall"
      }
     ]
    },
    {
     "title": "storage RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_storage_action_seconds_count{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p90 storage Latency - per action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (action,le) (\n    rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{action}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for storage Latency - per action",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (action) (\n  rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n  -\n  (\n    sum by (action) (\n  rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\", le=\"1\"}[$__interval])\n)\n\n  )\n)\n/ ignoring(action) group_left()\n(\n  sum by () (\n  rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\", le=\"+Inf\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "storage RPS - per action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (action) (\n  rate(registry_storage_action_seconds_count{env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "{{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "avg(instance:node_cpu_utilization:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "sum(rate(node_network_receive_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_reads_completed_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_writes_completed_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_read_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_written_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Total Time",
     "type": "graph",
     "description": "Total time spent in read operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_read_time_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Total Time",
     "type": "graph",
     "description": "Total time spent in write operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_write_time_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "CPU Scheduling Waiting",
     "type": "graph",
     "description": "CPU scheduling waiting on the run queue, as a percentage of time. Aggregated to worst CPU per node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "max by (fqdn) (\n  rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[5m])\n)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg1 per core",
     "type": "graph",
     "description": "Loadavg (1 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "loadavg1" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load1{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg5 per core",
     "type": "graph",
     "description": "Loadavg (5 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg5" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load5{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg15 per core",
     "type": "graph",
     "description": "Loadavg (15 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg15" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load15{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "registry Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      deployment=\"registry\",env=\"$environment\",environment=\"$environment\",type=\"registry\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "registry Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    deployment=\"registry\",env=\"$environment\",environment=\"$environment\",type=\"registry\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "registry Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"registry\",env=\"$environment\",environment=\"$environment\",type=\"registry\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"registry\",env=\"$environment\",environment=\"$environment\",type=\"registry\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "Node CPU Requests Utilization",
     "type": "graph",
     "description": "Ratio of requested CPU resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by memory requests already.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests_cpu_cores\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",type=\"registry\",resource=\"cpu\"}\n",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Node Memory Requests Utilization",
     "type": "graph",
     "description": "Ratio of requested Memory resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by CPU requests already.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests_memory_bytes\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",type=\"registry\",resource=\"memory\"}\n",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu component saturation: Average Service CPU Utilization",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a service fleet.\nIf it is becoming saturated, it may indicate that the fleet needs\nhorizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"cpu\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"cpu\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_inodes component saturation: Disk inode Utilization per Device per Node",
     "type": "graph",
     "description": "Disk inode utilization per device per node.\n\nIf this is too high, its possible that a directory is filling up with\nfiles. Consider logging in an checking temp directories for large numbers\nof files\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      1 - (\n        node_filesystem_files_free{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n        /\n        node_filesystem_files{fstype=~\"(ext.|xfs)\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"disk_inodes\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"disk_inodes\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"disk_inodes\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_space component saturation: Disk Space Utilization per Device per Node",
     "type": "graph",
     "description": "Disk space utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      (\n        1 - instance:node_filesystem_avail:ratio{fstype=~\"ext.|xfs\", fqdn!=\"\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"disk_space\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"disk_space\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"disk_space\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "go_memory component saturation: Go Memory Utilization per Node",
     "type": "graph",
     "description": "Go's memory allocation strategy can make it look like a Go process is saturating memory when measured using RSS, when in fact\nthe process is not at risk of memory saturation. For this reason, we measure Go processes using the `go_memstat_alloc_bytes`\nmetric instead of RSS.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, fqdn) (\n        go_memstats_alloc_bytes{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n      )\n      /\n      sum by (environment, tier, type, stage, fqdn) (\n        node_memory_MemTotal_bytes{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"go_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"go_memory\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"go_memory\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. When this is exhausted, the container may be thottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_container_cpu\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_container_cpu\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_container_memory component saturation: Kube Container Memory Utilization",
     "type": "graph",
     "description": "Records the total memory utilization for containers for this service, as a percentage of\nthe memory limit as configured through Kubernetes.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, pod, container) (\n  clamp_min(\n    clamp_max(\n      container_memory_working_set_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n      /\n      (container_spec_memory_limit_bytes:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"} > 0)\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_container_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_container_memory\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_container_memory\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_go_memory component saturation: Go Memory Utilization per Node",
     "type": "graph",
     "description": "Measures Go memory usage as a percentage of container memory limit\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, cluster, pod) (\n  clamp_min(\n    clamp_max(\n      (\n        go_memstats_alloc_bytes{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n        / on(environment, tier, type, stage, cluster, pod) group_left()\n        topk by(environment, tier, type, stage, cluster, pod) (1,\n          container_spec_memory_limit_bytes:labeled{container=~\"gitlab-workhorse|kas|registry|thanos-store\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n        )\n      )\n      or\n      (\n        go_memstats_alloc_bytes{type=\"monitoring\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n        / on(environment, tier, type, cluster, pod) group_left()\n        topk by (environment, tier, type, cluster, pod) (1,\n          container_spec_memory_limit_bytes:labeled{type=\"monitoring\", container=~\"gitlab-workhorse|kas|registry|thanos-store\"}\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ cluster }} {{ pod }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_go_memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_go_memory\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_go_memory\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_hpa_desired_replicas component saturation: HPA Desired Replicas",
     "type": "graph",
     "description": "The HPA is the [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/).\nIt automatically scales the number of Pods in a deployment based on metrics.\n\nThe HPA has a configured upper maximum. When this limit is reached, the HPA will not increase the number of pods and\nother resource saturation (eg, CPU, memory) may occur.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, hpa, shard) (\n  clamp_min(\n    clamp_max(\n      kube_hpa_status_desired_replicas:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|imports|memory-bound|urgent-other\"}\n      /\n      kube_hpa_spec_max_replicas:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", shard!~\"database-throttled|elasticsearch|gitaly-throttled|imports|memory-bound|urgent-other\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ hpa }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_hpa_desired_replicas\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_hpa_desired_replicas\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_hpa_desired_replicas\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_hpa_desired_replicas\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_hpa_desired_replicas\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_pool_cpu component saturation: Average Node Pool CPU Utilization",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in the node pool for\na service fleet.\n\nIf it is becoming saturated, it may indicate that the fleet needs horizontal scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage) (\n        rate(node_cpu_seconds_total:labeled{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_pool_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_pool_cpu\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_pool_cpu\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_pool_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_pool_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "kube_pool_max_nodes component saturation: Kube Pool Max Node Limit",
     "type": "graph",
     "description": "A GKE kubernetes node pool is close to it's maximum number of nodes.\n\nThe maximum is defined in terraform, via the `max_node_count` field of a node pool. The limit is per-zone, so for\nsingle zone clusters the number of nodes will match the limit, for regional clusters, the limit is multiplied by\nthe number of zones the cluster is deployed over.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(env, environment, tier, type, stage, cluster, label_pool, shard) (\n  clamp_min(\n    clamp_max(\n      count by (cluster, env, environment, label_pool, tier, type, stage, shard) (\n        kube_node_labels:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n      )\n      / on(cluster, env, environment, label_pool) group_left() (\n        label_replace(\n          terraform_report_google_cluster_node_pool_max_node_count,\n          \"label_pool\", \"$0\", \"pool_name\", \".*\"\n        )\n        * on(cluster, env, environment) group_left()\n        count by (cluster, env, environment) (\n          group by (cluster, env, environment, label_topology_kubernetes_io_zone) (\n            kube_node_labels:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n          )\n        )\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ cluster }} {{ label_pool }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_pool_max_nodes\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_pool_max_nodes\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"kube_pool_max_nodes\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_pool_max_nodes\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_pool_max_nodes\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "memory component saturation: Memory Utilization per Node",
     "type": "graph",
     "description": "Memory utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn) (\n  clamp_min(\n    clamp_max(\n      instance:node_memory_utilization:ratio{fqdn!=\"\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"memory\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"memory\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"memory\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "nf_conntrack_entries component saturation: conntrack Entries per Node",
     "type": "graph",
     "description": "Netfilter connection tracking table utilization per node.\n\nWhen saturated, new connection attempts (incoming SYN packets) are dropped with no reply, leaving clients to slowly retry (and typically fail again) over the next several seconds.  When packets are being dropped due to this condition, kernel will log the event as: \"nf_conntrack: table full, dropping packet\".\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn, instance) (\n  clamp_min(\n    clamp_max(\n      max_over_time(node_nf_conntrack_entries{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[1m])\n      /\n      node_nf_conntrack_entries_limit{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"nf_conntrack_entries\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"nf_conntrack_entries\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"nf_conntrack_entries\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "node_schedstat_waiting component saturation: Node Scheduler Waiting Time",
     "type": "graph",
     "description": "Measures the amount of scheduler waiting time that processes are waiting\nto be scheduled, according to [`CPU Scheduling Metrics`](https://www.robustperception.io/cpu-scheduling-metrics-from-the-node-exporter).\n\nA high value indicates that a node has more processes to be run than CPU time available\nto handle them, and may lead to degraded responsiveness and performance from the application.\n\nAdditionally, it may indicate that the fleet is under-provisioned.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn, shard) (\n  clamp_min(\n    clamp_max(\n      avg without (cpu) (rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[1h]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"node_schedstat_waiting\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"node_schedstat_waiting\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"node_schedstat_waiting\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"open_fds\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"open_fds\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "shard_cpu component saturation: Average CPU Utilization per Shard",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a shard of a\nservice fleet. If it is becoming saturated, it may indicate that the\nshard needs horizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage, shard) (\n        rate(node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"shard_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"shard_cpu\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"shard_cpu\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "single_node_cpu component saturation: Average CPU Utilization per Node",
     "type": "graph",
     "description": "Average CPU utilization per Node.\n\nIf average CPU is satured, it may indicate that a fleet is in need to horizontal or vertical scaling. It may also indicate\nimbalances in load in a fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn) (\n  clamp_min(\n    clamp_max(\n      avg without(cpu, mode) (1 - rate(node_cpu_seconds_total{fqdn!=\"\", mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\"}[5m]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"single_node_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"single_node_cpu\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\", component=\"single_node_cpu\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "content": "graph TD\n  subgraph db\n  patroni\n  pgbouncer\n  redis\n  redis-cache\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph stor\n  gitaly\n  praefect\nend\n\nsubgraph sv\n  api\n  registry\nend\n\n\n  api --> gitaly\napi --> patroni\napi --> pgbouncer\napi --> praefect\napi --> redis\napi --> redis-cache\napi --> redis-sidekiq\napi --> redis-tracechunks\ngitaly --> gitaly\npgbouncer --> patroni\npraefect --> gitaly\nregistry --> api\n",
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "content": "graph TD\n  subgraph db\n  patroni\n  pgbouncer\n  redis\n  redis-cache\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph stor\n  gitaly\n  praefect\nend\n\nsubgraph sv\n  api\n  registry\nend\n\n\n  api --> gitaly\napi --> patroni\napi --> pgbouncer\napi --> praefect\napi --> redis\napi --> redis-cache\napi --> redis-sidekiq\napi --> redis-tracechunks\ngitaly --> gitaly\npgbouncer --> patroni\npraefect --> gitaly\nregistry --> api\n",
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 76 },
   "options": {
    "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./registry/main.dashboard.jsonnet)\n"
   },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./registry/main.dashboard.jsonnet)\n"
  }
 ]
}