{
 "title": "registry: Application Info",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/1326129427 at Tue Jun  8 03:22:01 UTC 2021",
 "tags": [
  "managed",
  "registry",
  "container registry",
  "docker",
  "registry"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   { "name": "Deployment", "query": "gitlab-registry," }
  ]
 },
 "panels": [
  { "title": "Build Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(gitlab_build_info{app=\"registry\", cluster=\"$cluster\", namespace=\"$namespace\"}) by (version)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  { "title": "Stackdriver Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Log messages with severity ERROR",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"ERROR\", pod_id=~\"^$Deployment.*\", cluster_name=\"$cluster\", namespace_id=\"$namespace\"}) / 60",
     "legendFormat": "ERROR msgs per second"
    }
   ]
  },
  {
   "title": "Log messages with severity INFO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"INFO\", pod_id=~\"^$Deployment.*\", cluster_name=\"$cluster\", namespace_id=\"$namespace\"}) / 60",
     "legendFormat": "INFO msgs per second"
    }
   ]
  },
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Process CPU Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=~\"^$Deployment.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\"^$Deployment.*\", cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{service=~\"^$Deployment.*\", cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_http_requests_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (method, route, code)",
     "legendFormat": "{{ method }} {{ route }}: {{ code }}"
    }
   ]
  },
  {
   "title": "In-Flight HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_http_in_flight_requests{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (method, route, code)",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  {
   "title": "Registry Action Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3011 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(registry_storage_action_seconds_sum{job=~\".*registry.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval])) by (action)",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Cache Requests Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3011 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(registry_storage_cache_total{cluster=\"$cluster\", namespace=\"$namespace\"}[1m])) by (type)"
    }
   ]
  },
  {
   "title": "Cache Hit %",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3021 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{cluster=\"$cluster\", environment=\"$environment\", namespace=\"$namespace\",exported_type=\"Hit\"}[$__interval])) / sum(rate(registry_storage_cache_total{environment=\"$environment\",exported_type=\"Request\"}[$__interval]))"
    }
   ]
  },
  { "title": "Handler Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 } },
  {
   "title": "manifest",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4001 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{route=\"/v2/{name}/manifests/{reference}\",cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "blob_upload_chunk",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4001 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{route=\"/v2/{name}/blobs/uploads/{uuid}\", cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "blob",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4001 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{route=\"/v2/{name}/blobs/{digest}\",cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "base",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4011 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{route=\"/v2/\",cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "tags",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4011 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{route=\"/v2/{name}/tags/list\", cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  },
  {
   "title": "blob_upload",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4011 },
   "targets": [
    {
     "expr": "rate(registry_http_request_duration_seconds_bucket{route=\"/v2/{name}/blobs/uploads/\", cluster=\"$cluster\", namespace=\"$namespace\"}[10m])"
    }
   ]
  }
 ]
}