{
 "title": "registry: Database Info",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/1433463725 at Mon Jul 19 01:21:15 UTC 2021",
 "tags": [
  "managed",
  "registry",
  "container registry",
  "docker",
  "registry"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   { "name": "Deployment", "query": "gitlab-registry," }
  ]
 },
 "panels": [
  { "title": "Connection Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Open",
   "type": "graph",
   "description": "The total number of established connections both in use and idle.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_dbstats_connections_open{app=\"registry\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total In Use",
   "type": "graph",
   "description": "The total number of connections currently in use.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_dbstats_connections_in_use{app=\"registry\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Idle",
   "type": "graph",
   "description": "The total number of idle connections.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_dbstats_connections_idle{app=\"registry\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Open per Pod",
   "type": "graph",
   "description": "The number of established connections both in use and idle per pod.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_dbstats_connections_open{app=\"registry\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "In Use per Pod",
   "type": "graph",
   "description": "The number of connections currently in use per pod.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_dbstats_connections_in_use{app=\"registry\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Idle per Pod",
   "type": "graph",
   "description": "The number of idle connections per pod.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_dbstats_connections_idle{app=\"registry\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total Wait Time",
   "type": "graph",
   "description": "The total time blocked waiting for a new connection. Lower is better.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "rate(wait_seconds_total{app=\"registry\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Saturation per Pod",
   "type": "graph",
   "description": "Saturation per pod. Lower is better.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Utilization" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (pod) (go_sql_dbstats_connections_open{app=\"registry\", cluster=\"$cluster\", namespace=\"$namespace\"})\n/\nsum by (pod) (go_sql_dbstats_connections_max_open{app=\"registry\", cluster=\"$cluster\", namespace=\"$namespace\"})\n,1),0)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "CloudSQL (pre only)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "CPU utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 501 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization{database_id=~\".+:registry-db.+\", environment=\"$environment\"}",
     "legendFormat": "{{ database_id }}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "description": "Memory utilization.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 501 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_memory_utilization{database_id=~\".+:registry-db.+\", environment=\"$environment\"}",
     "legendFormat": "{{ database_id }}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "description": "Data utilization in bytes.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 501 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_disk_bytes_used{database_id=~\".+:registry-db.+\", environment=\"$environment\"}",
     "legendFormat": "{{ database_id }}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "Delta count of number of transactions. Sampled every 60 seconds.\n\nSee https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql for\nmore details.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 511 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (database_id) (\n  avg_over_time(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_postgresql_transaction_count{database_id=~\".+:registry-db.+\", environment=\"$environment\"}[$__interval])\n)\n",
     "legendFormat": "{{ database_id }}"
    }
   ]
  }
 ]
}