{
 "title": "Registry",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(up{job=\"registry\"}, env)"
   },
   {
    "name": "handler",
    "query": "label_values(registry_http_requests_total{env=\"$env\"}, handler)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (\n  rate(registry_http_requests_total{env=\"$env\",handler=~\"$handler\"}[$__interval])\n)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$env\",handler=~\"$handler\"}[$__interval])\n) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (\n  rate(registry_http_requests_total{env=\"$env\"}[$__interval])\n)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{env=\"$env\",type=\"Hit\"}[$__interval])) / sum(rate(registry_storage_cache_total{env=\"$env\",type=\"Request\"}[$__interval]))",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Cache Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_storage_cache_total{env=\"$env\",type=\"Request\"}[$__interval]))",
     "legendFormat": "Requests"
    }
   ]
  }
 ]
}