{
 "title": "registry: Storage Info",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/1420324780 at Tue Jul 13 13:05:55 UTC 2021",
 "tags": [
  "managed",
  "registry",
  "container registry",
  "docker",
  "registry"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   { "name": "Deployment", "query": "gitlab-registry," }
  ]
 },
 "panels": [
  { "title": "GCS Bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Size",
   "type": "graph",
   "description": "Total size of objects per bucket. Values are measured once per day.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "stackdriver_gcs_bucket_storage_googleapis_com_storage_total_bytes{bucket_name=~\"gitlab-.*-registry\", environment=\"$environment\"}",
     "legendFormat": "{{ bucket_name }}"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "graph",
   "description": "Total number of objects per bucket, grouped by storage class. Values are measured once per day.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage_class) (stackdriver_gcs_bucket_storage_googleapis_com_storage_object_count{bucket_name=~\"gitlab-.*-registry\", environment=\"$environment\"})",
     "legendFormat": "{{ storage_class }}"
    }
   ]
  },
  {
   "title": "Daily Throughput",
   "type": "graph",
   "description": "Total daily storage in byte*seconds used by the bucket, grouped by storage class.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (storage_class) (stackdriver_gcs_bucket_storage_googleapis_com_storage_total_byte_seconds{bucket_name=~\"gitlab-.*-registry\", environment=\"$environment\"})",
     "legendFormat": "{{ storage_class }}"
    }
   ]
  }
 ]
}