{
 "title": "registry: registry: Migration Detail - temp",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/2216159324 at Thu Mar 17 12:56:01 UTC 2022",
 "tags": [
  "unmanaged",
  "registry"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(gitlab_service_ops:rate, environment)"
    }
   },
   { "name": "stage", "query": "main,cny," },
   { "name": "migration_path", "label": "migration_path", "query": "old,new" }
  ]
 },
 "panels": [
  { "title": "General Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top-level namespaces",
   "type": "graph",
   "description": "Number of top-level namespaces registered in the metadata database.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"registry_top_level_namespaces\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "graph",
   "description": "Number of repositories registered in the metadata database. Not available in production.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"registry_repositories\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Manifests",
   "type": "graph",
   "description": "Number of manifests registered in the metadata database. Not available in production.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"registry_manifests\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Blobs",
   "type": "graph",
   "description": "Number of blobs registered in the metadata database. Not available in production.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (gitlab_database_rows{query_name=\"registry_blobs\", environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "Traffic Split",
   "type": "timeseries",
   "description": "Percentage of requests handled by old and new code paths.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(registry_http_requests_total{environment=\"$environment\", stage=\"$stage\", migration_path=\"new\"}[$__interval]))\n/\nsum (rate(registry_http_requests_total{environment=\"$environment\", stage=\"$stage\", migration_path=~\"new|old\"}[$__interval]))",
     "legendFormat": "New"
    },
    {
     "expr": "sum (rate(registry_http_requests_total{environment=\"$environment\", stage=\"$stage\", migration_path=\"old\"}[$__interval]))\n/\nsum (rate(registry_http_requests_total{environment=\"$environment\", stage=\"$stage\", migration_path=~\"new|old\"}[$__interval]))",
     "legendFormat": "Old"
    }
   ]
  },
  {
   "title": "🔬 server Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Estimated p90 server Latency - Overall",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
     "legendFormat": "p90 overall {{migration_path}}"
    }
   ]
  },
  {
   "title": "server Errors - Overall",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum by () (\n  rate(registry_http_requests_total{code=~\"5..\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "overall {{migration_path}}"
    }
   ]
  },
  {
   "title": "server RPS - Overall",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by () (\n  rate(registry_http_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "overall {{migration_path}}"
    }
   ]
  },
  {
   "title": "Estimated p90 server Latency - per route",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (route,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
     "legendFormat": "p90 {{migration_path}} {{route}}"
    }
   ]
  },
  {
   "title": "Apdex attribution for server Latency - per route",
   "type": "graph",
   "description": "Attributes apdex downscoring",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max((\n  sum by (route) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (route) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"2.5\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n  +\n  sum by (route) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"25\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(route) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
     "legendFormat": "{{migration_path}} {{route}}"
    }
   ]
  },
  {
   "title": "server Errors - per route",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum by (route) (\n  rate(registry_http_requests_total{code=~\"5..\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "{{migration_path}} {{route}}"
    }
   ]
  },
  {
   "title": "server RPS - per route",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (route) (\n  rate(registry_http_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "{{migration_path}} {{route}}"
    }
   ]
  },
  {
   "title": "Estimated p90 server Latency - per method",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (method,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
     "legendFormat": "p90 {{migration_path}} {{method}}"
    }
   ]
  },
  {
   "title": "Apdex attribution for server Latency - per method",
   "type": "graph",
   "description": "Attributes apdex downscoring",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max((\n  sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"2.5\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"25\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(method) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
     "legendFormat": "{{migration_path}} {{method}}"
    }
   ]
  },
  {
   "title": "server Errors - per method",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (\n  rate(registry_http_requests_total{code=~\"5..\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "{{migration_path}} {{method}}"
    }
   ]
  },
  {
   "title": "server RPS - per method",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (\n  rate(registry_http_requests_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
     "legendFormat": "{{migration_path}} {{method}}"
    }
   ]
  },
  {
   "title": "🔬 server_route_manifest_reads Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "panels": [
    {
     "title": "Estimated p90 server_route_manifest_reads Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_reads RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "Estimated p90 server_route_manifest_reads Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (method,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{migration_path}} {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_manifest_reads Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"0.5\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"1\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(method) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{migration_path}} {{method}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_reads RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "{{migration_path}} {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 server_route_manifest_writes Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 server_route_manifest_writes Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_writes RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "Estimated p90 server_route_manifest_writes Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (method,le) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{migration_path}} {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_manifest_writes Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n  -\n  (\n    (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"10\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"25\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n/\n2\n\n  )\n)\n/ ignoring(method) group_left()\n(\n  sum by () (\n  rate(registry_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",le=\"+Inf\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",type=\"registry\",migration_path=~\"$migration_path\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{migration_path}} {{method}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_writes RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{env=\"$environment\",environment=\"$environment\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "{{migration_path}} {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 storage Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p90 storage Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "storage RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_storage_action_seconds_count{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "overall {{migration_path}}"
      }
     ]
    },
    {
     "title": "Estimated p90 storage Latency - per action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.900000,\n  sum by (action,le) (\n    rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p90 {{migration_path}} {{action}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for storage Latency - per action",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  sum by (action) (\n  rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\", le=\"+Inf\"}[$__interval])\n)\n\n  -\n  (\n    sum by (action) (\n  rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\", le=\"1\"}[$__interval])\n)\n\n  )\n)\n/ ignoring(action) group_left()\n(\n  sum by () (\n  rate(registry_storage_action_seconds_bucket{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\", le=\"+Inf\"}[$__interval])\n)\n\n)\n\n,1),0)\n",
       "legendFormat": "{{migration_path}} {{action}}"
      }
     ]
    },
    {
     "title": "storage RPS - per action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (action) (\n  rate(registry_storage_action_seconds_count{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",migration_path=~\"$migration_path\"}[$__interval])\n)\n",
       "legendFormat": "{{migration_path}} {{action}}"
      }
     ]
    }
   ]
  }
 ]
}