{
 "title": "registry: Storage Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4837524698 at Wed Aug  9 22:19:34 UTC 2023",
 "tags": [
  "managed",
  "registry",
  "container registry",
  "docker",
  "registry",
  "type:registry"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   { "name": "Deployment", "query": "gitlab-registry," },
   {
    "name": "cluster",
    "query": "label_values(registry_storage_action_seconds_count{environment=\"$environment\"}, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "GCS Bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Total Size",
   "type": "graph",
   "description": "Total size of objects per bucket. Values are measured once per day.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "stackdriver_gcs_bucket_storage_googleapis_com_storage_total_bytes{bucket_name=~\"gitlab-.*-registry\", environment=\"$environment\"}",
     "legendFormat": "{{ bucket_name }}"
    }
   ]
  },
  {
   "title": "Object Count",
   "type": "graph",
   "description": "Total number of objects per bucket, grouped by storage class. Values are measured once per day.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (storage_class) (stackdriver_gcs_bucket_storage_googleapis_com_storage_object_count{bucket_name=~\"gitlab-.*-registry\", environment=\"$environment\"})",
     "legendFormat": "{{ storage_class }}"
    }
   ]
  },
  {
   "title": "Daily Throughput",
   "type": "graph",
   "description": "Total daily storage in byte*seconds used by the bucket, grouped by storage class.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (storage_class) (stackdriver_gcs_bucket_storage_googleapis_com_storage_total_byte_seconds{bucket_name=~\"gitlab-.*-registry\", environment=\"$environment\"})",
     "legendFormat": "{{ storage_class }}"
    }
   ]
  },
  {
   "title": "RPS (Overall)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_storage_action_seconds_count{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "RPS (Per Action)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (action) (\n  rate(registry_storage_action_seconds_count{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval])\n)\n",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Estimated p95 Latency (Overall)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1001 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_storage_action_seconds_bucket{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Estimated p95 Latency (Per Action)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.950000,\n  sum by (action,le) (\n    rate(registry_storage_action_seconds_bucket{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval])\n  )\n)\n",
     "legendFormat": "{{ action }}"
    }
   ]
  },
  {
   "title": "Rate Limited Requests Rate",
   "type": "graph",
   "description": "Rate of 429 Too Many Requests responses received from GCS",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1011 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(registry_storage_rate_limit_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))"
    }
   ]
  },
  { "title": "Cloud CDN Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Percentage of HTTP Requests CACHE HIT by response",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{cache_result=\"HIT\", environment=\"$environment\", forwarding_rule_name=~\".*registry-cdn.*\"}) by (response_code) / sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{environment=\"$environment\", forwarding_rule_name=~\".*registry-cdn.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "HTTP Requests CACHE HIT (bytes)",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_request_bytes_count{cache_result=\"HIT\", environment=\"$environment\", forwarding_rule_name=~\".*registry-cdn.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "Percentage of HTTP Requests CACHE MISS by response",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*registry-cdn.*\"}) by (response_code) / sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count{environment=\"$environment\", forwarding_rule_name=~\".*registry-cdn.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "HTTP Requests CACHE MISS (bytes)",
   "type": "graph",
   "description": "HTTP Requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2011 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_request_bytes_count{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*registry-cdn.*\"}) by (response_code)",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  { "title": "Cloud CDN Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "60th Percentile Latency CACHE HIT",
   "type": "graph",
   "description": "60th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.6,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"HIT\", environment=\"$environment\", forwarding_rule_name=~\".*registry-cdn.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "90th Percentile Latency CACHE HIT",
   "type": "graph",
   "description": "90th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"HIT\", environment=\"$environment\", forwarding_rule_name=~\".*registry-cdn.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "60th Percentile Latency CACHE MISS",
   "type": "graph",
   "description": "60th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.6,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*registry-cdn.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  {
   "title": "90th Percentile Latency CACHE MISS",
   "type": "graph",
   "description": "90th Percentile Latency CACHE MISS",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3011 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9,rate(stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_backend_latencies_bucket{cache_result=\"MISS\", environment=\"$environment\", forwarding_rule_name=~\".*registry-cdn.*\"}[10m]))",
     "legendFormat": "{{ response_code }}"
    }
   ]
  },
  { "title": "Cloud CDN Redirects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 } },
  {
   "title": "Percentage of Redirects to CDN",
   "type": "graph",
   "description": "The percentage of blob HEAD/GET requests redirected to Google Cloud CDN.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 4001 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum (rate(registry_storage_cdn_redirects_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", backend=\"cdn\"}[$__interval]))\n/\nsum (rate(registry_storage_cdn_redirects_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))\n,1),0)\n"
    }
   ]
  },
  {
   "title": "Number of Redirects (Per Backend)",
   "type": "graph",
   "description": "The number of blob HEAD/GET requests redirected to Google Cloud Storage or Google Cloud CDN.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 4001 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (backend) (rate(registry_storage_cdn_redirects_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Percentage of Redirects to CDN Skipped",
   "type": "graph",
   "description": "The percentage of blob HEAD/GET requests that were not redirected to Google Cloud CDN because of a given reason:\n  - `non_eligible`: This means that the request JWT token was not marked with the `cdn_redirect` flag by Rails. The number\n  of JWT tokens marked as such is currently controlled by the `container_registry_cdn_redirect` feature flag (percentage of time).\n\n  - `gcp`: This means that the request originates within GCP, and as such we redirected it to GCS and not CDN.\n",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 4001 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum (rate(registry_storage_cdn_redirects_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", bypass=\"true\"}[$__interval]))\n/\nsum (rate(registry_storage_cdn_redirects_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\"}[$__interval]))\n,1),0)\n"
    }
   ]
  },
  {
   "title": "Number of Redirects to CDN Skipped (Per Reason)",
   "type": "graph",
   "description": "The number of blob HEAD/GET requests that were not redirected to Google Cloud CDN because of a given reason:\n  - `non_eligible`: This means that the request JWT token was not marked with the `cdn_redirect` flag by Rails. The number\n  of JWT tokens marked as such is currently controlled by the `container_registry_cdn_redirect` feature flag (percentage of time).\n\n  - `gcp`: This means that the request originates within GCP, and as such we redirected it to GCS and not CDN.\n",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 4001 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (bypass_reason) (rate(registry_storage_cdn_redirects_total{environment=\"$environment\", cluster=~\"$cluster\", stage=\"$stage\", bypass=\"true\"}[$__interval]))",
     "legendFormat": "{{ bypass_reason }}"
    }
   ]
  }
 ]
}