{
 "title": "registry: Pod Info Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   {
    "name": "Node",
    "query": "query_result(count(count_over_time(kube_node_labels{environment=\"$environment\", cluster=\"$cluster\"}[1w])) by (label_kubernetes_io_hostname))"
   },
   { "name": "Deployment", "query": "gitlab-registry," }
  ]
 },
 "panels": [
  { "title": "Container Registry Version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Version",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=\"registry\", cluster=\"$cluster\"}) by (image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  {
   "title": "Active Replicaset",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_replicaset_spec_replicas{replicaset=~\"gitlab-registry-.*\", cluster=\"$cluster\"}) by (replicaset)",
     "legendFormat": "{{ replicaset }}"
    }
   ]
  },
  { "title": "Deployment Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Deployment Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", pod_name=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\", pod_name!=\"\"}) / sum (kube_node_status_allocatable_memory_bytes{env=~\"$environment\", node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", pod_name=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{env=~\"$environment\", kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(kube_deployment_status_replicas{env=~\"$environment\", deployment=~\".*$Deployment\"}) or vector(0)) - ((sum(kube_deployment_status_replicas_available{env=~\"$environment\", deployment=~\".*$Deployment\"}) or vector(0)))) / (sum(kube_deployment_status_replicas{env=~\"$environment\", deployment=~\".*$Deployment\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", pod_name=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\", pod_name!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory Total (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable_memory_bytes{env=~\"$environment\", node=~\"^$Node.*$\"})"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", pod_name=~\"^$Deployment.*$\", kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Total (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{env=~\"$environment\", kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{env=~\"$environment\", deployment=~\".*$Deployment\"})"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{env=~\"$environment\", deployment=~\".*$Deployment\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{env=~\"$environment\", image!=\"\", pod_name=~\"^$Deployment.*$\", node=~\"^$Node$\"}[1m])) by (pod_name,node)",
     "legendFormat": "real: {{ pod_name }}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{env=~\"$environment\", pod=~\"^$Deployment.*$\",node=~\"^$Node$\"}) by (pod,node)",
     "legendFormat": "rqst: {{ pod }}"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{env=~\"$environment\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\") * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{env=~\"$environment\", workload=\"gitlab-registry\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{env=~\"$environment\"} * on(namespace,pod) group_left(workload, workload_type) mixin_pod_workload{env=~\"$environment\", workload=\"gitlab-registry\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{env=~\"$environment\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\") * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", workload=\"gitlab-registry\"}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{env=~\"$environment\"} * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", workload=\"gitlab-registry\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{env=~\"$environment\", id!=\"/\",pod_name=~\"^$Deployment.*$\",node=~\"^$Node$\"}) by (pod_name)",
     "legendFormat": "real: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{env=~\"$environment\", container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\") * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", workload=\"gitlab-registry\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{env=~\"$environment\"} * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", workload=\"gitlab-registry\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{env=~\"$environment\", container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\") * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", workload=\"gitlab-registry\"}) by (pod) /sum(kube_pod_container_resource_requests_memory_bytes{env=~\"$environment\", } * on(pod) group_left(workload) mixin_pod_workload{env=~\"$environment\", workload=\"gitlab-registry\"}) by (pod)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{env=~\"$environment\", id!=\"/\",pod_name=~\"^$Deployment.*$\",node=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{env=~\"$environment\", id!=\"/\",pod_name=~\"^$Deployment.*$\",node=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}