{
 "title": "registry: Garbage Collection Detail 2",
 "description": "Uploaded by jpereira at Mon Oct  4 13:02:09 UTC 2021",
 "tags": [ "playground" ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   { "name": "Deployment", "query": "gitlab-registry," }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queued Tasks",
   "type": "stat",
   "description": "The most recent number of tasks queued for review.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(avg by (query_name) (last_over_time(gitlab_database_rows{query_name=~\"registry_gc_.*_review_queue\", environment=\"$environment\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "description": "The most recent number of tasks ready for review.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(avg by (query_name) (last_over_time(gitlab_database_rows{query_name=~\"registry_gc_.*_review_queue_overdue\", environment=\"$environment\"}[$__interval])))"
    }
   ]
  },
  {
   "title": "Recovered Storage Space",
   "type": "stat",
   "description": "The number of bytes recovered by online GC.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "total" ] } },
   "targets": [
    {
     "expr": "sum(increase(registry_gc_storage_deleted_bytes_total{environment=\"$environment\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Median Analysis Latency",
   "type": "stat",
   "description": "The aggregated P50 latency of the database queries used to determine if\na blob or manifest are eligible for deletion (dangling).\n",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\n  sum by (le) (\n    rate(registry_database_query_duration_seconds_bucket{name=~\"gc_.*_task_is_dangling\", environment=\"$environment\"}[$__interval])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Median Delete Latency (Database)",
   "type": "stat",
   "description": "The aggregated P50 latency of the database delete queries.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\n  sum by (le) (\n    rate(registry_gc_delete_duration_seconds_bucket{backend=\"database\", error=\"false\", environment=\"$environment\"}[$__interval])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Median Delete Latency (Storage)",
   "type": "stat",
   "description": "The aggregated P50 latency of the storage delete requests.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\n  sum by (le) (\n    rate(registry_gc_delete_duration_seconds_bucket{backend=\"storage\", error=\"false\", environment=\"$environment\"}[$__interval])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Successfull Runs",
   "type": "gauge",
   "description": "The percentage of online GC runs that completed without error.",
   "gridPos": { "h": 4, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(registry_gc_runs_total{error=\"false\", environment=\"$environment\"}[$__interval]))\n  /\n  sum(rate(registry_gc_runs_total{environment=\"$environment\"}[$__interval]))\n) * 100\n"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Queued Tasks",
   "type": "graph",
   "description": "The number of tasks queued for review.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg by (query_name) (gitlab_database_rows{query_name=~\"registry_gc_.*_review_queue\", environment=\"$environment\"})",
     "legendFormat": "{{ query_name }}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "graph",
   "description": "The number of tasks ready for review.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "avg by (query_name) (gitlab_database_rows{query_name=~\"registry_gc_.*_review_queue_overdue\", environment=\"$environment\"})",
     "legendFormat": "{{ query_name }}"
    }
   ]
  },
  {
   "title": "Postponed Tasks",
   "type": "graph",
   "description": "The number of tasks whose review was postponed due processing errors.\n",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (registry_gc_postpones_total{environment=\"$environment\"})",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Time Between Reviews",
   "type": "graph",
   "description": "The median time between task reviews. This is the workers' sleep duration\nbetween runs.\n",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum by (worker, le) (\n    rate(registry_gc_sleep_duration_seconds_bucket{environment=\"$environment\"}[$__interval])\n  )\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  { "title": "Run Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Aggregate",
   "type": "graph",
   "description": "The per-second rate of all online GC runs.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (rate(registry_gc_run_duration_seconds_count{environment=\"$environment\"}[$__interval]))",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Successful",
   "type": "graph",
   "description": "The per-second rate of successful online GC runs.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  rate(registry_gc_run_duration_seconds_count{error=\"false\", noop=\"false\", environment=\"$environment\"}[$__interval])\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "graph",
   "description": "The per-second rate of failed online GC runs.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  rate(registry_gc_run_duration_seconds_count{error=\"true\", noop=\"false\", environment=\"$environment\"}[$__interval])\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Noop",
   "type": "graph",
   "description": "The per-second rate of noop (no tasks available) online GC runs.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  rate(registry_gc_run_duration_seconds_count{error=\"false\", noop=\"true\", environment=\"$environment\"}[$__interval])\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  { "title": "Run Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "P90 Aggregate",
   "type": "graph",
   "description": "The estimated overal P90 latency of online GC runs.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (worker, le) (\n    rate(registry_gc_run_duration_seconds_bucket{environment=\"$environment\"}[$__interval])\n  )\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "P90 Successful",
   "type": "graph",
   "description": "The estimated P90 latency of successful online GC runs.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (worker, le) (\n    rate(registry_gc_run_duration_seconds_bucket{error=\"false\", noop=\"false\", environment=\"$environment\"}[$__interval])\n  )\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "P90 Failed",
   "type": "graph",
   "description": "The estimated P90 latency of failed online GC runs.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (worker, le) (\n    rate(registry_gc_run_duration_seconds_bucket{error=\"true\", noop=\"false\", environment=\"$environment\"}[$__interval])\n  )\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "P90 Noop",
   "type": "graph",
   "description": "The estimated P90 latency of noop (false positive) online GC runs.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (worker, le) (\n    rate(registry_gc_run_duration_seconds_bucket{error=\"false\", noop=\"true\", environment=\"$environment\"}[$__interval])\n  )\n)\n",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  { "title": "Delete Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Aggregate",
   "type": "graph",
   "description": "The per-second rate of all online GC deletions.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (backend) (\n  rate(registry_gc_delete_duration_seconds_count{environment=\"$environment\"}[$__interval])\n)\n",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Blobs",
   "type": "graph",
   "description": "The per-second rate of online GC blob deletions.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (backend) (\n  rate(registry_gc_delete_duration_seconds_count{artifact=\"blob\", environment=\"$environment\"}[$__interval])\n)\n",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Manifests",
   "type": "graph",
   "description": "The per-second rate of online GC manifest deletions.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (backend) (\n  rate(registry_gc_delete_duration_seconds_count{environment=\"$environment\", artifact=\"manifest\"}[$__interval])\n)\n",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  { "title": "Delete Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "P90 Aggregate",
   "type": "graph",
   "description": "The estimated overal P90 latency of online GC deletions.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (le) (\n    rate(registry_gc_delete_duration_seconds_bucket{environment=\"$environment\"}[$__interval])\n  )\n)\n"
    }
   ]
  },
  {
   "title": "P90 Blobs",
   "type": "graph",
   "description": "The estimated P90 latency of online GC blob deletions.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (backend, le) (\n    rate(registry_gc_delete_duration_seconds_bucket{artifact=\"blob\", environment=\"$environment\"}[$__interval])\n  )\n)\n",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "P90 Manifests",
   "type": "graph",
   "description": "The estimated P90 latency of online GC manifest deletions.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.900000,\n  sum by (backend, le) (\n    rate(registry_gc_delete_duration_seconds_bucket{artifact=\"manifest\", environment=\"$environment\"}[$__interval])\n  )\n)\n",
     "legendFormat": "{{ backend }}"
    }
   ]
  }
 ]
}