{
 "title": "Release Management",
 "tags": [ "delivery" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "🚀 gprd",
   "type": "singlestat",
   "description": "Rails revision on Production.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_replace(\n  topk(1, count(gitlab_version_info{environment=\"gprd\", stage=\"main\", component=\"gitlab-rails\", tier=\"sv\"}) by (version)),\n  \"version\", \"$1\",\n  \"version\", \"^([A-Fa-f0-9]{11}).*$\"\n)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🚀 gprd",
   "type": "singlestat",
   "description": "Package running on Production.",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, count(omnibus_build_info{environment=\"gprd\", stage=\"main\", tier=\"sv\"}) by (version))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Auto-deploy pressure",
   "type": "stat",
   "description": "The number of commits in `master` not yet deployed to each environment.",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delivery_auto_deploy_pressure{role!=\"\"}) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "New Sentry issues",
   "type": "stat",
   "description": "The number of new Sentry issues for each environment.",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delivery_sentry_issues) by (role)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "🐤 gprd-cny",
   "type": "singlestat",
   "description": "Rails revision on Canary.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "label_replace(\n  topk(1, count(gitlab_version_info{environment=\"gprd\", stage=\"cny\", component=\"gitlab-rails\", tier=\"sv\"}) by (version)),\n  \"version\", \"$1\",\n  \"version\", \"^([A-Fa-f0-9]{11}).*$\"\n)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🐤 gprd-cny",
   "type": "singlestat",
   "description": "Package running on Canary.",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, count(omnibus_build_info{environment=\"gprd\", stage=\"cny\", tier=\"sv\"}) by (version))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🏗 gstg",
   "type": "singlestat",
   "description": "Rails revision on Staging.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "label_replace(\n  topk(1, count(gitlab_version_info{environment=\"gstg\", stage=\"main\", component=\"gitlab-rails\", tier=\"sv\"}) by (version)),\n  \"version\", \"$1\",\n  \"version\", \"^([A-Fa-f0-9]{11}).*$\"\n)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "🏗 gstg",
   "type": "singlestat",
   "description": "Package running on Staging.",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, count(omnibus_build_info{environment=\"gstg\", tier=\"sv\"}) by (version))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Release pressure",
   "type": "gauge",
   "description": "Number of `Pick into` merge requests for previous releases",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delivery_release_pressure{state=\"merged\"}) by (state, version)",
     "legendFormat": "{{version}} ({{state}})"
    }
   ]
  },
  { "title": "🚀 gprd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "🚀 Auto-deploy pressure",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "Commits" }
   ],
   "targets": [
    {
     "expr": "delivery_auto_deploy_pressure{job=\"auto-deploy-pressure\", role=\"gprd\"}",
     "legendFormat": "Commits"
    }
   ]
  },
  {
   "title": "🚀 New Sentry issues",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Issues" }
   ],
   "targets": [
    {
     "expr": "delivery_sentry_issues{job=\"sentry-issues\", role=\"gprd\"}",
     "legendFormat": "Issues"
    }
   ]
  },
  {
   "title": "🐤 gprd-cny",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "🐤 Auto-deploy pressure",
     "type": "graph",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "Commits" }
     ],
     "targets": [
      {
       "expr": "delivery_auto_deploy_pressure{job=\"auto-deploy-pressure\", role=\"gprd-cny\"}",
       "legendFormat": "Commits"
      }
     ]
    },
    {
     "title": "🐤 New Sentry issues",
     "type": "graph",
     "gridPos": { "h": 12, "w": 10, "x": 10, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "Issues" }
     ],
     "targets": [
      {
       "expr": "delivery_sentry_issues{job=\"sentry-issues\", role=\"gprd-cny\"}",
       "legendFormat": "Issues"
      }
     ]
    }
   ]
  },
  {
   "title": "🏗 gstg",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "🏗 Auto-deploy pressure",
     "type": "graph",
     "gridPos": { "h": 12, "w": 10, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Commits" }
     ],
     "targets": [
      {
       "expr": "delivery_auto_deploy_pressure{job=\"auto-deploy-pressure\", role=\"gstg\"}",
       "legendFormat": "Commits"
      }
     ]
    }
   ]
  }
 ]
}