{
 "title": "rnaveiras - Prometheus Agents Fleet",
 "tags": [
  "unmanaged",
  "protected",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "env",
    "query": {
     "query": "label_values(prometheus_build_info,env)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(prometheus_build_info{env=\"$env\", service=\"gitlab-rw-prometheus\"},job)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(prometheus_build_info{env=\"$env\", job=\"$job\"},cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(prometheus_build_info{env=\"$env\", job=\"$job\", cluster=\"$cluster\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{env=\"$env\", job=\"kubelet\", namespace=\"monitoring\", pod=~\"prometheus-gitlab-monitoring-promethe-prometheus-.*\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of active series being tracked by the WAL storage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(prometheus_agent_active_series{env=\"$env\", job=\"$job\", cluster=~\"$cluster\", pod=~\"$pod\", container=\"prometheus\"}, \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Total number of samples appended to the storage ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(rate(prometheus_agent_samples_appended_total{env=\"$env\", job=\"$job\",  cluster=~\"$cluster\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Current WAL watcher segment",
   "type": "timeseries",
   "description": "shows the current WAL segment file that each remote write instance is currently reading from",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(prometheus_wal_watcher_current_segment{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}, \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Current WAL segment ",
   "type": "timeseries",
   "description": "is the WAL segment file that Prometheus is currently writing new data to",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(prometheus_tsdb_wal_segment_current{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}, \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Prometheus remote write is behind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\nmax_over_time(prometheus_remote_storage_highest_timestamp_in_seconds{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval])\n- ignoring(remote_name, url) group_right\nmax_over_time(prometheus_remote_storage_queue_highest_sent_timestamp_seconds{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Prometheus Remote Write Desired Shards vs Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(max_over_time(prometheus_remote_storage_shards_desired{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n\n              \n              ",
     "legendFormat": "Desired {{cluster}}/{{pod}}"
    },
    {
     "expr": "label_replace(max_over_time(prometheus_remote_storage_shards_max{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "Max {{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Total number of samples pending",
   "type": "timeseries",
   "description": "The number of samples pending in the queues shards to be sent to the remote storage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(max_over_time(prometheus_remote_storage_samples_pending{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Total number of samples sent to remote storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(rate(prometheus_remote_storage_samples_total{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Shard Capacity",
   "type": "timeseries",
   "description": "he capacity of each shard of the queue used for parallel sending to the remote storage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(max_over_time(prometheus_remote_storage_shard_capacity{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Remote Storage Samples failed",
   "type": "timeseries",
   "description": "Total number of samples which failed on send to remote storage, non-recoverable errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(rate(prometheus_remote_storage_samples_failed_total{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Max Samples per send",
   "type": "timeseries",
   "description": "The maximum number of samples to be sent, in a single request, to the remote storage. Note that, when sending of exemplars over remote write is enabled, exemplars count towards this limt.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(max_over_time(prometheus_remote_storage_max_samples_per_send{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Remote Storage Samples retried",
   "type": "timeseries",
   "description": "Total number of exemplars which failed on send to remote storage but were retried because the send error was recoverable.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(rate(prometheus_remote_storage_samples_retried_total{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Remote Storage Samples dropped",
   "type": "timeseries",
   "description": "Total number of samples which were dropped after being read from the WAL before being sent via remote write, either via relabelling, due to being too old or unintentionally because of an unknown reference ID",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(rate(prometheus_remote_storage_samples_dropped_total{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Total enqueue retries",
   "type": "timeseries",
   "description": "Total number of times enqueue has failed because a shards queue was full.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(rate(prometheus_remote_storage_enqueue_retries_total{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "WAL size",
   "type": "timeseries",
   "description": "Size of the write log directory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(prometheus_tsdb_wal_storage_size_bytes{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"},  \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes Total",
   "type": "timeseries",
   "description": "The total number of bytes of data (not metadata) sent by the queue after compression. Note that when exemplars over remote write is enabled the exemplars included in a remote write request count towards this metric.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(rate(prometheus_remote_storage_bytes_total{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval]), \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "prometheus_tsdb_data_replay_duration_seconds",
   "type": "timeseries",
   "description": "Time take to replay the data on disk",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(prometheus_tsdb_data_replay_duration_seconds{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"},  \"pod\", \"$1\", \"pod\", \".*(prometheus.*[0-9])\")\n              \n              ",
     "legendFormat": "{{cluster}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Retrieval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Targets by scrape",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name, config) (prometheus_sd_discovered_targets{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "{{scrape}}"
      }
     ]
    },
    {
     "title": "Average Scrape Interval Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_sum{env=\"$env\", cluster=~\"$cluster\", container=\"prometheus\",  pod=~\"$pod\", job=\"$job\"}[$__rate_interval])\n\n/ \nrate(prometheus_target_interval_length_seconds_count{env=\"$env\", cluster=~\"$cluster\", container=\"prometheus\", pod=~\"$pod\",  job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{pod}} / {{interval}}"
      }
     ]
    },
    {
     "title": "Total number of target sync failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, sum by(scrape_job) (rate(prometheus_target_sync_failed_total{env=\"$env\", cluster=~\"$cluster\", container=\"prometheus\",  pod=~\"$pod\", job=\"$job\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scrape failures by Reason",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (cluster) (rate(prometheus_target_scrapes_exceeded_body_size_limit_total{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))   ",
       "legendFormat": "exceeded body size limit: {{cluster}}"
      },
      {
       "expr": "sum by () (rate(prometheus_target_scrapes_exceeded_sample_limit_total{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "exceeded sample limit: {{cluster}}"
      },
      {
       "expr": "sum by (cluster) (rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{env=\"$env\", cluster=~\"$cluster\", job=\"$job\",  pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "duplicate timestamp: {{cluster}}"
      },
      {
       "expr": "sum by (cluster) (rate(prometheus_target_scrapes_sample_out_of_bounds_total{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "out of bounds: {{cluster}}"
      },
      {
       "expr": "sum by (cluster) (rate(prometheus_target_scrapes_sample_out_of_order_total{env=\"$env\", cluster=~\"$cluster\", job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "out of order: {{cluster}}"
      }
     ]
    },
    {
     "title": "rate API http requests by code and handler",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_http_requests_total{env=\"$env\", cluster=~\"$cluster\", container=\"prometheus\", pod=~\"$pod\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{pod}} / {{code}}  - {{ handler }}"
      }
     ]
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{env=\"$env\", cluster=~\"$cluster\", job=\"kubelet\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])",
     "legendFormat": "{{container}}/{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=\"$env\", cluster=~\"$cluster\", job=\"kube-state-metrics\", namespace=\"monitoring\", unit=\"core\", resource=\"cpu\", pod=~\"$pod\", container=~\"$container\"}\n",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=\"$env\", cluster=~\"$cluster\", job=\"kube-state-metrics\", namespace=\"monitoring\", pod=~\"$pod\", unit=\"core\", resource=\"cpu\", container=~\"$container\", unit=\"core\"}",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{env=\"$env\", cluster=~\"$cluster\", job=\"kubelet\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{container}}/{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=\"$env\", cluster=~\"$cluster\", job=\"kube-state-metrics\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=\"$env\", cluster=~\"$cluster\", job=\"kube-state-metrics\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Persistent Volume % Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "\nkubelet_volume_stats_used_bytes{job=\"kubelet\", env=\"$env\", cluster=~\"$cluster\", namespace=\"monitoring\", persistentvolumeclaim=~\".*$job.*\"}\n/ kubelet_volume_stats_capacity_bytes{job=\"kubelet\", env=\"$env\", cluster=~\"$cluster\", namespace=\"monitoring\", persistentvolumeclaim=~\".*$job.*\"}",
     "legendFormat": "{{cluster}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Prometheus Ready",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_ready{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (cluster,container) (increase(container_cpu_cfs_throttled_periods_total{env=\"$env\", cluster=~\"$cluster\", job=\"kubelet\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))\n/\n\nsum by (cluster, container) (increase(container_cpu_cfs_periods_total{env=\"$env\", cluster=~\"$cluster\", job=\"kubelet\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}