{
 "title": "rnaveiras - Prometheus",
 "tags": [
  "unmanaged",
  "protected"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "env",
    "query": {
     "query": "label_values(prometheus_build_info,env)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(prometheus_build_info{env=\"$env\"},cluster)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(prometheus_build_info{env=\"$env\", cluster=\"$cluster\"},job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(prometheus_build_info{env=\"$env\", cluster=\"$cluster\", job=\"$job\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{env=\"$env\", cluster=\"$cluster\", job=\"kubelet\", namespace=\"monitoring\", pod=~\"prometheus-gitlab-monitoring-promethe-prometheus-.*\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Headlines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total active time series",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(prometheus_tsdb_head_series{env=\"$env\", cluster=\"$cluster\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingestion rate",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{env=\"$env\", cluster=\"$cluster\"}[$__rate_interval])) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Capacity",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubelet_volume_stats_capacity_bytes{env=\"$env\", cluster=\"$cluster\", persistentvolumeclaim=~\".*prometheus.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average storage utilisation",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((100 - ((kubelet_volume_stats_available_bytes{env=\"$env\", cluster=\"$cluster\", persistentvolumeclaim=~\".*prometheus-.*\"} * 100) / kubelet_volume_stats_capacity_bytes{env=\"$env\", cluster=\"$cluster\", persistentvolumeclaim=~\".*prometheus-.*\"} )))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version Matrix",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (env, cluster, version) (prometheus_build_info{env=\"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{env=\"$env\", cluster=\"$cluster\", job=\"kubelet\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])",
     "legendFormat": "{{container}}/{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=\"$env\", cluster=\"$cluster\", job=\"kube-state-metrics\", namespace=\"monitoring\", unit=\"core\", resource=\"cpu\", pod=~\"$pod\", container=~\"$container\"}\n",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=\"$env\", cluster=\"$cluster\", job=\"kube-state-metrics\", namespace=\"monitoring\", pod=~\"$pod\", unit=\"core\", resource=\"cpu\", container=~\"$container\", unit=\"core\"}",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{env=\"$env\", cluster=\"$cluster\", job=\"kubelet\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{container}}/{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=\"$env\", cluster=\"$cluster\", job=\"kube-state-metrics\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=\"$env\", cluster=\"$cluster\", job=\"kube-state-metrics\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\", resource=\"memory\", unit=\"byte\"}\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (container) (increase(container_cpu_cfs_throttled_periods_total{env=\"$env\", cluster=\"$cluster\", job=\"kubelet\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))\n/\n\nsum by (container) (increase(container_cpu_cfs_periods_total{env=\"$env\", cluster=\"$cluster\", job=\"kubelet\", namespace=\"monitoring\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Active time series  ",
   "type": "timeseries",
   "description": "A time series is considered active if Prometheus scraped new data for it recently. Prometheus provides prometheus_tsdb_head_series metric, which shows the number of active time series. \n\nPrometheus holds recently added samples for active time series in RAM, so its RAM usage highly depends on the number of active time series.  \n\nThe number of active time series is connected to cardinality via churn rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TSDB Compactions Failed / Skipped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compactions_failed_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[2h])",
     "legendFormat": "Failed {{pod}}"
    },
    {
     "expr": "rate(prometheus_tsdb_compactions_skipped_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[2h])",
     "legendFormat": "Skipped {{pod}}"
    }
   ]
  },
  {
   "title": "WAL - Time taken to replay the data on disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_data_replay_duration_seconds{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average byte size of each sample ingested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[1d]))\n/\nsum by (pod) (rate(prometheus_tsdb_compaction_chunk_samples_sum{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[1d]))\n",
     "legendFormat": "Failed {{pod}}"
    }
   ]
  },
  {
   "title": "WAL Corruptions Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_wal_corruptions_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Agent:  Number of active series being tracked by the WAL storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_agent_active_series{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WAL MMap Chunk corruptions",
   "type": "timeseries",
   "description": "Total number of memory-mapped chunk corruptions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_mmap_chunk_corruptions_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Agent:  Total number of samples appended to the storage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_agent_samples_appended_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WAL - Total number snapshot replays that failed",
   "type": "timeseries",
   "description": "Total number snapshot replays that failed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_snapshot_replay_error_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\", container=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Retrieval", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Samples ingest/s",
   "type": "timeseries",
   "description": "prometheus_tsdb_head_samples_appended_total\nThe rate of this metric indicates the ingestion rate of every instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{env=\"$env\", cluster=\"$cluster\", container=\"prometheus\", job=\"$job\", pod=~\"$pod\", exported_type=\"float\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Scrape Interval Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_sum{env=\"$env\", cluster=\"$cluster\", container=\"prometheus\",  pod=~\"$pod\", job=\"$job\"}[$__rate_interval])\n\n/ \nrate(prometheus_target_interval_length_seconds_count{env=\"$env\", cluster=\"$cluster\", container=\"prometheus\", pod=~\"$pod\",  job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{pod}} / {{interval}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (prometheus_sd_discovered_targets{env=\"$env\", cluster=\"$cluster\", container=\"prometheus\", pod=~\"$pod\", job=\"gitlab-monitoring-promethe-prometheus\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scrape failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by () (prometheus_target_scrapes_exceeded_body_size_limit_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "exceeded body size limit: {{job}}"
    },
    {
     "expr": "sum by () (prometheus_target_scrapes_exceeded_sample_limit_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "exceeded sample limit: {{job}}"
    },
    {
     "expr": "sum by () (prometheus_target_scrapes_sample_duplicate_timestamp_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\",  pod=~\"$pod\"})",
     "legendFormat": "duplicate timestamp: {{job}}"
    },
    {
     "expr": "sum by () (prometheus_target_scrapes_sample_out_of_bounds_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "out of bounds: {{job}}"
    },
    {
     "expr": "sum by () (prometheus_target_scrapes_sample_out_of_order_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "out of order: {{job}}"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{env=\"$env\", cluster=\"$cluster\", container=\"prometheus\", pod=~\"$pod\", job=\"$job\", quantile=\"0.99\"}",
     "legendFormat": "{{pod}} / {{slice}}"
    }
   ]
  },
  {
   "title": "Query Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(prometheus_engine_queries{env=\"$env\", cluster=\"$cluster\", container=\"prometheus\",  pod=~\"$pod\", job=\"$job\"}[5m]) / max_over_time(prometheus_engine_queries_concurrent_max{env=\"$env\", cluster=\"$cluster\", container=\"prometheus\",  pod=~\"$pod\", job=\"$job\"}[5m])",
     "legendFormat": "{{pod}} / {{slice}}"
    }
   ]
  },
  { "title": "K8s", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Pod Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\n\nincrease(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\", env=\"$env\", cluster=\"$cluster\", namespace=\"monitoring\", pod=~\"$pod\", container=\"$container\"}[$__rate_interval])\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Container Status Last Terminated Reason",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum_over_time by (reason) (kube_pod_container_status_last_terminated_reason{job=\"kube-state-metrics\", env=\"$env\", cluster=\"$cluster\", namespace=\"monitoring\", container=\"$container\", pod=~\"$pod\"}[$__rate_interval])\n",
     "legendFormat": "{{pod}} / {{reason}}"
    }
   ]
  },
  {
   "title": "Container OOM Events Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(container_oom_events_total{job=\"kubelet\", env=\"$env\", cluster=\"$cluster\", namespace=\"monitoring\", pod=~\"$pod\", container=\"$container\"}[$__rate_interval])\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Rules evaluation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Rule evaluation failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (rule_group) (rate(prometheus_rule_evaluation_failures_total{env=\"$env\", cluster=\"$cluster\", job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{rule_group}}"
    }
   ]
  }
 ]
}