{
 "title": "rnaveiras - thanos memory usage",
 "tags": [
  "protected",
  "unmanaged",
  "thanos"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "thanos-gprd-storegateway-.*", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{env=\"ops\", cluster=\"ops-gitlab-gke\", namespace=\"thanos\", container=\"storegateway\",pod=~\"thanos-gprd-storegateway-.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=\"ops\", cluster=\"ops-gitlab-gke\", namespace=\"thanos\", container=\"storegateway\",pod=~\"thanos-gprd-storegateway-.*\", unit=\"core\", resource=\"cpu\"}\n",
     "legendFormat": "Request"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=\"ops\", cluster=\"ops-gitlab-gke\", namespace=\"thanos\", container=\"storegateway\",pod=~\"thanos-gprd-storegateway-.*\", unit=\"core\", resource=\"cpu\"}\n",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{env=\"ops\", cluster=\"ops-gitlab-gke\", namespace=\"thanos\", container=\"storegateway\",pod=~\"thanos-gprd-storegateway-.*\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=\"ops\", cluster=\"ops-gitlab-gke\", job=\"kube-state-metrics\", namespace=\"thanos\", pod=~\"thanos-gprd-storegateway-.*\", container=\"storegateway\", resource=\"memory\", unit=\"byte\"}\n",
     "legendFormat": "Memory Request"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=\"ops\", cluster=\"ops-gitlab-gke\", job=\"kube-state-metrics\", namespace=\"thanos\", pod=~\"thanos-gprd-storegateway-.*\", container=\"storegateway\", resource=\"memory\", unit=\"byte\"}\n",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  { "title": "thanos-query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{env=\"ops\", cluster=\"ops-gitlab-gke\", namespace=\"thanos\", container=\"query\", pod=~\"thanos-query-.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=\"ops\", cluster=\"ops-gitlab-gke\", namespace=\"thanos\", container=\"query\", pod=~\"thanos-query-.*\", unit=\"core\", resource=\"cpu\"}\n",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=\"ops\", cluster=\"ops-gitlab-gke\", namespace=\"thanos\", container=\"query\", pod=~\"thanos-query-.*\", unit=\"core\", resource=\"cpu\"}\n",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{env=\"ops\", cluster=\"ops-gitlab-gke\", namespace=\"thanos\", container=\"query\", pod=~\"thanos-query-.*\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{env=\"ops\", cluster=\"ops-gitlab-gke\", job=\"kube-state-metrics\", namespace=\"thanos\", container=\"query\", pod=~\"thanos-query-.*\", resource=\"memory\", unit=\"byte\"}\n",
     "legendFormat": "Memory request"
    },
    {
     "expr": "kube_pod_container_resource_limits{env=\"ops\", cluster=\"ops-gitlab-gke\", job=\"kube-state-metrics\", namespace=\"thanos\", container=\"query\", pod=~\"thanos-query-.*\", resource=\"memory\", unit=\"byte\"}\n",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "Active time series",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{env=\"ops\", cluster=\"ops-gitlab-gke\", namespace=\"thanos\", pod=~\"receive-gitlab-thanos-receive-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}