{
 "title": "rpereira2 - Auto deploy environment states",
 "tags": [
  "unmanaged",
  "protected"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Environment state legend",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "- Ready - The environment is idle and ready to accept a new deployment.\n- locked - There is an ongoing operation on the environment. Either a deployment, or a post-deploy migration.\n- awaiting_promotion - The environment is idle, and there is a package available for promotion. This only applies to gstg or gprd.\n- baking_time - A deployment just completed and the package is now considered to be \"baking\" on the environment. Baking usually lasts for 30 mins. This only applies to gprd-cny."
   }
  },
  {
   "title": "Lock state legend",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "- locked_deployment - There is an ongoing deployment to the environment.\n- locked_deployment_failed - The last deployment to the environment failed.\n- locked_qa - A QA pipeline is running against this environment.\n- locked_qa_failed - The last QA pipeline on the environment failed.\n- locked_post_deploy_migration - Post deploy migrations are being executed on this environment.\n- locked_post_deploy_migration_failed - Post deploy migrations on the environment has failed.\n"
   }
  },
  {
   "title": "Auto deploy packages",
   "type": "table",
   "description": "Displays the last 10 auto deploy packages and their statuses",
   "gridPos": { "h": 13, "w": 22, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "last_over_time(delivery_auto_deploy_package_state[$__range]) >= 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(delivery_deployment_completed[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current environment state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "gstg-cny environment state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delivery_auto_deploy_environment_state{target_env=\"gstg\", target_stage=\"cny\"} >= 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gstg-cny lock reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delivery_auto_deploy_lock_state{target_env=\"gstg\", target_stage=\"cny\"} >= 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gprd-cny environment state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delivery_auto_deploy_environment_state{target_env=\"gprd\", target_stage=\"cny\"} >= 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gprd-cny lock reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delivery_auto_deploy_lock_state{target_env=\"gprd\", target_stage=\"cny\"} >= 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gstg environment state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delivery_auto_deploy_environment_state{target_env=\"gstg\", target_stage=\"main\"} >= 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gstg lock reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delivery_auto_deploy_lock_state{target_env=\"gstg\", target_stage=\"main\"} >= 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gprd environment state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delivery_auto_deploy_environment_state{target_env=\"gprd\", target_stage=\"main\"} >= 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gprd lock reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delivery_auto_deploy_lock_state{target_env=\"gprd\", target_stage=\"main\"} >= 1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Important environment states", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Production awaiting promotion",
   "type": "stat",
   "description": "Percentage of time of the selected time range that production is ready to accept a new deployment, and there is a package available for promotion.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gprd\", target_stage=\"main\",env_state=\"awaiting_promotion\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Staging awaiting promotion",
   "type": "stat",
   "description": "Percentage of time of the selected time range that staging is ready to accept a new deployment, and there is a package available for promotion.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gstg\", target_stage=\"main\",env_state=\"awaiting_promotion\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prod Awaiting Promotion bars",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gprd\", target_stage=\"main\",env_state=\"awaiting_promotion\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Production canary baking time",
   "type": "stat",
   "description": "Percentage of time in the selected time range that production canary is baking a package.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gprd\", target_stage=\"cny\",env_state=\"baking_time\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Staging canary ready to accept new packages",
   "type": "stat",
   "description": "Percentage of time of the selected time range where staging-canary was idle and ready to accept a new deployment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gstg\", target_stage=\"cny\",env_state=\"ready\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Staging canary ready to accept new packages",
   "type": "stat",
   "description": "Percentage of time of the selected time range where production-canary was idle and ready to accept a new deployment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without (pod,instance) (delivery_auto_deploy_environment_state{target_env=\"gprd\", target_stage=\"cny\",env_state=\"ready\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}