{
 "title": "runway: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5985287050 at Mon Jan 22 22:41:10 UTC 2024",
 "tags": [
  "managed",
  "runway",
  "gitlab",
  "type:runway",
  "runway",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"runway\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{env=\"$environment\",environment=\"$environment\",type=\"runway\"}\n        /\n        process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"runway\"}\n      )\n      or\n      (\n        ruby_file_descriptors{env=\"$environment\",environment=\"$environment\",type=\"runway\"}\n        /\n        ruby_process_max_fds{env=\"$environment\",environment=\"$environment\",type=\"runway\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",type=\"runway\", component=\"open_fds\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",type=\"runway\", component=\"open_fds\"}\n)\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",type=\"runway\", component=\"open_fds\"}\n)\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-queues-meta\n  redis-cluster-ratelimiting\n  redis-cluster-shared-state\n  redis-pubsub\n  redis-repository-cache\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  runway\n  search\n  vault\nend\n\nsubgraph runners\n  ci-runners\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\n  praefect\nend\n\nsubgraph sv\n  api\n  consul\n  kas\n  pvs\nend\n\n\n  api --> consul\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> praefect\napi --> pvs\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-queues-meta\napi --> redis-cluster-ratelimiting\napi --> redis-cluster-shared-state\napi --> redis-pubsub\napi --> redis-repository-cache\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\nci-runners --> api\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> praefect\nkas --> redis\npgbouncer --> patroni\npraefect --> cloud-sql\npraefect --> gitaly\nrunway --> ci-runners\nrunway --> vault\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-queues-meta\n  redis-cluster-ratelimiting\n  redis-cluster-shared-state\n  redis-pubsub\n  redis-repository-cache\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  runway\n  search\n  vault\nend\n\nsubgraph runners\n  ci-runners\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\n  praefect\nend\n\nsubgraph sv\n  api\n  consul\n  kas\n  pvs\nend\n\n\n  api --> consul\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> praefect\napi --> pvs\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-queues-meta\napi --> redis-cluster-ratelimiting\napi --> redis-cluster-shared-state\napi --> redis-pubsub\napi --> redis-repository-cache\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\nci-runners --> api\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> praefect\nkas --> redis\npgbouncer --> patroni\npraefect --> cloud-sql\npraefect --> gitaly\nrunway --> ci-runners\nrunway --> vault\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql[\"cloud-sql (Level 1)\"]\n  patroni[\"patroni (Level 2)\"]\n  pgbouncer[\"pgbouncer (Level 1)\"]\n  redis-cluster-cache[\"redis-cluster-cache (Level 2)\"]\n  redis-cluster-chat-cache[\"redis-cluster-chat-cache (Level 2)\"]\n  redis-cluster-feature-flag[\"redis-cluster-feature-flag (Level 2)\"]\n  redis-cluster-queues-meta[\"redis-cluster-queues-meta (Level 2)\"]\n  redis-cluster-ratelimiting[\"redis-cluster-ratelimiting (Level 2)\"]\n  redis-cluster-shared-state[\"redis-cluster-shared-state (Level 2)\"]\n  redis-pubsub[\"redis-pubsub (Level 2)\"]\n  redis-repository-cache[\"redis-repository-cache (Level 2)\"]\n  redis-sessions[\"redis-sessions (Level 3)\"]\n  redis-sidekiq[\"redis-sidekiq (Level 3)\"]\n  redis-tracechunks[\"redis-tracechunks (Level 3)\"]\n  redis[\"redis (Level 3)\"]\nend\n\nsubgraph inf\n  runway[\"runway (Level 1)\"]\n  search[\"search (Level 1)\"]\n  vault[\"vault (Level 2)\"]\nend\n\nsubgraph runners\n  ci-runners[\"ci-runners (Level 2)\"]\nend\n\nsubgraph stor\n  gitaly[\"gitaly (Level 3)\"]\n  google-cloud-storage[\"google-cloud-storage (Level 2)\"]\n  praefect[\"praefect (Level 2)\"]\nend\n\nsubgraph sv\n  api[\"api (Level 2)\"]\n  consul[\"consul (Level 1)\"]\n  kas[\"kas (Level 3)\"]\n  pvs[\"pvs (Level 3)\"]\nend\n\n\n  api[\"api (Level 2)\"] --> consul\napi[\"api (Level 2)\"] --> gitaly\napi[\"api (Level 2)\"] --> google-cloud-storage\napi[\"api (Level 2)\"] --> kas\napi[\"api (Level 2)\"] --> patroni\napi[\"api (Level 2)\"] --> pgbouncer\napi[\"api (Level 2)\"] --> praefect\napi[\"api (Level 2)\"] --> pvs\napi[\"api (Level 2)\"] --> redis\napi[\"api (Level 2)\"] --> redis-cluster-cache\napi[\"api (Level 2)\"] --> redis-cluster-chat-cache\napi[\"api (Level 2)\"] --> redis-cluster-feature-flag\napi[\"api (Level 2)\"] --> redis-cluster-queues-meta\napi[\"api (Level 2)\"] --> redis-cluster-ratelimiting\napi[\"api (Level 2)\"] --> redis-cluster-shared-state\napi[\"api (Level 2)\"] --> redis-pubsub\napi[\"api (Level 2)\"] --> redis-repository-cache\napi[\"api (Level 2)\"] --> redis-sessions\napi[\"api (Level 2)\"] --> redis-sidekiq\napi[\"api (Level 2)\"] --> redis-tracechunks\napi[\"api (Level 2)\"] --> search\nci-runners[\"ci-runners (Level 2)\"] --> api\ngitaly[\"gitaly (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> api\nkas[\"kas (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> kas\nkas[\"kas (Level 3)\"] --> praefect\nkas[\"kas (Level 3)\"] --> redis\npgbouncer[\"pgbouncer (Level 1)\"] --> patroni\npraefect[\"praefect (Level 2)\"] --> cloud-sql\npraefect[\"praefect (Level 2)\"] --> gitaly\nrunway[\"runway (Level 1)\"] --> ci-runners\nrunway[\"runway (Level 1)\"] --> vault\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}