{
 "title": "runway: Runway Job Metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7851888781 at Wed Sep 18 05:14:13 UTC 2024",
 "tags": [
  "managed",
  "runway",
  "runway",
  "type:runway"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   },
   {
    "name": "type",
    "label": "job",
    "query": "label_values(stackdriver_cloud_run_job_run_googleapis_com_job_running_task_attempts{job=\"runway-exporter\", env=\"$environment\"}, job_name)"
   },
   {
    "name": "region",
    "query": "label_values(stackdriver_cloud_run_job_run_googleapis_com_job_running_task_attempts{job=\"runway-exporter\", env=\"$environment\", type=\"$type\"}, location)"
   }
  ]
 },
 "panels": [
  {
   "title": "Completed execution",
   "type": "graph",
   "description": "Number of completed executions",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Completed execution count" }
   ],
   "targets": [
    {
     "expr": "sum by (type, result) (\n  clamp_min(stackdriver_cloud_run_job_run_googleapis_com_job_completed_execution_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}, 1)\n)\n"
    }
   ]
  },
  {
   "title": "Completed task attempts",
   "type": "graph",
   "description": "Number of task attempts including retries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Completed task attempts count" }
   ],
   "targets": [
    {
     "expr": "sum by (type, result) (\n  clamp_min(\n    stackdriver_cloud_run_job_run_googleapis_com_job_completed_task_attempt_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n  , 1)\n)\n"
    }
   ]
  },
  {
   "title": "Running executions",
   "type": "graph",
   "description": "Number of running execution including retries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Running execution count" }
   ],
   "targets": [
    {
     "expr": "count by (type) (\n  stackdriver_cloud_run_job_run_googleapis_com_job_running_executions{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n)\n"
    }
   ]
  },
  {
   "title": "Running task attempts",
   "type": "graph",
   "description": "Number of running task including retries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Running task attempts count" }
   ],
   "targets": [
    {
     "expr": "count by (type, attempt) (\n  stackdriver_cloud_run_job_run_googleapis_com_job_running_task_attempts{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n)\n"
    }
   ]
  },
  {
   "title": "Runway Service Billable Container Instance Time",
   "type": "graph",
   "description": "Billable time aggregated from all container instances.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Seconds per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name) (\n  stackdriver_cloud_run_job_run_googleapis_com_container_billable_instance_time{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n) / 60\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Runway Service CPU Utilization",
   "type": "graph",
   "description": "Container CPU utilization distribution across all container instances.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(histogram_quantile(\n  0.99,\n  sum by (job_name, region, location, le) (\n    max_over_time(stackdriver_cloud_run_job_run_googleapis_com_container_cpu_utilizations_bucket{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}[$__interval])\n  )\n)\n,1),0)\n",
     "legendFormat": "p99 {{job_name}} {{region}} {{location}}"
    }
   ]
  },
  {
   "title": "Runway Service Memory Utilization",
   "type": "graph",
   "description": "Container memory utilization distribution across all container instances.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(histogram_quantile(\n  0.99,\n  sum by (job_name, region, location, le) (\n    max_over_time(stackdriver_cloud_run_job_run_googleapis_com_container_memory_utilizations_bucket{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}[$__interval])\n  )\n)\n,1),0)\n",
     "legendFormat": "p99 {{job_name}} {{region}} {{location}}"
    }
   ]
  },
  {
   "title": "Sent bytes by Kind",
   "type": "graph",
   "description": "Outgoing socket and HTTP response traffic, in bytes.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(kind) (\n  stackdriver_cloud_run_job_run_googleapis_com_container_network_sent_bytes_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n) / 60\n",
     "legendFormat": "send {{kind}}"
    },
    { "legendFormat": "receive {{kind}}" }
   ]
  },
  {
   "title": "Received bytes by Kind",
   "type": "graph",
   "description": "Incoming socket and HTTP response traffic, in bytes.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    { "legendFormat": "send {{kind}}" },
    {
     "expr": "sum by(kind) (\n  stackdriver_cloud_run_job_run_googleapis_com_container_network_received_bytes_count{env=\"$environment\",job=\"runway-exporter\",location=~\"$region\",type=\"$type\"}\n) * -1 / 60\n",
     "legendFormat": "receive {{kind}}"
    }
   ]
  }
 ]
}