{
 "title": "runway: Runway Service Metrics",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6059307990 at Wed Jan 31 05:59:37 UTC 2024",
 "tags": [
  "managed",
  "runway",
  "runway",
  "type:runway"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "service",
    "query": "label_values(stackdriver_cloud_run_revision_run_googleapis_com_container_instance_count{job=\"runway-exporter\", env=\"$environment\"}, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Runway Service Request Count",
   "type": "graph",
   "description": "Number of requests reaching the service.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (response_code_class) (\n  rate(\n    stackdriver_cloud_run_revision_run_googleapis_com_request_count{env=\"$environment\",job=\"runway-exporter\",type=\"$service\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Runway Service Request Latency",
   "type": "graph",
   "description": "Distribution of request times reaching the service, in milliseconds.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (revision_name, le) (\n    rate(stackdriver_cloud_run_revision_run_googleapis_com_request_latencies_bucket{env=\"$environment\",job=\"runway-exporter\",type=\"$service\"}[$__interval])\n  )\n)\n",
     "legendFormat": "p99 {{revision_name}}"
    }
   ]
  },
  {
   "title": "Runway Service Container Instance Count",
   "type": "graph",
   "description": "Number of container instances that exist for the service.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Container Instances per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (revision_name) (\n  max_over_time(\n    stackdriver_cloud_run_revision_run_googleapis_com_container_instance_count{env=\"$environment\",job=\"runway-exporter\",type=\"$service\"}[${__interval}]\n  )\n)\n",
     "legendFormat": "{{revision_name}}"
    }
   ]
  },
  {
   "title": "Runway Service Billable Container Instance Time",
   "type": "graph",
   "description": "Billable time aggregated from all container instances.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name) (\n  rate(\n    stackdriver_cloud_run_revision_run_googleapis_com_container_billable_instance_time{env=\"$environment\",job=\"runway-exporter\",type=\"$service\"}[${__interval}]\n  )\n)\n",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Runway Service CPU Utilization",
   "type": "graph",
   "description": "Container CPU utilization distribution across all container instances.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(histogram_quantile(\n  0.99,\n  sum by (revision_name, le) (\n    max_over_time(stackdriver_cloud_run_revision_run_googleapis_com_container_cpu_utilizations_bucket{env=\"$environment\",job=\"runway-exporter\",type=\"$service\"}[$__interval])\n  )\n)\n,1),0)\n",
     "legendFormat": "p99 {{revision_name}}"
    }
   ]
  },
  {
   "title": "Runway Service Memory Utilization",
   "type": "graph",
   "description": "Container memory utilization distribution across all container instances.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(histogram_quantile(\n  0.99,\n  sum by (revision_name, le) (\n    max_over_time(stackdriver_cloud_run_revision_run_googleapis_com_container_memory_utilizations_bucket{env=\"$environment\",job=\"runway-exporter\",type=\"$service\"}[$__interval])\n  )\n)\n,1),0)\n",
     "legendFormat": "p99 {{revision_name}}"
    }
   ]
  },
  {
   "title": "Runway Service Sent Bytes",
   "type": "graph",
   "description": "Outgoing socket and HTTP response traffic, in bytes.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by (revision_name, kind) (\n  rate(\n    stackdriver_cloud_run_revision_run_googleapis_com_container_network_sent_bytes_count{env=\"$environment\",job=\"runway-exporter\",type=\"$service\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{kind}} {{revision_name}}"
    },
    {
     "legendFormat": "receive {{kind}} {{revision_name}}"
    }
   ]
  },
  {
   "title": "Runway Service Received Bytes",
   "type": "graph",
   "description": "Incoming socket and HTTP response traffic, in bytes.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "legendFormat": "send {{kind}} {{revision_name}}"
    },
    {
     "expr": "sum by (revision_name, kind) (\n  rate(\n    stackdriver_cloud_run_revision_run_googleapis_com_container_network_received_bytes_count{env=\"$environment\",job=\"runway-exporter\",type=\"$service\"}[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{kind}} {{revision_name}}"
    }
   ]
  },
  {
   "title": "Runway Service Max Concurrent Requests",
   "type": "graph",
   "description": "Distribution of the maximum number number of concurrent requests being served by each container instance over a minute.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(histogram_quantile(\n  0.99,\n  sum by (revision_name, le) (\n    max_over_time(stackdriver_cloud_run_revision_run_googleapis_com_container_max_request_concurrencies_bucket{env=\"$environment\",job=\"runway-exporter\",type=\"$service\"}[$__interval])\n  )\n) / 100\n,1),0)\n",
     "legendFormat": "p99 {{revision_name}}"
    }
   ]
  },
  {
   "title": "Runway Service Container Startup Latency",
   "type": "graph",
   "description": "Distribution of time spent starting a new container instance, in milliseconds.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum by (revision_name) (\n  rate(\n    stackdriver_cloud_run_revision_run_googleapis_com_container_startup_latencies_sum{env=\"$environment\",job=\"runway-exporter\",type=\"$service\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{revision_name}}"
    }
   ]
  },
  {
   "title": "Runway Service Container Healthcheck Requests",
   "type": "graph",
   "description": "Request rate of healthcheck attempts for the ingress container",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (revision_name, probe_type, is_healthy) (\n  stackdriver_cloud_run_revision_run_googleapis_com_container_completed_probe_attempt_count{env=\"$environment\",job=\"runway-exporter\",type=\"$service\", container_name='ingress'}\n)\n",
     "legendFormat": "{{revision_name}} {{probe_type}} healthy: {{is_healthy}}"
    }
   ]
  },
  {
   "title": "Runway Service Container Healthcheck Latency",
   "type": "graph",
   "description": "Distribution of time spent probing a container instance, in milliseconds.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ms", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum by (revision_name, probe_type, is_healthy) (\n  rate(\n    stackdriver_cloud_run_revision_run_googleapis_com_container_probe_attempt_latencies_sum{env=\"$environment\",job=\"runway-exporter\",type=\"$service\", container_name='ingress'}[$__interval]\n  )\n)\n",
     "legendFormat": "{{revision_name}} {{probe_type}} healthy: {{is_healthy}}"
    }
   ]
  }
 ]
}