{
 "title": "Sam G CI Minute",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "CI Runner Minutes Used by Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CI minutes used each 1 min" }
   ],
   "targets": [
    {
     "expr": "(\nsum(increase(gitlab_runner_job_duration_seconds_sum{instance=~\"gitlab-docker-shared-runners-manager-01.gitlab.com.*|gitlab-docker-shared-runners-manager-02.gitlab.com.*|gitlab-docker-shared-runners-manager-03.gitlab.com.*|gitlab-docker-shared-runners-manager-04.gitlab.com.*|gitlab-shared-runners-manager-3.gitlab.com.*|gitlab-shared-runners-manager-4.gitlab.com.*|gitlab-shared-runners-manager-5.gitlab.com.*|gitlab-shared-runners-manager-6.gitlab.com.*|private-runners-manager-3.gitlab.com.*|private-runners-manager-4.gitlab.com.*|shared-runners-manager-3.gitlab.com.*|shared-runners-manager-3.staging.gitlab.com.*|shared-runners-manager-4.gitlab.com.*|shared-runners-manager-4.staging.gitlab.com.*|shared-runners-manager-5.gitlab.com.*|shared-runners-manager-6.gitlab.com.*|shared-runners-manager-7.gitlab.com.*|windows-shared-runners-manager-1.gitlab.com.*|windows-shared-runners-manager-2.gitlab.com.*\"}[1m]))\n) / 60",
     "requestId": "Q-278dc1c3-e1b2-4670-baa0-f82f433af732-0A"
    }
   ]
  },
  {
   "title": "CI Runner Minutes Used by Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CI minutes consumed per hour" }
   ],
   "targets": [
    {
     "expr": "(\nsum(increase(gitlab_runner_job_duration_seconds_sum{instance=~\"gitlab-docker-shared-runners-manager-01.gitlab.com.*|gitlab-docker-shared-runners-manager-02.gitlab.com.*|gitlab-docker-shared-runners-manager-03.gitlab.com.*|gitlab-docker-shared-runners-manager-04.gitlab.com.*|gitlab-shared-runners-manager-3.gitlab.com.*|gitlab-shared-runners-manager-4.gitlab.com.*|gitlab-shared-runners-manager-5.gitlab.com.*|gitlab-shared-runners-manager-6.gitlab.com.*|private-runners-manager-3.gitlab.com.*|private-runners-manager-4.gitlab.com.*|shared-runners-manager-3.gitlab.com.*|shared-runners-manager-3.staging.gitlab.com.*|shared-runners-manager-4.gitlab.com.*|shared-runners-manager-4.staging.gitlab.com.*|shared-runners-manager-5.gitlab.com.*|shared-runners-manager-6.gitlab.com.*|shared-runners-manager-7.gitlab.com.*|windows-shared-runners-manager-1.gitlab.com.*|windows-shared-runners-manager-2.gitlab.com.*\"}[1h]))\n) / 60",
     "requestId": "Q-278dc1c3-e1b2-4670-baa0-f82f433af732-0A"
    }
   ]
  },
  {
   "title": "CI Runner Minutes Used by 6 Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    {
     "format": "short",
     "label": "CI minutes consumed per 6 hours"
    }
   ],
   "targets": [
    {
     "expr": "(\nsum(increase(gitlab_runner_job_duration_seconds_sum{instance=~\"gitlab-docker-shared-runners-manager-01.gitlab.com.*|gitlab-docker-shared-runners-manager-02.gitlab.com.*|gitlab-docker-shared-runners-manager-03.gitlab.com.*|gitlab-docker-shared-runners-manager-04.gitlab.com.*|gitlab-shared-runners-manager-3.gitlab.com.*|gitlab-shared-runners-manager-4.gitlab.com.*|gitlab-shared-runners-manager-5.gitlab.com.*|gitlab-shared-runners-manager-6.gitlab.com.*|private-runners-manager-3.gitlab.com.*|private-runners-manager-4.gitlab.com.*|shared-runners-manager-3.gitlab.com.*|shared-runners-manager-3.staging.gitlab.com.*|shared-runners-manager-4.gitlab.com.*|shared-runners-manager-4.staging.gitlab.com.*|shared-runners-manager-5.gitlab.com.*|shared-runners-manager-6.gitlab.com.*|shared-runners-manager-7.gitlab.com.*|windows-shared-runners-manager-1.gitlab.com.*|windows-shared-runners-manager-2.gitlab.com.*\"}[6h]))\n) / 60",
     "requestId": "Q-278dc1c3-e1b2-4670-baa0-f82f433af732-0A"
    }
   ]
  },
  {
   "title": "CI Runner Minutes Used by Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    {
     "format": "short",
     "label": "CI minutes consumed per 24 hours"
    }
   ],
   "targets": [
    {
     "expr": "(\nsum(increase(gitlab_runner_job_duration_seconds_sum{instance=~\"gitlab-docker-shared-runners-manager-01.gitlab.com.*|gitlab-docker-shared-runners-manager-02.gitlab.com.*|gitlab-docker-shared-runners-manager-03.gitlab.com.*|gitlab-docker-shared-runners-manager-04.gitlab.com.*|gitlab-shared-runners-manager-3.gitlab.com.*|gitlab-shared-runners-manager-4.gitlab.com.*|gitlab-shared-runners-manager-5.gitlab.com.*|gitlab-shared-runners-manager-6.gitlab.com.*|private-runners-manager-3.gitlab.com.*|private-runners-manager-4.gitlab.com.*|shared-runners-manager-3.gitlab.com.*|shared-runners-manager-3.staging.gitlab.com.*|shared-runners-manager-4.gitlab.com.*|shared-runners-manager-4.staging.gitlab.com.*|shared-runners-manager-5.gitlab.com.*|shared-runners-manager-6.gitlab.com.*|shared-runners-manager-7.gitlab.com.*|windows-shared-runners-manager-1.gitlab.com.*|windows-shared-runners-manager-2.gitlab.com.*\"}[24h]))\n) / 60",
     "requestId": "Q-278dc1c3-e1b2-4670-baa0-f82f433af732-0A"
    }
   ]
  },
  {
   "title": "CI Runner Minutes Used by Week",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "CI minutes consumed per week" }
   ],
   "targets": [
    {
     "expr": "(\nsum(increase(gitlab_runner_job_duration_seconds_sum{instance=~\"gitlab-docker-shared-runners-manager-01.gitlab.com.*|gitlab-docker-shared-runners-manager-02.gitlab.com.*|gitlab-docker-shared-runners-manager-03.gitlab.com.*|gitlab-docker-shared-runners-manager-04.gitlab.com.*|gitlab-shared-runners-manager-3.gitlab.com.*|gitlab-shared-runners-manager-4.gitlab.com.*|gitlab-shared-runners-manager-5.gitlab.com.*|gitlab-shared-runners-manager-6.gitlab.com.*|private-runners-manager-3.gitlab.com.*|private-runners-manager-4.gitlab.com.*|shared-runners-manager-3.gitlab.com.*|shared-runners-manager-3.staging.gitlab.com.*|shared-runners-manager-4.gitlab.com.*|shared-runners-manager-4.staging.gitlab.com.*|shared-runners-manager-5.gitlab.com.*|shared-runners-manager-6.gitlab.com.*|shared-runners-manager-7.gitlab.com.*|windows-shared-runners-manager-1.gitlab.com.*|windows-shared-runners-manager-2.gitlab.com.*\"}[7d]))\n) / 60",
     "requestId": "Q-278dc1c3-e1b2-4670-baa0-f82f433af732-0A"
    }
   ]
  },
  {
   "title": "CI Runner Minutes Used by Month",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "CI minutes consumed per month" }
   ],
   "targets": [
    {
     "expr": "(\nsum(increase(gitlab_runner_job_duration_seconds_sum{instance=~\"gitlab-docker-shared-runners-manager-01.gitlab.com.*|gitlab-docker-shared-runners-manager-02.gitlab.com.*|gitlab-docker-shared-runners-manager-03.gitlab.com.*|gitlab-docker-shared-runners-manager-04.gitlab.com.*|gitlab-shared-runners-manager-3.gitlab.com.*|gitlab-shared-runners-manager-4.gitlab.com.*|gitlab-shared-runners-manager-5.gitlab.com.*|gitlab-shared-runners-manager-6.gitlab.com.*|private-runners-manager-3.gitlab.com.*|private-runners-manager-4.gitlab.com.*|shared-runners-manager-3.gitlab.com.*|shared-runners-manager-3.staging.gitlab.com.*|shared-runners-manager-4.gitlab.com.*|shared-runners-manager-4.staging.gitlab.com.*|shared-runners-manager-5.gitlab.com.*|shared-runners-manager-6.gitlab.com.*|shared-runners-manager-7.gitlab.com.*|windows-shared-runners-manager-1.gitlab.com.*|windows-shared-runners-manager-2.gitlab.com.*\"}[30d]))\n) / 60",
     "requestId": "Q-278dc1c3-e1b2-4670-baa0-f82f433af732-0A"
    }
   ]
  }
 ]
}