{
 "title": "score_chunks_v2",
 "tags": [
  "protected",
  "unmanaged"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Count of Prompts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM prompt_library.score_chunks_v2",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Count of Prompts by Chunking Method",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT chunking_method as \"Chunking Method\", COUNT(*) as \"Count\" FROM prompt_library.score_chunks_v2 GROUP BY chunking_method",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Average Similarity Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(score) FROM prompt_library.score_chunks_v2",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Average Similarity Score by Chunking Method",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT chunking_method as \"Chunking Method\", AVG(score) as \"Average Similarity Score\" FROM prompt_library.score_chunks_v2 GROUP BY chunking_method",
     "selectedFormat": 1
    }
   ]
  }
 ]
}