{
 "title": "search: Zoekt Info",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5164311687 at Tue Sep 26 07:52:38 UTC 2023",
 "tags": [
  "managed",
  "search",
  "zoekt",
  "search"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Search Duration 98th Percentile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.97999999999999998, sum by (container, le) (rate(zoekt_search_duration_seconds_bucket{env=\"$environment\"}[10m])))\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Search Rate 5m",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zoekt_search_requests_total{env=\"$environment\"}[5m])\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Error Rate 5m",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zoekt_search_failed_total{env=\"$environment\"}[5m])\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Persistent Volume Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "% utilization" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{env=\"$environment\", persistentvolumeclaim=~\"zoekt-index-gitlab-gitlab-zoekt.*\"}\n/ kubelet_volume_stats_capacity_bytes{env=\"$environment\", persistentvolumeclaim=~\"zoekt-index-gitlab-gitlab-zoekt.*\"}) by (persistentvolumeclaim)\n\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    { "expr": "80", "legendFormat": "80% Threshold" }
   ]
  },
  {
   "title": "I/O Reads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"}[5m])) by (container, pod)\n"
    }
   ]
  },
  {
   "title": "I/O Writes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"}[5m])) by (container, pod)\n"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(go_memstats_heap_sys_bytes{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"}) by (container, pod)\n/ sum(go_memstats_heap_alloc_bytes{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"}) by (container, pod)) / 100\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"}[5m]))by (container, pod)\n"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"}[5m]))by (container, pod)\n"
    }
   ]
  }
 ]
}