{
 "title": "search: Zoekt Info",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/7558995994 at Mon Aug 12 06:49:48 UTC 2024",
 "tags": [
  "managed",
  "search",
  "zoekt",
  "search"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Search Duration 98th Percentile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.97999999999999998, sum by (container, le) (rate(zoekt_search_duration_seconds_bucket{env=\"$environment\"}[10m])))\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Search Rate 5m",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zoekt_search_requests_total{env=\"$environment\"}[5m])\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Error Rate 5m",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zoekt_search_failed_total{env=\"$environment\"}[5m])\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Persistent Volume Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "% utilization" }
   ],
   "targets": [
    {
     "expr": "100*sum(kubelet_volume_stats_used_bytes{env=\"$environment\", persistentvolumeclaim=~\"zoekt-index-gitlab-gitlab-zoekt.*\"}\n/ kubelet_volume_stats_capacity_bytes{env=\"$environment\", persistentvolumeclaim=~\"zoekt-index-gitlab-gitlab-zoekt.*\"}) by (persistentvolumeclaim)\n\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    { "expr": "80", "legendFormat": "80% Threshold" }
   ]
  },
  {
   "title": "I/O Reads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"}[5m])) by (container, pod)\n"
    }
   ]
  },
  {
   "title": "I/O Writes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"}[5m])) by (container, pod)\n"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory Map Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(proc_metrics_memory_map_current_count{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"}) by (container, pod)\n"
    },
    {
     "expr": "min(proc_metrics_memory_map_max_limit{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"})\n",
     "legendFormat": "Memory Map Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"}[5m]))by (container, pod)\n"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{pod=~\"gitlab-gitlab-zoekt.*\", container=~\"zoekt.*\", env=\"$environment\"}[5m]))by (container, pod)\n"
    }
   ]
  },
  { "title": "Additional Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "content": "\n### Zoekt Rollout Epic\n\nSee https://gitlab.com/groups/gitlab-org/-/epics/9404\n\n### Helpful Links\n\n- [Memory Usage](https://dashboards.gitlab.net/d/kubernetes-resources-pod/kubernetes-compute-resources-pod?orgId=1&var-datasource=default&var-cluster=gprd-gitlab-gke&var-namespace=gitlab&var-pod=gitlab-gitlab-zoekt-0&from=now-6h&to=now)\n- [Sourcegraph Observability Documentation](https://docs.sourcegraph.com/admin/observability/dashboards)\n"
  }
 ]
}