{
 "title": "Secret Push Protection – Overview",
 "description": "This dashboard gives an overview of the components the Pre-receive SD feature interacts and monitors their stability and performance.",
 "tags": [
  "secret-detection",
  "secure",
  "gitaly",
  "rails",
  "workhorse",
  "unmanaged",
  "protected",
  "secret-push-protection",
  "gitlab-shell"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Secret Push Protection – Overview\n\nPlease read the associated [runbook](https://handbook.gitlab.com/handbook/engineering/development/sec/secure/secret-detection/runbooks/secret-push-protection-monitoring/) for more information on how to read and update this dashboard."
   }
  },
  { "title": "🐚 GitLab Shell (Git over SSH)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "gitlab–shell / RPS (Requests Per Second)",
   "type": "timeseries",
   "description": "This panel displays average number of requests per second (RPS) made to `gitlab-shell` over time. The panel can be used to monitor request rates and understand if there's a performance or scalability issue. Use the link for more detailed overview of this metric. Note: this isn't specific to `git-receive-pack` command.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"gitlab_shell\", env=\"gprd\", monitor=\"global\", stage=\"main\", type=\"git\"}[$__interval])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": {
    "content": "#### Description\n\nThis sub-section monitors [`gitlab-shell` tool](https://gitlab.com/gitlab-org/gitlab-shell) which is a set of executables used to handle git push over SSH (among other things). Most of the metrics available for `gitlab-shell` though aren't aggregated by the command used, so it does make sense to look more closely at the Kibana logs linked below for a good measure of how the `git-receive-pack` command is performing.\n\n#### Observability Tools\n\n* 📖 [Kibana: GitLab Shell Logs – For `git-receive-pack` command](https://log.gprd.gitlab.net/app/discover#/view/d7431f7a-95a1-4981-910f-6ffa575aa8f2?_g=()).\n* 📖 [Kibana: GitLab Shell Failed Requests Logs](https://log.gprd.gitlab.net/app/discover#/view/23da9f7a-1cf0-4fb1-9917-6f2596920539?_g=()).\n\n**Note**: `json.command` for failed requests isn't populated, so link above displays all failed requests."
   }
  },
  {
   "title": "gitlab-shell / Total Established Gitaly Connections",
   "type": "timeseries",
   "description": "This panel displays the total number of Gitaly connections that have been established by `gitlab-shell` at a given time. This panel can be used to determine if there's a sudden drop in connections between both components, which may indicate a performance or an availability issue. Note: this isn't specific to `git-receive-pack` command.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count by(status) (gitlab_shell_gitaly_connections_total{env=\"gprd\", stage=\"main\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gitlab-shell / Established SSH Sessions",
   "type": "stat",
   "description": "This panel displays the minimum number of established SSH sessions at a given time. The panel can be used to understand if there's an availability issue together with the panel adjacent to it which shows how the maximum number of SSH sessions that failed to establish at a given time. Note: this isn't specific to `git-receive-pack` command.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(gitlab_sli:shell_sshd_sessions:total{env=\"gprd\", stage=\"main\", type=\"git\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gitlab-shell / Failed SSH Sessions",
   "type": "stat",
   "description": "This panel displays the maximum number of failed SSH sessions at a given time. The panel can be used to understand if there's an availability issues together with the panel adjacent to it which shows how the minimum number of SSH sessions established over a given time. Note: this isn't specific to `git-receive-pack` command.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(app) (gitlab_sli:shell_sshd_sessions:errors_total{stage=\"main\", type=\"git\", env=\"gprd\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gitlab-shell / Established Session Average Duration",
   "type": "timeseries",
   "description": "This panel displays the average duration of establish SSH sessions summed up over a range of 24 hours. The panel can be used to determine if there's an increase in the duration of a git pull/push over SSH which may indicate a performance or availability issue. Note: this isn't specific to `git-receive-pack` command.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(gitlab_shell_sshd_session_established_duration_seconds_sum{env=\"gprd\", stage=\"main\", type=\"git\"}[24h])) / sum(rate(gitlab_shell_sshd_session_established_duration_seconds_count[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "gitlab-shell / All Sessions Average Duration",
   "type": "timeseries",
   "description": "This panel displays the average duration of all SSH sessions (whether established or failed) summed up over a range of 24 hours. The panel can be used to determine if there's an increase in the duration of a git pull/push over SSH which may indicate a performance or availability issue. Note: this isn't specific to `git-receive-pack` command.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(gitlab_shell_sshd_session_duration_seconds_sum{env=\"gprd\", stage=\"main\", type=\"git\"}[24h])) / sum(rate(gitlab_shell_sshd_session_duration_seconds_count[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "gitlab-sshd / SLI Apdex",
   "type": "timeseries",
   "description": "This panel displays the application performance index (Apdex) for the `gitlab-sshd` SSH daemon/server. This Service Level Indicator (SLI) averages close to 99.9%, most of the time but a drop in the indicator could point to an outage or degradation. Use the link for more detailed overview of this metric. Note: this isn't specific to git-receive-pack command.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"gitlab_sshd\",env=\"gprd\",environment=\"gprd\",monitor=\"global\",stage=\"main\",type=\"git\"}[$__interval])",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": {
    "content": "#### Description\n\nThis sub-section monitors the [`gitlab-sshd` daemon](https://docs.gitlab.com/ee/development/gitlab_shell/gitlab_sshd.html), which is the SSH server `gitlab-shell` uses to communicate with Rails to perform authorization or access checks. Most metrics available for `gitlab-sshd` aren't aggregated by the command used though, so take them with a grain of salt and focus more on the Kibana links below to learn how `git-receive-pack` is performing.\n\n#### Observability Tools\n\n* 📖 [Kibana: GitLab Shell Logs – For `git-receive-pack` command](https://log.gprd.gitlab.net/app/discover#/view/d7431f7a-95a1-4981-910f-6ffa575aa8f2?_g=()).\n* 📖 [Kibana: GitLab Shell Failed Requests Logs](https://log.gprd.gitlab.net/app/discover#/view/23da9f7a-1cf0-4fb1-9917-6f2596920539?_g=()).\n\n**Note**: `json.command` for failed requests isn't populated, so link above displays all failed requests."
   }
  },
  {
   "title": "gitlab–sshd / SLI Error Ratio",
   "type": "timeseries",
   "description": "This panel displays the max ratio of errors clamped to maximum value received for the `gitlab-sshd` SSH daemon/server. This Service Level Indicator (SLI) averages close to 0.01%, most of the time but an increase in the indicator could point to an outage or degradation. Use the link for more detailed overview of this metric. Note: this isn't specific to git-receive-pack command.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(gitlab_component_errors:ratio_5m{component=\"gitlab_sshd\",env=\"gprd\",environment=\"gprd\",monitor=\"global\",stage=\"main\",type=\"git\"}[$__interval]), 1)",
     "legendFormat": "Error Ratio"
    }
   ]
  },
  {
   "title": "gitlab–sshd / RPS (Requests Per Second)",
   "type": "timeseries",
   "description": "This panel displays average number of requests per second (RPS) made to `gitlab-sshd` SSH daemon/server over time. The panel can be used to monitor request rates and understand if there's a performance or scalability issue. Use the link for more detailed overview of this metric. Note: this isn't specific to `git-receive-pack` command.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"gitlab_sshd\", env=\"gprd\", monitor=\"global\", stage=\"main\", type=\"git\"}[$__interval])",
     "legendFormat": "RPS"
    }
   ]
  },
  { "title": "🐎 Workhorse (Git over HTTP/S)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Processed `/.git/git-receive-pack` Requests",
   "type": "timeseries",
   "description": "This panel displays the number of HTTP requests that have been processed by `workhorse` over time since last restart of the service, increasing in range of 24 hours. The panel partitions these requests by the HTTP verb/method and response code. This panel can be used to determine if the amount of `git-receive-pack` requests with a response code that isn't `200` had increased recently, indicating an issue with processing such requests.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(code, method) (increase(gitlab_workhorse_git_http_requests{exported_service=\"git-receive-pack\", stage=\"main\", env=\"gprd\", code!=\"0\"}[24h]))",
     "legendFormat": "{{code}} | {{method}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "options": {
    "content": "#### Description\n\nThis section monitors `workhorse`, which is a smart reverse proxy intended to handle resource-intensive and long-running requests. It intercepts all HTTP requests and either propagates them without changing or handles them itself by performing additional logic.\n\n#### Observability Tools\n\n* [📖 Kibana: Workhorse `/.git/git-receive-pack` request logs](https://log.gprd.gitlab.net/app/discover#/view/79006bda-a8a3-4f91-ba24-476211d4d64e?_g=())\n* [📖 Kibana: Workhorse `/.git/git-receive-pack` slow request logs](https://log.gprd.gitlab.net/app/discover#/view/deca6b50-7ae4-4e50-bfbc-d24bee529656?_g=())\n* [📖 Kibana: Workhorse `/.git/git-receive-pack` failed request logs](https://log.gprd.gitlab.net/app/discover#/view/eb17ec46-dbb9-4c16-a442-8b983e264eb6?_g=())"
   }
  },
  {
   "title": "Total Established Gitaly Connections",
   "type": "timeseries",
   "description": "This panel displays the total number of `Gitaly` connections that have been established by `workhorse` at a given time. This panel can be used to determine if there's a sudden drop in connections between both components, which may indicate a performance or an availability issue.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "count by(status) (gitlab_workhorse_gitaly_connections_total{env=\"gprd\", stage=\"main\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Latency for `/.git/git-receive-pack` Request [All Nodes]",
   "type": "timeseries",
   "description": "This panel displays the average latency (duration) in seconds for the `/.git/git-receive-pack` request for all nodes running `workhorse`. This panel can be used to determine if there is an increase in response times for that specific request, which could indicate performance degradation issue if it surpassed a certain thershold.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_request_duration_seconds_sum{env=\"gprd\", stage=\"main\", route=\"^/.+\\\\.git/git-receive-pack\\\\z\"}[24h])) / sum(rate(gitlab_workhorse_http_request_duration_seconds_count{env=\"gprd\", stage=\"main\", route=\"^/.+\\\\.git/git-receive-pack\\\\z\"}[24h]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SLI Apdex",
   "type": "timeseries",
   "description": "This panel displays the application performance index (Apdex) for the `workhorse` component. This Service Level Indicator (SLI) averages close to 99.9%, most of the time but a drop in the indicator could point to an outage or degradation. Use the link for more detailed overview of this metric. Note: this isn't specific to `/.git/git-receive-pack` route.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"workhorse\", env=\"gprd\", monitor=\"global\", stage=\"main\", type=\"git\"}[$__interval])",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "SLI Error Ratio",
   "type": "timeseries",
   "description": "This panel displays the max ratio of errors clamped to maximum value received for workhorse. This Service Level Indicator (SLI) averages close to 0.001%, most of the time but an increase in the indicator could point to an outage or degradation. Use the link for more detailed overview of this metric. Note: this isn't specific to `/.git/git-receive-pack` route.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(max_over_time(gitlab_component_errors:ratio_5m{component=\"workhorse\", env=\"gprd\", monitor=\"global\", stage=\"main\", type=\"git\"}[$__interval]), 1)",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "RPS (Requests Per Second)",
   "type": "timeseries",
   "description": "This panel displays average number of requests per second (RPS) made to `workhorse` over time. The panel can be used to monitor request rates and understand if there's a performance or scalability issue. Use the link for more detailed overview of this metric. Note: this isn't specific to `/.git/git-receive-pack` route.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"workhorse\", env=\"gprd\", monitor=\"global\", stage=\"main\", type=\"git\"}[$__interval])",
     "legendFormat": "RPS"
    }
   ]
  },
  { "title": "⚙️ Gitaly", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "PostReceivePack – Average Latency [All Hosts]",
   "type": "stat",
   "description": "This panel displays the average latency on all hosts in milliseconds for calls to the `PostReceivePack` RPC, which is the RPC responsible for calling `git-receive-pack` command, that in turn executes the `PreReceiveHook`. The latter goes on to call `/internal/allowed` endpoint that runs access checks on Rails side.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(1000 * avg(gitaly:grpc_server_handling_seconds:avg5m{grpc_method=\"PostReceivePack\"}))\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "options": {
    "content": "#### Details\n\nThis sub-section monitors the integration between **Workhorse** and **Gitaly**. We focus mostly on the `PostReceivePack` RPC which directly invokes `git-receive-pack` command when a git push takes place over HTTP/S, that in turn executes the hooks such as `PreReceiveHook`.\n\n#### Resources\n\n* [📈 PostReceivePack Feature Status](https://dashboards.gitlab.net/d/000000199/gitaly-feature-status?orgId=1&refresh=5m&var-environment=gprd&var-method=PostReceivePack&var-prometheus=PA5EEDCB71676F488)\n* [📈 PostReceivePack Latency Details](https://dashboards.gitlab.net/d/PqeIQ9Iik/gitaly-feature-latency-detail?orgId=1&refresh=5m&var-job=gitaly&var-method=PostReceivePack)\n* [📈 PostReceivePack Error Diagnostics](https://dashboards.gitlab.net/d/xSYVQ9Sik/gitaly-feature-error-diagnostics?orgId=1&refresh=5m&var-job=gitaly&var-method=PostReceivePack)"
   }
  },
  {
   "title": "SSHReceivePack – Average Latency [All Hosts]",
   "type": "stat",
   "description": "This panel displays the average latency on all hosts in milliseconds for calls to the `SSHReceivePack` RPC, which is the RPC responsible for calling `git-receive-pack` command (for git push over SSH), that in turn executes the `PreReceiveHook`. The latter goes on to call `/internal/allowed` endpoint which runs access checks on Rails side.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(1000 * avg(gitaly:grpc_server_handling_seconds:avg5m{grpc_method=\"SSHReceivePack\"}))\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "options": {
    "content": "#### Details\n\nThis sub-section monitors the integration between **GitLab Shell** and **Gitaly**. We focus mostly on the `SSHReceivePack` RPC which directly invokes `git-receive-pack` command when a git push takes place over SSH, that in turn executes the hooks such as `PreReceiveHook`.\n\n#### Resources\n\n* [📈 SSHReceivePack Feature Status](https://dashboards.gitlab.net/d/000000199/gitaly-feature-status?orgId=1&refresh=5m&var-environment=gprd&var-method=SSHReceivePack&var-prometheus=PA5EEDCB71676F488)\n* [📈 SSHReceivePack Latency Details](https://dashboards.gitlab.net/d/PqeIQ9Iik/gitaly-feature-latency-detail?orgId=1&refresh=5m&var-job=gitaly&var-method=SSHReceivePack)\n* [📈 SSHReceivePack Error Diagnostics](https://dashboards.gitlab.net/d/xSYVQ9Sik/gitaly-feature-error-diagnostics?orgId=1&refresh=5m&var-job=gitaly&var-method=SSHReceivePack)"
   }
  },
  {
   "title": "PreReceiveHook – Average Latency [All Hosts]",
   "type": "stat",
   "description": "This panel displays the average latency on all hosts in milliseconds for calls to the `PreReceiveHook` hook, that in turn calls `/internal/allowed` endpoint to runs access checks on Rails side.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(1000 * avg(gitaly:grpc_server_handling_seconds:avg5m{grpc_method=\"PreReceiveHook\"}))\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "options": {
    "content": "#### Details\n\nThis sub-section monitors the integration between **Gitaly** and **Rails**. We focus here on operations taking place before the `/internal/allowed` endpoint is called, namely:\n\n* [`PreReceiveHook` hook](https://gitlab.com/gitlab-org/gitaly/-/blob/master/doc/hooks.md#receive-pack-hooks)\n\n#### Resources\n\n* [📈 PreReceiveHook Feature Status](https://dashboards.gitlab.net/d/000000199/gitaly-feature-status?orgId=1&refresh=5m&var-environment=gprd&var-method=PreReceiveHook&var-prometheus=PA5EEDCB71676F488)\n* [📈 PreReceiveHook Latency Details](https://dashboards.gitlab.net/d/PqeIQ9Iik/gitaly-feature-latency-detail?orgId=1&refresh=5m&var-job=gitaly&var-method=PreReceiveHook)\n* [📈 PreReceiveHook Error Diagnostics](https://dashboards.gitlab.net/d/xSYVQ9Sik/gitaly-feature-error-diagnostics?orgId=1&refresh=5m&var-job=gitaly&var-method=PreReceiveHook)\n"
   }
  },
  {
   "title": "ListAllBlobs – Average Latency [All Hosts]",
   "type": "stat",
   "description": "This panel displays the average latency in milliseconds for all calls to the `ListAllBlobs` RPC, which is responsible (within the context of the feature) for enumerating all blobs of a repository under a certain size limit (i.e. exactly 1MiB). This procedure is usually fast because it is mostly used with the size limit set to `0` for checking file sizes of blobs in a certain `git` push.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(1000 * avg(gitaly:grpc_server_handling_seconds:avg5m{grpc_method=\"ListAllBlobs\"}))\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ListBlobs – Average Latency [All Hosts]",
   "type": "stat",
   "description": "This panel displays the average latency in milliseconds for all calls to the `ListBlobs` RPC, which is responsible (within the context of the feature) for enumerating all blobs of a repository under a certain size limit (i.e. exactly 1MiB), similar to `ListAllBlobs`, but it also loads up file paths for those blobs. The procedure is often slower than `ListAllBlobs` because it loads up blob contents when enumerating them. ",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(1000 * avg(gitaly:grpc_server_handling_seconds:avg5m{grpc_method=\"ListBlobs\"}))\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "options": {
    "content": "#### Details\n\nThis sub-section monitors the integration between Gitaly and Rails. We focus here on RPCs called from within the `/internal/allowed` endpoint, namely:\n\n* [`ListAllBlobs()` RPC](https://gitlab-org.gitlab.io/gitaly/#gitaly.ListAllBlobsRequest)\n* [`ListBlobs()` RPC](https://gitlab-org.gitlab.io/gitaly/#gitaly.ListBlobsRequest)\n* [`GetTreeEntries()` RPC](https://gitlab-org.gitlab.io/gitaly/#gitaly.GetTreeEntriesRequest)\n\n#### Resources\n\n* [📈 ListAllBlobs Feature Status](https://dashboards.gitlab.net/d/000000199/gitaly-feature-status?orgId=1&refresh=5m&var-environment=gprd&var-method=ListAllBlobs&var-prometheus=PA5EEDCB71676F488)\n* [📈 ListAllBlobs Latency Details](https://dashboards.gitlab.net/d/PqeIQ9Iik/gitaly-feature-latency-detail?orgId=1&refresh=5m&var-job=gitaly&var-method=ListAllBlobs)\n* [📈 ListAllBlobs Error Diagnostics](https://dashboards.gitlab.net/d/xSYVQ9Sik/gitaly-feature-error-diagnostics?orgId=1&refresh=5m&var-job=gitaly&var-method=ListAllBlobs)\n* [📈 ListBlobs Feature Status](https://dashboards.gitlab.net/d/000000199/gitaly-feature-status?orgId=1&refresh=5m&var-environment=gprd&var-method=ListBlobs&var-prometheus=PA5EEDCB71676F488)\n* [📈 ListBlobs Latency Details](https://dashboards.gitlab.net/d/PqeIQ9Iik/gitaly-feature-latency-detail?orgId=1&refresh=5m&var-job=gitaly&var-method=ListBlobs)\n* [📈 ListBlobs Error Diagnostics](https://dashboards.gitlab.net/d/xSYVQ9Sik/gitaly-feature-error-diagnostics?orgId=1&refresh=5m&var-job=gitaly&var-method=ListBlobs)\n* [📈 GetTreeEntries Feature Status](https://dashboards.gitlab.net/d/000000199/gitaly-feature-status?orgId=1&refresh=5m&var-environment=gprd&var-method=GetTreeEntries&var-prometheus=PA5EEDCB71676F488)\n* [📈 GetTreeEntries Latency Details](https://dashboards.gitlab.net/d/PqeIQ9Iik/gitaly-feature-latency-detail?orgId=1&refresh=5m&var-job=gitaly&var-method=GetTreeEntries)\n* [📈 GetTreeEntries Error Diagnostics](https://dashboards.gitlab.net/d/xSYVQ9Sik/gitaly-feature-error-diagnostics?orgId=1&refresh=5m&var-job=gitaly&var-method=GetTreeEntries)"
   }
  },
  {
   "title": "GetTreeEntries – Average Latency",
   "type": "stat",
   "description": "This panel displays the average latency in milliseconds for all calls to the GetTreeEntries RPC, which is responsible (within the context of the feature) for retrieving blob metadata (i.e. file path and commit sha) for all blobs that were scanned and found to include a leaked secret.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(1000 * avg(gitaly:grpc_server_handling_seconds:avg5m{grpc_method=\"GetTreeEntries\"}))\n",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ method }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "🚂 Rails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Internal API / Request Latency",
   "type": "timeseries",
   "description": "This panel displays the average, p95, and p99 latencies for requests made to the `/internal/allowed` endpoint over time. The panel can be used to monitor request latency and understand if there's a performance or scalability issue. Use the link for more detailed overview of this metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate5m{action=\"POST /api/internal/allowed\", controller=\"Grape\", environment=\"gprd\", stage=\"main\", type=\"internal-api\"}[$__interval]))",
     "legendFormat": "{{action}} - avg"
    },
    {
     "expr": "avg by (controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds:p95{action=~\"(POST /api/internal/allowed)\",controller=\"Grape\",environment=\"gprd\",stage=\"main\",type=\"internal-api\"}[$__interval]))",
     "legendFormat": "{{action}} - p95"
    },
    {
     "expr": "avg by (controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds:p95{action=~\"(POST /api/internal/allowed)\",controller=\"Grape\",environment=\"gprd\",stage=\"main\",type=\"internal-api\"}[$__interval]))",
     "legendFormat": "{{action}} - p99"
    },
    {
     "expr": "sum by (controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds_sum:rate1m{action=~\"(POST /api/internal/allowed)\",controller=\"Grape\",environment=\"gprd\",stage=\"main\",type=\"internal-api\"}[$__interval]))\n/\nsum by (controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds_count:rate1m{action=~\"(POST /api/internal/allowed)\",controller=\"Grape\",environment=\"gprd\",stage=\"main\",type=\"internal-api\"}[$__interval]))\n",
     "legendFormat": "{{action}} - mean"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "options": {
    "content": "#### Description\n\nThis sub-section monitors the `/internal/allowed` endpoint of [GitLab's Rails](https://gitlab.com/gitlab-org/gitlab) application. The endpoint is called from Gitaly within the [PreReceive Hook](https://gitlab.com/gitlab-org/gitaly/-/blob/master/doc/hooks.md#receive-pack-hooks) when a `git` push operation takes place.\n\nBelow you also find links to logs emitted from the [Secret Push Check](https://gitlab.com/gitlab-org/gitlab/-/blob/master/ee/lib/gitlab/checks/secrets_check.rb) as scanning takes place.\n\n#### Observability Tools\n\n* 📖 [Kibana: Logs for all scans](https://log.gprd.gitlab.net/app/discover#/view/31afcbb2-28e9-466f-a6c3-486e869e1ee3).\n* 📖 [Kibana: Logs for blocked pushes](https://log.gprd.gitlab.net/app/discover#/view/db7ba29d-d406-46df-8b43-e6d9c47fbed7)."
   }
  },
  {
   "title": "Internal API / RPS (Requests Per Second)",
   "type": "timeseries",
   "description": "This panel displays average number of requests per second (RPS) made to the `/internal/allowed` endpoint over time. The panel can be used to monitor request rates and understand if there's a performance or scalability issue. Use the link for more detailed overview of this metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(controller, action) (avg_over_time(controller_action:gitlab_transaction_duration_seconds_count:rate1m{action=\"POST /api/internal/allowed\", controller=\"Grape\", environment=\"gprd\", stage=\"main\", type=\"internal-api\"}[$__interval]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Internal API / Memory Saturation Rate",
   "type": "timeseries",
   "description": "This panel displays the memory saturation rate for two components of the internal API, which are Ruby VM and Puma Workers. This is helpful to understand if the memory consumption in Rails had increased to the point of saturation, which indicates a performance and a scalability issue and requires attention. Note: this panel isn't specific to `/internal/allowed` endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(component) (max_over_time(gitlab_component_saturation:ratio{env=\"gprd\", environment=\"gprd\", stage=\"main\", type=\"internal-api\", component=\"ruby_thread_contention\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(component) (max_over_time(gitlab_component_saturation:ratio{env=\"gprd\", environment=\"gprd\", stage=\"main\", type=\"internal-api\", component=\"puma_workers\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}