{
 "title": "Sentry",
 "tags": [ "observability" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(sentry_jobs_started_total, env)"
   },
   {
    "name": "fqdn",
    "query": "label_values(sentry_jobs_started_total{env=\"$env\"}, fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Client API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sentry_client_api_responses_total{env=\"$env\",fqdn=\"$fqdn\",status=~\"[0-9]{3}\"}[$__interval])",
     "legendFormat": "API {{api_version}} - {{status}}"
    }
   ]
  },
  {
   "title": "Events Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sentry_events_processed_total{env=\"$env\",fqdn=\"$fqdn\"}[$__interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sentry_jobs_started_total{env=\"ops\",fqdn=\"$fqdn\"}[$__interval])",
     "legendFormat": "Started"
    },
    {
     "expr": "rate(sentry_jobs_finished_total{env=\"ops\",fqdn=\"$fqdn\"}[$__interval])",
     "legendFormat": "Finished"
    }
   ]
  }
 ]
}