{
 "title": "sentry: Kube Sentry main Copy",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4645781195 at Thu Jul 13 08:21:48 UTC 2023",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"sentry\", pod=~\"sentry-worker-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RabbitMQ total queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{env=\"ops\", namespace=\"sentry\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentry Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Events processed per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sentry_ingest_consumer_process_event_count{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sentry_jobs_duration{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Time to process events",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sentry_ingest_consumer_process_event{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (nginx_ingress_controller_nginx_process_connections{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests in 5 minutes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(exported_service) (rate(nginx_ingress_controller_requests{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\", exported_service=~\"sentry-relay|sentry-web\"}[5m]))",
     "legendFormat": "{{ exported_service }}"
    }
   ]
  },
  {
   "title": "Clickhouse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname)(chi_clickhouse_metric_TCPConnection{chi=\"sentry\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica delay",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "chi_clickhouse_metric_ReplicasMaxAbsoluteDelay{chi=\"sentry\"}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Zookeeper requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname)(chi_clickhouse_metric_ZooKeeperRequest{chi=\"sentry\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Consumer group lag by topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{cluster=\"ops-gitlab-gke\",env=\"ops\",namespace=\"sentry\"}",
     "legendFormat": "{{ topic }}"
    }
   ]
  }
 ]
}