{
 "title": "sentry: Events",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4266941644 at Thu May 11 10:53:41 UTC 2023",
 "tags": [
  "managed",
  "sentry",
  "sentry"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Sentry Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client API Responses by API version",
   "type": "graph",
   "description": "Responses from client api by version and status",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(sentry_client_api_responses_total{env=\"ops\",status=~\"[0-9]{3}\"}[$__interval])",
     "legendFormat": "API {{api_version}} - {{status}}"
    }
   ]
  },
  {
   "title": "Events Processed by Language",
   "type": "graph",
   "description": "Events Processed by Sentry",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sentry_events_processed_total{env=\"ops\"}[$__interval])",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Total number of started and processed jobs",
   "type": "graph",
   "description": "Total number of jobs started and finished.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sentry_jobs_started_total{env=\"ops\"}[$__interval])",
     "legendFormat": "Started"
    },
    {
     "expr": "rate(sentry_jobs_finished_total{env=\"ops\"}[$__interval])",
     "legendFormat": "Finished"
    }
   ]
  },
  {
   "title": "Event Latency",
   "type": "heatmap",
   "description": "Responses from client api by version and status",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (le) (rate(sentry_events_latency_seconds_bucket{env=\"ops\"}[$__interval]))",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}