{
 "title": "Sentry draft",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Sentry application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events processed per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(sentry_ingest_consumer_process_event_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "sentry_jobs_duration", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Time to process events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sentry_ingest_consumer_process_event",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(pod) (nginx_ingress_controller_nginx_process_connections{namespace=\"sentry\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests in 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(exported_service) (rate(nginx_ingress_controller_requests{namespace=\"sentry\", exported_service=~\"sentry-relay|sentry-web\"}[5m]))",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  { "title": "Clickhouse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(ClickHouseMetrics_TCPConnection)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active vs Waiting Readers/Writers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(ClickHouseMetrics_RWLockActiveReaders)",
     "legendFormat": "Active Readers"
    },
    {
     "expr": "sum(ClickHouseMetrics_RWLockActiveWriters)",
     "legendFormat": "Active Writers"
    },
    {
     "expr": "sum(ClickHouseMetrics_RWLockWaitingReaders)",
     "legendFormat": "Waiting Readers"
    },
    {
     "expr": "sum(ClickHouseMetrics_RWLockWaitingWriters)",
     "legendFormat": "Waiting Writers"
    }
   ]
  },
  {
   "title": "Zookeeper requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(ClickHouseMetrics_ZooKeeperRequest)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasMaxAbsoluteDelay",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}