{
 "title": "Service Platform Metrics - Stages",
 "tags": [ "general" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "type",
    "query": "label_values(gitlab_service_ops:rate{environment=\"$environment\"}, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency: Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "\n      min(\n        min_over_time(\n          gitlab_service_apdex:ratio{environment=\"$environment\", type=\"$type\", stage!=\"\"}[$__interval]\n        )\n      ) by (stage)\n      ",
     "legendFormat": "{{ stage }} stage"
    },
    {
     "expr": "\n        avg(slo:min:gitlab_service_apdex:ratio{environment=\"$environment\", type=\"$type\"}) or avg(slo:min:gitlab_service_apdex:ratio{type=\"$type\"})\n      ",
     "legendFormat": "SLO"
    }
   ]
  },
  {
   "title": "Error Ratios",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions within a minute period. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "% Requests in Error" }
   ],
   "targets": [
    {
     "expr": "\n      max(\n        max_over_time(\n          gitlab_service_errors:ratio{environment=\"$environment\", type=\"$type\", stage!=\"\"}[$__interval]\n        )\n      ) by (stage)\n      ",
     "legendFormat": "{{ stage }} stage"
    },
    {
     "expr": "\n        avg(slo:max:gitlab_service_errors:ratio{environment=\"$environment\", type=\"$type\"}) or avg(slo:max:gitlab_service_errors:ratio{type=\"$type\"})\n      ",
     "legendFormat": "SLO"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "graph",
   "description": "Availability measures the ratio of component processes in the service that are currently healthy and able to handle requests. The closer to 100% the better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit", "label": "Availability %" }
   ],
   "targets": [
    {
     "expr": "\n      min(\n        min_over_time(\n          gitlab_service_availability:ratio{environment=\"$environment\", type=\"$type\", stage!=\"\"}[$__interval]\n        )\n      ) by (stage)\n      ",
     "legendFormat": "{{ stage }} stage"
    }
   ]
  },
  {
   "title": "RPS - Service Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "\n      max(\n        avg_over_time(\n          gitlab_service_ops:rate{environment=\"$environment\", type=\"$type\", stage!=\"\"}[$__interval]\n        )\n      ) by (stage)\n      ",
     "legendFormat": "{{ stage }} stage"
    }
   ]
  }
 ]
}