{
 "title": "Server Performance",
 "tags": [
  "staging-ref",
  "gstg-ref",
  "unmanaged"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Quality Server Performance\n\nUsed for https://staging-ref.gitlab.com/\n\n### Other dashboards\n\n- [Detailed gstg-ref host stats dashboard](https://dashboards.gitlab.net/d/bd2Kl9Imk/host-stats?orgId=1&var-env=gstg-ref)\n- [Detailed web controller dashboard](https://dashboards.gitlab.net/d/web-rails-controller/web-rails-controller?orgId=1&var-PROMETHEUS_DS=Global&var-environment=gstg-ref)"
   }
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - (avg by (instance) (irate(node_cpu_seconds_total{env=\"gstg-ref\",mode=\"idle\"}[5m]))))  * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "CPU - {{nodename}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{env=\"gstg-ref\", job!='prometheus'} - node_memory_MemAvailable_bytes{env=\"gstg-ref\",job!='prometheus'}) * on(instance) group_left(nodename) (node_uname_info{env=\"gstg-ref\",nodename!~\".*elastic-.\"})",
     "legendFormat": "Memory Used MB - {{nodename}}"
    },
    {
     "expr": "((100 - ((node_memory_MemAvailable_bytes{env=\"gstg-ref\",job!='prometheus'} * 100) / node_memory_MemTotal_bytes{env=\"gstg-ref\", job!='prometheus'})) > 75) * on(instance) group_left(nodename)(node_uname_info{env=\"gstg-ref\"})",
     "legendFormat": "Memory Used % - {{nodename}}"
    }
   ]
  },
  {
   "title": "Workhorse HTTP RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job)(irate(gitlab_workhorse_http_requests_total{env=\"gstg-ref\"}[1m]))",
     "legendFormat": "Workhorse req/s"
    }
   ]
  },
  {
   "title": "Controller - Action Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(gitlab_transaction_duration_seconds_count{env=\"gstg-ref\",controller!=''}[1m])) by (controller, action) > 0",
     "legendFormat": "{{controller}} - {{action}}"
    }
   ]
  },
  {
   "title": "NGINX Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{env=\"gstg-ref\",state=\"active\"}[2m]))",
     "legendFormat": "Active connections"
    },
    {
     "expr": "histogram_quantile(0.5,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{env=\"gstg-ref\"}[1m])))",
     "legendFormat": "Total request handling time 0.5"
    },
    {
     "expr": "histogram_quantile(0.99,sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{env=\"gstg-ref\"}[1m])))",
     "legendFormat": "Total request handling time 0.99"
    }
   ]
  },
  {
   "title": "HAProxy HTTP Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_http_responses_total{env=\"gstg-ref\"}[5m])) by (code)",
     "legendFormat": "Frontend {{ code }}"
    },
    {
     "expr": "sum(irate(haproxy_backend_http_responses_total{env=\"gstg-ref\"}[5m])) by (code)",
     "legendFormat": "Backend {{ code }}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{env=\"gstg-ref\",device!~'rootfs'} - node_filesystem_free_bytes{env=\"gstg-ref\",device!~'rootfs'}) * on(instance) group_left(nodename)(node_uname_info) != 0",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk Usage Times",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(node_disk_io_time_seconds_total{env=\"gstg-ref\"}[1m])) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "Disk Usage Time - {{nodename}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(sum by (instance) (rate(node_disk_reads_completed_total{env=\"gstg-ref\"}[1m]))) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "Disk IOPS Read Rate - {{nodename}}"
    },
    {
     "expr": "(sum by (instance) (rate(node_disk_writes_completed_total{env=\"gstg-ref\"}[1m]))) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "Disk IOPS Write Rate - {{nodename}}"
    }
   ]
  },
  {
   "title": "Disk I/O Byte Rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(sum by (instance) (rate(node_disk_read_bytes_total{env=\"gstg-ref\"}[1m]))) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "Disk Read Rate - {{nodename}}"
    },
    {
     "expr": "(sum by (instance) (rate(node_disk_written_bytes_total{env=\"gstg-ref\"}[1m]))) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "Disk Write Rate - {{nodename}}"
    }
   ]
  },
  {
   "title": "Context Switches / Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(irate(node_context_switches_total{env=\"gstg-ref\"}[5m])) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "Context Switches - {{nodename}}"
    },
    {
     "expr": "irate(node_intr_total{env=\"gstg-ref\"}[5m])  * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "Interrupts - {{nodename}}"
    }
   ]
  },
  {
   "title": "Puma (Webserver) Workers ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod)(puma_running_workers{env=\"gstg-ref\",worker=\"master\"})",
     "legendFormat": "Running - {{pod}}"
    },
    {
     "expr": "sum by (pod)(increase(puma_killer_terminations_total{env=\"gstg-ref\"}[1m]))",
     "legendFormat": "Puma Killed Workers - {{ pod }}"
    }
   ]
  },
  {
   "title": "Puma (Webserver) Metrics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum by (pod)(puma_active_connections{env=\"gstg-ref\"}), \"ip\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Puma Active Connections - {{pod}}"
    },
    {
     "expr": "label_replace(sum by (pod)(puma_queued_connections{env=\"gstg-ref\"}), \"ip\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "Puma Queued Connections - {{pod}}"
    }
   ]
  },
  {
   "title": "PgBouncer Metrics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{env=\"gstg-ref\",database=~\"gitlabhq_production\"})",
     "legendFormat": "Client Active Connections"
    },
    {
     "expr": "sum (pgbouncer_pools_server_active_connections{env=\"gstg-ref\",database=~\"gitlabhq_production\"})",
     "legendFormat": "Server Active Connections "
    },
    {
     "expr": "sum (pgbouncer_pools_client_waiting_connections{env=\"gstg-ref\",database=~\"gitlabhq_production\"})",
     "legendFormat": "Client Waiting Connections "
    }
   ]
  },
  {
   "title": "Postgres Metrics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum by (instance)(pg_stat_activity_count{env=\"gstg-ref\"}), \"ip\", \"$1\", \"instance\", \"(.*):.*\") * on(ip) group_left(nodename) (label_replace(node_uname_info, \"ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "Activity Count - {{nodename}}"
    }
   ]
  },
  {
   "title": "SQL Transactions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(gitlab_sql_duration_seconds_count{env=\"gstg-ref\"}[1m]))",
     "legendFormat": "SQL Transactions"
    }
   ]
  },
  {
   "title": "Redis Cache Queries",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(gitlab_cache_operation_duration_seconds_count{env=\"gstg-ref\"}[1m])) by (operation, type)",
     "legendFormat": "{{operation}} - {{type}}"
    }
   ]
  },
  {
   "title": "Workhorse p95",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{env=\"gstg-ref\"}[5m])) by (le))",
     "legendFormat": "Workhorse p95 HTTP Req Duration"
    }
   ]
  },
  {
   "title": "Gitaly p95",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{env=\"gstg-ref\"}[5m])) by (le))",
     "legendFormat": "Gitaly p95 GRPC"
    }
   ]
  },
  {
   "title": "Ruby GC Cycles",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(irate(ruby_gc_duration_seconds_count{env=\"gstg-ref\"}[5m]), \"ip\", \"$1\", \"instance\", \"(.*):.*\") ",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Ruby Heap GC Slots",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum by (job, instance)(ruby_gc_stat_heap_live_slots{env=\"gstg-ref\"}), \"ip\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}} - Ruby Heap Live Slots"
    },
    {
     "expr": "label_replace(sum by (job, instance)(ruby_gc_stat_heap_free_slots{env=\"gstg-ref\"}), \"ip\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{container}} - Ruby Heap Free Slots"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((100 - ((node_memory_MemAvailable_bytes{env=\"gstg-ref\",job!='prometheus'} * 100) / node_memory_MemTotal_bytes{env=\"gstg-ref\",job!='prometheus'}))) * on(instance) group_left(nodename) (node_uname_info)",
     "legendFormat": "Memory Used % - {{nodename}}"
    }
   ]
  },
  {
   "title": "Gitaly Read Distribution",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (virtual_storage, storage)(rate(gitaly_praefect_read_distribution{env=\"gstg-ref\"}[1m]))",
     "legendFormat": "{{virtual_storage}} - {{storage}}"
    }
   ]
  },
  {
   "title": "Gitaly Praefect Cache Access",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (virtual_storage, type)(rate(gitaly_praefect_uptodate_storages_cache_access_total{env=\"gstg-ref\"}[1m]))",
     "legendFormat": "{{virtual_storage}} - {{type}}"
    }
   ]
  },
  {
   "title": "Sidekiq Jobs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue)(sidekiq_running_jobs{env=\"gstg-ref\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "GRPCs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(30, sum by (grpc_code, grpc_method,grpc_service, job)(irate(grpc_client_handled_total{env=\"gstg-ref\"}[5m])) > 0)",
     "legendFormat": "{{job}} - {{grpc_service}} - {{grpc_method}} - {{grpc_code}}"
    }
   ]
  },
  {
   "title": "NFS Rate Metrics",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method)(irate(node_nfs_requests_total{env=\"gstg-ref\",proto='4'}[5m]))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum by (method)(irate(node_nfsd_requests_total{env=\"gstg-ref\",proto='4'}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "NFS Response/Request time Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (operation)(irate(node_mountstats_nfs_operations_request_time_seconds_total{env=\"gstg-ref\"}[5m])) > 0",
     "legendFormat": "{{operation}} - Request time"
    },
    {
     "expr": "sum by (operation)(irate(node_mountstats_nfs_operations_queue_time_seconds_total{env=\"gstg-ref\"}[5m])) > 0",
     "legendFormat": "{{operation}} - Queue time"
    }
   ]
  }
 ]
}