{
 "title": "Sidekiq Shard Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Shard Utilization - 10m window",
   "type": "graph",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, stage, shard)  (rate(sidekiq_jobs_completion_seconds_sum{environment=\"$environment\"}[10m]))\n/\nsum by (environment, stage, shard)  (avg_over_time(sidekiq_concurrency{environment=\"$environment\"}[10m]))\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Shard Utilization - Hourly window",
   "type": "graph",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (environment, stage, shard)  (rate(sidekiq_jobs_completion_seconds_sum{environment=\"$environment\"}[1h]))\n/\nsum by (environment, stage, shard)  (avg_over_time(sidekiq_concurrency{environment=\"$environment\"}[1h]))\n,1),0)\n",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Shard Utilization - Instant",
   "type": "graph",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "sum by (environment, stage, shard)  (rate(sidekiq_jobs_completion_seconds_sum{environment=\"$environment\"}[$__interval]))\n/\nsum by (environment, stage, shard)  (avg_over_time(sidekiq_concurrency{environment=\"$environment\"}[$__interval]))",
     "legendFormat": "{{shard}}"
    }
   ]
  }
 ]
}