{
 "title": "Sidekiq Resizing Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(up{job=\"prometheus\"}, environment)"
   },
   {
    "name": "priority",
    "label": "Priority",
    "query": "label_values(up{type=\"sidekiq\",environment=\"$environment\"}, priority)"
   }
  ]
 },
 "panels": [
  {
   "title": "Job completion time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (priority) (priority:sidekiq_jobs_completion_seconds:p95{environment=\"$environment\", priority=\"$priority\"} > 0)",
     "legendFormat": "{{priority}} - p95"
    },
    {
     "expr": "avg by (priority) (priority:sidekiq_jobs_completion_seconds:p99{environment=\"$environment\", priority=\"$priority\"} > 0 )",
     "legendFormat": "{{priority}} - p99"
    },
    {
     "expr": "avg by (priority)  (priority:sidekiq_jobs_completion_seconds:p50{environment=\"$environment\", priority=\"$priority\"} > 0)",
     "legendFormat": "{{priority}} - p50"
    }
   ]
  },
  {
   "title": "Rate of job failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn, priority) (rate(sidekiq_jobs_failed_total{environment=\"$environment\",priority=\"$priority\"}[1m]))",
     "legendFormat": "{{fqdn}} - {{priority}}"
    }
   ]
  },
  {
   "title": "Ratio of $priority-01-sv-$environment to the rest of the fleet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sidekiq_jobs_completion_seconds_bucket{environment=\"$environment\", priority=\"$priority\", fqdn=~\".*-01-.*\"}[5m])) by (le, priority))\n\n/\n\nhistogram_quantile(0.95, sum(rate(sidekiq_jobs_completion_seconds_bucket{environment=\"$environment\", priority=\"$priority\", fqdn!~\".*-01-.*\"}[5m])) by (le, priority))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Pages queue latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_latency{environment=\"$environment\",name=~\"pages|pages_domain_verification\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pages queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_size{environment=\"$environment\",name=~\"pages|pages_domain_verification\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Besteffort queue latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_latency{environment=\"$environment\",name=~\"auto_devops:auto_devops_disable|cronjob:admin_email|cronjob:expire_build_artifacts|cronjob:gitlab_usage_ping|cronjob:import_export_project_cleanup|cronjob:pages_domain_verification_cron|cronjob:pipeline_schedule|cronjob:prune_old_events|cronjob:remove_expired_group_links|cronjob:remove_expired_members|cronjob:remove_unreferenced_lfs_objects|cronjob:repository_archive_cache|cronjob:repository_check_dispatch|cronjob:requests_profiles|cronjob:stuck_ci_jobs|cronjob:stuck_import_jobs|cronjob:stuck_merge_jobs|cronjob:ci_archive_traces_cron|cronjob:trending_projects|cronjob:issue_due_scheduler|cronjob:prune_web_hook_logs|cronjob:schedule_migrate_external_diffs|gcp_cluster:cluster_install_app|gcp_cluster:cluster_patch_app|gcp_cluster:cluster_upgrade_app|gcp_cluster:cluster_provision|gcp_cluster:cluster_wait_for_app_installation|gcp_cluster:wait_for_cluster_creation|gcp_cluster:cluster_wait_for_ingress_ip_address|gcp_cluster:cluster_configure|gcp_cluster:cluster_project_configure|github_import_advance_stage|github_importer:github_import_import_diff_note|github_importer:github_import_import_issue|github_importer:github_import_import_note|github_importer:github_import_import_lfs_object|github_importer:github_import_refresh_import_jid|github_importer:github_import_stage_finish_import|github_importer:github_import_stage_import_base_data|github_importer:github_import_stage_import_issues_and_diff_notes|github_importer:github_import_stage_import_notes|github_importer:github_import_stage_import_lfs_objects|github_importer:github_import_stage_import_pull_requests|github_importer:github_import_stage_import_repository|hashed_storage:hashed_storage_migrator|hashed_storage:hashed_storage_rollbacker|hashed_storage:hashed_storage_project_migrate|hashed_storage:hashed_storage_project_rollback|object_storage:object_storage_migrate_uploads|pipeline_background:ci_build_trace_chunk_flush|deployment:deployments_success|repository_check:repository_check_clear|repository_check:repository_check_batch|repository_check:repository_check_single_repository|todos_destroyer:todos_destroyer_confidential_issue|todos_destroyer:todos_destroyer_entity_leave|todos_destroyer:todos_destroyer_group_private|todos_destroyer:todos_destroyer_project_private|todos_destroyer:todos_destroyer_private_features|object_pool:object_pool_create|object_pool:object_pool_schedule_join|object_pool:object_pool_join|object_pool:object_pool_destroy|container_repository:delete_container_repository|container_repository:cleanup_container_repository|default|mailers|background_migration|chat_notification|create_gpg_signature|git_garbage_collect|invalid_gpg_signature_update|irker|migrate_external_diffs|pages_domain_verification|plugin|project_cache|project_export|rebase|remote_mirror_notification|repository_remove_remote|system_hook_push|upload_checksum|repository_update_remote_mirror|create_note_diff_file|delete_diff_files|detect_repository_languages|repository_cleanup|delete_stored_files|import_issues_csv|project_daily_statistics|cronjob:clear_shared_runners_minutes|cronjob:geo_file_download_dispatch|cronjob:geo_metrics_update|cronjob:geo_prune_event_log|cronjob:geo_migrated_local_files_clean_up|cronjob:geo_repository_sync|cronjob:geo_repository_verification_primary_batch|cronjob:geo_repository_verification_secondary_scheduler|cronjob:geo_sidekiq_cron_config|cronjob:geo_scheduler_per_shard_scheduler|cronjob:geo_scheduler_primary_per_shard_scheduler|cronjob:geo_scheduler_secondary_per_shard_scheduler|cronjob:geo_repository_verification_secondary_shard|cronjob:historical_data|cronjob:ldap_all_groups_sync|cronjob:ldap_sync|cronjob:pseudonymizer|cronjob:update_max_seats_used_for_gitlab_com_subscriptions|gcp_cluster:cluster_update_app|gcp_cluster:cluster_wait_for_app_update|incident_management:incident_management_process_alert|create_github_webhook|elastic_namespace_indexer|new_epic\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Best effort queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_latency{environment=\"$environment\",name=~\"auto_devops:auto_devops_disable|cronjob:admin_email|cronjob:expire_build_artifacts|cronjob:gitlab_usage_ping|cronjob:import_export_project_cleanup|cronjob:pages_domain_verification_cron|cronjob:pipeline_schedule|cronjob:prune_old_events|cronjob:remove_expired_group_links|cronjob:remove_expired_members|cronjob:remove_unreferenced_lfs_objects|cronjob:repository_archive_cache|cronjob:repository_check_dispatch|cronjob:requests_profiles|cronjob:stuck_ci_jobs|cronjob:stuck_import_jobs|cronjob:stuck_merge_jobs|cronjob:ci_archive_traces_cron|cronjob:trending_projects|cronjob:issue_due_scheduler|cronjob:prune_web_hook_logs|cronjob:schedule_migrate_external_diffs|gcp_cluster:cluster_install_app|gcp_cluster:cluster_patch_app|gcp_cluster:cluster_upgrade_app|gcp_cluster:cluster_provision|gcp_cluster:cluster_wait_for_app_installation|gcp_cluster:wait_for_cluster_creation|gcp_cluster:cluster_wait_for_ingress_ip_address|gcp_cluster:cluster_configure|gcp_cluster:cluster_project_configure|github_import_advance_stage|github_importer:github_import_import_diff_note|github_importer:github_import_import_issue|github_importer:github_import_import_note|github_importer:github_import_import_lfs_object|github_importer:github_import_refresh_import_jid|github_importer:github_import_stage_finish_import|github_importer:github_import_stage_import_base_data|github_importer:github_import_stage_import_issues_and_diff_notes|github_importer:github_import_stage_import_notes|github_importer:github_import_stage_import_lfs_objects|github_importer:github_import_stage_import_pull_requests|github_importer:github_import_stage_import_repository|hashed_storage:hashed_storage_migrator|hashed_storage:hashed_storage_rollbacker|hashed_storage:hashed_storage_project_migrate|hashed_storage:hashed_storage_project_rollback|object_storage:object_storage_migrate_uploads|pipeline_background:ci_build_trace_chunk_flush|deployment:deployments_success|repository_check:repository_check_clear|repository_check:repository_check_batch|repository_check:repository_check_single_repository|todos_destroyer:todos_destroyer_confidential_issue|todos_destroyer:todos_destroyer_entity_leave|todos_destroyer:todos_destroyer_group_private|todos_destroyer:todos_destroyer_project_private|todos_destroyer:todos_destroyer_private_features|object_pool:object_pool_create|object_pool:object_pool_schedule_join|object_pool:object_pool_join|object_pool:object_pool_destroy|container_repository:delete_container_repository|container_repository:cleanup_container_repository|default|mailers|background_migration|chat_notification|create_gpg_signature|git_garbage_collect|invalid_gpg_signature_update|irker|migrate_external_diffs|pages_domain_verification|plugin|project_cache|project_export|rebase|remote_mirror_notification|repository_remove_remote|system_hook_push|upload_checksum|repository_update_remote_mirror|create_note_diff_file|delete_diff_files|detect_repository_languages|repository_cleanup|delete_stored_files|import_issues_csv|project_daily_statistics|cronjob:clear_shared_runners_minutes|cronjob:geo_file_download_dispatch|cronjob:geo_metrics_update|cronjob:geo_prune_event_log|cronjob:geo_migrated_local_files_clean_up|cronjob:geo_repository_sync|cronjob:geo_repository_verification_primary_batch|cronjob:geo_repository_verification_secondary_scheduler|cronjob:geo_sidekiq_cron_config|cronjob:geo_scheduler_per_shard_scheduler|cronjob:geo_scheduler_primary_per_shard_scheduler|cronjob:geo_scheduler_secondary_per_shard_scheduler|cronjob:geo_repository_verification_secondary_shard|cronjob:historical_data|cronjob:ldap_all_groups_sync|cronjob:ldap_sync|cronjob:pseudonymizer|cronjob:update_max_seats_used_for_gitlab_com_subscriptions|gcp_cluster:cluster_update_app|gcp_cluster:cluster_wait_for_app_update|incident_management:incident_management_process_alert|create_github_webhook|elastic_namespace_indexer|new_epic\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ASAP queue latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_latency{environment=\"$environment\",name=~\"post_receive|emails_on_push|mail_scheduler|mailers|delete_user|group_destroy|system_hook_push|propagate_service_template|admin_emails|export_csv|geo_repository_update|delete_merged_branches|project_service|project_destroy|namespaceless_project_destroy|web_hook|geo|update_merge_requests|new_note|process_commit|chat_notification|project_cache\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ASAP queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_size{environment=\"$environment\",name=~\"post_receive|emails_on_push|mail_scheduler|mailers|delete_user|group_destroy|system_hook_push|propagate_service_template|admin_emails|export_csv|geo_repository_update|delete_merged_branches|project_service|project_destroy|namespaceless_project_destroy|web_hook|geo|update_merge_requests|new_note|process_commit|chat_notification|project_cache\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Import queue latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_latency{environment=\"$environment\",name=~\"repository_import|github_importer:github_import_import_pull_request\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Import queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_size{environment=\"$environment\",name=~\"repository_import|github_importer:github_import_import_pull_request\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pipeline queue latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_latency{environment=\"$environment\",name=~\"build|expire_build_instance_artifacts|pipeline|pipeline_creation|pipeline_default|pipeline_cache|pipeline_hooks|pipeline_processing|pipeline_processing:stage_update|pipeline_processing:pipeline_update|pipeline_hooks:build_hooks|pipeline_cache:expire_job_cache|pipeline_processing:update_head_pipeline_for_merge_request\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pipeline queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_size{environment=\"$environment\",name=~\"build|expire_build_instance_artifacts|pipeline|pipeline_creation|pipeline_default|pipeline_cache|pipeline_hooks|pipeline_processing|pipeline_processing:stage_update|pipeline_processing:pipeline_update|pipeline_hooks:build_hooks|pipeline_cache:expire_job_cache|pipeline_processing:update_head_pipeline_for_merge_request\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pull mirror queue latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_latency{environment=\"$environment\",name=~\"cronjob:update_all_mirrors|project_import_schedule|repository_update_mirror\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pull mirror queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_size{environment=\"$environment\",name=~\"cronjob:update_all_mirrors|project_import_schedule|repository_update_mirror\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Realtime queue latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_latency{environment=\"$environment\",name=~\"post_receive|merge|update_merge_requests|gitlab_shell|email_receiver|repository_fork|reactive_caching|project_update_repository_storage|ldap_group_sync|new_issue|new_merge_request|process_commit|authorized_projects|new_note\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Realtime queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_size{environment=\"$environment\",name=~\"post_receive|merge|update_merge_requests|gitlab_shell|email_receiver|repository_fork|reactive_caching|project_update_repository_storage|ldap_group_sync|new_issue|new_merge_request|process_commit|authorized_projects|new_note\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Traces queue latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_latency{environment=\"$environment\",name=~\"pipeline_background:archive_trace|object_storage:object_storage_background_move|object_storage:migrate_uploads\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Traces queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sidekiq_queue_size{environment=\"$environment\",name=~\"pipeline_background:archive_trace|object_storage:object_storage_background_move|object_storage:migrate_uploads\"}) AND ON(fqdn) (redis_connected_slaves != 0)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}