{
 "title": "sidekiq: Bitbucket Server Importer",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5016984182 at Tue Sep  5 05:05:58 UTC 2023",
 "tags": [
  "managed",
  "sidekiq",
  "sidekiq"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Imported Projects",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(bitbucket_server_importer_imported_projects_total{env=\"$environment\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Imported Merge (Pull) Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(bitbucket_server_importer_imported_merge_requests_total{env=\"$environment\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Imported Issues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(bitbucket_server_importer_imported_issues_total{env=\"$environment\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Imported Projects Per Hour",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bitbucket_server_importer_imported_projects_total{env=\"$environment\"}[$__interval])) * 3600",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Imported Merge (Pull) Requests Per Hour",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bitbucket_server_importer_imported_merge_requests_total{env=\"$environment\"}[$__interval])) * 3600",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Imported Issues Per Hour",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bitbucket_server_importer_imported_issues_total{env=\"$environment\"}[$__interval])) * 3600",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Import Duration",
   "type": "graph",
   "description": "Import duration. Lower is better.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    rate(bitbucket_server_importer_total_duration_seconds_bucket{\n      environment=\"$environment\"\n    }[$__interval])\n  ) by (le, environment))\n",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90,\n  sum(\n    rate(bitbucket_server_importer_total_duration_seconds_bucket{\n      environment=\"$environment\"\n    }[$__interval])\n  ) by (le, environment))\n",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    rate(bitbucket_server_importer_total_duration_seconds_bucket{\n      environment=\"$environment\"\n    }[$__interval])\n  ) by (le, environment))\n",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    rate(bitbucket_server_importer_total_duration_seconds_bucket{\n      environment=\"$environment\"\n    }[$__interval])\n  ) by (le, environment))\n",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}