{
 "title": "Sidekiq Timings",
 "description": "Skarbek: https://gitlab.com/gitlab-com/gl-infra/delivery/-/issues/1680#note_550241382",
 "tags": [ "keep" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "shard",
    "query": "label_values(up{environment=\"gprd\", type=\"sidekiq\"}, shard)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queue Duration",
   "type": "heatmap",
   "description": "Time jobs spent queued",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (increase(sli_aggregations:sidekiq_jobs_queue_duration_seconds_bucket_rate1m{env=\"gprd\", shard=\"$shard\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Completions Timing",
   "type": "heatmap",
   "description": "Time jobs take to run to completion",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (increase(sli_aggregations:sidekiq_jobs_completion_seconds_bucket_rate1m{env=\"gprd\", shard=\"$shard\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Replica Counts",
   "type": "graph",
   "description": "The number of Pods scheduled.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{replicaset=~\"^gitlab-sidekiq-$shard.*\", cluster=~\"gprd.*\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": {
    "content": "# Replica Maximums\n\n| shard | max replica count |\n| --- | --- |\n| catchall | 140 | \n| database-throttled | 1 |\n| elasticsearch | 8 |\n| gitaly-throttled | 3 |\n| low-urgency-cpu-bound | 100 |\n| memory-bound | 16 |\n| urgent-cpu-bound | 84 |\n| urgent-other | 130 |     "
   }
  }
 ]
}