{
 "title": "sidekiq: Region Detail",
 "description": "Uploaded by sylvesterchin at Fri Sep  9 07:43:40 UTC 2022",
 "tags": [
  "managed",
  "sidekiq",
  "type:sidekiq",
  "detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(gitlab_service_ops:rate, environment)"
    }
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "region",
    "query": {
     "query": "label_values(gitlab_background_jobs:queue:apdex:weight:score_1h{environment=\"$environment\", type=\"sidekiq\"}, region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Max Queuing Duration SLO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(NaN) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", region=\"$region\", urgency=\"throttled\"}\nor\nvector(60.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", region=\"$region\", urgency=\"low\"}\nor\nvector(10.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", region=\"$region\", urgency=\"high\"}\n",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Max Execution Duration SLO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(300.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", region=\"$region\", urgency=\"throttled\"}\nor\nvector(300.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", region=\"$region\", urgency=\"low\"}\nor\nvector(10.000000) and on () sidekiq_running_jobs{environment=\"$environment\", type=\"sidekiq\", stage=\"$stage\", region=\"$region\", urgency=\"high\"}\n",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Backlog",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sidekiq_queue_size{environment=\"$environment\", name=\"$region\"} and on(fqdn) (redis_connected_slaves != 0)) > 10)\n/\n(-deriv(sidekiq_queue_size{environment=\"$environment\", name=\"$region\"}[5m]) and on(fqdn) (redis_connected_slaves != 0) > 0)\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "🌡 Queue Key Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Apdex",
   "type": "graph",
   "description": "Queue apdex monitors the percentage of jobs that are dequeued within their queue threshold. Higher is better. Different jobs have different thresholds.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    {
     "format": "percentunit",
     "label": "% Jobs within Max Queuing Duration SLO"
    }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (region) (\n  (gitlab_background_jobs:queue:apdex:ratio_5m{environment=\"$environment\", region=\"$region\"} >= 0)\n  *\n  (gitlab_background_jobs:queue:apdex:weight:score_5m{environment=\"$environment\", region=\"$region\"} >= 0)\n)\n/\nsum by (region) (\n  (gitlab_background_jobs:queue:apdex:weight:score_5m{environment=\"$environment\", region=\"$region\"})\n)\n,1),0)\n",
     "legendFormat": "{{ region }} region apdex"
    }
   ]
  },
  {
   "title": "Execution Apdex",
   "type": "graph",
   "description": "Execution apdex monitors the percentage of jobs that run within their execution (run-time) threshold. Higher is better. Different jobs have different thresholds.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    {
     "format": "percentunit",
     "label": "% Jobs within Max Execution Duration SLO"
    }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (region) (\n  (gitlab_background_jobs:execution:apdex:ratio_5m{environment=\"$environment\", region=\"$region\"} >= 0)\n  *\n  (gitlab_background_jobs:execution:apdex:weight:score_5m{environment=\"$environment\", region=\"$region\"} >= 0)\n)\n/\nsum by (region) (\n  (gitlab_background_jobs:execution:apdex:weight:score_5m{environment=\"$environment\", region=\"$region\"})\n)\n,1),0)\n",
     "legendFormat": "{{ region }} execution apdex"
    }
   ]
  },
  {
   "title": "Execution Rate (RPS)",
   "type": "graph",
   "description": "Jobs executed per second",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ops", "label": "Jobs per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (region) (gitlab_background_jobs:execution:ops:rate_5m{environment=\"$environment\", region=\"$region\"})\n",
     "legendFormat": "{{ region }} rps"
    }
   ]
  },
  {
   "title": "Error Ratio",
   "type": "graph",
   "description": "Percentage of jobs that fail with an error. Lower is better.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "percentunit", "label": "Error Percentage" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(sum by (region) (\n  (gitlab_background_jobs:execution:error:rate_5m{environment=\"$environment\", region=\"$region\"} >= 0)\n)\n/\nsum by (region) (\n  (gitlab_background_jobs:execution:ops:rate_5m{environment=\"$environment\", region=\"$region\"} >= 0)\n)\n,1),0)\n",
     "legendFormat": "{{ region }} error ratio"
    }
   ]
  },
  {
   "title": "Enqueuing (rate of jobs enqueuing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jobs Enqueued",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (region) (\n  gitlab_background_jobs:queue:ops:rate_5m{environment=\"$environment\", region=~\"$region\"}\n)\n",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Jobs Enqueued per Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type, region) (\n  gitlab_background_jobs:queue:ops:rate_5m{environment=\"$environment\", region=~\"$region\"}\n)\n",
     "legendFormat": "{{ region }} - {{ type }}"
    }
   ]
  },
  {
   "title": "Jobs Enqueued by Schedule",
   "type": "graph",
   "description": "Enqueue events separated by immediate (destined for execution) vs delayed (destined for ScheduledSet) scheduling.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (region, scheduling) (\n  rate(sidekiq_enqueued_jobs_total{environment=\"$environment\", stage=\"$stage\", region=\"$region\"}[$__interval])\n  )\n",
     "legendFormat": "{{ region }} - {{ scheduling }}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "graph",
   "description": "The number of unstarted jobs in a queue",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (name) (max_over_time(sidekiq_queue_size{environment=\"$environment\", name=\"$region\"}[$__interval]) and on(fqdn) (redis_connected_slaves != 0))\n",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Queue Latency (the amount of time spent queueing)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (region, le) (\n  sli_aggregations:sidekiq_jobs_queue_duration_seconds_bucket_rate5m{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}\n))\n",
     "legendFormat": "p95 {{ region }}"
    }
   ]
  },
  {
   "title": "Execution Latency (the amount of time the job takes to execute after dequeue)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Execution Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (region, le) (\n  sli_aggregations:sidekiq_jobs_completion_seconds_bucket_rate5m{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}\n))\n",
     "legendFormat": "p95 {{ region }}"
    }
   ]
  },
  {
   "title": "Execution RPS (the rate at which jobs are completed after dequeue)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (region) (\n  gitlab_background_jobs:execution:ops:rate_5m{environment=\"$environment\", region=~\"$region\"}\n)\n",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Error Rate (the rate at which jobs fail)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (region) (\n  gitlab_background_jobs:execution:error:rate_5m{environment=\"$environment\", region=~\"$region\"}\n)\n",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Dead Jobs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (region) (\n  increase(sidekiq_jobs_dead_total{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n)\n",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (region, le) (\n  rate(sidekiq_jobs_cpu_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (region, le) (\n  rate(sidekiq_jobs_cpu_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (region, le) (\n  rate(sidekiq_jobs_cpu_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (region, le) (\n  rate(sidekiq_jobs_cpu_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p99"
    }
   ]
  },
  {
   "title": "Gitaly Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (region, le) (\n  rate(sidekiq_jobs_gitaly_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (region, le) (\n  rate(sidekiq_jobs_gitaly_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (region, le) (\n  rate(sidekiq_jobs_gitaly_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (region, le) (\n  rate(sidekiq_jobs_gitaly_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p99"
    }
   ]
  },
  {
   "title": "Database Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (region, le) (\n  rate(sidekiq_jobs_db_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (region, le) (\n  rate(sidekiq_jobs_db_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (region, le) (\n  rate(sidekiq_jobs_db_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (region, le) (\n  rate(sidekiq_jobs_db_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p99"
    }
   ]
  },
  {
   "title": "Redis Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (region, le) (\n  rate(sidekiq_redis_requests_duration_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (region, le) (\n  rate(sidekiq_redis_requests_duration_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (region, le) (\n  rate(sidekiq_redis_requests_duration_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (region, le) (\n  rate(sidekiq_redis_requests_duration_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p99"
    }
   ]
  },
  {
   "title": "Elasticsearch Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (region, le) (\n  rate(sidekiq_elasticsearch_requests_duration_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (region, le) (\n  rate(sidekiq_elasticsearch_requests_duration_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (region, le) (\n  rate(sidekiq_elasticsearch_requests_duration_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (region, le) (\n  rate(sidekiq_elasticsearch_requests_duration_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n))\n",
     "legendFormat": "{{ region }} p99"
    }
   ]
  },
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total SQL Queries Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint_id) (\n  rate(\n    gitlab_transaction_db_count_total{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{ endpoint_id }} - total"
    },
    {
     "expr": "sum by (endpoint_id) (\n  rate(\n    gitlab_transaction_db_primary_count_total{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{ endpoint_id }} - primary"
    },
    {
     "expr": "sum by (endpoint_id) (\n  rate(\n    gitlab_transaction_db_replica_count_total{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval]\n  )\n)\n",
     "legendFormat": "{{ endpoint_id }} - replica"
    }
   ]
  },
  {
   "title": "SQL Transactions Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint_id) (\n  rate(gitlab_database_transaction_seconds_count{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n)\n",
     "legendFormat": "{{ endpoint_id }}"
    }
   ]
  },
  {
   "title": "SQL Transaction Holding Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_database_transaction_seconds_sum{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])) by (endpoint_id)\n/\nsum(rate(gitlab_database_transaction_seconds_count{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])) by (endpoint_id)\n",
     "legendFormat": "{{ endpoint_id }} - p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_database_transaction_seconds_bucket{environment=\"$environment\",region=~\"$region\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])) by (endpoint_id, le))\n",
     "legendFormat": "{{ endpoint_id }} - p95"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 100 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n",
   "targets": [
    {}
   ]
  }
 ]
}