{
 "title": "sidekiq: Application Info",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6032357029 at Fri Jan 26 18:51:46 UTC 2024",
 "tags": [
  "managed",
  "sidekiq",
  "sidekiq"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, cluster)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info{environment=\"$environment\"}, namespace)"
   },
   { "name": "Deployment", "query": "gitlab-sidekiq-export," }
  ]
 },
 "panels": [
  { "title": "Stackdriver Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log messages with severity ERROR",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"ERROR\", pod_id=~\"^$Deployment.*\", cluster_name=\"$cluster\", namespace_id=\"$namespace\"}) / 60",
     "legendFormat": "ERROR msgs per second"
    }
   ]
  },
  {
   "title": "Log messages with severity INFO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(stackdriver_gke_container_logging_googleapis_com_log_entry_count{severity=\"INFO\", pod_id=~\"^$Deployment.*\", cluster_name=\"$cluster\", namespace_id=\"$namespace\"}) / 60",
     "legendFormat": "INFO msgs per second"
    }
   ]
  },
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Process CPU Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ruby_process_cpu_seconds_total{pod=~\"^$Deployment.*\", cluster=\"$cluster\", namespace=\"$namespace\", environment=\"$environment\", stage=\"$stage\"}[$__interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ruby_process_resident_memory_bytes{pod=~\"^$Deployment.*\", cluster=\"$cluster\", namespace=\"$namespace\", environment=\"$environment\", stage=\"$stage\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1001 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ruby_process_max_fds{pod=~\"^$Deployment.*\", cluster=\"$cluster\", namespace=\"$namespace\", environment=\"$environment\", stage=\"$stage\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}