{
 "title": "Sidekiq Stats",
 "tags": [
  "sidekiq",
  "triage"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "app_prometheus", "query": "prometheus" },
   {
    "name": "priority",
    "query": "label_values(instance:node_cpus:count{environment=\"$environment\", tier=\"sv\"}, priority)"
   }
  ]
 },
 "panels": [
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sidekiq Exceptions Rate by Controller",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_transaction_event_sidekiq_exception_total{environment=\"$environment\"}[1m])) by (controller)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ controller }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sidekiq Exceptions Rate by Priority",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gitlab_transaction_event_sidekiq_exception_total{environment=\"$environment\"}[1m])) by (priority)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ priority  }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sidekiq Exceptions Count by Controller",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_transaction_event_sidekiq_exception_total{environment=\"$environment\"}) by (controller)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ controller }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sidekiq Exceptions Count by Priority",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(gitlab_transaction_event_sidekiq_exception_total{environment=\"$environment\"}) by (priority)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ priority  }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Queues State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total Enqueued Jobs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(sidekiq_queue_size{environment=\"$environment\"}) by (name))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sidekiq_running_jobs_count{environment=\"$environment\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs to be retried",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(sidekiq_jobs_to_be_retried_count{environment=\"$environment\"}) by (name))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Dead Jobs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(sidekiq_dead_jobs_total{environment=\"$environment\"}) by (name))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AVG Fleet CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum(instance_cpu:node_cpu_not_idle:rate5m{fqdn=~\"sidekiq.*\", environment=\"$environment\"}) without (cpu) / instance:node_cpus:count{fqdn=~\"sidekiq.*\", environment=\"$environment\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sidekiq nodes availability",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(up{tier=\"sv\", job=\"base-debian\",environment=\"$environment\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$priority - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "repeat": "priority",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilization:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$priority - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilization:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$priority - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilization:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$priority - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilization:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$priority - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilization:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$priority - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilization:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$priority - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilization:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$priority - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilization:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$priority - Load Average",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
     "repeat": "priority",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg(node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Average",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$priority - Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg(node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Average",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$priority - Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg(node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Average",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$priority - Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg(node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Average",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$priority - Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg(node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Average",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$priority - Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg(node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Average",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$priority - Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg(node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Average",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$priority - Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg(node_load1{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Average",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$priority - Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "repeat": "priority",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"} ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "$priority - Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"} ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "$priority - Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"} ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "$priority - Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"} ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "$priority - Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"} ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "$priority - Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"} ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "$priority - Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"} ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "$priority - Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"} ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{fqdn}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(1 - instance:node_memory_available:ratio{environment=\"$environment\", tier=\"sv\", priority=\"$priority\"})",
     "legendFormat": "AVG"
    }
   ]
  },
  { "title": "Totals & Queue Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total Enqueued Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_queue_size{environment=\"$environment\"} and on (fqdn) gitlab:redis_master)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Running Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_running_jobs_count{name!~\"(ActiveJob|Devise).*\", environment=\"$environment\"} and on (fqdn) gitlab:redis_master)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sidekiq Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sidekiq_queue_size{environment=\"$environment\"} and on (fqdn) gitlab:redis_master",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rate of Running Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(sidekiq_running_jobs_count{name!~\"(ActiveJob|Devise).*\", environment=\"$environment\"}[1m]) and on (fqdn) gitlab:redis_master",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sidekiq TCP Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{type=\"sidekiq\",fqdn=~\".*besteffort.*\"}",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  { "title": "Jobs completion time - p99", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Best-effort jobs completion time -  p99",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sidekiq_jobs_completion_time_seconds_bucket{priority=\"besteffort\", environment=\"$environment\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ASAP jobs completion time -  p99",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sidekiq_jobs_completion_time_seconds_bucket{priority=\"asap\", environment=\"$environment\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Real-time jobs completion time -  p99",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sidekiq_jobs_completion_time_seconds_bucket{priority=\"realtime\", environment=\"$environment\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch jobs completion time -  p99",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sidekiq_jobs_completion_time_seconds_bucket{priority=\"elasticsearch\", environment=\"$environment\"}[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jobs to Retry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total jobs to be Retried",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(max(sidekiq_jobs_to_be_retried_count{environment=\"$environment\"}) by (name))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Total",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Jobs to be Retried",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(sidekiq_jobs_to_be_retried_count{environment=\"$environment\"}) by (name)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Running Jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sidekiq_running_jobs_count{name!~\"(ActiveJob|Devise).*\", environment=\"$environment\"} and on (fqdn) gitlab:redis_master",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{name}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Job Failures and Errors (mtail)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "rate of Job failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(sidekiq_jobs_returned_to_redis_total[5m]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Jobs returned to Redis",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(rate(sidekiq_jobs_failed_total[5m]))",
       "legendFormat": "Failed jobs"
      }
     ]
    },
    {
     "title": "Rate of Worker Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(sidekiq_worker_ooms_total[5m]))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Worker OOMs",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(rate(sidekiq_workers_terminated_total[5m])) by (worker)",
       "legendFormat": "{{worker}} Terminated"
      }
     ]
    }
   ]
  },
  { "title": "Job completion times (mtail)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Job completion times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(sidekiq_jobs_completion_time_seconds_bucket[5m])) by (le))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "50th percentile",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(sidekiq_jobs_completion_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(sidekiq_jobs_completion_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Job completion time -  p95",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(sidekiq_jobs_completion_time_seconds_bucket[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job completion time -  p99",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sidekiq_jobs_completion_time_seconds_bucket[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}