{
 "title": "sidekiq: Loose Foreign Keys Processing",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4166130002 at Mon Apr 24 13:28:11 UTC 2023",
 "tags": [
  "managed",
  "sidekiq",
  "sidekiq",
  "stage_group:Sharding"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "LooseForeignKeys::CleanupWorker runtime",
   "type": "graph",
   "description": "How long it took for the worker to finish running. Higher is worse.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Duration (seconds)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_completion_seconds_sum{env=\"$environment\",worker=\"LooseForeignKeys::CleanupWorker\"}[$__interval]))",
     "legendFormat": "Total runtime"
    },
    {
     "expr": "sum(rate(sidekiq_jobs_db_seconds_sum{env=\"$environment\",worker=\"LooseForeignKeys::CleanupWorker\"}[$__interval]))",
     "legendFormat": "DB runtime"
    }
   ]
  },
  {
   "title": "Processed deleted parent rows by table",
   "type": "graph",
   "description": "How many deleted parents were processed over a time range by parent table. Higher means many deletes were occurring and being processed by the worker. A spike in this could be caused by a surge of deletes from a user.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loose_foreign_key_processed_deleted_records{env=\"$environment\"}[$__interval])) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Processed deleted child rows by table",
   "type": "graph",
   "description": "How many child records were deleted over a time range by child table. Higher means many deletes were occurring and being processed by the worker. A spike in this could be caused by a surge of parent deletions from a user or a small number of deletes that cascaded to many child deletions.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loose_foreign_key_deletions{env=\"$environment\"}[$__interval])) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Processed updated child rows by table",
   "type": "graph",
   "description": "How many child records were updated (nullified) over a time range by child table. Higher means many updates were occurring and being processed by the worker. A spike in this could be caused by a surge of parent deletions from a user or a small number of deletes that cascaded to many child updates.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loose_foreign_key_updates{env=\"$environment\"}[$__interval])) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  }
 ]
}