{
 "title": "sidekiq: Kube Deployment Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5094267319 at Thu Sep 14 20:56:50 UTC 2023",
 "tags": [
  "managed",
  "sidekiq",
  "sidekiq",
  "type:sidekiq",
  "kube",
  "kube detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  { "title": "sidekiq-catchall deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "sidekiq-catchall Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-catchall Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-catchall Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-catchall\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-database-throttled deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "sidekiq-database-throttled Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-database-throttled Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-database-throttled Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-database-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-elasticsearch deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "sidekiq-elasticsearch Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-elasticsearch Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-elasticsearch Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-elasticsearch\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-gitaly-throttled deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "sidekiq-gitaly-throttled Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-gitaly-throttled Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-gitaly-throttled Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-gitaly-throttled\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-low-urgency-cpu-bound deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 }
  },
  {
   "title": "sidekiq-low-urgency-cpu-bound Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-low-urgency-cpu-bound Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-low-urgency-cpu-bound Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-low-urgency-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-memory-bound deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 }
  },
  {
   "title": "sidekiq-memory-bound Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-memory-bound Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-memory-bound Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-memory-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  { "title": "sidekiq-quarantine deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "sidekiq-quarantine Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-quarantine Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 104 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-quarantine Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 104 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-quarantine\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-authorized-projects deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 }
  },
  {
   "title": "sidekiq-urgent-authorized-projects Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-authorized-projects Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 120 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-authorized-projects Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 120 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-authorized-projects\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-cpu-bound deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 }
  },
  {
   "title": "sidekiq-urgent-cpu-bound Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-cpu-bound Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 136 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-cpu-bound Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 136 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-cpu-bound\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-other deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 }
  },
  {
   "title": "sidekiq-urgent-other Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-other Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 152 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "sidekiq-urgent-other Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 152 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"sidekiq-urgent-other\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "Node CPU Requests Utilization",
   "type": "graph",
   "description": "Ratio of requested CPU resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by memory requests already.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n  kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",resource=\"cpu\"}\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node Memory Requests Utilization",
   "type": "graph",
   "description": "Ratio of requested Memory resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by CPU requests already.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n  kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"}\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"sidekiq\",resource=\"memory\"}\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}