{
 "title": "sidekiq: Priority Detail",
 "tags": [
  "managed",
  "sidekiq",
  "type:sidekiq",
  "detail"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "priority",
    "query": "label_values(up{environment=\"$environment\", type=\"sidekiq\", job=\"gitlab-sidekiq\"}, priority)"
   }
  ]
 },
 "panels": [
  { "title": "Sidekiq Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "Sidekiq Total Execution Time for Priority",
   "type": "graph",
   "description": "The sum of job execution times",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "s", "label": "Job time completed per second" }
   ],
   "targets": [
    {
     "expr": "\n        sum(rate(sidekiq_jobs_completion_time_seconds_sum{environment=\"$environment\", priority=~\"$priority\"}[$__interval])) by (priority)\n      ",
     "legendFormat": "{{ priority }}"
    }
   ]
  },
  {
   "title": "Sidekiq Aggregated Throughput for Priority",
   "type": "graph",
   "description": "The total number of jobs being completed",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "short", "label": "Jobs Completed per Second" }
   ],
   "targets": [
    {
     "expr": "\n        sum(worker:sidekiq_jobs_completion:rate1m{environment=\"$environment\", priority=~\"$priority\"}) by (priority)\n      ",
     "legendFormat": "{{ priority }}"
    }
   ]
  },
  {
   "title": "Sidekiq Throughput per Job for Priority",
   "type": "graph",
   "description": "The total number of jobs being completed per priority",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "short", "label": "Jobs Completed per Second" }
   ],
   "targets": [
    {
     "expr": "\n        sum(worker:sidekiq_jobs_completion:rate1m{environment=\"$environment\", priority=~\"$priority\"}) by (worker)\n      ",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Sidekiq Estimated Median Job Latency for priority",
   "type": "graph",
   "description": "The median duration, once a job starts executing, that it runs for, by priority. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "\n        avg(priority:sidekiq_jobs_completion_time_seconds:p50{environment=\"$environment\", priority=~\"$priority\"}) by (priority)\n      ",
     "legendFormat": "{{ priority }}"
    }
   ]
  },
  {
   "title": "Sidekiq Estimated p95 Job Latency for priority",
   "type": "graph",
   "description": "The 95th percentile duration, once a job starts executing, that it runs for, by priority. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1021 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "\n        avg(priority:sidekiq_jobs_completion_time_seconds:p95{environment=\"$environment\", priority=~\"$priority\"}) by (priority)\n      ",
     "legendFormat": "{{ priority }}"
    }
   ]
  },
  { "title": "Priority Workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Node Average CPU Utilization per Priority",
   "type": "graph",
   "description": "The maximum utilization of a single core on each node. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2001 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(\n          avg(1 - rate(node_cpu_seconds_total{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\", mode=\"idle\"}[$__interval])) by (priority)\n        ,1),0)",
     "legendFormat": "{{ priority }}"
    }
   ]
  },
  {
   "title": "Node Maximum Single Core Utilization per Priority",
   "type": "graph",
   "description": "The maximum utilization of a single core on each node. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2001 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(\n          max(1 - rate(node_cpu_seconds_total{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\", mode=\"idle\"}[$__interval])) by (priority)\n        ,1),0)",
     "legendFormat": "{{ priority }}"
    }
   ]
  },
  {
   "title": "Maximum Memory Utilization per Priority",
   "type": "graph",
   "description": "Memory utilization. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(\n          max(\n            1 -\n            (\n              (\n                node_memory_MemFree_bytes{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"} +\n                node_memory_Buffers_bytes{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"} +\n                node_memory_Cached_bytes{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"}\n              )\n            )\n            /\n            node_memory_MemTotal_bytes{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"}\n          ) by (priority)\n        ,1),0)",
     "legendFormat": "{{ priority }}"
    }
   ]
  },
  {
   "title": "Rails Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 },
   "collapsed": true,
   "panels": [
    {
     "title": "p95 Latency Estimate",
     "type": "graph",
     "description": "95th percentile Latency. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "\n        histogram_quantile(0.90,\n          sum(job_environment:gitlab_transaction_duration_seconds_bucket:rate5m{\n            environment=\"$environment\",\n            type=\"sidekiq\",\n            stage=\"$stage\"\n          }) by (le, job)\n        )\n      ",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Rails Total Time",
     "type": "graph",
     "description": "Seconds of Rails processing, per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "\n        sum(\n          job_environment:gitlab_transaction_duration_seconds_sum:rate1m{\n            environment=\"$environment\",\n            type=\"sidekiq\",\n            stage=\"$stage\"}\n        ) by (job)\n      ",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Rails Queue Time",
     "type": "graph",
     "description": "Time spend waiting for a rails worker",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "\n        sum(\n          rate(\n            gitlab_transaction_rails_queue_duration_total{\n              environment=\"$environment\",\n              type=\"sidekiq\",\n              stage=\"$stage\"}\n              [$__interval]\n          )\n        ) by (job)\n      ",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Total SQL Time",
     "type": "graph",
     "description": "Total seconds spent doing SQL processing, per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "\n        sum(\n          job_environment:gitlab_sql_duration_seconds_bucket:rate1m{\n            environment=\"$environment\",\n            type=\"sidekiq\",\n            stage=\"$stage\"}\n        ) by (job)\n      ",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Cache Operations",
     "type": "graph",
     "description": "Cache Operations per Second",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "\n        sum(\n          rate(\n            gitlab_cache_operations_total{\n              environment=\"$environment\",\n              type=\"sidekiq\",\n              stage=\"$stage\"}[$__interval]\n          )\n        ) by (job)\n      ",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "gitlab-rails Process restarts",
     "type": "graph",
     "description": "The number of times this process restarted in a given period, including children workers. Restarts are associated with poor client experience, so lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Process restarts" }
     ],
     "targets": [
      {
       "expr": "\n        sum(\n          changes(\n            ruby_process_start_time_seconds{\n              environment=\"$environment\",\n              type=\"sidekiq\",\n              stage=\"$stage\",\n              job=\"gitlab-rails\"\n            }[$__interval]\n          )\n        )\n      ",
       "legendFormat": "process restarts"
      }
     ]
    },
    {
     "title": "Database load balancer: average secondary connections per client",
     "type": "graph",
     "description": "This graph shows the average number of secondary database connections\n        per process. A value of zero indicates that the secondary replicas are unreachable.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "Average connections" }
     ],
     "targets": [
      {
       "expr": "\n        avg(\n          avg_over_time(\n            db_load_balancing_hosts{\n              environment=\"$environment\",\n              type=\"sidekiq\",\n              stage=\"$stage\"}[$__interval]\n          )\n        ) by (job)\n      ",
       "legendFormat": "{{ job }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "x": 0, "y": 6000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "\n            avg(instance:node_cpu_utilization:ratio{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"}) by (fqdn)\n            ",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(\n          max(1 - rate(node_cpu_seconds_total{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\", mode=\"idle\"}[$__interval])) by (fqdn)\n        ,1),0)",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "\n          sum(rate(node_network_transmit_bytes_total{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"}[$__interval])) by (fqdn)\n          ",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "\n          sum(rate(node_network_receive_bytes_total{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"}[$__interval])) by (fqdn)\n          ",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(\n        1 -\n        (\n          (\n            node_memory_MemFree_bytes{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"} +\n            node_memory_Buffers_bytes{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"} +\n            node_memory_Cached_bytes{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"}\n          )\n        )\n        /\n        node_memory_MemTotal_bytes{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"}\n      ,1),0)",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "\n        max(\n          rate(node_disk_reads_completed_total{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"}[$__interval])\n        ) by (fqdn)\n      ",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "\n        max(\n          rate(node_disk_read_bytes_total{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"}[$__interval])\n        ) by (fqdn)\n      ",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "\n        max(\n          rate(node_disk_writes_completed_total{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"}[$__interval])\n        ) by (fqdn)\n      ",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "\n        max(\n          rate(node_disk_written_bytes_total{type=\"sidekiq\", environment=\"$environment\", stage=\"$stage\", priority=~\"$priority\"}[$__interval])\n        ) by (fqdn)\n      ",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "📆 Capacity Planning",
   "type": "row",
   "gridPos": { "x": 0, "y": 7000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Saturation",
     "type": "bargauge",
     "description": "Resource Saturation. Lower is better.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "sort(\n          clamp_min(\n            clamp_max(\n              max(\n                gitlab_component_saturation:ratio:avg_over_time_1w{environment=\"$environment\", type=\"sidekiq\", stage=~\"|$stage\"}\n                + 2 * gitlab_component_saturation:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"sidekiq\", stage=~\"|$stage\"}\n              ) by (component),\n            1),\n          0)\n        )",
       "legendFormat": "{{ component }}"
      }
     ]
    },
    {
     "title": "14d Saturation Forecast (likely worst-case)",
     "type": "bargauge",
     "description": "Resource Saturation predictions for 14d from now. Lower is better.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sort(\n          clamp_min(\n            clamp_max(\n              max(\n                gitlab_component_saturation:ratio:predict_linear_2w{environment=\"$environment\", type=\"sidekiq\", stage=~\"|$stage\"}\n                + 2 * gitlab_component_saturation:ratio:stddev_over_time_1w{environment=\"$environment\", type=\"sidekiq\", stage=~\"|$stage\"}\n              ) by (component),\n            1),\n          0)\n        )",
       "legendFormat": "{{ component }}"
      }
     ]
    },
    {
     "title": "Long-term Resource Saturation",
     "type": "graph",
     "description": "Resource saturation levels for saturation components for this service. Lower is better.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(\n          max(\n            gitlab_component_saturation:ratio{\n              type=\"sidekiq\",\n              environment=\"$environment\",\n              stage=~\"|$stage\"\n            }\n          ) by (component)\n          ,1),0)\n        ",
       "legendFormat": "{{ component }}"
      }
     ]
    },
    {
     "title": "Long-term Resource Saturation - Rolling 1w average trend",
     "type": "graph",
     "description": "Percentage of time that resource is within capacity SLOs. Higher is better.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n          clamp_max(\n            max(\n              gitlab_component_saturation:ratio:avg_over_time_1w{\n                type=\"sidekiq\",\n                environment=\"$environment\",\n                stage=~\"$stage|\"\n              }\n            ) by (component)\n          ,1),0)\n        ",
       "legendFormat": "{{ component }}"
      }
     ]
    }
   ]
  }
 ]
}