{
 "title": "Sitespeed - Chrome User Experience Report",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "sitespeed_io" },
   { "name": "path", "query": "$base.*" },
   { "name": "group", "label": "domain", "query": "$base.$path.pageSummary.*" },
   {
    "name": "page",
    "query": "$base.$path.pageSummary.$group.*"
   },
   {
    "name": "formFactor",
    "label": "Form Factor",
    "query": "$base.$path.pageSummary.$group.$page.crux.loadingExperience.*"
   }
  ]
 },
 "panels": [
  { "title": "CrUX data for page $group$page", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.p75, 'First Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.p75, 'Largest Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.p75, 'First Input Delay')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.p75, 'Cumulative Layout Shift')"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.slow, 100), 9)"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.p75, 'First Contentful Paint')"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.p75, 'Largest Contentful Paint')"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.p75, 'First Input Delay')"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.crux.loadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.p75, 'Cumulative Layout Shift')"
    }
   ]
  },
  { "title": "CrUX data for origin $group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.p75, 'First Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.p75, 'Largest Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.p75, 'First Input Delay')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.p75, 'Cumulative Layout Shift')"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.fast, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.moderate, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.slow, 100), 8)"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.fast, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.moderate, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.slow, 100), 8)"
    }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.fast, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.moderate, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.slow, 100), 8)"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.fast, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.moderate, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.slow, 100), 8)"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.fast, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.moderate, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.slow, 100), 8)"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.fast, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.moderate, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.slow, 100), 8)"
    }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.fast, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.moderate, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.slow, 100), 8)"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.fast, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.moderate, 100), 8)"
    },
    {
     "target": "aliasByNode(scale($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.slow, 100), 8)"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_CONTENTFUL_PAINT_MS.p75, 'First Contentful Paint')"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.LARGEST_CONTENTFUL_PAINT_MS.p75, 'Largest Contentful Paint')"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.FIRST_INPUT_DELAY_MS.p75, 'First Input Delay')"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.crux.originLoadingExperience.$formFactor.CUMULATIVE_LAYOUT_SHIFT_SCORE.p75, 'Cumulative Layout Shift')"
    }
   ]
  }
 ]
}