{
 "title": "Sitespeed - Plus1",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "sitespeed_io" },
   { "name": "path", "query": "$base.*" },
   { "name": "group", "label": "domain", "query": "$base.$path.pageSummary.*" },
   {
    "name": "page",
    "query": "$base.$path.pageSummary.$group.*"
   },
   { "name": "type", "label": "GPSI type", "query": "mobile,desktop" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "Use the +1 container to get metrics from Lighthouse and GPSI",
   "targets": [
    {}
   ]
  },
  {
   "title": "Lighthouse Score",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.lighthouse.categories.*.score, 100), 7)"
    }
   ]
  },
  {
   "title": "GPSI Score",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.gpsi.$type.score.*, 8)"
    }
   ]
  },
  {
   "title": "First Input Delay",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_INPUT_DELAY_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_INPUT_DELAY_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_INPUT_DELAY_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "First Contentful Paint",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_CONTENTFUL_PAINT_MS.fast, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_CONTENTFUL_PAINT_MS.moderate, 100), 9)"
    },
    {
     "target": "aliasByNode(scale($base.$path.pageSummary.$group.$page.gpsi.$type.loadingExperience.FIRST_CONTENTFUL_PAINT_MS.slow, 100), 9)"
    }
   ]
  },
  {
   "title": "Loading experience percentile",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.gpsi.$type.loadingExperience.*.percentile, 8)"
    }
   ]
  }
 ]
}