{
 "title": "Sitespeed - Site summary",
 "tags": [ "site summary" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "sitespeed_io" },
   { "name": "path", "query": "$base.*" },
   { "name": "group", "label": "domain", "query": "$base.$path.summary.*" },
   { "name": "browser", "query": "$base.$path.summary.$group.*" },
   {
    "name": "connectivity",
    "query": "$base.$path.summary.$group.$browser.*"
   },
   { "name": "function", "query": "min, mean,median,p90,max" }
  ]
 },
 "panels": [
  { "title": "Visual Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "First Visual Change",
   "type": "graph",
   "description": "The first visual change is when something for the first time is painted within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.FirstVisualChange.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.FirstVisualChange.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.FirstVisualChange.min)"
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "graph",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan and you can checkout the full documentation [here](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.SpeedIndex.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.SpeedIndex.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.SpeedIndex.min)"
    }
   ]
  },
  {
   "title": "Largest image",
   "type": "graph",
   "description": "The largest image is the time when the largest image within the viewport is painted and on its final position. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.LargestImage.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.LargestImage.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.LargestImage.min)"
    }
   ]
  },
  {
   "title": "Last Visual Change",
   "type": "graph",
   "description": "The last visual change is when something for the last time is changing within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.LastVisualChange.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.LastVisualChange.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.LastVisualChange.min)"
    }
   ]
  },
  { "title": "Visual Metrics [$function]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "First Visual Change",
   "type": "singlestat",
   "description": "The first visual change is when something for the first time is painted within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.FirstVisualChange.$function"
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "singlestat",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan and you can checkout the full documentation [here](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index).",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.SpeedIndex.$function"
    }
   ]
  },
  {
   "title": "Perceptual Speed Index",
   "type": "singlestat",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan and you can checkout the full documentation [here](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index).",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.PerceptualSpeedIndex.$function"
    }
   ]
  },
  {
   "title": "Visual Complete 85%",
   "type": "singlestat",
   "description": "The last visual change is when something for the last time is changing within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.VisualComplete85.$function"
    }
   ]
  },
  {
   "title": "Last Visual Change",
   "type": "singlestat",
   "description": "The last visual change is when something for the last time is changing within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.LastVisualChange.$function"
    }
   ]
  },
  {
   "title": "Visual Metrics all pages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Visual Change",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "target": "aliasByNode(sitespeed_io.$path.pageSummary.$group.*.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 3, 4)"
      }
     ]
    },
    {
     "title": "Speed Index",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "target": "aliasByNode(sitespeed_io.$path.pageSummary.$group.*.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, 3, 4)"
      }
     ]
    }
   ]
  },
  {
   "title": "History Visual Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "History First Visual Change [$function]",
     "type": "graph",
     "description": "The history of First Visual Change (when something for the first time is painted within the current viewport) showing the current median value, the average median per day and the average median per week for all tested pages.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.FirstVisualChange.$function, 9)"
      },
      {
       "target": "alias(summarize($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.FirstVisualChange.$function, '24h', 'avg', false), 'Daily')"
      },
      {
       "target": "alias(summarize($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.FirstVisualChange.$function, '7d', 'avg', false), 'Weekly')"
      }
     ]
    },
    {
     "title": "History Speed Index  [$function]",
     "type": "graph",
     "description": "The history of [Speed Index](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index) showing the current median value, the average median per day and the average median per week for all tested pages.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.SpeedIndex.$function, 9)"
      },
      {
       "target": "alias(summarize($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.SpeedIndex.$function, '24h', 'avg', false), 'Daily')"
      },
      {
       "target": "alias(summarize($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.SpeedIndex.$function, '7d', 'avg', false), 'Weekly')"
      }
     ]
    },
    {
     "title": "History Visual Complete 85%  [$function]",
     "type": "graph",
     "description": "The history of Visual Complete 85%  (when 85% or more is ready within the current viewport) showing the current median value, the average median per day and the average median per week for all tested pages.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.VisualComplete85.$function, 9)"
      },
      {
       "target": "alias(summarize($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.VisualComplete85.$function, '24h', 'avg', false), 'Daily')"
      },
      {
       "target": "alias(summarize($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.VisualComplete85.$function, '7d', 'avg', false), 'Weekly')"
      }
     ]
    },
    {
     "title": "History Last Visual Change [$function]",
     "type": "graph",
     "description": "The history of Last Visual Change (when something for the last time is changing within the current viewport) showing the current median value, the average median per day and the average median per week for all tested pages.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.LastVisualChange.$function, 9)"
      },
      {
       "target": "alias(summarize($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.LastVisualChange.$function, '24h', 'avg', false), 'Daily')"
      },
      {
       "target": "alias(summarize($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.LastVisualChange.$function, '7d', 'avg', false), 'Weekly')"
      }
     ]
    },
    {
     "title": "History Fully Loaded  [$function]",
     "type": "graph",
     "description": "The history of Fully Loaded (when the last of all assets is downloaded on the page) showing the current median value, the average median per day and the average median per week for all tested pages.",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.summary.$group.$browser.$connectivity.browsertime.fullyLoaded.$function, 8)"
      },
      {
       "target": "alias(summarize($base.$path.summary.$group.$browser.$connectivity.browsertime.fullyLoaded.$function, '24h', 'avg', false), 'Daily')"
      },
      {
       "target": "alias(summarize($base.$path.summary.$group.$browser.$connectivity.browsertime.fullyLoaded.$function, '7d', 'avg', false), 'Weekly')"
      }
     ]
    }
   ]
  },
  { "title": "CPU Long Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Number of CPU Long Tasks",
   "type": "graph",
   "description": "The average number of CPU Long Tasks per page. A CPU long Task is by default a CPU task that takes longer than 50 ms to run. This metrics is Chrome only at the moment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.longTasks.tasks.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.longTasks.tasks.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.longTasks.tasks.min)"
    }
   ]
  },
  {
   "title": "CPU Long Tasks total duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.longTasks.totalDuration.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.longTasks.totalDuration.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.longTasks.totalDuration.min)"
    }
   ]
  },
  { "title": "CPU Time Spent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Script evaluation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.scriptEvaluation.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.scriptEvaluation.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.scriptEvaluation.min)"
    }
   ]
  },
  {
   "title": "Script parse compile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.scriptParseCompile.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.scriptParseCompile.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.scriptParseCompile.min)"
    }
   ]
  },
  {
   "title": "Paint composite render",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.paintCompositeRender.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.paintCompositeRender.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.paintCompositeRender.min)"
    }
   ]
  },
  {
   "title": "Style Layout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.styleLayout.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.styleLayout.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.cpu.categories.styleLayout.min)"
    }
   ]
  },
  { "title": "Technical Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.pagexray.requests.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.pagexray.requests.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.pagexray.requests.min)"
    }
   ]
  },
  {
   "title": "Total page transfer size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.pagexray.transferSize.median)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.pagexray.transferSize.max)"
    },
    {
     "target": "aliasByMetric(sitespeed_io.$path.summary.$group.$browser.$connectivity.pagexray.transferSize.min)"
    }
   ]
  },
  { "title": "Technical Metrics [$function]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Requests",
   "type": "singlestat",
   "description": "The $function number of requests for all the analyzed pages.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.requests.$function"
    }
   ]
  },
  {
   "title": "Total transfer size",
   "type": "singlestat",
   "description": "The $function total transfer size over the wire (compressed size if your asset is compressed) of all assets on a page.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 59 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.transferSize.$function"
    }
   ]
  },
  {
   "title": "Coach score",
   "type": "singlestat",
   "description": "The $function total score from the [Coach](https://www.sitespeed.io/documentation/coach/) for all tested pages.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.coach.score.$function"
    }
   ]
  },
  {
   "title": "Performance score",
   "type": "singlestat",
   "description": "The $function performance score from the [Coach](https://www.sitespeed.io/documentation/coach/) for all tested pages.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.coach.performance.score.$function"
    }
   ]
  },
  {
   "title": "Response expire time",
   "type": "singlestat",
   "description": "The $function value for the response expire time of all assets. Compare this with the $function last modified $function value to understand how good you configured the cache settings on your site.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 59 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.expireStats.$function"
    }
   ]
  },
  {
   "title": "Last modified time",
   "type": "singlestat",
   "description": "The $function value for the last modified time of all assets. Compare this with the $function cache time to know how smart you have configured the cache settings.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 59 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.lastModifiedStats.$function"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Image requests",
   "type": "singlestat",
   "description": "The $function number of image requests for all the analyzed pages.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 63 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.image.requests.$function"
    }
   ]
  },
  {
   "title": "Images transfer size",
   "type": "singlestat",
   "description": "The $function transfer size over the wire of all images on all analyzed page.",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 63 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.image.contentSize.$function"
    }
   ]
  },
  {
   "title": "Largest image size",
   "type": "singlestat",
   "description": "The size of the largest image on all the analyzed pages.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 63 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.largestassets.image.0.transferSize"
    }
   ]
  },
  {
   "title": "Domains",
   "type": "singlestat",
   "description": "The $function number of domains used for all the analyzed pages.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 63 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.domains.$function"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Backend time",
   "type": "singlestat",
   "description": "The  $function backend time is the  $function time it takes for the network and the server to generate and start sending the HTML for all the analyzed pages. It is collected using the Navigation Timing API taking the responseStart minus navigationStart.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 67 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.backEndTime.$function"
    }
   ]
  },
  {
   "title": "Frontend time",
   "type": "singlestat",
   "description": "The frontend $function time is the time it takes for the browser to parse and create the page.  It is collected using the Navigation Timing API by taking the loadEventStart minus responseEnd.",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 67 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.frontEndTime.$function"
    }
   ]
  },
  {
   "title": "JavaScript requests",
   "type": "singlestat",
   "description": "The $function number of JavaScript requests for all the analyzed pages.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 67 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.javascript.requests.$function"
    }
   ]
  },
  {
   "title": "CSS requests",
   "type": "singlestat",
   "description": "The $function number of CSS requests for all the analyzed pages.",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 67 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.css.requests.$function"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Summary Navigation Timings [$function]",
   "type": "graph",
   "description": "[Navigation Timing API](https://www.w3.org/TR/navigation-timing/) metrics.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.*.$function, 8)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Time spent in backend vs frontend [$function]",
   "type": "graph",
   "description": "The max time spent in frontend vs backend time. \n\nThe backend time is the time it takes for the network and the server to generate and start sending the HTML. It is collected using the Navigation Timing API taking the responseStart minus navigationStart.\n\nThe frontend time is the time it takes for the browser to parse and create the page.  It is collected using the Navigation Timing API by taking the loadEventStart minus responseEnd.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.backEndTime.$function, #C), 'Backend')",
     "targetFull": "alias(asPercent($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.backEndTime.$function, sumSeries($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.backEndTime.median,$base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.frontEndTime.median)), 'Backend')"
    },
    {
     "target": "alias(asPercent($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.frontEndTime.$function, #C), 'Frontend')",
     "targetFull": "alias(asPercent($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.frontEndTime.$function, sumSeries($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.backEndTime.median,$base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.frontEndTime.median)), 'Frontend')"
    }
   ]
  },
  {
   "title": "Response codes [$function]",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.summary.$group.$browser.$connectivity.pagexray.responseCodes.*.$function, 8)"
    }
   ]
  },
  {
   "title": "1st vs 3rd party (enable by --firstParty REGEX)  [$function]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }
  },
  {
   "title": "First party size",
   "type": "singlestat",
   "description": "The $function transfer size of all your first party responses.  \n\nThe first party content (content you serve your self ) are defined by the requests that  match the regexp you supply with the parameter *--firstParty*",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 96 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.firstParty.contentSize.$function"
    }
   ]
  },
  {
   "title": "Third party size",
   "type": "singlestat",
   "description": "The $function transfer size of all your third party responses.  \n\nThe third party content (content other companies/organizations serve like advertisement, social media buttons etc) are defined by the requests that doesn't match the regexp you supply with the parameter *--firstParty*",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 96 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.thirdParty.contentSize.$function"
    }
   ]
  },
  {
   "title": "First party requests",
   "type": "singlestat",
   "description": "The $function number of requests for all your first party responses.  \n\nThe first party content (content you serve your self ) are defined by the requests that match the regexp you supply with the parameter *--firstParty*",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 96 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.firstParty.requests.$function"
    }
   ]
  },
  {
   "title": "Third party requests",
   "type": "singlestat",
   "description": "The $function number of requests for all your third party responses.  \n\nThe third party content (content other companies/organizations serve like advertisement, social media buttons etc) are defined by the requests that doesn't match the regexp you supply with the parameter *--firstParty*",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 96 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.thirdParty.requests.$function"
    }
   ]
  },
  {
   "title": "Transfer and content size  [$function]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 }
  },
  {
   "title": "Total transfer size",
   "type": "singlestat",
   "description": "The $function total size over the wire for all assets served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 100 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.transferSize.$function"
    }
   ]
  },
  {
   "title": "Total content size",
   "type": "singlestat",
   "description": "The $function total size for all assets served for this page. This includes the uncompressed size for compressed text/css/html/js/font content.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 100 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentSize.$function"
    }
   ]
  },
  {
   "title": "Total CSS transfer size",
   "type": "singlestat",
   "description": "The $function total size over the wire for all stylesheet assets served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 100 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.css.transferSize.$function"
    }
   ]
  },
  {
   "title": "Total CSS content size",
   "type": "singlestat",
   "description": "The $function total size for stylesheets assets served for this page. This includes the uncompressed size of CSS responses.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 100 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.css.contentSize.$function"
    }
   ]
  },
  {
   "title": "Total JS transfer size",
   "type": "singlestat",
   "description": "The $function total size over the wire for all Javascript assets served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 100 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.javascript.transferSize.$function"
    }
   ]
  },
  {
   "title": "Total JS content size",
   "type": "singlestat",
   "description": "The $function total size for Javascripts assets served for this page. This includes the uncompressed size of JS responses.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 100 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.javascript.contentSize.$function"
    }
   ]
  },
  {
   "title": "Total HTML transfer size",
   "type": "singlestat",
   "description": "The $function total size over the wire for all HTML served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 103 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.html.transferSize.$function"
    }
   ]
  },
  {
   "title": "Total HTML content size",
   "type": "singlestat",
   "description": "The $function total size for HTML served for this page. This includes the uncompressed size of HTML responses.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 103 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.html.contentSize.$function"
    }
   ]
  },
  {
   "title": "Total font transfer size",
   "type": "singlestat",
   "description": "The $function total size over the wire for all font responses served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 103 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.font.transferSize.$function"
    }
   ]
  },
  {
   "title": "Total font content size",
   "type": "singlestat",
   "description": "The $function total size for font responses served for this page. This includes the uncompressed size of font responses.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 103 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.font.contentSize.$function"
    }
   ]
  },
  {
   "title": "Total image size",
   "type": "singlestat",
   "description": "The $function total size over the wire for all image responses served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 103 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.image.transferSize.$function"
    }
   ]
  },
  {
   "title": "Total SVG  transfer size",
   "type": "singlestat",
   "description": "The $function total size over the wire for all SVG responses served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 103 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "$base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.svg.transferSize.$function"
    }
   ]
  }
 ]
}