{
 "title": "skarbek: sidekiq: Shard Detail Copy",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/671036373 at Tue Aug  4 20:46:09 UTC 2020",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "shard",
    "query": "label_values(up{environment=\"$environment\", type=\"sidekiq\"}, shard)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queue Lengths - number of jobs queued",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Queue Lengths",
   "type": "graph",
   "description": "The number of unstarted jobs in queues serviced by this shard",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum by (queue) (\n  (\n    label_replace(\n      sidekiq_queue_size{environment=\"$environment\"} and on(fqdn) (redis_connected_slaves != 0),\n      \"queue\", \"$0\", \"name\", \".*\"\n    )\n  )\n  and on (queue)\n  (\n    max by (queue) (\n      rate(sidekiq_jobs_queue_duration_seconds_sum{environment=\"$environment\", shard=~\"$shard\"}[$__range]) > 0\n    )\n  )\n)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Aggregate queue length",
   "type": "graph",
   "description": "The sum total number of unstarted jobs in all queues serviced by this shard",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Jobs" }
   ],
   "targets": [
    {
     "expr": "sum(\n  (\n    label_replace(\n      sidekiq_queue_size{environment=\"$environment\"} and on(fqdn) (redis_connected_slaves != 0),\n      \"queue\", \"$0\", \"name\", \".*\"\n    )\n  )\n  and on (queue)\n  (\n    max by (queue) (\n      rate(sidekiq_jobs_queue_duration_seconds_sum{environment=\"$environment\", shard=~\"$shard\"}[$__range]) > 0\n    )\n  )\n)\n",
     "legendFormat": "Aggregated queue length"
    }
   ]
  },
  {
   "title": "Queue Time - time spend queueing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Sidekiq Estimated p95 Job Queue Time for $shard shard",
   "type": "graph",
   "description": "Estimated queue time, between when the job is enqueued and executed. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s", "label": "Queue Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sidekiq_jobs_queue_duration_seconds_bucket{environment=\"$environment\", shard=~\"$shard\"}[$__interval])) by (le, shard))\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Sidekiq Estimated p95 Job Queue Time per Queue, $shard shard",
   "type": "graph",
   "description": "Estimated queue time, between when the job is enqueued and executed. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s", "label": "Queue Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(sidekiq_jobs_queue_duration_seconds_bucket{environment=\"$environment\", shard=~\"$shard\"}[$__interval])) by (le, queue))\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Inflight Jobs - jobs currently running",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Sidekiq Inflight Jobs for $shard shard",
   "type": "graph",
   "description": "The total number of jobs being executed at a single moment for the shard",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_running_jobs{environment=\"$environment\", shard=~\"$shard\"}) by (shard)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Sidekiq Inflight Jobs per Queue, $shard shard",
   "type": "graph",
   "description": "The total number of jobs being executed at a single moment for the shard",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sidekiq_running_jobs{environment=\"$environment\", shard=~\"$shard\"}) by (queue)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Individual Execution Time - time taken for individual jobs to complete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "Sidekiq Estimated Median Job Latency for $shard shard",
   "type": "graph",
   "description": "The median duration, once a job starts executing, that it runs for, by shard. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum by (shard, le) (\n    rate(sidekiq_jobs_completion_seconds_bucket{\n      environment=\"$environment\",\n      shard=~\"$shard\"\n    }[$__interval])\n  )\n)\n",
     "legendFormat": "{{ shard }} p50"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum by (shard, le) (\n    rate(sidekiq_jobs_completion_seconds_bucket{\n      environment=\"$environment\",\n      shard=~\"$shard\"\n    }[$__interval])\n  )\n)\n",
     "legendFormat": "{{ shard }} p95"
    }
   ]
  },
  {
   "title": "Sidekiq Estimated p95 Job Latency per Queue, for $shard shard",
   "type": "graph",
   "description": "The 95th percentile duration, once a job starts executing, that it runs for, by shard. Lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum by (queue, le) (\n    rate(sidekiq_jobs_completion_seconds_bucket{\n      environment=\"$environment\",\n      shard=~\"$shard\"\n    }[$__interval])\n  )\n)\n",
     "legendFormat": "p95 {{ queue }}"
    }
   ]
  },
  {
   "title": "Total Execution Time - total time consumed processing jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }
  },
  {
   "title": "Sidekiq Total Execution Time for $shard Shard",
   "type": "graph",
   "description": "The sum of job execution times",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s", "label": "Job time completed per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_completion_seconds_sum{environment=\"$environment\", shard=~\"$shard\"}[$__interval])) by (shard)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Throughput - rate at which jobs complete",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }
  },
  {
   "title": "Sidekiq Aggregated Throughput for $shard Shard",
   "type": "graph",
   "description": "The total number of jobs being completed",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Jobs Completed per Second" }
   ],
   "targets": [
    {
     "expr": "sum(queue:sidekiq_jobs_completion:rate1m{environment=\"$environment\", shard=~\"$shard\"}) by (shard)\n",
     "legendFormat": "{{ shard }}"
    }
   ]
  },
  {
   "title": "Sidekiq Throughput per Queue for $shard Shard",
   "type": "graph",
   "description": "The total number of jobs being completed per queue for shard",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Jobs Completed per Second" }
   ],
   "targets": [
    {
     "expr": "sum(queue:sidekiq_jobs_completion:rate1m{environment=\"$environment\", shard=~\"$shard\"}) by (queue)\n",
     "legendFormat": "{{ queue }}"
    }
   ]
  },
  {
   "title": "Utilization - saturation of workers in this fleet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shard Utilization",
     "type": "graph",
     "description": "How heavily utilized is this shard? Ideally this should be around 33% plus minus 10%. If outside this range for long periods, consider scaling fleet appropriately.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(sum by (environment, stage, shard)  (rate(sidekiq_jobs_completion_seconds_sum{environment=\"$environment\", shard=~\"$shard\"}[1h]))\n/\nsum by (environment, stage, shard)  (avg_over_time(sidekiq_concurrency{environment=\"$environment\", shard=~\"$shard\"}[1h]))\n,1),0)\n",
       "legendFormat": "{{ shard }} utilization (per hour)"
      },
      {
       "expr": "sum by (environment, stage, shard)  (rate(sidekiq_jobs_completion_seconds_sum{environment=\"$environment\", shard=~\"$shard\"}[10m]))\n/\nsum by (environment, stage, shard)  (avg_over_time(sidekiq_concurrency{environment=\"$environment\", shard=~\"$shard\"}[10m]))\n",
       "legendFormat": "{{ shard }} utilization (per 10m)"
      },
      {
       "expr": "sum by (environment, stage, shard)  (rate(sidekiq_jobs_completion_seconds_sum{environment=\"$environment\", shard=~\"$shard\"}[$__interval]))\n/\nsum by (environment, stage, shard)  (avg_over_time(sidekiq_concurrency{environment=\"$environment\", shard=~\"$shard\"}[$__interval]))\n",
       "legendFormat": "{{ shard }} utilization (instant)"
      }
     ]
    }
   ]
  },
  {
   "title": "Rails Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "p95 Latency Estimate",
     "type": "graph",
     "description": "95th percentile Latency. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90,\n  sum(job_environment:gitlab_transaction_duration_seconds_bucket:rate5m{\n    environment=\"$environment\",\n    type=\"sidekiq\",\n    stage=\"$stage\"\n  }) by (le, job)\n)\n",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Rails Total Time",
     "type": "graph",
     "description": "Seconds of Rails processing, per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  job_environment:gitlab_transaction_duration_seconds_sum:rate1m{\n    environment=\"$environment\",\n    type=\"sidekiq\",\n    stage=\"$stage\"}\n) by (job)\n",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Rails Queue Time",
     "type": "graph",
     "description": "Time spend waiting for a rails worker",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(\n    gitlab_transaction_rails_queue_duration_total{\n      environment=\"$environment\",\n      type=\"sidekiq\",\n      stage=\"$stage\"}\n      [$__interval]\n  )\n) by (job)\n",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Total SQL Time",
     "type": "graph",
     "description": "Total seconds spent doing SQL processing, per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  job_environment:gitlab_sql_duration_seconds_bucket:rate1m{\n    environment=\"$environment\",\n    type=\"sidekiq\",\n    stage=\"$stage\"}\n) by (job)\n",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "Cache Operations",
     "type": "graph",
     "description": "Cache Operations per Second",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(\n    gitlab_cache_operations_total{\n      environment=\"$environment\",\n      type=\"sidekiq\",\n      stage=\"$stage\"}[$__interval]\n  )\n) by (job)\n",
       "legendFormat": "{{ job }}"
      }
     ]
    },
    {
     "title": "gitlab-rails Process restarts",
     "type": "graph",
     "description": "The number of times this process restarted in a given period, including children workers. Restarts are associated with poor client experience, so lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Process restarts" }
     ],
     "targets": [
      {
       "expr": "sum(\n  changes(\n    ruby_process_start_time_seconds{\n      environment=\"$environment\",\n      type=\"sidekiq\",\n      stage=\"$stage\",\n      job=\"gitlab-rails\"\n    }[$__interval]\n  )\n)\n",
       "legendFormat": "process restarts"
      }
     ]
    },
    {
     "title": "Database load balancer: average secondary connections per client",
     "type": "graph",
     "description": "This graph shows the average number of secondary database connections\n        per process. A value of zero indicates that the secondary replicas are unreachable.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "Average connections" }
     ],
     "targets": [
      {
       "expr": "avg(\n  avg_over_time(\n    db_load_balancing_hosts{\n      environment=\"$environment\",\n      type=\"sidekiq\",\n      stage=\"$stage\"}[$__interval]\n  )\n) by (job)\n",
       "legendFormat": "{{ job }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "avg(instance:node_cpu_utilization:ratio{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "sum(rate(node_network_receive_bytes_total{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(instance:node_memory_utilization:ratio{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_reads_completed_total{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_writes_completed_total{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_read_bytes_total{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_written_bytes_total{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Total Time",
     "type": "graph",
     "description": "Total time spent in read operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_read_time_seconds_total{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Total Time",
     "type": "graph",
     "description": "Total time spent in write operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_write_time_seconds_total{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg1 per core",
     "type": "graph",
     "description": "Loadavg (1 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "loadavg1" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, tier, stage, fqdn) (node_load1{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"})\n/\ncount by (environment, type, tier, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg5 per core",
     "type": "graph",
     "description": "Loadavg (5 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "loadavg5" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, tier, stage, fqdn) (node_load5{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"})\n/\ncount by (environment, type, tier, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg15 per core",
     "type": "graph",
     "description": "Loadavg (15 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg15" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, tier, stage, fqdn) (node_load15{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"})\n/\ncount by (environment, type, tier, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu component saturation: Average Service CPU Utilization",
     "type": "graph",
     "description": "This resource measures average CPU utilization across an all cores in a service fleet.\nIf it is becoming saturated, it may indicate that the fleet needs\nhorizontal or vertical scaling.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage) (\n  clamp_min(\n    clamp_max(\n      1 - avg by (environment, tier, type, stage) (\n        rate(node_cpu_seconds_total{mode=\"idle\", environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ type }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\", component=\"cpu\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "disk_space component saturation: Disk Space Utilization per Device per Node",
     "type": "graph",
     "description": "Disk space utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn, device) (\n  clamp_min(\n    clamp_max(\n      (\n        1 - instance:node_filesystem_avail:ratio{fstype=~\"ext.|xfs\", environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }} {{ device }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\", component=\"disk_space\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "memory component saturation: Memory Utilization per Node",
     "type": "graph",
     "description": "Memory utilization per device per node.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn) (\n  clamp_min(\n    clamp_max(\n      instance:node_memory_utilization:ratio{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\", component=\"memory\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "open_fds component saturation: Open file descriptor utilization per instance",
     "type": "graph",
     "description": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, job, instance) (\n  clamp_min(\n    clamp_max(\n      (\n        process_open_fds{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}\n        /\n        process_max_fds{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}\n      )\n      or\n      (\n        ruby_file_descriptors{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}\n        /\n        ruby_process_max_fds{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ job }} {{ instance }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\", component=\"open_fds\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "sidekiq_shard_workers component saturation: Sidekiq Worker Utilization per shard",
     "type": "graph",
     "description": "Sidekiq worker utilization per shard.\n\nThis metric represents the percentage of available threads*workers that are actively processing jobs.\n\nWhen this metric is saturated, new Sidekiq jobs will queue. Depending on whether or not the jobs are latency sensitive,\nthis could impact user experience.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, shard) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, shard) (\n        avg_over_time(sidekiq_running_jobs{shard!~\"database-throttled|elasticsearch|gitaly-throttled|memory-bound\", environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n      )\n      /\n      sum by (environment, tier, type, stage, shard) (\n        avg_over_time(sidekiq_concurrency{shard!~\"database-throttled|elasticsearch|gitaly-throttled|memory-bound\", environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[5m])\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ shard }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\", component=\"sidekiq_shard_workers\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"sidekiq_shard_workers\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"sidekiq_shard_workers\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "single_node_cpu component saturation: Average CPU Utilization per Node",
     "type": "graph",
     "description": "Average CPU utilization per Node.\n\nIf average CPU is satured, it may indicate that a fleet is in need to horizontal or vertical scaling. It may also indicate\nimbalances in load in a fleet.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn) (\n  clamp_min(\n    clamp_max(\n      avg without(cpu, mode) (1 - rate(node_cpu_seconds_total{mode=\"idle\", environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[5m]))\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\", component=\"single_node_cpu\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    },
    {
     "title": "single_node_puma_workers component saturation: Puma Worker Saturation per Node",
     "type": "graph",
     "description": "Puma thread utilization per node.\n\nPuma uses a fixed size thread pool to handle HTTP requests. This metric shows how many threads are busy handling requests. When this resource is saturated,\nwe will see puma queuing taking place. Leading to slowdowns across the application.\n\nPuma saturation is usually caused by latency problems in downstream services: usually Gitaly or Postgres, but possibly also Redis.\nPuma saturation can also be caused by traffic spikes.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, fqdn) (\n  clamp_min(\n    clamp_max(\n      sum by(environment, tier, type, stage, fqdn) (avg_over_time(puma_active_connections{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"}[1m]))\n      /\n      sum by(environment, tier, type, stage, fqdn) (puma_max_threads{pid=\"puma_master\", environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\"})\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ fqdn }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(\n        gitlab_component_saturation:ratio{environment=\"$environment\",shard=~\"$shard\",stage=\"$stage\",type=\"sidekiq\", component=\"single_node_puma_workers\"}[$__interval]\n      )\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_puma_workers\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_puma_workers\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  }
 ]
}