{
 "title": "skarbek - delivery#1592",
 "tags": [ "unmanaged" ],
 "time": { "from": "2021-05-21T00:00:00.000Z", "to": "2021-05-21T23:59:59.000Z" },
 "panels": [
  {
   "title": "API Pod Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_labels{label_type=~\"api\"}) by (region,type)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "NGINX Ingress Controller Pod Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_labels{label_app=\"nginx-ingress\"}) by (region,type)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "API Node Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_labels{label_type=~\"api\"}) by (region,type)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Default Node Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_labels{label_type=~\"default\"}) by (region,type)",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}