{
 "title": "skarbek testg",
 "tags": [
  "host",
  "drilldown"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(up{environment=\"$environment\"},fqdn)"
   },
   { "name": "environment", "label": "enivronment", "query": "gprd,gstg" },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"https://gitlab.com.*\", job=\"blackbox\"}"
      },
      {
       "expr": "probe_duration_seconds{instance=~\".*tree/master.*\"}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_command_call_duration_seconds_count{fqdn=~\"redis-cache-0.*\"}[1m])) by (cmd)",
       "legendFormat": "cache {{cmd}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_command_call_duration_seconds_count{fqdn=~\"redis-0.*\"}[1m])) by (cmd)",
       "legendFormat": "non-cache {{cmd}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(rate(node_cpu{fqdn=~\"$node\", mode!=\"idle\"}[$__interval])) by (mode, fqdn)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{fqdn }}: {{mode}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{fqdn=~\"$node\", mode!=\"idle\"}[$__interval])) by (mode, fqdn)",
       "legendFormat": "{{ fqdn }}: {{mode}}"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "cs p/s" }
     ],
     "targets": [
      {
       "expr": "rate(node_context_switches_total{fqdn=~\"$node\"}[$__interval])",
       "legendFormat": "{{ fqdn }} "
      }
     ]
    },
    {
     "title": "Load per CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(node_load1{fqdn=~\"$node\"}[$__interval]) / instance:node_cpus:count",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ fqdn }}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory Overview",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{fqdn=~\"$node\"} - node_memory_MemFree_bytes{fqdn=~\"$node\"} - node_memory_Buffers_bytes{fqdn=~\"$node\"} - node_memory_Cached_bytes{fqdn=~\"$node\"}",
       "legendFormat": "{{ fqdn }} Used"
      },
      {
       "expr": "node_memory_MemTotal_bytes{fqdn=~\"$node\"}",
       "legendFormat": "{{ fqdn }} Capacity"
      }
     ]
    },
    {
     "title": "Swap IO",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "increase(node_vmstat_pgpgin{fqdn=~\"$node\"}[$__interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "in",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "increase(node_vmstat_pgpgout{fqdn=~\"$node\"}[$__interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "out",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Page Faults",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgmajfault{fqdn=~\"$node\"}[$__interval])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Major Faults",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes{device!=\"lo\", fqdn=~\"$node\"}[$__interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "send {{device}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "rate(node_network_receive_bytes{device!=\"lo\", fqdn=~\"$node\"}[$__interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "receive {{device}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\", fqdn=~\"$node\"}[$__interval])",
       "legendFormat": "send {{device}}"
      },
      {
       "expr": "rate(node_network_receive_bytes_total{device!=\"lo\", fqdn=~\"$node\"}[$__interval])",
       "legendFormat": "receive {{device}}"
      }
     ]
    },
    {
     "title": "Total IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_reads_completed{fqdn=~\"$node\", device!~\"dm.*\"}[$__interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Reads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(rate(node_disk_writes_completed{fqdn=~\"$node\", device!~\"dm.*\"}[$__interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Writes",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(rate(node_disk_reads_completed_total{fqdn=~\"$node\", device!~\"dm.*\"}[$__interval]))",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum(rate(node_disk_writes_completed_total{fqdn=~\"$node\", device!~\"dm.*\"}[$__interval]))",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Total IO Wait",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_time_ms{fqdn=~\"$node\", device!~\"dm.*\"}[$__interval])) / 1000",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "read",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(rate(node_disk_write_time_ms{fqdn=~\"$node\", device!~\"dm.*\"}[$__interval])) / 1000",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "write",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum(rate(node_disk_read_time_seconds_total{fqdn=~\"$node\", device!~\"dm.*\"}[$__interval]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(node_disk_write_time_seconds_total{fqdn=~\"$node\", device!~\"dm.*\"}[$__interval]))",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Available Filesystem",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "instance:node_filesystem_avail:ratio{fqdn=~\"$node\", fstype=~\"ext.|xfs\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{mountpoint}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{fqdn=~\"$node\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "current connections",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Allocated file descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{fqdn=~\"$node\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Allocated",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "node_filefd_maximum{fqdn=~\"$node\"}",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  }
 ]
}