{
 "title": "skarbek - CR2986",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SSH Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (haproxy_ssh_active_connections{env=\"gprd\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_sessions_total{env=\"gprd\", backend=\"ssh\"}[1m])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Max Startup Violations",
   "type": "graph",
   "description": "This should never be greater than 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (server_name) (rate(haproxy_ssh_max_startups_breached_total{env=\"gprd\"}[1m]))",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Connection Termination Reasons",
   "type": "graph",
   "description": "http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#8.5",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (server_name, cause) (rate (haproxy_ssh_requests_terminated_total{env=\"gprd\"}[1m]))",
     "legendFormat": "{{server_name}} - {{cause}}"
    }
   ]
  }
 ]
}