{
 "title": "SLAs",
 "tags": [ "overview" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  { "title": "Headline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLA Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sort(\n          avg(\n            avg_over_time(slo_observation_status{environment=\"$environment\", stage=~\"main|\", type=~\"web|api|git|ci-runners|pages|sidekiq\"}[$__range])\n          )\n        )"
    }
   ]
  },
  {
   "title": "SLA Trends - Aggregated",
   "type": "graph",
   "description": "1w rolling average SLO adherence across all primary services. Higher is better.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(\n        avg(avg_over_time(slo_observation_status{environment=\"gprd\", stage=~\"main|\", type=~\"pages|web|api|git|sidekiq|registry\"}[7d]))\n      ,1),0)",
     "legendFormat": "gitlab.com SLA"
    }
   ]
  },
  { "title": "Primary Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2000 } },
  {
   "title": "Primary Services Average Availability for Period",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2001 },
   "targets": [
    {
     "expr": "\n        sort(avg(avg_over_time(slo_observation_status{environment=\"$environment\", stage=~\"main|\", type=~\"web|api|git|ci-runners|pages|sidekiq\"}[$__range])) by (type))\n      ",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "SLA Trends - Primary Services",
   "type": "graph",
   "description": "1w rolling average SLO adherence for primary services. Higher is better.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2011 },
   "yaxes": [
    { "format": "percentunit", "label": "SLA" }
   ],
   "targets": [
    {
     "expr": "clamp_min(clamp_max(\n        avg(avg_over_time(slo_observation_status{environment=\"gprd\", stage=~\"main|\", type=~\"pages|web|api|git|sidekiq|registry\"}[7d])) by (type)\n      ,1),0)",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}