{
 "title": "SLO proof-of-concept",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GitLab.com SLO (web+api), past week",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(avg_over_time(slo_observation_status{environment=\"gprd\", type=~\"web|api\", stage=~\"main|\"}[7d]))"
    }
   ]
  },
  {
   "title": "GitLab.com SLO Observance % - past 30 days",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(slo_observation_status{environment=\"gprd\", type=~\"web|api\", stage=~\"main|\"}[$__interval]))",
     "legendFormat": "SLO Observance %"
    }
   ]
  },
  {
   "title": "Per Service SLO - past week",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sort_desc(avg(avg_over_time(slo_observation_status{environment=\"gprd\", stage=~\"main|\"}[7d])) by (type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Per Service SLO - past month",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sort_desc(avg(avg_over_time(slo_observation_status{environment=\"gprd\", stage=~\"main|\"}[30d])) by (type))",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}