{
 "title": "SSH Performance",
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": "label_values(up{job=\"haproxy\"}, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "SSH request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (environment) (rate(haproxy_ssh_request_duration_seconds_count{environment=~\"$environment\"}[$__interval]))",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \n  sum by (le,env) (\n    rate(haproxy_ssh_request_duration_seconds_bucket{env=~\"$environment\"}[$__interval])\n  )\n)",
     "legendFormat": "50th {{env}}"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum by (le,env) (\n    rate(haproxy_ssh_request_duration_seconds_bucket{env=~\"$environment\"}[$__interval])\n  )\n)",
     "legendFormat": "10th {{env}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (rate(haproxy_ssh_request_duration_seconds_bucket{environment=~\"$environment\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}