{
 "title": "stage-groups: Applied Machine Learning: group error budget detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/3132880873 at Wed Oct  5 21:00:47 UTC 2022",
 "tags": [
  "managed",
  "stage-groups",
  "feature_category",
  "stage_group:Applied Machine Learning"
 ],
 "time": { "from": "now-28d/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "Error Budget (From ${__from:date:YYYY-MM-DD HHːmm} to ${__to:date:YYYY-MM-DD HHːmm})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n",
     "legendFormat": "%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 0, "y": 105.5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.9995 * 100.0" }
   ]
  },
  {
   "title": "Budget remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in $__range\n(1 - 0.9995) * $__range_s\n-\n(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * $__range_s\n)\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 6, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 6, "y": 105.5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in $__range\n(1 - 0.9995) * $__range_s\n"
    }
   ]
  },
  {
   "title": "Budget spent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * $__range_s\n)\n"
    },
    {
     "expr": "# The number of seconds allowed to be spent in $__range\n(1 - 0.9995) * $__range_s\n",
     "legendFormat": "budget"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 12, "y": 105.5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in $__range\n(1 - 0.9995) * $__range_s\n"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 100 },
   "content": "### [Error budget](https://about.gitlab.com/handbook/engineering/error-budgets/)\n\nThese error budget panels show an aggregate of SLIs across all components.\nHowever, not all components have been implemented yet.\n\nThe [handbook](https://about.gitlab.com/handbook/engineering/error-budgets/)\nexplains how these budgets are used.\n\nRead more about how the error budgets are calculated in the\n[stage group dashboard documentation](https://docs.gitlab.com/ee/development/stage_group_dashboards.html#error-budget).\n\nThe error budget is compared to our SLO of 99.95% and is always in\na range of 28 days from the selected end date in Grafana.\n\n### Availability\n\nThe availability shows the percentage of operations labeled with one of the\ncategories owned by Applied Machine Learning with satisfactory completion.\n\n### Budget remaining\n\nThe error budget in minutes is calculated based on the 99.95%.\nThere are 40320 minutes in 28 days, we allow 0.05% of failures, which\nmeans the budget in minutes is (1 - 0.9995) * $__range_s / 60.0 minutes.\n\nThe budget remaining shows how many minutes have not been spent in the\npast 28 days.\n\n### Minutes spent\n\nThis shows the total minutes spent over the past 28 days.\n\nFor example, if there were 403200 (28 * 24 * 60) operations in 28 days.\nThis would be 1 every minute. If 10 of those were unsatisfactory, that\nwould mean 10 minutes of the budget were spent.\n"
  },
  {
   "title": "Budget spend attribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "collapsed": true,
   "panels": [
    {
     "title": "Budget failures",
     "type": "table",
     "description": "Number of failures contributing to the budget send per component and type ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 151 },
     "targets": [
      {
       "expr": "ceil(\n  (\n    sum by (component,type,violation_type) (\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n            ) -\n            # Request with satisfactory apdex\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'apdex' , '', ''\n      )\n      or\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'error' , '', ''\n      )\n    ) > 0\n  ) * 60\n)\n"
      },
      {
       "expr": "ceil(\n  (\n    sum by (component,type,violation_type) (\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'apdex' , '', ''\n      )\n      or\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range]\n            )\n            and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__range])\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'error' , '', ''\n      )\n    ) > 0\n  ) * 60\n)\n"
      }
     ]
    },
    {
     "title": "Info",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 151 },
     "content": "This table shows the failures that contribute to the spend of the error budget.\nFixing the top item in this table will have the biggest impact on the\nbudget spend.\n\nA failure is one of 2 types:\n\n- **error**: An operation that failed: 500 response, failed background job.\n- **apdex**: This means an operation that succeeded, but did not perform within the set threshold.\n\nSee the [developer documentation](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/development/stage_group_dashboards.md#error-budget)\nto learn more about this.\n\nThe component refers to the component in our stack where the violation occurred.\nThe most common ones are:\n\n- **puma**: This component signifies requests handled by rails\n- **sidekiq_execution**: This component signifies background jobs executed by Sidekiq\n\nTo find the endpoint that is attributing to the budget spend and a violation type\nwe can use the logs over a 7 day range. Links for puma and sidekiq are available on the right.\nThese logs list the endpoints that had the most violations over the past 7 days.\n\nThe \"Other\" row is the sum of all the other violations excluding the top ones\nthat are listed.\n"
    },
    {
     "title": "Failure log links",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 151 },
     "content": "##### [Rails Requests Apdex](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security)))))),(meta:(key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),(meta:(key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'3',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.request_urgency.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'3',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.target_duration_s,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'3',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,id:'3',params:(customLabel:'Operations+over+specified+threshold+(apdex)',field:json.duration_s,json:'{\"script\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value+?+1+:+0\"}'),schema:metric,type:sum))))&_g=(time:(from:'now-7d',to:'now'))): slow requests\n\nThis shows the number of requests exceeding the request duration thresholds\nconfigured per endpoint over the past 7 days.\n\nThe threshold depends on the [configurable request urgency](https://docs.gitlab.com/ee/development/application_slis/rails_request_apdex.html#adjusting-request-urgency).\n\n##### [Puma Errors](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security)))))),(meta:(key:json.status,params:(gte:500),type:range),query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.request_urgency.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.target_duration_s,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): failing requests\n\nThis shows the number of Rails requests that failed per endpoint over\nthe past 7 days.\n\n##### [All request violations](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security)))))),(meta:(key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),(meta:(key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'5',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.request_urgency.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'5',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.target_duration_s,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'5',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,id:'3',params:(customLabel:'Operations+over+specified+threshold+(apdex)',field:json.duration_s,json:'{\"script\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value+?+1+:+0\"}'),schema:metric,type:sum),(enabled:!t,id:'4',params:(customLabel:'Failing+requests+(error)',field:json.status,json:'{\"script\":+\"doc[!'json.status!'].value+>=+500+?+1+:+0\"}'),schema:metric,type:sum),(enabled:!t,id:'5',params:(customLabel:'Total+violations+(apdex+%2B+error)',field:json.duration_s,json:'{\"script\":+\"int+errors+=+doc[!'json.status!'].value+>=+500+?+1+:+0;\\nint+slowRequests+=+doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value+?+1+:+0;\\nreturn+errors+%2B+slowRequests;\\n\"}'),schema:metric,type:sum))))&_g=(time:(from:'now-7d',to:'now'))): slow requests + failing requests\n\nThis slow loading table shows the endpoints that errored or where slow the most often\nin the past 7 days.\n\nIf `rails_requests` or `puma` are at the top of the table on the left side, then\nthis will show you the top endpoints to look into.\n\n##### [Sidekiq Execution Apdex](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security)))))),(meta:(key:json.job_status,params:done,type:phrase),query:(match:(json.job_status:(query:done,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(filters:!((input:(language:kuery,query:'json.shard:+\"urgent\"+AND+json.duration_s+>+10'),label:'Jobs+exceeding+10s'),(input:(language:kuery,query:'not+json.shard:+\"urgent\"+AND+json.duration_s+>+300'),label:'Jobs+exceeding+300s'))),schema:split,type:filters),(enabled:!t,params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): slow jobs\n\nThis shows the number of jobs per worker that took longer than their threshold to\nexecute over the past 7 days.\nFor urgent jobs the threshold is 10s, this is the table on the left.\nFor other jobs the threshold is 300s, this is the table on the right.\n\n##### [Sidekiq Execution Errors](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security)))))),(meta:(key:json.job_status,params:fail,type:phrase),query:(match:(json.job_status:(query:fail,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): failing jobs\n\nThis shows the number of jobs per worker that failed over the past 7 days.\nThis includes retries: if a job with a was retried 3 times, before exhausting\nits retries, this counts as 3 failures towards the budget.\n"
    }
   ]
  },
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }
  },
  {
   "title": "Overall Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab:stage_group:execution:apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n",
     "legendFormat": "Applied Machine Learning apdex"
    },
    {
     "expr": "(1 - 6 * (1 - 0.9995))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - 0.9995))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab:stage_group:execution:apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n",
     "legendFormat": "Applied Machine Learning apdex avg"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab:stage_group:execution:apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab:stage_group:execution:apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"} < (1 - (14.4 * (1 - 0.9995)))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab:stage_group:execution:apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"} < (1 - (14.4 * (1 - 0.9995)))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab:stage_group:execution:apdex:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"} < (1 - (6 * (1 - 0.9995)))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab:stage_group:execution:apdex:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"} < (1 - (6 * (1 - 0.9995)))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "Overall | Latency/Apdex"
    }
   ]
  },
  {
   "title": "Overall Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 201 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab:stage_group:execution:error:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Applied Machine Learning error ratio"
    },
    {
     "expr": "(6 * 0.0005)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * 0.0005)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab:stage_group:execution:error:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Applied Machine Learning error ratio avg"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 8, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab:stage_group:execution:error:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab:stage_group:execution:error:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"} > (14.4 * 0.9995)),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab:stage_group:execution:error:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"} > (14.4 * 0.9995)),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab:stage_group:execution:error:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"} > (6 * 0.9995)),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab:stage_group:execution:error:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"} > (6 * 0.9995)),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "Overall | Errors"
    }
   ]
  },
  {
   "title": "Overall RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab:stage_group:execution:ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n",
     "legendFormat": "Applied Machine Learning RPS"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "🔬 Service Level Indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 },
   "collapsed": true,
   "panels": [
    {
     "title": "graphql_queries SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"graphql_queries\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"graphql_queries\",monitor=\"global\"})\n))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"graphql_queries\",monitor=\"global\"})\n))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "graphql_queries SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"graphql_queries\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "content": "### Description\n\nThe number of GraphQL queries meeting their duration target based on the urgency\nof the endpoint. By default, a query should take no more than 1s. We're working\non making the urgency customizable in [this epic](https://gitlab.com/groups/gitlab-org/-/epics/5841).\n\nMutliple queries could be batched inside a single request.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security)))))),(meta:(key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s))),(meta:(key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value'))))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security)))))),(meta:(key:json.status,params:(gte:500),type:range),query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security)))))),(meta:(key:json.status,params:(gte:500),type:range),query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "puma SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"puma\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"puma\",monitor=\"global\"})\n)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"puma\",monitor=\"global\"})\n)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "puma SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"puma\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "content": "### Description\n\nAggregation of most web requests that pass through the puma to the GitLab rails monolith.\nHealthchecks are excluded.\n\n\n\n### Observability Tools\n\n* [🐞 Sentry Releases: gitlab/gitlabcom](https://sentry.gitlab.net/gitlab/gitlabcom/releases?environment=${environment})\n* [🐞 Sentry web issues](https://sentry.gitlab.net/gitlab/gitlabcom/issues?environment=${environment}&query=stage%3A${stage}+type%3Aweb)\n\n"
    },
    {
     "title": "rails_requests SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_requests\",monitor=\"global\"})\n))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_requests\",monitor=\"global\"})\n))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "rails_requests SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "content": "### Description\n\nThe number of requests meeting their duration target based on the urgency\nof the endpoint. By default, a request should take no more than 1s. But\nthis can be adjusted by endpoint.\n\nRead more about this in the [documentation](https://docs.gitlab.com/ee/development/application_slis/rails_request_apdex.html).\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security)))))),(meta:(key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s))),(meta:(key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value'))))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security)))))),(meta:(key:json.status,params:(gte:500),type:range),query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security)))))),(meta:(key:json.status,params:(gte:500),type:range),query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(workflow_automation,intel_code_security),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:workflow_automation)),(match_phrase:(json.meta.feature_category:intel_code_security))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "sidekiq_execution SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"sidekiq_execution\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution\",monitor=\"global\"})\n))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"sidekiq_execution\",monitor=\"global\"})\n))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "sidekiq_execution SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"sidekiq_execution\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution\",monitor=\"global\"})\n)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"sidekiq_execution\",monitor=\"global\"})\n)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "sidekiq_execution SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"sidekiq_execution\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"applied_ml\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
     "content": "### Description\n\nThe number of CustomersDot jobs meeting their duration target for their execution.\nBy default, a Sidekiq job should take no more than 5 seconds. But\nthis can be adjusted by endpoint.\n\n"
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: graphql_queries",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1200 },
   "collapsed": true,
   "panels": [
    {
     "title": "graphql_queries RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_graphql_query_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_queries Latency - per endpoint_id",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_success_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (endpoint_id) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "graphql_queries RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli_graphql_query_apdex_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_queries Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_success_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "graphql_queries RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_graphql_query_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_queries Latency - per query_urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (query_urgency) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n    )\n    -\n    sum by (query_urgency) (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_success_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (query_urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_graphql_query_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{query_urgency}}"
      }
     ]
    },
    {
     "title": "graphql_queries RPS - per query_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (query_urgency) (\n  sli_aggregations:gitlab_sli_graphql_query_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{query_urgency}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: puma",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1210 },
   "collapsed": true,
   "panels": [
    {
     "title": "puma Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "puma RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "puma Errors - per region",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (region) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",region!=\"\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "puma RPS - per region",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (region) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",region!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{region}}"
      }
     ]
    },
    {
     "title": "puma Errors - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",method!=\"\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "puma RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",method!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "puma Errors - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "puma RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: rails_requests",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1220 },
   "collapsed": true,
   "panels": [
    {
     "title": "rails_requests RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_requests Latency - per endpoint_id",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_success_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (endpoint_id) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "rails_requests RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_requests Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_success_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "rails_requests RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_requests Latency - per request_urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (request_urgency) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n    )\n    -\n    sum by (request_urgency) (\n      sli_aggregations:gitlab_sli_rails_request_apdex_success_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (request_urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    },
    {
     "title": "rails_requests RPS - per request_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (request_urgency) (\n  sli_aggregations:gitlab_sli_rails_request_apdex_total_rate5m{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: sidekiq_execution",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1230 },
   "collapsed": true,
   "panels": [
    {
     "title": "sidekiq_execution Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_sli_customers_dot_sidekiq_jobs_error_total{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_sli_customers_dot_sidekiq_jobs_total{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution Latency - per endpoint_id",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (endpoint_id) (\n      rate(gitlab_sli_customers_dot_sidekiq_jobs_apdex_total{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n    )\n    -\n    sum by (endpoint_id) (\n      rate(gitlab_sli_customers_dot_sidekiq_jobs_apdex_success_total{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n    )\n  )\n  / ignoring (endpoint_id) group_left()\n  (\n    sum by () (\n      rate(gitlab_sli_customers_dot_sidekiq_jobs_apdex_total{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution Errors - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  rate(gitlab_sli_customers_dot_sidekiq_jobs_error_total{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  rate(gitlab_sli_customers_dot_sidekiq_jobs_total{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for sidekiq_execution Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      rate(gitlab_sli_customers_dot_sidekiq_jobs_apdex_total{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n    )\n    -\n    sum by (feature_category) (\n      rate(gitlab_sli_customers_dot_sidekiq_jobs_apdex_success_total{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      rate(gitlab_sli_customers_dot_sidekiq_jobs_apdex_total{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution Errors - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  rate(gitlab_sli_customers_dot_sidekiq_jobs_error_total{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "sidekiq_execution RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  rate(gitlab_sli_customers_dot_sidekiq_jobs_total{environment=\"$environment\",feature_category=~\"workflow_automation|intel_code_security|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    }
   ]
  }
 ]
}