{
 "title": "stage-groups: Group dashboard: release (Release)",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/949593800 at Thu Jan  7 15:20:49 UTC 2021",
 "tags": [
  "managed",
  "stage-groups",
  "feature_category"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  { "title": "Rails Request Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 } },
  {
   "title": "API Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(gitlab_transaction_duration_seconds_count{\n    env='$environment',\n    environment='$environment',\n    feature_category=~'(continuous_delivery|advanced_deployments|review_apps|feature_flags|release_orchestration|pages)',\n    type='api'\n  }[$__interval])\n)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "GIT Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 202 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(gitlab_transaction_duration_seconds_count{\n    env='$environment',\n    environment='$environment',\n    feature_category=~'(continuous_delivery|advanced_deployments|review_apps|feature_flags|release_orchestration|pages)',\n    type='git'\n  }[$__interval])\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "WEB Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(gitlab_transaction_duration_seconds_count{\n    env='$environment',\n    environment='$environment',\n    feature_category=~'(continuous_delivery|advanced_deployments|review_apps|feature_flags|release_orchestration|pages)',\n    type='web'\n  }[$__interval])\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Extra links",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 202 },
   "content": "* [📖 Kibana: Kibana Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.controller,json.action,json.path,json.duration_s),filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),index:'AW5F1e45qthdGjPJueGO',query:(language:kuery,query:''))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Kibana Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.controller,json.action,json.path,json.duration_s),filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages)))))),(query:(range:(json.status:(gte:500))))),index:'AW5F1e45qthdGjPJueGO',query:(language:kuery,query:''))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1e45qthdGjPJueGO&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1e45qthdGjPJueGO&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages)))))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1e45qthdGjPJueGO&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.controller.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1e45qthdGjPJueGO&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.controller.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1e45qthdGjPJueGO&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1e45qthdGjPJueGO&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.controller.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n"
  },
  { "title": "Rails Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 301 } },
  {
   "title": "API Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 302 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (component) (\n  gitlab:component:feature_category:execution:error:rate_1m{\n    env='$environment',\n    environment='$environment',\n    feature_category=~'(continuous_delivery|advanced_deployments|review_apps|feature_flags|release_orchestration|pages)',\n    type='api'\n  }\n)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "GIT Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 302 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (component) (\n  gitlab:component:feature_category:execution:error:rate_1m{\n    env='$environment',\n    environment='$environment',\n    feature_category=~'(continuous_delivery|advanced_deployments|review_apps|feature_flags|release_orchestration|pages)',\n    type='git'\n  }\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "WEB Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 302 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (component) (\n  gitlab:component:feature_category:execution:error:rate_1m{\n    env='$environment',\n    environment='$environment',\n    feature_category=~'(continuous_delivery|advanced_deployments|review_apps|feature_flags|release_orchestration|pages)',\n    type='web'\n  }\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  { "title": "Sidekiq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 401 } },
  {
   "title": "Sidekiq Completion Rate",
   "type": "graph",
   "description": "The rate (Jobs per Second) at which jobs are completed after dequeue",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 402 },
   "yaxes": [
    { "format": "short", "label": "Jobs per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  rate(sidekiq_jobs_completion_seconds_count{\n    env='$environment',\n    environment='$environment',\n    feature_category=~'(continuous_delivery|advanced_deployments|review_apps|feature_flags|release_orchestration|pages)'\n  }[$__interval])\n)\n",
     "legendFormat": "{{worker]}}"
    }
   ]
  },
  {
   "title": "Sidekiq Error Rate",
   "type": "graph",
   "description": "The rate (Jobs per Second) at which jobs fail after dequeue",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 402 },
   "yaxes": [
    { "format": "short", "label": "Jobs per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  rate(sidekiq_jobs_failed_total{\n    env='$environment',\n    environment='$environment',\n    feature_category=~'(continuous_delivery|advanced_deployments|review_apps|feature_flags|release_orchestration|pages)'\n  }[$__interval])\n)\n",
     "legendFormat": "{{worker]}}"
    }
   ]
  },
  {
   "title": "Extra links",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 402 },
   "content": "* [📖 Kibana: Kibana Sidekiq logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.job_status,json.scheduling_latency_s,json.duration_s),filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),index:'AWNABDRwNDuQHTm2tH6l',query:(language:kuery,query:''))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Kibana Sidekiq failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.job_status,json.scheduling_latency_s,json.duration_s),filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages)))))),(query:(match:(json.job_status:(query:fail,type:phrase))))),index:'AWNABDRwNDuQHTm2tH6l',query:(language:kuery,query:''))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages)))))),(query:(match:(json.job_status:(query:fail,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:continuous_delivery)),(match_phrase:(json.meta.feature_category:advanced_deployments)),(match_phrase:(json.meta.feature_category:review_apps)),(match_phrase:(json.meta.feature_category:feature_flags)),(match_phrase:(json.meta.feature_category:release_orchestration)),(match_phrase:(json.meta.feature_category:pages))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./stage-groups/release.dashboard.jsonnet)\n"
  }
 ]
}