{
 "title": "stage-groups: Group dashboard: mobile (DevOps for Mobile Apps)",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/1183991985 at Thu Apr 15 17:42:38 UTC 2021",
 "tags": [
  "managed",
  "stage-groups",
  "feature_category"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," },
   {
    "name": "controller",
    "query": "label_values(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment='$environment', feature_category=~'(mobile_signing_deployment)'}, controller)"
   },
   {
    "name": "action",
    "query": "label_values(controller_action:gitlab_transaction_duration_seconds_count:rate1m{environment='$environment', controller=~'$controller', feature_category=~'(mobile_signing_deployment)'}, action)"
   }
  ]
 },
 "panels": [
  { "title": "Introduction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Introduction",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "content": "You may see there are some empty panels in this dashboard. The metrics in each dashboard are filtered and accumulated based on the GitLab [product categories](https://about.gitlab.com/handbook/product/categories/) and [feature categories](https://docs.gitlab.com/ee/development/feature_categorization/index.html).\n- If your stage group hasn't declared a feature category, please follow the feature category guideline.\n- If your stage group doesn't use a particular component, you can always [customize this dashboard](https://docs.gitlab.com/ee/development/stage_group_dashboards.html#how-to-customize-the-dashboard) to exclude irrelevant panels.\n\nFor more information, please visit [Dashboards for stage groups](https://docs.gitlab.com/ee/development/stage_group_dashboards.html) or watch [Guide to getting started with dashboards for stage groups](https://youtu.be/xB3gHlKCZpQ).\n\nThe dashboards for stage groups are at a very early stage. All contributions are welcome. If you have any questions or suggestions, please submit an issue in the [Scalability Team issues tracker](https://gitlab.com/gitlab-com/gl-infra/scalability/-/issues/new).\n"
  },
  {
   "title": "Error Budgets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 101 },
     "targets": [
      {
       "expr": "# Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"moble_devops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"moble_devops\"}[28d]\n      ) or vector(0)\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"moble_devops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"moble_devops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"moble_devops\"}[28d]\n    ) or vector(0)\n  ),\n1)\n",
       "legendFormat": "%"
      }
     ]
    },
    {
     "title": "Budget Spent",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 101 },
     "targets": [
      {
       "expr": "(\n  1 - # Account for missing metrics that are turned into 0 by `vector(0)`.\nclamp_max(\n  # Number of successful measurements\n  sum(\n    # Reuest with satisfactory apdex\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"moble_devops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests without error\n    (\n      sum_over_time(\n        gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"moble_devops\"}[28d]\n      ) or vector(0)\n      -\n      sum_over_time(\n        gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"moble_devops\"}[28d]\n      ) or vector(0)\n    )\n  )\n  /\n  # Number of measurements\n  sum(\n    # Apdex Measurements\n    sum_over_time(\n      gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"moble_devops\"}[28d]\n    ) or vector(0)\n    +\n    # Requests\n    sum_over_time(\n      gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"moble_devops\"}[28d]\n    ) or vector(0)\n  ),\n1)\n\n) * 2419200\n"
      }
     ]
    },
    {
     "title": "Info",
     "type": "text",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 101 },
     "content": "### [Error budget](https://about.gitlab.com/handbook/engineering/error-budgets/)\n\nThese error budget panels show an aggregate of SLIs across all components.\nThough not all components have been implemented yet.\n\nThe [handbook](https://about.gitlab.com/handbook/engineering/error-budgets/)\nexplains how these budgets are used.\n\nRead more about how the error budgets are calculated in the\n[stage group dashboard documentation](https://docs.gitlab.com/ee/development/stage_group_dashboards.html#error-budget).\n\nThe error budget is compared to our SLO of 99.95% and is always in\na range of 28 days from the selected end date in Grafana.\n\n### Availability\n\nThe availability shows the percentage operations labeled with one of the\ncategories owned by DevOps for Mobile Apps comleted satisfactory.\n\n### Budget spent\n\nThe budget spent shows the time spent during the past 28 days on operations\nthat did not complete satisfactory.\n\nFor example, if there were 43200 (28 * 24 * 60) operations for DevOps for Mobile Apps the last\n28 days, and 10 of them did not meet SLO, this means 10 minutes were spent.\n"
    }
   ]
  },
  { "title": "Rails Request Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 } },
  {
   "title": "API Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(gitlab_transaction_duration_seconds_count{\n    environment='$environment',\n    stage='$stage',\n    feature_category=~'(mobile_signing_deployment)',\n    type='api',\n    controller=~'$controller',\n    action=~'$action'\n  }[$__interval])\n)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "GIT Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 202 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(gitlab_transaction_duration_seconds_count{\n    environment='$environment',\n    stage='$stage',\n    feature_category=~'(mobile_signing_deployment)',\n    type='git',\n    controller=~'$controller',\n    action=~'$action'\n  }[$__interval])\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "WEB Request Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(gitlab_transaction_duration_seconds_count{\n    environment='$environment',\n    stage='$stage',\n    feature_category=~'(mobile_signing_deployment)',\n    type='web',\n    controller=~'$controller',\n    action=~'$action'\n  }[$__interval])\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Extra links",
   "type": "text",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 202 },
   "content": "* [📖 Kibana: Kibana Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.controller,json.action,json.path,json.duration_s),filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Kibana Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.controller,json.action,json.path,json.duration_s),filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment)))))),(query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment)))))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.controller.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.controller.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.controller.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n"
  },
  {
   "title": "Rails 95th Percentile Request Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 301 }
  },
  {
   "title": "API 95th Percentile Request Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 302 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(\n    controller_action:gitlab_transaction_duration_seconds:p95{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='api'\n    }[$__interval]\n  )\n) by (controller, action)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "GIT 95th Percentile Request Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 302 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(\n    controller_action:gitlab_transaction_duration_seconds:p95{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='git'\n    }[$__interval]\n  )\n) by (controller, action)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "WEB 95th Percentile Request Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 302 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(\n    controller_action:gitlab_transaction_duration_seconds:p95{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='web'\n    }[$__interval]\n  )\n) by (controller, action)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Rails Error Rates (accumulated by components)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 401 }
  },
  {
   "title": "API Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 402 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (component) (\n  gitlab:component:feature_category:execution:error:rate_1m{\n    environment='$environment',\n    stage='$stage',\n    feature_category=~'(mobile_signing_deployment)',\n    type='api'\n  }\n)\n",
     "legendFormat": "api error rate"
    }
   ]
  },
  {
   "title": "GIT Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 402 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (component) (\n  gitlab:component:feature_category:execution:error:rate_1m{\n    environment='$environment',\n    stage='$stage',\n    feature_category=~'(mobile_signing_deployment)',\n    type='git'\n  }\n)\n",
     "legendFormat": "git error rate"
    }
   ]
  },
  {
   "title": "WEB Error Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 402 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (component) (\n  gitlab:component:feature_category:execution:error:rate_1m{\n    environment='$environment',\n    stage='$stage',\n    feature_category=~'(mobile_signing_deployment)',\n    type='web'\n  }\n)\n",
     "legendFormat": "web error rate"
    }
   ]
  },
  { "title": "SQL Queries Per Action", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 501 } },
  {
   "title": "API SQL Queries per Action",
   "type": "graph",
   "description": "Average amount of SQL queries performed by a controller action.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 502 },
   "yaxes": [
    { "format": "short", "label": "Queries" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn,instance) (\n  rate(\n    gitlab_sql_duration_seconds_count{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='api'\n    }[$__interval]\n  )\n)\n/\navg_over_time(\n  controller_action:gitlab_transaction_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(mobile_signing_deployment)',\n    type='api'\n  }[$__interval]\n)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "GIT SQL Queries per Action",
   "type": "graph",
   "description": "Average amount of SQL queries performed by a controller action.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 502 },
   "yaxes": [
    { "format": "short", "label": "Queries" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn,instance) (\n  rate(\n    gitlab_sql_duration_seconds_count{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='git'\n    }[$__interval]\n  )\n)\n/\navg_over_time(\n  controller_action:gitlab_transaction_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(mobile_signing_deployment)',\n    type='git'\n  }[$__interval]\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "WEB SQL Queries per Action",
   "type": "graph",
   "description": "Average amount of SQL queries performed by a controller action.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 502 },
   "yaxes": [
    { "format": "short", "label": "Queries" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn,instance) (\n  rate(\n    gitlab_sql_duration_seconds_count{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='web'\n    }[$__interval]\n  )\n)\n/\navg_over_time(\n  controller_action:gitlab_transaction_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(mobile_signing_deployment)',\n    type='web'\n  }[$__interval]\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  { "title": "SQL Latency Per Action", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 601 } },
  {
   "title": "API SQL Latency per Action",
   "type": "graph",
   "description": "Average sum of all SQL query latency accumulated by a controller action.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 602 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(\n  controller_action:gitlab_sql_duration_seconds_sum:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(mobile_signing_deployment)',\n    type='api'\n  }[$__interval]\n)\n/\navg_over_time(\n  controller_action:gitlab_transaction_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(mobile_signing_deployment)',\n    type='api'\n  }[$__interval]\n)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "GIT SQL Latency per Action",
   "type": "graph",
   "description": "Average sum of all SQL query latency accumulated by a controller action.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 602 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(\n  controller_action:gitlab_sql_duration_seconds_sum:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(mobile_signing_deployment)',\n    type='git'\n  }[$__interval]\n)\n/\navg_over_time(\n  controller_action:gitlab_transaction_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(mobile_signing_deployment)',\n    type='git'\n  }[$__interval]\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "WEB SQL Latency per Action",
   "type": "graph",
   "description": "Average sum of all SQL query latency accumulated by a controller action.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 602 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(\n  controller_action:gitlab_sql_duration_seconds_sum:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(mobile_signing_deployment)',\n    type='web'\n  }[$__interval]\n)\n/\navg_over_time(\n  controller_action:gitlab_transaction_duration_seconds_count:rate1m{\n    environment=\"$environment\",\n    stage='$stage',\n    action=~\"$action\",\n    controller=~\"$controller\",\n    feature_category=~'(mobile_signing_deployment)',\n    type='web'\n  }[$__interval]\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  { "title": "SQL Latency Per Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 701 } },
  {
   "title": "API SQL Latency per Query",
   "type": "graph",
   "description": "Average latency of individual SQL queries\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 702 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(\n    gitlab_sql_duration_seconds_sum{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='api'\n    }[$__interval]\n  )\n)\n/\nsum by (controller, action) (\n  rate(\n    gitlab_sql_duration_seconds_count{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='api'\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "GIT SQL Latency per Query",
   "type": "graph",
   "description": "Average latency of individual SQL queries\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 702 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(\n    gitlab_sql_duration_seconds_sum{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='git'\n    }[$__interval]\n  )\n)\n/\nsum by (controller, action) (\n  rate(\n    gitlab_sql_duration_seconds_count{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='git'\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "WEB SQL Latency per Query",
   "type": "graph",
   "description": "Average latency of individual SQL queries\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 702 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action) (\n  rate(\n    gitlab_sql_duration_seconds_sum{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='web'\n    }[$__interval]\n  )\n)\n/\nsum by (controller, action) (\n  rate(\n    gitlab_sql_duration_seconds_count{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='web'\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  { "title": "Caches per Action", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 801 } },
  {
   "title": "API Caches per Action",
   "type": "graph",
   "description": "Average total number of caching operations (Read & Write) per action.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 802 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action, operation) (\n  rate(\n    gitlab_cache_operations_total{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='api'\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{operation}} - {{action}}"
    }
   ]
  },
  {
   "title": "GIT Caches per Action",
   "type": "graph",
   "description": "Average total number of caching operations (Read & Write) per action.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 802 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action, operation) (\n  rate(\n    gitlab_cache_operations_total{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='git'\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{operation}} - {{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "WEB Caches per Action",
   "type": "graph",
   "description": "Average total number of caching operations (Read & Write) per action.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 802 },
   "yaxes": [
    { "format": "short", "label": "Operations" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, action, operation) (\n  rate(\n    gitlab_cache_operations_total{\n      environment=\"$environment\",\n      stage='$stage',\n      action=~\"$action\",\n      controller=~\"$controller\",\n      feature_category=~'(mobile_signing_deployment)',\n      type='web'\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{operation}} - {{controller}}#{{action}}"
    }
   ]
  },
  { "title": "Sidekiq", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 901 } },
  {
   "title": "Sidekiq Completion Rate",
   "type": "graph",
   "description": "The rate (Jobs per Second) at which jobs are completed after dequeue",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 902 },
   "yaxes": [
    { "format": "short", "label": "Jobs per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  rate(sidekiq_jobs_completion_seconds_count{\n    environment=\"$environment\",\n    stage='$stage',\n    feature_category=~'(mobile_signing_deployment)'\n  }[$__interval])\n)\n",
     "legendFormat": "{{worker]}}"
    }
   ]
  },
  {
   "title": "Sidekiq Error Rate",
   "type": "graph",
   "description": "The rate (Jobs per Second) at which jobs fail after dequeue",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 902 },
   "yaxes": [
    { "format": "short", "label": "Jobs per Second" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (\n  rate(sidekiq_jobs_failed_total{\n    environment=\"$environment\",\n    stage='$stage',\n    feature_category=~'(mobile_signing_deployment)'\n  }[$__interval])\n)\n",
     "legendFormat": "{{worker]}}"
    }
   ]
  },
  {
   "title": "Extra links",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 902 },
   "content": "* [📖 Kibana: Kibana Sidekiq logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.job_status,json.scheduling_latency_s,json.duration_s),filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),index:'AWNABDRwNDuQHTm2tH6l')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Kibana Sidekiq failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.class,json.queue,json.meta.project,json.job_status,json.scheduling_latency_s,json.duration_s),filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment)))))),(query:(match:(json.job_status:(query:fail,type:phrase))))),index:'AWNABDRwNDuQHTm2tH6l')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment)))))),(query:(match:(json.job_status:(query:fail,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Kibana Sidekiq percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:mobile_signing_deployment))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.project.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/./stage-groups/moble_devops.dashboard.jsonnet)\n"
  }
 ]
}