{
 "title": "stage-groups: Gitaly:Cluster: group error budget detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4056077714 at Tue Apr  4 06:57:45 UTC 2023",
 "tags": [
  "managed",
  "stage-groups",
  "feature_category",
  "stage_group:Gitaly:Cluster"
 ],
 "time": { "from": "now-28d/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "Error Budget (From ${__from:date:YYYY-MM-DD HHːmm} to ${__to:date:YYYY-MM-DD HHːmm})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n",
     "legendFormat": "%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 0, "y": 105.5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.9995 * 100.0" }
   ]
  },
  {
   "title": "Budget remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in $__range\n(1 - 0.9995) * $__range_s\n-\n(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * $__range_s\n)\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 6, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 6, "y": 105.5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in $__range\n(1 - 0.9995) * $__range_s\n"
    }
   ]
  },
  {
   "title": "Budget spent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * $__range_s\n)\n"
    },
    {
     "expr": "# The number of seconds allowed to be spent in $__range\n(1 - 0.9995) * $__range_s\n",
     "legendFormat": "budget"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1.5, "w": 6, "x": 12, "y": 105.5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in $__range\n(1 - 0.9995) * $__range_s\n"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 100 },
   "content": "### [Error budget](https://about.gitlab.com/handbook/engineering/error-budgets/)\n\nThese error budget panels show an aggregate of SLIs across all components.\nHowever, not all components have been implemented yet.\n\nThe [handbook](https://about.gitlab.com/handbook/engineering/error-budgets/)\nexplains how these budgets are used.\n\nRead more about how the error budgets are calculated in the\n[stage group dashboard documentation](https://docs.gitlab.com/ee/development/stage_group_dashboards.html#error-budget).\n\nThe error budget is compared to our SLO of 99.95% and is always in\na range of 28 days from the selected end date in Grafana.\n\n### Availability\n\nThe availability shows the percentage of operations labeled with one of the\ncategories owned by Gitaly:Cluster with satisfactory completion.\n\n### Budget remaining\n\nThe error budget in minutes is calculated based on the 99.95%.\nThere are 40320 minutes in 28 days, we allow 0.05% of failures, which\nmeans the budget in minutes is (1 - 0.9995) * $__range_s / 60.0 minutes.\n\nThe budget remaining shows how many minutes have not been spent in the\npast 28 days.\n\n### Minutes spent\n\nThis shows the total minutes spent over the past 28 days.\n\nFor example, if there were 403200 (28 * 24 * 60) operations in 28 days.\nThis would be 1 every minute. If 10 of those were unsatisfactory, that\nwould mean 10 minutes of the budget were spent.\n"
  },
  {
   "title": "Budget spend attribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "collapsed": true,
   "panels": [
    {
     "title": "Budget failures",
     "type": "table",
     "description": "Number of failures contributing to the budget send per component and type ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 151 },
     "targets": [
      {
       "expr": "ceil(\n  (\n    sum by (component,type,violation_type) (\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n            ) -\n            # Request with satisfactory apdex\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'apdex' , '', ''\n      )\n      or\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'error' , '', ''\n      )\n    ) > 0\n  ) * 60\n)\n"
      },
      {
       "expr": "ceil(\n  (\n    sum by (component,type,violation_type) (\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'apdex' , '', ''\n      )\n      or\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range]\n            )\n            and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__range])\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'error' , '', ''\n      )\n    ) > 0\n  ) * 60\n)\n"
      }
     ]
    },
    {
     "title": "Info",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 151 },
     "content": "This table shows the failures that contribute to the spend of the error budget.\nFixing the top item in this table will have the biggest impact on the\nbudget spend.\n\nA failure is one of 2 types:\n\n- **error**: An operation that failed: 500 response, failed background job.\n- **apdex**: This means an operation that succeeded, but did not perform within the set threshold.\n\nSee the [developer documentation](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/development/stage_group_dashboards.md#error-budget)\nto learn more about this.\n\nThe component refers to the component in our stack where the violation occurred.\nThe most common ones are:\n\n- **puma**: This component signifies requests handled by rails\n- **sidekiq_execution**: This component signifies background jobs executed by Sidekiq\n\nTo find the endpoint that is attributing to the budget spend and a violation type\nwe can use the logs over a 7 day range. Links for puma and sidekiq are available on the right.\nThese logs list the endpoints that had the most violations over the past 7 days.\n\nThe \"Other\" row is the sum of all the other violations excluding the top ones\nthat are listed.\n"
    },
    {
     "title": "Failure log links",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 151 },
     "content": "##### [Rails Requests Apdex](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(meta:(key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),(meta:(key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'3',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.request_urgency.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'3',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.target_duration_s,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'3',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,id:'3',params:(customLabel:'Operations+over+specified+threshold+(apdex)',field:json.duration_s,json:'{\"script\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value+?+1+:+0\"}'),schema:metric,type:sum))))&_g=(time:(from:'now-7d',to:'now'))): slow requests\n\nThis shows the number of requests exceeding the request duration thresholds\nconfigured per endpoint over the past 7 days.\n\nThe threshold depends on the [configurable request urgency](https://docs.gitlab.com/ee/development/application_slis/rails_request_apdex.html#adjusting-request-urgency).\n\n##### [Puma Errors](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(meta:(key:json.status,params:(gte:500),type:range),query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.request_urgency.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.target_duration_s,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): failing requests\n\nThis shows the number of Rails requests that failed per endpoint over\nthe past 7 days.\n\n##### [All request violations](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(meta:(key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),(meta:(key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'5',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.request_urgency.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'5',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,params:(field:json.target_duration_s,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'5',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,id:'3',params:(customLabel:'Operations+over+specified+threshold+(apdex)',field:json.duration_s,json:'{\"script\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value+?+1+:+0\"}'),schema:metric,type:sum),(enabled:!t,id:'4',params:(customLabel:'Failing+requests+(error)',field:json.status,json:'{\"script\":+\"doc[!'json.status!'].value+>=+500+?+1+:+0\"}'),schema:metric,type:sum),(enabled:!t,id:'5',params:(customLabel:'Total+violations+(apdex+%2B+error)',field:json.duration_s,json:'{\"script\":+\"int+errors+=+doc[!'json.status!'].value+>=+500+?+1+:+0;\\nint+slowRequests+=+doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value+?+1+:+0;\\nreturn+errors+%2B+slowRequests;\\n\"}'),schema:metric,type:sum))))&_g=(time:(from:'now-7d',to:'now'))): slow requests + failing requests\n\nThis slow loading table shows the endpoints that errored or where slow the most often\nin the past 7 days.\n\nIf `rails_requests` or `puma` are at the top of the table on the left side, then\nthis will show you the top endpoints to look into.\n\n##### [Sidekiq Execution Apdex](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(meta:(key:json.job_status,params:done,type:phrase),query:(match:(json.job_status:(query:done,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(filters:!((input:(language:kuery,query:'json.shard:+\"urgent\"+AND+json.duration_s+>+10'),label:'Jobs+exceeding+10s'),(input:(language:kuery,query:'not+json.shard:+\"urgent\"+AND+json.duration_s+>+300'),label:'Jobs+exceeding+300s'))),schema:split,type:filters),(enabled:!t,params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): slow jobs\n\nThis shows the number of jobs per worker that took longer than their threshold to\nexecute over the past 7 days.\nFor urgent jobs the threshold is 10s, this is the table on the left.\nFor other jobs the threshold is 300s, this is the table on the right.\n\n##### [Sidekiq Execution Errors](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(meta:(key:json.job_status,params:fail,type:phrase),query:(match:(json.job_status:(query:fail,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): failing jobs\n\nThis shows the number of jobs per worker that failed over the past 7 days.\nThis includes retries: if a job with a was retried 3 times, before exhausting\nits retries, this counts as 3 failures towards the budget.\n"
    }
   ]
  },
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }
  },
  {
   "title": "Overall Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab:stage_group:execution:apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
     "legendFormat": "Gitaly:Cluster apdex"
    },
    {
     "expr": "(1 - 6 * (1 - 0.9995))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - 0.9995))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab:stage_group:execution:apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
     "legendFormat": "Gitaly:Cluster apdex avg"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab:stage_group:execution:apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab:stage_group:execution:apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"} < (1 - (14.4 * (1 - 0.9995)))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab:stage_group:execution:apdex:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"} < (1 - (14.4 * (1 - 0.9995)))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab:stage_group:execution:apdex:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"} < (1 - (6 * (1 - 0.9995)))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab:stage_group:execution:apdex:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"} < (1 - (6 * (1 - 0.9995)))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "Overall | Latency/Apdex"
    }
   ]
  },
  {
   "title": "Overall Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 201 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab:stage_group:execution:error:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Gitaly:Cluster error ratio"
    },
    {
     "expr": "(6 * 0.0005)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * 0.0005)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab:stage_group:execution:error:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Gitaly:Cluster error ratio avg"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 8, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab:stage_group:execution:error:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab:stage_group:execution:error:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"} > (14.4 * 0.9995)),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab:stage_group:execution:error:ratio_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"} > (14.4 * 0.9995)),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab:stage_group:execution:error:ratio_30m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"} > (6 * 0.9995)),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab:stage_group:execution:error:ratio_6h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"} > (6 * 0.9995)),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "Overall | Errors"
    }
   ]
  },
  {
   "title": "Overall RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab:stage_group:execution:ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
     "legendFormat": "Gitaly:Cluster RPS"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "🔬 Service Level Indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 },
   "collapsed": true,
   "panels": [
    {
     "title": "goserver SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"goserver\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"goserver\",monitor=\"global\"})\n))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"goserver\",monitor=\"global\"})\n))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "goserver SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"goserver\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"goserver\",monitor=\"global\"})\n)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"goserver\",monitor=\"global\"})\n)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "goserver SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"goserver\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
     "content": "### Description\n\nThis SLI monitors all Gitaly GRPC requests in aggregate, excluding the OperationService.\nGRPC failures which are considered to be the \"server's fault\" are counted as errors.\nThe apdex score is based on a subset of GRPC methods which are expected to be fast.\n\n\n\n### Observability Tools\n\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/gitaly;type=CPU/cpu?project=gitlab-production)\n* [🐞 Sentry Releases: gitlab/gitaly-production](https://sentry.gitlab.net/gitlab/gitaly-production/releases?environment=${environment})\n* [🐞 Sentry issues](https://sentry.gitlab.net/gitlab/gitaly-production/issues?environment=${environment})\n* [📖 Kibana: Gitaly logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'AW5F1OHTiGcMMNRn84Di')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Gitaly slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.msg,params:unary,type:phrase),query:(match:(json.msg:(query:unary,type:phrase)))),(meta:(key:json.grpc.time_ms,params:(gte:1000),type:range),query:(range:(json.grpc.time_ms:(gte:1000))))),index:'AW5F1OHTiGcMMNRn84Di',sort:!(!(json.grpc.time_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Gitaly failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.grpc.code,negate:!t,params:OK,type:phrase),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(meta:(key:exists,type:json.grpc.code,value:exists),query:(exists:(field:json.grpc.code)))),index:'AW5F1OHTiGcMMNRn84Di')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.grpc.code,negate:!t,params:OK,type:phrase),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(meta:(key:exists,type:json.grpc.code,value:exists),query:(exists:(field:json.grpc.code)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.grpc.time_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "graphql_query SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"graphql_query\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"graphql_query\",monitor=\"global\"})\n))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"graphql_query\",monitor=\"global\"})\n))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "graphql_query SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"graphql_query\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "content": "### Description\n\nThe number of GraphQL queries meeting their duration target based on the urgency\nof the endpoint. By default, a query should take no more than 1s. We're working\non making the urgency customizable in [this epic](https://gitlab.com/groups/gitlab-org/-/epics/5841).\n\nMutliple queries could be batched inside a single request.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(meta:(key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s))),(meta:(key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value'))))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(meta:(key:json.status,params:(gte:500),type:range),query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(meta:(key:json.status,params:(gte:500),type:range),query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "praefect_cloudsql SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"praefect_cloudsql\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"praefect_cloudsql\",monitor=\"global\"})\n)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"praefect_cloudsql\",monitor=\"global\"})\n)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "praefect_cloudsql SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"praefect_cloudsql\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "content": "### Description\n\nPraefect uses a GCP CloudSQL instance. This SLI represents SQL transactions to that service.\n\n\n\n### Observability Tools\n\n* [Cloud SQL](https://console.cloud.google.com/sql/instances/praefect-db-9dfb/overview?project=gitlab-production)\n* [Stackdriver Logs: Cloud SQL praefect-db-9dfb](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Edatabase%5Fid%3D%22gitlab%2Dproduction%3Apraefect%2Ddb%2D9dfb%22%0Aresource%2Elabels%2Eproject%5Fid%3D%22gitlab%2Dproduction%22%0Aresource%2Etype%3D%22cloudsql%5Fdatabase%22;timeRange=PT30M?project=gitlab-production)\n\n"
    },
    {
     "title": "proxy SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"proxy\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"proxy\",monitor=\"global\"})\n))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"proxy\",monitor=\"global\"})\n))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "proxy SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"proxy\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"proxy\",monitor=\"global\"})\n)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"proxy\",monitor=\"global\"})\n)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "proxy SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"proxy\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
     "content": "### Description\n\nAll Gitaly operations pass through the Praefect proxy on the way to a Gitaly instance. This SLI monitors\nthose operations in aggregate.\n\n\n\n### Observability Tools\n\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/praefect;type=CPU/cpu?project=gitlab-production)\n* [🐞 Sentry Releases: gitlab/praefect-production](https://sentry.gitlab.net/gitlab/praefect-production/releases?environment=${environment})\n* [🐞 Sentry issues](https://sentry.gitlab.net/gitlab/praefect-production/issues?environment=${environment})\n* [📖 Kibana: Praefect logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.virtual_storage,json.grpc.method,json.relative_path,json.grpc.code,json.grpc.time_ms),filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'AW98WAQvqthdGjPJ8jTY')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Praefect slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.virtual_storage,json.grpc.method,json.relative_path,json.grpc.code,json.grpc.time_ms),filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.msg,params:unary,type:phrase),query:(match:(json.msg:(query:unary,type:phrase)))),(meta:(key:json.grpc.time_ms,params:(gte:1000),type:range),query:(range:(json.grpc.time_ms:(gte:1000))))),index:'AW98WAQvqthdGjPJ8jTY',sort:!(!(json.grpc.time_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Praefect failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.virtual_storage,json.grpc.method,json.relative_path,json.grpc.code,json.grpc.time_ms),filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.grpc.code,negate:!t,params:OK,type:phrase),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(meta:(key:exists,type:json.grpc.code,value:exists),query:(exists:(field:json.grpc.code)))),index:'AW98WAQvqthdGjPJ8jTY')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.grpc.code,negate:!t,params:OK,type:phrase),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(meta:(key:exists,type:json.grpc.code,value:exists),query:(exists:(field:json.grpc.code)))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.grpc.time_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "rails_request SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\"})\n))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"rails_request\",monitor=\"global\"})\n))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "rails_request SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\"})\n)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"rails_request\",monitor=\"global\"})\n)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "rails_request SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"rails_request\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 40 },
     "content": "### Description\n\nThe number of requests meeting their duration target based on the urgency\nof the endpoint. By default, a request should take no more than 1s. But\nthis can be adjusted by endpoint.\n\nRead more about this in the [documentation](https://docs.gitlab.com/ee/development/application_slis/rails_request_apdex.html).\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(meta:(key:exists,type:json.target_duration_s,value:exists),query:(exists:(field:json.target_duration_s))),(meta:(key:exists,type:json.duration_s,value:exists),query:(exists:(field:json.duration_s))),!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"script\":+{\"script\":+{\"source\":+\"doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value\"}}}]}}'),query:(bool:(minimum_should_match:1,should:!((script:(script:(source:'doc[!'json.duration_s!'].value+>+doc[!'json.target_duration_s!'].value'))))))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.status,json.method,json.meta.caller_id,json.meta.feature_category,json.path,json.request_urgency,json.duration_s,json.target_duration_s),filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(meta:(key:json.status,params:(gte:500),type:range),query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(meta:(key:json.status,params:(gte:500),type:range),query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:json.subcomponent,negate:!t,params:graphql_json,type:phrase),query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(meta:(key:json.stage,params:'$stage',type:phrase),query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(key:json.meta.feature_category,params:!(gitaly),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "replicator_queue SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"replicator_queue\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"replicator_queue\",monitor=\"global\"})\n))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{component=\"replicator_queue\",monitor=\"global\"})\n))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "replicator_queue SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"replicator_queue\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly_cluster\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
     "content": "### Description\n\nPraefect replication operations. Latency represents the queuing delay before replication is carried out.\n\n"
    }
   ]
  }
 ]
}