{
 "title": "stage-groups: Gitaly: stage group error budget detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/2076237607 at Thu Feb 10 05:09:17 UTC 2022",
 "tags": [
  "managed",
  "stage-groups",
  "feature_category"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  { "title": "Error Budget (past 28 days)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n",
     "legendFormat": "%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "Budget remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209\n-\n(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * 2419200\n)\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209\n-\n(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * 2419200\n)\n\n"
    }
   ]
  },
  {
   "title": "Budget spent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * 2419200\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * 2419200\n)\n"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 100 },
   "content": "### [Error budget](https://about.gitlab.com/handbook/engineering/error-budgets/)\n\nThese error budget panels show an aggregate of SLIs across all components.\nHowever, not all components have been implemented yet.\n\nThe [handbook](https://about.gitlab.com/handbook/engineering/error-budgets/)\nexplains how these budgets are used.\n\nRead more about how the error budgets are calculated in the\n[stage group dashboard documentation](https://docs.gitlab.com/ee/development/stage_group_dashboards.html#error-budget).\n\nThe error budget is compared to our SLO of 99.95% and is always in\na range of 28 days from the selected end date in Grafana.\n\n### Availability\n\nThe availability shows the percentage of operations labeled with one of the\ncategories owned by Gitaly with satisfactory completion.\n\n### Budget remaining\n\nThe error budget in minutes is calculated based on the 99.95%.\nThere are 40320 minutes in 28 days, we allow 0.05% of failures, which\nmeans the budget in minutes is 20 minutes.\n\nThe budget remaining shows how many minutes have not been spent in the\npast 28 days.\n\n### Minutes spent\n\nThis shows the total minutes spent over the past 28 days.\n\nFor example, if there were 403200 (28 * 24 * 60) operations in 28 days.\nThis would be 1 every minute. If 10 of those were unsatisfactory, that\nwould mean 10 minutes of the budget were spent.\n"
  },
  {
   "title": "Budget spend attribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "title": "Budget failures",
     "type": "table",
     "description": "Number of failures contributing to the budget send per component and type ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "ceil(\n  (\n    sum by (component,type,violation_type) (\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n            ) -\n            # Request with satisfactory apdex\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'apdex' , '', ''\n      )\n      or\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'error' , '', ''\n      )\n    ) > 0\n  ) * 60\n)\n"
      },
      {
       "expr": "ceil(\n  (\n    sum by (component,type,violation_type) (\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'apdex' , '', ''\n      )\n      or\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d]\n            )\n            and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[28d])\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'error' , '', ''\n      )\n    ) > 0\n  ) * 60\n)\n"
      }
     ]
    },
    {
     "title": "Info",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 111 },
     "content": "This table shows the failures that contribute to the spend of the error budget.\nFixing the top item in this table will have the biggest impact on the\nbudget spend.\n\nA failure is one of 2 types:\n\n- **error**: An operation that failed: 500 response, failed background job.\n- **apdex**: This means an operation that succeeded, but did not perform within the set threshold.\n\nSee the [developer documentation](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/development/stage_group_dashboards.md#error-budget)\nto learn more about this.\n\nThe component refers to the component in our stack where the violation occurred.\nThe most common ones are:\n\n- **puma**: This component signifies requests handled by rails\n- **sidekiq_execution**: This component signifies background jobs executed by Sidekiq\n\nTo find the endpoint that is attributing to the budget spend and a violation type\nwe can use the logs over a 7 day range. Links for puma and sidekiq are available on the right.\nThese logs list the endpoints that had the most violations over the past 7 days.\n\nThe \"Other\" row is the sum of all the other violations excluding the top ones\nthat are listed.\n"
    },
    {
     "title": "Failure log links",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 111 },
     "content": "##### [Puma Apdex](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"match_phrase\":+{\"json.meta.feature_category\":+\"gitaly\"}}]}}'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'3',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,id:'3',params:(customLabel:'Operations+over+threshold+(1s)',field:json.duration_s,json:'{\"script\":+\"doc[!'json.duration_s!'].value+>=+1+?+1+:+0\"}'),schema:metric,type:sum),(enabled:!t,id:'4',params:(customLabel:'Operations+over+error+budget+threshold+(5s)',field:json.duration_s,json:'{\"script\":+\"doc[!'json.duration_s!'].value+>=+5+?+1+:+0\"}'),schema:metric,type:sum))))&_g=(time:(from:'now-7d',to:'now'))): slow requests\n\nThis shows the number of requests exceeding the request duration thresholds\nper endpoint over the past 7 days.\n\nThis shows all requests exceeding 1s and 5s durations. We will make this\ntake the configured [request urgency](https://docs.gitlab.com/ee/development/application_slis/rails_request_apdex.html#adjusting-request-urgency) into account in\n[this issue](https://gitlab.com/gitlab-com/gl-infra/scalability/-/issues/1478).\n\n##### [Puma Errors](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"match_phrase\":+{\"json.meta.feature_category\":+\"gitaly\"}}]}}'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): failing requests\n\nThis shows the number of Rails requests that failed per endpoint over\nthe past 7 days.\n\n##### [Sidekiq Execution Apdex](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"match_phrase\":+{\"json.meta.feature_category\":+\"gitaly\"}}]}}'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(query:(match:(json.job_status:(query:done,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(filters:!((input:(language:kuery,query:'json.shard:+\"urgent\"+AND+json.duration_s+>+10'),label:'Jobs+exceeding+10s'),(input:(language:kuery,query:'not+json.shard:+\"urgent\"+AND+json.duration_s+>+300'),label:'Jobs+exceeding+300s'))),schema:split,type:filters),(enabled:!t,params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): slow jobs\n\nThis shows the number of jobs per worker that took longer than their threshold to\nexecute over the past 7 days.\nFor urgent jobs the threshold is 10s, this is the table on the left.\nFor other jobs the threshold is 300s, this is the table on the right.\n\n##### [Sidekiq Execution Errors](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"match_phrase\":+{\"json.meta.feature_category\":+\"gitaly\"}}]}}'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:gitaly)))))),(query:(match:(json.job_status:(query:fail,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): failing jobs\n\nThis shows the number of jobs per worker that failed over the past 7 days.\nThis includes retries: if a job with a was retried 3 times, before exhausting\nits retries, this counts as 3 failures towards the budget.\n"
    }
   ]
  },
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }
  },
  {
   "title": "Overall Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab:stage_group:execution:apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
     "legendFormat": "Gitaly apdex"
    },
    {
     "expr": "(1 - 6 * (1 - 0.9995))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - 0.9995))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab:stage_group:execution:apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
     "legendFormat": "Gitaly apdex avg"
    }
   ]
  },
  {
   "title": "Overall Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 201 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab:stage_group:execution:error:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Gitaly error ratio"
    },
    {
     "expr": "(6 * 0.0005)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * 0.0005)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab:stage_group:execution:error:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Gitaly error ratio avg"
    }
   ]
  },
  {
   "title": "Overall RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab:stage_group:execution:ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
     "legendFormat": "Gitaly RPS"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "🔬 Service Level Indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 },
   "collapsed": true,
   "panels": [
    {
     "title": "gitalyruby SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"gitalyruby\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "gitalyruby SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"gitalyruby\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * 0.0005)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * 0.0005)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "gitalyruby SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"gitalyruby\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
     "content": "### Description\n\nThis SLI monitors requests to Gitaly's Ruby sidecar, known as Gitaly-Ruby. All requests made to\nGitaly-Ruby are monitored in aggregate, via its GRPC interface.\n\n\n\n### Observability Tools\n\n* [🐞 Sentry Releases: gitlab/gitlabcom-gitaly-ruby](https://sentry.gitlab.net/gitlab/gitlabcom-gitaly-ruby/releases?environment=${environment})\n* [🐞 Sentry issues](https://sentry.gitlab.net/gitlab/gitlabcom-gitaly-ruby/issues?environment=${environment})\n* [📖 Kibana: Gitaly Ruby logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((query:(match:(json.tag.keyword:(query:gitaly.ruby,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'AW5F1OHTiGcMMNRn84Di')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Gitaly Ruby failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((query:(match:(json.tag.keyword:(query:gitaly.ruby,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(negate:!t),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(exists:(field:json.grpc.code))),index:'AW5F1OHTiGcMMNRn84Di')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly Ruby requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.tag.keyword:(query:gitaly.ruby,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly Ruby failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.tag.keyword:(query:gitaly.ruby,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(negate:!t),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(exists:(field:json.grpc.code))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly Ruby sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.tag.keyword:(query:gitaly.ruby,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly Ruby sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.tag.keyword:(query:gitaly.ruby,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly Ruby percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.tag.keyword:(query:gitaly.ruby,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly Ruby percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.tag.keyword:(query:gitaly.ruby,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.grpc.time_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "goserver SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"goserver\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "goserver SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"goserver\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * 0.0005)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * 0.0005)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "goserver SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"goserver\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "content": "### Description\n\nThis SLI monitors all Gitaly GRPC requests in aggregate, excluding the OperationService.\nGRPC failures which are considered to be the \"server's fault\" are counted as errors.\nThe apdex score is based on a subset of GRPC methods which are expected to be fast.\n\n\n\n### Observability Tools\n\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/gitaly;type=CPU/cpu?project=gitlab-production)\n* [🐞 Sentry Releases: gitlab/gitaly-production](https://sentry.gitlab.net/gitlab/gitaly-production/releases?environment=${environment})\n* [🐞 Sentry issues](https://sentry.gitlab.net/gitlab/gitaly-production/issues?environment=${environment})\n* [📖 Kibana: Gitaly logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'AW5F1OHTiGcMMNRn84Di')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Gitaly slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.msg:(query:unary,type:phrase)))),(query:(range:(json.grpc.time_ms:(gte:1000))))),index:'AW5F1OHTiGcMMNRn84Di',sort:!(!(json.grpc.time_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Gitaly failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(negate:!t),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(exists:(field:json.grpc.code))),index:'AW5F1OHTiGcMMNRn84Di')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(negate:!t),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(exists:(field:json.grpc.code))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.grpc.time_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "goserver_op_service SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"goserver_op_service\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * 0.0005)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * 0.0005)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "goserver_op_service SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"goserver_op_service\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "content": "### Description\n\nThis SLI monitors requests to Gitaly's OperationService, via its GRPC endpoint.\nOperationService methods are generally expected to be slower than other Gitaly endpoints\nand this is reflected in the SLI.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Gitaly OperationService logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((query:(match:(json.grpc.service:(query:gitaly.OperationService,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'AW5F1OHTiGcMMNRn84Di')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Gitaly OperationService slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((query:(match:(json.grpc.service:(query:gitaly.OperationService,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.msg:(query:unary,type:phrase)))),(query:(range:(json.grpc.time_ms:(gte:30000))))),index:'AW5F1OHTiGcMMNRn84Di',sort:!(!(json.grpc.time_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Gitaly OperationService failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.grpc.method,json.grpc.request.glProjectPath,json.grpc.code,json.grpc.time_ms),filters:!((query:(match:(json.grpc.service:(query:gitaly.OperationService,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(negate:!t),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(exists:(field:json.grpc.code))),index:'AW5F1OHTiGcMMNRn84Di')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly OperationService requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.grpc.service:(query:gitaly.OperationService,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly OperationService failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.grpc.service:(query:gitaly.OperationService,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(negate:!t),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(exists:(field:json.grpc.code))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly OperationService sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.grpc.service:(query:gitaly.OperationService,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly OperationService sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.grpc.service:(query:gitaly.OperationService,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly OperationService percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.grpc.service:(query:gitaly.OperationService,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Gitaly OperationService percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW5F1OHTiGcMMNRn84Di&_a=(filters:!((query:(match:(json.grpc.service:(query:gitaly.OperationService,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.grpc.time_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "graphql_queries SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"graphql_queries\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "graphql_queries SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"graphql_queries\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
     "content": "### Description\n\nThe number of GraphQL queries meeting their duration target based on the urgency\nof the endpoint. By default, a query should take no more than 1s. We're working\non making the urgency customizable in [this epic](https://gitlab.com/groups/gitlab-org/-/epics/5841).\n\nMutliple queries could be batched inside a single request.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.duration_s:(gte:1))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "praefect_cloudsql SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"praefect_cloudsql\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * 0.0005)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * 0.0005)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "praefect_cloudsql SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"praefect_cloudsql\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
     "content": "### Description\n\nPraefect uses a GCP CloudSQL instance. This SLI represents SQL transactions to that service.\n\n\n\n### Observability Tools\n\n* [Cloud SQL](https://console.cloud.google.com/sql/instances/praefect-db-9dfb/overview?project=gitlab-production)\n* [Stackdriver Logs: Cloud SQL praefect-db-9dfb](https://console.cloud.google.com/logs/query;query=resource%2Elabels%2Edatabase%5Fid%3D%22gitlab%2Dproduction%3Apraefect%2Ddb%2D9dfb%22%0Aresource%2Elabels%2Eproject%5Fid%3D%22gitlab%2Dproduction%22%0Aresource%2Etype%3D%22cloudsql%5Fdatabase%22;timeRange=PT30M?project=gitlab-production)\n\n"
    },
    {
     "title": "proxy SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"proxy\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "proxy SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"proxy\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * 0.0005)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * 0.0005)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "proxy SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"proxy\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 50 },
     "content": "### Description\n\nAll Gitaly operations pass through the Praefect proxy on the way to a Gitaly instance. This SLI monitors\nthose operations in aggregate.\n\n\n\n### Observability Tools\n\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/praefect;type=CPU/cpu?project=gitlab-production)\n* [🐞 Sentry Releases: gitlab/praefect-production](https://sentry.gitlab.net/gitlab/praefect-production/releases?environment=${environment})\n* [🐞 Sentry issues](https://sentry.gitlab.net/gitlab/praefect-production/issues?environment=${environment})\n* [📖 Kibana: Praefect logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.virtual_storage,json.grpc.method,json.relative_path,json.grpc.code,json.grpc.time_ms),filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'AW98WAQvqthdGjPJ8jTY')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Praefect slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.virtual_storage,json.grpc.method,json.relative_path,json.grpc.code,json.grpc.time_ms),filters:!((query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.msg:(query:unary,type:phrase)))),(query:(range:(json.grpc.time_ms:(gte:1000))))),index:'AW98WAQvqthdGjPJ8jTY',sort:!(!(json.grpc.time_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Praefect failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.hostname,json.virtual_storage,json.grpc.method,json.relative_path,json.grpc.code,json.grpc.time_ms),filters:!((query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(negate:!t),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(exists:(field:json.grpc.code))),index:'AW98WAQvqthdGjPJ8jTY')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase)))),(meta:(negate:!t),query:(match:(json.grpc.code:(query:OK,type:phrase)))),(exists:(field:json.grpc.code))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Praefect percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=AW98WAQvqthdGjPJ8jTY&_a=(filters:!((query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.grpc.time_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.grpc.method.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.grpc.time_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.grpc.time_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "puma SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"puma\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * 0.0005)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * 0.0005)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "puma SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"puma\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 60 },
     "content": "### Description\n\nThis SLI monitors API traffic in aggregate, in the GitLab rails monolith, via its\nHTTP interface. 5xx responses are treated as failures.\n\n\n\n### Observability Tools\n\n* [🐞 Sentry Releases: gitlab/gitlabcom](https://sentry.gitlab.net/gitlab/gitlabcom/releases?environment=${environment})\n* [🐞 Sentry api issues](https://sentry.gitlab.net/gitlab/gitlabcom/issues?environment=${environment}&query=stage%3A${stage}+type%3Aapi)\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.duration_s:(gte:10))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "rails_requests SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "rails_requests SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 70 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 70 },
     "content": "### Description\n\nThe number of requests meeting their duration target based on the urgency\nof the endpoint. By default, a request should take no more than 1s. But\nthis can be adjusted by endpoint.\n\nRead more about this in the [documentation](https://docs.gitlab.com/ee/development/application_slis/rails_request_apdex.html).\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.duration_s:(gte:5))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "replicator_queue SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"replicator_queue\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "replicator_queue SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 80 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"replicator_queue\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"gitaly\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 80 },
     "content": "### Description\n\nPraefect replication operations. Latency represents the queuing delay before replication is carried out.\n\n"
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: gitalyruby",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 gitalyruby Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by ([\"le\"]) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",stage=\"$stage\"}[$__interval]) and on(grpc_service,grpc_method) grpc_client_handled_total{job=\"gitaly\"}\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "gitalyruby Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(grpc_client_handled_total{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_code!~\"AlreadyExists|DeadlineExceeded|FailedPrecondition|NotFound|OK|Unauthenticated\",grpc_method!~\"AddRemote|UpdateRemoteMirror\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "gitalyruby RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(grpc_client_handled_total{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 gitalyruby Latency - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (fqdn[\"le\"]) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",stage=\"$stage\"}[$__interval]) and on(grpc_service,grpc_method) grpc_client_handled_total{job=\"gitaly\"}\n  )\n)\n > 0",
       "legendFormat": "p95 {{fqdn}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for gitalyruby Latency - per fqdn",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (fqdn) (\n  rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_method!~\"CalculateChecksum|CommitLanguages|CommitStats|CreateFork|CreateRepositoryFromURL|FetchInternalRemote|FetchIntoObjectPool|FetchRemote|FetchSourceBranch|FindRemoteRepository|FindRemoteRootRef|Fsck|GarbageCollect|GetAllLFSPointers|GetLFSPointers|OptimizeRepository|PackObjectsHookWithSidechannel|PostReceiveHook|PostUploadPackWithSidechannel|PreReceiveHook|RepackFull|RepackIncremental|ReplicateRepository|SSHUploadPackWithSidechannel|UpdateHook\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"+Inf\",stage=\"$stage\"}[$__interval]) and on(grpc_service,grpc_method) grpc_client_handled_total{job=\"gitaly\"}\n)\n\n    -\n    (\n      (\n  sum by (fqdn) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_method!~\"CalculateChecksum|CommitLanguages|CommitStats|CreateFork|CreateRepositoryFromURL|FetchInternalRemote|FetchIntoObjectPool|FetchRemote|FetchSourceBranch|FindRemoteRepository|FindRemoteRootRef|Fsck|GarbageCollect|GetAllLFSPointers|GetLFSPointers|OptimizeRepository|PackObjectsHookWithSidechannel|PostReceiveHook|PostUploadPackWithSidechannel|PreReceiveHook|RepackFull|RepackIncremental|ReplicateRepository|SSHUploadPackWithSidechannel|UpdateHook\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"10\",stage=\"$stage\"}[$__interval]) and on(grpc_service,grpc_method) grpc_client_handled_total{job=\"gitaly\"}\n  )\n  +\n  sum by (fqdn) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_method!~\"CalculateChecksum|CommitLanguages|CommitStats|CreateFork|CreateRepositoryFromURL|FetchInternalRemote|FetchIntoObjectPool|FetchRemote|FetchSourceBranch|FindRemoteRepository|FindRemoteRootRef|Fsck|GarbageCollect|GetAllLFSPointers|GetLFSPointers|OptimizeRepository|PackObjectsHookWithSidechannel|PostReceiveHook|PostUploadPackWithSidechannel|PreReceiveHook|RepackFull|RepackIncremental|ReplicateRepository|SSHUploadPackWithSidechannel|UpdateHook\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"30\",stage=\"$stage\"}[$__interval]) and on(grpc_service,grpc_method) grpc_client_handled_total{job=\"gitaly\"}\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(fqdn) group_left()\n  (\n    sum by () (\n  rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_method!~\"CalculateChecksum|CommitLanguages|CommitStats|CreateFork|CreateRepositoryFromURL|FetchInternalRemote|FetchIntoObjectPool|FetchRemote|FetchSourceBranch|FindRemoteRepository|FindRemoteRootRef|Fsck|GarbageCollect|GetAllLFSPointers|GetLFSPointers|OptimizeRepository|PackObjectsHookWithSidechannel|PostReceiveHook|PostUploadPackWithSidechannel|PreReceiveHook|RepackFull|RepackIncremental|ReplicateRepository|SSHUploadPackWithSidechannel|UpdateHook\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"+Inf\",stage=\"$stage\"}[$__interval]) and on(grpc_service,grpc_method) grpc_client_handled_total{job=\"gitaly\"}\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "gitalyruby Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  rate(grpc_client_handled_total{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_code!~\"AlreadyExists|DeadlineExceeded|FailedPrecondition|NotFound|OK|Unauthenticated\",grpc_method!~\"AddRemote|UpdateRemoteMirror\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "gitalyruby RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  rate(grpc_client_handled_total{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "Estimated p95 gitalyruby Latency - per grpc_method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (grpc_method[\"le\"]) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_method!=\"\",stage=\"$stage\"}[$__interval]) and on(grpc_service,grpc_method) grpc_client_handled_total{job=\"gitaly\"}\n  )\n)\n > 0",
       "legendFormat": "p95 {{grpc_method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for gitalyruby Latency - per grpc_method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (grpc_method) (\n  rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_method!=\"\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"+Inf\",stage=\"$stage\"}[$__interval]) and on(grpc_service,grpc_method) grpc_client_handled_total{job=\"gitaly\"}\n)\n\n    -\n    (\n      (\n  sum by (grpc_method) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_method!=\"\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"10\",stage=\"$stage\"}[$__interval]) and on(grpc_service,grpc_method) grpc_client_handled_total{job=\"gitaly\"}\n  )\n  +\n  sum by (grpc_method) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_method!=\"\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"30\",stage=\"$stage\"}[$__interval]) and on(grpc_service,grpc_method) grpc_client_handled_total{job=\"gitaly\"}\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(grpc_method) group_left()\n  (\n    sum by () (\n  rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_method!=\"\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"+Inf\",stage=\"$stage\"}[$__interval]) and on(grpc_service,grpc_method) grpc_client_handled_total{job=\"gitaly\"}\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "gitalyruby Errors - per grpc_method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_method) (\n  rate(grpc_client_handled_total{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_code!~\"AlreadyExists|DeadlineExceeded|FailedPrecondition|NotFound|OK|Unauthenticated\",grpc_method!=\"\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "gitalyruby RPS - per grpc_method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (grpc_method) (\n  rate(grpc_client_handled_total{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_method!=\"\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: goserver",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1210 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 goserver Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_method!~\"CalculateChecksum|CommitLanguages|CommitStats|CreateFork|CreateRepositoryFromURL|FetchInternalRemote|FetchIntoObjectPool|FetchRemote|FetchSourceBranch|FindRemoteRepository|FindRemoteRootRef|Fsck|GarbageCollect|OptimizeRepository|PackObjectsHookWithSidechannel|PostReceiveHook|PostUploadPackWithSidechannel|PreReceiveHook|RepackFull|RepackIncremental|ReplicateRepository|SSHUploadPackWithSidechannel|UpdateHook\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "goserver Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  label_replace(rate(gitaly_service_client_requests_total{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_code!~\"AlreadyExists|Canceled|DeadlineExceeded|FailedPrecondition|InvalidArgument|NotFound|OK|Unauthenticated\",grpc_service!=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(gitaly_service_client_requests_total{deadline_type!=\"limited\",environment=\"$environment\",feature_category=~\"gitaly|\",grpc_code=\"DeadlineExceeded\",grpc_service!=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "goserver RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitaly_service_client_requests_total{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_service!=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 goserver Latency - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (fqdn,le) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_method!~\"CalculateChecksum|CommitLanguages|CommitStats|CreateFork|CreateRepositoryFromURL|FetchInternalRemote|FetchIntoObjectPool|FetchRemote|FetchSourceBranch|FindRemoteRepository|FindRemoteRootRef|Fsck|GarbageCollect|OptimizeRepository|PackObjectsHookWithSidechannel|PostReceiveHook|PostUploadPackWithSidechannel|PreReceiveHook|RepackFull|RepackIncremental|ReplicateRepository|SSHUploadPackWithSidechannel|UpdateHook\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{fqdn}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for goserver Latency - per fqdn",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (fqdn) (\n  rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_method!~\"CalculateChecksum|CommitLanguages|CommitStats|CreateFork|CreateRepositoryFromURL|FetchInternalRemote|FetchIntoObjectPool|FetchRemote|FetchSourceBranch|FindRemoteRepository|FindRemoteRootRef|Fsck|GarbageCollect|OptimizeRepository|PackObjectsHookWithSidechannel|PostReceiveHook|PostUploadPackWithSidechannel|PreReceiveHook|RepackFull|RepackIncremental|ReplicateRepository|SSHUploadPackWithSidechannel|UpdateHook\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (fqdn) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_method!~\"CalculateChecksum|CommitLanguages|CommitStats|CreateFork|CreateRepositoryFromURL|FetchInternalRemote|FetchIntoObjectPool|FetchRemote|FetchSourceBranch|FindRemoteRepository|FindRemoteRootRef|Fsck|GarbageCollect|OptimizeRepository|PackObjectsHookWithSidechannel|PostReceiveHook|PostUploadPackWithSidechannel|PreReceiveHook|RepackFull|RepackIncremental|ReplicateRepository|SSHUploadPackWithSidechannel|UpdateHook\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"0.5\",stage=\"$stage\"}[$__interval])\n  )\n  +\n  sum by (fqdn) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_method!~\"CalculateChecksum|CommitLanguages|CommitStats|CreateFork|CreateRepositoryFromURL|FetchInternalRemote|FetchIntoObjectPool|FetchRemote|FetchSourceBranch|FindRemoteRepository|FindRemoteRootRef|Fsck|GarbageCollect|OptimizeRepository|PackObjectsHookWithSidechannel|PostReceiveHook|PostUploadPackWithSidechannel|PreReceiveHook|RepackFull|RepackIncremental|ReplicateRepository|SSHUploadPackWithSidechannel|UpdateHook\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"1\",stage=\"$stage\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(fqdn) group_left()\n  (\n    sum by () (\n  rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_method!~\"CalculateChecksum|CommitLanguages|CommitStats|CreateFork|CreateRepositoryFromURL|FetchInternalRemote|FetchIntoObjectPool|FetchRemote|FetchSourceBranch|FindRemoteRepository|FindRemoteRootRef|Fsck|GarbageCollect|OptimizeRepository|PackObjectsHookWithSidechannel|PostReceiveHook|PostUploadPackWithSidechannel|PreReceiveHook|RepackFull|RepackIncremental|ReplicateRepository|SSHUploadPackWithSidechannel|UpdateHook\",grpc_service!=\"gitaly.OperationService\",grpc_type=\"unary\",job=\"gitaly\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "goserver Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  label_replace(rate(gitaly_service_client_requests_total{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_code!~\"AlreadyExists|Canceled|DeadlineExceeded|FailedPrecondition|InvalidArgument|NotFound|OK|Unauthenticated\",grpc_service!=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(gitaly_service_client_requests_total{deadline_type!=\"limited\",environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_code=\"DeadlineExceeded\",grpc_service!=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "goserver RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  rate(gitaly_service_client_requests_total{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_service!=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: goserver_op_service",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1220 },
   "collapsed": true,
   "panels": [
    {
     "title": "goserver_op_service Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  label_replace(rate(gitaly_service_client_requests_total{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_code!~\"AlreadyExists|Canceled|DeadlineExceeded|FailedPrecondition|InvalidArgument|NotFound|OK|Unauthenticated\",grpc_service=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(gitaly_service_client_requests_total{deadline_type!=\"limited\",environment=\"$environment\",feature_category=~\"gitaly|\",grpc_code=\"DeadlineExceeded\",grpc_service=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "goserver_op_service RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitaly_service_client_requests_total{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_service=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "goserver_op_service Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  label_replace(rate(gitaly_service_client_requests_total{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_code!~\"AlreadyExists|Canceled|DeadlineExceeded|FailedPrecondition|InvalidArgument|NotFound|OK|Unauthenticated\",grpc_service=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval]), \"_c\", \"0\", \"\", \"\")\n  or\n  label_replace(rate(gitaly_service_client_requests_total{deadline_type!=\"limited\",environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_code=\"DeadlineExceeded\",grpc_service=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval]), \"_c\", \"1\", \"\", \"\")\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "goserver_op_service RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  rate(gitaly_service_client_requests_total{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_service=\"gitaly.OperationService\",job=\"gitaly\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: graphql_queries",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1230 },
   "collapsed": true,
   "panels": [
    {
     "title": "graphql_queries RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_queries Latency - per endpoint_id",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:success_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (endpoint_id) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "graphql_queries RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_queries Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:success_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "graphql_queries RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_queries Latency - per query_urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (query_urgency) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n    )\n    -\n    sum by (query_urgency) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:success_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (query_urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{query_urgency}}"
      }
     ]
    },
    {
     "title": "graphql_queries RPS - per query_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (query_urgency) (\n  sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{query_urgency}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: praefect_cloudsql",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1240 },
   "collapsed": true,
   "panels": [
    {
     "title": "praefect_cloudsql Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  avg_over_time(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_postgresql_transaction_count{database=\"praefect_production\",environment=\"$environment\",feature_category=~\"gitaly|\",job=\"stackdriver\",stage=\"$stage\",transaction_type=\"rollback\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "praefect_cloudsql RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  avg_over_time(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_postgresql_transaction_count{database=\"praefect_production\",environment=\"$environment\",feature_category=~\"gitaly|\",job=\"stackdriver\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: proxy",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1250 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 proxy Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_type=\"unary\",job=\"praefect\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "proxy Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(grpc_server_handled_total{environment=\"$environment\",feature_category=~\"gitaly|\",grpc_code!~\"^(OK|NotFound|Unauthenticated|AlreadyExists|FailedPrecondition|Canceled)$\",job=\"praefect\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "proxy RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(grpc_server_handled_total{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"praefect\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 proxy Latency - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (fqdn,le) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_type=\"unary\",job=\"praefect\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{fqdn}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for proxy Latency - per fqdn",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (fqdn) (\n  rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_type=\"unary\",job=\"praefect\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (fqdn) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_type=\"unary\",job=\"praefect\",le=\"0.5\",stage=\"$stage\"}[$__interval])\n  )\n  +\n  sum by (fqdn) (\n    rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_type=\"unary\",job=\"praefect\",le=\"1\",stage=\"$stage\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(fqdn) group_left()\n  (\n    sum by () (\n  rate(grpc_server_handling_seconds_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_type=\"unary\",job=\"praefect\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "proxy Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  rate(grpc_server_handled_total{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",grpc_code!~\"^(OK|NotFound|Unauthenticated|AlreadyExists|FailedPrecondition|Canceled)$\",job=\"praefect\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "proxy RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  rate(grpc_server_handled_total{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",job=\"praefect\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: puma",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1260 },
   "collapsed": true,
   "panels": [
    {
     "title": "puma Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "puma RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "puma Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",job=\"gitlab-rails\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "puma RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "puma Errors - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",method!=\"\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "puma RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",method!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "puma Errors - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "puma RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: rails_requests",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1270 },
   "collapsed": true,
   "panels": [
    {
     "title": "rails_requests RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_requests Latency - per endpoint_id",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:success_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (endpoint_id) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "rails_requests RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_requests Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:success_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "rails_requests RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_requests Latency - per request_urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (request_urgency) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n    )\n    -\n    sum by (request_urgency) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:success_total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (request_urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    },
    {
     "title": "rails_requests RPS - per request_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (request_urgency) (\n  sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: replicator_queue",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1280 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 replicator_queue Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"praefect\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "replicator_queue RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"praefect\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 replicator_queue Latency - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (fqdn,le) (\n    rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",job=\"praefect\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{fqdn}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for replicator_queue Latency - per fqdn",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (fqdn) (\n  rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",job=\"praefect\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      sum by (fqdn) (\n  rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",job=\"praefect\",le=\"300\",stage=\"$stage\"}[$__interval])\n)\n\n    )\n  )\n  / ignoring(fqdn) group_left()\n  (\n    sum by () (\n  rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",job=\"praefect\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "replicator_queue RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",fqdn!=\"\",job=\"praefect\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "Estimated p95 replicator_queue Latency - per type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,type) (\n    rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"praefect\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{type}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for replicator_queue Latency - per type",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (type) (\n  rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"praefect\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      sum by (type) (\n  rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"praefect\",le=\"300\",stage=\"$stage\"}[$__interval])\n)\n\n    )\n  )\n  / ignoring(type) group_left()\n  (\n    sum by () (\n  rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"praefect\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "replicator_queue RPS - per type",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (\n  rate(gitaly_praefect_replication_delay_bucket{environment=\"$environment\",feature_category=~\"gitaly|\",job=\"praefect\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}