{
 "title": "stage-groups: Package: stage group error budget detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/2076237607 at Thu Feb 10 05:09:17 UTC 2022",
 "tags": [
  "managed",
  "stage-groups",
  "feature_category"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  { "title": "Error Budget (past 28 days)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n",
     "legendFormat": "%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n"
    }
   ]
  },
  {
   "title": "Budget remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209\n-\n(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * 2419200\n)\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# The number of seconds allowed to be spent in 28d\n1209\n-\n(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * 2419200\n)\n\n"
    }
   ]
  },
  {
   "title": "Budget spent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * 2419200\n)\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n     1 - clamp_max(\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        -\n        sum_over_time(\n          gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ), 'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  )\n  /\n  sum by ()(\n    sum by (stage_group,component) (\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        ),\n        'sli_kind', 'apdex', '', ''\n      )\n      or\n      label_replace(\n        sum_over_time(\n          gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n        )\n        and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]),\n        'sli_kind', 'error', '', ''\n      )\n    ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n  ),\n1)\n\n  ) * 2419200\n)\n"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 100 },
   "content": "### [Error budget](https://about.gitlab.com/handbook/engineering/error-budgets/)\n\nThese error budget panels show an aggregate of SLIs across all components.\nHowever, not all components have been implemented yet.\n\nThe [handbook](https://about.gitlab.com/handbook/engineering/error-budgets/)\nexplains how these budgets are used.\n\nRead more about how the error budgets are calculated in the\n[stage group dashboard documentation](https://docs.gitlab.com/ee/development/stage_group_dashboards.html#error-budget).\n\nThe error budget is compared to our SLO of 99.95% and is always in\na range of 28 days from the selected end date in Grafana.\n\n### Availability\n\nThe availability shows the percentage of operations labeled with one of the\ncategories owned by Package with satisfactory completion.\n\n### Budget remaining\n\nThe error budget in minutes is calculated based on the 99.95%.\nThere are 40320 minutes in 28 days, we allow 0.05% of failures, which\nmeans the budget in minutes is 20 minutes.\n\nThe budget remaining shows how many minutes have not been spent in the\npast 28 days.\n\n### Minutes spent\n\nThis shows the total minutes spent over the past 28 days.\n\nFor example, if there were 403200 (28 * 24 * 60) operations in 28 days.\nThis would be 1 every minute. If 10 of those were unsatisfactory, that\nwould mean 10 minutes of the budget were spent.\n"
  },
  {
   "title": "Budget spend attribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "title": "Budget failures",
     "type": "table",
     "description": "Number of failures contributing to the budget send per component and type ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "ceil(\n  (\n    sum by (component,type,violation_type) (\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n            ) -\n            # Request with satisfactory apdex\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:success:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'apdex' , '', ''\n      )\n      or\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'error' , '', ''\n      )\n    ) > 0\n  ) * 60\n)\n"
      },
      {
       "expr": "ceil(\n  (\n    sum by (component,type,violation_type) (\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:apdex:weight:score_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n            )\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'apdex' , '', ''\n      )\n      or\n      label_replace(\n        sum by (component,type)(\n          sum by (component,stage_group,type)(\n            sum_over_time(\n              gitlab:component:stage_group:execution:ops:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d]\n            )\n            and sum_over_time(gitlab:component:stage_group:execution:error:rate_1h{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[28d])\n          ) unless on (stage_group,component) gitlab:ignored_component:stage_group\n        ),\n        'violation_type', 'error' , '', ''\n      )\n    ) > 0\n  ) * 60\n)\n"
      }
     ]
    },
    {
     "title": "Info",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 111 },
     "content": "This table shows the failures that contribute to the spend of the error budget.\nFixing the top item in this table will have the biggest impact on the\nbudget spend.\n\nA failure is one of 2 types:\n\n- **error**: An operation that failed: 500 response, failed background job.\n- **apdex**: This means an operation that succeeded, but did not perform within the set threshold.\n\nSee the [developer documentation](https://gitlab.com/gitlab-org/gitlab/-/blob/master/doc/development/stage_group_dashboards.md#error-budget)\nto learn more about this.\n\nThe component refers to the component in our stack where the violation occurred.\nThe most common ones are:\n\n- **puma**: This component signifies requests handled by rails\n- **sidekiq_execution**: This component signifies background jobs executed by Sidekiq\n\nTo find the endpoint that is attributing to the budget spend and a violation type\nwe can use the logs over a 7 day range. Links for puma and sidekiq are available on the right.\nThese logs list the endpoints that had the most violations over the past 7 days.\n\nThe \"Other\" row is the sum of all the other violations excluding the top ones\nthat are listed.\n"
    },
    {
     "title": "Failure log links",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 111 },
     "content": "##### [Puma Apdex](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"match_phrase\":+{\"json.meta.feature_category\":+\"container_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"package_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"helm_chart_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"dependency_proxy\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"dependency_firewall\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"git_lfs\"}}]}}'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:container_registry)),(match_phrase:(json.meta.feature_category:package_registry)),(match_phrase:(json.meta.feature_category:helm_chart_registry)),(match_phrase:(json.meta.feature_category:dependency_proxy)),(match_phrase:(json.meta.feature_category:dependency_firewall)),(match_phrase:(json.meta.feature_category:git_lfs))))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'3',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms),(enabled:!t,id:'3',params:(customLabel:'Operations+over+threshold+(1s)',field:json.duration_s,json:'{\"script\":+\"doc[!'json.duration_s!'].value+>=+1+?+1+:+0\"}'),schema:metric,type:sum),(enabled:!t,id:'4',params:(customLabel:'Operations+over+error+budget+threshold+(5s)',field:json.duration_s,json:'{\"script\":+\"doc[!'json.duration_s!'].value+>=+5+?+1+:+0\"}'),schema:metric,type:sum))))&_g=(time:(from:'now-7d',to:'now'))): slow requests\n\nThis shows the number of requests exceeding the request duration thresholds\nper endpoint over the past 7 days.\n\nThis shows all requests exceeding 1s and 5s durations. We will make this\ntake the configured [request urgency](https://docs.gitlab.com/ee/development/application_slis/rails_request_apdex.html#adjusting-request-urgency) into account in\n[this issue](https://gitlab.com/gitlab-com/gl-infra/scalability/-/issues/1478).\n\n##### [Puma Errors](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"match_phrase\":+{\"json.meta.feature_category\":+\"container_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"package_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"helm_chart_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"dependency_proxy\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"dependency_firewall\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"git_lfs\"}}]}}'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:container_registry)),(match_phrase:(json.meta.feature_category:package_registry)),(match_phrase:(json.meta.feature_category:helm_chart_registry)),(match_phrase:(json.meta.feature_category:dependency_proxy)),(match_phrase:(json.meta.feature_category:dependency_firewall)),(match_phrase:(json.meta.feature_category:git_lfs)))))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): failing requests\n\nThis shows the number of Rails requests that failed per endpoint over\nthe past 7 days.\n\n##### [Sidekiq Execution Apdex](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"match_phrase\":+{\"json.meta.feature_category\":+\"container_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"package_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"helm_chart_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"dependency_proxy\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"dependency_firewall\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"git_lfs\"}}]}}'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:container_registry)),(match_phrase:(json.meta.feature_category:package_registry)),(match_phrase:(json.meta.feature_category:helm_chart_registry)),(match_phrase:(json.meta.feature_category:dependency_proxy)),(match_phrase:(json.meta.feature_category:dependency_firewall)),(match_phrase:(json.meta.feature_category:git_lfs)))))),(query:(match:(json.job_status:(query:done,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(filters:!((input:(language:kuery,query:'json.shard:+\"urgent\"+AND+json.duration_s+>+10'),label:'Jobs+exceeding+10s'),(input:(language:kuery,query:'not+json.shard:+\"urgent\"+AND+json.duration_s+>+300'),label:'Jobs+exceeding+300s'))),schema:split,type:filters),(enabled:!t,params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): slow jobs\n\nThis shows the number of jobs per worker that took longer than their threshold to\nexecute over the past 7 days.\nFor urgent jobs the threshold is 10s, this is the table on the left.\nFor other jobs the threshold is 300s, this is the table on the right.\n\n##### [Sidekiq Execution Errors](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=table&indexPattern=AWNABDRwNDuQHTm2tH6l&_a=(filters:!((meta:(key:query,type:custom,value:'{\"bool\":+{\"minimum_should_match\":+1,+\"should\":+[{\"match_phrase\":+{\"json.meta.feature_category\":+\"container_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"package_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"helm_chart_registry\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"dependency_proxy\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"dependency_firewall\"}},+{\"match_phrase\":+{\"json.meta.feature_category\":+\"git_lfs\"}}]}}'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(json.meta.feature_category:container_registry)),(match_phrase:(json.meta.feature_category:package_registry)),(match_phrase:(json.meta.feature_category:helm_chart_registry)),(match_phrase:(json.meta.feature_category:dependency_proxy)),(match_phrase:(json.meta.feature_category:dependency_firewall)),(match_phrase:(json.meta.feature_category:git_lfs)))))),(query:(match:(json.job_status:(query:fail,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,params:(field:json.class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:bucket,type:terms))))&_g=(time:(from:'now-7d',to:'now'))): failing jobs\n\nThis shows the number of jobs per worker that failed over the past 7 days.\nThis includes retries: if a job with a was retried 3 times, before exhausting\nits retries, this counts as 3 failures towards the budget.\n"
    }
   ]
  },
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }
  },
  {
   "title": "Overall Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab:stage_group:execution:apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
     "legendFormat": "Package apdex"
    },
    {
     "expr": "(1 - 6 * (1 - 0.9995))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - 0.9995))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab:stage_group:execution:apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
     "legendFormat": "Package apdex avg"
    }
   ]
  },
  {
   "title": "Overall Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 201 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab:stage_group:execution:error:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Package error ratio"
    },
    {
     "expr": "(6 * 0.0005)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * 0.0005)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab:stage_group:execution:error:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "Package error ratio avg"
    }
   ]
  },
  {
   "title": "Overall RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 201 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab:stage_group:execution:ops:rate_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
     "legendFormat": "Package RPS"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "🔬 Service Level Indicators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 },
   "collapsed": true,
   "panels": [
    {
     "title": "database SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"database\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "database SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"database\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "content": "### Description\n\nAggregation of all container registry database operations.\n\n"
    },
    {
     "title": "garbagecollector SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"garbagecollector\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "garbagecollector SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"garbagecollector\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * 0.0005)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * 0.0005)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "garbagecollector SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"garbagecollector\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "content": "### Description\n\nAggregation of all container registry online garbage collection operations.\n\n"
    },
    {
     "title": "graphql_queries SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"graphql_queries\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "graphql_queries SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"graphql_queries\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "content": "### Description\n\nThe number of GraphQL queries meeting their duration target based on the urgency\nof the endpoint. By default, a query should take no more than 1s. We're working\non making the urgency customizable in [this epic](https://gitlab.com/groups/gitlab-org/-/epics/5841).\n\nMutliple queries could be batched inside a single request.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.duration_s:(gte:1))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.meta.caller_id,json.operation_name,json.meta.feature_category,json.operation_fingerprint,json.duration_s),filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.subcomponent:(query:graphql_json,type:phrase)))),(query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.meta.caller_id.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "puma SLI Error Ratio",
     "type": "graph",
     "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Error %" }
     ],
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab:component:stage_group:execution:error:ratio_5m{component=\"puma\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n,\n  1\n)\n",
       "legendFormat": "{{ type }} error ratio"
      },
      {
       "expr": "(6 * 0.0005)\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(14.4 * 0.0005)\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "puma SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"puma\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
     "content": "### Description\n\nThis SLI monitors API traffic in aggregate, in the GitLab rails monolith, via its\nHTTP interface. 5xx responses are treated as failures.\n\n\n\n### Observability Tools\n\n* [🐞 Sentry Releases: gitlab/gitlabcom](https://sentry.gitlab.net/gitlab/gitlabcom/releases?environment=${environment})\n* [🐞 Sentry api issues](https://sentry.gitlab.net/gitlab/gitlabcom/issues?environment=${environment}&query=stage%3A${stage}+type%3Aapi)\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.duration_s:(gte:10))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "rails_requests SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "rails_requests SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"rails_requests\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
     "content": "### Description\n\nThe number of requests meeting their duration target based on the urgency\nof the endpoint. By default, a request should take no more than 1s. But\nthis can be adjusted by endpoint.\n\nRead more about this in the [documentation](https://docs.gitlab.com/ee/development/application_slis/rails_request_apdex.html).\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.duration_s:(gte:5))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.route,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:api,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.route.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
    },
    {
     "title": "registry_storage SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"registry_storage\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "registry_storage SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"registry_storage\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
     "content": "### Description\n\nAggregation of all container registry GCS storage operations.\n\n"
    },
    {
     "title": "server_route_manifest_reads SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"server_route_manifest_reads\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "server_route_manifest_reads SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"server_route_manifest_reads\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 60 },
     "content": "### Description\n\nAll read-requests (HEAD or GET) for the manifest endpoints on\nthe registry.\nFetch the manifest identified by name and reference where reference can be\na tag or digest. A HEAD request can also be issued to this endpoint to\nobtain resource information without receiving all data.\n\n"
    },
    {
     "title": "server_route_manifest_writes SLI Apdex",
     "type": "graph",
     "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "percentunit", "label": "Apdex %" }
     ],
     "targets": [
      {
       "expr": "min_over_time(gitlab:component:stage_group:execution:apdex:ratio_5m{component=\"server_route_manifest_writes\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} apdex"
      },
      {
       "expr": "(1 - 6 * (1 - 0.9995))\n",
       "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
      },
      {
       "expr": "(1 - 14.4 * (1 - 0.9995))\n",
       "legendFormat": "1h Outage SLO (2% of monthly error budget)"
      }
     ]
    },
    {
     "title": "server_route_manifest_writes SLI RPS - Requests per Second",
     "type": "graph",
     "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 70 },
     "yaxes": [
      { "format": "short", "label": "Operations per Second" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(gitlab:component:stage_group:execution:ops:rate_5m{component=\"server_route_manifest_writes\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",stage_group=\"package\"}[$__interval])\n",
       "legendFormat": "{{ type }} RPS"
      }
     ]
    },
    {
     "title": "Details",
     "type": "text",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 70 },
     "content": "### Description\n\nAll write-requests (put, delete) for the manifest endpoints on\nthe registry.\n\nPut the manifest identified by name and reference where reference can be\na tag or digest.\n\nDelete the manifest identified by name and reference. Note that a manifest\ncan only be deleted by digest.\n\n"
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: database",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1200 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 database Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_database_query_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "database RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_database_queries_total{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 database Latency - per name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,name) (\n    rate(registry_database_query_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",name!=\"\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{name}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for database Latency - per name",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (name) (\n  rate(registry_database_query_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",name!=\"\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (name) (\n    rate(registry_database_query_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"0.5\",name!=\"\",stage=\"$stage\"}[$__interval])\n  )\n  +\n  sum by (name) (\n    rate(registry_database_query_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"1\",name!=\"\",stage=\"$stage\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(name) group_left()\n  (\n    sum by () (\n  rate(registry_database_query_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",name!=\"\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "database RPS - per name",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (name) (\n  rate(registry_database_queries_total{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",name!=\"\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: garbagecollector",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1210 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 garbagecollector Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_gc_run_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "garbagecollector Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_gc_runs_total{environment=\"$environment\",error=\"true\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "garbagecollector RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_gc_runs_total{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 garbagecollector Latency - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,worker) (\n    rate(registry_gc_run_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\",worker!=\"\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{worker}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for garbagecollector Latency - per worker",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (worker) (\n  rate(registry_gc_run_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",stage=\"$stage\",worker!=\"\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (worker) (\n    rate(registry_gc_run_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"0.5\",stage=\"$stage\",worker!=\"\"}[$__interval])\n  )\n  +\n  sum by (worker) (\n    rate(registry_gc_run_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"1\",stage=\"$stage\",worker!=\"\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(worker) group_left()\n  (\n    sum by () (\n  rate(registry_gc_run_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",stage=\"$stage\",worker!=\"\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "garbagecollector Errors - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (\n  rate(registry_gc_runs_total{environment=\"$environment\",error=\"true\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\",worker!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "garbagecollector RPS - per worker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (\n  rate(registry_gc_runs_total{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\",worker!=\"\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{worker}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: graphql_queries",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1220 },
   "collapsed": true,
   "panels": [
    {
     "title": "graphql_queries RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_queries Latency - per endpoint_id",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:success_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (endpoint_id) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "graphql_queries RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_queries Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:success_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "graphql_queries RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for graphql_queries Latency - per query_urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (query_urgency) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n    )\n    -\n    sum by (query_urgency) (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:success_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (query_urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{query_urgency}}"
      }
     ]
    },
    {
     "title": "graphql_queries RPS - per query_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (query_urgency) (\n  sli_aggregations:gitlab_sli:graphql_query_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",query_urgency!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{query_urgency}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: puma",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1230 },
   "collapsed": true,
   "panels": [
    {
     "title": "puma Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "puma RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "puma Errors - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",fqdn!=\"\",job=\"gitlab-rails\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "puma RPS - per fqdn",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (fqdn) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",fqdn!=\"\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{fqdn}}"
      }
     ]
    },
    {
     "title": "puma Errors - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",method!=\"\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "puma RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",method!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "puma Errors - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\",status=~\"5..\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "puma RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:http_requests_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: rails_requests",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1240 },
   "collapsed": true,
   "panels": [
    {
     "title": "rails_requests RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_requests Latency - per endpoint_id",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (endpoint_id) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:success_total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (endpoint_id) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "rails_requests RPS - per endpoint_id",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (endpoint_id) (\n  sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{endpoint_id!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{endpoint_id}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_requests Latency - per feature_category",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n    -\n    sum by (feature_category) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:success_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (feature_category) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "rails_requests RPS - per feature_category",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (feature_category) (\n  sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{feature_category}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for rails_requests Latency - per request_urgency",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (request_urgency) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n    )\n    -\n    sum by (request_urgency) (\n      sli_aggregations:gitlab_sli:rails_request_apdex:success_total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n  / ignoring (request_urgency) group_left()\n  (\n    sum by () (\n      sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n    )\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    },
    {
     "title": "rails_requests RPS - per request_urgency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (request_urgency) (\n  sli_aggregations:gitlab_sli:rails_request_apdex:total_rate5m{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",job=\"gitlab-rails\",request_urgency!=\"\",stage=\"$stage\"}\n)\n > 0",
       "legendFormat": "{{request_urgency}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: registry_storage",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1250 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 registry_storage Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_storage_action_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "registry_storage RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_storage_action_seconds_count{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 registry_storage Latency - per action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (action,le) (\n    rate(registry_storage_action_seconds_bucket{action!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{action}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for registry_storage Latency - per action",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (action) (\n  rate(registry_storage_action_seconds_bucket{action!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      sum by (action) (\n  rate(registry_storage_action_seconds_bucket{action!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"1\",stage=\"$stage\"}[$__interval])\n)\n\n    )\n  )\n  / ignoring(action) group_left()\n  (\n    sum by () (\n  rate(registry_storage_action_seconds_bucket{action!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "registry_storage RPS - per action",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (action) (\n  rate(registry_storage_action_seconds_count{action!=\"\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Estimated p95 registry_storage Latency - per migration_path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,migration_path) (\n    rate(registry_storage_action_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",migration_path!=\"\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{migration_path}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for registry_storage Latency - per migration_path",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (migration_path) (\n  rate(registry_storage_action_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",migration_path!=\"\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      sum by (migration_path) (\n  rate(registry_storage_action_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"1\",migration_path!=\"\",stage=\"$stage\"}[$__interval])\n)\n\n    )\n  )\n  / ignoring(migration_path) group_left()\n  (\n    sum by () (\n  rate(registry_storage_action_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",migration_path!=\"\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{migration_path}}"
      }
     ]
    },
    {
     "title": "registry_storage RPS - per migration_path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (migration_path) (\n  rate(registry_storage_action_seconds_count{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",migration_path!=\"\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{migration_path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: server",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1260 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 server Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "server Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_requests_total{code=~\"5..\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "server RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_requests_total{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 server Latency - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,route) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",route!=\"\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{route}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server Latency - per route",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (route) (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",route!=\"\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (route) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"2.5\",route!=\"\",stage=\"$stage\"}[$__interval])\n  )\n  +\n  sum by (route) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"25\",route!=\"\",stage=\"$stage\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(route) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",route!=\"\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "server Errors - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (\n  rate(registry_http_requests_total{code=~\"5..\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",route!=\"\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "server RPS - per route",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (route) (\n  rate(registry_http_requests_total{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",route!=\"\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Estimated p95 server Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method!=\"\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",method!=\"\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"2.5\",method!=\"\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"25\",method!=\"\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",method!=\"\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server Errors - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_requests_total{code=~\"5..\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method!=\"\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_requests_total{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method!=\"\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Estimated p95 server Latency - per migration_path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,migration_path) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",migration_path!=\"\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{migration_path}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server Latency - per migration_path",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (migration_path) (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",migration_path!=\"\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (migration_path) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"2.5\",migration_path!=\"\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n  +\n  sum by (migration_path) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"25\",migration_path!=\"\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(migration_path) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",migration_path!=\"\",route!~\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{migration_path}}"
      }
     ]
    },
    {
     "title": "server Errors - per migration_path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by (migration_path) (\n  rate(registry_http_requests_total{code=~\"5..\",environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",migration_path!=\"\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{migration_path}}"
      }
     ]
    },
    {
     "title": "server RPS - per migration_path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (migration_path) (\n  rate(registry_http_requests_total{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",migration_path!=\"\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{migration_path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: server_route_manifest_reads",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1270 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 server_route_manifest_reads Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "server_route_manifest_reads RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method=~\"get|head\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 server_route_manifest_reads Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_manifest_reads Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"0.5\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"1\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_reads RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Estimated p95 server_route_manifest_reads Latency - per migration_path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,migration_path) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method=~\"get|head\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{migration_path}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_manifest_reads Latency - per migration_path",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (migration_path) (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",method=~\"get|head\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (migration_path) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"0.5\",method=~\"get|head\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n  +\n  sum by (migration_path) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"1\",method=~\"get|head\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(migration_path) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",method=~\"get|head\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{migration_path}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_reads RPS - per migration_path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (migration_path) (\n  rate(registry_http_request_duration_seconds_count{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method=~\"get|head\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{migration_path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: server_route_manifest_writes",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1280 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 server_route_manifest_writes Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "server_route_manifest_writes RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(registry_http_request_duration_seconds_count{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method=~\"put|delete|post|patch\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "Estimated p95 server_route_manifest_writes Latency - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,method) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{method}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_manifest_writes Latency - per method",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (method) (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"10\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n  +\n  sum by (method) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"25\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(method) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_writes RPS - per method",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(registry_http_request_duration_seconds_count{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Estimated p95 server_route_manifest_writes Latency - per migration_path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le,migration_path) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method=~\"put|delete|post|patch\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n > 0",
       "legendFormat": "p95 {{migration_path}}"
      }
     ]
    },
    {
     "title": "Apdex attribution for server_route_manifest_writes Latency - per migration_path",
     "type": "graph",
     "description": "Attributes apdex downscoring",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "percentunit", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max((\n  (\n    sum by (migration_path) (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",method=~\"put|delete|post|patch\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n    -\n    (\n      (\n  sum by (migration_path) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"10\",method=~\"put|delete|post|patch\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n  +\n  sum by (migration_path) (\n    rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"25\",method=~\"put|delete|post|patch\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n  )\n)\n/\n2\n\n    )\n  )\n  / ignoring(migration_path) group_left()\n  (\n    sum by () (\n  rate(registry_http_request_duration_seconds_bucket{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",le=\"+Inf\",method=~\"put|delete|post|patch\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n\n  )\n) > 0\n,1),0)\n",
       "legendFormat": "{{migration_path}}"
      }
     ]
    },
    {
     "title": "server_route_manifest_writes RPS - per migration_path",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by (migration_path) (\n  rate(registry_http_request_duration_seconds_count{environment=\"$environment\",feature_category=~\"container_registry|package_registry|helm_chart_registry|dependency_proxy|dependency_firewall|git_lfs|\",method=~\"put|delete|post|patch\",migration_path!=\"\",route=\"/v2/{name}/manifests/{reference}\",stage=\"$stage\"}[$__interval])\n)\n > 0",
       "legendFormat": "{{migration_path}}"
      }
     ]
    }
   ]
  }
 ]
}