{
 "title": "suggestedReviewer_eval_metrics_t1",
 "time": { "from": "2022-05-01T14:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "in_top_k Accuracy",
   "type": "stat",
   "description": "This describes the percentage of times where at least one suggested reviewer is in the candidate list.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(in_top_k) * 100 AS accuracy_global FROM validation_model_metrics.aggregate_metrics_mv"
    }
   ]
  },
  {
   "title": "Number of MRs per Approved Projects",
   "type": "barchart",
   "description": "This displays the count of MRs per all approved projects (internal projects).",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    project_name,\n    merge_requests_count\nFROM\n(\nSELECT\n    project_id,\n    count(*) AS merge_requests_count\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id\n)  AS per_project_metrics\nJOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 20\nORDER BY merge_requests_count DESC\n"
    }
   ]
  },
  {
   "title": "Ratio of Accepted Reviewers Given N Candidates",
   "type": "table",
   "description": "The ratio is calculated by aggregating all MRs by length of candidates first and then aggregating by the number of accepted reviewers amongst that candidate list. This number of MRs is divided by the total number of MRs and then multiplied by 100 to get a percentage of total MRs. For example, in the first row, the ratio indicates the number of MRs with one accepted reviewer with five total candidates amongst all MRs.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  LENGTH(candidates) AS \"Candidates\",\n  LENGTH(arrayIntersect(reviewers,candidates)) AS \"Accepted Reviewers\",\n  COUNT(*) / (SELECT COUNT(*) FROM validation_model_metrics.aggregate_metrics) * 100 AS \"Acceptance Ratio\"\nFROM validation_model_metrics.aggregate_metrics\nWHERE LENGTH(candidates) >= 5 and LENGTH(candidates) <= 7 and LENGTH(arrayIntersect(reviewers, candidates)) > 0 and LENGTH(arrayIntersect(reviewers, candidates)) <= 7\nGROUP BY LENGTH(candidates), LENGTH(arrayIntersect(reviewers, candidates))\nORDER BY LENGTH(candidates), LENGTH(arrayIntersect(reviewers, candidates))",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "in_top_k Misclassification",
   "type": "stat",
   "description": "This metric describes the percent of times the selected reviewers is not in the suggested candidates.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1 - AVG(in_top_k) AS misclassification_global \nFROM validation_model_metrics.aggregate_metrics"
    }
   ]
  },
  {
   "title": "Number of MRs per Internal Project Monthly",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-com/www-gitlab-com'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/customers-gitlab-com'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/gitlab'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-com/marketing/digital-experience/buyer-experience'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'levenlabs/frontend/app-web'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/customers-gitlab-com'\nORDER BY recommendation_month"
    }
   ]
  },
  {
   "title": "Change in Number of MRs per Internal Project Monthly",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) AS \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-com/www-gitlab-com'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) AS \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/customers-gitlab-com'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) AS \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/gitlab'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) AS \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-com/marketing/digital-experience/buyer-experience'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) AS \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'levenlabs/frontend/app-web'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) AS \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/customers-gitlab-com'\nORDER BY recommendation_month"
    }
   ]
  },
  {
   "title": "in_top_k Accuracy by Project Monthly",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'gitlab-com/www-gitlab-com'\nORDER BY recommendation_month\n"
    },
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'gitlab-org/customers-gitlab-com'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'gitlab-org/gitlab'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'gitlab-com/marketing/digital-experience/buyer-experience'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'levenlabs/frontend/app-web'\nORDER BY recommendation_month"
    },
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_month\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfMonth(latest_recommendation_time) as recommendation_month\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_month\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'gitlab-org/gitlab-qa'\nORDER BY recommendation_month"
    }
   ]
  },
  {
   "title": "Number of MRs per Internal Project Weekly",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-com/www-gitlab-com'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/customers-gitlab-com'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/gitlab'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-com/marketing/digital-experience/buyer-experience'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'levenlabs/frontend/app-web'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    merge_requests_count as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/gitlab-qa'\nORDER BY recommendation_week"
    }
   ]
  },
  {
   "title": "Change in Number of MRs per Internal Project Weekly",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-com/www-gitlab-com'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/customers-gitlab-com'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/gitlab'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-com/marketing/digital-experience/buyer-experience'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'levenlabs/frontend/app-web'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    runningDifference(merge_requests_count) as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS merge_requests_count,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE merge_requests_count > 10 and project_name = 'gitlab-org/gitlab-qa'\nORDER BY recommendation_week"
    }
   ]
  },
  {
   "title": "in_top_k Accuracy by Project Weekly",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'gitlab-com/www-gitlab-com'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'gitlab-org/customers-gitlab-com'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'gitlab-org/gitlab'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'gitlab-com/marketing/digital-experience/buyer-experience'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'levenlabs/frontend/app-web'\nORDER BY recommendation_week"
    },
    {
     "rawSql": "SELECT\n    global_accuracy as \" \",\n    recommendation_week\nFROM (SELECT\n    project_id,\n    count(*) AS sample_size,\n    AVG(in_top_k) AS global_accuracy,\n    toStartOfWeek(latest_recommendation_time) as recommendation_week\nFROM\n    validation_model_metrics.aggregate_metrics\nGROUP BY project_id, recommendation_week\n)  AS per_project_metrics\nINNER JOIN validation_model_metrics.project_id_to_name as link \nON link.project_id = per_project_metrics.project_id\nWHERE sample_size > 10 and project_name = 'gitlab-org/gitlab-qa'\nORDER BY recommendation_week"
    }
   ]
  }
 ]
}