{
 "title": "TCP retransmits on Patroni hosts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TCP Retransmit Rate (outbound segments per minute)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "TCP segments / minute" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{environment=\"gprd\", type=\"patroni\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP SYN Retransmit Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "TCP SYN retransmits / minute" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_TcpExt_TCPSynRetrans{environment=\"gprd\", type=\"patroni\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall TCP Transmit Rate (outbound segments per minute)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "TCP segments / minute" }
   ],
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{environment=\"gprd\", type=\"patroni\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}