{
 "title": "Team Error Budget",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Availability - 90 day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort(avg(avg_over_time(gitlab_team_availability:ratio[90d])) by (team))",
     "legendFormat": "{{ team }}"
    }
   ]
  },
  {
   "title": "Availability - 1 day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort(avg(avg_over_time(gitlab_team_availability:ratio[1d])) by (team))",
     "legendFormat": "{{ team }}"
    }
   ]
  },
  {
   "title": "Availability - 1 week",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort(avg(avg_over_time(gitlab_team_availability:ratio[1w])) by (team))",
     "legendFormat": "{{ team }}"
    }
   ]
  }
 ]
}