{
 "title": "thanos: Thanos / Rule",
 "tags": [
  "protected",
  "thanos",
  "unmanaged"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(thanos_build_info{}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(thanos_build_info{environment=\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(thanos_build_info{environment=\"$environment\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(thanos_build_info{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"thanos-rule.+\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", pod=~\"$job.+\"}[$__interval]))",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_requests{container=\"ruler\", job=\"kube-state-metrics\", environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$job.+\", resource=\"cpu\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{container=\"ruler\", job=\"kube-state-metrics\", job=\"kube-state-metrics\", environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$job.+\", resource=\"cpu\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$job.+\", container!=\"\"}[$__rate_interval])) by (pod, container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$job.+\",}[$__rate_interval])) by (pod, container)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Horizontal Pod Autoscaler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", horizontalpodautoscaler=\"$job\"}",
     "legendFormat": "current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", horizontalpodautoscaler=\"$job\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$job.+\", container=\"ruler\"}) by (pod)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$job.+\", container=\"ruler\", resource=\"memory\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$job.+\", container=\"ruler\", resource=\"memory\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(kube_pod_container_status_restarts_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", container=\"ruler\", pod=~\"$job.+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Terminations",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated_reason{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$job.+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rule Group Evaluations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rule Group Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, strategy) (rate(prometheus_rule_evaluations_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{ strategy }}"
    }
   ]
  },
  {
   "title": "Rule Group Evaluations Missed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, strategy) (increase(prometheus_rule_group_iterations_missed_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{ strategy }}"
    }
   ]
  },
  {
   "title": "Rule Group Evlauations Too Slow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  sum by(job, rule_group) (prometheus_rule_group_last_duration_seconds{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"})\n  >\n  sum by(job, rule_group) (prometheus_rule_group_interval_seconds{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"})\n)\n",
     "legendFormat": "{{ rule_group }}"
    }
   ]
  },
  { "title": "Ruler Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Ruler Failures by err and name",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (name, err, msg) (rate({namespace=\"thanos\", component=~\"ruler\"} | json | __error__!=`JSONParserErr`| level=~\"warn\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Error Logging Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (level) (rate({namespace=\"thanos\", component=~\"ruler\"} | json | __error__!=`JSONParserErr`| level=~\"error\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Ruler Error logs detail",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "{environment=\"$environment\", namespace=\"thanos\", component=~\"ruler\"} | json | __error__!=`JSONParserErr`| level=~\"error\" "
    }
   ]
  },
  {
   "title": "Alert Sent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Dropped Rate",
     "type": "timeseries",
     "description": "Shows rate of dropped alerts.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, alertmanager) (rate(thanos_alert_sender_alerts_dropped_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{alertmanager}}"
      }
     ]
    },
    {
     "title": "Sent Rate",
     "type": "timeseries",
     "description": "Shows rate of alerts that successfully sent to alert manager.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, alertmanager) (rate(thanos_alert_sender_alerts_sent_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{alertmanager}}"
      }
     ]
    },
    {
     "title": "Sent Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of sent alerts.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_alert_sender_errors_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_alert_sender_alerts_sent_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$interval]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "Sent Duration",
     "type": "timeseries",
     "description": "Shows how long has it taken to send alerts to alert manager.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_alert_sender_latency_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p50 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, le) (rate(thanos_alert_sender_latency_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p90 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_alert_sender_latency_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p99 {{job}}",
       "logBase": 10
      }
     ]
    }
   ]
  },
  {
   "title": "Alert Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Push Rate",
     "type": "timeseries",
     "description": "Shows rate of queued alerts.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_alert_queue_alerts_dropped_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Drop Ratio",
     "type": "timeseries",
     "description": "Shows ratio of dropped alerts compared to the total number of queued alerts.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_alert_queue_alerts_dropped_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_alert_queue_alerts_pushed_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$interval]))",
       "legendFormat": "error"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC (Unary)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "description": "Shows rate of handled Unary gRPC requests.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))",
       "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Shows ratio of errors compared to the total number of handled requests.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",job=~\"$job\", grpc_type=\"unary\"}[$interval])) / sum by (job) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "description": "Shows how long has it taken to handle requests, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
       "legendFormat": "p50 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
       "legendFormat": "p90 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
       "legendFormat": "p99 {{job}}",
       "logBase": 10
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC (Stream)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "description": "Shows rate of handled Streamed gRPC requests.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))",
       "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Shows ratio of errors compared to the total number of handled requests.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",job=~\"$job\", grpc_type=\"server_stream\"}[$interval])) / sum by (job) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "description": "Shows how long has it taken to handle requests, in quantiles",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
       "legendFormat": "p50 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
       "legendFormat": "p90 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
       "legendFormat": "p99 {{job}}",
       "logBase": 10
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "alloc all {{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "alloc heap {{instance}}"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate all {{instance}}"
      },
      {
       "expr": "rate(go_memstats_heap_alloc_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate heap {{instance}}"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "inuse heap {{instance}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "inuse stack {{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{quantile}} {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}