{
 "title": "thanos: Kube Deployment Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6719132820 at Thu Apr 25 18:01:26 UTC 2024",
 "tags": [
  "managed",
  "thanos",
  "thanos",
  "type:thanos",
  "kube",
  "kube detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "memcached-thanos-bucket-cache deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "memcached-thanos-bucket-cache Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-bucket-cache Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-bucket-cache Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-index-cache deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "memcached-thanos-index-cache Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-index-cache Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-index-cache Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-qfe-labels deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "memcached-thanos-qfe-labels Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-qfe-labels Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-qfe-labels Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-qfe-query-range deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "memcached-thanos-qfe-query-range Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-qfe-query-range Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-qfe-query-range Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  { "title": "thanos-query deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "thanos-query Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "thanos-query Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "thanos-query Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "thanos-query-frontend deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 }
  },
  {
   "title": "thanos-query-frontend Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "thanos-query-frontend Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "thanos-query-frontend Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  { "title": "thanos-store deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "thanos-store Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      container!=\"\",container!=\"POD\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "thanos-store Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 104 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    container!=\"\",container!=\"POD\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "thanos-store Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 104 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}