{
 "title": "thanos: Capacity Review",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/6474957084 at Mon Mar 25 23:20:36 UTC 2024",
 "tags": [
  "managed",
  "thanos",
  "thanos",
  "type:thanos",
  "capacity-review"
 ],
 "time": { "from": "now-15d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate_1h, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "disk_space: Disk Space Utilization per Device per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(2)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"disk_space\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"disk_space\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Disk Space Utilization per Device per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"disk_space\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"disk_space\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"disk_space\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 2 },
   "content": "Disk space utilization per device per node.\n"
  },
  {
   "title": "disk_inodes: Disk inode Utilization per Device per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(2)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"disk_inodes\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"disk_inodes\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Disk inode Utilization per Device per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"disk_inodes\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"disk_inodes\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"disk_inodes\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 102 },
   "content": "Disk inode utilization per device per node.\n\nIf this is too high, its possible that a directory is filling up with\nfiles. Consider logging in an checking temp directories for large numbers\nof files\n"
  },
  {
   "title": "go_goroutines: Go goroutines Utilization per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(2)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"go_goroutines\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"go_goroutines\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Go goroutines Utilization per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"go_goroutines\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"go_goroutines\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"go_goroutines\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"go_goroutines\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"go_goroutines\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 202 },
   "content": "Go goroutines utilization per node.\n\nGoroutines leaks can cause memory saturation which can cause service degradation.\n\nA limit of 250k goroutines is very generous, so if a service exceeds this limit,\nit's a sign of a leak and it should be dealt with.\n"
  },
  {
   "title": "open_fds: Open file descriptor utilization per instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(2)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"open_fds\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"open_fds\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Open file descriptor utilization per instance",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 302 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"open_fds\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"open_fds\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"open_fds\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 302 },
   "content": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n"
  },
  {
   "title": "shard_cpu: Average CPU Utilization per Shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 401 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 401 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 401 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"shard_cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 401 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"shard_cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Average CPU Utilization per Shard",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 402 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"shard_cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"shard_cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"shard_cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 402 },
   "content": "This resource measures average CPU utilization across an all cores in a shard of a\nservice fleet. If it is becoming saturated, it may indicate that the\nshard needs horizontal or vertical scaling.\n"
  },
  {
   "title": "cpu: Average Service CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 501 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 501 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 501 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 501 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Average Service CPU Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 502 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 502 },
   "content": "This resource measures average CPU utilization across an all cores in a service fleet.\nIf it is becoming saturated, it may indicate that the fleet needs\nhorizontal or vertical scaling.\n"
  },
  {
   "title": "kube_horizontalpodautoscaler_desired_replicas: Horizontal Pod Autoscaler Desired Replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 600 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 601 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 601 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 601 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_horizontalpodautoscaler_desired_replicas\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 601 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_horizontalpodautoscaler_desired_replicas\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Horizontal Pod Autoscaler Desired Replicas",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 602 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 602 },
   "content": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n"
  },
  {
   "title": "kube_container_throttling: Kube container throttling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 700 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 701 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 701 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 701 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_throttling\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 701 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_throttling\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Kube container throttling",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 702 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_throttling\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_throttling\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_throttling\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_throttling\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 702 },
   "content": "Kube container throttling\n\nA container will be throttled if it reaches the configured cpu limit for the\nhorizontal pod autoscaler. Or when other containers on the node are overutilizing\nthe the CPU.\n\nTo get around this, consider increasing the limit for this workload, taking\ninto consideration the requested resources.\n"
  },
  {
   "title": "nf_conntrack_entries: conntrack Entries per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 800 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 801 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 801 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 801 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"nf_conntrack_entries\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 801 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"nf_conntrack_entries\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "conntrack Entries per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 802 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"nf_conntrack_entries\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"nf_conntrack_entries\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"nf_conntrack_entries\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 802 },
   "content": "Netfilter connection tracking table utilization per node.\n\nWhen saturated, new connection attempts (incoming SYN packets) are dropped with no reply, leaving clients to slowly retry (and typically fail again) over the next several seconds.  When packets are being dropped due to this condition, kernel will log the event as: \"nf_conntrack: table full, dropping packet\".\n"
  },
  {
   "title": "single_node_cpu: Average CPU Utilization per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 900 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 901 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 901 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 901 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"single_node_cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 901 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"single_node_cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Average CPU Utilization per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 902 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"single_node_cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"single_node_cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"single_node_cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 902 },
   "content": "Average CPU utilization per Node.\n\nIf average CPU is saturated, it may indicate that a fleet is in need to horizontal or vertical scaling. It may also indicate\nimbalances in load in a fleet.\n"
  },
  {
   "title": "go_memory: Go Memory Utilization per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1001 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1001 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"go_memory\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"go_memory\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Go Memory Utilization per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1002 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"go_memory\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"go_memory\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"go_memory\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1002 },
   "content": "Go's memory allocation strategy can make it look like a Go process is saturating memory when measured using RSS, when in fact\nthe process is not at risk of memory saturation. For this reason, we measure Go processes using the `go_memstat_alloc_bytes`\n"
  },
  {
   "title": "kube_go_memory: Go Memory Utilization per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1100 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_go_memory\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_go_memory\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Go Memory Utilization per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1102 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_go_memory\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_go_memory\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_go_memory\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1102 },
   "content": "Measures Go memory usage as a percentage of container memory limit\n"
  },
  {
   "title": "kube_container_cpu: Kube Container CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1200 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Kube Container CPU Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1202 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1202 },
   "content": "Kubernetes containers are allocated a share of CPU. Configured using resource requests.\n\nThis is the amount of CPU that a container should always have available,\nthough it can briefly utilize more. However, if a lot of pods on the same\nhost exceed their requested CPU the container could be throttled earlier.\n\nThis monitors utilization/allocated requests over a 1 hour period, and takes\nthe 99th quantile of that utilization percentage in that period.\nWe want the worst case to be around 80%-90% utilization,\nmeaning we've sized the container correctly. If utilization is much higher than that\nthe container could already be throttled because the host is overused, if it\nis much lower, then we could be underutilizing a host.\n\nThis saturation point is only used for capacity planning.\nThe burst utilization of a CPU is monitored and alerted upon using the\n`kube_container_cpu_limit` saturation point.\n"
  },
  {
   "title": "kube_container_cpu_limit: Kube Container CPU over-utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1300 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_cpu_limit\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_cpu_limit\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Kube Container CPU over-utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1302 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_cpu_limit\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_cpu_limit\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_cpu_limit\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu_limit\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1302 },
   "content": "Kubernetes containers can have a limit configured on how much CPU they can consume in\na burst. If we are at this limit, exceeding the allocated requested resources, we\nshould consider revisting the container's HPA configuration.\n\nWhen a container is utilizing CPU resources up-to it's configured limit for\nextended periods of time, this could cause it and other running containers to be\nthrottled.\n"
  },
  {
   "title": "kube_container_memory: Kube Container Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1400 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1401 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1401 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1401 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_memory\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1401 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_memory\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Kube Container Memory Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1402 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_memory\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_memory\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"kube_container_memory\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1402 },
   "content": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n"
  },
  {
   "title": "memory: Memory Utilization per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1500 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1501 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1501 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1501 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"memory\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1501 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"memory\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Memory Utilization per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1502 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"memory\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"memory\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"memory\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1502 },
   "content": "Memory utilization per device per node.\n"
  },
  {
   "title": "node_schedstat_waiting: Node Scheduler Waiting Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1600 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1601 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1601 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1601 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"node_schedstat_waiting\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1601 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"node_schedstat_waiting\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"thanos\"}\n"
    }
   ]
  },
  {
   "title": "Node Scheduler Waiting Time",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1602 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"node_schedstat_waiting\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"node_schedstat_waiting\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"thanos\", component=\"node_schedstat_waiting\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1602 },
   "content": "Measures the amount of scheduler waiting time that processes are waiting\nto be scheduled, according to [`CPU Scheduling Metrics`](https://www.robustperception.io/cpu-scheduling-metrics-from-the-node-exporter).\n\nA high value indicates that a node has more processes to be run than CPU time available\nto handle them, and may lead to degraded responsiveness and performance from the application.\n\nAdditionally, it may indicate that the fleet is under-provisioned.\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}