{
 "title": "Thanos: compactor",
 "tags": [
  "thanos-mixin",
  "unmanaged"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" },
   {
    "name": "compactor",
    "label": "Compactor",
    "query": {
     "query": "label_values(up{job=~\"thanos\",  fqdn=~\"thanos-compact.*\"}, fqdn)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Compactor Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Compaction Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (fqdn) (thanos_compact_todo_compactions{fqdn=~\"$compactor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compaction Block Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (fqdn) (thanos_compact_todo_compaction_blocks{fqdn=~\"$compactor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downsample Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (job) (thanos_compact_todo_downsample_blocks{namespace=\"thanos\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Deletion Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (fqdn) (thanos_compact_todo_deletion_blocks{fqdn=~\"$compactor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Group Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for compactions against blocks that are stored in the bucket by compaction group.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn, group) (rate(thanos_compact_group_compactions_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "compaction {{fqdn}} {{group}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed compactions against blocks that are stored in the bucket.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn) (rate(thanos_compact_group_compactions_failures_total{fqdn=~\"$compactor\"}[$interval])) / sum by (fqdn) (rate(thanos_compact_group_compactions_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Downsample",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for downsampling against blocks that are stored in the bucket by compaction group.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn, group) (rate(thanos_compact_downsample_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "downsample {{fqdn}} {{group}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed downsampling against blocks that are stored in the bucket.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn) (rate(thanos_compact_downsample_failed_total{fqdn=~\"$compactor\"}[$interval])) / sum by (fqdn) (rate(thanos_compact_downsample_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for removals of blocks if their data is available as part of a block with a higher compaction level.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn) (rate(thanos_compact_garbage_collection_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "garbage collection {{job}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed garbage collections.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn) (rate(thanos_compact_garbage_collection_failures_total{fqdn=~\"$compactor\"}[$interval])) / sum by (fqdn) (rate(thanos_compact_garbage_collection_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to execute garbage collection in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (fqdn, le) (rate(thanos_compact_garbage_collection_duration_seconds_bucket{fqdn=~\"$compactor\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (fqdn, le) (rate(thanos_compact_garbage_collection_duration_seconds_bucket{fqdn=~\"$compactor\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (fqdn, le) (rate(thanos_compact_garbage_collection_duration_seconds_bucket{fqdn=~\"$compactor\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Blocks deletion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deletion Rate",
   "type": "graph",
   "description": "Shows deletion rate of blocks already marked for deletion.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn) (rate(thanos_compact_blocks_cleaned_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "Blocks cleanup {{fqdn}}"
    }
   ]
  },
  {
   "title": "Deletion Error Rate",
   "type": "graph",
   "description": "Shows deletion failures rate of blocks already marked for deletion.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn) (rate(thanos_compact_block_cleanup_failures_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "Blocks cleanup failures {{job}}"
    }
   ]
  },
  {
   "title": "Marking Rate",
   "type": "graph",
   "description": "Shows rate at which blocks are marked for deletion (from GC and retention policy).",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn) (rate(thanos_compact_blocks_marked_for_deletion_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "Blocks marked {{job}}"
    }
   ]
  },
  {
   "title": "Sync Meta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for all meta files from blocks in the bucket into the memory.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn) (rate(thanos_blocks_meta_syncs_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "sync {{job}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed meta file sync.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn) (rate(thanos_blocks_meta_sync_failures_total{fqdn=~\"$compactor\"}[$interval])) / sum by (fqdn) (rate(thanos_blocks_meta_syncs_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to execute meta file sync, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (fqdn, le) (rate(thanos_blocks_meta_sync_duration_seconds_bucket{fqdn=~\"$compactor\"}[$interval]))) * 1",
     "legendFormat": "p50 {{fqdn}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (fqdn, le) (rate(thanos_blocks_meta_sync_duration_seconds_bucket{fqdn=~\"$compactor\"}[$interval]))) * 1",
     "legendFormat": "p90 {{fqdn}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (fqdn, le) (rate(thanos_blocks_meta_sync_duration_seconds_bucket{fqdn=~\"$compactor\"}[$interval]))) * 1",
     "legendFormat": "p99 {{fqdn}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Object Store Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn, operation) (rate(thanos_objstore_bucket_operations_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "{{fqdn}} {{operation}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (fqdn, operation) (rate(thanos_objstore_bucket_operation_failures_total{fqdn=~\"$compactor\"}[$interval])) / sum by (fqdn, operation) (rate(thanos_objstore_bucket_operations_total{fqdn=~\"$compactor\"}[$interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to execute operations against the bucket, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (fqdn, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{fqdn=~\"$compactor\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (fqdn, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{fqdn=~\"$compactor\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (fqdn, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{fqdn=~\"$compactor\"}[$interval]))) * 1",
     "legendFormat": "p99 {{fqdn}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{fqdn=~\"$compactor\", job=~\"thanos.*\"}",
     "legendFormat": "alloc all {{fqdn}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{fqdn=~\"$compactor\", job=~\"thanos.*\"}",
     "legendFormat": "alloc heap {{fqdn}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{fqdn=~\"$compactor\", job=~\"thanos.*\"}[30s])",
     "legendFormat": "alloc rate all {{fqdn}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{fqdn=~\"$compactor\", job=~\"thanos.*\"}[30s])",
     "legendFormat": "alloc rate heap {{fqdn}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{fqdn=~\"$compactor\", job=~\"thanos.*\"}",
     "legendFormat": "inuse heap {{fqdn}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{fqdn=~\"$compactor\", job=~\"thanos.*\"}",
     "legendFormat": "inuse stack {{fqdn}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{fqdn=~\"$compactor\", job=~\"thanos.*\"}",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{fqdn=~\"$compactor\", job=~\"thanos.*\"}",
     "legendFormat": "{{quantile}} {{fqdn}}"
    }
   ]
  }
 ]
}