{
 "title": "thanos: Thanos / Receive",
 "tags": [
  "protected",
  "thanos",
  "unmanaged"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(thanos_build_info,environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(thanos_build_info{environment=\"$environment\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(thanos_build_info{environment=\"$environment\", cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(up{job=~\".*thanos-receive.*\"}, job)"
   },
   {
    "name": "tenant",
    "label": "tenant",
    "query": "label_values(http_requests_total{job=~\"$job\", tenant!=\"\"}, tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "WRITE - Incoming Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Shows rate of incoming requests.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, handler, code) (rate(http_requests_total{job=~\"$job\", handler=\"receive\"}[$interval]))",
     "legendFormat": "{{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled incoming requests.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(http_requests_total{job=~\"$job\", handler=\"receive\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (job) (rate(http_requests_total{job=~\"$job\", handler=\"receive\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle incoming requests in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\", handler=\"receive\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\", handler=\"receive\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\", handler=\"receive\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "WRITE - Incoming Request (tenant focus)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of write requests (by tenant and code)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenant, code) (rate(http_requests_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\"}[$__rate_interval]))",
     "legendFormat": "{{code}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Number of errors (by tenant and code)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenant, code) (rate(http_requests_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\", code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{code}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Average request duration (by tenant)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, tenant) (rate(http_request_duration_seconds_sum{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\"}[$__rate_interval])) / sum by (job, tenant) (http_request_duration_seconds_count{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "HTTP requests (tenant focus)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average successful HTTP request size (per tenant and code, only 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, tenant) (rate(http_request_size_bytes_sum{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\", code=~\"2..\"}[$__rate_interval])) / sum by (job, tenant) (rate(http_request_size_bytes_count{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\", code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Average failed HTTP request size (per tenant and code, non 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, tenant) (rate(http_request_size_bytes_sum{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\", code!~\"2..\"}[$__rate_interval])) / sum by (job, tenant) (rate(http_request_size_bytes_count{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\", code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Inflight requests (per tenant and method)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, tenant, method) (http_inflight_requests{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", handler=\"receive\"})",
     "legendFormat": "{{method}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Series & Samples (tenant focus)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of series received (per tenant, only 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(thanos_receive_write_timeseries_sum{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", code=~\"2..\"}[$__rate_interval])) by (job, tenant) ",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Rate of series not written (per tenant and code, non 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(thanos_receive_write_timeseries_sum{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", code!~\"2..\"}[$__rate_interval])) by (tenant, code) ",
     "legendFormat": "{{code}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Rate of samples received (per tenant, only 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(thanos_receive_write_samples_sum{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", code=~\"2..\"}[$__rate_interval])) by (job, tenant) ",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Rate of samples not written (per tenant and code, non 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(thanos_receive_write_samples_sum{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", tenant=~\"$tenant\", code!~\"2..\"}[$__rate_interval])) by (tenant, code) ",
     "legendFormat": "{{code}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "WRITE - Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "description": "Shows rate of replications to other receive nodes.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_receive_replications_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "all {{job}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Shows ratio of errors compared to the total number of replications to other receive nodes.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_receive_replications_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", result=\"error\"}[$interval])) / sum by (job) (rate(thanos_receive_replications_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$interval]))",
       "legendFormat": "error"
      }
     ]
    }
   ]
  },
  {
   "title": "WRITE - Forward Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "description": "Shows rate of forwarded requests to other receive nodes.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_receive_forward_requests_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "all {{job}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Shows ratio of errors compared to the total number of forwareded requests to other receive nodes.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_receive_forward_requests_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", result=\"error\"}[$interval])) / sum by (job) (rate(thanos_receive_forward_requests_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[$interval]))",
       "legendFormat": "error"
      }
     ]
    }
   ]
  },
  {
   "title": "WRITE - gRPC (Unary)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of handled Unary gRPC requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))",
       "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job, grpc_code) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval])) / ignoring (grpc_code) group_left() sum by (job) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))) * 1",
       "legendFormat": "p50 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))) * 1",
       "legendFormat": "p90 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))) * 1",
       "legendFormat": "p99 {{job}}",
       "logBase": 10
      }
     ]
    }
   ]
  },
  {
   "title": "READ - gRPC (Unary)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of handled Unary gRPC requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval]))",
       "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job, grpc_code) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval])) / ignoring (grpc_code) group_left() sum by (job) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval]))) * 1",
       "legendFormat": "p50 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval]))) * 1",
       "legendFormat": "p90 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\", grpc_method!=\"RemoteWrite\"}[$interval]))) * 1",
       "legendFormat": "p99 {{job}}",
       "logBase": 10
      }
     ]
    }
   ]
  },
  {
   "title": "READ - gRPC (Stream)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "description": "Shows rate of handled Streamed gRPC requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job, grpc_method, grpc_code) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))",
       "legendFormat": "{{job}} {{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (job, grpc_code) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",job=~\"$job\", grpc_type=\"server_stream\"}[$interval])) / ignoring (grpc_code) group_left() sum by (job) (rate(grpc_server_handled_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
       "legendFormat": "p50 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
       "legendFormat": "p90 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
       "legendFormat": "p99 {{job}}",
       "logBase": 10
      }
     ]
    }
   ]
  },
  {
   "title": "Last Updated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Successful Upload",
     "type": "table-old",
     "description": "Shows the relative time of last successful upload to the object-store bucket.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "time() - max by (job, bucket) (thanos_objstore_bucket_last_successful_upload_time{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "alloc all {{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "alloc heap {{instance}}"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate all {{instance}}"
      },
      {
       "expr": "rate(go_memstats_heap_alloc_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate heap {{instance}}"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "inuse heap {{instance}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "inuse stack {{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=~\"$job\"}",
       "legendFormat": "{{quantile}} {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}