{
 "title": "Thanos Sidecar",
 "tags": [
  "thanos",
  "unmanaged"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "labelvalue", "query": "thanos" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kubernetes_namespace)"
   },
   { "name": "labelselector", "query": "job" }
  ]
 },
 "panels": [
  { "title": "Thanos Sidecar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Upload time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(time() - thanos_objstore_bucket_last_successful_upload_time{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Last Heartbeat time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(time() - thanos_sidecar_last_heartbeat_success_time_seconds{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Query RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$__interval])) by (grpc_code, grpc_method, kubernetes_namespace)",
     "legendFormat": "{{grpc_code}} {{grpc_method}}  {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Query Response Time Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(grpc_server_handling_seconds_bucket{$labelselector=\"$labelvalue\"}[$__interval])) by (grpc_method, le, kubernetes_namespace))",
     "legendFormat": "99.99 {{grpc_method}} {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Bucket Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$__interval])) by (kubernetes_namespace, operation)",
     "legendFormat": "{{operation}} {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Bucket Operation Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_failures_total{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$__interval])) by (operation,kubernetes_namespace)",
     "legendFormat": "{{operation}} {{kubernetes_namespace}}"
    }
   ]
  },
  {
   "title": "Bucket Operation Time Quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}[$__interval])) by (kubernetes_namespace,le))",
     "legendFormat": "99.99 bucket ops {{kubernetes_namespace}}"
    }
   ]
  },
  { "title": "Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{$labelselector=\"$labelvalue\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{$labelselector=\"$labelvalue\", quantile=\"1\"}",
     "legendFormat": "{{quantile}} {{instance}} {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}