{
 "title": "thanos: Thanos / Compact",
 "tags": [
  "thanos",
  "protected"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\", environment=~\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(thanos_build_info{environment=\"$environment\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(thanos_build_info{namespace=\"$namespace\", job=~\".+compactor\"}, job)"
    }
   },
   { "name": "level", "label": "Log Level", "query": "info,error,debug,warn" },
   { "name": "search", "label": "Log Search" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", component=\"compactor\"} | json | __error__!=`JSONParserErr` !~ \"OTLP\" | level=~\"$level\" |~ \"$search\""
    }
   ]
  },
  { "title": "Pod Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\", resource=\"cpu\"}) by (pod))",
     "legendFormat": "requests"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\", resource=\"cpu\"}) by (pod))",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\", resource=\"memory\"}) by (pod))",
     "legendFormat": "requests"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job.+\", resource=\"memory\"}) by (pod))",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "PVC Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  kubelet_volume_stats_capacity_bytes{env=\"$environment\", cluster=\"$cluster\", job=\"kubelet\", namespace=\"$namespace\", persistentvolumeclaim=~\"$job\"}\n  -\n  kubelet_volume_stats_available_bytes{env=\"$environment\", cluster=\"$cluster\", job=\"kubelet\", namespace=\"$namespace\", persistentvolumeclaim=~\"$job\"}\n)\n",
     "legendFormat": "Usage - {{persistentvolumeclaim}}"
    },
    {
     "expr": "kubelet_volume_stats_capacity_bytes{env=\"$environment\", cluster=\"$cluster\", job=\"kubelet\", namespace=\"$namespace\", persistentvolumeclaim=~\"$job\"}",
     "legendFormat": "Capacity - {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 21 },
   "targets": [
    {
     "expr": "sum by (reason) (kube_pod_container_status_last_terminated_reason{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$job.+\", cluster=\"$cluster\", container=\"compactor\"}[$__rate_interval])) by (container) / sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", namespace=\"$namespace\", pod=~\"$job.+\", cluster=\"$cluster\", container=\"compactor\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Compactor Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Compactor Halted Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thanos_compact_halted{env=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compaction Backlog",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 37 },
   "targets": [
    {
     "expr": "sum by (pod) (thanos_compact_todo_compactions{env=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Compactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 37 },
   "targets": [
    {
     "expr": "sum by (pod) (thanos_compact_todo_compaction_blocks{env=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deletion Backlog",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 37 },
   "targets": [
    {
     "expr": "sum by (pod) (thanos_compact_todo_deletion_blocks{env=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downsample Backlog",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 37 },
   "targets": [
    {
     "expr": "sum by (pod) (thanos_compact_todo_downsample_blocks{env=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Group Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of execution for compactions against blocks that are stored in the bucket by compaction group.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job, group) (rate(thanos_compact_group_compactions_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "compaction {{job}} {{group}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of executed compactions against blocks that are stored in the bucket.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_compact_group_compactions_failures_total{job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_compact_group_compactions_total{job=~\"$job\"}[$interval]))",
       "legendFormat": "error"
      }
     ]
    }
   ]
  },
  {
   "title": "Downsample",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of execution for downsampling against blocks that are stored in the bucket by compaction group.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job, group) (rate(thanos_compact_downsample_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "downsample {{job}} {{group}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of executed downsampling against blocks that are stored in the bucket.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_compact_downsample_failed_total{job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_compact_downsample_total{job=~\"$job\"}[$interval]))",
       "legendFormat": "error"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of execution for removals of blocks if their data is available as part of a block with a higher compaction level.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_compact_garbage_collection_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "garbage collection {{job}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of executed garbage collections.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_compact_garbage_collection_failures_total{job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_compact_garbage_collection_total{job=~\"$job\"}[$interval]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to execute garbage collection in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_compact_garbage_collection_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p50 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, le) (rate(thanos_compact_garbage_collection_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p90 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_compact_garbage_collection_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p99 {{job}}",
       "logBase": 10
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks deletion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Deletion Rate",
     "type": "graph",
     "description": "Shows deletion rate of blocks already marked for deletion.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_compact_blocks_cleaned_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "Blocks cleanup {{job}}"
      }
     ]
    },
    {
     "title": "Deletion Error Rate",
     "type": "graph",
     "description": "Shows deletion failures rate of blocks already marked for deletion.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_compact_block_cleanup_failures_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "Blocks cleanup failures {{job}}"
      }
     ]
    },
    {
     "title": "Marking Rate",
     "type": "graph",
     "description": "Shows rate at which blocks are marked for deletion (from GC and retention policy).",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_compact_blocks_marked_for_deletion_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "Blocks marked {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync Meta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of execution for all meta files from blocks in the bucket into the memory.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_blocks_meta_syncs_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "sync {{job}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of executed meta file sync.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_blocks_meta_sync_failures_total{job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_blocks_meta_syncs_total{job=~\"$job\"}[$interval]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to execute meta file sync, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_blocks_meta_sync_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p50 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, le) (rate(thanos_blocks_meta_sync_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p90 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_blocks_meta_sync_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p99 {{job}}",
       "logBase": 10
      }
     ]
    }
   ]
  },
  {
   "title": "Object Store Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of execution for operations against the bucket.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (job, operation) (rate(thanos_objstore_bucket_operations_total{job=~\"$job\"}[$__rate_interval]))",
       "legendFormat": "{{job}} {{operation}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of executed operations against the bucket.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (job) (rate(thanos_objstore_bucket_operation_failures_total{job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_objstore_bucket_operations_total{job=~\"$job\"}[$interval]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to execute operations against the bucket, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p50 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.90, sum by (job, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p90 {{job}}",
       "logBase": 10
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
       "legendFormat": "p99 {{job}}",
       "logBase": 10
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=~\"$job\"}",
       "legendFormat": "alloc all {{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\"}",
       "legendFormat": "alloc heap {{instance}}"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate all {{instance}}"
      },
      {
       "expr": "rate(go_memstats_heap_alloc_bytes{job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate heap {{instance}}"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\"}",
       "legendFormat": "inuse heap {{instance}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\"}",
       "legendFormat": "inuse stack {{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=~\"$job\"}",
       "legendFormat": "{{quantile}} {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}