{
 "title": "Thanos / Memcached",
 "description": "Prometheus dashboard for thanos memcached servers",
 "tags": [ "thanos" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(memcached_commands_total{}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(memcached_commands_total{environment=\"$environment\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(memcached_commands_total{environment=\"$environment\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(memcached_commands_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"memcached\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\", container=\"memcached\"}) by (pod))",
     "legendFormat": "requests"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\", container=\"memcached\"}) by (pod))",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", container=\"memcached\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\", container=\"memcached\"}) by (pod))",
     "legendFormat": "requests"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits{environment=~\"$environment\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\", container=\"memcached\"}) by (pod))",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "% Hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(memcached_commands_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", status=\"miss\"}[$__interval])) by (pod)  / sum (rate(memcached_commands_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (memcached_current_connections{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum (memcached_max_connections{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "max connections"
    }
   ]
  },
  {
   "title": "Get / Set ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(memcached_commands_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", command=\"set\"}[$__interval])) / sum (rate(memcached_commands_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\", command=\"get\"}[$__interval]))",
     "legendFormat": "{{pod }} - ratio"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(memcached_commands_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__interval])) by (pod, command)",
     "legendFormat": "{{pod}} - {{command}}"
    }
   ]
  },
  {
   "title": "evicts / reclaims",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_items_evicted_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}} - evicts"
    },
    {
     "expr": "sum(rate(memcached_items_reclaimed_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}} - reclaims"
    }
   ]
  },
  {
   "title": "Read / written bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(memcached_read_bytes_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "{{pod}} - read from network"
    },
    {
     "expr": "irate(memcached_written_bytes_total{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}[10m])",
     "legendFormat": "{{pod}} - written to network"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (pod) / sum(memcached_limit_bytes{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (memcached_current_items{environment=\"$environment\", cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}