{
 "title": "thanos: Kube Containers Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/5450170080 at Thu Nov  2 22:54:29 UTC 2023",
 "tags": [
  "managed",
  "thanos",
  "thanos",
  "type:thanos",
  "kube",
  "kube detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "memcached-thanos-bucket-cache deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "memcached container/memcached-thanos-bucket-cache deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 memcached Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 memcached Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 memcached Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 memcached Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 memcached Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 memcached Container CPU"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-bucket-cache deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p99 memcached Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p95 memcached Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p75 memcached Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p50 memcached Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p25 memcached Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p10 memcached Container Memory"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-bucket-cache deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-bucket-cache deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-bucket-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-index-cache deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "memcached container/memcached-thanos-index-cache deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 memcached Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 memcached Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 memcached Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 memcached Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 memcached Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 memcached Container CPU"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-index-cache deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p99 memcached Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p95 memcached Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p75 memcached Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p50 memcached Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p25 memcached Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p10 memcached Container Memory"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-index-cache deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-index-cache deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-index-cache\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-qfe-labels deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 }
  },
  {
   "title": "memcached container/memcached-thanos-qfe-labels deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 memcached Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 memcached Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 memcached Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 memcached Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 memcached Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 memcached Container CPU"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-qfe-labels deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p99 memcached Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p95 memcached Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p75 memcached Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p50 memcached Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p25 memcached Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p10 memcached Container Memory"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-qfe-labels deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-qfe-labels deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-labels\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memcached-thanos-qfe-query-range deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 }
  },
  {
   "title": "memcached container/memcached-thanos-qfe-query-range deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 memcached Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 memcached Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 memcached Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 memcached Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 memcached Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 memcached Container CPU"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-qfe-query-range deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p99 memcached Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p95 memcached Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p75 memcached Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p50 memcached Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p25 memcached Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p10 memcached Container Memory"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-qfe-query-range deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "memcached container/memcached-thanos-qfe-query-range deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"memcached\",deployment=\"memcached-thanos-qfe-query-range\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "thanos-query deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "thanos-query container/thanos-query deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 thanos-query Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 thanos-query Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 thanos-query Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 thanos-query Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 thanos-query Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 thanos-query Container CPU"
    }
   ]
  },
  {
   "title": "thanos-query container/thanos-query deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p99 thanos-query Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p95 thanos-query Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p75 thanos-query Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p50 thanos-query Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p25 thanos-query Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p10 thanos-query Container Memory"
    }
   ]
  },
  {
   "title": "thanos-query container/thanos-query deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "thanos-query container/thanos-query deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"thanos-query\",deployment=\"thanos-query\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "thanos-query-frontend deployment",
   "type": "row",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 }
  },
  {
   "title": "thanos-query-frontend container/thanos-query-frontend deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 thanos-query-frontend Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 thanos-query-frontend Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 thanos-query-frontend Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 thanos-query-frontend Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 thanos-query-frontend Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 thanos-query-frontend Container CPU"
    }
   ]
  },
  {
   "title": "thanos-query-frontend container/thanos-query-frontend deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p99 thanos-query-frontend Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p95 thanos-query-frontend Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p75 thanos-query-frontend Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p50 thanos-query-frontend Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p25 thanos-query-frontend Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p10 thanos-query-frontend Container Memory"
    }
   ]
  },
  {
   "title": "thanos-query-frontend container/thanos-query-frontend deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "thanos-query-frontend container/thanos-query-frontend deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"thanos-query-frontend\",deployment=\"thanos-query-frontend\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  { "title": "thanos-store deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "thanos-store container/thanos-store deployment - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p99 thanos-store Container CPU"
    },
    {
     "expr": "quantile(0.950000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p95 thanos-store Container CPU"
    },
    {
     "expr": "quantile(0.750000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p75 thanos-store Container CPU"
    },
    {
     "expr": "quantile(0.500000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p50 thanos-store Container CPU"
    },
    {
     "expr": "quantile(0.250000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p25 thanos-store Container CPU"
    },
    {
     "expr": "quantile(0.100000, rate(\n  container_cpu_usage_seconds_total:labeled{\n    container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n   }[$__rate_interval]\n )\n)\n",
     "legendFormat": "p10 thanos-store Container CPU"
    }
   ]
  },
  {
   "title": "thanos-store container/thanos-store deployment - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "quantile(0.990000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p99 thanos-store Container Memory"
    },
    {
     "expr": "quantile(0.950000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p95 thanos-store Container Memory"
    },
    {
     "expr": "quantile(0.750000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p75 thanos-store Container Memory"
    },
    {
     "expr": "quantile(0.500000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p50 thanos-store Container Memory"
    },
    {
     "expr": "quantile(0.250000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p25 thanos-store Container Memory"
    },
    {
     "expr": "quantile(0.100000, container_memory_working_set_bytes:labeled{\n  container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n }\n)\n",
     "legendFormat": "p10 thanos-store Container Memory"
    }
   ]
  },
  {
   "title": "thanos-store container/thanos-store deployment - Container Waiting Reasons",
   "type": "graph",
   "description": "Why are containers waiting?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_waiting_reason:labeled{\n  container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "thanos-store container/thanos-store deployment - Container Terminations",
   "type": "graph",
   "description": "Why are containers terminating?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "short", "label": "Containers Terminated" }
   ],
   "targets": [
    {
     "expr": "sum by (reason) (max_over_time(kube_pod_container_status_terminated_reason:labeled{\n  container=\"thanos-store\",deployment=\"thanos-store\",env=\"$environment\",environment=\"$environment\",type=\"thanos\"\n}[10m]))\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}