{
 "title": "Traffic Generation",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "query": "gstg,gprd" },
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "stage",
    "query": "label_values(traffic_gen_gitlab_qa_results, stage)"
   }
  ]
 },
 "panels": [
  { "title": "GitLab QA Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GitLab QA Last Run",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "push_time_seconds{job=\"$environment:$stage:auto:gitlab-qa\"} * 1000"
    }
   ]
  },
  {
   "title": "Successful Test Run Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "traffic_gen_gitlab_qa_results{job=\"$environment:$stage:auto:gitlab-qa\", status=\"passed\"}",
     "legendFormat": "{{ description }}"
    }
   ]
  },
  {
   "title": "GitLab QA Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max_over_time(traffic_gen_gitlab_qa_failures{job=\"$environment:$stage:auto:gitlab-qa\"}[$__interval])) OR vector(0)"
    }
   ]
  },
  {
   "title": "Test Results",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(traffic_gen_gitlab_qa_results{job=\"$environment:$stage:auto:gitlab-qa\", status=\"passed\"}) by (description)",
     "legendFormat": "pass {{ description }}"
    },
    {
     "expr": "count(traffic_gen_gitlab_qa_results{job=\"$environment:$stage:auto:gitlab-qa\", status=\"failed\"}) by (description)",
     "legendFormat": "fail {{ description }}"
    }
   ]
  },
  { "title": "HTTPS Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Last Run Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "push_time_seconds{job=~'$environment:$stage.*'} * 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "traffic_gen_result{result=\"errors_count\", job=~\"$environment:$stage:.*\"}",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Status codes that are not 2xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traffic_gen_result{result=~\"num_status_[^2].*\", job=~\"$environment:$stage:.*\"}) by (result, url)",
     "legendFormat": "{{ result }} {{ url }}"
    }
   ]
  },
  {
   "title": "Requests / Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "traffic_gen_result{result=\"rps_mean\", job=~\"$environment:$stage:.*\"}",
     "legendFormat": "{{ result }} {{ url }}"
    }
   ]
  },
  {
   "title": "Request Latencies p50",
   "type": "graph",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "traffic_gen_result{result=\"latency_percentiles_50\", job=~\"$environment:$stage:.*\"}",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Request Latencies p95",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "traffic_gen_result{result=\"latency_percentiles_95\", job=~\"$environment:$stage:.*\"}",
     "legendFormat": "{{ url }}"
    }
   ]
  }
 ]
}