{
 "title": "Transactions",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "stage",
    "query": {
     "query": "label_values(gitaly_exclusive_snapshots_created_total,stage)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Partitions",
   "type": "barchart",
   "description": "The number of active partitions. The value contains only partitions that were active at the scrape time. ",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gitaly_partitions_started_total{stage=\"$stage\"} - gitaly_partitions_stopped_total{stage=\"$stage\"}",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Begin rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (storage) (rate(gitaly_transaction_control_statement_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  { "title": "Snapshotting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Snapshot Reuse Ratio",
   "type": "timeseries",
   "description": "Snapshot reuse ratio displays how many transactions reuse an existing shared snapshot instead of creating a new one.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(gitaly_shared_snapshots_reused_total{stage=\"$stage\"}[$__rate_interval]) / on(storage) (rate(gitaly_shared_snapshots_reused_total{stage=\"$stage\"}[$__rate_interval]) + rate(gitaly_shared_snapshots_created_total{stage=\"$stage\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shared Snapshots Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(gitaly_shared_snapshots_created_total{stage=\"$stage\"}[$__rate_interval])",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Shared Snapshots Reused",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(gitaly_shared_snapshots_reused_total{stage=\"$stage\"}[$__rate_interval])",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Exclusive Snapshots Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(gitaly_exclusive_snapshots_created_total{stage=\"$stage\"}[$__rate_interval])",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  { "title": "Commit Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(gitaly_transaction_commit_queue_depth) by (storage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wait Duration p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (storage, le) (rate(gitaly_transaction_commit_queue_wait_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Control Statement Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "Begin p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (storage, le) (rate(gitaly_transaction_control_statement_duration_seconds_bucket{control_statement=\"begin\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (storage, le) (rate(gitaly_transaction_control_statement_duration_seconds_bucket{control_statement=\"commit\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollback p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (storage, le) (rate(gitaly_transaction_control_statement_duration_seconds_bucket{control_statement=\"rollback\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction total duration p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (storage, le) (rate(gitaly_transaction_total_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Transaction Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Processing p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (storage, le) (rate(gitaly_transaction_processing_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}