{
 "title": "Triton Server",
 "description": "Visualize metrics from the Triton server.",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Request success / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(model, version) (rate(nv_inference_request_success[$__rate_interval]))",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Batchsize ( #infer/ #exec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(model, version) (rate(nv_inference_count[$__rate_interval])) / sum by(model, version) (rate(nv_inference_exec_count[$__rate_interval]))",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Input time / req",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "irate(nv_inference_compute_input_duration_us[$__interval]) / irate(nv_inference_request_success[$__interval])",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Request fail / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(model, version) (rate(nv_inference_request_failure[$__rate_interval]))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "DB ratio ( #request / #exec )",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(model, version) (rate(nv_inference_request_success[$__rate_interval])) / sum by(model, version) (rate(nv_inference_exec_count[$__rate_interval]))",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Queue time / req",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(irate(nv_inference_queue_duration_us[$__interval])) / sum(irate(nv_inference_request_success[$__interval]))",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Request time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "irate(nv_inference_request_duration_us[$__interval]) / irate(nv_inference_request_success[$__interval])",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Output time / req",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "irate(nv_inference_compute_output_duration_us[$__interval]) / irate(nv_inference_request_success[$__interval])",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Inference time / req",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "irate(nv_inference_compute_infer_duration_us[$__interval]) / irate(nv_inference_request_success[$__interval])",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "GPU Util",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "nv_gpu_utilization", "legendFormat": "Util" }
   ]
  },
  {
   "title": "Power consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(nv_gpu_power_usage)", "legendFormat": "Total Power (W)" }
   ]
  }
 ]
}