{
 "title": "Unicorn Workers",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(unicorn_active_connections, environment)"
   },
   {
    "name": "type",
    "query": "label_values(unicorn_active_connections{environment=\"$env\"}, fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Queued Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(job:unicorn_queued_connections:sum{environment=\"$env\",type=\"$type\"}[$__interval]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "sum(max_over_time(job:unicorn_queued_connections:sum{environment=\"$env\",type=\"$type\"}[$__interval]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(job:unicorn_active_connections:sum{environment=\"$env\",type=\"$type\"}[$__interval]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "sum(max_over_time(job:unicorn_active_connections:sum{environment=\"$env\",type=\"$type\"}[$__interval]))",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(avg_over_time(unicorn_workers{environment=\"$env\",type=\"$type\"}[$__interval])) or count(ruby_memory_bytes{environment=\"$env\",type=\"$type\"})",
     "legendFormat": "Workers"
    }
   ]
  },
  {
   "title": "Resurce Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(instance:memory_utilization:ratio_q95{environment=\"$env\",fqdn=~\"$type-[0-9]+.*\"}[$__interval]))",
     "legendFormat": "Memory"
    },
    {
     "expr": "avg(avg_over_time(instance:cpu_utilization:ratio_q95{environment=\"$env\",fqdn=~\"$type-[0-9]+.*\"}[$__interval]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Worker Kills / minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(job:unicorn_killer_terminations_total:rate1m{job=\"mtail\",environment=\"$env\",type=\"$type\"}[$__interval])) * 60"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (le) (avg_over_time(job_environment:gitlab_transaction_duration_seconds_bucket:rate1m{environment=\"$env\",type=\"$type\"}[$__interval])) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}