{
 "title": "Unicorn Workers [deprecated]",
 "tags": [
  "deprecated",
  "unmanaged"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(unicorn_active_connections, environment)"
   },
   {
    "name": "type",
    "query": "label_values(unicorn_active_connections{environment=\"$env\"}, fqdn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "content": "![](https://media.giphy.com/media/l0HlKrB02QY0f1mbm/giphy.gif)"
  },
  {
   "title": "Deprecation  Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 0 },
   "content": "# Deprecated ⚠️⚠️⚠️⚠️⚠️\n\nThis dashboard is deprecated, please consider switching over to the new service based dashboards:\n\n* [api](/d/api-main/api-overview)\n* [web](/d/git-main/git-overview)\n* [git](/d/web-main/web-overview)\n\n\n"
  },
  {
   "title": "Queued Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(job:unicorn_queued_connections:sum{env=\"$env\",type=\"$type\"}[$__interval]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "sum(max_over_time(job:unicorn_queued_connections:sum{env=\"$env\",type=\"$type\"}[$__interval]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(job:unicorn_active_connections:sum{env=\"$env\",type=\"$type\"}[$__interval]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "sum(max_over_time(job:unicorn_active_connections:sum{env=\"$env\",type=\"$type\"}[$__interval]))",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(avg_over_time(unicorn_workers{env=\"$env\",type=\"$type\"}[$__interval])) or count(ruby_memory_bytes{env=\"$env\",type=\"$type\"})",
     "legendFormat": "Workers"
    }
   ]
  },
  {
   "title": "Scrape Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(up{job=\"gitlab-rails\",env=\"$env\",type=\"$type\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(scrape_duration_seconds{job=\"gitlab-rails\",env=\"$env\",type=\"$type\"}[$__interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(max_over_time(scrape_duration_seconds{job=\"gitlab-rails\",env=\"$env\",type=\"$type\"}[$__interval]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Resurce Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(instance:memory_utilization:ratio_q95{env=\"$env\",fqdn=~\"$type-[0-9]+.*\"}[$__interval]))",
     "legendFormat": "Memory"
    },
    {
     "expr": "avg(avg_over_time(instance:cpu_utilization:ratio_q95{env=\"$env\",fqdn=~\"$type-[0-9]+.*\"}[$__interval]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Worker Kills / minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(job:unicorn_killer_terminations_total:rate1m{job=\"mtail\",env=\"$env\",type=\"$type\"}[$__interval])) * 60"
    }
   ]
  },
  {
   "title": "Queuing Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(gitlab_rails_queue_duration_seconds_bucket{env=\"$env\",monitor=\"app\",type=\"$type\"}[$__interval])\n) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by (le) (avg_over_time(job_environment:gitlab_transaction_duration_seconds_bucket:rate1m{environment=\"$env\",type=\"$type\"}[$__interval])) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}