{
 "title": "User Authentication Events",
 "description": "Summary of various types of user authentication events",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(up{job=\"prometheus\"}, env)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(up{job=\"prometheus\",env=\"$env\"}, environment)"
   },
   {
    "name": "type",
    "query": "label_values(gitlab_auth_user_authenticated_total, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "2FA % (24hrs)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(increase(gitlab_auth_user_two_factor_authenticated_total{type=~\"$type\",environment=\"$env\"}[24h]))/sum(increase(gitlab_auth_user_authenticated_total{type=~\"$type\",environment=\"$env\"}[24h])))*100"
    }
   ]
  },
  {
   "title": "Successful auths (24hrs)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_auth_user_authenticated_total{type=~\"$type\",environment=\"$env\"}[24h]))"
    }
   ]
  },
  {
   "title": "Failed auths (24hrs)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_auth_user_unauthenticated_total{type=~\"$type\",environment=\"$env\"}[24h]))"
    }
   ]
  },
  {
   "title": "Blocked user attempts % (24hrs)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(increase(gitlab_auth_user_blocked_total{type=~\"$type\",environment=\"$env\"}[24h]))/sum(increase(gitlab_auth_user_authenticated_total{type=~\"$type\",environment=\"$env\"}[24h])))*100"
    }
   ]
  },
  {
   "title": "Authentication event counts (summed)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Events/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_auth_user_authenticated_total{type=~\"$type\", environment=\"$env\"}[5m]))",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rate(gitlab_auth_user_two_factor_authenticated_total{type=~\"$type\", environment=\"$env\"}[5m]))",
     "legendFormat": "2FA logins"
    },
    {
     "expr": "sum(rate(gitlab_auth_user_session_override_total{type=~\"$type\", environment=\"$env\"}[5m]))",
     "legendFormat": "Session overrides"
    },
    {
     "expr": "sum(rate(gitlab_auth_user_sessionless_authentication_total{type=~\"$type\", environment=\"$env\"}[5m]))",
     "legendFormat": "Token authentications"
    },
    {
     "expr": "sum(rate(gitlab_auth_user_blocked_total{type=~\"$type\", environment=\"$env\"}[5m]))",
     "legendFormat": "Blocked user login attempts"
    },
    {
     "expr": "sum(rate(gitlab_auth_user_not_found_total{type=~\"$type\", environment=\"$env\"}[5m]))",
     "legendFormat": "User not found"
    },
    {
     "expr": "sum(rate(gitlab_auth_user_password_invalid_total{type=~\"$type\", environment=\"$env\"}[5m]))",
     "legendFormat": "Invalid password"
    },
    {
     "expr": "sum(rate(gitlab_auth_user_unauthenticated_total{type=~\"$type\", environment=\"$env\"}[5m]))",
     "legendFormat": "Authentication failures"
    },
    {
     "expr": "sum(rate(gitlab_auth_user_session_destroyed_total{type=~\"$type\", environment=\"$env\"}[5m]))",
     "legendFormat": "Logouts"
    }
   ]
  },
  {
   "title": "Blocked user login attempts (% of successful)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(gitlab_auth_user_blocked_total{type=~\"$type\",environment=\"$env\"}[5m]))/sum(rate(gitlab_auth_user_authenticated_total{type=~\"$type\",environment=\"$env\"}[5m])))*100",
     "legendFormat": "Blocked attempts % of successful attempts"
    }
   ]
  },
  {
   "title": "Successful logins by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Events/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_auth_user_authenticated_total{environment=\"$env\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "2FA logins as percentage of total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitlab_auth_user_two_factor_authenticated_total{type=~\"$type\",environment=\"$env\"}[5m]))/sum(rate(gitlab_auth_user_authenticated_total{type=~\"$type\",environment=\"$env\"}[5m]))",
     "legendFormat": "2FA logins"
    }
   ]
  }
 ]
}