{
 "title": "Vanity Metrics Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "content": "# Postgres Storage\n\n------------------------------------"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 1 },
   "content": "# Git Storage\n\n------------------------------------"
  },
  {
   "title": "Current Postgres Database Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_filesystem_size_bytes{mountpoint=\"/var/opt/gitlab\", type=\"postgres\", environment=\"gprd\"} - node_filesystem_avail_bytes{mountpoint=\"/var/opt/gitlab\", type=\"postgres\", environment=\"gprd\"})"
    }
   ]
  },
  {
   "title": "Current Allocated Git Storage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/var/opt/gitlab\", type=\"gitaly\", environment=\"gprd\"} - node_filesystem_avail_bytes{mountpoint=\"/var/opt/gitlab\", type=\"gitaly\", environment=\"gprd\"})"
    }
   ]
  },
  {
   "title": "Δ Average Daily Postgres Delta",
   "type": "singlestat",
   "description": "Additional postgres storage allocated per day",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max((node_filesystem_avail_bytes{type=\"postgres\", mountpoint=\"/var/opt/gitlab\", environment=\"gprd\"} offset 1w) - node_filesystem_avail_bytes) / 7"
    }
   ]
  },
  {
   "title": "Δ Average Allocated Git Storage Daily Delta",
   "type": "singlestat",
   "description": "Additional git storage allocated per day",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 9 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\n\nsum(node_filesystem_size_bytes{mountpoint=\"/var/opt/gitlab\", type=\"gitaly\", environment=\"gprd\"} - (node_filesystem_size_bytes offset 1w))\n\n- \n\nsum(node_filesystem_avail_bytes{mountpoint=\"/var/opt/gitlab\", type=\"gitaly\", environment=\"gprd\"} - (node_filesystem_avail_bytes offset 1w))\n\n) / 7"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 15 },
   "content": "# Web Performance (https)\n\n------------------------------------"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 15 },
   "content": "# API Performance (https)\n\n---------------------------"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 16, "y": 15 },
   "content": "# Git Backend Performance (gitaly)\n\n---------------------------"
  },
  {
   "title": "Current Web Requests per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 18 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"gprd\",job=\"gitlab-workhorse-web\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Current API Requests per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 18 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"gprd\",job=\"gitlab-workhorse-api\"}[$__interval]))\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Current Git Backend Requests per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 18 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{environment=\"gprd\"}[$__interval]))\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Average Daily Web Requests per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 23 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"gprd\",job=\"gitlab-workhorse-web\"}[7d]))"
    }
   ]
  },
  {
   "title": "Average Daily API Requests per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 23 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"gprd\",job=\"gitlab-workhorse-api\"}[7d]))"
    }
   ]
  },
  {
   "title": "Average Daily Backend Git Operations per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 23 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{environment=\"gprd\"}[7d]))"
    }
   ]
  },
  {
   "title": "🏔Peak Web Requests per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 28 },
   "format": "locale",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"gprd\",job=\"gitlab-workhorse-web\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "🏔Peak API Requests per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 28 },
   "format": "locale",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(gitlab_workhorse_http_requests_total{environment=\"gprd\",job=\"gitlab-workhorse-api\"}[$__interval]))\n"
    }
   ]
  },
  {
   "title": "🏔Peak Backend Git Requests per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 28 },
   "format": "locale",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{environment=\"gprd\"}[$__interval]))"
    }
   ]
  },
  { "title": "Git User Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 34 },
   "content": "# Git Pull Operations (ssh + https)\n\n------------------------------------"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 34 },
   "content": "# Git Push Operations (ssh + https)\n\n------------------------------------"
  },
  {
   "title": "Current Git Pull Operations per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 37 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"SSHUploadPack\"}[1m]) or rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"PostUploadPack\"}[1m]))\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Current Git Push Operations per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 37 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"SSHReceivePack\"}[1m]) or rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"PostReceivePack\"}[1m]))\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "🏔Peak Daily Git Pull Operations per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 42 },
   "format": "locale",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"SSHUploadPack\"}[$__interval]) or rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"PostUploadPack\"}[$__interval]))\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "🏔Peak Daily Git Push Operations per Second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 42 },
   "format": "locale",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"SSHReceivePack\"}[$__interval]) or rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"PostReceivePack\"}[$__interval]))\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Average Git Pull Operations per Day",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 47 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"SSHUploadPack\"}[7d]) or rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"PostUploadPack\"}[7d])) * 86400\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Average Git Push Operations per Day",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 47 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"SSHReceivePack\"}[7d]) or rate(grpc_server_started_total{environment=\"gprd\", grpc_method=\"PostReceivePack\"}[7d])) * 86400\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Unique Registered User Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 53 },
   "content": "# Unique Registered Web Users\n\n------------------------------------"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 53 },
   "content": "# Unique Registered API Users\n\n------------------------------------"
  },
  {
   "title": "Unique Registered Users over past hour (Web)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 56 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "json.tag.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "json.username.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "json.tag.keyword:\"rails.production\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unique Registered Users over past hour (API)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 56 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "json.tag.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "json.username.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "json.tag.keyword:\"rails.api\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unique Registered Users over past day (Web)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 61 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "json.tag.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "json.username.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "json.tag.keyword:\"rails.production\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unique Registered Users over past day (API)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 61 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "json.tag.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "json.username.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "json.tag.keyword:\"rails.api\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unique Registered Users over past 7 days (Web)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 66 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "json.tag.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "json.username.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "json.tag.keyword:\"rails.production\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unique Registered Users over past 7 days (API)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 66 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "json.tag.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "json.username.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "json.tag.keyword:\"rails.api\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "CI Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 72 },
   "content": "# CI Runner Fleet\n\n------------------------------------"
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 72 },
   "content": "# CI Pipelines\n\n------------------------------------"
  },
  {
   "title": "Current GitLab Runner Fleet Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 75 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(gcp_exporter_instances_count{project=\"gitlab-ci-155816\",tags=~\".*docker-machine.*\"}) without (instance))"
    }
   ]
  },
  {
   "title": "Currently Executing CI Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 75 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{state=\"running\"})"
    }
   ]
  },
  {
   "title": "Average Daily GitLab Runner Fleet Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 80 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max(gcp_exporter_instances_count{project=\"gitlab-ci-155816\",tags=~\".*docker-machine.*\"}) without (instance))"
    }
   ]
  },
  {
   "title": "Average Number of CI Jobs Per Day",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 80 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(job_register_attempts_total[1d]) - rate(job_register_attempts_failed_total[1d])) * 86400"
    }
   ]
  },
  {
   "title": "🏔Peak GitLab Runner Fleet Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 85 },
   "format": "locale",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(max(gcp_exporter_instances_count{project=\"gitlab-ci-155816\",tags=~\".*docker-machine.*\"}) without (instance))"
    }
   ]
  },
  {
   "title": "🏔Peak Concurrent CI Jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 85 },
   "format": "locale",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{state=\"running\"})"
    }
   ]
  }
 ]
}