{
 "title": "version.gitlab.com",
 "time": { "from": "now-1d/d", "to": "now-1d/d" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max_over_time(instance:node_cpu_utilization:ratio{env=\"ops\",fqdn=\"version.gitlab.com\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Probe Success",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_success{env=\"gprd\",instance=\"https://version.gitlab.com\",job=\"blackbox\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Blackbox Probe Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_http_duration_seconds{env=\"gprd\",instance=\"https://version.gitlab.com\",job=\"blackbox\",monitor=\"default\"}[$__interval])",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Blackbox Probe Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(probe_http_duration_seconds{env=\"gprd\",instance=\"https://version.gitlab.com\",job=\"blackbox\",monitor=\"default\"}[$__interval])",
     "legendFormat": "{{phase}}"
    }
   ]
  }
 ]
}