{
 "title": "waf: Overview",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4977361853 at Tue Aug 29 21:27:50 UTC 2023",
 "tags": [
  "managed",
  "waf",
  "gitlab",
  "type:waf",
  "waf",
  "service overview"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "waf Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "waf error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"waf\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"waf\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "waf error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"waf\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "waf Service | Errors"
    }
   ]
  },
  {
   "title": "waf Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}[$__interval])\n",
     "legendFormat": "waf RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "gitlab_net_zone SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"gitlab_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "gitlab_net_zone error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_net_zone\",monitor=\"global\",type=\"waf\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_net_zone\",monitor=\"global\",type=\"waf\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"gitlab_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "gitlab_net_zone error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"gitlab_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_net_zone\",monitor=\"global\",type=\"waf\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"gitlab_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"gitlab_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_net_zone\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"gitlab_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_net_zone\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"gitlab_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_net_zone\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"gitlab_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_net_zone\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "gitlab_net_zone SLI | Errors"
    }
   ]
  },
  {
   "title": "gitlab_net_zone SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"gitlab_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}[$__interval])\n",
     "legendFormat": "gitlab_net_zone RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"gitlab_net_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Description\n\nAggregation of all GitLab.net (non-pulic) traffic passing through the WAF.\n\nErrors on this SLI may indicate that the WAF has detected\nmalicious traffic and is blocking it.\n\n"
  },
  {
   "title": "gitlab_zone SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"gitlab_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "gitlab_zone error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_zone\",monitor=\"global\",type=\"waf\"})\n)\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_zone\",monitor=\"global\",type=\"waf\"})\n)\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"gitlab_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "gitlab_zone error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"gitlab_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_zone\",monitor=\"global\",type=\"waf\"})\n)\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"gitlab_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"gitlab_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_zone\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"gitlab_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_zone\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"gitlab_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_zone\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"gitlab_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{component=\"gitlab_zone\",monitor=\"global\",type=\"waf\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "gitlab_zone SLI | Errors"
    }
   ]
  },
  {
   "title": "gitlab_zone SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"gitlab_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"}[$__interval])\n",
     "legendFormat": "gitlab_zone RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"gitlab_zone\",env=\"ops\",environment=\"ops\",monitor=\"global\",type=\"waf\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "content": "### Description\n\nAggregation of all public traffic for GitLab.com passing through the WAF.\n\nErrors on this SLI may indicate that the WAF has detected\nmalicious traffic and is blocking it. It may also indicate\nserious upstream failures on GitLab.com.\n\n"
  },
  {
   "title": "🔬 SLI Detail: gitlab_net_zone",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "collapsed": true,
   "panels": [
    {
     "title": "gitlab_net_zone Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(cloudflare_zone_requests_status{env=\"ops\",environment=\"ops\",status=~\"5..\",zone=\"gitlab.net\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "gitlab_net_zone RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(cloudflare_zone_requests_total{env=\"ops\",environment=\"ops\",zone=\"gitlab.net\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 SLI Detail: gitlab_zone",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "collapsed": true,
   "panels": [
    {
     "title": "gitlab_zone Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(cloudflare_zone_requests_status{env=\"ops\",environment=\"ops\",status=~\"5..\",zone=~\"gitlab.com|staging.gitlab.com\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "gitlab_zone RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(cloudflare_zone_requests_total{env=\"ops\",environment=\"ops\",zone=~\"gitlab.com|staging.gitlab.com\"}[$__interval])\n)\n > 0",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-ratelimiting\n  redis-db-load-balancing\n  redis-registry-cache\n  redis-repository-cache\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  nat\n  search\nend\n\nsubgraph lb\n  frontend\n  waf\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\n  praefect\nend\n\nsubgraph sv\n  api\n  consul\n  git\n  kas\n  pvs\n  registry\n  web\nend\n\n\n  api --> consul\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> praefect\napi --> pvs\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-ratelimiting\napi --> redis-repository-cache\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\nfrontend --> api\nfrontend --> git\nfrontend --> registry\nfrontend --> web\ngit --> consul\ngit --> gitaly\ngit --> google-cloud-storage\ngit --> patroni\ngit --> pgbouncer\ngit --> praefect\ngit --> pvs\ngit --> redis\ngit --> redis-cluster-cache\ngit --> redis-sidekiq\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> praefect\nkas --> redis\nnat --> frontend\npgbouncer --> patroni\npraefect --> cloud-sql\npraefect --> gitaly\nregistry --> api\nregistry --> redis-registry-cache\nwaf --> frontend\nwaf --> nat\nweb --> consul\nweb --> gitaly\nweb --> google-cloud-storage\nweb --> patroni\nweb --> pgbouncer\nweb --> praefect\nweb --> pvs\nweb --> redis\nweb --> redis-cluster-cache\nweb --> redis-cluster-chat-cache\nweb --> redis-cluster-feature-flag\nweb --> redis-cluster-ratelimiting\nweb --> redis-db-load-balancing\nweb --> redis-repository-cache\nweb --> redis-sessions\nweb --> redis-sidekiq\nweb --> search\n"
     },
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql\n  patroni\n  pgbouncer\n  redis\n  redis-cluster-cache\n  redis-cluster-chat-cache\n  redis-cluster-feature-flag\n  redis-cluster-ratelimiting\n  redis-db-load-balancing\n  redis-registry-cache\n  redis-repository-cache\n  redis-sessions\n  redis-sidekiq\n  redis-tracechunks\nend\n\nsubgraph inf\n  nat\n  search\nend\n\nsubgraph lb\n  frontend\n  waf\nend\n\nsubgraph stor\n  gitaly\n  google-cloud-storage\n  praefect\nend\n\nsubgraph sv\n  api\n  consul\n  git\n  kas\n  pvs\n  registry\n  web\nend\n\n\n  api --> consul\napi --> gitaly\napi --> google-cloud-storage\napi --> kas\napi --> patroni\napi --> pgbouncer\napi --> praefect\napi --> pvs\napi --> redis\napi --> redis-cluster-cache\napi --> redis-cluster-chat-cache\napi --> redis-cluster-feature-flag\napi --> redis-cluster-ratelimiting\napi --> redis-repository-cache\napi --> redis-sessions\napi --> redis-sidekiq\napi --> redis-tracechunks\napi --> search\nfrontend --> api\nfrontend --> git\nfrontend --> registry\nfrontend --> web\ngit --> consul\ngit --> gitaly\ngit --> google-cloud-storage\ngit --> patroni\ngit --> pgbouncer\ngit --> praefect\ngit --> pvs\ngit --> redis\ngit --> redis-cluster-cache\ngit --> redis-sidekiq\ngitaly --> gitaly\nkas --> api\nkas --> gitaly\nkas --> kas\nkas --> praefect\nkas --> redis\nnat --> frontend\npgbouncer --> patroni\npraefect --> cloud-sql\npraefect --> gitaly\nregistry --> api\nregistry --> redis-registry-cache\nwaf --> frontend\nwaf --> nat\nweb --> consul\nweb --> gitaly\nweb --> google-cloud-storage\nweb --> patroni\nweb --> pgbouncer\nweb --> praefect\nweb --> pvs\nweb --> redis\nweb --> redis-cluster-cache\nweb --> redis-cluster-chat-cache\nweb --> redis-cluster-feature-flag\nweb --> redis-cluster-ratelimiting\nweb --> redis-db-load-balancing\nweb --> redis-repository-cache\nweb --> redis-sessions\nweb --> redis-sidekiq\nweb --> search\n"
     },
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",monitor=\"global\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Maturity Model)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "format": "percentunit",
     "valueName": "current",
     "options": {
      "content": "graph TD\n  subgraph db\n  cloud-sql[\"cloud-sql (Level 1)\"]\n  patroni[\"patroni (Level 2)\"]\n  pgbouncer[\"pgbouncer (Level 1)\"]\n  redis-cluster-cache[\"redis-cluster-cache (Level 2)\"]\n  redis-cluster-chat-cache[\"redis-cluster-chat-cache (Level 2)\"]\n  redis-cluster-feature-flag[\"redis-cluster-feature-flag (Level 2)\"]\n  redis-cluster-ratelimiting[\"redis-cluster-ratelimiting (Level 2)\"]\n  redis-db-load-balancing[\"redis-db-load-balancing (Level 2)\"]\n  redis-registry-cache[\"redis-registry-cache (Level 2)\"]\n  redis-repository-cache[\"redis-repository-cache (Level 2)\"]\n  redis-sessions[\"redis-sessions (Level 3)\"]\n  redis-sidekiq[\"redis-sidekiq (Level 3)\"]\n  redis-tracechunks[\"redis-tracechunks (Level 3)\"]\n  redis[\"redis (Level 3)\"]\nend\n\nsubgraph inf\n  nat[\"nat (Level 1)\"]\n  search[\"search (Level 1)\"]\nend\n\nsubgraph lb\n  frontend[\"frontend (Level 3)\"]\n  waf[\"waf (Level 1)\"]\nend\n\nsubgraph stor\n  gitaly[\"gitaly (Level 3)\"]\n  google-cloud-storage[\"google-cloud-storage (Level 2)\"]\n  praefect[\"praefect (Level 2)\"]\nend\n\nsubgraph sv\n  api[\"api (Level 2)\"]\n  consul[\"consul (Level 1)\"]\n  git[\"git (Level 2)\"]\n  kas[\"kas (Level 3)\"]\n  pvs[\"pvs (Level 3)\"]\n  registry[\"registry (Level 2)\"]\n  web[\"web (Level 2)\"]\nend\n\n\n  api[\"api (Level 2)\"] --> consul\napi[\"api (Level 2)\"] --> gitaly\napi[\"api (Level 2)\"] --> google-cloud-storage\napi[\"api (Level 2)\"] --> kas\napi[\"api (Level 2)\"] --> patroni\napi[\"api (Level 2)\"] --> pgbouncer\napi[\"api (Level 2)\"] --> praefect\napi[\"api (Level 2)\"] --> pvs\napi[\"api (Level 2)\"] --> redis\napi[\"api (Level 2)\"] --> redis-cluster-cache\napi[\"api (Level 2)\"] --> redis-cluster-chat-cache\napi[\"api (Level 2)\"] --> redis-cluster-feature-flag\napi[\"api (Level 2)\"] --> redis-cluster-ratelimiting\napi[\"api (Level 2)\"] --> redis-repository-cache\napi[\"api (Level 2)\"] --> redis-sessions\napi[\"api (Level 2)\"] --> redis-sidekiq\napi[\"api (Level 2)\"] --> redis-tracechunks\napi[\"api (Level 2)\"] --> search\nfrontend[\"frontend (Level 3)\"] --> api\nfrontend[\"frontend (Level 3)\"] --> git\nfrontend[\"frontend (Level 3)\"] --> registry\nfrontend[\"frontend (Level 3)\"] --> web\ngit[\"git (Level 2)\"] --> consul\ngit[\"git (Level 2)\"] --> gitaly\ngit[\"git (Level 2)\"] --> google-cloud-storage\ngit[\"git (Level 2)\"] --> patroni\ngit[\"git (Level 2)\"] --> pgbouncer\ngit[\"git (Level 2)\"] --> praefect\ngit[\"git (Level 2)\"] --> pvs\ngit[\"git (Level 2)\"] --> redis\ngit[\"git (Level 2)\"] --> redis-cluster-cache\ngit[\"git (Level 2)\"] --> redis-sidekiq\ngitaly[\"gitaly (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> api\nkas[\"kas (Level 3)\"] --> gitaly\nkas[\"kas (Level 3)\"] --> kas\nkas[\"kas (Level 3)\"] --> praefect\nkas[\"kas (Level 3)\"] --> redis\nnat[\"nat (Level 1)\"] --> frontend\npgbouncer[\"pgbouncer (Level 1)\"] --> patroni\npraefect[\"praefect (Level 2)\"] --> cloud-sql\npraefect[\"praefect (Level 2)\"] --> gitaly\nregistry[\"registry (Level 2)\"] --> api\nregistry[\"registry (Level 2)\"] --> redis-registry-cache\nwaf[\"waf (Level 1)\"] --> frontend\nwaf[\"waf (Level 1)\"] --> nat\nweb[\"web (Level 2)\"] --> consul\nweb[\"web (Level 2)\"] --> gitaly\nweb[\"web (Level 2)\"] --> google-cloud-storage\nweb[\"web (Level 2)\"] --> patroni\nweb[\"web (Level 2)\"] --> pgbouncer\nweb[\"web (Level 2)\"] --> praefect\nweb[\"web (Level 2)\"] --> pvs\nweb[\"web (Level 2)\"] --> redis\nweb[\"web (Level 2)\"] --> redis-cluster-cache\nweb[\"web (Level 2)\"] --> redis-cluster-chat-cache\nweb[\"web (Level 2)\"] --> redis-cluster-feature-flag\nweb[\"web (Level 2)\"] --> redis-cluster-ratelimiting\nweb[\"web (Level 2)\"] --> redis-db-load-balancing\nweb[\"web (Level 2)\"] --> redis-repository-cache\nweb[\"web (Level 2)\"] --> redis-sessions\nweb[\"web (Level 2)\"] --> redis-sidekiq\nweb[\"web (Level 2)\"] --> search\n"
     }
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}