{
 "title": "Web Overview BJK",
 "description": "An overview of all web requests",
 "tags": [
  "prometheus",
  "wip"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "process_type", "label": "Process Type", "query": "web,api" },
   { "name": "environment", "label": "Environment", "query": "prd,stg,dev" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(job_environment:gitlab_transaction_duration_seconds_count:rate5m{environment = \"$environment\", type != \"sidekiq\"})",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "legendFormat": "Amount (transaction)",
     "measurement": "transactions",
     "query": "SELECT \"count\" as \"Amount\" FROM downsampled.\"[[process_type]]_transaction_counts_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{environment = \"$environment\", type != \"sidekiq\"}[5m]))",
     "legendFormat": "Ammount (http)"
    }
   ]
  },
  {
   "title": "$process_type Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(job_environment:gitlab_transaction_duration_seconds_count:rate5m{environment = \"$environment\", type = \"$process_type\"})",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "legendFormat": "Amount",
     "measurement": "transactions",
     "query": "SELECT \"count\" as \"Amount\" FROM downsampled.\"[[process_type]]_transaction_counts_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Timings (log₂)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "job_environment:gitlab_transaction_duration_seconds:p95{environment = \"$environment\", type = \"$process_type\"}",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "legendFormat": "95th Percentile",
     "measurement": "gitlab.transaction",
     "query": "SELECT \"duration_95th\" AS \"95th Percentile\", \"duration_99th\" as \"99th Percentile\", \"duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "job_environment:gitlab_transaction_duration_seconds:p99{environment = \"$environment\", type = \"$process_type\"}",
     "legendFormat": "99h Percentile"
    },
    {
     "expr": "job_environment:gitlab_transaction_duration_latency_seconds:rate5m{environment = \"$environment\", type = \"$process_type\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{environment=\"$environment\",type=\"$process_type\"}[5m])) \n  /\nsum(rate(http_request_duration_seconds_count{environment=\"$environment\",type=\"$process_type\"}[5m]))",
     "legendFormat": "Mean (http)"
    },
    {
     "expr": "sum(rate(rails_requests_completed_seconds_sum{environment=\"$environment\",type=\"$process_type\"}[5m])) \n  /\nsum(rate(rails_requests_completed_seconds_count{environment=\"$environment\",type=\"$process_type\"}[5m]))",
     "legendFormat": "Mean (mtail/rails)"
    }
   ]
  },
  {
   "title": "HTTP Queue Timings (log₂)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(gitlab_rails_queue_duration_seconds_sum{environment = \"$environment\", type = \"$process_type\"}[1m]) * 60)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "SQL Timings (log₂)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "job_environment:gitlab_sql_latency_seconds:rate5m{environment = \"$environment\", type = \"$process_type\"}",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "legendFormat": "Mean",
     "measurement": "gitlab.transaction",
     "query": "SELECT \"sql_duration_95th\" AS \"95th Percentile\", \"sql_duration_99th\" as \"99th Percentile\", \"sql_duration_mean\" AS \"Mean\" FROM downsampled.\"[[process_type]]_transaction_timings_overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "job_environment:gitlab_sql_duration_seconds:p95{environment = \"$environment\", type = \"$process_type\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "job_environment:gitlab_sql_duration_seconds:p99{environment = \"$environment\", type = \"$process_type\"}",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "SQL Query Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "job_environment:gitlab_sql_duration_seconds_count:rate5m{environment = \"$environment\", type = \"$process_type\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}