{
 "title": "web-pages: Capacity Review",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/4316440639 at Fri May 19 15:12:33 UTC 2023",
 "tags": [
  "managed",
  "web-pages",
  "web-pages",
  "type:web-pages",
  "capacity-review"
 ],
 "time": { "from": "now-15d/d", "to": "now-1d/d" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   }
  ]
 },
 "panels": [
  {
   "title": "disk_space: Disk Space Utilization per Device per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(2)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"disk_space\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"disk_space\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Disk Space Utilization per Device per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"disk_space\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"disk_space\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"disk_space\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_space\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 2 },
   "content": "Disk space utilization per device per node.\n"
  },
  {
   "title": "disk_inodes: Disk inode Utilization per Device per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(2)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"disk_inodes\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"disk_inodes\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Disk inode Utilization per Device per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"disk_inodes\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"disk_inodes\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"disk_inodes\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"disk_inodes\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 102 },
   "content": "Disk inode utilization per device per node.\n\nIf this is too high, its possible that a directory is filling up with\nfiles. Consider logging in an checking temp directories for large numbers\nof files\n"
  },
  {
   "title": "open_fds: Open file descriptor utilization per instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(2)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"open_fds\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"open_fds\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Open file descriptor utilization per instance",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"open_fds\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"open_fds\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"open_fds\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"open_fds\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 202 },
   "content": "Open file descriptor utilization per instance.\n\nSaturation on file descriptor limits may indicate a resource-descriptor leak in the application.\n\nAs a temporary fix, you may want to consider restarting the affected process.\n"
  },
  {
   "title": "shard_cpu: Average CPU Utilization per Shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"shard_cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"shard_cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Average CPU Utilization per Shard",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 302 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"shard_cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"shard_cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"shard_cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"shard_cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 302 },
   "content": "This resource measures average CPU utilization across an all cores in a shard of a\nservice fleet. If it is becoming saturated, it may indicate that the\nshard needs horizontal or vertical scaling.\n"
  },
  {
   "title": "kube_pool_cpu: Average Node Pool CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 401 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 401 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 401 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_pool_cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 401 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_pool_cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Average Node Pool CPU Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 402 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_pool_cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_pool_cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_pool_cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_pool_cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_pool_cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 402 },
   "content": "This resource measures average CPU utilization across an all cores in the node pool for\na service fleet.\n\nIf it is becoming saturated, it may indicate that the fleet needs horizontal scaling.\n"
  },
  {
   "title": "cpu: Average Service CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 501 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 501 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 501 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 501 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Average Service CPU Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 502 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 502 },
   "content": "This resource measures average CPU utilization across an all cores in a service fleet.\nIf it is becoming saturated, it may indicate that the fleet needs\nhorizontal or vertical scaling.\n"
  },
  {
   "title": "kube_horizontalpodautoscaler_desired_replicas: Horizontal Pod Autoscaler Desired Replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 600 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 601 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 601 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 601 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_horizontalpodautoscaler_desired_replicas\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 601 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_horizontalpodautoscaler_desired_replicas\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Horizontal Pod Autoscaler Desired Replicas",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 602 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_horizontalpodautoscaler_desired_replicas\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_horizontalpodautoscaler_desired_replicas\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 602 },
   "content": "The [Horizontal Pod Autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)\nautomatically scales the number of Pods in a deployment based on metrics.\n\nThe Horizontal Pod Autoscaler has a configured upper maximum. When this\nlimit is reached, the HPA will not increase the number of pods and other\nresource saturation (eg, CPU, memory) may occur.\n"
  },
  {
   "title": "kube_pool_max_nodes: Kube Pool Max Node Limit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 700 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 701 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 701 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 701 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_pool_max_nodes\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 701 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_pool_max_nodes\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Kube Pool Max Node Limit",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 702 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_pool_max_nodes\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_pool_max_nodes\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_pool_max_nodes\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_pool_max_nodes\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_pool_max_nodes\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 702 },
   "content": "A GKE kubernetes node pool is close to it's maximum number of nodes.\n\nThe maximum is defined in terraform, via the `max_node_count` field of a node pool. The limit is per-zone, so for\nsingle zone clusters the number of nodes will match the limit, for regional clusters, the limit is multiplied by\nthe number of zones the cluster is deployed over.\n"
  },
  {
   "title": "nf_conntrack_entries: conntrack Entries per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 800 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 801 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(3)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 801 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 801 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"nf_conntrack_entries\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 801 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"nf_conntrack_entries\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "conntrack Entries per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 802 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"nf_conntrack_entries\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"nf_conntrack_entries\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"nf_conntrack_entries\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"nf_conntrack_entries\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 802 },
   "content": "Netfilter connection tracking table utilization per node.\n\nWhen saturated, new connection attempts (incoming SYN packets) are dropped with no reply, leaving clients to slowly retry (and typically fail again) over the next several seconds.  When packets are being dropped due to this condition, kernel will log the event as: \"nf_conntrack: table full, dropping packet\".\n"
  },
  {
   "title": "single_node_cpu: Average CPU Utilization per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 900 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 901 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 901 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 901 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"single_node_cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 901 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"single_node_cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Average CPU Utilization per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 902 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"single_node_cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"single_node_cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"single_node_cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"single_node_cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 902 },
   "content": "Average CPU utilization per Node.\n\nIf average CPU is saturated, it may indicate that a fleet is in need to horizontal or vertical scaling. It may also indicate\nimbalances in load in a fleet.\n"
  },
  {
   "title": "go_memory: Go Memory Utilization per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1001 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1001 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"go_memory\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1001 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"go_memory\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Go Memory Utilization per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1002 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"go_memory\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"go_memory\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"go_memory\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"go_memory\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1002 },
   "content": "Go's memory allocation strategy can make it look like a Go process is saturating memory when measured using RSS, when in fact\nthe process is not at risk of memory saturation. For this reason, we measure Go processes using the `go_memstat_alloc_bytes`\nmetric instead of RSS.\n"
  },
  {
   "title": "kube_go_memory: Go Memory Utilization per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1100 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_go_memory\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1101 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_go_memory\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Go Memory Utilization per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1102 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_go_memory\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_go_memory\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_go_memory\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_go_memory\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1102 },
   "content": "Measures Go memory usage as a percentage of container memory limit\n"
  },
  {
   "title": "kube_container_cpu: Kube Container CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1200 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1201 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_cpu\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1201 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_cpu\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Kube Container CPU Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1202 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_container_cpu\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_container_cpu\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_container_cpu\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1202 },
   "content": "Kubernetes containers are allocated a share of CPU. When this is exhausted, the container may be thottled.\n"
  },
  {
   "title": "kube_container_memory: Kube Container Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1300 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1301 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_memory\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1301 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"kube_container_memory\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Kube Container Memory Utilization",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1302 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_container_memory\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_container_memory\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"kube_container_memory\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_memory\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1302 },
   "content": "This uses the working set size from cAdvisor for the cgroup's memory usage. That may\nnot be a good measure as it includes filesystem cache pages that are not necessarily\nattributable to the application inside the cgroup, and are permitted to be evicted\ninstead of being OOM killed.\n"
  },
  {
   "title": "memory: Memory Utilization per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1400 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1401 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1401 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1401 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"memory\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1401 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"memory\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Memory Utilization per Node",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1402 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"memory\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"memory\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"memory\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"memory\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1402 },
   "content": "Memory utilization per device per node.\n"
  },
  {
   "title": "node_schedstat_waiting: Node Scheduler Waiting Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1500 }
  },
  {
   "title": "Saturation Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1501 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(4)\n" }
   ]
  },
  {
   "title": "Scaling Characteristics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1501 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(1)\n" }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Average Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1501 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"node_schedstat_waiting\",confidence_type=\"mean\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Tamland Predicted Threshold Violation, Pessimistic Case",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1501 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tamland_forecast_violation_days{component=\"node_schedstat_waiting\",confidence_type=\"80%\",env=\"ops\",environment=\"ops\",threshold_type=\"hard\",type=\"web-pages\"}\n"
    }
   ]
  },
  {
   "title": "Node Scheduler Waiting Time",
   "type": "graph",
   "description": "Timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1502 },
   "yaxes": [
    { "format": "percentunit", "label": "Saturation %" }
   ],
   "targets": [
    {
     "expr": "clamp_min(\n  clamp_max(\n    max(\n      gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"node_schedstat_waiting\"}\n    ) by (component)\n  ,1)\n,0)\n",
     "legendFormat": "aggregated {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"node_schedstat_waiting\"}\n)\n",
     "legendFormat": "95th quantile for week {{ component }}"
    },
    {
     "expr": "max(\n  gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"main\",type=\"web-pages\", component=\"node_schedstat_waiting\"}\n)\n",
     "legendFormat": "99th quantile for week {{ component }}"
    },
    {
     "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
     "legendFormat": "Soft SLO: {{ component }}"
    },
    {
     "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"node_schedstat_waiting\"}) by (component)\n",
     "legendFormat": "Hard SLO: {{ component }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1502 },
   "content": "Measures the amount of scheduler waiting time that processes are waiting\nto be scheduled, according to [`CPU Scheduling Metrics`](https://www.robustperception.io/cpu-scheduling-metrics-from-the-node-exporter).\n\nA high value indicates that a node has more processes to be run than CPU time available\nto handle them, and may lead to degraded responsiveness and performance from the application.\n\nAdditionally, it may indicate that the fleet is under-provisioned.\n"
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}