{
 "title": "web: Kube Deployment Detail",
 "description": "Uploaded by https://gitlab.com/gitlab-com/runbooks/-/jobs/3918925111 at Mon Mar 13 00:15:05 UTC 2023",
 "tags": [
  "managed",
  "web",
  "web",
  "type:web",
  "kube",
  "kube detail"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  { "title": "web deployment", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "web Deployment: CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      deployment=\"web\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "web Deployment: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    deployment=\"web\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"\n  }\n)\n",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "web Deployment: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"web\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "send {{ cluster }}"
    },
    {
     "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"web\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }}"
    }
   ]
  },
  {
   "title": "Node CPU Requests Utilization",
   "type": "graph",
   "description": "Ratio of requested CPU resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by memory requests already.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n  kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\",resource=\"cpu\"}\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node Memory Requests Utilization",
   "type": "graph",
   "description": "Ratio of requested Memory resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by CPU requests already.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n  kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\"}\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\",resource=\"memory\"}\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards)\n"
  }
 ]
}