{
 "title": "Web Latency Issue",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Redis CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(redis_used_cpu_user{environment=\"gprd\"}[1m]) + rate(redis_used_cpu_sys{environment=\"gprd\"}[1m]) ",
     "legendFormat": "{{fqdn}} CPu"
    }
   ]
  },
  {
   "title": "Node MemFree",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemFree_bytes{fqdn=~\"web-.*-sv-gprd.*\"}) / 1000 / 1024 ",
     "legendFormat": "Node MemFree"
    }
   ]
  },
  {
   "title": "DB Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"gitlabhq_production\", environment=\"gprd\", tier=\"db\", type=\"patroni\"}[$__interval])",
     "legendFormat": "{{fqdn}} committed"
    }
   ]
  },
  {
   "title": "Active Conns > 42  workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unicorn_active_connections{fqdn=~\"web-.*-sv-gprd.*\", environment=\"gprd\", type=\"web\", socket_address=\"/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket\"} > 42  ",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Web Apdex VS internal_ids for update time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(pg_stat_statements_time_milliseconds{queryid=\"2722666312\"}[$__interval]))",
     "legendFormat": "QueryTime"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio{type=\"web\", environment=\"gprd\", stage=\"main\"}[$__interval])",
     "legendFormat": "Web Apdex"
    }
   ]
  },
  {
   "title": "Unicorn Max Memory Exceeds | SIGQUIT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(unicorn_exceeds_memory_limit_total{fqdn=~\"web-[0-9][0-9]-sv-gprd.*\", environment=\"gprd\"}[5m]) * 300)",
     "legendFormat": "Unicorn Memory Exceeds"
    }
   ]
  },
  {
   "title": "GitHub Imports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(github_importer_imported_projects{environment = \"gprd\"}[$__interval])) * 3600",
     "legendFormat": "Projects"
    },
    {
     "expr": "sum(rate(github_importer_imported_issues{environment = \"gprd\"}[$__interval])) * 3600",
     "legendFormat": "Issues"
    },
    {
     "expr": "sum(rate(github_importer_imported_repositories{environment = \"gprd\"}[$__interval])) * 3600",
     "legendFormat": "Repositories"
    },
    {
     "expr": "sum(rate(github_importer_imported_pull_requests{environment = \"gprd\"}[$__interval])) * 3600",
     "legendFormat": "PRs"
    },
    {
     "expr": "sum((rate(github_importer_imported_notes{environment=\"gprd\"}[$__interval]) + rate(github_importer_imported_diff_notes{environment=\"gprd\"}[$__interval]))) * 3600",
     "legendFormat": "Notes"
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(avg_over_time(instance:memory_utilization:ratio_q95{environment=\"gprd\",fqdn=~\"web-[0-9][0-9]-sv-gprd.*\"}[5m]))",
     "legendFormat": "Memory Utiliization"
    },
    {
     "expr": "avg(avg_over_time(instance:cpu_utilization:ratio_q95{environment=\"gprd\",fqdn=~\"web-[0-9][0-9]-sv-gprd.*\"}[5m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg((node_memory_Cached_bytes{fqdn=~\"web-[0-9][0-9]-sv-gprd.*\", environment=\"gprd\"} + node_memory_Buffers_bytes{fqdn=~\"web-[0-9][0-9]-sv-gprd.*\", environment=\"gprd\"}) / 1000 / 1024 / 1024)",
     "legendFormat": "Buff/Cache"
    }
   ]
  },
  {
   "title": "Unicorn  Queued Conns",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(job:unicorn_queued_connections:sum{environment=\"gprd\",type=\"web\"}[1m]))  ",
     "legendFormat": "Unicorn  Queued Conns"
    }
   ]
  },
  {
   "title": "Traffic (HAProxy Frontend)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_requests_total{environment=\"gprd\", frontend=~\"http[s]\"}[5m]))",
     "legendFormat": "Traffic (HAProxy Frontend)"
    }
   ]
  }
 ]
}