{
 "title": "WebPageTest",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "sitespeed_io" },
   { "name": "path", "query": "$base.*" },
   { "name": "testname", "query": "$base.$path.*" },
   {
    "name": "group",
    "label": "domain",
    "query": "$base.$path.$testname.pageSummary.*"
   },
   {
    "name": "page",
    "query": "$base.$path.$testname.pageSummary.$group.*"
   },
   {
    "name": "browser",
    "query": "$base.$path.$testname.pageSummary.$group.$page.*"
   },
   {
    "name": "location",
    "query": "$base.$path.$testname.pageSummary.$group.$page.webpagetest.*"
   },
   {
    "name": "connectivity",
    "query": "$base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.*"
   },
   {
    "name": "view",
    "query": "$base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.*"
   }
  ]
 },
 "panels": [
  { "title": "Google Web Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.firstContentfulPaint, 'First Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.LargestContentfulPaint, 'Largest Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.TotalBlockingTime, 'Total Blocking Time')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.CumulativeLayoutShift, 'Cumulative Layout Shift')"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Metrics",
   "type": "graph",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.render, 'First Visual Change')"
    },
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, 'Last Visual Change')"
    },
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.TTFB, 'TTFB')"
    },
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, 'Fully Loaded')"
    },
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, 'Speed Index')"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.requestsFull, 11)"
    }
   ]
  },
  {
   "title": "Total size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.bytesIn, 'Size')"
    }
   ]
  },
  {
   "title": "DOM elements",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.domElements, 'Elements')"
    }
   ]
  },
  {
   "title": "Stdev",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view.render, 'Render')"
    }
   ]
  },
  {
   "title": "Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Visual Change",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "alias(movingAverage($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.render, '24h'), 'First Visual Change')"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.render, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "Speed Index",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(movingAverage($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), 12)"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "TTFB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "alias(movingAverage($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.TTFB, '24h'), 'TTFB')"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.TTFB, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "Fully loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "alias(movingAverage($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), 'Fully Loaded')"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "Speed Index",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, 11)"
      }
     ]
    }
   ]
  },
  { "title": "Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "HTML",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.breakdown.html.bytes, 'Size')"
    }
   ]
  },
  {
   "title": "JavaScript",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.breakdown.js.bytes, 'Size')"
    }
   ]
  },
  {
   "title": "CSS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.breakdown.css.bytes, 'Size')"
    }
   ]
  },
  {
   "title": "Image",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.breakdown.image.bytes, 'Size')"
    }
   ]
  },
  { "title": "User Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "User Timing API",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.userTimes.*, 13)"
    }
   ]
  },
  { "title": "Chrome", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU [Chrome only]",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.cpuTimes.*, 13)"
    }
   ]
  },
  {
   "title": "Chrome timings [Chrome only]",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.LargestContentfulPaint, 13)"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.domComplete, 13)"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.firstContentfulPaint, 13)"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.firstImagePaint, 13)"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.firstMeaningfulPaint, 13)"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.firstPaint, 13)"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.loadEventEnd, 13)"
    }
   ]
  }
 ]
}