{
 "title": "webservice Overview",
 "tags": [
  "type:web",
  "web",
  "service overview",
  "unmanaged"
 ],
 "time": { "from": "now-6h/m", "to": "now/m" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "environment",
    "query": "label_values(gitlab_service_ops:rate, environment)"
   },
   { "name": "stage", "query": "main,cny," }
  ]
 },
 "panels": [
  {
   "title": "🌡️ Aggregated Service Level Indicators (𝙎𝙇𝙄𝙨)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "web Service Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "web apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "web apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_service_apdex:ratio_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_service_apdex:ratio_1h{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_service_apdex:ratio_30m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_service_apdex:ratio_6h{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "web Service | Latency/Apdex"
    }
   ]
  },
  {
   "title": "web Service Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "web error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"}))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"}))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "web error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"}))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_service_errors:ratio_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_service_errors:ratio_1h{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_service_errors:ratio_30m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_service_errors:ratio_6h{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "web Service | Errors"
    }
   ]
  },
  {
   "title": "web Service RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "web RPS"
    },
    {
     "expr": "gitlab_service_ops:rate_5m{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} offset 1w\n",
     "legendFormat": "last week"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}\n    + (1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}\n  ),\n  0\n)\n",
     "legendFormat": "upper normal"
    },
    {
     "expr": "clamp_min(\n  avg by (type) (\n    gitlab_service_ops:rate:prediction{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}\n    + (-1) *\n    gitlab_service_ops:rate:stddev_over_time_1w{env=\"$environment\",environment=\"$environment\",monitor=\"global\",stage=\"$stage\",type=\"web\"}\n  ),\n  0\n)\n",
     "legendFormat": "lower normal"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "description": "Saturation is a measure of what ratio of a finite resource is currently being utilized. Lower is better.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval]\n  )\n) by (component)\n",
     "legendFormat": "{{ component }} component"
    }
   ]
  },
  { "title": "🔬 Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "imagescaler SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"imagescaler\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "imagescaler apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"imagescaler\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "imagescaler apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"imagescaler\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"imagescaler\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"imagescaler\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"imagescaler\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"imagescaler\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"imagescaler\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "imagescaler SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "imagescaler SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"imagescaler\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "imagescaler RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"imagescaler\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "content": "### Description\n\nThe imagescaler rescales images before sending them to clients. This allows faster transmission of\nimages and faster rendering of web pages.\n\n\n\n### Observability Tools\n\n* [📖 Kibana: Image Resizer logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.uri,json.imageresizer.content_type,json.imageresizer.original_filesize,json.imageresizer.target_width,json.imageresizer.status),filters:!((query:(match:(json.subsystem:(query:imageresizer,type:phrase)))),(query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Image Resizer failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.uri,json.imageresizer.content_type,json.imageresizer.original_filesize,json.imageresizer.target_width,json.imageresizer.status),filters:!((query:(match:(json.subsystem:(query:imageresizer,type:phrase)))),(query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase)))),(meta:(negate:!t),query:(match:(json.imageresizer.status:(query:success,type:phrase))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Image Resizer requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((query:(match:(json.subsystem:(query:imageresizer,type:phrase)))),(query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Image Resizer failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((query:(match:(json.subsystem:(query:imageresizer,type:phrase)))),(query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase)))),(meta:(negate:!t),query:(match:(json.imageresizer.status:(query:success,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "puma SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "puma apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "puma apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "puma SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "puma SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "puma error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"}))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"}))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "puma error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"}))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 38 },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "puma SLI | Errors"
    }
   ]
  },
  {
   "title": "puma SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "puma RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"puma\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "content": "### Description\n\nAggregation of most web requests that pass through the puma to the GitLab rails monolith.\nHealthchecks are excluded.\n\n\n\n### Observability Tools\n\n* [🐞 Sentry Releases: gitlab/gitlabcom](https://sentry.gitlab.net/gitlab/gitlabcom/releases?environment=${environment})\n* [🐞 Sentry web issues](https://sentry.gitlab.net/gitlab/gitlabcom/issues?environment=${environment}&query=stage%3A${stage}+type%3Aweb)\n* [📖 Kibana: Rails logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.controller,json.action,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.controller,json.action,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase)))),(query:(range:(json.duration_s:(gte:10))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090',sort:!(!(json.duration_s,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Rails failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.status,json.controller,json.action,json.path,json.duration_s),filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase)))),(query:(range:(json.status:(gte:500))))),index:'7092c4e2-4eb5-46f2-8305-a7da2edad090')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase)))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.controller.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.controller.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Rails percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=7092c4e2-4eb5-46f2-8305-a7da2edad090&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_s,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.controller.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_s),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_s'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "workhorse SLI Apdex",
   "type": "graph",
   "description": "Apdex is a measure of requests that complete within a tolerable period of time for the service. Higher is better.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Apdex %" }
   ],
   "targets": [
    {
     "expr": "min_over_time(gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "workhorse apdex"
    },
    {
     "expr": "(1 - 6 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "workhorse apdex avg"
    },
    {
     "expr": "clamp_min(\n  gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} offset 1w\n,\n  scalar(min((1 - 14.4 * (1 - avg(slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    vector(0) and on() (gitlab_component_apdex:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on () (gitlab_component_apdex:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on () (gitlab_component_apdex:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (14.4 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on () (gitlab_component_apdex:ratio_30m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on () (gitlab_component_apdex:ratio_6h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} < on(tier, type) group_left() (1 - (6 * (1 - slo:min:events:gitlab_service_apdex:ratio{monitor=\"global\",type=\"web\"})))),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "workhorse SLI | Latency/Apdex"
    }
   ]
  },
  {
   "title": "workhorse SLI Error Ratio",
   "type": "graph",
   "description": "Error rates are a measure of unhandled service exceptions per second. Client errors are excluded when possible. Lower is better",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "percentunit", "label": "Error %" }
   ],
   "targets": [
    {
     "expr": "clamp_max(\n  max_over_time(gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "workhorse error ratio"
    },
    {
     "expr": "(6 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"}))\n",
     "legendFormat": "6h Degradation SLO (5% of monthly error budget)"
    },
    {
     "expr": "(14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"}))\n",
     "legendFormat": "1h Outage SLO (2% of monthly error budget)"
    },
    {
     "expr": "clamp_max(\n  avg_over_time(gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n,\n  1\n)\n",
     "legendFormat": "workhorse error ratio avg"
    },
    {
     "expr": "clamp_max(\n  gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} offset 1w\n,\n  scalar(max((14.4 * avg(slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"}))\n))\n)\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 48 },
   "targets": [
    {
     "expr": "sum (\n  label_replace(\n    vector(0) and on() (gitlab_component_errors:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}),\n    \"period\", \"na\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(1) and on() (gitlab_component_errors:ratio_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"5m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(2) and on() (gitlab_component_errors:ratio_1h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (14.4 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"1h\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(4) and on() (gitlab_component_errors:ratio_30m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"30m\", \"\", \"\"\n  )\n  or\n  label_replace(\n    vector(8) and on() (gitlab_component_errors:ratio_6h{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} > on(tier, type) group_left() (6 * slo:max:events:gitlab_service_errors:ratio{monitor=\"global\",type=\"web\"})),\n    \"period\", \"6h\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "workhorse SLI | Errors"
    }
   ]
  },
  {
   "title": "workhorse SLI RPS - Requests per Second",
   "type": "graph",
   "description": "The operation rate is the sum total of all requests being handle for all components within this service. Note that a single user request can lead to requests to multiple components. Higher is busier.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Operations per Second" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_ops:rate_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n",
     "legendFormat": "workhorse RPS"
    },
    {
     "expr": "gitlab_component_ops:rate_5m{component=\"workhorse\",env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"} offset 1w\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Details",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "content": "### Description\n\nAggregation of most web requests that pass through workhorse, monitored via the HTTP interface.\nExcludes health, readiness and liveness requests. Some known slow requests, such as HTTP uploads,\nare excluded from the apdex score.\n\n\n\n### Observability Tools\n\n* [Google Stackdriver Continuous Profiling](https://console.cloud.google.com/profiler;timespan=4h/workhorse-web;type=CPU/cpu?project=gitlab-production)\n* [🐞 Sentry Releases: gitlab/gitlab-workhorse-gitlabcom](https://sentry.gitlab.net/gitlab/gitlab-workhorse-gitlabcom/releases?environment=${environment})\n* [🐞 Sentry issues](https://sentry.gitlab.net/gitlab/gitlab-workhorse-gitlabcom/issues?environment=${environment})\n* [📖 Kibana: Workhorse logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Workhorse slow request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase)))),(query:(range:(json.duration_ms:(gte:10000))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4',sort:!(!(json.duration_ms,desc)))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📖 Kibana: Workhorse failed request logs](https://log.gprd.gitlab.net/app/kibana#/discover?_a=(columns:!(json.method,json.remote_ip,json.status,json.uri,json.duration_ms),filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase)))),(query:(range:(json.status:(gte:500))))),index:'a4f5b470-edde-11ea-81e5-155ba78758d4')&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse failed requests](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase)))),(query:(range:(json.status:(gte:500))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse sum latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse sum latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms),schema:metric,type:sum),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Sum+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse percentile latency aggregated](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n* [📈 Kibana: Workhorse percentile latency aggregated (split)](https://log.gprd.gitlab.net/app/kibana#/visualize/create?type=line&indexPattern=a4f5b470-edde-11ea-81e5-155ba78758d4&_a=(filters:!((query:(match:(json.type.keyword:(query:web,type:phrase)))),(query:(match:(json.stage:(query:'$stage',type:phrase)))),(query:(match:(json.type:(query:web,type:phrase))))),query:(language:kuery,query:''),vis:(aggs:!((enabled:!t,id:'1',params:(field:json.duration_ms,percents:!(95)),schema:metric,type:percentiles),(enabled:!t,id:'2',params:(drop_partials:!t,extended_bounds:(),field:json.time,interval:auto,min_doc_count:1,scaleMetricValues:!f,timeRange:(from:'${__from:date:iso}',to:'${__to:date:iso}'),useNormalizedEsInterval:!t),schema:segment,type:date_histogram),(enabled:!t,id:'3',params:(field:json.remote_ip.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(field:json.duration_ms),schema:orderAgg,type:sum),orderBy:custom,otherBucket:!t,otherBucketLabel:Other,size:5),schema:group,type:terms)),params:(valueAxes:!((id:'ValueAxis-1',name:'LeftAxis-1',position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'p95+Request+Duration:+json.duration_ms'),type:value)))))&_g=(time:(from:'${__from:date:iso}',to:'${__to:date:iso}')))\n\n"
  },
  {
   "title": "🔬 imagescaler Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 imagescaler Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(gitlab_workhorse_image_resize_duration_seconds_bucket{job=~\"gitlab-workhorse|gitlab-workhorse-web\", type=\"web\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "imagescaler RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_workhorse_image_resize_requests_total{job=~\"gitlab-workhorse|gitlab-workhorse-web\", type=\"web\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 puma Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 puma Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"web\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "puma Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:http_requests_total_rate5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",status=~\"5..\",type=\"web\"}\n)\n",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "puma RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  sli_aggregations:http_requests_total_rate5m{env=\"$environment\",environment=\"$environment\",job=\"gitlab-rails\",stage=\"$stage\",type=\"web\"}\n)\n",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🔬 workhorse Service Level Indicator Detail",
   "type": "row",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimated p95 workhorse Latency - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "s", "label": "Duration" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.950000,\n  sum by (le) (\n    rate(gitlab_workhorse_http_request_duration_seconds_bucket{env=\"$environment\",environment=\"$environment\",job=~\"gitlab-workhorse|gitlab-workhorse-web\",route!=\"^/([^/]+/){1,}[^/]+/uploads\\\\z\",route!=\"^/-/health$\",route!=\"^/-/(readiness|liveness)$\",route!=\"^/([^/]+/){1,}[^/]+\\\\.git/git-receive-pack\\\\z\",route!=\"^/([^/]+/){1,}[^/]+\\\\.git/git-upload-pack\\\\z\",route!=\"^/([^/]+/){1,}[^/]+\\\\.git/info/refs\\\\z\",route!=\"^/([^/]+/){1,}[^/]+\\\\.git/gitlab-lfs/objects/([0-9a-f]{64})/([0-9]+)\\\\z\",stage=\"$stage\",type=\"web\"}[$__interval])\n  )\n)\n",
       "legendFormat": "p95 overall"
      }
     ]
    },
    {
     "title": "workhorse Errors - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_workhorse_http_requests_total{job=~\"gitlab-workhorse|gitlab-workhorse-web\", type=\"web\", code=~\"^5.*\", route!=\"^/-/health$\", route!=\"^/-/(readiness|liveness)$\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "overall"
      }
     ]
    },
    {
     "title": "workhorse RPS - Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
     "yaxes": [
      { "format": "short", "label": "Requests per Second" }
     ],
     "targets": [
      {
       "expr": "sum by () (\n  rate(gitlab_workhorse_http_requests_total{job=~\"gitlab-workhorse|gitlab-workhorse-web\", type=\"web\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\"}[$__interval])\n)\n",
       "legendFormat": "overall"
      }
     ]
    }
   ]
  },
  {
   "title": "🖥️ Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU",
     "type": "graph",
     "description": "The amount of non-idle time consumed by nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "avg(instance:node_cpu_utilization:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Maximum Single Core Utilization",
     "type": "graph",
     "description": "The maximum utilization of a single core on each node. Lower is better",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(max(1 - rate(node_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\", mode=\"idle\"}[$__interval])) by (fqdn)\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Node Network Utilization",
     "type": "graph",
     "description": "Network utilization for nodes for this service",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "send {{ fqdn }}"
      },
      {
       "expr": "sum(rate(node_network_receive_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])) by (fqdn)\n",
       "legendFormat": "receive {{ fqdn }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "description": "Memory utilization. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation" }
     ],
     "targets": [
      {
       "expr": "clamp_min(clamp_max(instance:node_memory_utilization:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}\n,1),0)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read IOPs",
     "type": "graph",
     "description": "Disk Read IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_reads_completed_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write IOPs",
     "type": "graph",
     "description": "Disk Write IO operations per second. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ops", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_writes_completed_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Throughput",
     "type": "graph",
     "description": "Disk Read throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_read_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Throughput",
     "type": "graph",
     "description": "Disk Write throughput datarate. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "max(\n  rate(node_disk_written_bytes_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Read Total Time",
     "type": "graph",
     "description": "Total time spent in read operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_read_time_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "Disk Write Total Time",
     "type": "graph",
     "description": "Total time spent in write operations across all disks on the node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "sum(\n  rate(node_disk_write_time_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[$__interval])\n) by (fqdn)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "CPU Scheduling Waiting",
     "type": "graph",
     "description": "CPU scheduling waiting on the run queue, as a percentage of time. Aggregated to worst CPU per node. Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit", "label": "Total Time/s" }
     ],
     "targets": [
      {
       "expr": "max by (fqdn) (\n  rate(node_schedstat_waiting_seconds_total{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[5m])\n)\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg1 per core",
     "type": "graph",
     "description": "Loadavg (1 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short", "label": "loadavg1" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load1{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg5 per core",
     "type": "graph",
     "description": "Loadavg (5 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg5" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load5{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    },
    {
     "title": "loadavg15 per core",
     "type": "graph",
     "description": "Loadavg (15 minute) per core, below 1 is better.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short", "label": "loadavg15" }
     ],
     "targets": [
      {
       "expr": "avg by (environment, type, stage, fqdn) (node_load15{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"})\n/\ncount by (environment, type, stage, fqdn) (node_cpu_seconds_total{mode=\"idle\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"})\n",
       "legendFormat": "{{ fqdn }}"
      }
     ]
    }
   ]
  },
  {
   "title": "☸️ Kubernetes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 400 },
   "collapsed": true,
   "panels": [
    {
     "title": "web Deployment: CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_cpu_usage_seconds_total:labeled{\n      deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"web\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "web Deployment: Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  container_memory_working_set_bytes:labeled{\n    deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"web\"\n  }\n)\n",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "web Deployment: Network IO",
     "type": "graph",
     "description": "Network utilization",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "Bps", "label": "Network utilization" }
     ],
     "targets": [
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_transmit_bytes_total:labeled{\n      deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"web\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "send {{ cluster }}"
      },
      {
       "expr": "sum by(cluster) (\n  rate(\n    container_network_receive_bytes_total:labeled{\n      deployment=\"web\",env=\"$environment\",environment=\"$environment\",type=\"web\"\n    }[$__rate_interval]\n  )\n)\n",
       "legendFormat": "receive {{ cluster }}"
      }
     ]
    },
    {
     "title": "Node CPU Requests Utilization",
     "type": "graph",
     "description": "Ratio of requested CPU resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by memory requests already.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests_cpu_cores\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",type=\"web\",resource=\"cpu\"}\n",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Node Memory Requests Utilization",
     "type": "graph",
     "description": "Ratio of requested Memory resources from allocatable resources.\nIdeally we have requests utilization close to 100%. Values are\nbelow 100% typically because pods do not fit well on nodes or\nbecause we might be bound by CPU requests already.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (node) (\n  kube_pod_container_resource_requests_memory_bytes\n)\n/ on (node) group_left()\nkube_node_status_allocatable:labeled{env=\"$environment\",environment=\"$environment\",type=\"web\",resource=\"memory\"}\n",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  {
   "title": "🌡 Saturation Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 500 },
   "collapsed": true,
   "panels": [
    {
     "title": "kube_container_cpu component saturation: Kube Container CPU Utilization",
     "type": "graph",
     "description": "Kubernetes containers are allocated a share of CPU. When this is exhausted, the container may be thottled.\n Lower is better.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "yaxes": [
      { "format": "percentunit", "label": "Saturation %" }
     ],
     "targets": [
      {
       "expr": "clamp_min(\n  clamp_max(\n    max by(environment, tier, type, stage, pod, container) (\n  clamp_min(\n    clamp_max(\n      sum by (environment, tier, type, stage, pod, container) (\n        rate(container_cpu_usage_seconds_total:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}[5m])\n      )\n      /\n      sum by(environment, tier, type, stage, pod, container) (\n        container_spec_cpu_quota:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}\n        /\n        container_spec_cpu_period:labeled{container!=\"\", container!=\"POD\", env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\"}\n      )\n      ,\n      1)\n  ,\n  0)\n)\n\n  ,1)\n,0)\n",
       "legendFormat": "{{ pod }} {{ container }}"
      },
      {
       "expr": "clamp_min(\n  clamp_max(\n    max(\n      max_over_time(gitlab_component_saturation:ratio{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\", component=\"kube_container_cpu\"}[$__interval])\n    ) by (component)\n  ,1)\n,0)\n",
       "legendFormat": "aggregated {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile95_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\", component=\"kube_container_cpu\"}\n",
       "legendFormat": "95th quantile for week {{ component }}"
      },
      {
       "expr": "gitlab_component_saturation:ratio_quantile99_1w{env=\"$environment\",environment=\"$environment\",stage=\"$stage\",type=\"web\", component=\"kube_container_cpu\"}\n",
       "legendFormat": "99th quantile for week {{ component }}"
      },
      {
       "expr": "avg(slo:max:soft:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Soft SLO: {{ component }}"
      },
      {
       "expr": "avg(slo:max:hard:gitlab_component_saturation:ratio{component=\"kube_container_cpu\"}) by (component)\n",
       "legendFormat": "Hard SLO: {{ component }}"
      }
     ]
    }
   ]
  },
  { "title": "Workhorse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1000 } },
  {
   "title": "p50 Overall Latency Estimate",
   "type": "graph",
   "description": "p50 Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1001 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\"}\n  ) by (le))\n",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  {
   "title": "p90 Latency Estimate per Route",
   "type": "graph",
   "description": "90th percentile Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1001 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  histogram_quantile(\n    0.9,\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n        environment=\"$environment\",\n        type=\"web\",\n        stage=\"$stage\"}\n    ) by (route, le)),\n\"route\", \"none\", \"route\", \"\")\n",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  {
   "title": "p50 Latency Estimate per Route",
   "type": "graph",
   "description": "Median Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1011 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  histogram_quantile(\n    0.5,\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n        environment=\"$environment\",\n        type=\"web\",\n        stage=\"$stage\"}\n    ) by (route, le)),\n\"route\", \"none\", \"route\", \"\")\n",
     "legendFormat": "{{ method }} {{ route }}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "description": "Total Requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1011 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\",\n      le=\"+Inf\"}\n)\n",
     "legendFormat": "{{ code_class }}"
    }
   ]
  },
  {
   "title": "Requests by Status Class",
   "type": "graph",
   "description": "Requests by Status Class",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1021 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n          environment=\"$environment\",\n          type=\"web\",\n          stage=\"$stage\",\n          le=\"+Inf\"}\n    ) by (code),\n  \"code_class\", \"${1}XX\", \"code\", \"(.).*\")\n) by (code_class)\n",
     "legendFormat": "{{ code_class }}"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "graph",
   "description": "Requests by Status Code",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1021 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\",\n      le=\"+Inf\"}\n) by (code)\n",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Requests by Route",
   "type": "graph",
   "description": "Requests by Route",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1031 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    sum(\n      job:gitlab_workhorse_http_request_duration_seconds_bucket:rate1m{\n          environment=\"$environment\",\n          type=\"web\",\n          stage=\"$stage\",\n          le=\"+Inf\"}\n    ) by (route),\n  \"route\", \"none\", \"route\", \"\")\n) by (route)\n",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  { "title": "Rails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3000 } },
  {
   "title": "p95 Latency Estimate",
   "type": "graph",
   "description": "95th percentile Latency. Lower is better",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3001 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90,\n  sum(job_environment:gitlab_transaction_duration_seconds_bucket:rate5m{\n    environment=\"$environment\",\n    type=\"web\",\n    stage=\"$stage\"\n  }) by (le, job)\n)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Rails Total Time",
   "type": "graph",
   "description": "Seconds of Rails processing, per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3001 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job_environment:gitlab_transaction_duration_seconds_sum:rate1m{\n    environment=\"$environment\",\n    type=\"web\",\n    stage=\"$stage\"}\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Rails Queue Time",
   "type": "graph",
   "description": "Time spend waiting for a rails worker",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3011 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    gitlab_transaction_rails_queue_duration_total{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\"}\n      [$__interval]\n  )\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Total SQL Time",
   "type": "graph",
   "description": "Total seconds spent doing SQL processing, per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3011 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  job_environment:gitlab_sql_duration_seconds_bucket:rate1m{\n    environment=\"$environment\",\n    type=\"web\",\n    stage=\"$stage\"}\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "graph",
   "description": "Cache Operations per Second",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3021 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(\n    gitlab_cache_operations_total{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\"}[$__interval]\n  )\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "gitlab-rails Process restarts",
   "type": "graph",
   "description": "The number of times this process restarted in a given period, including children workers. Restarts are associated with poor client experience, so lower is better.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3021 },
   "yaxes": [
    { "format": "short", "label": "Process restarts" }
   ],
   "targets": [
    {
     "expr": "sum(\n  changes(\n    ruby_process_start_time_seconds{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\",\n      job=\"gitlab-rails\"\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "process restarts"
    }
   ]
  },
  {
   "title": "Database load balancer: average secondary connections per client",
   "type": "graph",
   "description": "This graph shows the average number of secondary database connections\n        per process. A value of zero indicates that the secondary replicas are unreachable.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3031 },
   "yaxes": [
    { "format": "short", "label": "Average connections" }
   ],
   "targets": [
    {
     "expr": "avg(\n  avg_over_time(\n    db_load_balancing_hosts{\n      environment=\"$environment\",\n      type=\"web\",\n      stage=\"$stage\"}[$__interval]\n  )\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "puma parent processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU Time",
     "type": "graph",
     "description": "Seconds of CPU time for the named process group, per second",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  rate(\n    namedprocess_namegroup_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",groupname=\"puma_parent\",stage=\"$stage\",type=\"web\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "puma_parent: Open File Descriptors",
     "type": "graph",
     "description": "Maximum number of open file descriptors per host",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by(fqdn) (\n    namedprocess_namegroup_open_filedesc{env=\"$environment\",environment=\"$environment\",groupname=\"puma_parent\",stage=\"$stage\",type=\"web\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "puma_parent: Number of Processes",
     "type": "graph",
     "description": "Number of processes in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  avg_over_time(namedprocess_namegroup_num_procs{env=\"$environment\",environment=\"$environment\",groupname=\"puma_parent\",stage=\"$stage\",type=\"web\"}[$__interval])\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "puma_parent: Number of Threads",
     "type": "graph",
     "description": "Number of threads in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_num_threads{env=\"$environment\",environment=\"$environment\",groupname=\"puma_parent\",stage=\"$stage\",type=\"web\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "puma_parent: RSS Memory Usage",
     "type": "graph",
     "description": "Resident Memory usage for named process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_memory_bytes{memtype=\"resident\", env=\"$environment\",environment=\"$environment\",groupname=\"puma_parent\",stage=\"$stage\",type=\"web\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "puma worker processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5000 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU Time",
     "type": "graph",
     "description": "Seconds of CPU time for the named process group, per second",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  rate(\n    namedprocess_namegroup_cpu_seconds_total{env=\"$environment\",environment=\"$environment\",groupname=\"puma_worker\",stage=\"$stage\",type=\"web\"}[$__interval]\n  )\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "puma_worker: Open File Descriptors",
     "type": "graph",
     "description": "Maximum number of open file descriptors per host",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by(fqdn) (\n    namedprocess_namegroup_open_filedesc{env=\"$environment\",environment=\"$environment\",groupname=\"puma_worker\",stage=\"$stage\",type=\"web\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "puma_worker: Number of Processes",
     "type": "graph",
     "description": "Number of processes in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  avg_over_time(namedprocess_namegroup_num_procs{env=\"$environment\",environment=\"$environment\",groupname=\"puma_worker\",stage=\"$stage\",type=\"web\"}[$__interval])\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "puma_worker: Number of Threads",
     "type": "graph",
     "description": "Number of threads in the process group",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_num_threads{env=\"$environment\",environment=\"$environment\",groupname=\"puma_worker\",stage=\"$stage\",type=\"web\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    },
    {
     "title": "puma_worker: RSS Memory Usage",
     "type": "graph",
     "description": "Resident Memory usage for named process group",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(fqdn) (\n  namedprocess_namegroup_memory_bytes{memtype=\"resident\", env=\"$environment\",environment=\"$environment\",groupname=\"puma_worker\",stage=\"$stage\",type=\"web\"}\n)\n",
       "legendFormat": "{{ fqdn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🗺️ System Diagrams",
   "type": "row",
   "gridPos": { "x": 0, "y": 100010 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Diagram (Keyed by Error Rates)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "content": "graph TD\n  subgraph sv\n  web\nend\n\n\n  \n",
     "targets": [
      {
       "expr": "clamp_max(\n  max_over_time(gitlab_service_errors:ratio_5m{environment=\"$environment\",stage=\"$stage\"}[$__range])\n,\n  1\n)\n",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "System Diagram (Keyed by Apdex/Latency Scores)",
     "type": "jdbranham-diagram-panel",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
     "format": "percentunit",
     "valueName": "current",
     "content": "graph TD\n  subgraph sv\n  web\nend\n\n\n  \n",
     "targets": [
      {
       "expr": "min_over_time(gitlab_service_apdex:ratio_5m{environment=\"$environment\",stage=\"$stage\"}[$__range])\n",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110000 },
   "content": "Made with ❤️ and [Grafonnet](https://github.com/grafana/grafonnet-lib). [Contribute to this dashboard on GitLab.com](https://gitlab.com/gitlab-com/runbooks/blob/master/dashboards/)\n"
  }
 ]
}