{
 "title": "Wiz Sensor",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"wiz-sensor\"},env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(2,rate(container_cpu_usage_seconds_total{env='$environment', container='wiz-sensor'}[$__rate_interval]))",
     "legendFormat": "{cluster=\"{{cluster}}\",pod={{pod}}}"
    }
   ]
  },
  {
   "title": "OOM Kills Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,container_oom_events_total{env='$environment', container='wiz-sensor'})",
     "legendFormat": "{cluster=\"{{cluster}}\", pod={{pod}}}"
    }
   ]
  },
  {
   "title": "Top Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10,container_memory_usage_bytes{env='$environment', container='wiz-sensor'})",
     "legendFormat": "{cluster=\"{{cluster}}\",pod={{pod}}}"
    }
   ]
  }
 ]
}