{
 "title": "Wiz Sensor Kubernetes Pods",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"wiz-sensor\"},env)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"wiz-sensor\", env=\"$environment\"},cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"wiz-sensor\", env=\"$environment\", cluster=\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Wiz Sensor: Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{env='$environment', container='wiz-sensor',cluster=\"$cluster\",pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Wiz Sensor: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    container_network_transmit_bytes_total{\n      env=\"$environment\",namespace=\"wiz-sensor\",cluster=\"$cluster\",pod=\"$pod\"\n    }[$__rate_interval]\n  ))\n",
     "legendFormat": "send {{ cluster }} {{ pod }}"
    },
    {
     "expr": "sum by (pod) (\n  rate(\n    container_network_receive_bytes_total{\n      env=\"$environment\",namespace=\"wiz-sensor\",cluster=\"$cluster\",pod=\"$pod\"\n    }[$__rate_interval]\n  ))\n",
     "legendFormat": "receive {{ cluster }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Wiz Sensor: Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{env=\"$environment\",namespace=\"wiz-sensor\",cluster=\"$cluster\",pod=\"$pod\",container=\"wiz-sensor\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Wiz Sensor: Read IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_fs_reads_total{env=\"$environment\",container=\"wiz-sensor\",cluster=\"$cluster\",pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Wiz Sensor: Write IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_fs_writes_total{env=\"$environment\",container=\"wiz-sensor\",cluster=\"$cluster\",pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}