{
 "title": "Wiz Sensor Linux Hosts",
 "description": "Wiz Sensor Host Stats",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(namedprocess_namegroup_memory_bytes{groupname=\"wiz-sensor\"},env)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total{groupname=\"wiz-sensor\", env=\"$environment\"},fqdn)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "wiz-sensor fleet CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"wiz-sensor\",environment=\"$environment\",mode=\"user\",fqdn=\"$node\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "avg by (env) (rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"wiz-sensor\",environment=\"$environment\",mode=\"system\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "avg by (env) (rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"wiz-sensor\",environment=\"$environment\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "CPU User Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"wiz-sensor\",environment=\"$environment\",mode=\"user\",fqdn=\"$node\"}[1h])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "CPU System Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"wiz-sensor\",environment=\"$environment\",mode=\"system\",fqdn=\"$node\"}[1h])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Wiz Sensor Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=\"wiz-sensor\",memtype=\"resident\",environment=\"$environment\",fqdn=\"$node\"}",
     "legendFormat": "Wiz Sensor Memory"
    }
   ]
  },
  {
   "title": "Write IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{groupname=\"wiz-sensor\",environment=\"$environment\",fqdn=\"$node\"}[2h])",
     "legendFormat": "{{fqdn}}"
    }
   ]
  },
  {
   "title": "Read IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(5,rate(namedprocess_namegroup_read_bytes_total{groupname=\"wiz-sensor\",environment=\"$environment\",fqdn=\"$node\"}[2h]))",
     "legendFormat": "{{fqdn}}"
    }
   ]
  }
 ]
}