{
 "title": "Wiz Sensor Global Stats",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"wiz-sensor\"},env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Wiz Sensor: Top Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,rate(container_cpu_usage_seconds_total{env='$environment', container='wiz-sensor'}[$__rate_interval]))",
     "legendFormat": "{cluster=\"{{cluster}}\",pod={{pod}}}"
    }
   ]
  },
  {
   "title": "Wiz Sensor: Top Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum by(pod) (\n  rate(\n    container_network_transmit_bytes_total{\n      env=\"$environment\",namespace=\"wiz-sensor\"\n    }[$__rate_interval]\n  )\n))\n",
     "legendFormat": "send {{ cluster }} {{ pod }}"
    },
    {
     "expr": "topk(5,\n  rate(\n    container_network_receive_bytes_total{\n      env=\"$environment\",namespace=\"wiz-sensor\"\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "receive {{ cluster }} {{ pod }}"
    }
   ]
  },
  {
   "title": "Wiz Sensor: OOM Kills Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,container_oom_events_total{env='$environment', container='wiz-sensor'})",
     "legendFormat": "{cluster=\"{{cluster}}\", pod={{pod}}}"
    }
   ]
  },
  {
   "title": "Wiz Sensor: Top Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,container_memory_usage_bytes{env='$environment', container='wiz-sensor'})",
     "legendFormat": "{cluster=\"{{cluster}}\",pod={{pod}}}"
    }
   ]
  }
 ]
}