{
 "title": "Wiz Sensor Kubernetes",
 "tags": [ "unmanaged" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(container_memory_usage_bytes{container=\"wiz-sensor\"},env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Wiz Sensor: Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (cluster, pod) (topk(2,rate(container_cpu_usage_seconds_total{env='$environment', container='wiz-sensor'}[$__rate_interval])))",
     "legendFormat": "{{ cluster }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Wiz Sensor: Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster,pod) (topk(5,container_memory_usage_bytes{env=\"$environment\",namespace=\"wiz-sensor\",container=\"wiz-sensor\"}))",
     "legendFormat": "{{ cluster - pod }}"
    }
   ]
  },
  {
   "title": "OOM Kills",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,(container_oom_events_total{env='$environment', container='wiz-sensor'}))",
     "legendFormat": "{cluster=\"{{cluster}}\", pod={{pod}}}"
    }
   ]
  },
  {
   "title": "Wiz Sensor: Read IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod) (rate(container_fs_reads_total{env=\"$environment\",container=\"wiz-sensor\"}[$__rate_interval]))",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "Wiz Sensor: Write IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (cluster, pod) (rate(container_fs_writes_total{env=\"$environment\",container=\"wiz-sensor\"}[$__rate_interval]))",
     "legendFormat": "{{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "Wiz Sensor: Network IO",
   "type": "graph",
   "description": "Network utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Network utilization" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster,pod) (topk(5,\n  rate(\n    container_network_transmit_bytes_total{\n      env=\"$environment\",namespace=\"wiz-sensor\"\n    }[$__rate_interval]\n  )))\n",
     "legendFormat": "send {{ cluster }} {{ pod }}"
    },
    {
     "expr": "sum by (cluster,pod) (topk(5,\n  rate(\n    container_network_receive_bytes_total{\n      env=\"$environment\",namespace=\"wiz-sensor\"\n    }[$__rate_interval]\n  )))\n",
     "legendFormat": "receive {{ cluster }} {{ pod }}"
    }
   ]
  }
 ]
}