{
 "title": "Workhorse Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(gitlab_workhorse_http_requests_total, environment)"
   },
   { "name": "type", "query": "web,api,git" }
  ]
 },
 "panels": [
  {
   "title": "Combined Error + Latency Apdex Scores",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"$env\", type=\"web\", le=\"1\", code=~\"^[23].*\"}[5m])) \n+\n  sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"$env\", type=\"web\", le=\"10\", code=~\"^[23].*\"}[5m])) \n) \n/ \n2 / sum(rate(gitlab_workhorse_http_request_duration_seconds_count{environment=\"$env\", type=\"web\", code=~\"^[235].*\"}[5m])) ",
     "legendFormat": "Web - Target 1s, Acceptable 10s"
    },
    {
     "expr": "(\n  sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"$env\", type=\"api\", le=\"10\", code=~\"^[23].*\", route!=\"^/api/v4/jobs/request\\\\z\"}[5m])) \n+\n  sum(rate(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"$env\", type=\"api\", le=\"30\", code=~\"^[23].*\", route!=\"^/api/v4/jobs/request\\\\z\"}[5m])) \n) \n/ \n2 / sum(rate(gitlab_workhorse_http_request_duration_seconds_count{environment=\"$env\", type=\"api\", code=~\"^[235].*\", route!=\"^/api/v4/jobs/request\\\\z\"}[5m])) ",
     "legendFormat": "API - Target 10s, Acceptable 30s"
    }
   ]
  },
  { "title": "HTTP Status Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Workhorse Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit", "label": "Successful Requests" }
   ],
   "targets": [
    {
     "expr": "1 -\n(\n  sum(rate(gitlab_workhorse_http_requests_total{environment=\"$env\", code=~\"^5.*\"}[$__interval])) by (fqdn) \n  /  \n  sum(rate(gitlab_workhorse_http_requests_total{environment=\"$env\"}[$__interval])) by (fqdn) \n)",
     "legendFormat": "{{ fqdn }}"
    }
   ]
  },
  {
   "title": "$type: All HTTP Responses per Backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "repeat": "type",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nsum without(fqdn, instance, code) (\n  label_replace(\n    label_replace(\n      rate(\n        gitlab_workhorse_http_requests_total{environment=\"$env\", type=\"$type\"}[$__interval]\n      ), \n      \"class\", \"${1}XX\", \"code\", \"^(.).*\"\n    ),\n    \"route\", \"default\", \"route\", \"^$\"\n  )\n)\n",
     "legendFormat": "{{ class }}: {{ method  }} {{ route }}"
    }
   ]
  },
  { "title": "5xx Server Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "$type: 5xx HTTP Responses per Backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "repeat": "type",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nsum without(fqdn, instance) (\n  label_replace(\n    rate(\n      gitlab_workhorse_http_requests_total{environment=\"$env\", type=\"$type\", code=~\"^5.*\"}[$__interval]\n    ),\n    \"route\", \"default\", \"route\", \"^$\"\n  )\n)\n",
     "legendFormat": "{{ code }}: {{ method  }} {{ route }}"
    }
   ]
  },
  { "title": "Inflight Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "$type: Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "repeat": "type",
   "yaxes": [
    { "format": "short", "label": "Inflight Requests" }
   ],
   "targets": [
    {
     "expr": "gitlab_workhorse_http_in_flight_requests{environment=\"$env\", type=\"$type\"}",
     "legendFormat": "{{ fqdn }} "
    }
   ]
  },
  { "title": "Request Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "$type: p99 Response Times (2XX, 5XX responses)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "repeat": "type",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(\n    label_replace(\n      rate(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"$env\", type=\"$type\", code=~\"^[25].*\", method!=\"head\", route!=\"^/api/v4/jobs/request\\\\z\"}[$__interval]),\n      \"route\", \"default\", \"route\", \"^$\"\n    )\n  ) by (route, le)\n)\n",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  { "title": "Request Payload Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "$type: p95 Request Size (2xx)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "repeat": "type",
   "yaxes": [
    { "format": "bytes", "label": "Request Size" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_workhorse_http_request_size_bytes_bucket{environment=\"$env\", type=\"$type\", code=~\"^2.*\"}[5m])) by (le, method))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "$type: p99 Time-to-First-Byte",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "repeat": "type",
   "yaxes": [
    { "format": "dtdurations", "label": "Time to First Byte" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(\n    label_replace(\n      rate(gitlab_workhorse_http_time_to_write_header_seconds_bucket{environment=\"$env\", type=\"$type\", code=~\"^2.*\"}[$__interval]),\n      \"route\", \"default\", \"route\", \"^$\"\n    )\n  ) by (route, le)\n)\n",
     "legendFormat": "{{ route }}"
    }
   ]
  }
 ]
}