{
 "title": "Workhorse memory bloat on API nodes",
 "time": { "from": "2020-08-27T15:00:00.000Z", "to": "2020-08-27T22:00:00.000Z" },
 "panels": [
  {
   "title": "Rate of HTTP 5xx errors seen by HAProxy from API hosts",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(backend_code:haproxy_server_http_responses_total:irate1m{env=\"gprd\",monitor=\"default\",code=\"5xx\",backend=\"api\"}[$__interval])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Workhorse memory alloc > 10 GB on API nodes",
   "type": "graph",
   "description": "Normally workhorse has a modest used memory footprint of roughly 100 MB, but under some conditions it spikes enormously to 10-50 GB.  This graph helps find those usage spikes.",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"gitlab-workhorse-api\", type=\"api\", environment=\"gprd\"} > 10*1024^3",
     "legendFormat": "{{fqdn}}"
    },
    {}
   ]
  },
  {
   "title": "Used vs Total heap size - api-06",
   "type": "graph",
   "description": "From the go runtime's perspective, compare used vs total size of the heap.  The total heap size (\"go_memstats_heap_sys_bytes\") is typically most of the memory allocated by the OS to this process, and golang's internal heap allocator may retain that memory after it is reclaimed by the garbage collector, rather than release it back to the OS.",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"gitlab-workhorse-api\", type=\"api\", environment=\"gprd\", fqdn=\"api-06-sv-gprd.c.gitlab-production.internal\"}",
     "legendFormat": "used heap"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"gitlab-workhorse-api\", type=\"api\", environment=\"gprd\", fqdn=\"api-06-sv-gprd.c.gitlab-production.internal\"}",
     "legendFormat": "total heap"
    }
   ]
  },
  {
   "title": "GC duration and age - api-06",
   "type": "graph",
   "description": "I may be misinterpreting these metrics.\n\nFrom the prometheus /metrics endpoint:\n* go_gc_duration_seconds: A summary of the GC invocation durations.\n* go_memstats_last_gc_time_seconds: Number of seconds since 1970 of last garbage collection.",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"gitlab-workhorse-api\", type=\"api\", environment=\"gprd\", fqdn=\"api-06-sv-gprd.c.gitlab-production.internal\",quantile=\"1\"}",
     "legendFormat": "max GC duration during interval"
    },
    {
     "expr": "time() - go_memstats_last_gc_time_seconds{job=\"gitlab-workhorse-api\", type=\"api\", environment=\"gprd\", fqdn=\"api-06-sv-gprd.c.gitlab-production.internal\"}",
     "legendFormat": "seconds since last GC"
    }
   ]
  }
 ]
}