{
 "title": "Workhorse Overview [deprecated]",
 "tags": [
  "unmanaged",
  "deprecated"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(gitlab_workhorse_http_requests_total, environment)"
   },
   { "name": "type", "query": "web,api,git" }
  ]
 },
 "panels": [
  {
   "title": "Deprecation Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "content": "![](https://media.giphy.com/media/l0HlKrB02QY0f1mbm/giphy.gif)"
  },
  {
   "title": "Deprecation  Notice",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 0 },
   "content": "# Deprecated ⚠️⚠️⚠️⚠️⚠️\n\nThis dashboard is deprecated, please consider switching over to the new service based dashboards:\n\n* [api](/d/api-main/api-overview)\n* [web](/d/git-main/git-overview)\n* [git](/d/web-main/web-overview)\n\n\n"
  },
  {
   "title": "Combined Error + Latency Apdex Scores",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio{environment=\"$env\",type=~\"$type\"}[$__interval])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg_over_time(gitlab_component_apdex:ratio{environment=\"$env\",type=~\"$type\"}[$__interval] offset 7d)",
     "legendFormat": "{{type}} - last week"
    }
   ]
  },
  { "title": "HTTP Status Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Workhorse Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit", "label": "Successful Requests" }
   ],
   "targets": [
    {
     "expr": "1 -\n(\n  sum(avg_over_time(code_method:gitlab_workhorse_http_requests_total:rate1m{environment=\"$env\", type=~\"$type\", code=~\"^5.*\"}[$__interval])) by (type) \n  /  \n  sum(avg_over_time(code_method:gitlab_workhorse_http_requests_total:rate1m{environment=\"$env\", type=~\"$type\"}[$__interval])) by (type) \n)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "$type: All HTTP Responses per Backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "repeat": "type",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nsum without(code) (\n  label_replace(\n    label_replace(\n      avg_over_time(\n        code_method:gitlab_workhorse_http_requests_total:rate1m{environment=\"$env\", type=\"$type\"}[$__interval]\n      ), \n      \"class\", \"${1}XX\", \"code\", \"^(.).*\"\n    ),\n    \"route\", \"default\", \"route\", \"^$\"\n  )\n)\n",
     "legendFormat": "{{ class }}: {{ method  }} {{ route }}"
    }
   ]
  },
  { "title": "5xx Server Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "$type: 5xx HTTP Responses per Backend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "repeat": "type",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nsum without(fqdn, instance) (\n  label_replace(\n    avg_over_time(\n      code_method:gitlab_workhorse_http_requests_total:rate1m{environment=\"$env\", type=\"$type\", code=~\"^5.*\"}[$__interval]\n    ),\n    \"route\", \"default\", \"route\", \"^$\"\n  )\n)\n",
     "legendFormat": "{{ code }}: {{ method  }} {{ route }}"
    }
   ]
  },
  { "title": "Inflight Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "$type: Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "repeat": "type",
   "yaxes": [
    { "format": "short", "label": "Inflight Requests" }
   ],
   "targets": [
    {
     "expr": "sum without (fqdn,instance) (gitlab_workhorse_http_in_flight_requests{environment=\"$env\", type=\"$type\"})",
     "legendFormat": "{{type}} - {{ stage }}"
    }
   ]
  },
  { "title": "Request Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "$type: p99 Response Times (2XX, 5XX responses)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "repeat": "type",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(\n    label_replace(\n      rate(gitlab_workhorse_http_request_duration_seconds_bucket{environment=\"$env\", type=\"$type\", code=~\"^[25].*\", method!=\"head\", route!=\"^/api/v4/jobs/request\\\\z\"}[$__interval]),\n      \"route\", \"default\", \"route\", \"^$\"\n    )\n  ) by (route, le)\n)\n",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  { "title": "Request Payload Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "$type: p95 Request Size (2xx)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "repeat": "type",
   "yaxes": [
    { "format": "bytes", "label": "Request Size" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitlab_workhorse_http_request_size_bytes_bucket{environment=\"$env\", type=\"$type\", code=~\"2.*\"}[$__interval])) by (le, method))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "$type: p99 Time-to-First-Byte",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "repeat": "type",
   "yaxes": [
    { "format": "dtdurations", "label": "Time to First Byte" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(\n    label_replace(\n      rate(gitlab_workhorse_http_time_to_write_header_seconds_bucket{environment=\"$env\", type=\"$type\", code=~\"2.*\"}[$__interval]),\n      \"route\", \"default\", \"route\", \"^$\"\n    )\n  ) by (route, le)\n)\n",
     "legendFormat": "{{ route }}"
    }
   ]
  }
 ]
}